### ISSUE TITLE
Vulkan capture shows last input vertex as "---" if using non-standard offset

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#1007]
## Description

I've attached two traces for NVIDIA and AMD. We are using a vertex array with an odd offset (1/5) and a simple stride. The last vertex in the draw call is showing up as "---" and generating an out of range value in RenderDoc. Rendering works on NVIDIA and fails on AMD. This may be an AMD bug that I was investigating.

## Repro steps

Please refer to the traces. The draw call is in event 18. Please look at the mesh output for the position coordinate.

## Environment

* RenderDoc build: nightly
* Operating System: Windows 10
* API: Vulkan

I've attached a screenshot.

[offset_vertex_bug.zip](https://github.com/baldurk/renderdoc/files/2072820/offset_vertex_bug.zip)
![capture](https://user-images.githubusercontent.com/541607/40983470-b6484ade-68ad-11e8-8f38-629c323cf1c4.JPG)

**Comment by baldurk** [comment]
Looks like this is a simple bug on my side - I'm not accounting for the vertex attribute offsets poking outside of the strided vertex buffer size. The internal calculation I do is to find the maximum index, then fetch `(maxIndex + 1) * vertexBufferStride` bytes of data. In your case however your last vertex goes outside that range - because the attribute offset is 5 bytes and the vertex data is 16 bytes, with a stride of 16 bytes as well, so you read 5 more bytes past the end of the data and I display that as `---`.

I can easily fix this but I figured I'd explain it since there's a good chance this is the problem on AMD too. I don't see anything illegal about this, although it's odd to have a misaligned offset and poke outside the strided element. There is language that would prevent this kind of behaviour if it were near the end of the buffer, but your buffer is much larger giving plenty space, so it might be a bug on AMD's side.

**Comment by null77** [comment]
Thanks! It turns out this might be invalid Vulkan usage. At least on some platforms. But figured you might want to fix the off by one error anyway.

**Comment by baldurk** [comment]
Thanks! Should be fixed with that commit.
