### ISSUE TITLE
[OpenGL 4.4] Debugging issue

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#1015]
## Description

I have a glMultiDrawArraysIndirect call that I want to capture, but when I click 'timings' or I click the MDAI call, RenderDoc crashes. Is this because MDI isn't supported with RenderDoc or has that already been fixed in an update? I tried getting the latest build but it wasn't working.

## Repro steps

https://ufile.io/thgih if this file is opened and you click on the multi draw indirect or timer button, RenderDoc crashes.

## Environment

RenderDoc build: https://github.com/baldurk/renderdoc/commit/569f11b7577ba77458f41d81116b545cc82971c6
Operating System: Windows 10 x64
API: OpenGL 4.4

**Comment by baldurk** [comment]
Looking at this, the crash seems to be caused by having no vertex data bound at the point of glMultiDrawElementsIndirect. The vertex array object bound just before the draw isn't initialised properly, but from the capture file itself I can't tell if this was a bug during capture that caused mismatched tracing, or if it was a bug in the program itself.

Are you able to share the program with me (here or privately)? If not, would you be willing to compile renderdoc locally and run it with some extra debug logging to track down the problem?

**Comment by Nielsbishere** [comment]
You're right, I forgot to bind the VBO to the correct slot and I don't have an IBO so I was using the wrong funtion. Shouldn't there be a safeguard so that it doesn't crash though, or at least a popup about that there was no element/vertex buffer bound when you select it? That would be pretty useful.

Thank you for helping,
Nielsbishere

**Comment by baldurk** [comment]
Glad you got it working!

RenderDoc isn't intended for debugging invalid API use, and every API has built-in debugging validation to catch this kind of thing. It's not worth duplicating all of that that functionality in this tool, since there are many ways to call API functions in invalid ways and it's not practical to detect and warn about all of them, especially across 4 or more APIs.

**Comment by Nielsbishere** [comment]
Okay fair enough
