### ISSUE TITLE
Why exchange double and float in “DoSerialise：gl_program_iterate.cpp”

### ISSUE THREAD

**Issue by letmegocc** [baldurk/renderdoc#1019]
## Description
This code ：in file“gl_program_iterate.cpp” line 250
  if(baseType == VarType::Double){
	  ser.Serialise("data", fv, elemCount, SerialiserFlags::NoFlags);
    }
  else if(baseType == VarType::Float){
	  ser.Serialise("data", dv, elemCount, SerialiserFlags::NoFlags);
    }

my issue is why fv and dv exchange，and I modify it as follow   
  if(baseType == VarType::Double){
	  ser.Serialise("data", dv, elemCount, SerialiserFlags::NoFlags);
    }
  else if(baseType == VarType::Float){
	  ser.Serialise("data", fv, elemCount, SerialiserFlags::NoFlags);
    }
But，the following mistakes happend：
     serialiser.h(1603) - Error   - Reading invalid array or byte buffer - 6879078459457404928 larger than total stream size 203392.

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* API: e.g. Vulkan, D3D11, OpenGL, etc

**Comment by baldurk** [comment]
As to why - there's no reason, this looks like just a bug caused by copy-pasting or a typo. Thanks for finding it.

The error you ran into is the reason why it's a little difficult to fix - captures already made with the old code will have a particular amount of data, specifically for any float variable it will have N doubles. If you change that to read only N floats, you're reading half the data, and then whatever is next serialised will read the incorrect data because it reads out of the second half of the 'float' data instead of whatever it should be reading after that.

Fortunately because data is read into and out of the values as a union, for the float case this will work fine just serialising garbage after the real data. It will only break for double uniforms since it won't serialise enough, and they are pretty rare so the impact of the bug is small.

I'll fix this, but it will need a backwards compatibility check to continue serialising the old way whenever it encounters a capture made before the fix.

**Comment by baldurk** [comment]
I've fixed this now in a backwards-compatible way.

**Comment by z00318884** [comment]
I also have this problem. In export xml ,chunk id =3, chunk child type=9(program),ProgramUniformValue  typename also have "double" ,<float typename="double" width="8">5.1881901305002474e-315</float>.
But in fact, it used float. And it was read from GPU in file“gl_program_iterate.cpp"   425 lines as gl.glGetUniformfv(progSrc, srcLocation, fv); I print it but not above in xml.so in xml data is wrong?

**Comment by baldurk** [comment]
It sounds like you're describing the original bug report? The XML export is just a representation of the serialised data, so it has the exact same bug. Any captures made after the fix a couple of days ago should have the correct data type, but old captures need to be serialised the same way for backwards compatibility.

**Comment by z00318884** [comment]
I've updated code. on mostly app it is ok.But on GFXBench APP，it also have this problem。can you check it？

**Comment by baldurk** [comment]
The fix is not application specific, GFXBench works fine for me. It sounds like you're compiling the code yourself - make sure you have rebuilt everything, GFXBench is a 32-bit application so if you didn't recompile the 32-bit version of RenderDoc it will create old broken captures, even if it's loaded on a 64-bit version of the UI.

You can check by seeing which path the code goes in `gl_program_iterate.cpp`.
