### ISSUE TITLE
Find Event should search from current event onwards

### ISSUE THREAD

**Issue by vaspoul** [baldurk/renderdoc#1030]
We output PIX labels with material names to make it easier to locate. Each material name may appear multiple times in a frame (e.g. z prepass, g buffer, etc). When doing a Find Event, it currently starts finding from the top. It would be useful if it could start looking from the event that is currently selected.

**Comment by baldurk** [comment]
This should be the current behaviour. The code searches forward or backwards from the current eventId since then it also supports incremental find without any special casing:

https://github.com/baldurk/renderdoc/blob/9c9e61a95e408196f9348a661474521161e8f537/qrenderdoc/Windows/EventBrowser.cpp#L1282-L1289

That's the behaviour that I see if I search. Can you give more details about what's going wrong in your case? Does it search from the top only when you make a new search, and incremental search works? or is incremental search not working either?

![findforward](https://user-images.githubusercontent.com/661798/42327575-f7bdf540-8063-11e8-8e4d-614d01aeedf1.gif)

**Comment by vaspoul** [comment]
My repro steps are:

- do a capture. 
Capture contains labels 'Z PrePass' and 'GBuffer'. Within each of these there are one or more entries of a material name (say 'branches').

- type branches on search box (don't click find yet)

- click on GBuffer event

- click on right arrow on the search toolbar.

- it finds the first entry inside the Z PrePass group.



HOWEVER, if I click on an event after the fist occurrence inside ZPrePass, then it correctly finds the second occurrence.

Does it matter if the groups are expanded?

**Comment by vaspoul** [comment]
Ah...I may have something.

It looks like it does a search *after* the event/element you have currently selected.

So in my case I have:

Frame
---- Z PrePass
-------- foo
-------- bar
-------- branches
-------- stuff
---- GBuffer
-------- foo
-------- bar
-------- branches
-------- stuff
---- UI

Everything is collapsed to start with. I want to find the entry inside GBuffer, so I click on GBuffer and hit find. I think it wraps around and finds the first entry inside the Z PrePass group.

If I click on the ZPrePass group and click find, then it finds the first entry inside the GBuffer group.

**Comment by baldurk** [comment]
I think I understand now. When you click on GBuffer, the 'current event' is considered to be the very last child - i.e. the last child in "stuff" in your example. So when you search, it searches forward from the very end of the GBuffer because that's the 'current' event.

This is intuitive for most stuff while browsing the frame because you want to see the contents & state reflected _after_ everything in the GBuffer region has happened - the same as when you select a draw you see the contents & state reflected _after_ the draw. It's not intuitive for search though where your mental model is more like you're selecting the whole thing and you have a virtual cursor at the start of the GBuffer pass.

Fortunately there's already a concept of a selected event vs the current one - so e.g. the API inspector shows API calls leading up to the start of the GBuffer pass when selecting it, even if the rest of the UI is showing state at the end of it. I think what I should do is change the start of the find to begin from this selected event, then I think it should behave as you expect.

**Comment by baldurk** [comment]
With that commit it *should* now behave as expected. Let me know if there's still some weirdness.
