### ISSUE TITLE
Add marker region 'path' to current event in event browser

### ISSUE THREAD

**Issue by vaspoul** [baldurk/renderdoc#1031]
We use PIX labels to organize the events in a single frame (e.g. Z PrePass, GBuffer, Alpha, etc). These can get quite deep/nested.

It would be useful if we could see a 'path' for the event currently selected, e.g.

Camera 1\3D Stage\GBuffer\TreeBark Material

It would be extra nice if clicking on any of these would take you to the beginning of that section.
(think folders in Windows Explorer).

**Comment by baldurk** [comment]
This should be feasible, I already do similar things in the pipeline state export or pixel history. Are you only wanting explicit marker _regions_, or do you also want e.g. the last _label_ that happened? In PIX terms this is the difference between `BeginEvent` / `EndEvent` and `SetMarker` respectively.

One issue is horizontal space - windows explorer is typically a lot wider than the event browser is. What behaviour would you expect when the path is wider than can be displayed?

Windows explorer elides from the start so only the last items that fit will be displayed, but I'm not sure that's necessarily what you want in frame browsing, so perhaps it should elide middle items? Or should it try to elide items individually to make space, so e.g. in your example it might squeeze down to "Ca\3D\GB\TreeBark Material" to give as much context as possible without losing levels in the hierarchy early?

**Comment by vaspoul** [comment]
I'm personally interested in the BeginEvent/EndEvent labels because that's the ones that make more sense to use when trying to identify a portion/region of the frame.

You're right about the collapsing behaviour and not having enough space. Would a scroll behaviour be suitable, i.e. display as many labels as you can in full size, but the user can scroll left/right to see a different portion.

**Comment by baldurk** [comment]
I think having a scrollbar for a small single-line element like that wouldn't be very nice, and it would be annoying to combine it with the horizontal scroll for the main panel.

You could maybe mimic windows explorer by having it change to a textbox when you click, that lets you browse left and right the same as any text edit field with the cursor. However that strongly implies that it's editable and can type any 'address', and I _really_ don't want to allow that as it's a whole different can of worms.

I'm leaning towards thinking that removing items from the middle of the path is probably the best option, then just hard truncating from the beginning. Users can always resize it larger if they want to see more of the path. It can be iterated on once the feature is implemented though, rather than bikeshedding right now :smile: .

**Comment by vaspoul** [comment]
Agreed! even just a normal string, not even clickable, would be useful.

**Comment by baldurk** [comment]
That commit adds breadcrumbs for marker regions, as part of a larger refactor of the event browser. Each marker has a drop-down menus at each stage to go to neighbours. When the path is too long it's elided in the middle and there's a `...` button which allows stepping back to any of those omitted markers.

![image](https://user-images.githubusercontent.com/661798/124173375-de0ec880-daa2-11eb-8aa3-ac7cda492f88.png)
