### ISSUE TITLE
Vulkan pure offscreen rendering: what to pass as `dev` in StartFrame?

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#1032]
This is a follow-up question to closed issue #608

I have an offscreen Vulkan application, which I have instrumented using: 

- StartFrameCapture(null, null)
- EndFrameCapture(null, null)

However this sporadically crashes, from what I can see `RenderDoc::MatchFrameCapturer` picks one of 2 elements `m_DeviceFrameCapturers` - where the sometimes picked element does not seem to correspond to valid device. 

So I have a question: 

To avoid above, what should I pass to `StartFrameCapture` as `dev` to identify my current VkDevice?

**Comment by ghost** [comment]
After some some pointer chasing, it seems it may be just VkInstance dereferenced once: 
`*(void**)VkInstance`

Am I right? Is this documented somewhere?

**Comment by baldurk** [comment]
I'd like to understand the bug here. There shouldn't be any invalid frame capturers in `m_DeviceFrameCapturers`, and in a typical case with just a single vulkan instance passing `NULL, NULL` should work to capture as the wildcard matching will find only one capturer, having two at all is strange.

It seems like you have source available to debug, can you breakpoint on `RenderDoc::AddDeviceFrameCapturer` to see where it's coming from? It should only be called once inside `WrappedVulkan::vkCreateInstance`, so I'm wondering where the other one comes from. Or if you can share your application I can debug into this.

But yes it's the dispatch table, contained inside the VkInstance. That's the only identifier that doesn't change with potential layers (the VkInstance the application sees is not always the same as the one that RenderDoc's layer sees). There's a helper macro in the `renderdoc_app.h` header `RENDERDOC_DEVICEPOINTER_FROM_VKINSTANCE` which will do this for you, given a `VkInstance`.

This is documented in the [in-application API](https://renderdoc.org/docs/in_application_api.html) linked from the issue you referenced, in particular under the section for [SetActiveWindow, StartFrameCapture and EndFrameCapture](https://renderdoc.org/docs/in_application_api.html#_CPPv215SetActiveWindow23RENDERDOC_DevicePointer22RENDERDOC_WindowHandle) it details exactly what the `RENDERDOC_DevicePointer` and `RENDERDOC_WindowHandle` correspond to on different APIs.

**Comment by ghost** [comment]
@baldurk Oh, thanks for the info on `RENDERDOC_DEVICEPOINTER_FROM_VKINSTANCE` ! Somehow I missed that. 

> I'd like to understand the bug here.

So do I, so I have debugged this is a bit. 

There is an issue, especially visible when there are multiple VkInstances in the application. 

On vkDestroyInstance, the value of 'dev' parameter passed to `RemoveDeviceFrameCapturer` looks like being read from freed memory.

With RDOC_DEVEL / DebugClear the value is clobbered in:
```
 	vcruntime140.dll!00007ffb514fcf03()	Unknown
 	renderdoc.dll!WrappingPool<WrappedVkInstance,8192,1048576,1>::ItemPool::Deallocate(void * p) Line 234	C++
 	renderdoc.dll!WrappingPool<WrappedVkInstance,8192,1048576,1>::Deallocate(void * p) Line 122	C++
 	renderdoc.dll!WrappedVkInstance::operator delete(void * p) Line 233	C++
 	renderdoc.dll!VulkanResourceManager::ReleaseWrappedResource<VkInstance_T * __ptr64>(VkInstance_T * obj, bool clearID) Line 403	C++
 	renderdoc.dll!WrappedVulkan::vkDestroyInstance(VkInstance_T * instance, const VkAllocationCallbacks * pAllocator) Line 578	C++
 	renderdoc.dll!hooked_vkDestroyInstance(VkInstance_T * instance, const VkAllocationCallbacks * pAllocator) Line 174	C++

```

So it looks like the bug is here: 

```
void WrappedVulkan::vkDestroyInstance(VkInstance instance, const VkAllocationCallbacks *pAllocator)
{
...
  GetResourceManager()->ReleaseWrappedResource(m_Instance);

  RenderDoc::Inst().RemoveDeviceFrameCapturer(LayerDisp(m_Instance));
....
}
```

The `ReleaseWrappedResource` frees the value accessed by `LayerDisp(m_Instance)`. 

Maybe it's just a matter of swapping these two lines?


Btw, AppVerifier does not flag this - so I may be wrong.

**Comment by ghost** [comment]
>Btw, AppVerifier does not flag this - so I may be wrong.

or there is a pool being used here, so verifier is blind :)

**Comment by baldurk** [comment]
Aha, yes indeed that makes sense. This was a bug someone caught a little while ago - see #958. If you try a recent nightly build or build from latest source it should be OK I think?

**Comment by baldurk** [comment]
Closing this as I believe the bug was fixed and the original question has a documented answer.
