### ISSUE TITLE
Vulkan recording asserts when VkRenderPass.attachmentCount > 17

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#1033]
`renderdoc/driver/vulkan/vk_resources.h`  defines following constant: 

```
static const int MaxImageAttachments = 17;    // 8 Input, 8 Colour and 1 Depth
```

Than this const is used for validating & capping the VkRenderPassCreateInfo.attachmentCount. 

However this is too tight - the maximum values (8+8+1 or `maxColorAttachments` and friends) apply only to one subpass (one VkSubpassDescription) at a time.

Subpasses can use VkFramebuffer/VkRenderpass attachments `sparsely` - so their attachmenCount should not be limited.  In fact I don't see any limit in spec at this moment.

Is it possible to eliminate this constant?  Or if not  -  maybe increase to somewhere beyond 64? 

(The app recorded was https://github.com/KhronosGroup/VK-GL-CTS  :)  Some tests have around 30 attachments).

**Comment by baldurk** [comment]
I think this constant comes from originally having a fixed array in the `VkResourceRecord` which is size-sensitive. Since it's now only used to dynamically allocate, it seems like it could be removed indeed.

The renderpass can use the attachment count to allocate its array and then leave a sentinel value at the end, which the framebuffer can use to determine the number of attachments in the matching array.

**Comment by baldurk** [comment]
Fixed as described before, although I'm not brave enough to try compiling or running VK-GL-CTS to test for sure :).
