### ISSUE TITLE
Feature Request: support natural sort order in resource inspector

### ISSUE THREAD

**Issue by didito** [baldurk/renderdoc#1034]
Often when I look through a capture I have to inspect resources in (roughly) the same order they were created, i.e. Buffer 1 -> 2 -> 3 etc.. Unfortunately the list is sorted in ASCII order so I get more something like this: 1 -> 10 -> 100 -> 101 -> 2 etc..

![renderdoc_resourceinspector_naturalsort](https://user-images.githubusercontent.com/1446766/42342935-69640cb0-804c-11e8-9e80-6c489ade5497.png)

This gets very tedious to navigate. So I suggest having a toggle for ordering the list in different ways. This is a nice resource for natural sort order (including some code) https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/

Ideally the whole filtering in the resource inspector would of course support regexp, some kind of syntax ("type: Buffer size:64b usedinframe:<num>") or something like a matching functionality (same buffer description), but first things first :)

**Comment by baldurk** [comment]
This shouldn't be too hard to implement, but can you give more details about what your use case is? The resource inspector was intended for looking up the details of a specific resource rather than browsing through them all - I added the list so you could find something by name, rather than going from something bound to a pipeline or referenced in an API call. Going through _every_ resource in creation order seems strange.

**Comment by didito** [comment]
I'm not going through _every resource in order_, but several subsets which are in order.

In my case I was checking a lot of Map / Unmap calls (hundreds) in a render pass and quite a lot of those calls happened to use buffers more or less in creation order (not even 100% in order, but within a certain range). I was trying to figure out what kind of buffers they are (how similar to each other, to identify a pattern) and if they are even used in that frame (they were not).

For that I did not want to go through every Map call in the API inspector in this pass:

- click it
- expand it
- select the buffer id
- check "Usage in Frames"
- expand and check "Resource Initialization Params"

Because it is tedious. And not only that - after going through them, going back later (now I have their consecutive ids in my memory) seems unnecessarily painful. It would be way more convenient to filter for "Buffer", scroll to my area of interest (i.e. buffer id range 10-36) and use the arrow keys to go up and down.

Obviously this situation will be different depending on how an engine creates and assigns resources (pooling, re-creating) but neither does it seem too strange to me when I think about how some things are created and registered for their render updates.

With all due respect ASCII order seems to me to be the one that is not very useful in any case.

**Comment by baldurk** [comment]
I didn't say that ASCII order is better, it only sorts like that because it's the default and I hadn't changed it. This sounds like a good improvement to make regardless, as I agree that it's better just to have natural sorting always.

I just wanted to understand your use-case better. It's better for me to know the whole workflow that you have rather than just one particular pain point that results from it, since it can sometimes lead to an even better improvement. In this case the change is a good one either way, but in other cases there might be a better fix than the one suggested - having more information about a problem never hurts!

One way to improve this would be to have some way to batch-analyse a set of buffers, or do comparisons across multiple resources to see similarities and differences. You probably want something more context-specific than just the resource inspector which is quite a generic view of resources and doesn't differentiate between a buffer, a texture, or a command buffer.

For your particular case one improvement would be if you could highlight the resource usage of a buffer across the timeline view by selecting it in the API inspector. That way you could quickly click through the Map calls and see where the buffers are used. Perhaps a holistic Dr. PIX style analysis that could identify resources that are updated without being used would be useful, similar in principle to detecting redundant state setting.

**Comment by didito** [comment]
Yes, some way to batch-analyse or see the settings of a set of buffers is the goal. Easy visual comparisons / diffs are even better. But creating a good UI for such things is very hard. I would already be happy if the resource viewer would always present the content in "Resource Initialisation Parameters" as expanded (or remember the setting between selections). Those two extra clicks to expand (first the create function, then the description) just kill me :)

**Comment by baldurk** [comment]
That commit will add the natural sorting into the resource inspector. I still have some ideas for addressing at least some of the other issues.

I'm going to experiment with rolling out tree-expansion saving over the rest of the UI, since it's been requested for other areas as well and generally is quite nice. My main concern is memory bloat from saving all those states, but I'm going to add it and see what it's like after measuring.

I also have some ideas about pre-expanding some of the trees. The problem here is that depending on the API both the number of calls in that list can vary (or might vary in future), and also the structs themselves can be quite deep and you might not care about all of them. It's the kind of problem of "expand just as much as I want, and no more" which is hard to solve :smile:. I have some ideas though that I'll try out in future.

**Comment by didito** [comment]
Nice, thank you. Will check it out in a nightly build.

Regarding tree expansion - yes, it's not so easy to get that right for everybody. But an UI that supports saving expansion state during a session already makes me 90% happy :)

Other little UX paradigms I have seen and appreciated:
- keyboard navigation (up / down) and control over expansion / collapse (left / right)
- "expand / collapse all" (via Shift (or Ctrl or) click).
- "expand / collapse sub tree from / until here" (also via modifier key + click)

**Comment by baldurk** [comment]
To clarify are these things you like or you'd want? Because the first one should exist already, the other two don't (that I'm aware of).

**Comment by baldurk** [comment]
I've implemented the saving of tree collapse/expand states, as in #678, so for the moment I consider this closed. If you want to open another issue for related features feel free.

As I mentioned I do have plans to address the readability-at-a-glance of things like the creation chunks but it's a longer term more significant change.

**Comment by didito** [comment]
Sorry for being unclear - , yes, the first one already is in RenderDoc, the other ones aren't. I was just thinking of other ways of how to improve quality of life with the tree expansion / collapse.

Re #678 - thank you! I've checked out a build and it seems to work.

After using it for a bit I realize though that while I like the behavior in the Event Browser / API - I expand something and the application remembers it on that specific EID - it is not 100% what I was looking for in the Resource Inspector (Resource List & Resource Initialisation Parameters). I wish for the latter it would just apply the expansion to all of the same type. But I guess that would make things more complicated. And we would be back at the problem of how much / far to expand ...

Either way, it seems like a good step into the right direction.

**Comment by baldurk** [comment]
Yes it helps if you're going back and forth between resources to compare, since it saves you re-expanding, but it doesn't help you on the first browse.

As we've discussed though it gets into a difficult grey area. E.g. you might think that always expanding the first call would be a useful default, but on OpenGL that's not what you want because the first call is going to be an uninteresting `glGenTextures` or `glGenBuffers` and really what you want is the next call - `glTexImage2D`. Which is already more complicated because that might not even be the second call it might be the third or fourth, etc...

My very rough plan is to try and add extra annotation into the serialised form to markup 'important' properties and calls, with some kind of heavy editorialising of what's considered important. Then 'important' parameters will be in-lined into the unexpanded calls to give a more at-a-glance view. This would apply equally to the API inspector and resource inspector. Then it would also allow picking the top 1 or 2 'important' calls in the list of creation functions to expand, if that's needed. Basically a combination between manual annotation and automatic identification.

It's not very well formulated in my head though so this might change a lot :smile:.

**Comment by didito** [comment]
Extra annotation in the API wrapper source code sounds like a good approach. Alternatively, additionally or as a starting point it could be useful to have configurable list of types or functions where you can set an expand flag for the state after loading a capture.

And I do think that users might not want the same behavior in the API browser (remember expansion per instance) and the resource inspector (remember expansion per "type").
