### ISSUE TITLE
RenderDoc API: Set capture comments?

### ISSUE THREAD

**Issue by JensRestemeier** [baldurk/renderdoc#1037]
## Description

I successfully integrated renderdoc capture (both trigger capture and start/end capture) into my application. I was wondering, is there a way to set the "capture comments" text? Or is one of the debug message functions trapped and used to init the capture comments?

I could automatically init some of the environment and application version from the code.

## Environment

* RenderDoc Release 1.0
* Operating System: Windows 10,
* API: D3D11

**Comment by baldurk** [comment]
It's an interesting idea. I probably wouldn't want to couple this too tightly with using Start/End capture API as some users might want to set capture comments even if they're not manually defining the capture themselves. That probably means an entry point along the lines of `SetFileComments("foo.rdc", "my comments")`. I'll look at this and see what I can do, although I don't think it'll happen before the next release.

In the meantime as a workaround, you _could_ in theory invoke the replay API - see [renderdoc_replay.h](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/api/replay/renderdoc_replay.h). Much of the replay API is **not** safe to call when capturing, but if you stick to just the set needed to open the file and add a section, that should work fine (since it goes to the same code that is used to ). That's just a temporary hack though, it might break in future I give no promises :smile:.

Another alternative if you prefer it is to append a text file that can add a section, I support a simple ASCII format which is intended to be easy to construct and help scripting or hand-crafting simple sections rather than having to match the binary format. The format is like so:

```
A                         # Single 'A' character followed by '\n'
35                        # Length of the payload followed by '\n' - everything from { to EOF
4                         # ID of the section followed by '\n' - the notes section in this case
0                         # Section version followed by '\n', ignored for the comments right now
renderdoc/ui/notes        # Section name - predefined
{"comments":"Here are my comments"}
```

Which you can append to an .rdc and have the capture comments load up.

**Comment by JensRestemeier** [comment]
This text is probably updated rarely, at startup or when the scene changes. Maybe a global string buffer is enough?

**Comment by baldurk** [comment]
I'd like to avoid having extra state in the API where it's not needed. Directly setting the comments on a file is a simpler and more isolated operation, and it also means that if someone can generate the comments after the capture more easily than before they can still do that.

You could have a global string buffer on your own side and then just check `if(!comments.empty()) SetFileComments(last_capture_path, comments.c_str());` if you want the other behaviour.

**Comment by baldurk** [comment]
As discussed I added a `SetFileComments` function in the app API 1.2.0. I added a convenience feature that if you pass `NULL` for the file path, it will use the most recent capture's path. That way if you call this right after `EndFrameCapture` it will tag on whatever persistent comments string you have.
