### ISSUE TITLE
Vulkan preview of vkCmdCopyImage

### ISSUE THREAD

**Issue by pjaholkowski** [baldurk/renderdoc#1039]
## Description

After clicking on vkCmdCopyImage in EventBrowser TextureViewer tab doesn't show valid image
previews (shows black instead)

## Repro steps

I wrote source code based on cubepp example from VulkanSDK which reproduces that bug. Linked as attachment

## Environment

* RenderDoc build: v1.0, built from (5ef2d0bb)
* Operating System: Windows 10
* API: Vulkan
[cube.zip](https://github.com/baldurk/renderdoc/files/2188175/cube.zip)

**Comment by baldurk** [comment]
Your example has a fair bit of code relating to external memory sharing. I don't think it's relevant to this particular bug but it's hard to tell exactly. As an aside, I ran into one issue with the code which might be relevant to you - `vkGetPhysicalDeviceImageFormatProperties2KHR` doesn't return `VK_FALSE` for unsupported formats, it returns `VK_ERROR_FORMAT_NOT_SUPPORTED`. So the fallback bit you have to try `VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT_KHR` doesn't get hit.

The core issue is that you're copying from another frame's swapchain image. In your example this is illegal because you haven't acquired the image, but even if you did acquire it then you'd still get black in RenderDoc. The reason being I don't read back the contents of swapchain images due to the inherent difficulties in synchronising access, so they are always black at the start of the frame.

Normally that's fine and rendering into them during the frame fills the contents, so if you copied from the image you're currently rendering to at the end of the frame the copy would work as expected. Or if you copied from a non-swapchain image it would be there as normal.

Trying to fix this would have high risk of adding deadlocks or sync issues and it's a very niche use-case, so I don't have any plans to change that behaviour.
