### ISSUE TITLE
Fail to capture and replay OpenGL ES on Linux

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1040]
## Description

I'm  trying to capture an OpenGL ES desktop application on Linux but it crashes. 

I manage to capture if I modify this line:
`LibraryHooks::RegisterLibraryHook("libGL.so.1", &GLHooked);`
by setting the FunctionLoadCallback to NULL in the **RegisterHooks()** method of the **glx_hooks.cpp**.
Can we make a fix for this? 

Replaying doesn't work for me either, the problem is that RenderDoc uses the Mesa library while NVIDIA should be used. 
Could you give a solution for this problem?
Thank you.

## Environment

* RenderDoc build: v1.x 2018-07-12
* Operating System: Ubuntu Linux
* API: OpenGL ES

**Comment by baldurk** [comment]
Can you give more information: What program are you running? Where is the crash happening exactly? We can make a fix if it's a RenderDoc bug but I need more information to determine what the correct fix is. You can't just remove that callback to fix your case as that will break for other cases, and it shouldn't be necessary.

I don't understand what you mean that mesa is used instead of NVIDIA's driver. RenderDoc doesn't select any particular driver it just calls into the system libraries, it's up to the system's configuration to determine which driver is used.

I did find a bug that caused `libGLESv2.so` not to be hooked properly, I've just pushed a fixed for that so it would be worth trying with latest code as of now, but it doesn't sound like what you were running into.

**Comment by tabikati** [comment]
I was running a GLES desktop application which uses SOIL to load images and I crashed because **version** is null here: 
`const char *version = (const char *)GL.glGetString(eGL_VERSION);`
in the **FetchEnabledExtensions()** method of **gl_common.cpp**.

Since then I have tried other GLES applications (without SOIL) and they can be captured fine.
I couldn't capture Vulkan desktop applications either, only if i remove or modify `libGL.so.1` hooking like in my previous comment. 

As for the replaying, the application is compiled with NVIDIA but when it is replayed, the Mesa library is called. Setting up the library path environment variable when running RenderDoc solves this problem though.

**Comment by baldurk** [comment]
I still need more information to investigate this. If it's only any program using SOIL can you share an example either as source or binary that I can run to debug this? glGetString returning NULL suggests something is very wrong, are there any GL errors?

Changing the `libGL.so.1` hooking only clouds the issue, this will maybe hide some symptom but it's not a real fix. You mention that you have trouble capturing from Vulkan applications which is a different issue, but you don't say what actually happens or goes wrong.

I don't understand what you mean by "compiled with NVIDIA". It sounds like your system is misconfigured if there's some library mismatch or you need to set the library path environment variable, none of that should be necessary to run RenderDoc.

**Comment by tabikati** [comment]
I'm sending the GLES example code attached. I didn't get any GL error for this.

When I tried to capture the Vulkan, I got VK_ERROR_INCOMPATIBLE_DRIVER error message after vkCreateInstance was called.

[GLES_SOIL.zip](https://github.com/baldurk/renderdoc/files/2213549/GLES_SOIL.zip)

**Comment by baldurk** [comment]
Thank you for the repro. I don't think it's related to SOIL, it was a bug where it seems that on linux calling GL functions in `libGL` isn't equivalent to `libGLESv2`, and the example you gave was linked against `libGLESv2`. I applied the same fix as windows to forcibly clear and re-initialise the GL function pointers using `eglGetProcAddress`. Hopefully that will work well enough.

The vulkan errors were a problem with my hack around some broken distributions that ship the nvidia vulkan ICD as `libGL.so`. Using `RTLD_NEXT` to fetch the ICD functions doesn't work if `libGL.so` wasn't loaded earlier, because the loader loads the ICD as `RTLD_LOCAL`. Instead I grab the handle when it's loaded and look at it directly.

**Comment by tabikati** [comment]
Both GLES and Vulkan capturing works fine now, thank you.
