### ISSUE TITLE
Ability to choose replay adapter

### ISSUE THREAD

**Issue by Kamayuq** [baldurk/renderdoc#1072]
## Description

At least Windows supports more than 2 adapters and it would be nice to be able to select the replay adapter if more than one adapter are present. Maybe even selecting Warp as a possibility.

**Comment by didito** [comment]
Just ran into the same problem. I forgot that I switched machines and that one had multiple adapters available, so the performance counters did not show up. Later I realized the used adapter gets printed in the diagnostic log file but that is not very accessible.

Ideally you could choose the adapter when opening the capture / trace you want to replay. Per trace because maybe one day we will have support for multiple traces. Alternatively it would be a global preference or setting. And I think it would be great to show it in the UI at all times, maybe next to the Replay Context (bottom left).

**Comment by baldurk** [comment]
I've added a 'Open Capture with Options' menu item which includes a selection to let you override the GPU used for a capture.

![Open Capture with Options](https://user-images.githubusercontent.com/661798/63792128-d0abb480-c8f4-11e9-93ac-300d0f5d075a.png)

This is also available in the settings window to set the global defaults (or you can click 'save defaults' there).

The default algorithm is now the same on all APIs - it tries to match the adapter closest to the one used in the capture. Vulkan has always worked like this, but previously D3D just used whichever was the system default adapter.
