### ISSUE TITLE
DX12 Capture crash when using a GPU descriptor heap with 8K+ entries

### ISSUE THREAD

**Issue by Guoshima** [baldurk/renderdoc#1076]
## Description

Capturing our game on DX12 in RenderDoc crashes while iterating the bound desc at the following location:
renderdoc\driver\d3d12\d3d12_command_queue_wrap.cpp around line 421

It crashes because the vector (record->bakedCommands->cmdInfo->boundDescs) contains entries with invalid data.

I checked the vector quickly and saw that it contains invalid entries after some entries where the heap was set to a nullptr. This is copy of the a subrange of boundDescs from visual studio:

```
[53173]	0x000002a1b7bb3fc0 {data={samp={heap=0x000002a1989257b0 {realCPUBase={ptr=8 } realGPUBase={ptr=33366669250265088 } ...} ...} ...} }	D3D12Descriptor *
[53174]	0x000002a1b7bb4000 {data={samp={heap=0x000002a1989257b0 {realCPUBase={ptr=8 } realGPUBase={ptr=33366669250265088 } ...} ...} ...} }	D3D12Descriptor *
[53175]	0x000002a1b7bb4040 {data={samp={heap=0x0000000000000000 <NULL> idx=0 desc={Filter=D3D12_FILTER_MIN_MAG_MIP_POINT (0) ...} } ...} }	D3D12Descriptor *
[53176]	0x000002a1b7bb4080 {data={samp={heap=0x0000000000000000 <NULL> idx=0 desc={Filter=D3D12_FILTER_MIN_MAG_MIP_POINT (0) ...} } ...} }	D3D12Descriptor *
...
[53236]	0x000002a1b7bb4f80 {data={samp={heap=0x0000000000000000 <NULL> idx=0 desc={Filter=D3D12_FILTER_MIN_MAG_MIP_POINT (0) ...} } ...} }	D3D12Descriptor *
[53237]	0x000002a1b7bb4fc0 {data={samp={heap=0x0000000000000000 <NULL> idx=0 desc={Filter=D3D12_FILTER_MIN_MAG_MIP_POINT (0) ...} } ...} }	D3D12Descriptor *
[53238]	0x000002a1b7bb5000 {data={samp={heap=??? idx=??? desc={Filter=??? AddressU=??? AddressV=??? ...} } nonsamp=...} }	D3D12Descriptor *
[53239]	0x000002a1b7bb5040 {data={samp={heap=??? idx=??? desc={Filter=??? AddressU=??? AddressV=??? ...} } nonsamp=...} }	D3D12Descriptor *
[53240]	0x000002a1b7bb5080 {data={samp={heap=??? idx=??? desc={Filter=??? AddressU=??? AddressV=??? ...} } nonsamp=...} }	D3D12Descriptor *
[53241]	0x000002a1b7bb50c0 {data={samp={heap=??? idx=??? desc={Filter=??? AddressU=??? AddressV=??? ...} } nonsamp=...} }	D3D12Descriptor *
```

I added to following workaround locally and I can now make a capture again. I have no idea  if this is a good work around and where the invalid entries are coming from.

```
for(auto it = record->bakedCommands->cmdInfo->boundDescs.begin();
       it != record->bakedCommands->cmdInfo->boundDescs.end(); ++it)
{
      D3D12Descriptor *desc = *it;

     if (desc->GetHeap() == nullptr)
        break;
```

## Repro steps

We bind a single HEAP_TYPE_CBV_SRV_UAV descriptor heap for the whole frame (as suggested by the nVidia DX12 do's and don'ts). As long as this heap is maximum 8K everything works fine, but if I make it bigger (eg 16K), then I get the above mentioned crash when capturing.

If you need more info or repro steps please let me know.

## Environment

RenderDoc build v1.2 (release and own build)
OS: Windows 10
API: DX12
GPU: GTX 1080

**Comment by baldurk** [comment]
That workaround is probably not always going to work I think - a NULL heap means the descriptor is uninitialised (or maybe just pointing to random memory that happens to contain zeroes), there's no guarantee you'll hit that before you hit invalid memory, the key is how they got there in the first place.

I don't think this is related to the size of the heap alone - I've captured games that create CBV_SRV_UAV heaps at the maximum 1,000,000 size for tier1/2 and that works. When you say you're binding a single heap, you mean you're binding it as a single large descriptor table right?

My first educated guess is that there's a problem with that descriptor table binding. The `boundDescs` list is used to track which resources are referenced in a capture, and it's populated fairly simply from `SetComputeRootDescriptorTable` / `SetGraphicsRootDescriptorTable` by iterating the descriptor ranges specified in the root signature and blanket adding all the descriptors from the heap into that list. You can see all the entries in the list are contiguous with `sizeof(D3D12Descriptor) == 0x40`.

Does your program have any D3D12 warnings/errors? If not, could you still double check to see that your table binding isn't going to run off the end of the declared descriptor heap? RenderDoc won't check for that itself (although in retrospect it wouldn't be a bad idea to add a warning message), and I think it would produce this kind of result as it blindly referenced pointers into invalid memory off the end of the heap's declared array of descriptors.

I'm assuming you can't share a repro of your program itself which would be simplest for me to debug :smile:. Would you be willing to run a renderdoc build with extra logging to see where those invalid entries are coming from?

I'd like to fix this bug either way, but FYI if you're doing this bindless style with binding huge descriptor tables, you'll likely get a performance boost under RenderDoc by enabling the "ref all resources" capture option. That turns off active tracking of which resources are referenced because it's going to include them all anyway.

**Comment by Guoshima** [comment]
thank you for the very quick reply!

I kind of knew the workaround wouldn't be a valid option, but it least got me a bit further :)
I sadly enough can't easily share the executable and content. And it make sense that Renderdoc has made captures of heaps of upto a 1 million entries (8K was already very limiting :)).

But I can of course run a RenderDoc build with extra logging enabled if you tell me how.

We have currently no D3D12 warnings or errors and we are still in the progress of porting the engine to DX12. But I think I might have an idea what could cause the issue:

I try and share as many root signatures as I can so the tables in the root signatures are over allocated (space for 16 RW buffers for example, while on average only a few will be bound). For each drawcall I only fill in the D3D12_GPU_DESCRIPTOR_HANDLE for the entries which are actually used by that shader and just skip the other entries. I guess these will be unitialized memory.

I quickly tried forcing this to zero but D3D doesn't allow me to do that. Is there an easy way to clear a descriptor heap. I could try and always bind a valid resource on every slot and see if that fixes it.

We are planning to go bindless at some point but we currently are not yet. But I will try the 'ref all resources' and see what that gives me.

Cheers,
Kenzo

**Comment by Guoshima** [comment]
"ref all resources" fixes the issue and I can now make captures with the released build as well. 

But I guess you are still interested in getting more info about the other crash as well then, so please let me know what extra info I can provide or test.

**Comment by baldurk** [comment]
Oh, hey Kenzo! :wave:

Yep "ref all resources" will bypass this whole codepath, but it's just hiding the bug so I would like to fix it indeed.

I'm not sure exactly what D3D12's rules are (they are probably undocumented) but I know vulkan doesn't require you to fill out descriptors that are never going to be used by the shader even with flow control, so D3D12 is likely similar.

In this case I'm not meaning the _contents_ of descriptors being filled in, I'm saying the descriptors themselves. I believe I have correct handling for uninitialised descriptors in the API sense, but the way the snippet you pasted looked I was wondering if the descriptor pointers themselves were pointing at memory that hadn't been initialised properly, meaning somehow the tracking tripped over invalid pointers.

I've created a branch [`dx12_desc_logging`](https://github.com/baldurk/renderdoc/tree/dx12_desc_logging) with some first-pass logging. This will be quite spammy but if you build and run with it and upload the log somewhere it might point towards what the problem is. It would be good to have also at the same time the matching paste of the `boundDescs` array subrange as you posted in the original report, so I can match up the pointer values to the log.

**Comment by Guoshima** [comment]
Hi Baldur :)

Thank you for info and branch. I am currently sidetracked with something but I will still try and provide the log later today (otherwise latest Monday morning first thing!).

Normally all the command lists get the same SRV and Sampler descriptor heap set during the preparation of the command list for that frame. The descriptor heaps are double buffered (double buffered frame rendering). 

But as mentioned before, the DX12 pipeline is still far from finished yet, so plenty of bugs are still in there!

**Comment by Guoshima** [comment]
Hi!

For every every call to SetComputeRootDescriptorTable or SetGraphicsRootDescriptorTable I get a warning saying that I am going out of range:

```
Log     - Setting descriptor table root parameter 2 in root signature 0000019EDBF11D40 (125)
Log     - Base descriptor 0000019EE64D9FC0 (index 175/2048 in heap 0000019ED949DC30 (40))
Log     - Range 0/1: offs (4294967295 => 0) len (4294967295 => 2048) goes from 0000019EE64D9FC0 (index 175) to 0000019EE64F9F80 (index 2222)
Warning - Range seems to run off the end of the descriptor heap
Log     - Setting descriptor table root parameter 0 in root signature 0000019EDBF11EC0 (121)
Log     - Base descriptor 0000019EF5DCEE80 (index 4473/131072 in heap 0000019ED949DC90 (39))
Log     - Range 0/5: offs (4294967295 => 0) len (1 => 1) goes from 0000019EF5DCEE80 (index 4473) to 0000019EF5DCEE80 (index 4473)
Log     - Range 1/5: offs (4294967295 => 1) len (16 => 16) goes from 0000019EF5DCEEC0 (index 4474) to 0000019EF5DCF280 (index 4489)
Log     - Range 2/5: offs (4294967295 => 17) len (8 => 8) goes from 0000019EF5DCF2C0 (index 4490) to 0000019EF5DCF480 (index 4497)
Log     - Range 3/5: offs (4294967295 => 25) len (8 => 8) goes from 0000019EF5DCF4C0 (index 4498) to 0000019EF5DCF680 (index 4505)
Log     - Range 4/5: offs (4294967295 => 33) len (4294967295 => 131039) goes from 0000019EF5DCF6C0 (index 4506) to 0000019EF65CEE40 (index 135544)
Warning - Range seems to run off the end of the descriptor heap
Log     - Setting descriptor table root parameter 0 in root signature 0000019EDBF11EC0 (121)
Log     - Base descriptor 0000019EF5DCF740 (index 4508/131072 in heap 0000019ED949DC90 (39))
Log     - Range 0/5: offs (4294967295 => 0) len (1 => 1) goes from 0000019EF5DCF740 (index 4508) to 0000019EF5DCF740 (index 4508)
Log     - Range 1/5: offs (4294967295 => 1) len (16 => 16) goes from 0000019EF5DCF780 (index 4509) to 0000019EF5DCFB40 (index 4524)
Log     - Range 2/5: offs (4294967295 => 17) len (8 => 8) goes from 0000019EF5DCFB80 (index 4525) to 0000019EF5DCFD40 (index 4532)
Log     - Range 3/5: offs (4294967295 => 25) len (8 => 8) goes from 0000019EF5DCFD80 (index 4533) to 0000019EF5DCFF40 (index 4540)
Log     - Range 4/5: offs (4294967295 => 33) len (4294967295 => 131039) goes from 0000019EF5DCFF80 (index 4541) to 0000019EF65CF700 (index 135579)
Warning - Range seems to run off the end of the descriptor heap
```

But after checking the code a little bit it tries to adjust the count of the range in the table when the range is unbounded (UINT_MAX):

```
if(num == UINT_MAX)
{
    // find out how many descriptors are left after rangeStart
    num = HeapNumDescriptors - offset;
}
```

But shouldn't this code also take the current heap index into account (base->GetHeapIndex())? (could of course be missing something here!)

I will create a full dump now and attach it as well.

Cheers,
Kenzo

**Comment by baldurk** [comment]
Ahhh, duh, you're right. The `HeapNumDescriptors - offset` is meant to be the remaining size, but the `offset` here is only the offset defined in the range itself. It doesn't include any other offset from `BaseDescriptor`.

If you change that to `num = HeapNumDescriptors - rangeStart->GetHeapIndex();` (not base, since that's wrong in the other sense - missing the range's offset) does it work?

**Comment by Guoshima** [comment]
I attached the log of all the renderdoc traces, just in case: 

[RenderDoclog.txt](https://github.com/baldurk/renderdoc/files/2278324/RenderDoclog.txt)

**Comment by Guoshima** [comment]
Yes it does! Thank you for the fast feedback. I guess this fix will find itself in an official render doc release soon.

Have a good weekend!
Kenzo

**Comment by baldurk** [comment]
Fix committed there, it'll be in the next nightly build.
