### ISSUE TITLE
Environment var VK_LAYER_PATH should be used for replay

### ISSUE THREAD

**Issue by farnoy** [baldurk/renderdoc#1078]
## Description

I've found an issue where, when specifying `VK_LAYER_PATH` in capture settings is not used for replay. In theory, this shouldn't be a problem, but it seems fragile enough that it makes a difference here.

The problem is somehow amplified when creating a device and requesting more queues, but this is beyond me. When I changed my code to request just one graphics queue, the problem goes away, even withotu any differences in environment.

I've seen this on Linux and Windows 10 (AMDVLK in both cases)

```
RDOC 011172: [20:27:37]          vk_core.cpp(2995) - Warning - [Loader Message:0/0] terminator_CreateDevice: Failed in ICD C:\WINDOWS\System32\DriverStore\FileRepository\c0331834.inf_amd64_598c38be6d6a3fce\B331820\.\amdvlk64.dll vkCreateDevicecall
RDOC 011172: [20:27:37]          vk_core.cpp(2995) - Warning - [Loader Message:0/0] vkCreateDevice:  Failed to create device chain.
RDOC 011172: [20:27:37]  vk_device_funcs.cpp(1557) - Error   - Failed to create logical device: VK_ERROR_OUT_OF_HOST_MEMORY
```

## Repro steps

Here's my capture: [v4_2018.08.11_18.46.29_frame26.zip](https://github.com/baldurk/renderdoc/files/2280451/v4_2018.08.11_18.46.29_frame26.zip). I generated it by starting renderdoc with clean environment and setting `VK_LAYER_PATH` inside

1. Start renderdoc with your usual, unchanged, environment.
2. Replay my capture and witness the error (Renderdoc as a whole doesn't crash, nice touch)

Now the workaround:

1. Start renderdoc with `VK_LAYER_PATH` already set (I did this from powershell). In my case (and in the case of this capture) it was `C:\VulkanSDK\1.1.82.0\Source\Lib`
2. Replay that capture and it works just as expected.

## Environment

* RenderDoc build: 197a279e31087ba0de4f3d9b2efa273ccae7c21e
* Operating System: Windows 10
* API: Vulkan
* GPU Driver: Radeon 18.8.1

**Comment by baldurk** [comment]
I think of `VK_LAYER_PATH` as a local hack that you can apply to override correct layer registration, so I'm not going to try and save and apply that during replay. It would also make captures incredibly specific as you could get in the situation where you couldn't open it without editing it if the referenced paths change. If you need to use the env var for replay then setting it before running renderdoc is the right way rather than a workaround.

That said, this bug seems very strange and I'm not sure it's about the path at all. If it were just failing to find a layer then you'd get a message like `Capture requires layer '%s' which is not supported`, but it's getting as far as device creation. The device create failing in the driver like that is something I've not seen before.

On top of that, the only layer you seem to have active is `VK_LAYER_LUNARG_standard_validation` which is deliberately stripped out on replay since there's no point to having them active, so I'm even more confused about how setting `VK_LAYER_PATH` changes anything.

Can you run vulkaninfo with and without it? I wonder if there's an implicit layer on your system which is causing problems.

Also can you clarify what you mean about creating graphics queues? The capture you've uploaded only creates one queue - do you mean that it doesn't repro the bug? I can also see that the physical device itself only actually supports one graphics queue so requesting more would definitely fail.

**Comment by farnoy** [comment]
I agree about `VK_LAYER_PATH`, just typing out the issue it didn't seem like the best solution. Maybe we can at least document this somewhere, for people to watch out if they do modify it?

When I saw vkCreateDevice fail in the driver, I reinstalled it completely with DDU, did not help. I wish there was better messaging here, no way could this be an OOM issue.

I ran vulkaninfo with and without VK_LAYER_PATH. The only differences are in `ArrayOfVkLayerProperties`:

<details>
  <summary>Stock</summary>

```json
	"ArrayOfVkLayerProperties": [
		{
			"layerName": "VK_LAYER_AMD_switchable_graphics",
			"specVersion": 4198477,
			"implementationVersion": 1,
			"description": "AMD switchable graphics layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_standard_validation",
			"specVersion": 4194381,
			"implementationVersion": 1,
			"description": "LunarG Standard Validation Layer"
		},
		{
			"layerName": "VK_LAYER_RENDERDOC_Capture",
			"specVersion": 4198473,
			"implementationVersion": 2,
			"description": "Debugging capture layer for RenderDoc"
		},
		{
			"layerName": "VK_LAYER_VALVE_steam_overlay",
			"specVersion": 4198473,
			"implementationVersion": 1,
			"description": "Steam Overlay Layer"
		}
	],
````
</details>

<details>
  <summary>C:\VulkanSDK\1.1.82.0\Source\lib</summary>

```json
	"ArrayOfVkLayerProperties": [
		{
			"layerName": "VK_LAYER_AMD_switchable_graphics",
			"specVersion": 4198477,
			"implementationVersion": 1,
			"description": "AMD switchable graphics layer"
		},
		{
			"layerName": "VK_LAYER_GOOGLE_threading",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "Google Validation Layer"
		},
		{
			"layerName": "VK_LAYER_GOOGLE_unique_objects",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "Google Validation Layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_api_dump",
			"specVersion": 4198482,
			"implementationVersion": 2,
			"description": "LunarG debug layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_assistant_layer",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "LunarG Validation Factory Layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_core_validation",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "LunarG Validation Layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_device_simulation",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "LunarG device simulation layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_monitor",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "Execution Monitoring Layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_object_tracker",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "LunarG Validation Layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_parameter_validation",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "LunarG Validation Layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_screenshot",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "LunarG image capture layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_standard_validation",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "LunarG Standard Validation"
		},
		{
			"layerName": "VK_LAYER_LUNARG_vktrace",
			"specVersion": 4198482,
			"implementationVersion": 1,
			"description": "Vktrace tracing library"
		},
		{
			"layerName": "VK_LAYER_RENDERDOC_Capture",
			"specVersion": 4198473,
			"implementationVersion": 2,
			"description": "Debugging capture layer for RenderDoc"
		},
		{
			"layerName": "VK_LAYER_VALVE_steam_overlay",
			"specVersion": 4198473,
			"implementationVersion": 1,
			"description": "Steam Overlay Layer"
		}
	],
````
</details>

Interestingly, `VK_LAYER_LUNARG_standard_validation` has an older `specVersion` in the ~stock~ modified-path version.

I also get a warning with vulkaninfo:

```
WARNING: [Loader Message] Code 0 : Layer "VK_LAYER_RENDERDOC_Capture" using deprecated 'vkGetInstanceProcAddr' tag which was deprecated starting with JSON file version 1.1.0.  Instead, use the new vkNegotiateLayerInterfaceVersion function to return the GetInstanceProcAddr function for this layer.
WARNING: [Loader Message] Code 0 : Layer "VK_LAYER_RENDERDOC_Capture" using deprecated 'vkGetDeviceProcAddr' tag which was deprecated starting with JSON file version 1.1.0.  Instead, use the new vkNegotiateLayerInterfaceVersion function to return the GetDeviceProcAddr function for this layer.
```

Regarding queues, I believe my program was requesting 1 graphics queue (GRAPHICS | COMPUTE | TRANSFER) and 3 compute queues (COMPUTE | TRANSFER). I went back in my git history and these are the API calls it is making under renderdoc, are you seeing something else stored in the capture?

<details>
  <summary>API calls</summary>

```
Thread 0, Frame 0:
vkGetPhysicalDeviceQueueFamilyProperties(physicalDevice, pQueueFamilyPropertyCount, pQueueFamilyProperties) returns void:
    physicalDevice:                 VkPhysicalDevice = 000001F7AB187510
    pQueueFamilyPropertyCount:      uint32_t* = 3
    pQueueFamilyProperties:         VkQueueFamilyProperties* = 000001F7AAE245D0
        pQueueFamilyProperties[0]:      VkQueueFamilyProperties = 000001F7AAE245D0:
            queueFlags:                     VkQueueFlags = 15 (VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT | VK_QUEUE_TRANSFER_BIT | VK_QUEUE_SPARSE_BINDING_BIT)
            queueCount:                     uint32_t = 1
            timestampValidBits:             uint32_t = 64
            minImageTransferGranularity:    VkExtent3D = 000001F7AAE245DC:
                width:                          uint32_t = 1
                height:                         uint32_t = 1
                depth:                          uint32_t = 1
        pQueueFamilyProperties[1]:      VkQueueFamilyProperties = 000001F7AAE245E8:
            queueFlags:                     VkQueueFlags = 14 (VK_QUEUE_COMPUTE_BIT | VK_QUEUE_TRANSFER_BIT | VK_QUEUE_SPARSE_BINDING_BIT)
            queueCount:                     uint32_t = 3
            timestampValidBits:             uint32_t = 64
            minImageTransferGranularity:    VkExtent3D = 000001F7AAE245F4:
                width:                          uint32_t = 1
                height:                         uint32_t = 1
                depth:                          uint32_t = 1
        pQueueFamilyProperties[2]:      VkQueueFamilyProperties = 000001F7AAE24600:
            queueFlags:                     VkQueueFlags = 12 (VK_QUEUE_TRANSFER_BIT | VK_QUEUE_SPARSE_BINDING_BIT)
            queueCount:                     uint32_t = 2
            timestampValidBits:             uint32_t = 64
            minImageTransferGranularity:    VkExtent3D = 000001F7AAE2460C:
                width:                          uint32_t = 16
                height:                         uint32_t = 16
                depth:                          uint32_t = 8

Thread 0, Frame 0:
vkCreateDevice(physicalDevice, pCreateInfo, pAllocator, pDevice) returns VkResult VK_SUCCESS (0):
    physicalDevice:                 VkPhysicalDevice = 000001F7AB187510
    pCreateInfo:                    const VkDeviceCreateInfo* = 0000004F5C738830:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO (3)
        pNext:                          const void* = 0000004F5C738808
        flags:                          VkDeviceCreateFlags = 0
        queueCreateInfoCount:           uint32_t = 2
        pQueueCreateInfos:              const VkDeviceQueueCreateInfo* = 000001F7AB3173D0
            pQueueCreateInfos[0]:           const VkDeviceQueueCreateInfo = 000001F7AB3173D0:
                sType:                          VkStructureType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO (2)
                pNext:                          const void* = NULL
                flags:                          VkDeviceQueueCreateFlags = 0
                queueFamilyIndex:               uint32_t = 0
                queueCount:                     uint32_t = 1
                pQueuePriorities:               const float* = 000001F7A7CA5CB0
                    pQueuePriorities[0]:            const float = 1
            pQueueCreateInfos[1]:           const VkDeviceQueueCreateInfo = 000001F7AB3173F8:
                sType:                          VkStructureType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO (2)
                pNext:                          const void* = NULL
                flags:                          VkDeviceQueueCreateFlags = 0
                queueFamilyIndex:               uint32_t = 1
                queueCount:                     uint32_t = 3
                pQueuePriorities:               const float* = 000001F7AB2E6370
                    pQueuePriorities[0]:            const float = 1
                    pQueuePriorities[1]:            const float = 1
                    pQueuePriorities[2]:            const float = 1
```
</details>

**Comment by baldurk** [comment]
I don't think the `VK_LAYER_PATH` interaction needs to be documented, it's an external factor and there are all sorts of ways to modify your system with custom overrides or changes that could mess up RenderDoc's operation. The variable is a "use this at your own risk and if you know what you're doing" kind of backdoor hack so the onus is kind of on the user to get it working. As I say though in this case I think it's hiding whatever the real problem is since in principle it shouldn't change anything at all.

I don't see any changes in the implicit layers there that would explain any behaviour difference. You could try disabling the `VK_LAYER_AMD_switchable_graphics` or `VK_LAYER_VALVE_steam_overlay` layers to see what would happen (env var for steam is `DISABLE_VK_LAYER_VALVE_steam_overlay_1=1`, I don't know about the AMD one you'd need to check the json for it).

The loader warning is nonsense, you can ignore it as a loader bug it shouldn't be warning about that.

I think we're on the same page about the queues, I misread "requesting more queues, [...] changed my code to request just one graphics queue" as saying you were requesting more than one graphics queue before, but you're always requesting one graphics queue either way. You're meaning you don't request more other types of queues. Those API calls match what I see in the capture so that's fine.

I'll try and look into this next week on my AMD machine. In the meantime if you feel up to some digging then since you have it reproducing on linux you can build the AMDVLK driver locally and step through the source to see exactly why that OOM is being returned. Inspecting the [xgl source](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/vk_device.cpp#L279-L284) it seems like there's a couple of ways OOM can be returned but mostly if a custom memory allocation callback failed. There are calls to other functions that might return it - I didn't trace all the way through.

**Comment by farnoy** [comment]
The switch for AMD layer is `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1` but it doesn't help either. I will try to build their linux driver with debuginfo to see, but it's so easy to crash the whole graphics stack that I might not succeed.

**Comment by farnoy** [comment]
I can no longer reproduce it on Linux, maybe that was something else, I don't remember now :disappointed: Renderdoc is working here, even with different drivers for capture&replay. The capture from Windows also runs fine.

**Comment by baldurk** [comment]
I've tried to repro this on my windows RX 480 system but I don't get any problems unfortunately, the capture loads fine regardless of what I try to do. For comparison's sake, my vulkaninfo without any env var looks like:

<details>
  <summary>vulkaninfo</summary>

```json
	"ArrayOfVkLayerProperties": [
		{
			"layerName": "VK_LAYER_AMD_switchable_graphics",
			"specVersion": 4198477,
			"implementationVersion": 1,
			"description": "AMD switchable graphics layer"
		},
		{
			"layerName": "VK_LAYER_LUNARG_standard_validation",
			"specVersion": 4194386,
			"implementationVersion": 1,
			"description": "LunarG Standard Validation Layer"
		},
		{
			"layerName": "VK_LAYER_NV_optimus",
			"specVersion": 4198470,
			"implementationVersion": 1,
			"description": "NVIDIA Optimus layer"
		},
		{
			"layerName": "VK_LAYER_RENDERDOC_Capture",
			"specVersion": 4198473,
			"implementationVersion": 2,
			"description": "Debugging capture layer for RenderDoc"
		},
		{
			"layerName": "VK_LAYER_VALVE_steam_overlay",
			"specVersion": 4198473,
			"implementationVersion": 1,
			"description": "Steam Overlay Layer"
		}
	],
```
</details>

The extra NV layer just because I also have an NV card in this system (not used for loading an AMD capture obviously).

I don't have a lot of ideas from here. You've already tried completely reinstalling the driver which would have been my first guess. Have you run a debug build of RenderDoc? I wonder if you'll get any extra messages through EXT_debug_report - though that's a wild stab in the dark.

EDIT: also just to check, try reinstalling the vulkan SDK. To do a proper test, you might need to set VK_LAYER_PATH to somewhere invalid otherwise the registry entries that _should_ be pointing your 'stock' setup at the vulkan layers will likely be fixed. Though I still don't know how that would affect it.

**Comment by baldurk** [comment]
It would be worth testing with some other known-good applications as well just in case - [Sascha Willems' samples](https://github.com/SaschaWillems/Vulkan) include a couple that use multiple queues which you could use for testing.

**Comment by farnoy** [comment]
Sascha's computeshader example works perfectly fine.

I think we can just drop this, it doesn't seem worth pursuing further, thanks for your time!
