### ISSUE TITLE
RenderDoc crashes when selecting DrawIndexedInstanced that has no index buffer bound on D3D12

### ISSUE THREAD

**Issue by wdegroot** [baldurk/renderdoc#1085]
## Description

I discovered this by mistake, but RenderDoc crashes when you select a DrawIndexedInstanced drawcall when no index buffer has been bound yet on D3D12. It's invalid behavior but I wouldn't expect a crash.

## Repro steps

These two lines should be enough to make it crash:
`m_commandList->Reset(m_commandAllocator, nullptr)`
`m_commandList->DrawIndexedInstanced(3, 1, 0, 0, 0);`

I've attached a zip with a modified D3D12HelloTriangle sample. It doesn't render anything but when you make a capture of the D3D12HelloTriangle project and select the drawcall RenderDoc crashes.

[D3D12HelloWorld.zip](https://github.com/baldurk/renderdoc/files/2311275/D3D12HelloWorld.zip)

## Environment

* RenderDoc build: v1.1 (built from c7d5aa86)
* Operating System: Windows 10 Version 1803
* API: D3D12

**Comment by baldurk** [comment]
Just to clarify - is this something that the D3D12 debug layers warn as invalid? In that case it's possible it works by coincidence on some GPUs but will crash on others the same as it crashes in RenderDoc.

RenderDoc is not intended to work with invalid API use, so if it's illegal then this would be up to the application to ensure and use API validation to check for. If it's a kind of valid-but-degenerate case then I can ensure it's handled properly.

**Comment by wdegroot** [comment]
No warning or error from the debug layer. But to be fair, the debug layer doesn't catch all the incorrect behavior cases.

I assume the driver will always return index 0 in this case?

**Comment by baldurk** [comment]
OK yeh I just wanted to clarify what it was. Unfortunately the D3D12 docs are as usual terrible, so I don't know whether the indices always return 0 or not, but if the debug layer doesn't mention it then it's probably legal in some manner. Returning 0 was the behaviour in D3D11 but in some ways D3D12 is not so forgiving of unbound/out of bounds behaviour.

To be honest I should probably flag this as an error renderdoc side since I can't imagine it's ever intentional.

**Comment by baldurk** [comment]
That commit should now check and at least not crash - though as expected you won't get any useful mesh output.
