### ISSUE TITLE
Missing Vulkan cache flushes and invalidates

### ISSUE THREAD

**Issue by gary-sweet** [baldurk/renderdoc#1090]
## Description

Our Vulkan driver supports real cached memory allocations that aren't coherent or write-through. This tends to uncover issues relating to missing cache flushes and invalidates that others miss.

We were seeing odd behavior in the renderdoc overlay rendering and also in the readback of images, buffers and meshes. Forcing our driver to use write-combined memory made all those errors disappear, which indicated that there were likely some missing flushes and invalidates.

I inspected the code, looking for calls to MapMemory and identified a number of missing cases which are addressed in a pull-request I have ready to go.

## Repro steps

Only visible on systems with genuine non-coherent, non-write-through cached memory.
Most obvious in the renderdoc overlay during capture. Text is garbled and often in the wrong place.

## Environment

* RenderDoc build: v1.1 and nightly builds
* Operating System: Linux
* API: Vulkan
* GPU: Broadcom VC6

**Comment by baldurk** [comment]
Thanks for the PR fix, that's very helpful. This was an oversight on my part since I hadn't come across such a memory type.

One problem that I don't have a solution for is that in future I have no way of testing that this stays working. I wonder if it's something the validation layers could (optionally) check for. Staging all memory to keep non-coherent memory separate, and do a copy from one buffer to another when you invalidate/flush. I guess it doesn't work if there are writes from both sides and you cache flush the whole buffer though :disappointed:. Any time you're able to test on your hardware I'd be grateful to hear of any bugs.

**Comment by gary-sweet** [comment]
The fix isn't really specific to just our memory configuration. Any memory that isn't allocated as coherent should be flushed and invalidated at the correct times. Most drivers probably just use write-combined cached memory allocations, so the fact that the memory hasn't been flushed just isn't generally visible.  We have an option to enable write-combined, which is how we found these issues.

> I wonder if it's something the validation layers could (optionally) check for, Staging all memory to keep non-coherent memory separate ...

I have a feeling they already do this. I remember back in the early lifetime of our Vulkan driver we found a number of bugs in the validation layers when they were doing just what you suggest, just not quite correctly.

> I guess it doesn't work if there are writes from both sides and you cache flush the whole buffer though.

I'm not sure that would be valid usage.

**Comment by baldurk** [comment]
Sure, what I meant was I don't know if I've come across a device that had non-coherent memory - though I haven't been looking out for it particularly so as you say I may have seen one and not realised since nothing went wrong.

I originally wanted to take advantage of non-coherent memory to make persistent maps significantly faster in renderdoc by tweaking the memory types to shove applications onto non-coherent memory so I could snoop flushes/invalidates. Unfortunately the spec requires coherent memory to exist in some form, and most applications just requiring coherent for their memory type selection anyway. That's a possible fix for renderdoc as well that's much less likely to regress in future.

**Comment by gary-sweet** [comment]
To be honest, I've yet to run a Vulkan app, benchmark, demo or tool that has got all of its flushes and invalidates correct.

We could, of course, just turn on write-combining as our default driver mode, but then we wouldn't find any of these bugs ;-)

**Comment by baldurk** [comment]
I'm going to close this now that #1092 and #1093 are merged. If you run into anything else and don't want to just PR directly, feel free to comment here or open a new issue.

**Comment by gary-sweet** [comment]
Sure, no problem. Thanks
