### ISSUE TITLE
WrappedVulkan::vkCreateImage can create images with invalid usage flags

### ISSUE THREAD

**Issue by gary-sweet** [baldurk/renderdoc#1098]
## Description

WrappedVulkan::vkCreateImage is adjusting the usage flags for the image create. In some cases, this is resulting in invalid combinations.

I'm running gfxbench50 on a platform that doesn't support sampling from linear-tiling textures (only optimal-tiling). 

Line 1397 in vk_resource_funcs.cpp adds VK_IMAGE_USAGE_SAMPLED_BIT to the flags without actually checking whether that is a valid thing to do using vkGetPhysicalDeviceFormatProperties().

In my case this results in trying to create a _linear_-tiled 2D ASTC4x4 image with SAMPLED usage, which is invalid on my platform.

## Repro steps

./renderdoccmd capture gfxbench50 -b gfxbench50_data -t vulkan_5_normal
will provoke the issue, but only on a system where linear-tiled texturing isn't supported.

## Environment

* RenderDoc build: v1.x
* Operating System: Embedded Linux
* API: Vulkan
* GPU: Broadcom VC6

**Comment by baldurk** [comment]
Yeh this is added so that I can display textures on replay, and since usage flags can (and do) affect memory requirements I add it during capture too.

What usage flags _are_ supported for the format if sampling isn't? An image that can't be sampled seems kind of pointless. As long as it supports `TRANSFER_SRC_BIT` I can probably set something up to copy out to an optimal tiled image of the same format - assuming that optimal tiling does support sampling.

**Comment by gary-sweet** [comment]
Linear-tiled images support TRANSFER_SRC_BIT and TRANSFER_DST_BIT, which means they can be filled with raster-order data by the host, and be read back in raster-order if required. Transfer operations can be used to convert these into optimal-tiled images which will support sampling.

They are essentially just staging buffers used to get data into the hardware in a format-agnostic manner. Every vendor has different optimal-tiled image formats, so linear-tiled images are the only common format.

> An image that can't be sampled seems kind of pointless

There is a good reason for not supporting sampling on linear-tiled images; they are a lot less efficient than optimal-tiled ones.

GPU architectures, caches and memory systems are designed around their internal texture formats (optimal-tiled images) which aim to keep spatially local accesses close together in memory. These are generally quite different layouts from raster-ordered images. Texturing from raster-ordered images, especially when they are rotated 90 degrees for example, is much less efficient since the accesses are no longer close in memory resulting in extremely poor cache behaviour and increased memory bandwidth.

**Comment by baldurk** [comment]
I understand the reason for opaque tiled/swizzled formats and the distinction from linear, and I get why you wouldn't want to support linear sampling for formats. What I meant was it seems strange to have a format that is supported for some other usage, but not for sampling. I was imagining e.g. a format that supported color attachment but not sampling.

In an older API like GL you'd need staging images (if you had to stage at all) because it only supports image-to-image copies, but in vulkan you stage from a plain buffer with `vkCmdCopyBufferToImage` / `vkCmdCopyImageToBuffer` which is much nicer. That's what applications should do and is e.g. how initial state copies are done in RenderDoc. It's relatively common for IHVs to report no support for formats that they can't sample from linearly, meaning applications are forced to do the right thing anyway with buffer copies to get data into an optimally tiled images.

Either way, if transfer is supported on the format then in theory this could be fixed with an extra copy in that case.

**Comment by gary-sweet** [comment]
> What I meant was it seems strange to have a format that is supported for some other usage, but not for sampling. I was imagining e.g. a format that supported color attachment but not sampling.

Some of our backend presentation paths can only accept raster-order (linear) images, so in some cases our swapchain images have to be linear, and wouldn't be sample-able.

> ... in vulkan you stage from a plain buffer ...

I guess that's a choice made by the application at the end of the day. They have the choice to stage from a buffer or from a linear-image. I'm pretty sure we've seen both cases, but I take your point.

> Either way, if transfer is supported on the format then in theory this could be fixed with an extra copy in that case.

Agreed, thanks.

**Comment by baldurk** [comment]
Fortunately there is an easier and more robust alternative - the format support required by the spec all requires TRANSFER & SAMPLED but only for optimal tiled images, so instead I just snoop the format support queries and remove reported support for any formats that don't support at least those usage bits.

This still means that any required format support is still reported as normal, it just removes any optional format support that isn't useful.

**Comment by gary-sweet** [comment]
> Fortunately there is an easier and more robust alternative  ...

Sounds like a reasonable compromise. I guess you might not be capturing the exact behaviour of the system running outside of RenderDoc though. Hopefully that won't prove problematic.

**Comment by gary-sweet** [comment]
I've just tested this with my original use-case and unfortunately it hasn't really helped much.

It looks like the application under test (GfxBench 5.0) is assuming that it can use linear tiled images for texture staging, without falling back to using buffers if they aren't supported.

I see the following API trace:

> vkCreateImage(device, pCreateInfo, pAllocator, pImage) returns VkResult VK_SUCCESS (0):                         
>     device:                         VkDevice = 0x9ced84                                                         
>     pCreateInfo:                    const VkImageCreateInfo* = 0xbe98f4a4:                                      
>         sType:                          VkStructureType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO (14)              
>         pNext:                          const void* = NULL                                                      
>         flags:                          VkImageCreateFlags = 0                                                  
>         imageType:                      VkImageType = VK_IMAGE_TYPE_2D (1)                                      
>         format:                         VkFormat = VK_FORMAT_ASTC_4x4_UNORM_BLOCK (157)                         
>         extent:                         VkExtent3D = 0xbe98f4b8:                                                
>             width:                          uint32_t = 128                                                      
>             height:                         uint32_t = 128                                                      
>             depth:                          uint32_t = 1                                                        
>         mipLevels:                      uint32_t = 8                                                            
>         arrayLayers:                    uint32_t = 1                                                            
>         samples:                        VkSampleCountFlagBits = 1 (VK_SAMPLE_COUNT_1_BIT)                       
>         tiling:                         VkImageTiling = VK_IMAGE_TILING_OPTIMAL (0)                             
>         usage:                          VkImageUsageFlags = 7 (VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_
>         sharingMode:                    VkSharingMode = VK_SHARING_MODE_EXCLUSIVE (0)                           
>         queueFamilyIndexCount:          uint32_t = 0                                                            
>         pQueueFamilyIndices:            const uint32_t* = UNUSED                                                
>         initialLayout:                  VkImageLayout = VK_IMAGE_LAYOUT_PREINITIALIZED (8)                      
>     pAllocator:                     const VkAllocationCallbacks* = NULL                                         
>     pImage:                         VkImage* = 12995216
> 

I believe RenderDoc has changed the tiling to optimal, by the initialLayout is still VK_IMAGE_LAYOUT_PREINITIALIZED, which is only valid for linear tiled images.

One could argue that this is just a bug in GfxBench, and that may well be true, but it's also a pretty common pattern for texture staging.  Can we reasonably expect all apps to implement a staging fallback using buffers if linear textures aren't supported?

**Comment by baldurk** [comment]
I think this is a clear bug in GfxBench, I don't think one could argue that it's not. RenderDoc only adds usage bits that it will need internally, so I'd guess the invalid optimal tiling in this case is part of the way the bug exhibits.

To be honest my expectation is for apps to just always use buffers. Using linear textures purely for staging is unnecessary and has extra restrictions like using `vkGetImageSubresourceLayout` to figure out the offsets and pitches rather than always allowing tightly packed upload. Linear images that can be sampled have value since it could allow e.g. rendering from a UI texture that's updated at high frequency on the CPU and has low bandwidth requirements, but in that case RenderDoc will work fine because the sampled usage is all it needs.

**Comment by gary-sweet** [comment]
I agree it's a bug in GfxBench. My concern was how often that same bug may appear in other apps, provoked by this particular change in RenderDoc, which is why I mentioned it.
