### ISSUE TITLE
What should I do if global hook went wrong and .reg file cannot restore the previous registry

### ISSUE THREAD

**Issue by PenroseWang** [baldurk/renderdoc#1099]
## Description

I've been using Global Hook for capturing images from a game. And for some reason the game (or Renderdoc, I cannot recall) crashes and now Global Hook are injected to every app/process and there is overlay for some apps I am using like Blender, Chrome (in a word, every app that uses GPU). I've tried to run .reg file to restore the registry to its previous state, but it didn't work. And I also tried to uninstall Renderdoc, still didn't help. So I am asking what should I do under these circumstances.

**Comment by baldurk** [comment]
This is one reason why you should only use the global hook if you know what you are doing and understand the consequences that can go wrong if RenderDoc crashes while it's active. The .reg only works if you load it immediately after RenderDoc crashes to restore the previous contents of the registry keys - otherwise it will have the already-active global hook listed in there.

To fix it manually, go to the registry keys referenced in the .reg file and reset `AppInit_DLLs` to an empty string, and set `LoadAppInit_DLLs` to 0, that should disable the global hook.
