### ISSUE TITLE
Linux: Launching application fails

### ISSUE THREAD

**Issue by jonathansty** [baldurk/renderdoc#1108]
## Description
When trying to launch an application with renderdoc it fails to open an application. 

Note: If you start renderdoc from the terminal it will be able to open the application.

The way I am starting the application is through the start menu of Ubuntu Budgie's default desktop environment. The editor is called `menulibre` which creates *.desktop files (If I'm correct). 

## Repro steps
1. Create a *.desktop file to launch renderdoc
```
[Desktop Entry]
Version=1.1
Type=Application
Name=Renderdoc
Comment=A small descriptive blurb about this application.
Icon=2402_msiexec.0
Exec=/home/jonathan/projects/renderdoc_1.1/bin/qrenderdoc
Terminal=true
Actions=
Categories=Development;Graphics;
```
2. Launch renderdoc using this file
3. Select an application to launch, in my case this is a small graphics app using rust
4. click launch
5. nothing happens

The diagnostic log for 2 launch tries is:
```
RDOC 013252: [23:48:47]             core.cpp( 300) - Log     - RenderDoc v1.1 64-bit Development (c7d5aa863e5f13430b2230e5048d253d342d1a18) loaded in replay application
QTRD 013252: [23:48:47]       qrenderdoc.cpp(  88) - Log     - QRenderDoc initialising.
RDOC 013277: [23:48:52]             core.cpp( 300) - Log     - RenderDoc v1.1 64-bit Development (c7d5aa863e5f13430b2230e5048d253d342d1a18) capturing application
RDOC 013277: [23:48:52]   posix_libentry.cpp(  59) - Log     - Using delay for debugger 0
RDOC 013277: [23:48:52]   posix_libentry.cpp(  69) - Log     - Loading into /home/jonathan/projects/experiments/pong/target/debug/pong
RDOC 013277: [23:48:52]         gl_hooks.cpp( 168) - Log     - Registering OpenGL hooks
RDOC 013277: [23:48:52]        glx_hooks.cpp( 671) - Log     - Registering GLX hooks
RDOC 013277: [23:48:52]        egl_hooks.cpp( 580) - Log     - Registering EGL hooks
RDOC 013277: [23:48:52]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
RDOC 013252: [23:48:52]    posix_network.cpp( 461) - Debug   - ECONNREFUSED: A connection was refused.
RDOC 013252: [23:48:52]    posix_network.cpp( 461) - Debug   - ECONNREFUSED: A connection was refused.
RDOC 013252: [23:48:52]    posix_network.cpp( 473) - Debug   - Failed to connect to localhost:38920
RDOC 013353: [23:49:04]             core.cpp( 300) - Log     - RenderDoc v1.1 64-bit Development (c7d5aa863e5f13430b2230e5048d253d342d1a18) capturing application
RDOC 013353: [23:49:04]   posix_libentry.cpp(  59) - Log     - Using delay for debugger 0
RDOC 013353: [23:49:04]   posix_libentry.cpp(  69) - Log     - Loading into /home/jonathan/projects/experiments/pong/target/debug/pong
RDOC 013353: [23:49:04]         gl_hooks.cpp( 168) - Log     - Registering OpenGL hooks
RDOC 013353: [23:49:04]        glx_hooks.cpp( 671) - Log     - Registering GLX hooks
RDOC 013353: [23:49:04]        egl_hooks.cpp( 580) - Log     - Registering EGL hooks
RDOC 013353: [23:49:04]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
RDOC 013252: [23:49:04]    posix_network.cpp( 461) - Debug   - ECONNREFUSED: A connection was refused.
RDOC 013252: [23:49:04]    posix_network.cpp( 461) - Debug   - ECONNREFUSED: A connection was refused.
RDOC 013252: [23:49:04]    posix_network.cpp( 473) - Debug   - Failed to connect to localhost:38920

```
## Environment

* RenderDoc build: 1.1
* Operating System: Pop!_Os using Budgie desktop as DE
* API: Vulkan in rust (vulkano)

**Comment by baldurk** [comment]
Just to clarify since I'm not entirely sure - are you saying that this only happens when `qrenderdoc` is run from the `.desktop` file you created? Running it from a terminal works OK?

If so, could you try using the `renderdoc.desktop` file from the 1.1 build or [source tree](https://github.com/baldurk/renderdoc/blob/v1.x/qrenderdoc/share/renderdoc.desktop) and capturing a known-good program like [gears3d](https://github.com/gears3d/gears3d)? I tested it just now on my Ubuntu install with the default desktop file and it works OK for me capturing gears3d.

It's not feasible for me to install your ubuntu variant and desktop environment, so if it's only happening while run from a desktop file on your system I'd need more information about what's actually going wrong.

From the log the process is starting, but then it exits before a control connection is made (the `ECONNREFUSED` errors) or displays a window as you say. If you added logging or something into your application you could see if it reaches `main`, and if so then how far it gets. If you could attach a debugger and see where and why it exits that would also be useful.

**Comment by jonathansty** [comment]
> Just to clarify since I'm not entirely sure - are you saying that this only happens when qrenderdoc is run from the .desktop file you created? Running it from a terminal works OK?

Yes, that is the problem. 

I will give running gears3d a try using the .desktop file provided. My application has logging, the very first thing it does is intialises a logger, although thinking of it. Anyways, when I get home tonight I will have a look if I can get it running properly and update this issue.

**Comment by jonathansty** [comment]
Alright, seems to be that my app is crashing when trying to initialize the logging system I was using. But not when running in a terminal. 

So no worries doesn't seem to be a renderdoc issue.
