### ISSUE TITLE
Feature request: VK_EXT_descriptor_indexing support?

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#1111]
RenderDoc currently doesn't support VK_EXT_descriptor_indexing , which provides variable sized descriptor arrays, for example.

Would love to see it supported in RenderDoc :)

**Comment by baldurk** [comment]
I think most of the guarantees in the extension about descriptor update timing and lifetime probably Just Work&trade; since I only fetch descriptor contents at submit time, and should handle unbound descriptors gracefully (since I don't do static use analysis either).

However bindless is difficult for tools to handle properly and it will need new functionality to figure out from dynamic inspection which descriptors are used or not. Until that happens I'm extremely reticent to report support for this extension. There's not much point in being able to capture and replay if the debugger is then useless.

Supporting bindless properly is certainly a goal, so it's definitely on my list, but I wouldn't expect it soon.

**Comment by farnoy** [comment]
I'm not sure if it's relevant, but can the work done in GPU assisted validation layers be of help to RenderDoc? Specifically to "figure out from dynamic inspection which descriptors are used or not".

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/gpu_validation.md#gpu-assisted-validation-checks

**Comment by baldurk** [comment]
There's no direct relation between the validation layers and RenderDoc. Aside from needing to solve similar problems no code is shared.

Supporting this extension is still on my radar, don't worry!

**Comment by manhnt9** [comment]
I would like have this as well.

**Comment by baldurk** [comment]
I've implemented support for the extension as well as feedback to show which indices are used - that will work regardless of whether you're using the extension or the base vulkan support for descriptor arrays.

You'll get something like this by default in the pipeline state view with only used indices visible:

![image](https://user-images.githubusercontent.com/661798/55641801-b139b100-57c6-11e9-90ec-4ab14aeb6f33.png)

This also extends to the thumbnails in the texture viewer.

**Comment by farnoy** [comment]
Oh this is brilliant, can't wait to try it. Thanks Baldur!
