### ISSUE TITLE
D32S8 renderbuffer generating "Framebuffer bindings are not framebuffer complete"

### ISSUE THREAD

**Issue by moll** [baldurk/renderdoc#1116]
Hey,

I noticed my NVIDIA driver defaults `GL_DEPTH_STENCIL` to `D32S8` in a fresh renderbuffer. Is that supposed to work and be displayed out of the box? I'm seeing a black image with no values. `GL_DEPTH24_STENCIL8` works as expected.

Thanks!

**Comment by moll** [comment]
`GL_DEPTH_COMPONENT` by itself defaults to `D32` and that also works.

**Comment by baldurk** [comment]
Can you please give more information about the bug and the exact setup that your application is using? Asking if a very common depth-stencil format is broken isn't too helpful because it's used in many programs that are working fine - the bug you are running into will have some more specific circumstances that will need to be isolated before it can be reproduced and fixed.

The issue template that you could have used, which appears when you create a new issue, guides you along the lines of the kind of information that is needed: details about your platform & configuration, and more importantly repro steps such as code snippets, a full application or a capture that shows the problem.

**Comment by moll** [comment]
Hi! You're correct my report above lacks details, but that was because it was preliminary --- to check whether it's _supposed_ to work. :) Doing proper bug reports is very time consuming and occasionally it turns out a particular feature isn't even implemented. Had that experience just last week with a Blender plugin, for example.

As for this issue, thanks for confirming it probably should work! I ended up going with another depth-stencil combination (`D32` with no stencil) that RenderDoc showed nicely, so unfortunately I don't have the time to dig too deep into this. It's probably safer to assume it was an issue on my end now that you've confirmed `D38S8` generally works. I'll close the issue until I get around to dig deeper. :)

For the record, these were the versions involved:
* RenderDoc build: v1.1
* Operating System: Arch Linux (https://aur.archlinux.org/packages/renderdoc)
* API: OpenGL with forward compat, core profile.
* NVIDIA: 396.54-3

Thanks again!

**Comment by baldurk** [comment]
I understand that bug reports can be time consuming, that's entirely fair. I feel the same way sometimes when a bug report feels like it goes into a black hole and is ignored, but I'd ask a little faith to start with :).

If you're unsure whether you're hitting a bug or a missing feature, it's best just to start with the basic three things - a description of what you're doing, what results you actually get, and what results you'd expect. In this case the key point would be to explain exactly how you're creating the GL_DEPTH32F_STENCIL8 texture and binding it to the framebuffer - ideally with a few pasted lines of code showing your initialisation, and that when viewing it you get black instead of the actual depth data.

Because you're talking about GL, there are often dozens of ways to do very similar things and it might be that only the one particular path you are taking actually leads to a problem with X and Y and Z all happening together. That's why here in particular it's important to get a precise idea of how you're creating and binding your textures. One of the variables you've found is specifying D32S8, since D32 works fine, but that doesn't tell the whole story as it's not _only_ specifying D32S8 that breaks.

In this case, unless it's something private that can't be shared, uploading the broken capture would be a good way to provide a direct repro case with minimal effort. You can either email to me directly or post a link here. Sometimes a bug isn't fully explained by a capture but it at least gives me something to start with that is easy to report.

**Comment by moll** [comment]
> I understand that bug reports can be time consuming, that's entirely fair. I feel the same way sometimes when a bug report feels like it goes into a black hole and is ignored, but I'd ask a little faith to start with :). If you're unsure whether you're hitting a bug or a missing feature, it's best just to start with the basic three things - a description of what you're doing, what results you actually get, and what results you'd expect.

I'm a relatively new OpenGL-er and a 40-bit format of `D32S8` did sound unique enough to my untrained eye to question whether it was supposed to be supported. :) I totally concur that once it's known to have to work, technical details should follow, and they will! That's because unfortunately I've seen RenderDoc continue to misbehave around viewing the states of some renderbuffers, so I'm now more than happy to troubleshoot that.

I can extract a minimum scene and create a capture from that, but to set up some context:
I'm using Haskell with its [GL library](http://hackage.haskell.org/package/gl) and rendering first to a separate framebuffer, then blitting only the color renderbuffer over to the window's back buffer. The rendered-to framebuffer consists of 3 multisampled renderbuffers with 4 samples:
1. `GL_RGBA8`. `MS{4x 0Q} 1 mips - R8G8B8A8_UNOFMR` as shown by RenderDoc
2. `GL_DEPTH_STENCIL`. `MS{4x 0Q} 1 mips - D32S8` as shown by RenderDoc
2. `GL_R8UI`. `MS{4x 0Q} 1 mips - R8_UINT` as shown by RenderDoc

The first color buffer and the third integer buffer seem to show correctly, however when clicking on the depth-stencil buffer, the following gets printed to stdout of RenderDoc:
``` 
Warning - Unexpected raw format for stencil visualization
Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 1286, severity GL_DEBUG_SEVERITY_HIGH:
'GL_INVALID_FRAMEBUFFER_OPERATION error generated. Framebuffer bindings are not framebuffer complete.'
```
When moving my mouse over the depth-stencil, more `GL_INVALID_FRAMEBUFFER_OPERATION` get generated. Would that perhaps indicate that something's going on not with reading `D32S8` in, but with RenderDoc displaying it?

While we're on the topic of displaying renderbuffers, what's the logic around showing integer buffers (the `GL_R8UI` above)? RenderDoc seems to show values of 0 as black and values of >= 1 as pure white, while I'd expect black-white to range from 0--255 by default. I do realize the range picker permits configuring it as such, but why not default to it?

Thanks again and thanks in advance!

**Comment by baldurk** [comment]
As I mentioned above you don't necessarily have to make a minimal repro, most bugs can be repro'd even from the full scene just fine, I don't need you to isolate the exact problem and no more. Unless there's something in the full capture that is confidential and you can't share, you don't have to spend time reducing the test case. There's a fair chance that just the normal capture alone will give me the information I need.

Otherwise if you can't, I still need more precise details about exactly how you're creating your framebuffer, more than the formats. For example, I've modified a GL sample to contain this code (summarised) that is set up as you're describing:

```cpp
GLuint rgba8unorm, depth, r8uint;

glGenTextures(1, &rgba8unorm);
glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, rgba8unorm);
glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, 4, GL_RGBA8, WindowSize.x, WindowSize.y, GL_TRUE);

glGenTextures(1, &depth);
glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, depth);
glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, 4, GL_DEPTH32F_STENCIL8, WindowSize.x, WindowSize.y, GL_TRUE);

glGenTextures(1, &r8uint);
glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, r8uint);
glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, 4, GL_R8UI, WindowSize.x, WindowSize.y, GL_TRUE);

glGenFramebuffers(1, &FramebufferName);
glBindFramebuffer(GL_FRAMEBUFFER, FramebufferName);
glFramebufferTexture(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, rgba8unorm, 0);
glFramebufferTexture(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT1, r8uint, 0);
glFramebufferTexture(GL_FRAMEBUFFER, GL_DEPTH_STENCIL_ATTACHMENT, depth, 0);

GLuint buffers[] = { GL_COLOR_ATTACHMENT0, GL_COLOR_ATTACHMENT1 };
glDrawBuffers(2, buffers);
```

But that works for me though - can you tell me in what ways your code is different?

Regarding previewing int textures, for the case of R8 then 0-255 might make sense, but for most int textures 0-INT_MAX is often not any more helpful than 0-1. I avoid trying to have the program make 'smart' decisions on behalf of the user which is usually much more annoying when it gets it wrong than the inconvenience of configuring it yourself. I don't feel that there is a good default, so in the lack of it I'd rather pick a bad but consistent default.

The auto-fitting button allows you to change the scale to match the minimum and maximum values in the texture in one click.

**Comment by moll** [comment]
Thanks for the continued help! I'll go about seeing getting a capture, but to quickly point out the discrepancy between our attempts is that I was using renderbuffers, not textures. Roughly the following:
```
glGenFramebuffers
glBindRenderbuffer
glRenderbufferStorageMultisample Gl.GL_RENDERBUFFER 4 format width height
```
with `format` being `GL_RGBA8`, `GL_DEPTH_STENCIL` and `GL_R8UI`.
Then bound the renderbuffers to the framebuffer with `glNamedFramebufferRenderbuffer`.

**Comment by baldurk** [comment]
OK I can repro this now. Multisampled doesn't matter, but if you create a renderbuffer (not a texture), with `GL_DEPTH_STENCIL` (not a proper sized format), then nvidia seems to have a driver bug.

The issue is that I need to create a separate internal display texture for every renderbuffer, and blit into it constantly to allow actually displaying the contents. Nvidia allocates 24 bits internally for the renderbuffer with `GL_DEPTH_STENCIL`, but 32 bits for an identical _texture_ with `GL_DEPTH_STENCIL`. It then disallows blitting between them - even though they were created with equivalent (unsized) formats and AFAIK should allow blitting. AMD works because it seems to assign 24 bits for the same format in both cases.

The workaround would be as you found to declare an explicit depth-stencil size, or else to use textures rather than renderbuffers.

I think I can fix it, I can check what sized format was _actually_ allocated and use a explicitly sized format to create the texture. I had to remove explicit-sizing everywhere because there are extremely buggy parts of GL around unsized formats, but since this is an internal texture and I leave the renderbuffer with the original format, it should probably be OK.

**Comment by baldurk** [comment]
In my repro case that I got similar behaviour in, that commit fixed the issues I was having. Let me know if it doesn't work for you.

**Comment by moll** [comment]
Great! Thank you!

Btw, left you a little code comment in https://github.com/baldurk/renderdoc/commit/0ffff7d5dabea50428fc97809704b469a26a065a. :)
