### ISSUE TITLE
DX11 severity breaks not working if dll is loaded

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1121]
## Description

We've recently integrated renderdoc natively in our engine so that we can programatically make captures via a UI button instead of loading the executable through renderdoc. To that effect the game loads the dll as the instructions say and everything works fine.

The issue though is that we also have a command line to enable validation on d3d and set "break on severity" sort of options on the device creation, but as it turns out they don't work if renderdoc is loaded. It took me a while to figure out why no errors were being printed out and it's because renderdoc captures them and our application doesn't receive them anymore. Is there any way around this or do we need to disable renderdoc to get our validation back?

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: Windows 7
* API: D3D11

**Comment by baldurk** [comment]
Yes this is deliberate behaviour, RenderDoc takes control over the debug layer so that there isn't a conflict with the application. Unfortunately by its design only one thing can be fetching messages from ID3D11InfoQueue at any time.

When running with RenderDoc it's usually not super useful to get debug messages anyway unless you've opted into RenderDoc's tracking & management - and having RenderDoc enabled constantly is something I recommend against. When integrating RenderDoc I'd suggest having it be an opt-in option to enable when you need it, or if you can load it dynamically and re-initialise your renderer at runtime then do that.

This came up before in #418 and I added a backdoor UUID `{3FC4E618-3F70-452A-8B8F-A73ACCB58E3D}` that you can use at your own risk of breaking things, to query for the real ID3D11InfoQueue. As long as you've enabled the API validation capture option that will give you access to it. It looks like I haven't documented that anywhere so I can do that, but otherwise I don't plan to change this behaviour.

**Comment by baldurk** [comment]
I've added a FAQ entry about this into the docs.

**Comment by redorav** [comment]
Thanks a lot for your quick reply! I'll see if I can/should workaround the issue based on your comments.
