### ISSUE TITLE
RENDERDOC_ResourceFormatName shows up in CPU profiles

### ISSUE THREAD

**Issue by vaspoul** [baldurk/renderdoc#1127]
## Description

We recently hooked up the RenderDoc DLL to our engine and noticed that RENDERDOC_ResourceFormatName shows up high when profiling the loading code.

It looks like it's coming from ResourceFormat::Name()

  rdcstr Name() const
  {
    rdcstr ret;
    RENDERDOC_ResourceFormatName(*this, ret);
    return ret;
  }

Is it worth caching the returned string?

**Comment by baldurk** [comment]
Are you definitely sure that the profiling is actually pointing to `RENDERDOC_ResourceFormatName` and that it's not a false positive? I think what might be happening is that you don't have symbols loaded in your profiler for renderdoc.dll, so the profiler is assigning all code after that export to it:

![image](https://user-images.githubusercontent.com/661798/46867013-6f354100-ce1b-11e8-9321-619278a1fdba.png)

It's not a very good default behaviour since it can be confusing and it would be better just to show unresolved hex addresses, but it's quite common. What are the callstacks you have where it actually gets to that function? It should only get called normally via the replay-analysis API, and I guess they will show an 'impossible' stack like when calling a graphics API function.

The RenderDoc symbols are available in a symbol server at [https://renderdoc.org/symbols](https://renderdoc.org/symbols), though as a side note I did notice today that they've been broken for about the last 6 weeks. It has symbols for v1.1 and nightly builds up to 2018-08-20, and for the latest nightly build that I just re-ran.

**Comment by vaspoul** [comment]
You're absolutely right! I saw something like

<our create texture function> -> ENDERDOC_ResourceFormatName -> memcpy

and I assumed it was some kind of string copying.

Building from source does indeed show a different callstack:

memcpy
renderdoc.dll!MapIntercept::CopyFromD3D()
renderdoc.dll!WrappedID3D11Device::Serialise_CreateTextureData<Wri...
renderdoc.dll!WrappedID3D11Device::Serialise_CreateTexture2D<Write...
renderdoc.dll!WrappedID3D11Device::CreateTexture2D(const D3D11_TEXT...
<our create texture function>

Which looks like it's making of copy of the texture data, which I assume that's an essential part of RenderDoc's operation and can't be disabled without limiting functionality.
