### ISSUE TITLE
Compute shader and syncronization issue.

### ISSUE THREAD

**Issue by andre-ferreira** [baldurk/renderdoc#1128]
## Description
Hello!

I am unsure if this is a bug on my code or an unsupported feature/bug on renderdoc but this is the issue i have:
If i run my program outside of renderdoc i get the correct values from a CPU/GPU memory pointer. However if i use renderdoc i  always get the maximum possible value of a GLuint  read into my program instead of a normal value. If i capture a frame i see the correct value in the buffer inside the dispatch command.

## Repro steps

My program uses the standard sync method of getting a pointer to memory using glMapBufferRange once and then reading/writing to pointer value using sync fences i.e.:

```
GLuint nTriangles;
			
// Wait for all commands are finished
waitSync();

// read the shared CPU/GPU memory for the value
nTriangles = *nTrianglesCounter;

lockSync();

std::cout << "nTriangles: " << nTriangles << std::endl;

```

with:

```
void waitSync(void)
{
	// waiting for the buffer
	GLenum waitReturn = GL_UNSIGNALED;

	while (waitReturn != GL_ALREADY_SIGNALED && waitReturn != GL_CONDITION_SATISFIED)
		waitReturn = glClientWaitSync(atomicSync, GL_SYNC_FLUSH_COMMANDS_BIT, 1);
}


void lockSync(void)
{
	// lock the buffer:
	glDeleteSync(atomicSync);
	atomicSync = glFenceSync(GL_SYNC_GPU_COMMANDS_COMPLETE, 0);
}
```

## Environment

* RenderDoc 2018-10-14 nightly build.
* Operating System: Windows 10
* API: OpenGL
* GPU: Nvidia 940m v398.82

Edit: Looking at the issues this might be the same issue as #677

**Comment by baldurk** [comment]
Is this a persistent map of the buffer? It's unclear if you're using `glMapBufferRange` whenever you want to read the value or not.

If it is persistent then yes this is the same issue as #677.

**Comment by andre-ferreira** [comment]
Yeah its a persistent map, i just use glMapBufferRange once at the beginning with the flags:

```
nTrianglesCounter = (GLuint*)glMapBufferRange(GL_ATOMIC_COUNTER_BUFFER,
		0,
		sizeof(GLuint),
		GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT | GL_MAP_READ_BIT
	);
```

Any workarounds/better way of read/write to a atomic buffer that work with renderdoc?

What i am looking for is:
- Reset atomic counter (for this i am using a glClearBufferData as i understand its faster than a CPU/GPU memory write)
- Run compute shader which will write to an atomic counter
- Read atomic counter after shader has finished

Thanks,
André

**Comment by baldurk** [comment]
The simplest workaround would just be to map the buffer each time you need to read it, but I don't know how much impact that will have on performance, whether it would be negligible or noticeable. Another alternative would be not to map the atomic buffer directly but to have a staging buffer that you copy to when the shader has finished, and read from that.

Currently RenderDoc will always intercept a persistent map and redirect it to its own allocated pointer for change tracking, which is why you're not seeing the written values because that allocation isn't updated from GPU writes, it only copies from CPU -> GPU. Currently I don't have a good idea of how to solve #677 because when both sides of the map can be updated it's not really possible in general to know which way to copy on changes without overwriting data incorrectly. In your case if it's read-only that could potentially be handled correctly but that solution wouldn't extend to the general read-write case.

Since it is a duplicate though, I'm going to close this issue.

**Comment by andre-ferreira** [comment]
> In your case if it's read-only that could potentially be handled correctly but that solution wouldn't extend to the general read-write case.

Well, it doesn't seem to be working from with read only because i am getting bad results using:

```
nTrianglesCounter = (GLuint*)glMapBufferRange(GL_ATOMIC_COUNTER_BUFFER,
		0,
		sizeof(GLuint),
		GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT | GL_MAP_READ_BIT
	);
```
But yes its the same issue.

**Comment by baldurk** [comment]
I mean that RenderDoc currently doesn't handle the read-only case correctly, as you've found, but that is an easier case to handle correctly in the future since for read-only maps I can just pass it through to GL as long as I detect them).

**Comment by andre-ferreira** [comment]
Ah okay okay, sorry i misunderstood it. Thanks anyway!

**Comment by baldurk** [comment]
That commit should detect read-only maps and pass them straight through to GL, which means you'll get the right results back. I set up a simple example using an atomic counter buffer like you had and it worked OK, but there might still be some issues there.

This only applies to buffers and maps that are completely read-only, anything read-write still suffers from the same issue as #677.

**Comment by andre-ferreira** [comment]
I tried yesterdays nightly build and it seems to be working now! Many thanks! If i run into some kind of issue using read only buffers i will let you know.

Cheers!

**Comment by andre-ferreira** [comment]
Okay it seems that it isnt completely gone. If i use the following code it will give me the max number of GLuint for the nTriangles variable:

```
/////////////////////////////////////////
// Get number of triangles
GLuint nTriangles;
	
// Wait for all commands are finished
waitSync();

// read the shared CPU/GPU memory for the value
nTriangles = *nTrianglesCounter;

memcpy(clientTriangles, ptr_triangles, sizeof(buoyancyTriangle) * MAX_POINTS);

lockSync();

std::cout << "nTriangles: " << nTriangles << std::endl;

if (nTriangles > 0)
{	
	buoyancyTriangles.clear();

	for (int i = 0; i < nTriangles; i++)
	{
		buoyancyTriangles.push_back(clientTriangles[i]);
	}
}
```
However if i change the nTriangles variable to a constant value in the "for" cycle it correctly reads the value, which doesnt really make any sense because im not reading the pointer anymore, just a local variable. Outside of RenderDoc it works correctly.
The "ptr_triangles" variable is also a read only buffer mapped in the same way as the atomic counter.

Thanks,
André

**Comment by baldurk** [comment]
I'm not sure I understand what you mean. You say that changing nTriangles to a constant value causes the previous read & print to get the right value? That sounds like perhaps your synchronisation is incorrect and rearranging compiled code has changed the execution.

I'd suggest trying to add `glFinish()` calls to see if that fixes the problem, and check your synchronisation. I don't understand exactly how you're trying to arrange it. I see that you have a sync which is signalled, then next time around you wait on it just before reading the value, but I don't understand how that ensures that your read happens after all the GPU work has finished, because the sync is signalled before any work happens.

If that doesn't help I can try and look at it, but I'd need full source that I can compile and run to test with.

**Comment by andre-ferreira** [comment]
Thank you for your answer. Adding a `glFinish()` did make things work correctly which means my sync is not working correctly as you suggested. I will look more into this,.


> but I don't understand how that ensures that your read happens after all the GPU work has finished, because the sync is signalled before any work happens.

Can you clarify on this? What im looking to do (for now) is to wait for GPU work to be done, read pointer, lock the fence again.

Before the gpu wait there is more code and a dispatch compute:

```
glMemoryBarrier(GL_TEXTURE_FETCH_BARRIER_BIT | GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT | GL_ATOMIC_COUNTER_BARRIER_BIT | GL_SHADER_STORAGE_BARRIER_BIT);
glDispatchCompute(triangles.size()/3, 1, 1);
```

Many thanks!

**Comment by andre-ferreira** [comment]
So it seems that my `waitSync()` is not waiting for the` glDispatchCompute(triangles.size()/3, 1, 1)` to be over before it reads. This only happens if i pass it in renderdoc but this might be due to the delay/lag that it introduces making it fail, and without using it, it could finish before the read even without the `waitSync()`

Cheers,
André

**Comment by baldurk** [comment]
> Can you clarify on this? What im looking to do (for now) is to wait for GPU work to be done, read pointer, lock the fence again.

Sorry I didn't see this because it was edited in after the original comment.

The issue I can see is that your wait doesn't seem to be waiting on the GPU work that you expect it to. Your pseudocode is something like this if I understand right:

```cpp
while(rendering frames)
{
  computeWork();

  waitSync();

  read nTriangles;

  lockSync();
}
```

But the way you defined `waitSync()` and `lockSync()` is that `lockSync()` sets the sync point, and `waitSync` waits on it. So when you execute the compute work, in principle the CPU and GPU are running simultaneously. When you hit `waitSync()` you wait for the *previous* `lockSync()` to complete on the GPU. If you're running in lockstep with the GPU this won't really do anything useful, and you'll keep going and read the `nTriangles` value with no guarantee that the GPU has finished.

If you only have a single `nTriangles` value that both GPU writes and CPU reads, then you can't do any better than lockstep. Using either `glFinish()` or manually doing `lockSync()` *then* `waitSync()` would cause the CPU to wait no the GPU, but then you have no parallelism. If you want the GPU to be running the next frame while you're reading the value for the previous frame, you need more than one atomic location.

That said, this bug isn't the best place to diagnose problems in your code if there's no indication that it's a renderdoc bug. Feel free to email me if you want more information but unless there's a renderdoc issue please move the conversation elsewhere.
