### ISSUE TITLE
Unable to launch application that is using Nvidia raytracing extension

### ISSUE THREAD

**Issue by iOrange** [baldurk/renderdoc#1148]
## Description

While trying to launch application that is using Nvidia Vulkan raytracing extension the application fails to start with error:
"vkCreateDevice failed due to missing extension.  Make sure VK_NV_RAYTRACING_EXTENSION is supported by installed driver!"

The application in question is running properly if launched directly.

## Repro steps

Try to launch any application that is using Nvidia Vulkan raytracing extension through RenderDoc 1.1

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 10 Pro  64bit
* API: e.g. Vulkan
* GPU: Nvidia RTX 2070
* Driver version: 416.34

**Comment by baldurk** [comment]
The nvidia raytracing extension is not supported by RenderDoc and almost certainly never will be.

Judging by the error message it looks like the application is doing the correct thing by enumerating the list of available extensions (from which RenderDoc will remove any unsupported extensions like the raytracing one) and failing out when it's not found.

**Comment by dictoon** [comment]
> The nvidia raytracing extension [...] almost certainly never will be [supported].

Out of curiosity, why?

**Comment by baldurk** [comment]
As a general rule I don't add support for vendor API extensions unless they're mostly trivial and 'free' to implement, which is definitely not the case for nvidia's RT extensions.

That means it would have to be contributed and maintained externally which I think is highly unlikely. Especially since it's likely that before too long a future cross-vendor standard extension will come out which would be within scope to support.

**Comment by dictoon** [comment]
That makes sense; thanks for the explanation.

**Comment by natevm** [comment]
@baldurk This doesn't make much sense. 

I understand not wanting to profile vendor specific commands, but those aren't all that I want to profile. I should be able to profile **non-raytracing** commands which coexist with raytracing commands. I need to profile draw calls and compute commands, which execute independently of the vendor specific commands. Surely RenderDoc could handle this is a more graceful way than crashing catastrophically and preventing me from profiling anything, vendor specific or not. Very annoying...

**Comment by baldurk** [comment]
Raytracing commands are not independent of other commands in a frame. The output of one can be used in the other and vice-versa. When debugging a capture if the raytracing commands are not replayed then debugging the whole frame will not be valid and you'll get incorrect and unpredictable results.

RenderDoc does already handle this gracefully - it removes the extension from the list of supported extensions, and returns an error code from vkCreateDevice if the extension is specified invalidly in spite of that. If the application doesn't correctly enumerate the available extensions and either fallback or exit, then that's an application problem.

**Comment by natevm** [comment]
Removing the extension prevents us from profiling raytracing renderpaths entirely, and is not an acceptable solution. An acceptable solution would be to not report ray tracing  specific information, but otherwise continue to work as expected.

It should not be needed to re-execute raytrace shaders to profile later shaders. Why does renderdoc need to replay the raytracing commands to profile later commands? I don’t understand why renderdoc can’t just cache the state of the changed image/SSBO descriptors before and after the trace rays call like with any other compute shader. I don’t see why renderdoc would need to re-execute the actual raytrace commands to do this. I must be missing something here...

All other raytraced calls could be ignored. I don’t expect renderdoc to be able to profile BVH builds, but I do expect renderdoc to be able to profile a simple compute shader used in the same application. 

Ultimately I should be able to profile a capture from any machine, regardless of whether that machine supports the extensions used by the capture or not. Stating it’s the applications job to ”just deal without” is not a practical solution and seemingly just an excuse to not think of a more usable solution. It’s non-trivial to write an entire raytracing renderpath without that extension (that’s why the extension exists in the first place), and although I could try using CUDA/Vulkan interop with OptiX, I don’t know if RenderDoc even supports interop, and this would significantly increase the technical complexity of my application, just so that I can validate some later non-raytracing compute shaders. 

IMO, this is still a critical bug, as it impedes workflow with no practical solution or workaround.

**Comment by baldurk** [comment]
I explained that RenderDoc removes the reported extension because you said that it should "handle this is a more graceful way than crashing catastrophically". That is the more graceful handling - the application may crash if it doesn't check for the extension being present (even by throwing an error message and exiting if it has no alternative), but RenderDoc behaves in the best way it can. It's the same as if you ran the program on an AMD GPU.

RenderDoc functions by replaying the commands recorded at capture time fully or partially and interspersing extra work to analyse the command stream and data. For that reason yes it will require all functionality the capture uses to be present on the replaying system. That includes raytracing, and means that the raytracing commands must be supported at a certain level to allow correct capture and replay, even if there isn't UI for introspecting those commands. There is no such before and after snapshotting as you describe for compute shaders.

This is a feature request, not a bug, and misrepresenting it doesn't make it any more likely to happen. I understand that without raytracing support then RenderDoc cannot be used to debug any part of a program that uses raytracing, and so within that context this lack of feature is a blocking issue. I'm not saying the application must have a fallback, only that RenderDoc cannot be used if an unsupported extension is a hard requirement. For some applications they may have a fallback to not use raytracing at all since it's currently only supported on a few cards on one vendor.

There are many features within graphics APIs which RenderDoc does not support and some it likely never will support. Indeed there are graphics APIs like metal which are not supported at all. That's the reality of having limited scope and engineering time, I have assessed and set priorities and some features will happen sooner, some later, and some very likely never. Writing aggressively worded demands on a project that you use for free is only likely to decrease the chances of your desired feature being added.

**Comment by natevm** [comment]
I apologize if it sounds like I'm making "aggressively worded demands". To be clear, I'm not demanding anything, just trying to understand the underlying problem.

`I understand that without raytracing support then RenderDoc cannot be used to debug any part of a program that uses raytracing, and so within that context this lack of feature is a blocking issue. `

This is exactly the context I'm describing. For personal projects I usually interpret "blocking issue" and "critical bug" as one an the same, but "blocking issue" is probably more accurate. 

`RenderDoc functions by replaying the commands recorded at capture time fully or partially and interspersing extra work to analyse the command stream and data. For that reason yes it will require all functionality the capture uses to be present on the replaying system. That includes raytracing, and means that the raytracing commands must be supported at a certain level to allow correct capture and replay, even if there isn't UI for introspecting those commands. There is no such before and after snapshotting as you describe for compute shaders.`

So RenderDoc currently requires replaying commands. I'm assuming implementing a snapshotting system like I'm describing would require some significant changes, and although it might be a more robust solution when applications require particular extensions, it would take a lot of work to implement. Still, I often profile on the same machine I'm running the application on, and so my machine should be able to replay any of the raytracing commands without that snapshotting work around.

`I'm not saying the application must have a fallback, only that RenderDoc cannot be used if an unsupported extension is a hard requirement.`

You're saying the application must have a fallback in order for RenderDoc to work. My point is that there isn't really a practical fallback option for raytracing developers though, so really, this assumption is the blocking issue. In some cases (like with raytracing), RenderDoc should not require a fallback to work.

`There are many features within graphics APIs which RenderDoc does not support and some it likely never will support. Indeed there are graphics APIs like metal which are not supported at all. That's the reality of having limited scope and engineering time, I have assessed and set priorities and some features will happen sooner, some later, and some very likely never. `

The nice thing about open source projects like this is that other developers can contribute. Sure, you have limited engineering time, and I understand that. I could personally work on the issue and submit a pull request if I get things working though. This issue is more of a priority to me, and so I might be able to help out. Seems like the first step would be for me to re-enable the extension in renderdoc, and see where things blow up. Do you know where in the RenderDoc codebase this extension is filtered out?

**Comment by baldurk** [comment]
I'm saying that raytracing plain isn't supported, not any more or less. If raytracing is an optional feature in your program (as is quite common currently while it is still a niche feature) then you can use RenderDoc, otherwise you can't. Raytracing isn't any different in this respect from any other feature in any API that RenderDoc doesn't support. Saying that RenderDoc "should not require a fallback to work" seems to me to assume implicitly that all optional API features must be supported as a principle.

Yes RenderDoc is open source and contributions are possible and generally welcome, but a PR which adds a feature must be supported and accounted for in future work and so comes with a cost. You are talking about a project of significant scale and complexity which would require a large amount of support in future. That's not something that can be dropped in easily with a PR or two, it would need a lot of work and a commitment to support it _forever_ either from myself or the PR author. In this case in addition I do not want to add opaque support for raytracing with no introspection ability, so either there is a plan and commitment to support it fully and completely or I'd prefer that it remain unsupported.

That doesn't preclude the possibility that outside contributions will add raytracing support in future, but I think you underestimate the scale of work required. If you're able to modify the source to get something working for your usecase then you are of course more than welcome to, not every source change must necessarily land upstream either.

This discussion has gotten significantly off topic so please don't continue commenting here - the original bug report was an application behaving entirely reasonably when an unsupported extension that it required was not present and that issue has been resolved. I've made it clear that I have no intention to support NV's raytracing extension in the future.

**Comment by natevm** [comment]
Well, that's disappointing to hear, especially since RenderDoc works quite well otherwise.

In the meantime, I've re-enabled the raytracing extension on this fork. Maybe we can get this working over there: [https://github.com/n8vm/renderdoc](https://github.com/n8vm/renderdoc )

**Comment by oscarbg** [comment]
@baldurk related to this.. do you plan to support the official KHR (still "provisional") raytracing extension?
Nvidia driver mentions:
VK_KHR_ray_tracing
VK_KHR_deferred_host_operations
VK_KHR_pipeline_library
VK_EXT_pipeline_creation_cache_control

maybe open a separate issue..

thanks..

**Comment by natevm** [comment]
@oscarbg For what it’s worth, I’ve found that since this post, Nsight Graphics (the stand-alone application) has come a long way, and does an awesome job at profiling/debugging Vulkan RT on both Windows and Linux. It recently added support for the official Vulkan ray tracing extensions too.  https://developer.nvidia.com/nsight-graphics-2020_2 

I’ve found the developers over there are very responsive to bug reports as well. Highly recommend checking out the latest release if you have an Nvidia card.

**Comment by baldurk** [comment]
Currently while the extension is provisional I won't be looking into it. Once it is finalised then it can be supported, and there is functionality within the extension to make capture and replay more feasible, however supporting raytracing properly is a huge amount of work and that will not be undertaken lightly. It will be a balance of priorities as with any other features, once there is enough benefit and user base to justify the work needed to support it properly then it will be looked at. For the current future I don't expect that to be the case for a while since there is more value in investing in features that will benefit a wide audience of users.

**Comment by kyamant** [comment]
@baldurk What is the current (and planned if any) situation regarding the support for Vulkan RayTracing extensions (not Nvidia specific)? I cannot use it with v 1.22.

**Comment by baldurk** [comment]
Please do not comment on old resolved issues.
