### ISSUE TITLE
VkPhysicalDeviceFeatures2KHR not serialised or patched in vkCreateDevice

### ISSUE THREAD

**Issue by aejsmith** [baldurk/renderdoc#1157]
## Description

On Android (specifically, 8.0.0 on a Samsung Note 8 with Mali-G71), if an app is launched through RenderDoc, and the app uses VkPhysicalDeviceFeatures2KHR in the pNext chain of VkDeviceCreateInfo to enable features rather than pEnabledFeatures (which is set to null), then vkCreateDevice will fail with VK_ERROR_INITIALIZATION_FAILED.

Using that works correctly when launched outside of RenderDoc. The failure doesn't occur if pEnabledFeatures is used instead. Capturing on Linux works correctly when VkPhysicalDeviceFeatures2KHR is used, so it appears to be Android-specific.

## Repro steps

Use VkPhysicalDeviceFeatures2KHR to enable features when creating a device and attempt to launch that app through RenderDoc.

## Environment

* RenderDoc build: Both latest git (9ffcd0a9e0c6c406057104abb97555964b306131) and 1.1 have the issue
* Operating System: Android 8.0.0
* API: Vulkan
* Phone: Samsung Note 8, Mali-G71

**Comment by baldurk** [comment]
Can you upload the logcat output from renderdoc, are there any messages about initialization? I don't actually do anything special with the struct (although I should), so it shouldn't vary between android and linux.

The android loader is the main suspect here since it's consistently worse/broken compared to the desktop loader so I wonder if something is going wrong there.

**Comment by aejsmith** [comment]
[log.txt](https://github.com/baldurk/renderdoc/files/2538376/log.txt)

That's everything RenderDoc/Vulkan related I can see (with a few lines removed that contain our app name).

**Comment by baldurk** [comment]
Hmm OK yeh nothing in there. If you run *without* renderdoc and instead of setting `pEnabledFeatures` to `NULL` you set it to an empty-initialised struct, does that have any issues?

That's what the code will be doing at the moment, I don't have proper handling in for the VKPDF2 features struct, so I'll be setting a features struct to enable a few things I need for capture. I don't see anything in the spec saying you can't set both (it should just ignore the non-extended one) but maybe something is complaining about that.

**Comment by aejsmith** [comment]
Yeah, that fails. The spec does have:
> If the pNext chain includes a VkPhysicalDeviceFeatures2 structure, then pEnabledFeatures must be NULL

**Comment by baldurk** [comment]
Ahh that would explain it then, I was looking elsewhere and it seemed like it was just an override rather than mutually exclusive.

I need to update that code to handle the different features structs that can go on pNext, as at the moment it's not serialising & replaying them either. That should sort it out then I think.

**Comment by aejsmith** [comment]
OK, in the meantime I can just avoid using VkPhysicalDeviceFeatures2 on Android since there's no extended features I need to enable there.

**Comment by baldurk** [comment]
The code should now properly serialise & patch `VkPhysicalDeviceFeatures2` and leave the regular `pEnabledFeatures` as `NULL` if it wasn't used by the application. Also any other chained extension-specific feature structs will be serialised & replayed at the same time.
