### ISSUE TITLE
Debug Marker Stats

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1162]
## Description

I was wondering if it would make sense to have a sort of per debug marker stat system. I'm finding myself trying to get some ballpark data from a complex frame, and while I can see the relative timings, which are useful, I'm trying to determine things like number of drawcalls, vert count, etc.

So, the way I imagine it is the following.

1) Load up capture (perhaps you'd need to click on the clock to "gather stats" or something like that)
2) Hover over a debug marker and a popup shows up with the stats, e.g.

    Z-Prepass
    Drawcalls: 1970
    Vertex Count: 150,000
    Shaded Pixels: 1.000.000
    Average vertices per drawcall: 1.000

3) Export this data as an xml so that they can be better visualized in external software or sent.

Frame
    - ZPass stats
    - GBuffer stats
        - List1 stats
        - List2 stats

etc. These are all made up numbers.

It would be really useful to at a glance see basic data about a bunch of drawcalls to then start drilling in and seeing what's up with all of them. It helps diagnose a particularly bad stream of calls and give data to other people like artists, etc. which might need some guidance as to what regions need looking at, etc.

Does this seem like a sensible idea? Is there a simple way to obtain this with Python in any way? Thanks!

## Environment

* RenderDoc build: 1.1
* Operating System: Windows 
* API: D3D11

**Comment by baldurk** [comment]
This isn't something I'd consider adding upstream currently. I don't see a use-case for debugging, this seems like your motivation is performance analysis and RenderDoc is not a profiler.

The data you want is definitely available through the python API, because it exposes 100% of the information the UI can currently display. The python API is autogenerated from the C++ API that the UI is built on top of. Some of the data is available plainly through the [`DrawcallDescription`](https://renderdoc.org/docs/python_api/renderdoc/enums_data.html#renderdoc.DrawcallDescription) structs, whereas others you might need to fetch counter values for.

This might be something where you could use the plugin API added recently to integrate a new menu item into the UI - see #991.

**Comment by redorav** [comment]
I see, I wasn't aware there was a plugin system in the latest and greatest. I'll give that a spin, you're correct that it's more performance analysis than debugging so a fair reason not to prioritize it.
