### ISSUE TITLE
glMapBufferRange writing garbage when used with GL_MAP_UNSYNCHRONIZED_BIT

### ISSUE THREAD

**Issue by cmartel** [baldurk/renderdoc#1164]
## Description

In order to update uniform buffers while avoiding GPU sync points, I'm using a buffer orphaning approach. Through experimentation, I've found that the approach that works best to do this without introducing a sync point is to discard the existing buffer using `glBufferData(NULL)` and then perform the update using `glMapBufferRange(GL_MAP_UNSYNCHRONIZED_BIT)`.

However, when RenderDoc attached, the update will sometimes push garbage (marked as 0xDD by MSVC debug heap). This seems to depend on GL state before/after the update as the issue doesn't occur if certain draw calls are missing from the frame. Taking a frame capture makes the problem go away for the rest of the execution. Frame captures while the problem is present have the garbled values, and subsequent ones taken after the problem subsides have the correct values. By mapping the uniform buffer for readback before/after the unsynchronized map, I'm able to confirm that the value being mapped for read is 0xDD after the incorrect update.

The somewhat specific nature of this problem might also hint at incorrect state/API usage in my application. But since it only happens while RenderDoc is attached, I figured I'd at least throw this in here just in case. I have captures before/after inducing the garbage updates. I've tried taking a capture programmatically in the middle of the first garbage update, but `StartFrameCapture` seems sufficient to prevent the issue, so there seems to be nothing relevant in the API trace for that capture.

[RenderDocCaptures.zip](https://github.com/baldurk/renderdoc/files/2550828/RenderDocCaptures.zip)

Reproducing this seems somewhat app/renderer specific, so I'd be happy to gather more information as needed.

## Repro steps

1. Run with RenderDoc attached.
2. Perform an orphaned uniform buffer update using `glBufferData(NULL)` followed by `glMapBufferRange(GL_MAP_UNSYNCHRONIZED_BIT)`.
3. Results are incorrect no matter how many times the update is repeated.
4. Take a Renderdoc frame capture.
5. Perform another orphaned uniform buffer update.
6. Issue corrects itself for subsequent updates.

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 10
* API: OpenGL 4.3
* GPU: GeForce GTX 1050 Ti, driver 388.13

**Comment by baldurk** [comment]
When you call `glBufferData(NULL)` the contents of the buffer become undefined. RenderDoc will try to highlight bugs with uninitialised data leaking through by filling the data with `0xdddddddd`. With GL buffer management being what it is, there may be some cases after capturing where this won't happen if you continue orphaning, I'm not entirely sure.

I'm not clear on whether you're overwriting all the data with `glMapBufferRange` or not. Is the problem you're describing that data which should have been written in the map actually came out wrongly as `0xdd`, or just that the buffer contained `0xdd` where nothing else had been written?

As an aside this is behaviour I'm considering removing because many people don't expect it and it's hard to indicate to people, and it can lead to problems like uninitialised buffers which are expected to be full of 0s ending up with huge values and causing GPU timeouts when shader loops run amok. It's unfortunate because uninitialised buffers are very often *but not always* full of 0s, so this is a difficult bug to catch without renderdoc's explicit initialisation.

**Comment by cmartel** [comment]
All data is overwritten, yes. I keep a CPU copy of the buffer data and map the entire range ([0, size]) for a memcpy. I'm using `glMapBufferRange` instead of `glMapBuffer` because the latter doesn't support flags like `GL_MAP_UNSYNCHRONIZED_BIT`.

FWIW, I find the uninitialized data marker useful, although I thought it came Visual Studio's runtime in this case. It might just be misbehaving for the first update in this case...

**Comment by baldurk** [comment]
Yeh it's useful up until the point where a replay 'mysteriously' crashes the GPU and it's very difficult to tell that it's actually because X dispatch is reading from undefined buffer contents when running a loop..

It seems like the problem is `GL_MAP_UNSYNCHRONIZED_BIT` causing the `0xdddddddd` data upload in the `glBufferData` call to overlap with the map itself, which I guess makes sense.

I've tried to detect the `glBufferData(NULL)` -> `glMapBufferRange(GL_MAP_UNSYNCHRONIZED_BIT)` and just add a hard sync in then. It should mitigate the problem without affecting people who don't need the sync, let me know if it doesn't work for you.

**Comment by cmartel** [comment]
Took a glance at the commit, seems solid. I'll give it a go.

Just one observation on detecting GL orphaning, though (and take this with a grain of salt as I'm more familiar with D3D/gnm): 

Reissuing `glBufferStorage` doesn't count as orphaning as reinitializing immutable buffers is a GL error. The "proper" way of orphaning immutable buffers is by calling `glInvalidateBufferData` or mapping with `GL_MAP_INVALIDATE_BUFFER_BIT`. 

At least, in theory--I've tried a few different drivers/platforms and the only combination that seemed to reliably orphan without introducing sync points is `glBufferData(NULL)` -> `glMapBufferRange(GL_MAP_UNSYNCHRONIZED_BIT)`. This definitely is no `MAP_WRITE_DISCARD`...

Anyway, thanks for maintaining the renderdoc OpenGL layer, it makes developing on it considerably less painful.

**Comment by baldurk** [comment]
Sure that makes sense, but in this case the flag is more like "Detect where we've inserted a data upload that the application didn't expect, meaning we will need extra synchronisation before any `glMapBufferRange(GL_MAP_UNSYNCHRONIZED_BIT)` call". That's a bit of a mouthful though, so I just named it `orphaned`. So it's still needed in the call to `glBufferStorage` because you could then do an unsynchronised map right after that to upload data even if you're not really orphaning.

**Comment by cmartel** [comment]
Fair point, naming things is hard! 

And just came back to confirm that the commit fixes the problem nicely. Thanks! 👌
