### ISSUE TITLE
Hooking library selection

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1175]
## Description

In Android build instructions you mentioned a Note as below:
**With GLES programs on Android, the built-in hooking method doesn't always work. If you have trouble with crashes or problems capturing GLES programs, try enabling building with interceptor-lib. WARNING: Building this requires a hefty dependency.**

The built-in hooking method you mentioned is PLT hooking. Correct? 

On Linux/Windows machines, Renderdoc works with PLT hooking without any issues for all APIs.
The problem with built in hooking on Android is with GLES tracing only or for Vulkan tracing also? Can't we use PLT hooking on Android similar to Linux? 

I am trying to know what could be the reason for it not working on Android with built in hooking? What is the need for going to gapid-interceptor library?

## Environment

* RenderDoc build: v1.0
* Operating System: Android
* API:  Vulkan, OpenGL ES

**Comment by baldurk** [comment]
Windows does use IAT hooking which is similar in principle, but Linux doesn't use PLT hooking. On linux we use `LD_PRELOAD` to hook function calls as needed. Each platform uses whatever hooking mechanism makes sense and is most robust for that platform.

Yes the built-in hooking method on Android is the PLT hooking implementation, and hooking is only used for GLES at present and not Vulkan.

The reason interceptor-lib is recommended and used for shipping builds is because PLT hooking doesn't always work on Android. I explained the problem with PLT hooking on #1160. Each platform is different which is why a different solution is necessary for complete correctness on Android.

I'm not sure what the actual question or problem is here?

**Comment by gittmi** [comment]
Thanks baldurk.
As per your comment, PLT hooking is used for openGLES only. 
How the vulkan APIs are intercepted on Android?

**Comment by baldurk** [comment]
Vulkan has a layer system built into the API to allow tools to intercept API calls, so there's no need for OS-level hooking. The Android loader is kind of broken/limited and it doesn't allow global implicit layers, but using JDWP then debuggable apps can still be instructed to explicitly load an external layer.

I'm going to close this issue now since it seems like you're just wanting to understand how the hooking works. I'm always happy to explain anything about how RenderDoc works but github issues aren't quite the best place to do that - since they generally track a specific problem or request and can be closed when that is completed. Questions often result in follow-up questions so the conversation could continue indefinitely.

If you have any general questions you can always [email me](mailto:baldurk@baldurk.org?subject=RenderDoc%20Question) and I can answer that way.

**Comment by gittmi** [comment]
I am sorry. I was trying to understand the hooking part. I will email you for understanding related questions.

Thanks.

**Comment by baldurk** [comment]
No need to apologise, it's just that it's difficult to manage issues if they don't really have a resolution.
