### ISSUE TITLE
Can't start Android NativeActivity

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1179]
## Description

I get an error when trying to launch an Android application which has a NativeActivity as main Activity. 
Related commit: https://github.com/baldurk/renderdoc/commit/588642c4c866ea985d3ab3fc8600dfea47ddacf5
It doesn't necessary for the Activity name to contain the package name.
For example, here the packageName is: **com.example.native_activity** while the Activity name is **android.app.NativeActivity**:
https://github.com/googlesamples/android-ndk/blob/master/native-activity/app/src/main/AndroidManifest.xml

## Environment

* RenderDoc build: v1.x, 2018-11-15

**Comment by baldurk** [comment]
That commit only adds an error message - do you just get an error or are you unable to start the app at all? Those are different problems; one is a false positive error which is annoying but harmless, the other is an actual broken behaviour.

**Comment by tabikati** [comment]
I just get an error message which I think I should not get.

**Comment by baldurk** [comment]
If it's just an error message that isn't always accurate, that's not a bug since it's just one more line in the android log. If nothing actually goes wrong no-one will even look in the log and notice the message so it doesn't do any harm.

It's clear that no-one fully understands how android apks work, so it's better to be conservative with the check. The only point of the error is to alert the users to a potential problem that might mean they can't launch their apk, if the activity name is fetched wrongly for some apks. It's fine if there is an edge-case where this alerts the user but they can see that it's correct by knowledge or by the apk starting correctly.

**Comment by baldurk** [comment]
From discussion offline with @cnorthrop, it seems like there's actually no relation between package name and activity name. The activity name is entirely arbitrary, I don't think NativeActivity has anything to do with it.

I've removed the error and replaced it with a log message with package & activity, but hopefully there's some condition that's possible to check when an invalid activity is fetched.
