### ISSUE TITLE
Black regions appear when launched with RenderDoc

### ISSUE THREAD

**Issue by enginmanap** [baldurk/renderdoc#1183]
## Description

I am trying to debug my game engine, but it creates different result in renderdoc, then when launched manually.

The difference is, for directional lights, if an fragment is **not** in shadow, then it results in black color in renderdoc. It works as expected when launched manually.

I captured the screenshots, you can see them here:
Renderdoc: http://tinypic.com/view.php?pic=5390ra&s=9
Normal: http://tinypic.com/view.php?pic=30lm7th&s=9

## Repro steps

I am launching my application without any parameters, with the same path of the executable. No further configuration.

A build of the engine with the given map can be downloaded here:

https://drive.google.com/file/d/1Gm_K45KTa2mhW8Bg1_LmvN_mITBfCp1W/view?usp=sharing

Please note this is a debug build of the current head (b2e190), you can check the source code here:
https://github.com/enginmanap/limonEngine

It is compiled using mingw64, SDL2 + GLEW is used for OpenGL context creation.

## Environment

RenderDoc 1.1 release
OS: Windows 10, 1809 (I had same issue on 1803 too)
API: OpenGL 3.3 with GL_ARB_texture_cube_map_array extension

Nvidia 1070 + 416.94 drivers

**Comment by baldurk** [comment]
This seems like it's caused by the application relying on undefined buffer contents.

In the source [lightUBOlocation](https://github.com/enginmanap/limonEngine/blob/d1acbbf2cd07b138d31ea499f159c213bcbcc8e5/src/GLHelper.cpp#L314-L317) is initialised with `glBufferData` and a `NULL` data, which the spec says results in undefined buffer contents. It's then partially updated in `GLHelper::setLight` wherever a light is added, but [only that light's data is updated](https://github.com/enginmanap/limonEngine/blob/d1acbbf2cd07b138d31ea499f159c213bcbcc8e5/src/GLHelper.cpp#L885-L898) leaving any lights that are never initialised containing garbage data.

Drivers _often but not always_ initialise buffers to 0 when their contents are undefined which is easy to rely on accidentally, but this can't be guaranteed. To try and help catch this kind of bug, RenderDoc instead initialises the buffer to `0xddddddd` so that any contents that aren't written have obvious values. In this case, that causes some uninitialised lights to render and they show up as black areas:

![image](https://user-images.githubusercontent.com/661798/48924432-0a581680-eeb0-11e8-8fc7-693c3b5ad35e.png)

**Comment by enginmanap** [comment]
Thank you very much.
