### ISSUE TITLE
Question regarding the installation on Debian

### ISSUE THREAD

**Issue by marsp0** [baldurk/renderdoc#1184]
I downloaded the archive from the website and unpacked it. I am not good with manually installing apps on Debian as I have always used the package manager. After opening the directories inside the folder I see that there is a bin directory containing an executable. I tried running it and I successfully captured a frame of my game. I was wondering, can I just leave the whole folder as it is in my Documents and open the app from there? Am i losing something by doing it that way (except for not having the app in my dock etc.) ?

**Comment by baldurk** [comment]
The short answer is yes - as long as the program runs for you there's nothing special requiring it to be installed in the regular system tree.

The main downsides would be as you say lack of integration into any desktop environment and that `qrenderdoc` wouldn't be in the default `PATH` (although you could add it to your user's `PATH`). The renderdoc library isn't ever linked against so there's no need for that to be in the `ld.so` search path.

There are potential compatibility issues that might crop up more subtly, as the binary I distribute is static linked as much as possible to be as portable to a wide set of distributions. A native package would use the system libraries and be more reliable. The reason I distribute a simple binary tarball is because creating distribution packages is out of scope for and a whole maintenance burden of its own, but it's still useful to have a package for people to run without compiling from source.

It's worth noting that several distributions do now have renderdoc in their package managers including a [renderdoc package in debian sid](https://packages.debian.org/sid/main/renderdoc). I think the main one that's missing is Ubuntu. I'm happy to help out packagers but I can't realistically maintain all of those myself, so that's up to the individual maintainers in each distro.
