### ISSUE TITLE
Exe icon (Windows)

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#1185]
## Description

After pinning RenderDoc to taskbar, the icon can change into a totally different icon. On my laptop it changed to the Pixelformer icon, while on my desktop it changed to the Windows Photos icon. When I installed it the icon was normal; but not after a few restarts (the RenderDoc that came with Vulkan).

## Repro steps

Install and restart a few times.

## Environment

RenderDoc build: https://github.com/baldurk/renderdoc/commit/c7d5aa863e5f13430b2230e5048d253d342d1a18
OS: Windows 10 & Windows 8.1

**Comment by baldurk** [comment]
This seems like a windows bug rather than a renderdoc bug, and searching google shows a lot of results showing this happening for other programs. Even if somehow the icon got corrupted or went wrong on RenderDoc's side it wouldn't have any access or knowledge of other programs installed on your system to substitute their icons. I can try and repro this but unless I can reliably repro it I don't have a hope of debugging it.

Can you clarify a couple of things - it sounds like you got RenderDoc from the Vulkan SDK installer. Which SDK version did you install? If you uninstall RenderDoc and then install it from the standalone installer do you get the same problem? When the icon pinned to your taskbar breaks, does it break on the start menu? What about the icon on the executable itself or in the add/remove programs menu?

**Comment by baldurk** [comment]
I uninstalled any other version of renderdoc, let the vulkan SDK install RD 1.1, then pinned the shortcut to the taskbar. I restarted 3-4 times but the icon has stayed consistently correct, so I can't repro this.

If this is a RenderDoc bug and not a windows problem, I'd need more information to investigate.

**Comment by Nielsbishere** [comment]
Vulkan SDK: 1.1.85.0
The icon looks okay in the top left of the window, but not on the taskbar (even when unpinned) and looks correct in the start menu. The add/remove programs menu looked correct. I think you're right and this is a Windows issue, which is weird, because it happened accross Windows versions though. I haven't noticed this happening with any other software. I'm going to try to repro this.

**Comment by Nielsbishere** [comment]
Was able to repro this by installing RenderDoc from the Vulkan SDK installer (1.1.85), after a restart. It immediately went back to the Windows icon for a photo (.png, .jpg, etc). When I install it from the standalone installer it works fine (even after trying to break it). Does the VkSDK's version use a special icon or is it seen as a Windows app or something? It might be that it conflicts an id or something and Windows uses a different icon for it?

**Comment by baldurk** [comment]
I don't think the vulkan SDK does anything special, but if it only happens there you'd need to report it to LunarG. I'm not sure if they'll be able to do anything about it either though, it sounds like a windows bug.

**Comment by Nielsbishere** [comment]
Wanted to say that RenderDoc looks like the Windows photo icon again in a fresh install. The icon seems to work fine until you open a photo in the Windows photo viewer, no clue why it happens, but it does.
![afbeelding](https://user-images.githubusercontent.com/28758736/94343439-807fb400-0018-11eb-823e-6c753a84f896.png)

**Comment by baldurk** [comment]
There's still no indication this is a RenderDoc bug, I do nothing special to set that icon. If it were broken completely that might be an issue but if it only breaks intermittently and in the same way as other programs have been reported to then the signs all point to it being a windows bug.
