### ISSUE TITLE
Unidentified objects in resource viewer

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#1188]
## Description

In my capture I see a few resources that do belong to the Vulkan device but don't seem to be created by me; they don't have a name and they don't seem to be used by the app. Is this because RenderDoc injects into the program and uses the Vulkan device to create resources or because RenderDoc's device is being used?  
It would be handy to see a way to filter out these resources if they do belong to RenderDoc, just to ensure that there are no invalid resources laying around on my part. 

## Repro steps

Capture an application or use the [following capture](https://ufile.io/y9b4u).    
![unidentified objects](https://i.imgur.com/tMM8WbA.png)  
The image shows a few named and unnamed resources; every vkCreate is followed by my own vkName; so my resources are all named. 

## Environment

RenderDoc build: https://github.com/baldurk/renderdoc/commit/569f11b7577ba77458f41d81116b545cc82971c6  
Operating System: Windows 10  
API: Vulkan

**Comment by baldurk** [comment]
Going by the shader modules which are identifiable those are indeed internal renderdoc resources.

Are you capturing with the 'Ref All Resources' option enabled? In v1.1 internal resources could get included in the capture as well if that's enabled, which has been fixed since. If that's the case can you say why you've enabled the option? It's rarely useful as it just bloats the capture with unnecessary extra data.

**Comment by Nielsbishere** [comment]
Makes sense, I just thought 'ref all resources' would be required to view all resources that have been created (even if they aren't used in the current command buffers). Turning off ref all does solve it, thank you.

**Comment by baldurk** [comment]
That is what the option does it's just rarely useful and often enabled by accident. In recent builds it should work correctly without including internal resources.
