### ISSUE TITLE
Capturing first frame in Vulkan doesn't start until swapchain is created

### ISSUE THREAD

**Issue by rumblehhh** [baldurk/renderdoc#1195]
I've been working with VK_EXT_debug_utils and have been visualizing the results using RenderDoc. 
I attempted to add nested calls of vkQueueBeginDebugUtilsLabelEXT/vkQueueEndDebugUtilsLabelEXT with a pattern similar to the following:
"
vkQueueBeginDebugUtilsLabelEXT("Outer Queue Begin Debug Utils Label")

vkQueueBeginDebugUtilsLabelEXT("First Inner Queue Begin Debug Utils Label")
vkQueueEndDebugUtilsLabelEXT()

vkQueueBeginDebugUtilsLabelEXT("Second Inner Queue Begin Debug Utils Label")
vkQueueEndDebugUtilsLabelEXT()

vkQueueEndDebugUtilsLabelEXT()
"

However the RenderDoc GUI is not showing me entries as I was expecting. I see entries for "First Inner Queue Begin Debug Utils Label" and "Second Inner Queue Begin Debug Utils Label" but they are not nested inside an "Outer Queue Begin Debug Utils Label" as I was expecting and as happens when using a similar pattern of nested vkCmdBeginDebugUtilsLabelEXT/vkCmdEndDebugUtilsLabelEXT calls.

Should this work as I'm expecting? I can't see that it's not allowed by the spec but then again it doesn't specifically mention nesting as it does with vkCmdBeginDebugUtilsLabelEXT/vkCmdEndDebugUtilsLabelEXT calls.

I've attached a windows (x64) binary which can be used to show the potential issue I've outlined above.
[VulkanBumpmap.zip](https://github.com/baldurk/renderdoc/files/2643947/VulkanBumpmap.zip)

I've tried RenderDoc using Version 1.2 and compiling from source.

**Comment by baldurk** [comment]
That should work fine as you describe. I can't repro the problem with your binary - I don't see the exact text or order that you have but it looks correct to me:

![image](https://user-images.githubusercontent.com/661798/49443770-31beb580-f7c5-11e8-96f6-2873b62d34bb.png)

![image](https://user-images.githubusercontent.com/661798/49443754-24a1c680-f7c5-11e8-9fad-e8ee1535954c.png)

That's with release version 1.2 and with latest source (which is pretty much the same).

**Comment by rumblehhh** [comment]
Thanks for the reply! Sorry I should have mentioned that to see the issue I described the capture needs to be taken of the first frame (I'm so used to queuing up a first frame capture its become a bit second nature to me. Apologies though for the rubbish repro steps). The attached image shows a capture taken from the first frame. 

![frame0](https://user-images.githubusercontent.com/40687079/49448077-fecdef00-f7cf-11e8-9fbc-8751983f3972.png)

After a second look it looks like I'm seeing the expected behaviour for the nested queueBeginDebugUtilsLabelExt starting with "renderFrame" but don't see the expected nested queueBeginDebugUtilsLabelExt starting with "initView". The two, from what I can see, don't differ in the calls used. From application code I can see that queueBeginDebugUtilsLabelExt with labelName: initView is being called.

I'm expecting to see:
queueBeginDebugUtilsLabelExt: initView
    queueBeginDebugUtilsLabelExt: Batching Application Resource Upload
    queueEndDebugUtilsLabelExt
    queueBeginDebugUtilsLabelExt: PVRUtilsVk::UIRenderer::Init
    queueEndDebugUtilsLabelExt
queueEndDebugUtilsLabelExt

queueBeginDebugUtilsLabelExt: renderFrame
    queueBeginDebugUtilsLabelExt: Submitting per frame command buffers
    queueEndDebugUtilsLabelExt
    queueBeginDebugUtilsLabelExt: Presenting swapchain image to the screen
    queueEndDebugUtilsLabelExt
queueEndDebugUtilsLabelExt

I put a breakpoint in RenderDoc in renderdoc\driver\vulkan\wrappers::Serialise_vkQueueBeginDebugUtilsLabelEXT which gets hit for each of the queueBeginDebugUtils calls other than for the one with a label name of "initView". Is there any reason why the queueBeginDebugUtilsLabelExt with labelName: initView wouldn't be captured/logged by RenderDoc?

**Comment by baldurk** [comment]
OK I see the problem. The issue is that the 'first frame' starts capturing when the swapchain is created, which happens after the first queue label is submitted.

Part of the reason for this is that captures are defined in terms of which device & window are active (which of course requires a window), but the main reason is because for D3D11 & GL historically it's very common to create multiple devices/contexts for enumeration before creating the 'real' context. Without leaning on something like the window creation it's hard to tell which one should actually start the capture.

I'll need to think about this for a bit to see if there's a better solution, but the above reasoning doesn't apply as strongly to Vulkan/D3D12 so I could probably start capturing as soon as the first device is created. It is definitely more intuitive to what people expect but it's a bit inconsistent and has the risk of false positives if someone _does_ for some reason create an instance & device and then destroys them without doing anything.

Object creation etc is all captured either way, but you miss out on draw/command events before the capture starts. In the meantime if you need to capture your initialisation and you have specific range you want to capture, I'd suggest using [the RenderDoc API](https://renderdoc.org/docs/in_application_api.html) - it only takes a dozen lines of code or so to start and stop a capture and then you can be sure of what's contained within it. You can just pass `NULL, NULL` for device/window to capture.

**Comment by rumblehhh** [comment]
Great, thanks for the brilliant explanation for why this happens. We're not particularly desperate to see the queueBeginDebugUtils("initview") so I don't think we'll need to work with the RenderDoc API right now although thanks for pointing it out - I haven't looked into this before, I'll definitely take a quick look through it. Thanks for looking into this issue.

**Comment by baldurk** [comment]
As discussed above I've moved the 'first frame' to start at device creation on Vulkan and D3D12 since they don't need you to construct multiple devices for enumeration or setup like D3D11/GL do. In my tests this seems to behave well and it's a reasonable behaviour.

**Comment by rumblehhh** [comment]
Great, sounds good thanks for the improvement and for following up with me
