### ISSUE TITLE
Incorrect depth stencil resource classification from format

### ISSUE THREAD

**Issue by MichelVachon** [baldurk/renderdoc#1198]
Hi,

I modified the code so that depth texture resources are correctly classified as Depth and not Render, and vice-versa. These changes are necessary for us to capture and replay.

I attached the changes, let me know what you think.

The source files were downloaded on dec 3, at 3:43PM.

Thanks
Mike

[d3d12_msaa_array_conv.cpp.txt](https://github.com/baldurk/renderdoc/files/2654868/d3d12_msaa_array_conv.cpp.txt)

[d3d12_initstate.cpp.txt](https://github.com/baldurk/renderdoc/files/2654862/d3d12_initstate.cpp.txt)

**Comment by MichelVachon** [comment]
I created a branch with the modified files.

[Depth Render Classification branch](/MichelVachon/renderdoc/tree/Depth-classification)

Since I'm such a github newbie, I was told to create a branch :)

Thanks

**Comment by baldurk** [comment]
Hi, the github branch is much easier because it shows the changes you've made rather than having to manually match up the code and diff by hand.

Can you explain what situation you had run into and the problem you found, and then why the changes were needed? It's not immediately obvious from the changes and I'd like to understand it to make sure the appropriate fix is made.

**Comment by MichelVachon** [comment]
Some of our depth textures use typeless formats in the resource desc and a typed format in the view desc. The code was classifying the resource based on the resource desc format. The problem is that resources may already have the flags D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL or D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET set.

Illegal side effects include:

Simultanious flags D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL and D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET.

Setting D3D12_RESOURCE_STATE_DEPTH_WRITE on a non depth resource

Setting D3D12_RESOURCE_STATE_RENDER_TARGET on a depth resource

I changed the code so that a texture is classified as depth not based on the format but based on the resource flag D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL. Which means everything will be classified as render target when the flag is not set. 

I updated my branch, I removed some changes that are no longer needed.

**Comment by baldurk** [comment]
OK I think I understand the problem, so you are presumably using `R32_TYPELESS` or `R16_TYPELESS`? Since the other `TYPELESS` depth-capable formats that are packed depth/stencil are identified as depth anyway, but those two could be created as depth resources but wouldn't be identified by `IsDepthFormat`.

I think my preferred fix though would be to make a smaller change like changing the check to `IsDepthFormat(desc.Format) || desc.Flags & D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL`. That way it should never mistakenly identify a depth resource as colour. The reason being it's a smaller change, and if a user creates a depth-formatted texture that *must* be copied as depth, like `DXGI_FORMAT_R24G8_TYPELESS`, but doesn't set `ALLOW_DEPTH_STENCIL` perhaps because it's a temporary read-only copy texture, it still must be put through the depth pipeline.

One thing I'm not clear on is how the existing code would identify a non-depth resource as depth. i.e. how could you end up setting `STATE_DEPTH_WRITE` on a non depth resource? As far as I see the formats identified with `IsDepthFormat()` shouldn't be legal to use as a render target.

**Comment by MichelVachon** [comment]
You're right about the last point, my mistake.

I tested the new changes and updated my branch.

**Comment by baldurk** [comment]
Great thanks! I think we're on the same page then.

For future info, github issues are usually like bug reports or feature requests, if you have a change you'd like to have added to the code then you can make a 'pull request'. Basically when you go to your branch there should be an option to make a new pull request, which you can then enter a description & any explanation, and it goes through a code review & CI checks before being merged.

Just to simplify things I manually squashed the changes together and merged them in (76848d493b74d9a1bbd8759ce4793624e2a39e11) which are now in the main branch. Thanks!
