### ISSUE TITLE
D3D12 OpenSharedHandle

### ISSUE THREAD

**Issue by MichelVachon** [baldurk/renderdoc#1199]
A colleague of mine contacted you by email previously regarding the unsupported OpenSharedHandle feature. 
We use it to interact with wpf.
As it stands right now, we don't read the original texture content, we only write to it.

With that in mind, I partially implemented it in 0.91 before migrating to 1.2.

It's implemented pretty much as if it was a CreateCommittedResource.

I will re-implement it for 1.2 today probably.

But I was wondering if you'd be interested in having a partial feature support in the main branch.

Thanks
Mike

**Comment by baldurk** [comment]
I haven't had any emails about it I don't think, but I did have someone request support over twitter.

As long as the partial implementation is limited to just the `WrappedID3D12Device::OpenSharedHandle` function that should probably be fine. It's already completely unsupported/crashing, so having an implementation that works in some cases would be fine. Ideally it would detect any failing cases and at least print an error message similar to what it does now.

Implementing it as if it was `CreateCommittedResource` should be enough actually I think, so your implementation might be more complete than you think. Since there's no way to detect writes realistically mid-frame, for the D3D11 implementation I just grab the creation parameters and serialise it as-if it were a normal resource create pretty much. If some writes come in mid-frame they aren't reflected in the capture.

The only other thing is a full implementation would need to handle fetching parameters out of D3D11 objects, and similarly add handling for D3D12 objects being shared with D3D11.

**Comment by MichelVachon** [comment]
did you get a change to look at the changes?

**Comment by baldurk** [comment]
I'm in Europe so I didn't get to look at the PR before I finished for the day. I'll look at it on Monday.

**Comment by MichelVachon** [comment]
I see, have a great weekend!

**Comment by baldurk** [comment]
Closing this as the PR is now merged.
