### ISSUE TITLE
Capture API no longer captures all windows?

### ISSUE THREAD

**Issue by PfhorSlayer** [baldurk/renderdoc#1205]
## Description

We're using the Unreal engine for our current project, and with RenderDoc v1.1 we were able to take captures that contained the contents of all windows that were open. After upgrading to v1.2 though, it seems we're only getting captures of the API calls to a single window. Looking through the documentation it seems like maybe this should have always been the case, but I found the previous behavior to be extremely useful. Is there a way to make the API capture the calls for all open windows of the application, rather than just a single one?

Note that this can be somewhat worked around by making sure that the stuff I'm trying to capture is being drawn to the main editor window, but it's still much less convenient than the previous behavior.

## Environment

* RenderDoc v1.2
* Windows 10
* D3D11

**Comment by baldurk** [comment]
This is indeed how it was always meant to work, a 'frame' isn't really very well defined when multiple windows are present but RenderDoc starts the capture at one present of the 'active' window and ends it and the next.

It's not generally possible to include 'all' windows because there's not really any direct correlation between rendering work that ultimately ends up presented to a window and the window presents.

E.g. if an application with three windows renders and presents them in round-robin fashion:

1. render A
2. present A (active)
3. render B
4. present B (inactive)
5. render C
6. present C (inactive)
7. render A
8. present A (active)

Then RenderDoc will capture from step 2 to step 8, and you'll get rendering for B, C, A in order. If B and C are dormant and the application is only rendering to A then you'll just get A's rendering. In general it's not possible to tell what rendering should go where since it's really up to the application, the 'active window present-to-present' is a fairly arbitrary best effort to capture what's desired.

I don't think anything should have changed with this between v1.1 and v1.2. Can you capture side-by-side with the two renderdoc versions on the same UE4 and see different results? It's possible that UE changed their rendering order since last you tested on v1.1, e.g. it's a common optimisation to not render windows that aren't receiving any input events and don't have any animation, since their contents haven't been invalidated - perhaps UE changed their code to not render all windows all the time, or to present the main window more often such that two presents happen without the other windows rendering in between?

If you can give me a repro, or narrow down using nightly buidds where the behaviour changed, I can take a look into why it's changed. Unless it's a bug in RenderDoc's tracking somehow though, then this isn't something I'll change.

If you want fine-grained control over what's included in a capture I suggest using the [renderdoc API](https://renderdoc.org/docs/in_application_api.html) which UE already uses in its renderdoc plugin. That allows you to start and stop the capture whenever you want.

**Comment by PfhorSlayer** [comment]
That's the thing - we are using the API to do the capture. We do a `StartFrameCapture` at the beginning of the frame we want, and then at the beginning of the next frame we do an `EndFrameCapture`. Same version of UE, all that changed was me installing RenderDoc v1.2.

You absolutely are right that UE renders as you described, but all of that happens within a single engine tick so I'd expect to be capturing everything there and not just stuff from a single present.

I'll try to get you captures from both versions later today.

**Comment by baldurk** [comment]
If you're calling `StartFrameCapture` and `EndFrameCapture` then RenderDoc takes no control over what is included in the capture. For D3D11 it's just all commands submitted to the immediate context between those two points. If you're submitting from multiple threads it would be up to you to synchronise between rendering and starting/stopping the capture, but I'd guess that's not an issue for D3D11.

Nothing should have changed with that handling so I'm not sure why it would behave differently for you with v1.2. Getting captures won't be helpful to debug this as whatever the issue is, it's something that's determined when the capture itself is created. Could you give me a patch to the UE4 source maybe that I can apply and try to reproduce the problem myself locally? Either that or I could make a logging branch for you to run to see what's going on.

**Comment by PfhorSlayer** [comment]
After digging through our local changelists, I'm rather embarrassed to report that this seems to have been caused by one of our programmers optimizing the update loop by defaulting most things to not update in realtime, but rather only when modified. This change was checked in one hour after I upgraded RenderDoc, and I missed the connection. After locally enabling realtime updates on various views, things do work correctly!

Sorry for having taken your time with a bogus bug report!
