### ISSUE TITLE
OpenGL demo not capturing

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1218]
## Description

Hi,

I was wondering if you could point me in the right direction here. I'm having an issue capturing a small public OpenGL demo. The demo provides full source and an executable here: http://theorangeduck.com/page/neural-network-ambient-occlusion

When I start the executable through renderdoc, it detects the API properly but the overlay doesn't appear and it doesn't let me capture anything. The moment I close the application, however, the overlay appears briefly and the program dies. Would you be able to advise? I don't think I'm doing anything particularly unusual, it must be something specific to this application.

## Repro steps

1) Download the demo from the link (click Code & Data). No need to compile anything
2) Run nnao_demo.exe through renderdoc. It will ask for glew32.dll which can be downloaded here. http://glew.sourceforge.net/index.html It is a 64-bit application so it will need that.

## Environment

* RenderDoc build: 1.2
* Operating System: Windows 10
* API: OpenGL

## Log

RDOC 009740: [00:53:41]    win32_network.cpp( 222) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.
RDOC 009740: [00:53:43]    win32_process.cpp( 493) - Log     - Running process C:\Users\RedOrav\Desktop\nnao_demo\demo.exe
RDOC 009740: [00:53:43]    win32_process.cpp( 577) - Log     - Injecting renderdoc into process 12952
RDOC 012952: [00:53:43]             core.cpp( 310) - Log     - RenderDoc v1.2 64-bit Release (204724bebe2484ee2d14a572d9f1074dd3f933a9) capturing application
RDOC 012952: [00:53:43]      crash_handler.h( 112) - Log     - Creating crash-handling server
RDOC 012952: [00:53:43]   win32_libentry.cpp(  66) - Log     - Loading into C:\Users\RedOrav\Desktop\nnao_demo\demo.exe
RDOC 012952: [00:53:43]  sys_win32_hooks.cpp(  82) - Log     - Registering Win32 system hooks
RDOC 012952: [00:53:43]      d3d11_hooks.cpp( 125) - Log     - Registering D3D11 hooks
RDOC 012952: [00:53:43]      d3d12_hooks.cpp( 125) - Log     - Registering D3D12 hooks
RDOC 012952: [00:53:43]       d3d8_hooks.cpp(  36) - Log     - Registering D3D8 hooks
RDOC 012952: [00:53:43]       d3d9_hooks.cpp(  45) - Log     - Registering D3D9 hooks
RDOC 012952: [00:53:43]       dxgi_hooks.cpp(  77) - Log     - Registering DXGI hooks
RDOC 012952: [00:53:43]        egl_hooks.cpp( 654) - Log     - Registering EGL hooks
RDOC 012952: [00:53:43]         gl_hooks.cpp( 191) - Log     - Registering OpenGL hooks
RDOC 012952: [00:53:43]        wgl_hooks.cpp( 555) - Log     - Registering WGL hooks
RDOC 012952: [00:53:43]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
RDOC 009740: [00:53:43]   target_control.cpp( 560) - Log     - Got remote handshake: demo [12952]
RDOC 012952: [00:53:44]        gl_driver.cpp( 959) - Log     - Compatibility context 0000000000010000 created without attribs, sharing with context 0000000000000000
RDOC 012952: [00:53:44]        gl_common.cpp( 461) - Log     - Checking enabled extensions, running as OpenGL 4.6
RDOC 012952: [00:53:44]        gl_driver.cpp(1167) - Log     - Activating new GL context: NVIDIA Corporation / GeForce GTX 980 Ti/PCIe/SSE2 / 4.6.0 NVIDIA 411.63
RDOC 012952: [00:53:44]        gl_driver.cpp( 959) - Log     - Compatibility context 0000000000020000 created without attribs, sharing with context 0000000000000000
RDOC 012952: [00:53:44]        gl_common.cpp( 461) - Log     - Checking enabled extensions, running as OpenGL 4.6
RDOC 012952: [00:53:44]        gl_driver.cpp(1167) - Log     - Activating new GL context: NVIDIA Corporation / GeForce GTX 980 Ti/PCIe/SSE2 / 4.6.0 NVIDIA 411.63
RDOC 012952: [00:53:44]        gl_driver.cpp( 959) - Log     - Compatibility context 0000000000030000 created without attribs, sharing with context 0000000000000000
RDOC 012952: [00:53:44]        gl_common.cpp( 461) - Log     - Checking enabled extensions, running as OpenGL 4.6
RDOC 012952: [00:53:44]        gl_driver.cpp(1167) - Log     - Activating new GL context: NVIDIA Corporation / GeForce GTX 980 Ti/PCIe/SSE2 / 4.6.0 NVIDIA 411.63
RDOC 009740: [00:53:44]   target_control.cpp( 787) - Log     - Used API: OpenGL (Not presenting & supported)
RDOC 009740: [00:53:44]   target_control.cpp( 787) - Log     - Used API: OpenGL (Presenting & supported)

**Comment by baldurk** [comment]
The program has no delay in its render loop and disables doublebuffering:

```cpp
  SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 0);
```

Which means that as soon as RenderDoc's overlay has rendered and the present has happened the program starts rendering the next frame directly to the frontbuffer and scribbles over it.

If the program did anything but render a static image to the ~back~ _front_ buffer it would hit extreme flickering itself I think.

In theory I could try and hook the window init and force double buffering but in the extreme it would be messy as hell, so I'm going to chalk this one up as the developer getting exactly what they asked for even though that doesn't make much sense. RenderDoc still works fine without the overlay it's just not super clear in this case that the application is initialising legacy GL so can't be captured. I might add something to the connection panel to that effect because there's no indication there.

**Comment by redorav** [comment]
I see, I'm out of luck then, and it's not worth spending time to "fix" it like you say. Thanks for checking it out.

**Comment by baldurk** [comment]
If you just want to capture then you can add this code in:

```cpp
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 4);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
```

The program itself isn't using any deprecated functionality that renderdoc doesn't support. It doesn't use VAOs and uses client-side vertex arrays, but renderdoc has support for those due to GLES still allowing it. It just doesn't create a modern context so there's no way for renderdoc to know that it doesn't use e.g. fixed function.

You still won't get the overlay (if you could, you'd see the warning about compatibility mode), but it captures OK in v1.2 with that change.

**Comment by redorav** [comment]
That worked great, I had to fiddle about with glew and sdl but after that capture worked beautifully :)
