### ISSUE TITLE
wglShareLists doesn't properly share objects on GL

### ISSUE THREAD

**Issue by loren-osborn** [baldurk/renderdoc#1224]
Much of this (beyond steps to reproduce) is conjecture:

## App captured from has a default keybinding conflict with RenderDoc:

When using [F12] to capture a frame from an app, the app is opening a new window to render into. I suspect this is the cause of the crash I'm seeing:

### Only facts below this line:

When attempting to capture an eevee rendering artifact on my laptop with Intel HD Graphics 620 GPU, Blender crashes, sometimes taking RenderDoc with it. 

- Context FYI:
    - [Blender](https://blender.org) is an open source 3D animation suite. Blender 2.80 is currently in beta.
    - [EEVEE](https://www.blender.org/2-8/#eevee) is Blender's new real-time [PBR](https://en.wikipedia.org/wiki/Physically_based_rendering) render, due for official release in Blender 2.80

When I attach Blender to the Visual Studio 2017 debugger before it crashes, the exception appears to be in a RenderDoc thread.

## Repro steps

1. Download a nightly build of Blender 2.80 (it may affect the actual beta release also, I'm not sure.)
2. Launch Blender 2.80 from RenderDoc
3. Click outside the splash screen to get to the main editor with a default cube.
4. (optional) Attach debugger.
5. In the lower right window pane (which should be a "Properties" pane), select the second vertical tab from the top: "Render"
6. Verify that the "Render Engine" is set to "Eevee"
7. In the upper right hand corner of the 3D editor pane there is a drop-down selector labeled "Shading". Just to the right of that you will see four buttons with sphere shaped icons on them. The right-most of these four buttons is labeled "Rendered". Click it to select Eevee rendered mode.
8. Press [F12] to cause RenderDoc to capture a frame.

This causes Blender to crash.

## Environment

* RenderDoc build: v1.2
* Operating System: Windows 10 Home (64 bit)
* API: OpenGL
* GPU: Intel HD Graphics 620

Please let me know if there's any additional information I can offer.

**Comment by loren-osborn** [comment]
Additional information:

It looks like this isn't related to opening another window. [PrtScrn] doesn't open a new window, but causes the same behavior.

**Comment by baldurk** [comment]
The problem seems to be that for who knows what reason blender is using `wglShareLists` even though it also uses `wglCreateContextAttribsARB` right before. RenderDoc's shared context tracking doesn't handle `wglShareLists` so buffers/textures aren't found. If you look in the RenderDoc diagnostic log you will see a huge number of errors related to this.

**Comment by baldurk** [comment]
That commit adds support for `wglShareLists` and I can capture from Blender fine now. Note that it won't support `wglShareLists` being called after `wglMakeCurrent` because I have to create internal resources in `wglMakeCurrent`. That's the last chance I have before general work.

See #155 which pre-dates proper support for sharing and non-sharing of contexts. I don't think it's important to support this case as `wglShareLists` is ancient and superceded by `wglCreateContextAttribsARB` which is the only context creation mechanism that RenderDoc supports anyway.
