### ISSUE TITLE
ld_indexable(buffer)(uint,uint,uint,uint) not working in debugger

### ISSUE THREAD

**Issue by loosche** [baldurk/renderdoc#123]
Compute Shader (cs_5_0)
DirectX 11
AMD 7900 Series (Catalyst Version 14.2)
Description: ld_indexable always returns 0 instead of actual buffer value

I can't upload the shader. Basically it's a byte code interpreter that loops over uint32 operations and uses a switch statement to pick a bit of code to execute for each operator. The bytecode comes in as a uint Buffer. If I look at the buffer itself the data seems correct, but if I look at the data returned from the following load, it's always zero.

<code>ld_indexable(buffer)(uint, uint, uint, uint) r0.z r4.yyyy, bytecode.yzxw</code>

r4.y= 0, then 1, then 2, then 3, ...
bytecode= t0 (Value in Constants & Resource Window is 380 - Buffer 1705)

If I put counts in each switch (notice how many adds, how many subtracts, etc) and output that to a UAV, the counts are correct. But if I take that same capture and step through the code debugger I don't see all the different bytecode ops, I only see zeros.

I may take a look at this after work hours, but I figured someone else might find the cause quicker than I can.

**Comment by loosche** [comment]
Update:
I just saw this work in version v0.23. Since last time I have changed the format from r32_uint to r8_uint for the buffer being loaded from. Same D3D IL however.

**Comment by baldurk** [comment]
This is a complete stab in the dark, but talking about changing the format got me thinking - how do you create your buffer SRV?

This is the important structure:
```cpp
struct D3D11_SHADER_RESOURCE_VIEW_DESC
{
	DXGI_FORMAT Format;
	D3D11_SRV_DIMENSION ViewDimension;
	union 
	{
		struct /*D3D11_BUFFER_SRV*/ Buffer
		{
			union 
			{
				UINT FirstElement;
				UINT ElementOffset;
			};
			union 
			{
				UINT NumElements;
				UINT ElementWidth;
			};
		};
		/* Texture union members, not important */
	};
};
```

I assume `ViewDimension` is set to `D3D11_SRV_DIMENSION_BUFFER` and `Format` is `DXGI_FORMAT_R32_UINT` since format=unknown is only used for structured buffers AFAIK, but then there's ambiguity in how you set up the members of D3D11_BUFFER_SRV. As far as I know the documentation is *completely* useless in telling you which of these two equivalent forms you should use, RenderDoc does what I think is the right thing (and I've seen it recommended [elsewhere](http://stackoverflow.com/questions/26544489/d3d11-buffer-srv-how-do-i-use-it)) and always interprets this as `FirstElement`/`NumElements`.

RenderDoc uses these values to figure out which section of the buffer to readback to the CPU into a byte array, and that byte array is then interpreted according to the format when you do any [ld_indexable loads from it](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/d3d11/shaders/dxbc_debug.cpp#L3172-L3338). If it didn't read back enough, out of bounds loads would come back as 0, which might explain what you were seeing. It wouldn't explain why it got fixed unless you changed the srv descriptor.

If you see it broken again though, it might be worth breakpointing in that code and stepping through to see if the data is missing, broken (0s when it shouldn't be) or if something else is going wrong.

**Comment by loosche** [comment]
I did change the SRV descriptor

<code>
.Format= _r32_uint -> _r8_uint;
.ViewDimension= D3D11_SRV_DIMENSION_BUFFER;
.FirstElement= 0;
.NumElements= num_32_bit_elements -> num_8_bit_elements;
</code>

So your comments make sense. I'll see if I can repro it with the old types. 

I've tried to look into it a few times but I'm having trouble figuring out how to setup the .sln file so that I can step into the actual renderdoc dll when running from the renderdoc ui from inside visual studio.

**Comment by baldurk** [comment]
Hmm, if it was consistent before that wouldn't tie into my theory.

[This commit](https://github.com/baldurk/renderdoc/commit/b8d5b3f4af2820d2b7eefa5a1e6cd58ffc82a842) might really help with running and stepping in - the VS defaults are rubbish at .NET & C++ debugging together - previously you had to enable this setting manually as I thought it could only be enabled in the user properties file which I can't commit to git.

**Comment by loosche** [comment]
So I believe I can see what's going on in RenderDoc. 

The assembly instruction in question is 

    ld_indexable(buffer)(uint,uint,uint,uint) r9.w, r14.xxxx, t1.yzwx

The bytes at the beginning of the buffer are (52, 0, 65 1). When DebugThread() is run it gets the proper byte from the stream (52), and then there's a loop (in GetNext() in dxbc_debug.cpp:line 3327):

````
ShaderVariable fetch("", 0U, 0U, 0U, 0U);

for(int c=0; c < 4; c++)
{
	uint8_t comp = op.operands[2].comps[c];
	if(op.operands[2].comps[c] == 0xff)
		comp = 0;

	fetch.value.uv[c] = result.value.uv[comp];
}

s.SetDst(op.operands[0], op, fetch);
````

which swizzles the bytes (fetch.yzwx = results.xyzw) into the State s. I'm **guessing** the D3D Compiler generates this swizzle because it wants to copy the result into r9.w, so the desired value (t1.x) needs to be moved to the .w channel.

I **bet** RenderDoc is assuming the output value of this operation that should be stored is (t1.yzwx).x (since only one value is supposed to be output) instead of matching up the outputs and returning (t1.yzwx).w to match r9.w. 

That could also explain why it worked somtimes. If the register allocation is different and we're storing the load into r#.x you'd never see the problem.

I'll keep looking, but figured I'd update with my findings in case it gives you an ah-ha! moment.

**Comment by baldurk** [comment]
Yes I think that does give me an ah-ha! moment. As usual, it makes me feel stupid for making the mistake in the first place.

It's one of the things that's messy about the DX bytecode and it's combined with a sloppy implementation on my side. This vector-input-scalar-output is kind of an edge case and the same thing came up in the resinfo opcode. My code assumes that if you're assigning to a scalar in SetDst then the value is in the .x component of the parameter, the source swizzling is usually handled in GetSrc. That way I don't have to worry about component selections all throughout the code - I can just treat scalars as .x everywhere. The problem here is that after the swizzle I haven't moved the 'scalar' into the x component so in SetDst I end up doing the wrong thing.

Unfortunately it's hard to force the compiler to generate a nice test case for me since the register allocation is all internal. Can you try putting this code right before the s.SetDst, which would be copied from the OPCODE_RESINFO handling except I noticed a copy-paste bug in it while writing this. Oooops:

```cpp
// if we are assigning into a scalar, SetDst expects the result to be in .x (as normally we are assigning FROM a scalar also).
// to match this expectation, propogate the component across.
if(op.operands[0].comps[0] != 0xff && op.operands[0].comps[1] == 0xff && op.operands[0].comps[2] == 0xff && op.operands[0].comps[3] == 0xff)
  fetch.value.uv[ 0 ] = fetch.value.uv[ op.operands[0].comps[0] ];
```

And see if that fixes it for you. It's annoying to have this special case code but there are few instructions that do this vector-to-scalar thing I believe. If that fixes it I'll need to double check all of the ones to make sure I'm handling correctly.

**Comment by loosche** [comment]
I completely understand about not being able to test it, it's the same reason I can't look at this bug at home (because it's work code).

Your change seems to fix my problem. There are other parts of the loop that use different ld_indexeable (for uint8 and float4s) and they all seem to still be working too. You probably still want to run the change through your own test battery of course.

Thanks for finding this!

Brad

**Comment by baldurk** [comment]
To make an apple pie from scratch, I'd have to construct the universe. To run this change through my test battery, I'd have to make some tests :). (Don't worry, it's planned! Just a lack of time/prioritisation).

It sounds like the change is a good one, and like I say I ran across this problem for resinfo too which is why I had that code to hand. I'll double check all the other opcodes that might run into this issue, ie. not basic arithmetic and logical ones etc.

**Comment by loosche** [comment]
It's totally fine, I just wanted to make sure you knew I hadn't done more than run that code for my specific problem. 

Thanks again for the fix, and RenderDoc in general. It's super helpful!

**Comment by baldurk** [comment]
I've committed my change now, it seems fine. I'm going to close this since it fixes your issue.

**Comment by loosche** [comment]
Looks like the commit was slightly different than what you told me to use. All your comparisons are !=, when the last three should be ==.

Your commit looks like this:

if(op.operands[0].comps[0] != 0xff && op.operands[0].comps[1] != 0xff && op.operands[0].comps[2] != 0xff && op.operands[0].comps[3] != 0xff)

When it should look like this:

if(op.operands[0].comps[0] != 0xff && op.operands[0].comps[1] == 0xff && op.operands[0].comps[2] == 0xff && op.operands[0].comps[3] == 0xff)

**Comment by baldurk** [comment]
Damn, you are exactly right. You can see [on this line](https://github.com/baldurk/renderdoc/commit/9273a5bdb31c7bd8a171e32513198952479d4780#diff-8a97242cc5903301b045dc7c081c0315L3110) that when I originally gave you the lines of code I saw both the mistake of using comps[0] in every comparison as well as the != vs ==. When I actually made the commit, I fixed the first mistake but not the other.

Thanks for catching that!
