### ISSUE TITLE
Crash when attached to Vulkan app (Debug)

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#1235]
## Description

Whenever I launch my Vulkan app (Windows) on Debug mode, it crashes on startup; after creating the back buffer's render pass and setting up the views. It works fine in Release for RenderDoc and in Debug it runs fine without RenderDoc attached. 
I'm using the following extensions:
```
Creating Vulkan instance with 5 extensions & 1 layers:
        Extensions:
                VK_KHR_surface
                VK_KHR_win32_surface
                VK_EXT_debug_utils
                VK_EXT_debug_report
                VK_KHR_get_physical_device_properties2
        Layers:
                VK_LAYER_LUNARG_standard_validation
Creating Vulkan device with 5 extensions & 0 layers:
        Extensions:
                VK_KHR_swapchain
                VK_KHR_shader_draw_parameters
                VK_KHR_get_memory_requirements2
                VK_KHR_dedicated_allocation
                VK_KHR_multiview
```
This happened somewhere along my [project](https://github.com/OsomiLunar/ocore), but I am unable to pinpoint when exactly. I'm guessing it happened after I added the extra extensions (VK_KHR_get_memory_requirements2, VK_KHR_dedicated_allocation, VK_KHR_get_physical_device_properties2 or possibly VK_KHR_multiview (even though I don't use it yet)).

## Repro steps

Launch my app's debug build through RenderDoc. Release works fine and both builds work fine; without validation errors or other errors when you run them normally.

## Environment

RenderDoc build: v1.2 (https://github.com/baldurk/renderdoc/commit/ae895cd2ba218c4c7f75750a009a403ad181f95f)
Operating system: Windows 10
API: Vulkan
Extensions: surface, win32, debug & validatino, device properties 2, swapchain, draw parameters, memory requirements 2, dedicated allocation, multiview
GPU: GTX 1060 6GB
Driver: NVIDIA 25.21.14.1701

**Comment by baldurk** [comment]
I can't follow your repro steps because I don't have a copy of your application. Can you share it with me so that I can debug further? I can't do anything without something to investigate.

If you can't share the application can you give more information about the crash - what's the callstack at the point that it crashes, does it happen with the validation layers disabled, etc.

**Comment by Nielsbishere** [comment]
My project is open source on [GitHub](https://github.com/OsomiLunar/ocore), but I have uploaded the debug build to my [Dropbox](https://www.dropbox.com/s/91bosze87i7dhbl/Osomi%20Core%20x64.exe?dl=0). It might seem odd because it's just an exe, but the resources are included into the exe and it's fine, I promise (run a [scan](https://www.virustotal.com/#/file/14dba91c45b484df9c3a92b3179e63b2d05503d3cc78608f9b912cc44b947d50/detection) if you still think it's odd).
If you run it without RenderDoc attached it works perfectly fine (you can see a rotating planet), but with RenderDoc attached it crashes. Due to this, I wasn't able to find the exact point where it crashes, because before I can attach VS to my application it has crashed. Like I said before, the Release build works fine.

**Comment by baldurk** [comment]
Thanks. I'm having trouble running the exe because it requires xinput1_4.dll which isn't available, I get the same thing when compiling from source. Any ideas?

EDIT: To get a callstack you can usually select to debug from the windows post-crash popup, assuming RenderDoc's crash handler isn't kicking in:

![image](https://user-images.githubusercontent.com/661798/51211297-fe675e80-190c-11e9-9ab3-970d78078c3f.png)

Failing that you can also set 'debugger delay' to say 30s when launching the program, that gives you enough time to attach a debugger before the program actually runs.

**Comment by Nielsbishere** [comment]
Hmm, which windows are you running? Xinput is being used for controller input in owc/src/platforms/windows/wcontroller.cpp and it might work if you change the xinput version but I should look at that myself I think. A quick fix could be to comment out the contents of the Controller::update function and commenting out the pragma comment(lib). I'm not at my pc atm, but will try your suggestion asap.
EDIT: Also, it doesn't just crash, it just automatically closes.. so there's no popup like that :(

**Comment by Nielsbishere** [comment]
Okay, so when I attach the debugger, it crashed at my vkName function:
```cpp
template<typename T>
void vkName(GraphicsExt &g, T val, VkObjectType type, String name) {

	const VkDebugUtilsObjectNameInfoEXT namedInfo = {
		VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT, // sType
		NULL,                                               // pNext
		type,												// objectType
		(uint64_t)val,										// object
		name.toCString()									// pObjectName
	};

	if(g.debugNames == nullptr)
		return;

	g.debugNames(g.device, &namedInfo);

}
```
it seems like g.debugNames (which is the function to name an object) points to renderdoc's internal naming function. I don't have the symbols, but I can see that it crashes inside of RenderDoc after calling another function.
```
RDOC 005556: [23:42:25]  vk_device_funcs.cpp( 558) - Log     - Initialised capture layer in Vulkan instance.
RDOC 005556: [23:42:25]  vk_device_funcs.cpp( 933) - Log     - physical device 0: GeForce GTX 1060 6GB (ver 417.1 patch 0x0) - 10de:1c03
RDOC 005556: [23:42:25]          vk_core.cpp( 985) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
RDOC 005556: [23:42:25]          vk_core.cpp( 985) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
RDOC 005556: [23:42:25]          vk_core.cpp( 985) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
RDOC 005556: [23:42:25]          vk_core.cpp( 985) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
'Osomi Core.exe' (Win32): Loaded 'C:\Windows\System32\winsta.dll'. Cannot find or open the PDB file.
Exception thrown at 0x00007FFFB2EB7CE1 (renderdoc.dll) in Osomi Core.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

**Comment by baldurk** [comment]
I'm running windows 7, I can try win10 tomorrow if it only works there.

What version of the validation layers are you running? Some older versions had a bug that would crash inside the debug marker functions due to incorrect handling. You could check to see if it crashes when you enable the validation layers in release. Or doesn't crash if you force-off the validation layers in debug. Then it is most likely a bug with them.

**Comment by Nielsbishere** [comment]
Windows 7 doesn't support xinput1_4, I've change it to xinput9_1_0 so it will probably work on Windows 7 too. I think it is the validation layers, but I got the latest version of the Vulkan SDK; which should contain the correct validation layers right? Release mode doesn't have layers, it strips them; which explains why it works.

**Comment by baldurk** [comment]
I got it compiled & running just by commenting out the controller code. For me it crashes inside vkName even without renderdoc at all:

![image](https://user-images.githubusercontent.com/661798/51216131-34134400-191b-11e9-9634-150a4848a919.png)

I looked at the `VkDebugUtilsObjectNameInfoEXT` struct and the `objectHandle` is wrong - the `ext` being passed into the function is your `oi::gc::SamplerExt *` and not a `VkSampler`, meaning it's set to `0x1e30ba8` where if I go up the callstack and look, the actual handle returned was stored in `ext->obj` which is `0x20` - more what I'd expect when the unique handles layer is active.

I'd double check your `vkName` code to make sure you only ever pass a valid vulkan handle in there, if you pass anything else then I would expect that to crash inside renderdoc.

**Comment by Nielsbishere** [comment]
Just double checked it, it was also being done in my pipeline implementation. I changed it sometime when I added memory allocation. So I'm guessing RenderDoc intercepts the call to debugNames and gets the name and figures out the object passed was invalid? Weird that it didn't give me any runtime or compile-time errors (I did see it did for you, but not on my pcs?). It's fixed now, thank you for your time and I guess the report about xinput too :+1:

**Comment by baldurk** [comment]
RenderDoc does indeed intercept naming so that it can display the names in the UI. It doesn't do any validation or checking - it will look up per-object data to know where to store the name, and when you pass an invalid object it won't know that and will write into random memory giving the crash.

It's not possible to catch at compiel time but the validation layers should catch this, I'd recommend filing an issue with them to request that they check object validity in these functions.

**Comment by Nielsbishere** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/590 hopefully it will be fixed, but my application runs correctly now. :+1:
