### ISSUE TITLE
Add option to specify ignored/whitelisted vulkan layers/extensions

### ISSUE THREAD

**Issue by tafuri** [baldurk/renderdoc#1237]
## Description
Due to the nature of how vulkan extensions/layers work, renderdoc will currently not accept replays containing unknown layers/extensions. In the general case this makes sense, but in some cases it could be useful to work around this issue.

We are currently using a couple of private vulkan layers/extensions related to diagnostics and stat counting which means that by design they *should* only observe and not affect anything.
Currently if we, for some reason, do not disable these layers we can still capture in renderdoc but trying to replay these captures will generate an error.

I therefore see a use in allowing an option to manually specify layers which will always be ignored, or perhaps even better, excluded from renderdoc captures/replays.

## Environment
* RenderDoc build: v1.2
* API: Vulkan

**Comment by baldurk** [comment]
Your description is a bit entangled, layers and extensions are different and I can't tell exactly which you're talking about. Layers can't add any new functionality so shouldn't in theory cause any problems with capture/replay whether they're present or not, extensions are the ones that require careful handling.

For layers, they are currently not filtered at all during capture. All layers that are available are reported back to the application and can be enabled freely, the list of which is then saved in the capture. On replay, I strip out a few known layers that shouldn't be replayed - primarily the validation layers but also a couple of others that come with the SDK.

For extensions, the reported lists during capture time are trimmed to only extensions that RenderDoc supports. Any unsupported extensions (including unknown ones by definition) are hidden from the application's enumeration so only supported extensions can be enabled. Then similar to layers the list is saved in the capture and replayed, except without any extensions being stripped out.

Currently I require all layers and extensions to be present on replay to successfully load the capture. The difference is that arguably layers don't provide any functionality in themselves, so it doesn't have to be a blocking error to not have a layer. I wouldn't mind making it a warning/non-blocking error for a layer to be missing. I'd just remove it from the list and continue, and it would only become blocking if an extension is missing.

In theory I could also filter layers similarly to extensions, so that applications naturally act as if the layer isn't present. Though I would have a list of exclusions rather than a list of inclusions.

So for your case, can you be more specific about exactly whether it's a layer or extension or both that you're talking about? If it's a layer then I think there will be a solution.

**Comment by tafuri** [comment]
Yes, you are right. I did not clearly differentiate between layers and extensions so let me try to give some more context.

I implemented layer which collects information on all memory allocations and created resource to be able to determine some statistics and worst case metrics. This layer currently also exposes a new function used to report this information back to the host application. But except for this entry point this layer is supposed to be completely transparent.
Reading the specification of differences between layers and extensions I got under the impression that, even though the new functionality is practically transparent I must also declare an extension since I do modify the result `vkGetDeviceProcAddress`, to be compliant with the specification. I do not have to report and enable this extension though, it would work just as fine.

But it would still be nice to be able to declare extra layers which renderdoc should hide or ignore.

**Comment by baldurk** [comment]
OK I understand where you're coming from. To clarify - is it the extension or the layer that causes RenderDoc to fail to replay?

Yes if you're implementing any new functionality then you need to provide a new extension in the layer. However if you want to use that extension in your application you still have to report it and enable it. As you've found it might still work for now even if you don't do that, but there's no guarantee that will always work because it's invalid behaviour, and you'll encounter problems like this in RenderDoc.

If your layer does report a new internal extension and your application checks for whether or not the extension is available, I think it should work correctly. Outside of RenderDoc you'll see the extension available and enable it, and similarly your application should be able to gracefully fallback and disable the extension when RenderDoc is injected and hides the reported availability.

I'm not going to add any option to bypass extension whitelisting because it is a very good way to cause things to explode. It's far too easy for users to enable it without understanding and cause crashes without knowing what's going on. Even in your case, it might work at the moment if the new function call doesn't use any vulkan objects but it would likely start crashing if in future you added a new function to e.g. record and query for only the number of resources referenced in a particular command buffer.

**Comment by tafuri** [comment]
Sure, I agree. I mostly wanted to bring this up for discussion since it confused some people here at first when they could not use their captured replays.

So the question then is, how come this extension was reported as available for me when I captured through renderdoc? This may have been a separate mistake on my part of course, so I will verify this and report as a bug if that was actually the case. At least now I know what the intended behavior of renderdoc is regarding unknown extensions (ie filter them).

Just a final question. What is the rationale to expose all unknown available layers? Why are they not also filtered by default?

**Comment by baldurk** [comment]
Yeh, everything should be filtered, even for layer-provided extensions. If you're seeing the extension still being reported that's definitely a problem so let me know - it's quite possible there's an issue lurking here somewhere as I think the only cases of layers reporting extensions I'm aware of are the validation layers, and I support EXT_debug_report / EXT_debug_marker for them.

If everything is working well then as long as the application enumerates what's available it should all be compatible - aside from the case where there's a layer that only your application can see at capture time. I've convinced myself that should be non-fatal so I'll make sure the replay handles that case.

The reason I haven't filtered layers is mostly because in theory I shouldn't need to. A layer can inject itself into the callstack but without an extension it shouldn't add any new functions or structs or anything. Any changes it makes should be application-invisible so that legal code before is still legal code afterwards. In fact the only reason I *do* filter extensions is because they can add new functions or structs, which are very likely to break without proper wrapping and handling.

**Comment by tafuri** [comment]
They should not affect anything but it will still impose an extra dependency on that capture.  Sure you can argue that it is not the responsibility of renderdoc to handle that. But it is perhaps something to think about.

Thanks for the clarifications!
