### ISSUE TITLE
Renderdoc does not always filter out unknown extensions

### ISSUE THREAD

**Issue by tafuri** [baldurk/renderdoc#1238]
## Description
This is related to issue #1237

It seems like when `vkEnumerateInstanceExtensionProperties` or `vkEnumerateDeviceExtensionProperties` is used with a layer specified in `pLayerName`, renderdoc will not filter out that extension.

This behavior does make some sense, but since the vulkan specification specifies that:
> When pLayerName parameter is NULL, only extensions provided by the Vulkan implementation or by implicitly enabled layers are returned. When pLayerName is the name of a layer, the instance extensions provided by that layer are returned.

The only way to enumerate extensions from a non-implicit layer is to specify that layer in `pLayerName`.

## Repro steps

1.  Enable a layer unknown to renderdoc containing a custom extension
2. Call `vkEnumerateDeviceExtensionProperties`with the custom layer name and collect the results
3. Note that the custom extension is returned as available and can be enabled.

## Environment

* RenderDoc build: v1.2
* Operating System: Windows 10
* API: Vulkan 1.1

**Comment by baldurk** [comment]
Argh, your interpretation is exactly right - layers should only return their device extensions when `pLayerName` is their own name.

Unfortunately I think you'll find (I did in my test) that if you breakpoint on your implementation of `vkEnumerateDeviceExtensionProperties` it only ever gets called with `pLayerName = NULL`. The [loader's implementation](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/trampoline.c#L901-L910) for the case of `pLayerName = "foo"` actually goes directly to the json manifest and reads the extensions declared there. That means your layer implementation doesn't get called, and neither does RenderDoc's to filter it.

This can't be fixed in RenderDoc without abandoning the layer system entirely and hooking entry points above the layers, it has to be fixed in the loader. I'm going to open an issue there and hopefully this can be addressed in a future loader.

In the meantime I can't really suggest a great workaround other than using some other method to detect renderdoc like `GetModuleHandleA("renderdoc.dll") != NULL` and manually pretending the extension isn't there.

**Comment by baldurk** [comment]
Actually looking at the code further and doing a quick test - `vkEnumerateInstanceExtensionProperties` should be correctly filtered as it goes straight through the pre-instance call chain. Did you definitely see unknown extensions coming through if you enumerate that way? That might be a better workaround in the meantime, to just make your extension instance-level (which isn't generally a good idea but if it's internal-only it should work OK as it's technically legal).

**Comment by tafuri** [comment]
Yes, I noticed this while debugging also which is unfortunate.

My current workaround was to look for the value of `ENABLE_VULKAN_RENDERDOC_CAPTURE` since the layer wont activate unless this is set to 1. Unfortunately it will require a similar check for all known capture/replay tools layers... For my specific uses I can definitely use `vkEnumerateInstanceExtensionProperties` instead, I will try that and see how the other tools behave.

In the meantime though, would it not be a slight usability improvement to fail device creation when renderdoc detects unknown extensions during capture also instead of just during replay?

**Comment by baldurk** [comment]
Usually I rely on validation to catch that, but yes in this case it's not going to work because the validation layers won't see any problem until there's a change to the loader. I have a check for instance extensions because not everyone will have a loader capable of filtering them, so I'll add a parallel check for device extensions.

**Comment by baldurk** [comment]
That commit doesn't fix the issue completely but as mentioned it should check for unsupported device extensions and error out at vkCreateDevice time.

**Comment by tafuri** [comment]
Great, it is at least more consistent now.

Unfortunately I spoke to soon regarding using `vkEnumerateInstanceExtensionProperties` instead. Apparently the loader does not support loading any instance extensions from layers which are not known in the spec or part of a driver...

**Comment by baldurk** [comment]
Hmmm, yeh that's tricky. The real solution is to allow filtering of that function, until then I think it's just a matter of picking your poison for a hack in the meantime :disappointed: .

**Comment by baldurk** [comment]
I made a change to the loader which now calls through RenderDoc's layer (and all others) for enumerating device extensions. If you build the loader from source now it should work, and that will get rolled into the SDK and official loader builds at some point (I'm not sure if it will make it for the _next_ version).

One thing to bear in mind is there's a bug with the validation layers that will corrupt the results of that call. So if you're using them with the new loader you probably want to build them from source too.

I made the RenderDoc side changes to support this a while back so once you update the loader this will be resolved on v1.4 and forwards and any unsupported extensions in layers will be filtered out. Closing the issue as there's nothing more to do.
