### ISSUE TITLE
App is blocked by Bitdefender

### ISSUE THREAD

**Issue by frydzielson** [baldurk/renderdoc#1241]
## Description

Hi.
When I try to launch a game with RenderDoc it is instantly blocked by antivirus software, so I cannot use it.
Is renderDoc safe? If so, is there a workaround for this issue? Temporarily disabling antivirus software is not working, it still blocks renderdoc.

Sorry for my english :)

## Environment

* RenderDoc build: 1.2_64
* Operating System: Windows 10
* API: No idea

"Bitdefender Total Security" is really "Totally Securing"... and "Bitdefending"

**Comment by baldurk** [comment]
Hi, I replied to your email about this too but for the sake of anyone else; I can't suggest any fix for this apart from disabling the antivirus or whitelisting RenderDoc in some way. If RenderDoc is still blocked then you haven't temporarily disabled the antivirus completely.

RenderDoc uses standard windows APIs to inject itself into the target program. This is something that malicious software could do, but there are many legitimate uses for it so any antivirus blocking is a false positive.

If you're unsure about RenderDoc then you can compile a version from source code. You can look at the source code and examine it to make sure nothing malicious is there. Otherwise I can promise that there are no viruses in the binary builds, which you can check with an upload to virustotal.com.

**Comment by frydzielson** [comment]
Thank you. I will let you know if and how I make it work.

**Comment by frydzielson** [comment]
It works, but whitelisting didn't do anything. I had to completely disable everything in Bitdefender, and whitelist it in windows defender. Thank you for four super fast reply :)
