### ISSUE TITLE
glCreateShaderProgramv isn't properly handled in mesh output view

### ISSUE THREAD

**Issue by Aeva** [baldurk/renderdoc#1244]
## Description
The "GS/DS Output" tab in the mesh viewer shows no data, but the geometry shader appears to be otherwise working fine.

## Repro steps
1. Select a draw call with a working geometry shader, and see that it never the less shows nothing in the "GS/DS Output" tab in the mesh viewer.

I have a small test program where in [this commit](https://github.com/Aeva/messing_with_compute_shaders/commit/6d0bfc3142e4567a134bcc5bad2d2c68694df003), I have the GS just drawing a full screen quad.  And likely more useful I also have a capture demonstrating the issue: [gs_output_repro.zip](https://github.com/baldurk/renderdoc/files/2776394/gs_output_repro.zip)

## Environment
* RenderDoc build: 2019-01-11 nightly build.
* Operating System: Fedora Linux
* API: OpenGL 4.2

**Comment by baldurk** [comment]
This looks like it's caused by the use of `glCreateShaderProgramv` to create the programs - the code is assuming that each stage has an actual shader where that only creates a separable program. I'll need to add another path to handle it.

Out of interest I did run into a couple of shader issues loading the repro capture on my machine - the VS/FS/GS shaders have `#extension GL_ARB_compute_shader : require` declared which _really_ confuses the driver. I'm not sure if this is supposed to be legal and ignored. The VS also needs to redeclare `gl_PerVertex` due to GL's stupid separable program rules.

**Comment by baldurk** [comment]
That should now work (bar the other issues mentioned above), I added a path to handle `glCreateShaderProgramv` programs.

**Comment by Aeva** [comment]
Awesome, thank you so much!

Now that you point it out, I have no idea if its legal to do that with extensions either.  I just figured without thinking too hard about it that it would be fine to put all of the extensions I intended to use into a common block :3
