### ISSUE TITLE
Make wireframe overlay work well under zooming

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#1248]
## Description

Wireframe overlay is useful to understand the output geometry with regards to affected pixels. When zooming, however, the wireframe becomes thicker:

![renderdoc-wireframe](https://user-images.githubusercontent.com/107301/52068490-c128e080-254a-11e9-85d4-f314023bf977.png)

There is no reason why wireframe rendering should be drawing a pixel-to-pixel with the render target. If the target is zoomed, it would be helpful to still see the wireframe drawn in thinnest lines. For example, we'd be able to tell instantly if we missed the pixel center and by how much, instead of going for the calculator and computing the screen space positions based on vertex outputs manually.

## Repro steps

1. Enable wireframe overlay.
2. Zoom in.

## Environment

* RenderDoc build: v1.2
* Operating System: Linux
* API: OpenGL

**Comment by baldurk** [comment]
I'm not sure I agree, I think it's more consistent for the overlays to show up at the same resolution as the output texture. If the wireframe overlay is decoupled then probably some of the others like highlight drawcall should be, but at the same time depth/stencil test etc shouldn't be and then you end up with a weird disparity.

There are also implementation concerns. You'd have to run the draw with a patched viewport of some kind to fetch the subsection you want at higher resolution (since you couldn't supersample enough without quickly hitting texture dimension limits). I'm not sure off the top of my head if you could end up in trouble in some cases doing that with certain state/shaders. With the wireframe overlay in particular if you're expecting mathematical precision I'm not sure you'd actually get that precision, due to implementation/line rasterization differences with the different draw state.

I'll leave this open for now, but I lean against making such a change. I think it follows the principle of least surprise to have the overlays be the same resolution, and it seems like a very specialised use-case to need an arbitrary wireframe resolution.

**Comment by kvark** [comment]
@baldurk I agree, the concept of overlay implies that zoom would affect it like all other pixels. For this reason, I think wireframe shouldn't be an overlay.
I still think this would be useful to have (basically, every time I use the wireframe overlay, I need that zooming ability), but I understand that it's not the lowest hanging fruit around in terms of implementation :)

**Comment by baldurk** [comment]
I'm closing this as I don't think I'll ever make this change. The use-case of needing to know precise rasterizer test results is an interesting one and there's probably a way to display that information, but I think a very low-priority one. Also as above I think it would probably need to use either some more sophisticated way of getting rasterizer feedback or a reference rasterizer, not the wireframe overlay.
