### ISSUE TITLE
Child processes on Android not hooked

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1263]
## Description
I can't crawl my app.
my application name is com.eg.android.goodplay.
but it has some children process.

When I modify my program and only set a process, I can perform the crawl operation.

In the renderdoc "android.cpp" code, which process is launched, the corresponding pid will be obtained, and then the process will be inject. If it is another process, the corresponding interception will not be performed.

Is renderdoc not supporting multiple processes in an application?
If you want to try it, there are many examples of applications like this. 
for example：3Dmark

**Comment by baldurk** [comment]
Hi there, I'm not sure I understand your problem description 100%, but it seems like the main problem you have is that your android program launches a child process?

This won't ever be supported on OpenGL ES as it stands now, because GLES needs complex hooking logic that can only be controlled from the host machine. It can't be run on the device so it wouldn't be possible to hook the child process.

It won't work right now for Vulkan I think because it still requires some hooking to change the search paths for Vulkan layers, but it's possible it could be supported in future Android versions if the Vulkan layer search path can be controlled externally.

I think for your case the only workaround is to modify your app to not use child processes, or launch the child process directly from RenderDoc somehow. It seems like you're able to do that already.

Does that answer your question?

**Comment by z00318884** [comment]
yes，Your answer is what I want.I I can capture by changing my program.If my phone is the root version, can I intercept it by replacing libGLES.so?

**Comment by baldurk** [comment]
No RenderDoc doesn't support hooking by replacing libGLES.so, as it expects to be able to load that library to call GLES functions.

You might be able to 'manually' hook by calling `dlopen("libVkLayer_GLES_RenderDoc.so")` at the very start of your child process, but I can't guarantee this will work and it's not supported.
