### ISSUE TITLE
Add handling for D3D12.4 interfaces

### ISSUE THREAD

**Issue by giordi91** [baldurk/renderdoc#1268]
## Description
Good afternoon, I am trying to run render doc with my dx12 application. The applications runs, but there  is not RenderDoc overlay and cannot take captures, I managed to look at the log and seems there are few errors here below the log:

```
RDOC 172160: [16:30:36]             core.cpp( 310) - Log     - RenderDoc v1.2 64-bit Release (204724bebe2484ee2d14a572d9f1074dd3f933a9) loaded in replay application
RDOC 172160: [16:30:36]      crash_handler.h( 112) - Log     - Creating crash-handling server
RDOC 178768: [16:30:36]             core.cpp( 310) - Log     - RenderDoc v1.2 64-bit Release (204724bebe2484ee2d14a572d9f1074dd3f933a9) loaded in replay application
QTRD 172160: [16:30:37]       qrenderdoc.cpp(  88) - Log     - QRenderDoc initialising.
QTRD 172160: [16:30:43]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
QTRD 172160: [16:30:45]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///C:/Users/marco/Desktop/WORK_IN_PROGRESS/SirEngineThe3rd/build/bin/Debug/Sandbox.exe")) 1
RDOC 172160: [16:30:50]    win32_process.cpp( 493) - Log     - Running process C:\Users\marco\Desktop\WORK_IN_PROGRESS\SirEngineThe3rd\build\bin\Debug\Sandbox.exe
RDOC 172160: [16:30:50]    win32_process.cpp( 577) - Log     - Injecting renderdoc into process 179532
RDOC 179532: [16:30:51]             core.cpp( 310) - Log     - RenderDoc v1.2 64-bit Release (204724bebe2484ee2d14a572d9f1074dd3f933a9) capturing application
RDOC 179532: [16:30:51]      crash_handler.h( 112) - Log     - Creating crash-handling server
RDOC 179532: [16:30:53]   win32_libentry.cpp(  66) - Log     - Loading into C:\Users\marco\Desktop\WORK_IN_PROGRESS\SirEngineThe3rd\build\bin\Debug\Sandbox.exe
RDOC 179532: [16:30:53]  sys_win32_hooks.cpp(  82) - Log     - Registering Win32 system hooks
RDOC 179532: [16:30:53]      d3d11_hooks.cpp( 125) - Log     - Registering D3D11 hooks
RDOC 179532: [16:30:53]      d3d12_hooks.cpp( 125) - Log     - Registering D3D12 hooks
RDOC 179532: [16:30:53]       d3d8_hooks.cpp(  36) - Log     - Registering D3D8 hooks
RDOC 179532: [16:30:53]       d3d9_hooks.cpp(  45) - Log     - Registering D3D9 hooks
RDOC 179532: [16:30:53]       dxgi_hooks.cpp(  77) - Log     - Registering DXGI hooks
RDOC 179532: [16:30:53]        egl_hooks.cpp( 654) - Log     - Registering EGL hooks
RDOC 179532: [16:30:53]         gl_hooks.cpp( 191) - Log     - Registering OpenGL hooks
RDOC 179532: [16:30:53]        wgl_hooks.cpp( 555) - Log     - Registering WGL hooks
RDOC 179532: [16:30:53]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
RDOC 179532: [16:30:53]      d3d12_hooks.cpp( 203) - Error   - Unsupported UUID GUID {e865df17-a9ee-46f9-a463-3098315aa2e5} for D3D12CreateDevice
RDOC 179532: [16:30:53]      dxgi_common.cpp(1370) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 179532: [16:30:53]      dxgi_common.cpp(1365) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 172160: [16:30:53]   target_control.cpp( 560) - Log     - Got remote handshake: Sandbox [179532]
RDOC 179532: [16:30:53]     dxgi_wrapped.cpp(1066) - Error   - Creating swap chain with non-hooked device!
RDOC 172160: [16:30:56]    win32_network.cpp( 222) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.

```
More specifically:

```
RDOC 179532: [16:30:53]      d3d12_hooks.cpp( 203) - Error   - Unsupported UUID GUID {e865df17-a9ee-46f9-a463-3098315aa2e5} for D3D12CreateDevice
```

The code is using a ID3D12Device4. Is just a matter of the device being too recent? As far as I can tell the application is well behaved, no errors reported by debug layer and gpu validation. Pix seems to work just fine. 

## Repro steps
If the log is not enough, please let me know I can provide the executable to run.

## Environment

* RenderDoc build: e.g. v1.2,https://github.com/baldurk/renderdoc/commit/204724bebe2484ee2d14a572d9f1074dd3f933a9
* Operating System: Windows 10 1809
* API:D3D12

This happens on both Intel graphics for a surface pro and a 2080ti on latest driver. I can try to run on an AMD card as well if it helps.

**Comment by baldurk** [comment]
Yes, D3D12.4 with `ID3D12Device4`, `ID3D12GraphicsCommandList4`, etc is not supported. From what I can tell that contains almost all DXR raytracing stuff. If your program doesn't use DXR then there's no reason to use that interface as it will only hurt compatibility (e.g. if the user isn't on the right version of Windows 10 it won't work either). If you _do_ need DXR then RenderDoc won't work at all.

I can add enough support to gracefully report that these interfaces/features aren't supported, but for DXR etc I have no plans to support it.

**Comment by giordi91** [comment]
Make sense, I will be downgrading the device and let you know. I do plan to integrate some of the DXR code I have but will be behind compile switch. I was using device 5 for DXR, Did not know device 4 was for DXR aswell.

**Comment by giordi91** [comment]
Thank you for your patience, I have removed the version 4 of device and command list, but I am not able to run my application. RenderDoc simply does not attach. The log says:
```
RDOC 001780: [10:23:23]      dxgi_common.cpp(1365) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 007148: [10:23:23]   target_control.cpp( 787) - Log     - Used API: D3D12 (Not presenting & supported)
RDOC 007148: [10:23:33]    win32_network.cpp( 222) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.
```

I started digging around and rather than let Render Doc start the application I have injected it right at the beginning of main. My application crashes when trying to create the command list:

```
  result = DEVICE->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT,
                                     fc->commandAllocator, nullptr,
                                     IID_PPV_ARGS(&fc->commandList));
```

My FrameCommand struct (fc) is declared as such:
```
struct FrameCommand final {
  ID3D12CommandAllocator *commandAllocator = nullptr;
#if DXR_ENABLED
  ID3D12GraphicsCommandList4 *commandList = nullptr;
#else
  ID3D12GraphicsCommandList3 *commandList = nullptr;
#endif
  bool isListOpen = false;
};
```

Similarly goes for the Device. Without render doc attached the the program works fine across the board, I worked on 4 different machines spanning all 3 major IHV:

* 8700k + rtx6000
* surface pro IGPU
* 4790k + vega 64
* 2700X + rtx 2080ti

The command list never failed and run fine. I was able to test on bot the vega 64 and 2080ti system and both fail to create the command list if Render Doc attaches. 

Any Idea about this matter? Would you rather me open a different issue and close this one?

Extra information: Currently NSight Graphics seems to bomb as well after few frames. I tried to analyze the memory dump but is corrupted. Might be completely unrelated. 
On the other hand, Pix works perfectly fine on all 4 computers and Radeon profiler has no issues as well on the Vega system.

PS:
Managed to read something out of the .dmp for NSight, it crashes when reading a null pointer deep int he Nvidia dll. Seems to be related to a command allocator. I don't think the two crashes are related, but worth to share as much information as possible. Here part of the dump
```

PRIMARY_PROBLEM_CLASS:  NULL_POINTER_READ

BUGCHECK_STR:  APPLICATION_FAULT_NULL_POINTER_READ

LAST_CONTROL_TRANSFER:  from 00007ffda592dda2 to 00007ffd7f2f6412

STACK_TEXT:  
00000016`f11ef048 00007ffd`a592dda2 : 00000000`00000008 00007ffd`844b4498 00000206`7c890fa0 00000206`7c86dd50 : nvwgf2umx+0x3d6412
00000016`f11ef050 00000000`00000008 : 00007ffd`844b4498 00000206`7c890fa0 00000206`7c86dd50 00000206`7c890fa0 : nvapi64+0x25dda2
00000016`f11ef058 00007ffd`844b4498 : 00000206`7c890fa0 00000206`7c86dd50 00000206`7c890fa0 00007ffd`843f9272 : 0x8
00000016`f11ef060 00000206`7c890fa0 : 00000206`7c86dd50 00000206`7c890fa0 00007ffd`843f9272 00000000`00000000 : D3D12!`CCommandAllocator::_GetEntries'::`2'::_entries+0x28
00000016`f11ef068 00000206`7c86dd50 : 00000206`7c890fa0 00007ffd`843f9272 00000000`00000000 00000000`00000000 : 0x206`7c890fa0
00000016`f11ef070 00000206`7c890fa0 : 00007ffd`843f9272 00000000`00000000 00000000`00000000 00000000`00000000 : 0x206`7c86dd50
00000016`f11ef078 00007ffd`843f9272 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x206`7c890fa0
00000016`f11ef080 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : D3D12!CPrivateData::Set+0x6e


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  nvwgf2umx+3d6412

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: nvwgf2umx

IMAGE_NAME:  nvwgf2umx.dll

DEBUG_FLR_IMAGE_TIMESTAMP:  5c5b3624

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_nvwgf2umx.dll!Unknown

BUCKET_ID:  X64_APPLICATION_FAULT_NULL_POINTER_READ_nvwgf2umx+3d6412

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/Sandbox_exe/0_0_0_0/5c67e9a7/nvwgf2umx_dll/25_21_14_1891/5c5b3624/c0000005/003d6412.htm?Retriage=1

```

**Comment by baldurk** [comment]
This issue is still valid, I should hopefully be able to do non-capturing pass-through support, or at least handle the interfaces enough to reject them with a proper error message and report lack of support for those interfaces.

I don't understand exactly what's happening though. You say "RenderDoc simply does not attach" but then the log snippet you posted indicates that RenderDoc _did_ attach after all. Can you post the full log which might show the problem rather than only a small segment which doesn't immediately show anything wrong? In general I advise against loading RenderDoc manually as it can cause issues if you don't know exactly what you're getting yourself in for, and it's very rarely needed.

I'm not sure why the call to `CreateCommandList` would be crashing. In your case it should return `E_NOINTERFACE` because `ID3D12GraphicsCommandList3` is not a supported interface, but this is handled correctly by returning the appropriate error message. If you can provide me with a repro application that shows the crash, or if you can send me the minidump, I can debug it further.

Can you try using `ID3D12GraphicsCommandList2` or lower? Unless you need `ID3D12ProtectedResourceSession` then there is no reason to use `ID3D12GraphicsCommandList3` because the only function it adds is `SetProtectedResourceSession`.

**Comment by giordi91** [comment]
Apologies for the confusion. In the original issue render doc would not attach, and my app runs without RenderDoc overlay. After downgrading to v3, render doc started crashing (and before that correctly attaching to my app) sorry for the confusion. 

Also, my terminology was wrong, it was not a crash, it was correctly returned `E_NOINTERFACE`. Rather than a crash was failing to create the command list. If you don't mind me asking why would `ID3D12GraphicsCommandList3` be a not supported interface?

After downgrading to `ID3D12GraphicsCommandList2` I was able to successfully run `RenderDoc` and make a capture. Thank you.

**Comment by baldurk** [comment]
OK that makes sense, I'm glad you got it working then. To clarify RenderDoc was attaching and was injected into the process, but it wasn't properly hooking the D3D12 interfaces. That's why you didn't get the overlay and couldn't capture.

It's not supported just because I haven't added a wrapper for that interface :smile:. It's not even documented properly on MSDN (as is sadly typical for D3D) so the best I can do is some kind of pass-through wrapper and hope no-one actually uses those new interfaces. D3D12's versioning is a complete mess so when I say 'D3D12.4' that's really an approximation for whichever updates brought the DXR stuff which seems to have kind of combined multiple interfaces together.

I would strongly suggest that if you don't need the functionality provided by higher versioned interfaces then don't request them. With COM they're all virtual calls so you still get the same implementation of base functionality regardless - all you'll end up doing is reducing your compatibility with tools and users.

I will keep this issue open so I make sure that an application checking for interface/feature support properly can work with RenderDoc without needing any compile time toggles. But if you do need DXR then of course you do need the higher versioned interfaces, and as I mentioned I don't plan to support those features so it would be unusable in RenderDoc anyway. There's not much that can be done about that.

**Comment by giordi91** [comment]
Thank you. I really appreciated the explanation. No worries about DXR, I will have it under compile switch because I wish to run my code on AMD as well.

Cheers.

**Comment by baldurk** [comment]
That commit adds support for the new interfaces although they mostly add DXR and whatever protected resource sessions are, which are reported as unsupported so an application correctly checking for the features shouldn't use any of the functionality that's not implemented.
