### ISSUE TITLE
Replay API initialisation failed

### ISSUE THREAD

**Issue by TheShot** [baldurk/renderdoc#1273]
## Description
  Hello.
  The capture created on a Android machine. And I load the capture locally. The error information is :Failed to open capture for replay API initialisation failed. When I check diagnostic,I found "libEGL not available, and GL cannot initialise or doesn't support EXT_create_context_es2_profile"and"Couldn't create a replay device :(.". I  drop the libEGL.dll into plugins/gles in my RebderDoc folder, but it doesn't work.I drop the wrong libEGD.dll? I don't konw what's wrong with me.Please help me,Thank you very much.

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* API: e.g. Vulkan, D3D11, OpenGL, etc

**Comment by baldurk** [comment]
Loading captures locally on a host PC from an Android device is not supported. It may work but I **strongly** recommend that you follow the normal workflow and load them on the Android device instead, that way you are most likely to have the capabilities to replay.

The error you're getting is because RenderDoc can't create a replay context. Since you're talking about copying libEGL.dll into the plugins/gles folder that suggests you're using a GLES emulator - to the best of my knowledge no GLES emulator on windows provides reliable ES3 replay capability that RenderDoc needs. ANGLE is by far the most reliable emulator but it doesn't fully implement ES3 and has bugs if you try to use it, and all the other emulators I tried are very buggy and break.

Again if you're capturing from Android then replay on Android, replaying locally is quite likely to break.

**Comment by TheShot** [comment]
Thank you very much. I will follow the normal workflow.
