### ISSUE TITLE
Crash on launch when using ID3D11Texture2D1 in IDXGISwapChain3::GetBuffer

### ISSUE THREAD

**Issue by wobbier** [baldurk/renderdoc#1276]
## Description
I'm getting a crash launching my engine through RenderDoc. It seems to crash when using ID3D11Texture2D1 when calling IDXGISwapChain3::GetBuffer

> Workaround is to use **ID3D11Texture2D** instead of **ID3D11Texture2D1**

## Repro steps

```C++
ComPtr<ID3D11Texture2D1> backBuffer;
DX::ThrowIfFailed(m_swapChain->GetBuffer(0, __uuidof(ID3D11Texture2D1), &backBuffer));
DX::ThrowIfFailed(
	m_d3dDevice->CreateRenderTargetView1(
		backBuffer.Get(),
		nullptr,
		&m_d3dRenderTargetView
	)
);
```
Console log stuff
> RDOC 002744: [22:15:37]     d3d11_device.cpp( 171) - Log     - New D3D11 device created: nVidia / NVIDIA GeForce GTX 1070 Ti 25.21.14.1881
RDOC 002744: [22:15:37]          app_api.cpp( 334) - Log     - Initialising RenderDoc API version 1.3.0 for requested version 10200
RDOC 002744: [22:15:39]     dxgi_wrapped.cpp( 453) - Error   - Unsupported or unrecognised UUID passed to IDXGISwapChain::GetBuffer - GUID {51218251-1e33-4617-9ccb-4d3a4367e7bb}

## Environment

* RenderDoc build: v1.2 release
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
Yes I need to add explicit handling for that UUID in `IDXGISwapChain::GetBuffer`, the workaround as you've found is to use one of the supported UUIDs.

I don't think there's any advantage here that I can see to using `ID3D11Texture2D1` since that interface only allows querying the `D3D11_TEXTURE2D_DESC1` which differs only by `D3D11_TEXTURE_LAYOUT`, which isn't relevant for swapchain images.

**Comment by baldurk** [comment]
With that commit `IDXGISwapChain::GetBuffer` should now accept `ID3D11Texture2D1` and `ID3D12Resource1` in the case applications request through those interfaces instead of the normal ones.
