### ISSUE TITLE
RenderDoc crashes if app draws without a vertex buffer

### ISSUE THREAD

**Issue by manhnt9** [baldurk/renderdoc#1287]
## Description

RenderDoc can capture, save, expand draw call list but fails to inspect a draw call (crashes when click on a draw call).

Console output:
```
Log     - QRenderDoc - renderer created for "/home/manh/Desktop/test.rdc"
Segmentation fault
```

## Repro steps

- Download and extract [test.zip](https://github.com/baldurk/renderdoc/files/2909019/test.zip)
- Load capture file
- Click on a draw call

## Environment

* RenderDoc build: v1.2
* Operating System: Ubuntu 18.04
* API: Vulkan
* GPU: GTX 1050Ti
* Driver: NVIDIA 410.78

**Comment by manhnt9** [comment]
Sorry I forgot to turn on my validation layers. Errors caused by my app.

**Comment by manhnt9** [comment]
Well validation layer prints this:
`
DS(ERROR / SPEC): object: 0x55c8653b84e0 type: 6 msgNum: 26 - The Pipeline State Object (0x1e) expects that this Command Buffer's vertex binding Index 0 should be set via vkCmdBindVertexBuffers. This is because VkVertexInputBindingDescription struct at index 0 of pVertexBindingDescriptions has a binding value of 0.
DS(ERROR): object: 0x55c8653b84e0 type: 6 location: 991 msg_code: 26: Object: 0x55c8653b84e0 | The Pipeline State Object (0x1e) expects that this Command Buffer's vertex binding Index 0 should be set via vkCmdBindVertexBuffers. This is because VkVertexInputBindingDescription struct at index 0 of pVertexBindingDescriptions has a binding value of 0.
`

But anyways RenderDoc should tolerate this error (drawing without binding a vertex buffer).
Since I'm doing this trick: https://www.saschawillems.de/?page_id=2122
The standalone app runs fine.

**Comment by baldurk** [comment]
To clarify - drawing without a vertex buffer as in the page you linked works fine. The issue here is that your pipeline descriptor still lists a vertex binding which is then not bound and that's what crashes:

![image](https://user-images.githubusercontent.com/661798/53479276-95791780-3a70-11e9-8cd5-b9d79e9ceb21.png)

It's unclear to me whether this is allowed or banned by the specification, it seems to be a little unclear/contradictory in places. Since in this case it's simple to catch out of bounds vertex buffers and pretend they read 0s (since it won't actually be used in this shader) I've made that fix, but I'd suggest not declaring the vertex buffer at all in case some drivers have an issue with that.

**Comment by manhnt9** [comment]
Wow thanks for the catch. It worked. I forgot to set the vertex binding count.
More over, you've given me a lead to solve another bug in my engine too.
