### ISSUE TITLE
Fail to capture GLES on Android 9

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1289]
## Description

Got a SIGSEGV when starting a GLES app. This crash doesn't occur if we build RenderDoc using the interceptor lib. It seems without interceptor lib, some of the GLES calls are not captured.
(backtrace is attached) [3dmark_backtrace .txt](https://github.com/baldurk/renderdoc/files/2910814/3dmark_backtrace.txt)

Using the interceptor lib, we tried to capture 3DMark but we got an infinite loop. Skia methods are caught by RenderDoc and skia reports "program linking failed" so it deletes the program and tries again.

Skia uses the glProgramBinary function to create shader programs but in RenderDoc this call does nothing. There is a solution for this, that is glProgramBinary function in RenderDoc should trigger an incorrect glProgramBinary call to create a program linking error. I will upload a pr for this soon.

From Android 9, it's suggested to use interceptor lib to capture every GLES calls and avoid crashes.
We have started to work on integrating the interceptor lib to the cmake build system.  

## Repro steps

1. Install 3DMark to a device with Android 9 os.
(3DMark on Google Play: https://play.google.com/store/apps/details?id=com.futuremark.dmandroid.application) 
2. Set up 3DMark to capture with RenderDoc
2. A)  Start 3DMark with RenderDoc without interceptor lib
2. B) Start 3DMark with RenderDoc using interceptor lib

## Environment

* RenderDoc build: v1.x
* Operating System: Android 9
* API: OpenGL ES

**Comment by baldurk** [comment]
I don't have access to any Android 9 device unfortunately so I can't test this directly. Let me know if you find a way to repro this without needing Android 9 and I can look into it.

To be clear: the only supported way of capturing on Android is with interceptor-lib. It's expected there might be bugs or crashes without it as it is the only known mostly reliable way to inject into GLES applications, and I won't fix bugs related to building without it. The PLT hooking path is provided just as a "best effort" solution as a fallback if LLVM isn't available to build interceptor-lib, but all nightly and official builds are built with it enabled.

I'm not clear if the problem only happens when compiling without interceptor-lib or not. First you say it doesn't crash, but then you say it does infinite loop - what exactly happens?

> Using the interceptor lib, we tried to capture 3DMark but we got an infinite loop. Skia methods are caught by RenderDoc and skia reports "program linking failed" so it deletes the program and tries again.
> 
> Skia uses the glProgramBinary function to create shader programs but in RenderDoc this call does nothing. There is a solution for this, that is glProgramBinary function in RenderDoc should trigger an incorrect glProgramBinary call to create a program linking error. I will upload a pr for this soon.

Can you explain this in more detail? RenderDoc suppresses glProgramBinary, so when the program checks for the `GL_LINK_STATUS` of the program it will see `GL_FALSE` because it hasn't been linked. Then the program can fallback to uploading the GLSL as we want. What goes wrong in this path in your case?

> We have started to work on integrating the interceptor lib to the cmake build system.

I don't understand what you mean. There is already support for enabling interceptor-lib via cmake since that's how it's built, what are you proposing to change?

**Comment by tabikati** [comment]
SIGSEGV only occurs if the LLVM interceptor lib is not used. Therefore we would like to integrate building the LLVM interceptor lib instead of building it manually as it works now.

When we use the LLVM interceptor lib, we don't have this SIGSEGV crash but there is an infinite loop which doesn't cause a crash but it prevents starting the 3DMark application. This can be reproduced with a Samsung Galaxy S9 which has an Android 9 op.  (I also tested it with a Xiaomi Pocophone F1 which has Android 9 too and with other Samsung devices with Android 7 and 8, but they worked fine, I couldn't reproduce this issue with them.) 

As for the infinite loop,  I can see that after glCreateProgram, glProgramBinary is called but in case of capture mode, RenderDoc doesn't call the actual function (only in replay mode). This causes the skia program linking to fail. glDeleteProgram and then glCreateProgram is called again, restarting the loop.

A part of the logcat is attached: [skia_loop_logcat.txt](https://github.com/baldurk/renderdoc/files/2914448/skia_loop_logcat.txt)

**Comment by baldurk** [comment]
> SIGSEGV only occurs if the LLVM interceptor lib is not used.

If the bug only happens without interceptor-lib then I don't plan to fix it, as there are known issues with the PLT hooking method that can never be solved.

> Therefore we would like to integrate building the LLVM interceptor lib instead of building it manually as it works now.

This doesn't make sense to me. interceptor-lib is **already** part of the build when LLVM is configured.

Are you suggesting that LLVM itself should be built from source as part of compiling renderdoc? If so then that is absolutely not acceptable.

For one thing as far as I'm aware it is impossible to build LLVM for android from windows (I tried many times) so this would completely break android compilation on windows. Even if that were solved it would increase the burden for compiling RenderDoc's android build massively with impact on every user and Travis CI.

For people who only use Vulkan or know that the PLT hooking works for their case, they can build for Android at the moment without heavy dependencies. For people who want to build for Android with the best GLES hooking support they can compile LLVM once and cache it on their system for later use. There are instructions available for how to build it.

> As for the infinite loop, I can see that after glCreateProgram, glProgramBinary is called but in case of capture mode, RenderDoc doesn't call the actual function (only in replay mode). This causes the skia program linking to fail. glDeleteProgram and then glCreateProgram is called again, restarting the loop.

It seems like there's more going on here. An application using `glProgramBinary` will do something like this:

```
GLuint prog = glCreateProgram();
glProgramBinary(prog, ...);
GLint status = 0;
glGetProgramiv(sepProg, GL_LINK_STATUS, &status);

if(status == 0)
{
  // .. fallback to uploading source here
}
```

By omitting the call to `glProgramBinary`, the program's `GL_LINK_STATUS` value will remain at 0 since it was never linked, so the application is forced to upload its source.

The logcat you posted also contains these messages which indicate that the code is trying to fallback to using `glAttachShader` and `glLinkProgram` but something else is going wrong - something not explained by `glProgramBinary` failing:

```
02-28 10:05:01.883 18254 18361 I renderdoc: @5c77a43d00001017@ RDOC 018254: [10:05:01]  gl_shader_funcs.cpp( 556) - Error   - Assertion failed: 'progRecord && shadRecord' 
02-28 10:05:01.884 18254 18361 I renderdoc: @5c77a43d00001018@ RDOC 018254: [10:05:01]  gl_shader_funcs.cpp( 556) - Error   - Assertion failed: 'progRecord && shadRecord' 
02-28 10:05:01.884 18254 18361 I renderdoc: @5c77a43d00001019@ RDOC 018254: [10:05:01]  gl_shader_funcs.cpp(1066) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=1368)
02-28 10:05:01.884 18254 18361 I renderdoc: @5c77a43d0000101a@ RDOC 018254: [10:05:01]  gl_shader_funcs.cpp(1066) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=1368)
02-28 10:05:01.884 18254 18361 I renderdoc: @5c77a43d0000101b@ RDOC 018254: [10:05:01]  gl_shader_funcs.cpp(1066) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=1368)
02-28 10:05:01.884 18254 18361 I renderdoc: @5c77a43d0000101c@ RDOC 018254: [10:05:01]  gl_shader_funcs.cpp( 903) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=1368)
```

**Comment by tabikati** [comment]
OK, I understand that integrating the LLVM build won't work. Can we make and include a script that helps to build the LLVM?

I have created a pull request that fixes the Skia looping issue:
https://github.com/baldurk/renderdoc/pull/1292

It seems the problem is that after calling glProgramBinary, glGetError is called but it returns 0, so Skia assumes that everything went fine with the linking. But after that, it checks the link status and since it is 0, deletes the program.

We can solve it if we generate an INVALID_OPERATION error when glProgramBinary is called, to make the app notice that this call wasn't successful.

This issue is related to Skia on Android 9, and the same function calls happen in every GLES application not only in 3DMark.

**Comment by baldurk** [comment]
There's already documentation and instructions on how to build LLVM, I don't think there is value in trying to maintain a script that will work for everyone automatically, compared to asking people to manually follow the instructions.

`glProgramBinary` should not return `GL_INVALID_OPERATION` on a valid call, from the extension spec:

> **If ProgramBinary fails to load a binary, no error is generated**, but any information about a previous link or load of that program object is lost. Thus, a failed load does not restore the old state of <program>. The failure does not alter other program state not affected by linking such as the attached shaders, and the vertex attribute and fragment data location bindings as set by BindAttribLocation and BindFragDataLocation.

Which is exactly what happens with RenderDoc's implementation now - the program is untouched and remains unlinked if it hasn't been successfully linked before. The application must then check `GL_LINK_STATUS` to see if the binary was successfully uploaded - and if not then fall back to setting GLSL.

If some application code is only checking for `glGetError()` then it is wrong and should be fixed. You say that it does check the link status but deletes the program if it's 0 - that is incorrect behaviour. Generating an error would be invalid and might lead applications behaving correctly to think something else has gone wrong when it hasn't.

You also still haven't explained why the log you pasted also showed calls to `glAttachShader` and `glLinkProgram`, if Skia is only calling `glProgramBinary` then deleting the program.

**Comment by tabikati** [comment]
Please find the related Skia source code here:
https://github.com/google/skia/blob/cd700e9ab7d07eb502792a0bdab450154141a31e/src/gpu/gl/builders/GrGLProgramBuilder.cpp#L213
`glProgramBinary` is called in the 210th row. Then, since no error was generated, the `checkLinkStatus` method is called (367th row).
Inside `checkLinkStatus` method,  if the `GL_LINK_STATUS` is false, `glDeleteProgram` is called and `checkLinkStatus` returns false, setting the `cached` variable to false.
Since `cached` is false (223rd row),  it continues to compile and attach shaders to the already deleted program, that's when we get the assertion failed messages.
This indeed seems to be a wrong behavior but this is how it works now. Can we fix this issue by generating an error when `glProgramBinary` is called only in case of Android?

**Comment by baldurk** [comment]
You've described a clear bug in Skia's code. I suggest filing an issue with their project to get it fixed - for example not deleting the program if `checkLinkStatus` fails in this case since it's not fatal.

Regardless of platform I'm not going to add a hack into RenderDoc to fix buggy application code, especially not if it could break working applications.

**Comment by tabikati** [comment]
I will report an issue to Skia but it may take a long time to be fixed, and we can't capture GLES apps on Android 9 until that. 

**Gapid** and **apitrace** also generate an error when glProgramBinary is called:
https://github.com/apitrace/apitrace/blob/9b9eb3d955b2464006a0790470be6d8f8ee14fe6/wrappers/gltrace.py#L749
https://github.com/google/gapid/blob/aa82473fe2105ea3cbf4a7a7f120ca1bdc385cb7/gapii/cc/spy_disable_precompiled_shaders.cpp#L91

**Comment by baldurk** [comment]
I know users who have captured on Android 9 fine - exaggerating the scope of the problem will not change the situation.

Other programs are free to implement such hacks if they want and accept the consequences and downsides. gapid even seems like it checks the program hashes to avoid reporting the error in certain known-broken applications, which is where this road leads.
