### ISSUE TITLE
In-app help window is blank

### ISSUE THREAD

**Issue by steel3d** [baldurk/renderdoc#129]
03/31 Nightly. Press F1.

The right pane where the actual information should be is empty. None of the articles from the contents tree show up.

**Comment by baldurk** [comment]
I wonder if this might be because of [silly chm limitations](http://weblog.helpware.net/?p=36). I've seen it before when you get downloaded files that windows has marked as "potentially insecure" - exes have the little popup asking you if you're sure you want to run it, and I think CHMs just flat-out don't work. Can you try opening the chm manually to see if you get a prompt that you can then clear? or check the file properties as in that link above.

**Comment by steel3d** [comment]
Good call! Opening renderdoc.chm manually and unchecking "warn every time" allows it to open correctly from the app.

Btw, this is with the "portable zip" install. I haven't seen this issue in the past with the installer install.

Thanks!

**Comment by baldurk** [comment]
Yeh I think if you install then the windows prompt will only happen when you launch the installer, anything the installer copies to your system is fair game and considered secure.

**Comment by steel3d** [comment]
Pretty obscure problem with the zip install, still... Wonder if you can somehow force the UAC window to pop up for the chm instead of silently fail...
