### ISSUE TITLE
Long shader sources in the Resource Inspector are stepped over when scrolling

### ISSUE THREAD

**Issue by fekga** [baldurk/renderdoc#1298]
## Description
The scrollbar in the GUI has steps that are bound to the Treeview elements' top. This causes long shader sources to not be fully visible when scrolling down because it causes the view to step to the next element and goes out of view.

## Repro steps
This can be recreated with any shader that has at least as much lines as the GUI element's length allows, but a few hundred lines will certainly cause problems.

## Environment

* RenderDoc build: v1.2
* Operating System: Windows 10
* API: OpenGL

**Comment by baldurk** [comment]
Yes this is a side-effect of having the view set to scroll in units of whole items, rather than pixels. I think that for the typical data in the resource inspector that's better. It is a bit unexpected behaviour when a row that's longer than usual shows up, so what I can do is trim any string data to appear with a maximum of a couple of lines and then ends "...". That way it will behave more predictably upon scrolling.

To view the source of a shader from the resource inspector you can click the 'view contents' button at the top right to open the shader viewer.

**Comment by baldurk** [comment]
With that commit as mentioned above, strings with more than 3 lines will be truncated for display in the resource inspector.
