### ISSUE TITLE
Renderdoc injection fails when using address sanitizer `-fsanitize`

### ISSUE THREAD

**Issue by carlfindahl** [baldurk/renderdoc#1299]
## Description
Renderdoc injection fails when using address sanitizer with GCC 8.2.1 (at least) on Linux.

## Repro steps

Given a basic OpenGL program, such as a Hello Triangle program, compile it with `-fsanitize=address` and link with `asan` compiling with GCC. When trying to launch Renderdoc, the injection will fail.

Probably the same will happen using Clang and other versions of GCC too.

![img](blob:https://imgur.com/fa763c52-b0f2-414d-aad7-e00c93bc92f1)

## Environment

* RenderDoc build: 1.2
* Operating System: Arch Linux
* API: OpenGL

**Comment by baldurk** [comment]
When I did this I got this error from ASan:

```
==26122==ASan runtime does not come first in initial library list; you should
either link runtime to your application or manually preload it with LD_PRELOAD.
```

Which suggests that libasan expects to be the first library loaded, and with an otherwise empty `LD_PRELOAD` then RenderDoc injecting its library first via `LD_PRELOAD` breaks that assumption.

As suggested in that error I configured `LD_PRELOAD` to point to `libasan.so` in RenderDoc before launching the program, and that then worked fine. From a quick google search for the error it seems like an alternate solution is to specify `-static-libasan` when linking the program itself which also seems to work for me, but YMMV.

In general though I would not be surprised to see more subtle bad interactions between these tools since they may fight over trying to do the same thing. I would _strongly_ recommend against trying to use them both together, and only use RenderDoc on builds without sanitizers enabled.
