### ISSUE TITLE
Upgrade to openssl 1.1

### ISSUE THREAD

**Issue by Lawrencemm** [baldurk/renderdoc#1317]
I believe it's just a build switch in QT. If one has the openssl 1.1 development package installed, Renderdoc crashes on startup:
```
[user@hero bin]$ ./qrenderdoc 
Log     - QRenderDoc initialising.
Warning - QSslSocket: cannot resolve CRYPTO_num_locks
Warning - QSslSocket: cannot resolve CRYPTO_set_id_callback
Warning - QSslSocket: cannot resolve CRYPTO_set_locking_callback
Warning - QSslSocket: cannot resolve ERR_free_strings
Warning - QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
Warning - QSslSocket: cannot resolve EVP_CIPHER_CTX_init
Warning - QSslSocket: cannot resolve sk_new_null
Warning - QSslSocket: cannot resolve sk_push
Warning - QSslSocket: cannot resolve sk_free
Warning - QSslSocket: cannot resolve sk_num
Warning - QSslSocket: cannot resolve sk_pop_free
Warning - QSslSocket: cannot resolve sk_value
Warning - QSslSocket: cannot resolve SSL_library_init
Warning - QSslSocket: cannot resolve SSL_load_error_strings
Warning - QSslSocket: cannot resolve SSL_get_ex_new_index
Warning - QSslSocket: cannot resolve SSLv23_client_method
Warning - QSslSocket: cannot resolve SSLv23_server_method
Warning - QSslSocket: cannot resolve X509_STORE_CTX_get_chain
Warning - QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
Warning - QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
Warning - QSslSocket: cannot resolve SSLeay
Warning - QSslSocket: cannot resolve SSLeay_version
Warning - QSslSocket: cannot call unresolved function CRYPTO_num_locks
Warning - QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
Warning - QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
Warning - QSslSocket: cannot call unresolved function SSL_library_init
Warning - QSslSocket: cannot call unresolved function SSLv23_client_method
Warning - QSslSocket: cannot call unresolved function sk_num
Segmentation fault (core dumped)
```

ATM I've installed the compatibility openssl 1.0 development package but this might become a problem if I need something that requires 1.1 development package.

**Comment by baldurk** [comment]
I'm not sure I understand the problem exactly. RenderDoc doesn't link directly against openssl, qt will depend on it. So it depends on the qt that you are building against on your system. 

I'm currently away until the end of next week so I will look at this in depth when I'm back.

**Comment by baldurk** [comment]
I've had a look at this more closely and I'm still not clear what the problem is.

As I understand it, in openssl 1.1 some symbols were removed from the library so it's not backwards compatible with 1.0, meaning binaries linked against 1.0 need to be sure to open precisely that version. At the same time there was also an issue with the [Qt binary builds](https://bugreports.qt.io/browse/QTBUG-68156) where they were being built on a distro (RHEL) that patched the openssl version information, so that instead of trying to open `libssl.so.1.0.0` or `libcrypto.so.1.0.0` it instead loaded `libssl.so.1.0.2k` which only existed on RHEL as I understand it.

I'm not sure if you're building renderdoc from source yourself or you're running the binary builds I make (either stable versions or nightly). If you're building from source I don't see how this error could occur as the Qt on your system should point at the correct compatible library, even if it's not necessarily portable. If you're running binary builds then I build them on an ubuntu 14.04 install with a custom-compiled Qt, which I've verified has the correct 1.0.0 SONAME. So on any distribution as long as the `1.0.0` suffixed library is present it will get loaded, even if an incompatible `1.1` exists.

The only case that would break is if _only_ `1.1` is available so Qt falls back to loading un-suffixed `libssl.so` when it can't find `1.0.0` and has the wrong version with missing symbols. However when I tested this by temporarily renaming libraries on an Ubuntu 18.04 install I did get the errors about missing symbols and the SSL request failed (the analytics submission), but nothing crashed and the program ran as normal apart from the failed request.

Given all of that I don't understand what is going wrong in your case. Can you please explain exactly what your problem is with information on your distribution and how you are building and running RenderDoc so I can understand the issue, rather than jumping to a suggested fix which is not helpful.

**Comment by Lawrencemm** [comment]
I'm trying to run nightly pre-built.

To my surprise, the development version of openssl is required to run renderdoc on Fedora, and this is the problem - while both library versions can be installed at once, the development versions - compat-openssl10-devel and openssl-devel, conflict.

**Comment by baldurk** [comment]
It sounds like it's a distro issue then - as above red hat distros patch the SONAME for openssl, so when the Qt code linked into qrenderdoc looks for `libssl.so.1.0.0` it doesn't find it. Development openssl libraries will likely set up a `libssl.so` symlink which is used as a fallback, and so as long as you have the 1.0 development library installed then the fallback happens to load the right thing.

I'd recommend building renderdoc yourself since then it will work with your distro's conventions, and is the only reliable way to have software on linux since as we can see binary distributions are flawed.
