### ISSUE TITLE
RenderDoc in-app API overrides OpenGL's debug output settings and `Enable API Validation` seems no effect

### ISSUE THREAD

**Issue by liurui39660** [baldurk/renderdoc#1325]
## Description

I'm using OpenGL 4.5. As long as I load RenderDoc's dll in my app before creating the window (`glfwCreateWindow`), the built-in debug output (`GL_DEBUG_OUTPUT`) no longer takes effect. 

However, if I load the dll after creating the window, the debug output will work but RenderDoc fails.

Question 1: I'd like to both enable RenderDoc in-app API and OpenGL's debug output, when shall I load the dll file?

If I remove all the RenderDoc in-app API and OpenGL's debug output code from my application, and using the RenderDoc GUI, checking `Enable API Validation` and then launch my application, the "Errors and Warnings" can't catch any error in my application (I left an invalid call `glGenBuffers(-1, &temp);` on purpose).

Question 2: What's the correct way to enable API validation?

#### Debug-Output-Not-Working Code

```cpp
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <Windows.h>
#include <renderdoc_app.h>
#include <cassert>

void callback(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar* message, GLvoid* userParam) {
	abort();
}

int main(int argc, char* argv[]) {
	glfwInit();
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	RENDERDOC_API_1_3_0* rd = nullptr;
	if (const HMODULE mod = LoadLibrary("renderdoc.dll")) {
		const auto RENDERDOC_GetAPI = reinterpret_cast<pRENDERDOC_GetAPI>(GetProcAddress(mod, "RENDERDOC_GetAPI"));
		assert(RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_3_0, reinterpret_cast<void **>(&rd)));
	}
	GLFWwindow* window = glfwCreateWindow(1280, 720, "", nullptr, nullptr);
	glfwMakeContextCurrent(window);
	glewExperimental = true;
	glewInit();
	glEnable(GL_DEBUG_OUTPUT);
	glDebugMessageCallback(callback, nullptr);
	glClearColor(0.6, 0.6, 1, 1);
	unsigned temp;
	glGenBuffers(-1, &temp); // Error
	while (!glfwWindowShouldClose(window)) {
		glClear(GL_COLOR_BUFFER_BIT);
		glfwSwapBuffers(window);
		glfwPollEvents();
	}
}
```

Nothing happens

#### Debug-Output-Working Code

```cpp
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <Windows.h>
#include <renderdoc_app.h>
#include <cassert>

void callback(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar* message, GLvoid* userParam) {
	abort();
}

int main(int argc, char* argv[]) {
	glfwInit();
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	GLFWwindow* window = glfwCreateWindow(1280, 720, "", nullptr, nullptr); // Moved here
	RENDERDOC_API_1_3_0* rd = nullptr;
	if (const HMODULE mod = LoadLibrary("renderdoc.dll")) {
		const auto RENDERDOC_GetAPI = reinterpret_cast<pRENDERDOC_GetAPI>(GetProcAddress(mod, "RENDERDOC_GetAPI"));
		assert(RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_3_0, reinterpret_cast<void **>(&rd)));
	}
	glfwMakeContextCurrent(window);
	glewExperimental = true;
	glewInit();
	glEnable(GL_DEBUG_OUTPUT);
	glDebugMessageCallback(callback, nullptr);
	glClearColor(0.6, 0.6, 1, 1);
	unsigned temp;
	glGenBuffers(-1, &temp); // Error
	while (!glfwWindowShouldClose(window)) {
		glClear(GL_COLOR_BUFFER_BIT);
		glfwSwapBuffers(window);
		glfwPollEvents();
	}
}
```

The `abort` will be called.

### Question 2

1. Compile the code below

```cpp
#include <GL/glew.h>
#include <GLFW/glfw3.h>
int main(int argc, char* argv[]) {
	glfwInit();
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	GLFWwindow* window = glfwCreateWindow(1280, 720, "", nullptr, nullptr);
	glfwMakeContextCurrent(window);
	glewExperimental = true;
	glewInit();
	glClearColor(0.6, 0.6, 1, 1);
	unsigned temp;
	glGenBuffers(-1, &temp); // Error: Parameter 1 should be greater than 0
	while (!glfwWindowShouldClose(window)) {
		glClear(GL_COLOR_BUFFER_BIT);
		glfwSwapBuffers(window);
		glfwPollEvents();
	}
}
```

2. Launch the application via RenderDoc GUI with `Enable API Validation` checked.
2. Press F12 to capture a frame.
2. Quit your application.
2. Switch to "Errors and Warnings" tab in RenderDoc.
2. Nothing there.

## Environment

* RenderDoc build: v1.2
* Operating System: Windows 10 Education, Version 1511, no .NET 4.7 available
* API: OpenGL 4.5 with GLFW 3.2.1.5 (via NuGet) and GLEW 1.9.0.1 (via NuGet)

**Comment by baldurk** [comment]
There are a few things to note here:

1. You must **always** load renderdoc.dll before any graphics API calls, and ideally on the first line of main. Loading the RenderDoc library after calling any graphics API functions could lead to unpredictable behaviour or crashes.
2. RenderDoc only saves the API validation calls that occur during the rendering captured in a frame, and then shows those messages next to the event where they happen. Any invalid calls that happen before the frame like in `glGenBuffers` here won't be shown.
3. It's also important to note that RenderDoc will not handle all invalid API use. Many calls will be fine if they can still be captured and replayed, but some calls like the one you have shown could cause crashes in RenderDoc. For the best results it's always recommended to fix any validation errors separately before trying to use RenderDoc.
4. Finally - when RenderDoc is present it takes control over any debug output and does not pass it on to the application, which is the behaviour you're seeing. This is to avoid the problem shown in your example where the application's callback is too sensitive and kills the whole program when any message is received, as validation layers commonly produce false positive warnings when RenderDoc is capturing a frame.
  You can disable this behaviour using the `eRENDERDOC_Option_DebugOutputMute` option in RenderDoc's API, but if you do so then you should remove any call similar to `abort()` in your callback.

I don't think there's an actual bug here as this is behaving as expected, so I'll close this issue. If you think there is a bug please comment and let me know.
