### ISSUE TITLE
avx 256 issue

### ISSUE THREAD

**Issue by ronanbel** [baldurk/renderdoc#133]
Hi, I'm facing a crash while running some code (DX11, either NVidia or ATI driver).
I'm mapping a texture, and filling it using SIMD intrinsic _mm256_stream_si256
When this code runs as stand-alone, it's fine (meaning that mapped buffer is at least 32bytes aligned)
When this code runs through Renderdoc "capture executable", the mapped buffer is only 16bytes aligned.
(I can "hack" my code to use AVX128 instructions)
I'm not sure it comes from Renderdoc (I don't know if mapped buffer pointer comes from D3D or from Renderdoc. If it's the case, would it be possible to align it to at least 32bytes boundary please ?

**Comment by baldurk** [comment]
That commit should align any pointers returned from Map() to 32-bytes instead of 16-bytes.

But as far as I'm aware the D3D spec only guarantees 16-byte alignment - see [pData here](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476182(v=vs.85).aspx) and [this D3D10 page](https://msdn.microsoft.com/en-us/library/windows/desktop/bb205132%28v=vs.85%29.aspx) which seems to still apply to all feature levels above D3D10 - so you might be relying on undefined behaviour and it might not always be 32-byte aligned, even stand-alone.

**Comment by ronanbel** [comment]
Hi Baldur, thanks for your support :)
I tried with the latest nightly version, still the same issue. Does your change align (32bytes) memory also for textures please ? (I assume it does since the class is named "resource")
I don't know if I'm lucky with "stand-alone" alignment. It's fine on all hardware I'm using. (maybe it's undocumented and D3D force alignment as soon as you have an AVX CPU, I don't know)

**Comment by baldurk** [comment]
Oh right! No, if you are mapping textures there will need to be other changes as well, I'll look into that.

Yes if it's working for now then it doesn't really matter, but I wanted to warn you just in case you distribute it somewhere and other people get a crash maybe.

**Comment by baldurk** [comment]
That commit should now ensure texture Map() pointers are coming back 32-byte aligned. If you're still having issues after tonight's nightly, I might need some help to set up a repro case of what you're running into.

**Comment by ronanbel** [comment]
Hi Baldur, I've just tried with "current" nightly (e35fc4000dd0c5ac89b4ab85c03657d59d9df577e), and still the same.
It's easy to reproduce, just add an assert in any of your sample code after a call to Map()

		D3D11_MAPPED_SUBRESOURCE	oLockedRect;
call Map()
		if	( ( ((u8)oLockedRect.pData) & 31 ) != 0 )
			mpo_Toolbox->GetKernel()->FatalErrorS("Unaligned lock");

"asset" should not be triggered launched as stand-alone, and be triggered launched through Renderdoc.

BTW : I wouldn't be surprised (even if it's not stated in the documentation) that ConstantBuffer map returns 256 bytes aligned pointer since it seems to be the minimal alignment to offset ConstantBuffer, and that other resource map returns at least 64 bytes aligned pointer since it matches the size of a cache-line and enables memcpy (prefetch) optimizations for the subsequent driver's operations (and I wouldn't be surprised standard alignment beeing 4KB as it matches page size)

**Comment by baldurk** [comment]
Damn, yes you're right - when I tested before I must have gotten lucky that it ended up being 32-byte aligned, but I can see now why it's still not working.

The problem is I aligned the whole chunk of a buffer creation with all the data. But there's some additional descriptors and things (like D3D11_BUFFER_DESC) serialised before the actual data, so that can mess with the alignment. Internally I only align buffers to 16-bytes which is way back from when that was the minimum to be D3D11 complaint.

I don't want to break capture file backwards compatibility over this, so I'll probably just over-size the buffers and align that way.

**Comment by baldurk** [comment]
OK this should now align internally within a chunk so all the mapped pointers should really now satisfy 32-byte alignment. I ran my test many times now instead of just the once so let me know how it goes with tonight's nightly build :smile:.

**Comment by baldurk** [comment]
There was a bugfix for this that went in today, some serialised data wasn't accounting for the alignment padding which broke Unmap()s. So try with tonight's nightly instead.

**Comment by ronanbel** [comment]
Hi Baldur (thanks for your work, I was off this week-end). I've just tried with this version "2dde5ee5, 2015-04-26", and still get 32bytes unaligned pointers for texture locks.
I can (private) share an EXE if it can help you (I will send you an email later today to tell you where you can get it)

**Comment by baldurk** [comment]
That would be useful yes. The texture path is a bit more complicated than the buffer path, since there are a few places where the memory can be allocated (there's some lazy allocation to avoid allocating CPU-side memory for render targets that don't need it).

**Comment by baldurk** [comment]
Strangely I wasn't able to get the unaligned pointers in my tests, but looking back over it I noticed that the alignment calculation was flawed anyway, so it could easily be non-aligned. It would still be good to get your test EXE - if only so that I can incorporate it into my testing for future versions to make sure this doesn't regress.

In retrospect trying to overlay this larger alignment over the top of the existing 16-byte alignment I had has become rather messy. Originally I set that all up since it was all that the D3D11 API requires, but it means everything was very nicely tuned for 16-byte alignment. Perhaps for the next version (after v0.24 which is due Any Day Now&trade; once I can stabilise this) I will break file compatibility with previous captures and then I can make the internal alignment variable.

**Comment by ronanbel** [comment]
Hi Baldur, I sent you a mail (using your first name at your company address)(the one you gave me some monthes ago) a couple of days ago, maybe this email address is not valid anymore ?
can you contact me by mail please so I can give you the link to download my test EXE ?

**Comment by baldurk** [comment]
Oh right, sorry, if the last time we talked was when I was at Crytek then yes that email address is not valid anymore - I left Crytek in August last year. It also means I won't have your mail address to contact you directly. You can resend to my personal email which is the one I use for everything related to renderdoc, baldurk@baldurk.org.

**Comment by baldurk** [comment]
With 0.26 all buffers in logs should be natively 64-byte aligned, so this bug should now be fixed (if it wasn't before).
