### ISSUE TITLE
D3D_FEATURE_LEVEL_9_3 won't capture

### ISSUE THREAD

**Issue by nkindt** [baldurk/renderdoc#1332]
Could not find anything about this problem but if i have a feature level -

D3D_FEATURE_LEVEL fl[] =
{
	D3D_FEATURE_LEVEL_9_3,
	D3D_FEATURE_LEVEL_9_2,
	D3D_FEATURE_LEVEL_9_1
};

my app just shows a white screen all the time and RenderDoc 1.2 won't capture anything although it shows D3D11 as the active API. Adding D3D_FEATURE_LEVEL_11_0 as the first supported makes RenderDoc behave ok again (everything is rendered and captured correctly). Not sure if D3D_FEATURE_LEVEL_9_3 is not supported and if not a message would be appreciated (otherwise it looks like something is just wrong without any further info).

Thanks

p.s. Windows 10 x64/x32 via injection

**Comment by baldurk** [comment]
I don't know if it's the _only_ problem, but in my test the device was being removed because the text rendering for the overlay tried to use some features that aren't available in FL_9_x.

In that commit above I've added a legacy path to the overlay so it should work - it does work at least in a little triangle demo I ran, but I don't know if there will be other problems on more complicated samples. If you can give me a repro then I can look into it though I don't promise anything necessarily and I might decide not to support this if it becomes too much work.
