### ISSUE TITLE
New UI is very hard to use with Windows scaling

### ISSUE THREAD

**Issue by FallowWing** [baldurk/renderdoc#1335]
Windows with a 1080p display and 150% scaling makes the program extremely cumbersome, some options are off screen or barely visible, and the options popup is larger than my screen. https://imgur.com/a/d2DqEIC
150% scaling is pretty standard with modern high resolution laptops, some kind of option to change global app scaling and UI padding would be much appreciated.

Windows 10
Version v1.2 (built from 204724be)

**Comment by baldurk** [comment]
There are a couple of issues here. One is that on 1080p you ideally shouldn't be using any scaling since it's not high resolution. I don't necessarily assume a 1920x1080 size to work correctly but there is a certain minimum needed for the UI to function correctly.

The other is that the screenshots show 200% scaling. Looking around it seems to be a known Qt bug which currently doesn't support fractional scaling, so it's being rounded up to 200% which significantly reduces the available space, see [QTBUG-53022](https://bugreports.qt.io/browse/QTBUG-53022). The scaling and padding is correct for that value, so RenderDoc's UI is rendering correctly just for the wrong scale value.

As a result I don't think there's anything I can do about this at the moment, if I understand right. It needs a Qt fix at which point newer builds can use the newer Qt. You'd have this problem with any other Qt program which will scale up to 200%.

Until then I'd recommend changing your system scaling to 100% - even if this was fixed your effective resolution even with 150% scaling working correctly is 1280x720 which is probably about the minimum resolution I'd support, and even then it's not going to be comfortable.
