### ISSUE TITLE
glGetString does not return supported emulated OpenGL ES extensions when running an OpenGL ES application on desktop via an emulation library

### ISSUE THREAD

**Issue by rumblehhh** [baldurk/renderdoc#1336]
## Description

As far as I can tell when taking a RenderDoc of an OpenGL ES application on desktop using an OpenGL ES on top of OpenGL emulation library such as PVRVFrame calls to glGetString should return the set of extensions supported by the emulation library as well as those supported directly via RenderDoc.

Currently when taking a RenderDoc capture of an OpenGL ES application when using PVRVFrame as the emulation library I only see the following extensions are listed as supported:
	"GL_EXT_debug_tool", "GL_GREMEDY_frame_terminator" and "GL_GREMEDY_string_marker".
	
From what I can see in renderdoc/driver/gl/gl_driver.cpp: from line 1225 checks are being done to determine whether extensions supported via the emulation library for OpenGL ES are also supported on the host OpenGL driver. 
This won't generally happen as for many OpenGL extensions there will be an equivalent or more limited version of the extension supported on OpenGL ES for example GL_EXT_color_buffer_float for OpenGL ES vs. GL_ARB_color_buffer_float for OpenGL.

When running under emulation should glGetString simply return the list of extensions supported via the emulation library directly rather than attempting to find a mapping on the host?

Commit 73e1f7e770ac2dfae532c7c99c71e2d02e33b966 seems to be quite relevant here - the expected behaviour outlined above previously worked although I couldn't say which version of RenderDoc exactly.

## Repro steps

Download the PowerVR SDK from https://www.imgtec.com/download/windows-installer-powervr-tools-and-sdk/ (Only required for PVRVFrame libraries and a windows binary of the SDK example OpenGLESPostProcessing)
Copy the PVRVFrame libraries from PowerVR_Tools\PVRVFrame\Library\Windows_x86_64\ to a DLL-accessible directory prior to running the SDK applications - may be anywhere in the path, next to the executable, system default folders etc. 
Queue a frame 0 capture of PowerVR_SDK\SDK_2018_R2\bin\Windows_x86_64\Release\OpenGLESPostProcessing in RenderDoc.
Currently the application will fail due to unsupported GL_EXT_color_buffer_float extension. 

The application runs under PVRVFrame emulation without taking a capture using RenderDoc as PVRVFrame provides emulation for the appropriate OpenGL ES extensions.

## Environment

* RenderDoc build: Built from source commit 3b4f2837196b80da84bd341575dcf145ac7e0000.
* Operating System: Windows 10.
* API: OpenGL ES.

Some info taken from the diagnostic log:
Activating new GL context: Imagination Technologies (Host: ATI Technologies Inc.) / PVRVFrame 10.9 - None (Host : AMD Radeon HD 7700 Series) (SDK Build: MAIN@5319879) / OpenGL ES 3.2 (Host : 4.6.13547 Core Profile Context 25.20.15027.9004).

**Comment by baldurk** [comment]
I believe this is only happens on AMD, because the driver calls wglCreateLayerContext whereas on NV's driver this doesn't happen. When AMD's driver calls a wgl function this then starts to conflict between GLES and desktop GL hooks in RenderDoc and things rapidly break from there. The filtering you've identified is not trying to look behind any emulation but is just whitelisting the extensions returned by the GL implementation (whatever it is - emulator or real driver) according to what RenderDoc supports. I don't know or care about any emulator I only know about the GL implementation that I'm wrapping.

GLES-on-GL emulators are fragile with RenderDoc and in general I don't guarantee that I'll support them. The problem is I can either hook & capture the input calls or the output calls but not both - and if somehow both sides get hooked then things will break as above. When capturing the GLES side I do this by not hooking any calls that come out of GLES libraries at all on windows, however if they go via another DLL (like AMD's driver) this breaks down, and there's no good way to catch it.

I've added a workaround which will disable the WGL hooks completely as soon as EGL is loaded. It seems to work for now but as I say if this breaks again I may not be able to fix it.

While looking at this I discovered a couple of other issues that I've also fixed, though the captures don't replay correctly. I'm not sure if this is a bug in RenderDoc or not, as last time I looked at PVRVFrame it had bugs itself and didn't properly implement the GLES features RenderDoc needed to function.

**Comment by rumblehhh** [comment]
Aha right - Well I wasn't even close then in the end with what I thought the issue might have been! Thanks very much for providing a workaround!
Funnily enough I only switched to using this AMD card a couple of weeks ago so yeah this makes sense why I'd not seen any issues before.

I grabbed your latest commits and was able to successfully take a RenderDoc capture of the application I pointed you towards using a PVRVFrame version from our impending 19.1 release.

Thanks again for the quick fix/workaround!

Thanks,
James
