### ISSUE TITLE
No hooks on SwapBuffersWithDamageKHR？

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1341]
## Description
My Android app calls the SwapBuffersWithDamageKHR API, but the renderdoc lanuch black screen after my app. I added the SwapBuffersWithDamageKHR API hook in the renderdoc. No problem, is this API leaking?

## add this code
HOOK_EXPORT EGLBoolean EGLAPIENTRY eglSwapBuffersWithDamageKHR_renderdoc_hooked(EGLDisplay dpy, EGLSurface surface, EGLint *rects, EGLint n_rects)
{
    if (RenderDoc::Inst().IsReplayApp()) {
        if (EGL.SwapBuffersWithDamageKHR == NULL) {
            EGL.PopulateForReplay();
        }
        return EGL.SwapBuffersWithDamageKHR(dpy, surface, rects, n_rects);
    }
    SCOPED_LOCK(glLock);
    eglhook.driver.SetDriverType(RDCDriver::OpenGLES);
    if (!eglhook.driver.UsesVRFrameMarkers()) {
        GLWindowingData data;
        data.egl_dpy = dpy;
        data.egl_wnd = surface;
        data.egl_ctx = EGL.GetCurrentContext();
        eglhook.RefreshWindowParameters(data);
        eglhook.driver.SwapBuffers(surface);
    }
    return EGL.SwapBuffersWithDamageKHR(dpy, surface, rects, n_rects);
}
## Environment

* Operating System: android
* API:  OpenGLES 3.2

**Comment by baldurk** [comment]
You didn't mention what version of RenderDoc you're using but I assume you're running v1.2. Support for `EGL_EXT_swap_buffers_with_damage` and `EGL_KHR_swap_buffers_with_damage` has been added since then, so if you test a recent nightly build you should find it works better.

I'm closing this assuming that all you were looking for was support for those extensions.
