### ISSUE TITLE
Click right mouse to create a new floder in popup dialog. Prompt ntdll.pdb find ntdll.dll 

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1343]
## Description
I has capture a rdc file, when i select save capture. It's popup a save dialog.
I click right mouse to create a new floder in popup dialog, It's occur crash.

it prompt ntdll.pdb find ntdll.dll 's original source code.

**Comment by baldurk** [comment]
I'm sorry but I don't understand your description entirely.

It sounds like you're encountering a crash within the windows save dialog, if so that is not part of RenderDoc's code and the crash is likely caused by something else external. Check for any windows explorer plugins or add-ons you have enabled as they may be the culprit.

**Comment by mimijava** [comment]
Ok, Thanks for your reply.
