### ISSUE TITLE
Dependency on VK_EXT_vertex_attribute_divisor

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#1348]
## Description

On windows, the AMD driver doesn't support this extension, making it impossible to use renderdoc to debug issues. Is it possible to implement a fallback, or partially disable some things instead of disallowing debugging altogether?

## Environment

* RenderDoc build: v1.2
* Operating System: Windows 7
* API: Vulkan
* GPU: AMD RX 550
* Driver: 25.20.15031.1000 (latest at this date)

This confirms that this feature is only implemented in MESA for AMD, and is not available on windows:

https://vulkan.gpuinfo.org/listreports.php?extensionfeature=vertexAttributeInstanceRateDivisor

**Comment by baldurk** [comment]
Can you please explain directly what your problem is? You've come to the conclusion that RenderDoc depends on this extension which is incorrect. It does not have a dependency on `VK_EXT_vertex_attribute_divisor` or `vertexAttributeInstanceRateDivisor`, or any other Vulkan extension for that matter.

It certainly does work on drivers that don't expose those extensions, which means your issue must be something else. If you can explain in more detail what you are doing and what you see, how to reproduce your problem, I can investigate what is happening.

**Comment by ShabbyX** [comment]
Ok, thanks for confirming that renderdoc doesn't depend on this. Based on that, I did some more research and I believe I realize now what the issue is. We enable that feature in ANGLE which builds with the latest Vulkan repos. It's likely that renderdoc is picking an older version of Vulkan installed somewhere in the system where this feature doesn't exist.

That must be how I can take a capture with renderdoc, but cannot replay it. FYI, the issue was that replaying failed with a message saying that that feature is not available.

**Comment by baldurk** [comment]
RenderDoc uses the standard vulkan loader to query for available physical devices and does its best to match them up between capture and replay if they change. On the same system this should not happen though - if you're doing anything to modify the environment or loader's ICD enumeration logic such as setting the `VK_ICD_FILENAMES` variable then ensure that you do this globally and not just for capture.

**Comment by ShabbyX** [comment]
No, it's just that when the test runs, it picks up libvulkan.dll (or whatever the windows equivalent of libvulkan.so is) from the build directory of ANGLE. Renderdoc then uses the system libvulkan on replay.

Actually I see this in the [docs](https://renderdoc.org/docs/behind_scenes/vulkan_support.html#current-support):

> RenderDoc has support for Vulkan version 1.1, as well as a number of extensions, but it contains some caveats. In addition, not all replay features are currently supported, but this is being actively worked on.

Perhaps then the issue should be rephrased to "Please add support for `vertexAttributeInstanceRateDivisor`", as if I understand correctly, there are extensions you don't support in renderdoc and this could be one of them.

Note: the literal error I get from renderdoc is:

    Capture requires physical device feature `vertexAttributeInstanceRateDivisor` ... which is not supported.

**Comment by baldurk** [comment]
No again, RenderDoc fully supports VK_EXT_vertex_attribute_divisor and has for about a year. Any extensions which aren't supported are removed from the reported lists during capture so the application won't use them.

The error you are seeing is that during capture an extension & physical device feature were enabled, but on replay it was not available. This functionality is provided by the driver itself, as it's a device-level extension, so I don't think it's possible that using a different vulkan loader would make any difference unless it enumerated a different driver install. Unless your system vulkan library is so old that it doesn't support `VK_KHR_get_physcial_device_properties2`, but since you are running the latest AMD driver it will have installed a recent enough vulkan loader to the system.

There's an inconsistency in what you're describing. As you've shown in the original post the AMD windows drivers do not support the `vertexAttributeInstanceRateDivisor` feature - so how was it able to be enabled during capture in the first place?

**Comment by ShabbyX** [comment]
This is what angle does:

```
VkDeviceCreateInfo createInfo = {};
....

VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT divisorFeatures = {};
divisorFeatures.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_EXT;
divisorFeatures.vertexAttributeInstanceRateDivisor = true;

VkPhysicalDeviceFeatures2KHR enabledFeatures = {};
...
if (vkGetPhysicalDeviceProperties2KHR &&
    ExtensionFound(VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME, deviceExtensionNames))
{
    enabledFeatures.pNext = &divisorFeatures;
    ...
    createInfo.pNext = &enabledFeatures;
}
```

The `if` expression evaluates to `true`. In the particular test that I'm running, this feature is not actually used, though. The behavior I get from renderdoc is:

- Capture works fine, replay gives the error I gave you.
- If I comment out `enabledFeatures.pNext = &divisorFeatures;`, capture works fine, replay works fine.

**Comment by baldurk** [comment]
Where does your code call `vkGetPhysicalDeviceFeatures2KHR` to verify that the `VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT` struct you're chaining on there is actually valid? You enable `vertexAttributeInstanceRateDivisor` but don't seem to check that it's actually available, which seemingly it's not on your driver.

It looks like your code is invalid and you're enabling a feature unconditionally which is not actually supported by the physical device. I'd guess that it only fails in RenderDoc because I check these physical device features on replay and not on capture because I'm checking for capture compatibility and not for validity.

Are you running with the vulkan validation layers? They should catch this kind of error.

**Comment by ShabbyX** [comment]
Yeap, that was my thought too as I was looking at the code to write the previous comment. We do run with VVL, and apparently they don't catch this.

**Comment by ShabbyX** [comment]
Looks like you shouldn't be doing this extra validation in renderdoc. See [this comment](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/855#issuecomment-484163767).

**Comment by baldurk** [comment]
The comment does not say that RenderDoc shouldn't be checking this, you've added that interpretation and misrepresented what was said. The comment only says that enabling unsupported features isn't a validation error and has the defined behaviour of `VK_ERROR_FEATURE_NOT_PRESENT` being returned - which is a fair point, I didn't realise that was part of the spec required for drivers.

As mentioned before this is not validation, it is a compatibility check for the capture. I check these features individually so that the log output can inform the user which specific feature is required by the capture but is not supported on replay.
