### ISSUE TITLE
renderdoccmd on hikey960 (android P) failing 

### ISSUE THREAD

**Issue by seckalou** [baldurk/renderdoc#1349]
Hello,

Sorry if this has been ask/answered before, just couldn't find similar issues after browsing them all. 

I am trying to run renderdoccm on android target without the UI qrenderdoc:

`adb shell am start org.renderdoc.renderdoccmd.arm64/.Loader -e renderdoccmd "remoteserver"`

But the server would not stick around. Are there other steps to do before trying this? Starting server from the UI would work alright.

Thanks

**Comment by baldurk** [comment]
I'm unclear - are you saying that the remote server doesn't start properly when you select the replay context in the UI? Or that it only fails when you're manually running adb commands?

If it's the latter then you're not doing anything that I support. I can't realistically help with and diagnose problems you run into when doing things outside the scope of how you're intended to use RenderDoc.

Why do you want to run these commands manually instead of using the UI as intended which will handle all this automatically for you?

**Comment by seckalou** [comment]
> I'm unclear - are you saying that the remote server doesn't start properly when you select the replay context in the UI? Or that it only fails when you're manually running adb commands?

I am using adb. 

> Why do you want to run these commands manually instead of using the UI as intended which will handle all this automatically for you?

This is to be able to automate captures on host side (e.g. be able to batch a serie of captures with scripts etc.). I however just came across the python API that might allow that (?). (sorry relatively new here)

**Comment by baldurk** [comment]
That python API does provide access to enumerating remote servers on given hostnames and launching remote programs, then connecting and triggering captures.

The problem you'll run into is that at the moment the android-specific enumeration of devices is not formally part of that API and is considered internal. It's technically still exposed but I don't know if the functions bind correctly to python as it's only intended to be called from C++.

I can think about whether the android access should be promoted to public, though I'll admit I'm kind of skeptical. Android is an incredibly fragile and unreliable platform so I'm worried about exposing too much of it in the API. Perhaps there is a way to expose it publicly though in future.

For now honestly your best bet might be to run your scripts that launch the capture on Android via `qrenderdoc --python`, and take advantage of the UI automatically doing all the android initialisation & populate for you. You can iterate through the [RemoteHosts](https://renderdoc.org/docs/python_api/qrenderdoc/config.html#remote-host) and launch the one you want, then fetch the hostname property and use the more direct python API for connecting to the remote server and launching programs from there (none of which is Android specific after that point).

Otherwise you might find some way to fix the adb commands. It should be feasible to 100% replicate the adb commands that RenderDoc runs, but given how flakey adb is I wouldn't be surprised if there was a very particular set of steps you had to follow. I can't really help with that - but bear in mind you have to run the server and forward all ports as expected.

btw as a side note, you're a braver person than I for trying to do automated captures on android! I have automated testing on every other platform but I wouldn't even consider it on Android since that seems like a recipe for disaster.

**Comment by seckalou** [comment]
Thanks- Yeah adb (maybe not only it) across time and OEM is a nightmare. Will give the python+ui a go. Thanks again

**Comment by Ocasio-J** [comment]
>  You can iterate through the RemoteHosts and launch the one you want, ...

Sorry, how exactly can I iterate the RemoteHosts? I can't seem to find the API that allows this.
I'm also trying to find a way to replay a capture on Android through a script.

**Comment by baldurk** [comment]
It seems like the documentation isn't being generated for member functions for some reason, I'll look into that. On v1.4 for fetching the remote hosts available in the UI check out `help(pyrenderdoc.Config().RemoteHostCount)` and `help(pyrenderdoc.Config().GetRemoteHost)`. Note though that scripting on Android remains unsupported due to the inherent instability and unreliability of the platform.
