### ISSUE TITLE
Build issues 

### ISSUE THREAD

**Issue by seckalou** [baldurk/renderdoc#1350]
Hello,

Anyone came across this issue while building? (Building on Ubuntu 16.04, make 4.1 and cmake 2.8.12.2):

`renderdoc/CMakeFiles/renderdoc.dir/build.make:55: *** target pattern contains no '%'.  Stop.`

Was trying to hack my way around the build.make by removing colons in target that seem to confuse make but then thought I should not as these are generated in the first place :/

Thanks

**Comment by baldurk** [comment]
I downloaded 2.8.12.2 and it seems like it's not properly translating the `$<TARGET_FILE:include-bin>` generator expression as the dependency of include-bin resources. I think this probably broke in 73c315961585de9e8c9c82394c4d0bd5cc2d1fa7 and since I'm not testing on 2.8.12 anywhere it broke. I've put in a simple fix that seems to work, though I'm not sure it makes sense to spend much effort supporting 2.8.12 at this point.

From what I can tell the [mainline Ubuntu 16.04 cmake package](https://packages.ubuntu.com/xenial/cmake) is 3.5.1 - is there any reason you are using 2.8.12.2? It will probably work for now but might break again in future and it won't be caught and may not be fixed.

**Comment by seckalou** [comment]
For cmake I am using in-house builds not ubuntu's package (created a newer build though). All working now :+1:  Just thought it might be useful to someone to mention I had few trouble with qt and ended up ditching the system one and installed from official qt installer :) . 
Thanks
