### ISSUE TITLE
Resizing panes on left monitor break when right is primary

### ISSUE THREAD

**Issue by MrZoner** [baldurk/renderdoc#1354]
## Description

The UI doesn't quite work right on secondary monitors when the coordinate system is negative for them.

## Repro steps

Have two monitors.  Have the monitor on the right be the windows primary.  When renderdoc is displayed on the left monitor (which has negative X coordinates in windows UI terms), when you drag the control to resize the EventBrowser to make it wider, it snaps to a position near the right edge of the display.  Moving renderdoc to the other monitor, and the resize works as expected.

## Environment

* RenderDoc build: e.g. v1.3 nightly from Apr 04 2019
* Operating System: Windows 10
* API: D3D11/D3D12, 
* GPU : Radeon VII, latest gpu drivers (2019.4.2)

**Comment by baldurk** [comment]
I can't reproduce this, but I'm testing on windows 7 so maybe it's a windows 10 exclusive bug. I'll need to see if I can connect up multiple monitors to my win10 test box.

Could you record a video/screencast showing the problem?

**Comment by MrZoner** [comment]
I have found 2 more requirements:

- An empty renderdoc session won't exhibit the UI quirk.  There must be a capture being analyzed (so there are events showing in the EventBrowser pane).
- DPI scaling of 150%.  When it is changed to 100% the UI is behaving normally.

**Comment by baldurk** [comment]
Does it happen with 200% DPI scaling? It came up recently that Qt doesn't properly support non-integer DPI scaling so there might be bugs there that I can't fix, I'll try to test and see if it's some calculation on my side that's going wrong.

**Comment by baldurk** [comment]
I was able to set something up to repro this. I think it's actually independent of the scale factor, but I can't verify since windows 10 doesn't let me set a DPI scaling of 200% on my 1080p monitors.

I stepped through the Qt code and it's a Qt bug, the negative pointer position breaks under DPI remapping between actual and logical co-ordinates it seems. You might be able to report this to Qt but I would be surprised if it ever gets fixed unfortunately.
