### ISSUE TITLE
Bug: Buffer content viewer can open multiple identical tabs

### ISSUE THREAD

**Issue by bioglaze** [baldurk/renderdoc#1377]
## Description

I was viewing index buffer contents (Vertex Input -> Buffers -> Index -> Go) and noticed that if a tab is already open for a buffer, pressing "Go" doesn't focus on the already opened tab, instead it opens a new tab with the same contents. In my workflow I ended up opening many identical tabs by accident and had to close them one by one.

## Repro steps
See Description.

## Environment

* RenderDoc build: v1.4
* Operating System: Windows 10
* API: Vulkan

**Comment by baldurk** [comment]
This is deliberate, since it can be useful to do so and may be critical in some cases - consider having the same buffer bound with different ranges to index buffer and vertex buffers. Or on other APIs where that's not common you could still have the same buffer bound with different offsets at different draws, and you want to compare side by side. If the UI locked you to only ever have one view of a buffer open it would be really annoying to try to switch back and forth between them.

In theory it could do something really fancy where it tries to find an existing buffer view with the exact same configuration and focus it instead of opening a new one, but this seems fragile and of limited use and might get in the way in some cases where you want to open two views then change the formatting string of one to be able to compare side-by-side again. Being able to open many identical tabs is kind of a "enough rope to hang yourself with" situation.
