### ISSUE TITLE
The first launch of RenderDoc after an update still show "Update available"

### ISSUE THREAD

**Issue by ScrappyCocco** [baldurk/renderdoc#1379]
## Description

Open RenderDoc and get the "New Version Available" notification, then close it.
Aftern an update, launching RenderDoc still show "Update available" label on the top bar.
Clicking "Check for updates" make it disappear forever.

## Repro steps

* Use Renderdoc 1.3 and get the "New Version Available" notification
* Close it and install Renderdoc 1.4
* Open Renderdoc 1.4 and it still says "New Version Available" in the top bar

## Environment

* RenderDoc build: 1.4
* Operating System: Windows 10

**Comment by baldurk** [comment]
Just to clarify - in the second step do you mean that you installed RenderDoc v1.4 manually instead of using the built-in autoupdater?

If so then yes this was a bug - see #1368 - where RenderDoc did not expect to be updated behind its back, and kept the cached update notification. As you found, checking for updates refreshes the state and in future versions it will invalidate the cache when the version changes.

**Comment by ScrappyCocco** [comment]
Yeah i did it manually
So it's already known, thanks for your reply
