### ISSUE TITLE
Vulkan: Support for Capture without vkQueuePresentKHR

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#1386]
## Description

When there is no window, or when there is a window but no `vkQueuePresentKHR` call is made, renderdoc discards the capture as if nothing ran.

This is a request to add support for capturing and replaying whatever was `vkQueueSubmit`ed to the GPU even if there is no terminating `vkQueuePresentKHR`.

I noticed this in two cases:

- A window is made, some work is done on a swapchain image and the results read back on the CPU. This involved `vkQueueSubmit` and `vkQueueWaitIdle`, but not `vkQueuePresentKHR`. Renderdoc didn't create a capture to be replayed. _I worked around this by doing an unnecessary present)_
- No window is made, all work is done on off-screen `VkImage`s. Renderdoc didn't create a capture. There's no workaround (unless a window is created for no reason).

## Repro steps

Record a command buffer, `vkQueueSubmit` it and terminate the application without presenting.

## Environment

* RenderDoc build: 26d823905
* Operating System: Linux
* API: Vulkan
* GPU: Intel, Mesa 18.0.3

**Comment by baldurk** [comment]
Just to clarify: You say that RenderDoc 'discards' the capture when there's no window, but rather it's just not possible to make a capture using the default process since it is indeed default based around delimiting frames by window presents.

For headless programs that don't have a those default frame boundaries you can use the [in-application API](https://renderdoc.org/docs/in_application_api.html) which RenderDoc provides. This is also useful even when your application does have a window, if some work outside of a normal frame e.g. to cache or bake some results.

The API allows you to start and stop the capture at a time of your choosing to define the boundaries of the 'frame'. When there's only one graphics device present you can call `StartFrameCapture(NULL, NULL)` and `EndFrameCapture(NULL, NULL)`.

**Comment by ShabbyX** [comment]
> Just to clarify: You say that RenderDoc 'discards' the capture when there's no window, but rather it's just not possible to make a capture using the default process since it is indeed default based around delimiting frames by window presents.

Yes, I guessed this (as the captured frames are clearly separated at present calls). This issue is a request to actually add support for such a use case. I suspect this issue affects situations like this too:

- Render, present, repeat
- Render, terminate

With the last bit of rendering not getting captured by RenderDoc. The issue is likely not too difficult to resolve. Instead of "saving" each frame when "present" is seen, RenderDoc can do it when either "present" is seen or the device is destroyed. That would automatically support all these use cases.

**Comment by baldurk** [comment]
It feels like there's still a miscommunication or misunderstanding here. RenderDoc does not capture every frame in the application when a present is seen, it only captures specific frames when prompted - either by a keypress, a trigger from the UI either immediately or delayed - using presents to mark the boundaries. Alternatively the API linked previously can be used to start and stop a capture at any time.

If you don't have the delimiter of presents to a window then I don't think there's a good way to know how to subdivide the work and determine which subsets should be captured as a 'frame' or not. That's why I recommend in this case that you use the API to determine exactly what should be included in what you want to capture.

If I understand your suggestion to be treating each vkQueueSubmit as an individual 'frame' in this case that is not going to be desirable in many cases since there are typically multiple submits in one 'unit' of work. Though again if an application isn't presenting to a window it's very hard to reason about what is a meaningful unit of work at all, hence why it's better to leave it up to the user to define.

Yes you would also get into difficulty if you triggered a frame capture relying on the implicit present boundaries, and then destroyed the device mid-way through the frame. If a user wanted to capture that final frame then they would also be best using the API as well.

**Comment by ShabbyX** [comment]
First, I am now capturing through the API just fine.

My suggestion wasn't to treat each `vkQueueSubmit` as an individual frame though. It was to threat `vkDestoryDevice` as a frame delimiter too. The work is still subdivided into frames by present calls, except the trailing work before a device destory is captured into one final frame. Does that make sense?

**Comment by baldurk** [comment]
If you don't have any present calls in the frame, as described in your original post, then treating `vkDestroyDevice` as a frame delimiter to end any final frame capture won't help since there's nothing to start the capture in the first place.

If you're talking about a case where you do have window presents then it's different to what you originally described. It seems like you're asking about a hypothetical case and not something you've actually run into.

It's a pretty obscure edge case and it can already be solved by the user using the API to define the capture for the final frame before destroying their device.

**Comment by ShabbyX** [comment]
Let's focus on the case without window. Wouldn't selecting `Queue Capture` with `Frame 0` already start the capture right at the beginning? `vkDestroyDevice` would end that and voila, one frame with all the commands!

**Comment by baldurk** [comment]
That would capture the entire application's work for however long it runs which is definitely not desired.

Queuing a capture of frame 0 is undefined when the application has no frames. As with many other examples you could construct where there's no easily delimited frame, it is easier and more reliable to have the user define what their workload boundary is rather than trying to automatically guess it and exposing sharp edges and pitfalls.

It sounds like you want to abuse RenderDoc to capture the work of an entire application. That is not its purpose nor an intended use, though of course if you really want to you can use the API to capture as much as you want. This is also far off-topic from the original question which was how to capture work when there are no window present operations - to which the simple answer is that you can use the RenderDoc API to define the bounds and you've already said that works well for you.

**Comment by ShabbyX** [comment]
I would be fine if your answer is "I don't feel like doing it", but your reasoning is not exactly great.

> That would capture the entire application's work for however long it runs which is definitely not desired.

Not _definitely_. I did just ask for it, so there is desire by _some_.

I will be keeping the commit that adds renderdoc API capture lying around, but it would have been far more convenient if the capture just worked in renderdoc itself.

> Queuing a capture of frame 0 is undefined when the application has no frames.

Undefined by who? It can be very well defined if you want it. To me, "Queuing a capture from frame 0" would mean capture whatever comes after `vkCreateDevice`.

> It sounds like you want to abuse RenderDoc to capture the work of an entire application.

If the application is a conformance test that runs for a short time, why would capturing the entire application be an abuse?

> That is not its purpose nor an intended use, though of course if you really want to you can use the API to capture as much as you want.

I think you just answered yourself here. Also, I didn't notice anywhere RenderDoc saying it's intended for capturing window-based workloads only. In fact, the task is already doable with the API, it's just the UI that's missing a feature.

> This is also far off-topic from the original question which was how to capture work when there are no window present operations.

Nope, the original issue was "a request to add support for capturing and replaying whatever was `vkQueueSubmited` to the GPU even if there is no terminating `vkQueuePresentKHR`".

**Comment by ShabbyX** [comment]
You could end this discussion with "I don't want to do it, do it yourself if you really care" which I think is more reasonable.

**Comment by courtney-g** [comment]
I'm trying to debug some conformance tests. These tests don't generate traditional frames and are pretty short. Would be really nice if RenderDoc could capture everything from CreateIntance or CreateDevice to the corresponding Destroy.

**Comment by baldurk** [comment]
Capture all of an entire application's work from start to finish is explicitly not a goal of RenderDoc.

As mentioned above if you want to capture a section of work that's not delimited by frame boundaries you can use the [RenderDoc API](https://renderdoc.org/docs/in_application_api.html) to start and stop the capture at any time. I know at least that the vulkan conformance tests do exactly that.

Please don't comment on closed issues, if there is still a bug or a new request then you can open a new issue.
