### ISSUE TITLE
Allow Activity selection for Android

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1387]
## Description

We would like a feature that allows us to select the starter Activity when we launch an Android application to capture. This would be useful for us because it is quite common for some Activities to run on a process different from the default MAIN Activity and therefore they cannot be captured with RenderDoc.

There should be a list of the selectable Activities (which can be launched by other applications) but it seems to me that we can't obtain every Activity from the APK with an adb command.  
I have tried `adb shell dumpsys package [package-name]` with some applications but only those Activities are listed which has an `<intent-filter>`. (Those Activities which have the `android:exported` attribute set to "true" are not included even though they can be launched by other applications too.)

**Comment by baldurk** [comment]
That commit adds an extra browse step when selecting android applications to select the activity within each package. An entry `#DefaultActivity` is given for users that don't care about activities and just want to launch the package as normal.

If your activity isn't listed due to the implementation details of `adb shell dumpsys` then I suggest making a small change to your application to list a dummy intent-filter for the activity you want to launch, so that it is listed.
