### ISSUE TITLE
Capture on Linux with NVIDIA driver fails due to calling wrong glGetString

### ISSUE THREAD

**Issue by bsalomon** [baldurk/renderdoc#1389]
## Description

Capture does not work for NVIDIA driver on Linux with context created via glXCreateContextAttribsARB.

## Repro steps

Build Skia's viewer application: https://skia.org/user/sample/viewer for Linux. Attempt to capture an OpenGL trace using either rendererdoccmd or qrenderdoc. The application crashes before the window is displayed.

The problem is that GLXHooked calls GL.PopulateWithCallback prior to an OpenGL context being created. The NVIDIA driver will return a glGetString that seems to always return nullptr. Later when renderdoc tries to determine the OpenGL version in GetContextVersion() this null string causes a crash. I verified the null return behavior by modifying the viewer app itself. The following returns nullptr:

`glGetString(GL_VERSION);`

However, the following:

```
using GetString = const GLubyte*(GLenum);
auto getstring = (GetString*)(glXGetProcAddress((const GLubyte*)"glGetString"));
getstring(GL_VERSION);

```
returns "3.2.0 NVIDIA 390.87"

The fact that the even the statically linked glGetString() seems odd to me.

If the GL procs are requeried after a GL context is created then the correct glGetString gets populated into the global GL instance of GLDispatchTable then capturing works correctly.

Here is a hacky fix that works: 
https://github.com/bsalomon/renderdoc/commit/0e6be25d1dab536080bf4c8f8254d5427ec06daf
The switch to glXGetProcAddressARB from glXGetProcAddress is irrelevant has no effect.

My understanding is that each GL entry points are allowed to vary from context to context, at least for extensions. So perhaps a more correct fix is to store a GLDispatchTable for
each context that gets created.

## Environment

* RenderDoc build: e.g. v1.4, and latest nightly build.
* Operating System: Linux
* API: e.g. OpenGL

NVIDIA driver: 390.87
Linux distro: Debian

The application uses glxCreateContextAttribsARB to create it's context. Code here:
https://cs.chromium.org/chromium/src/third_party/skia/tools/sk_app/unix/GLWindowContext_unix.cpp?q=GLWindowContext_unix.c+file:%5Esrc/third_party/skia/+package:%5Echromium$&g=0&l=73

**Comment by baldurk** [comment]
I can't reproduce this - I built the skia viewer but I'm able to capture it successfully both with v1.4 and from a locally build of latest v1.x, I don't get any crashes.

GL's GetProcAddress functions are one layer in the onion of horribleness that GL is, but in particular here there's a subtle distinction - `wglGetProcAddress` on windows is allowed to vary function pointers by context, and in particular there's the infamous requirement that you first make a context before you can properly query for extension function pointers (and anything past GL 1.4). `glXGetProcAddress` is explicitly spec'd as having function pointers be context-independent both in [the original extension spec](https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_get_proc_address.txt) and in [the GLX spec](https://www.khronos.org/registry/OpenGL/specs/gl/glx1.4.pdf):

> GL function pointers returned by glXGetProcAddressARB are independent of the currently bound context and may be used by any context which supports the extension.

In particular this means GL functions are queryable with no context bound (again unlike wgl - but like egl). The [glXGetProcAddressNeverReturnsNULL](https://dri.freedesktop.org/wiki/glXGetProcAddressNeverReturnsNULL/) page addresses this:

> Many GLX extension functions are called before the application has a context bound (e.g., glXMakeCurrentReadSGI). In order for pointers returned by glXGetProcAddress to be context-dependent the application would have to have a context to call glXGetProcAddress. The chicken-and-egg problem here should be obvious. 

The requirement for this dispatch is why mesa returns a valid non-NULL function pointer even for invalid functions, or extensions it doesn't support, since the idea is you can query for any function but it's only valid to call it when a context is active that provides that function.

Something else must be going on here to explain what you're seeing - can you give more information such as the callstack of where that glGetString() returns NULL (there are a couple of paths it could take) and verify that there is definitely a context bound at that point.

For reference I'm testing on Ubuntu but a newer driver (418.56), so you could try updating to a newer driver to see if that makes a difference.

**Comment by bsalomon** [comment]
I'm at home now on a Ubuntu 19.04 with NVIDIA driver 390.116 and also can't
reproduce it. So it probably is something about my system in my office.
I'll see if I can get some more info tomorrow.

**Comment by bsalomon** [comment]
I figured out what's going on. On the machine that I'm having this issue with I'm building the viewer app so that it can optionally run through the ANGLE GLES->GL library. This means that both the ANGLE and the normal GL glGetStrings are present. The ANGLE version is being selected, which returns nullptr since no ANGLE context has been created. Calling glXGetProcAddress ensures that the native glGetString is used. Sorry for the noise!
