### ISSUE TITLE
invoking `run_tests.py` exception exit

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1391]
## Description
when i invoking 'run_tests.py' with the cmd as below.

python /path/to/util/test/run_tests.py --pyrenderdoc /path/to/renderdoc/x64/Development/pymodules --renderdoc /path/to/renderdoc/x64/Development

program exit  when execute import renderdoc as rd. It's popup a window's dialog show "python is stopped."

I guess it's maybe load native library 'renderdoc' error. But it can't debuggable, and without any log. 

How i can find what's error happened?

**Comment by baldurk** [comment]
What version of python are you running? it must precisely match the version of python you compiled the renderdoc python module against - by default one windows the one in the repository is 3.6.

Otherwise I'll need more information to understand what the problem is beyond just knowing that it crashed. If you run python through a debugger or attach it before it executes that line, what is actually crashing and what is the callstack where it crashes?

**Comment by mimijava** [comment]
how to compile python module?

**Comment by baldurk** [comment]
On windows the python module is built automatically as part of the build process. You must have compiled it for `import renderdoc` to crash, since otherwise python would just throw a `ModuleNotFoundError` exception and the scripts would catch it and print a message that the module couldn't be found.
