### ISSUE TITLE
Possible to save images with more control

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1400]
## Description

Here's a feature request. Would it be possible/feasible to save images with the currently set up filters? For instance, an image that has been set to not gamma correct, or only showing two channels out of four, or even being decoded via a custom shader (say decoded GBuffer normals), basically any setup that has been applied for visualization. I saw that we can already export overlays which is neat, would it be possible to export the whole thing together? Such that attaching to a bug report or similar would have useful information on top.

Thanks for your hard work!

## Environment

* RenderDoc build: 1.4
* Operating System: Windows 10
* API: All

**Comment by baldurk** [comment]
I don't want to feature creep the texture saving options. The only intention is to be able to save the texture data out as faithfully as possible, and if you want any further processing then that can be done in external programs with the right source data. Otherwise there's a lot of scope for edits/changes and ambiguity on how to handle processing images together with different format precisions.

FYI if you have a custom visualisation shader configured then that's what is saved.
