### ISSUE TITLE
Need help capturing the render process of a web page

### ISSUE THREAD

**Issue by LeLocTai** [baldurk/renderdoc#1404]
I was looking for a way to inspect how web page are rendered. I tried capturing Chrome using direction from #810 , but while the Connection status is shown as Established, the API is shown as OpenGLES (Not Presenting). As I understand, this mean I need to modify Chrome code to add markers to make this work. If that the case, I don't think I'm ready to do this atm.

I then tried Firefox, and while everything worked straightforwardly, the resulting capture does not contain the web page rendering process at all, but only show the already-rendered web page as a texture.

Any help would be appreciated.

## Environment

* RenderDoc build: v1.4
* Operating System: Windows 10
* API: OpenGLES (I think)
* GPU: Intel UHD Graphic 630

**Comment by baldurk** [comment]
I don't provide any support for capturing from web browsers unless you're a browser dev yourself. Partly because it's a very complex program with a lot of internal complexities and in Chrome's case ANGLE dependencies that can break without it being a RenderDoc bug. Also partly because recently there have been notable cases of people using RenderDoc to extract copyrighted assets from webgl which is not endorsed or supported.

RenderDoc is intended for capturing your own programs and currently webgl is not officially supported.

**Comment by ezhikus** [comment]
Just use workaround, suggested by Chromium at this page: https://chromium.googlesource.com/angle/angle/+/master/doc/DebuggingTips.md
