### ISSUE TITLE
ARB_gl_spirv program not captured properly on Intel HD Graphics 620

### ISSUE THREAD

**Issue by TheSpydog** [baldurk/renderdoc#1405]
## Description

On my Surface Laptop with an Intel HD Graphics 620 chip, RenderDoc seems to have trouble capturing programs that use GL_ARB_gl_spirv. Even though the programs appear to render without issue, when I capture a frame and inspect it, I am greeted with the error: `Incorrect API Use | High | … | No vertex shader bound at draw!` and no output is shown for any non-glClear call in the Texture View.

I suspect this is a bug in RenderDoc because if I try capturing a frame from the same app on my desktop computer (Win10, NVIDIA GeForce GTX 1060), it works as expected with no errors. Also, if I run the same program on my laptop using GLSL instead of SPIRV, capturing still works as intended.

## Repro steps

[pugtest.zip](https://github.com/baldurk/renderdoc/files/3254798/pugtest.zip)

1. Use a computer with an Intel HD Graphics 620 chip. (Might be the same on other Intel cards, haven't been able to test.)
2. Extract the attached zip and run `pugtest.exe`.
3. See that it renders a picture of a silly dog.
4. Close the app and re-launch it from RenderDoc with the environment variable: "FNA_OPENGL_FORCE_CORE_PROFILE=1".
5. While the program is running, capture a frame.
6. Open the capture.
7. Notice the errors and lack of visual output.

## Environment

* RenderDoc build: v1.4
* Operating System: Windows 10
* API: OpenGL
* GPU: Intel HD Graphics 620
* GL Driver Version: 4.6.0 - Build 26.20.100.6890

**Comment by baldurk** [comment]
There were a few places where I was relying on driver reflection that is not required for ARB_gl_spirv, and/or calling functions that I shouldn't have been. I think it's all tightened up as of that commit.

FWIW in this case part of the reason it was failing looks to be a driver bug with Intel which muddied the waters a bit. I've reported that to them and hopefully they can get it fixed - you might still find that not everything works correctly due to this bug (e.g. the texture viewer overlays fail for me on Intel).
