### ISSUE TITLE
OpenGL incorrect API use error "No index buffer bound at indexed draw!"

### ISSUE THREAD

**Issue by FredGithub** [baldurk/renderdoc#1409]
## Description

Similar to #452, I'm getting the error "No index buffer bound at indexed draw!" with a very simple test application that only draws a quad from a VAO. This happens with the latest release (v1.4) and with a build of the lastest source code (f31f9e4).

I tried diving in the source code since this issue makes RenderDoc unusable and since there are literally 0 hits when googling this appart from #452. I noticed that this error comes because `glGetIntegerv` of `GL_ELEMENT_ARRAY_BUFFER_BINDING` returns 0. I tried doing the same call within the app code after `glBindVertexArray`, and it works fine, which makes me unsure whether this is a driver bug.

Note that the issue is not present when building RenderDoc in Development mode.

Do you have any hint on what to look for?

## Repro steps

The app is the simplest indexed draw example I could find, taken from [here](https://learnopengl.com/code_viewer_gh.php?code=src/1.getting_started/2.2.hello_triangle_indexed/hello_triangle_indexed.cpp).

Here is a zip with with everything included: [renderdoctest.zip](https://github.com/baldurk/renderdoc/files/3269570/renderdoctest.zip)

Unzip and run the following commands:
```
mkdir build
cd build
cmake .. -A x64
```

Capture file: [capture.zip](https://github.com/baldurk/renderdoc/files/3269586/capture.zip)

## Environment

* RenderDoc build: v1.4 and HEAD
* Operating System: Windows 10
* API: OpenGL
* GPU: GeForce GTX 1060 6GB/PCIe/SSE2 / 4.6.0 NVIDIA 430.86

**Comment by baldurk** [comment]
Yes this is definitely a driver bug. You can see it in the demo program if you make some changes:

```
    // remember: do NOT unbind the EBO while a VAO is active as the bound element buffer object IS stored in the VAO; keep the EBO bound.
    //glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
    
    typedef void (APIENTRYP PFNGLENABLEVERTEXARRAYATTRIBEXTPROC) (GLuint vaobj, GLuint index);
    PFNGLENABLEVERTEXARRAYATTRIBEXTPROC glEnableVertexArrayAttribEXT;
    
    typedef void* (APIENTRYP PFNWGLGETPROCADDRESSPROC_PRIVATE)(const char*);
    static PFNWGLGETPROCADDRESSPROC_PRIVATE gpa =
      (PFNWGLGETPROCADDRESSPROC_PRIVATE)GetProcAddress(LoadLibraryA("opengl32.dll"), "wglGetProcAddress");

    glEnableVertexArrayAttribEXT = (PFNGLENABLEVERTEXARRAYATTRIBEXTPROC)gpa("glEnableVertexArrayAttribEXT");

    GLint getEBO = 0;
    glGetIntegerv(GL_ELEMENT_ARRAY_BUFFER_BINDING, &getEBO);
    
    glBindVertexArray(0); 
    glEnableVertexArrayAttribEXT(VAO, 0);

    getEBO = 0;
    glBindVertexArray(VAO); 
    glGetIntegerv(GL_ELEMENT_ARRAY_BUFFER_BINDING, &getEBO);
```

With this I get the first getEBO returning the right buffer, the second returning 0. This isn't just a bug of the query it seems, if you let it run then it will crash trying to access the indices via raw CPU pointer instead of with an index buffer.

It seems to be particular to calling EXT_direct_state_access functions on a VAO with the VAO unbound. If you comment out the `glBindVertexArray(0);` just above the `glEnableVertexArrayAttribEXT(VAO, 0);` it works fine.

It also fixes it to enable `GL_DEBUG_OUTPUT_SYNCHRONOUS` but only if you have a debug context - that's why development RenderDoc builds worked because they create debug contexts, where release builds don't.

None of this happens on AMD, it works fine there.

I'll see if there's a way to report this to NV but in the meantime I can probably find a workaround. This isn't the first time that I've had problems with NV's EXT_dsa functions and they're all emulatable at the expensive of pushing and popping bindings. It might be better just to always emulate EXT_dsa rather than rely on potentially buggy implementations.

**Comment by baldurk** [comment]
In testing against your demo program & capture that commit fixes it for me, I can't guarantee it will fix all bugs that might show up in this area :(.

**Comment by FredGithub** [comment]
Seems like it fixed it for me too. Thank you!
