### ISSUE TITLE
Save all textures?

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#1414]

**Comment by baldurk** [comment]
Can you explain what you're trying to solve and why this would be useful? I can't see a reason why you'd want to save all textures to disk to debug something. If you explain your full use-case from the start then it's easier to see if maybe there is a better solution to your problem that's more direct.

**Comment by ToppestOfDogs** [comment]
Renderdoc is the only reliable way of dumping textures from PS3/360 games that I've found. There's many projects that involve dumping textures from games to archive them for various purposes.
You can learn more about texture archival at https://www.textures-resource.com/ if you're interested. You'll notice that PS3 and 360 have very few games on there compared to Nintendo's consoles, the reason is that Nintendo consoles usually end up with much more robust emulators and decompiling tools, right now the only way to work with PS3 and 360 games is with renderdoc, saving one texture at a time.

**Comment by baldurk** [comment]
RenderDoc is intended only to be used for debugging your own programs. Extracting copyrighted assets from commercial games is absolutely not supported or endorsed.
