### ISSUE TITLE
Cannot open Qt 5 based applicatoin

### ISSUE THREAD

**Issue by fu5ha** [baldurk/renderdoc#1417]
## Description

I'm attempting to launch [appleseed](https://github.com/appleseedhq/appleseed) to debug an OpenGL rendering problem. I am unable to do so, it seems to fail before being able to inject.

![fail2](https://user-images.githubusercontent.com/887711/59471876-5ee1c580-8df1-11e9-8623-d17d4c8edab6.PNG)
![fail3](https://user-images.githubusercontent.com/887711/59471886-64d7a680-8df1-11e9-9645-cd4f3052f692.PNG)

The app needs a few environment variables to be set to launch. This works properly in Visual Studio as well as from the command line. I enter these same env variables to launch from RenderDoc (I've checked multiple times that they match exactly)

![fail1](https://user-images.githubusercontent.com/887711/59471966-b54f0400-8df1-11e9-8a0d-e7eb57a3b08b.PNG)

Also, if I am in a cmd prompt with those environment vars set, I am able to do `.../renderdoccmd.exe capture .../appleseed.studio.exe` and it launches, though I can't tell if it captured anything or not.

## Environment

* RenderDoc build: v1.4
* Operating System: Windows 10
* API: OpenGL 3.3
* Nvidia 430.64 drivers, 980ti gpu

**Comment by baldurk** [comment]
I couldn't reproduce this on a downloaded build of the program. It took a while but I was eventually able to build from source, and I was maybe able to reproduce the problem.

For me if I configure it [like the wiki suggests](https://github.com/appleseedhq/appleseed/wiki/Building-appleseed-on-Windows#configuring-the-visual-studio-solution) then it runs correctly. When I configure it like you do, with PATH configured to append to the existing variable, then it fails with an error that indicates an incompatible version of Qt5Widgets.dll has been found.

![image](https://user-images.githubusercontent.com/661798/59518409-7c7c6100-8ebd-11e9-950c-627ad78ec591.png)

Which makes sense since I have other programs in my PATH which use Qt, so their version will be found first but won't be compatible with the 5.12 I used to build.

Why do you have the PATH variable configured to append instead of set (or at least prepend)? When you are launching the program successfully in a cmd prompt are you actually appending the PATH variable or are you setting it?
It also works if I prepend instead of append, so the specific needed Qt version is found first.

**Comment by fu5ha** [comment]
Wow, that was actually one of the first things I tried, but then it didn't help, and then I realized another mistake that I made and fixed that, and didn't think to go back and try set/prepend again. I just tried set and it works. Thank you so much for investigating!
