### ISSUE TITLE
scripting captures

### ISSUE THREAD

**Issue by crogersarvr** [baldurk/renderdoc#1418]
## Description

I would like to be able to script captures on an attached android VR device.
Ideally have something else, like the app i'm profiling when it has low FPS, trigger the capture.

From renderdoccmd, i dont see a way to do remote captures.  It seems the remotesersver option there is for replays.

Is all of the python code compiled into qrenderdoc? the only .pyd files i see are for qt stuff.

Is there any other docs (ive seen the ones that show a few commands like renderdoc.EnumerateRemoteTargets but dont list any of the arguments) on the python objects besides using dir() inside of qrenderdoc python shelll?

update: the inspect module will show me the arguments for the python funcs/methods

Thanks!

## Environment

renderdoc 1.4
windows 10
capturing android (oculus quest)

**Comment by baldurk** [comment]
About the python modules in general, if you build RenderDoc from source you can get a python module for the [core interface](https://renderdoc.org/docs/python_api/renderdoc/index.html) which the UI is built on. This isn't distributed due to the impracticality of distributing python modules (I'd need to ship one per minor version of python at least - I don't know if patch versions break ABI compatibility too).

The documentation is [all available online](https://renderdoc.org/docs/python_api/index.html) as well as through the `help()` python built-in, e.g. `help(renderdoc.EnumerateRemoteTargets)`.

It is definitely possible to script capture and analysis on desktop platforms, I do that already for automatic testing and you can look at the infrastructure [here in github](https://github.com/baldurk/renderdoc/tree/v1.x/util/test). I haven't done it myself but in theory it'd be possible to script access over remote servers although starting & setting up communication with those remote servers is outside the scope of the RenderDoc API itself.

However I have no plans to ever try to extend automatic scripting support to Android. Android is a truly awful platform and extremely unreliable even at the best of times, relying on a lot of bespoke hacks in code. I don't want to increase the platform support burden even further by trying to support stable scripting access. In theory it is possible, since the UI is built on top of the same APIs as are exposed to python, however you'd need to use the undocumented internal android interfaces to properly enumerate and configure Android devices. Those are untested from python and may change at any time, so you're on your own if you want to attempt that.
