### ISSUE TITLE
Feature Request: Display Vulkan handles in Resource Inspector

### ISSUE THREAD

**Issue by Dolphiniac** [baldurk/renderdoc#1427]
If I'm not mistaken, the default identifier for Vulkan resources in the playback system is just a monotonically increasing ID (for an unnamed resource).  It would be useful if the handles returned to the app were displayed in the resource inspector, at least, so that unnamed resources can still be identified in a debugging session by comparing the value of the VkImage, VkBuffer, etc. to the resource inspected in the RDC.

If this is already supported and I've missed it, please disregard.

**Comment by baldurk** [comment]
This is inadvisable for a few reasons: Vulkan handles can be re-used if an object is destroyed then a new one is created, many vulkan types are not required to be unique (the classic example being VkSampler for which an implementation is free to return duplicate handles), and with the layer system the handle that RenderDoc's layer sees might not be the same as the handle the application sees due to object wrapping. Other APIs have similar issues, which is why the unique ID is generated to ensure a consistent identifier for each resource.

If you need to correlate resources in a capture to resources from the running application then you can use `VK_EXT_debug_utils` or the older `VK_EXT_debug_marker` to give those resources names, which is a good practice anyway.
