### ISSUE TITLE
Inject Error

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#1439]
use tag1.4 in visual studio 2017. the app can inject and capture in one of my android device, but can't inject in other device.  there is the log.
[renderdoc_errorLog.txt](https://github.com/baldurk/renderdoc/files/3358342/renderdoc_errorLog.txt)

**Comment by baldurk** [comment]
Does this happen with the official v1.4 build? I can't support any problems you encounter on Android that aren't reproducible on an official stable build or nightly build due both to the requirement for interceptor-lib, and how unreliable the platform is in general leading to build variation and unpredictability.

I also can't investigate this bug unless you provide steps to reproduce and give the details of your environment. Since you say it works on one device the chances I'll be able to reproduce it on one of my available devices is very low, and in fact that indicates that the bug is likely not in RenderDoc but in the version of Android on the device itself.

The log indicates that `android.app.ApplicationLoaders.getClassLoader` was found but then never called. To debug this you'd need to find out why that isn't called on your version of Android but I don't know how you would do that. It's very likely that this is a bug in your device or Android version.

If you can show that this could be a RenderDoc bug, or provide steps to reproduce it that I can follow, I'll look into it. My expectation is that this is an Android bug though especially when it is device-specific issue.

**Comment by ghost** [comment]
I have root the device.Maybe  the   error caused because this.I want to fix it, but dont know how to start, and what reason the error become.

**Comment by baldurk** [comment]
If you've rooted the device I can't predict what could be going wrong, something is breaking the normal call to that function `getClassLoader` but whether it can be fixed I don't know.
