### ISSUE TITLE
ANGLE and extra extensions

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1448]
## Description

We have a GLES application that uses ANGLE on PC. We have code that detects whether compressed textures are supported and act based on that. However, GLES being convoluted as it is, there are always several ways of doing the same thing. In this case, detecting support for DXT5 can be detected via several extensions:

1) GL_EXT_texture_compression_s3tc
2) GL_EXT_texture_compression_s3tc_srgb
3) GL_ANGLE_texture_compression_dxt5

All those will tell you whether it supports DXT5 and we check all 3. However, ANGLE seems to only report the last two, and renderdoc only support the first one. How should this ideally work? I'd love renderdoc to be able to handle them gracefully even if ANGLE seems to be doing the wrong thing.

## Repro steps

Load and call glGetString(GL_EXTENSIONS);

## Environment

* RenderDoc build: e.g. v1.4
* Operating System: e.g. Windows 10
* API: e.g. OpenGL ES

**Comment by baldurk** [comment]
Looking at it, I should be able to whitelist `GL_EXT_texture_compression_s3tc_srgb`. The equivalent functionality in proper GL is in `GL_EXT_texture_sRGB_decode`.

The [`GL_EXT_texture_compression_s3tc_srgb` spec](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_s3tc_srgb.txt) does say that `GL_EXT_texture_compression_s3tc` is required, so I'm not sure it's valid to report one without the other, but neither the GLES spec nor ANGLE are super reliable so the easiest fix is just to report both (since you'll likely want SRGB encoded textures anyway).

It's worth noting that to my knowledge ANGLE does not support GLES well enough for RenderDoc to function. I think you should be able to capture OK as I have a lot of emulation/fallback paths for capturing on downlevel devices, but I don't believe replay will work. If you're on windows then the only GLES replay that I'm aware of that works is NV's driver supported replay.

**Comment by baldurk** [comment]
That commit should whitelist `GL_EXT_texture_compression_s3tc_srgb` on GLES now, let me know if that's enough to get by on - but as above I'm not sure things will work with ANGLE in general.

**Comment by redorav** [comment]
Oh, not at all, I actually am able to capture, replay and work pretty reliably with a recent version of ANGLE, with relatively complex scenes as well. So, good job I guess!
