### ISSUE TITLE
glDrawArrays() shows mode GL_NONE where GL_POINTS was used.

### ISSUE THREAD

**Issue by stolk** [baldurk/renderdoc#1452]
## Description

renderdoc shows a glDrawArrays() call as using mode GL_NONE.

But that was not what was specified in my call.

![image](https://user-images.githubusercontent.com/455280/61093694-9f3c5f80-a400-11e9-827b-cffda8048f11.png)

Whereas the code in question is like thus:
```
    glDrawArrays( GL_POINTS, 0, c_numStars );
```

I noticed that my GL_LINES and GL_TRIANGLES drawing do show up correctly.

## Repro steps

Capturing a trace of a program drawing points.

## Environment

* RenderDoc v1.4
* Operating System:Ubuntu Linux
* API: OpenGL
* GPU: nVidia GTX 1650

**Comment by baldurk** [comment]
In a perverse sense, you *are* passing `GL_NONE` to `glDrawArrays`, because `GLenum` is just defined as an unsigned integer with each `GL_...` value as a `#define`. Unfortunately while most GL enums quickly started getting unique values (at least modulo extension suffixes), `GL_NONE` and `GL_POINTS` are both defined to 0.

When serialising `GLenum` values in general RenderDoc has to pick one value to disambiguate so `GL_NONE` is far more often the intended value, compared to `GL_POINTS` so that's how it shows up. I agree though that this isn't ideal and actually someone brought this up recently, so I made a change in 85738ad571034bc22374b0440ca42e2b5dce3598 which does a context-sensitive serialise to special case the topology enum.

If you run with a recent nightly build it should then display `GL_POINTS` as expected. If it doesn't then let me know.
