### ISSUE TITLE
Crash when launching native Android Vulkan app

### ISSUE THREAD

**Issue by kudaba** [baldurk/renderdoc#1454]
I have an app that is running perfectly on Windows with no validation errors, but I've been having loads of problems getting it up and running on Android. After stumbling through a lot broken code that the worked fine on windows and crashes on android with no validation errors, I've finally managed to get it stable and running fine. My last issue is that no 3D objects are rendering (ImGui renders fine). I'm definitely doing a lot of things out of the ordinary:
* Compiling with visual studio
* Stuck on platform r16b (lack of visual studio support)
* Compiling hlsl shaders at runtime through locally compiled shaderc (ImGui uses precompiled Spir-v)

Basically at this point I just need to debug what's going on in the frame but every time I launch with renderdoc is crashes on startup. I tried embedding the renderdoc layer into my apk and launching but it seemed to be crashing slightly differently. In both cases I'm really at a loss as to what to try next.

The callstack when I launch and debug through android studio:
art_sigsegv_fault 0x00000070b7ab4da8
art::FaultManager::HandleFault(int, siginfo*, void*) 0x00000070b7ab52b4
___lldb_unnamed_symbol20$$app_process64 0x0000005a4c806b5c
<unknown> 0x000000713d9d5870
___lldb_unnamed_symbol290$$libvulkan.so 0x0000007139d13370
___lldb_unnamed_symbol294$$libvulkan.so 0x0000007139d136f4
___lldb_unnamed_symbol279$$libvulkan.so 0x0000007139d12fbc
___lldb_unnamed_symbol278$$libvulkan.so 0x0000007139d12ad8
___lldb_unnamed_symbol14$$libvulkan.so 0x0000007139d08ee0
std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*)) 0x000000713cd62e1c
___lldb_unnamed_symbol5$$libvulkan.so 0x0000007139d07804
GR_VulkanRenderSystem::Initialize() GR_VulkanRenderSystem.cpp:447

It's crashing in vkCreateInstance, the entry above GR_VulkanRenderSystem::Initialize(). I've attached the relevant bits of the logcat for this run.

I've also attached the log file from renderdoc, that callstack seems to have crashed shortly after vkCreateInstance.

## Repro steps

Launch native android app built with visual studio using platform r16b.

## Environment

* RenderDoc build: v1.4 built from 214d8522
* Operating System: Windows 10, Android 9 (Pixel 1 and 3)
* API: Vulkan

[Debug - logcat.log](https://github.com/baldurk/renderdoc/files/3385386/Debug.-.logcat.log)
[RenderDoc_2019.07.11_23.39.21.log](https://github.com/baldurk/renderdoc/files/3385387/RenderDoc_2019.07.11_23.39.21.log)

**Comment by baldurk** [comment]
Can you provide your application for me to reproduce the problem? The repro steps of "launch any native android app" aren't very helpful because I can test with native apps here and it works fine, so there's something specific to what you're doing that's causing the problem.

I would definitely strongly recommend that you don't try to do any manual custom steps like embedding the layer in the apk. That is not how RenderDoc is supposed to work and given how terrible a platform Android is I would not be surprised if it crashed in unexpected ways.

One thing, the callstack in the RenderDoc log you attached suggests that the validation layers are active and in fact the crash is happening within the layers after a `vkCreateDevice` call. Can you test without the validation layers to see if that makes any difference? In the past the validation layers have had bugs/crashes when interacting with RenderDoc so it's good to simplify the repro case.

**Comment by kudaba** [comment]
You nailed it. Not sure about other NDKs but r15c and r16b seem to have very broken validation layers. Disabling fixed most of the rendering issues and got renderdoc working again.

Thanks for the quick response and accurate feedback. I'm going to assume that since the validation layers are broken it's not working debugging the issue any further.

Thanks!

**Comment by baldurk** [comment]
Going by the NDK archive r15c and r16b are from 2017 so I'm not surprised you had problems. When you use the layers I'd recommend using the latest available, either from the latest NDK or from building them yourself from source. But yes any debugging/investigation would need to happen on the validation layers repository, not here.
