### ISSUE TITLE
Error about storage permission on android device

### ISSUE THREAD

**Issue by xiaodaxia** [baldurk/renderdoc#1459]
* RenderDoc build: latest source code build.
* Operating System: Host Ubuntu Linux, Target: Android 8.1
I am using qrenderdoc to connect to my android 8.1 mobile phone, and after a while there is an error message said:
"Enable RenderDocCmd to access storage on your device"
I do not quite understand how to do it. I searched the document and do not find anything related. So maybe you can give me some hints about how can I enable RenderDocCmd to access storage on my device.
Also does it bother that I did not compile the arm64 version? I only compile the arm32 version.

**Comment by baldurk** [comment]
The error message is very poorly written, I'll update the text to better convey the problem. The error comes from when RenderDoc is unable to properly verify that the server APK is installed properly and may be missing permissions that are required to function.

Since Android is a terrible and unreliable platform, the normal install process that grants permission sometimes fails so it must be installed without permissions granted - in this case you have to manually give the APK the correct permissions using the Android menus.

If you are building from source this can happen if you have not correctly built the precisely matching APK to the UI, since then the version check will always fail, or if you have not correctly built all ABIs needed for functioning. If your device supports arm64 then you must build both arm64 and arm32. You must also always run precisely matching source on both android and host PC.
