### ISSUE TITLE
OpenGL 2015 ARB extensions support

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#146]
Hi,
Khornos release 12-13 new ARB extensions which be would like a new OpenGL revision..
I issued a bug on apitrace and they supported the same day!
can you add support for that?

**Comment by baldurk** [comment]
Similar notes/caveats to #145. For OpenGL RenderDoc doesn't necessarily support all ARB extensions, only core versions (for example, ARB_bindless_texture would be a real pain to support since it's lacking some key functionality).

I can look at which of the extensions would be trivial to support like GLSL only extensions.

**Comment by oscarbg** [comment]
Interesting missing func. in  ARB_bindless_texture for supporting it as a recent NV Nsight talk says they support it minus ARB_sparse_texture so that may be more difficult, right?

**Comment by baldurk** [comment]
Added support for the 'trivial' extensions that are just shader side so I don't have to anything for them, so at least applications still see them reported. There are a few others that aren't hard to support so I'll try and get them added at some point.

The problem I found with ARB_bindless_texture is that there's no uniform query function, and IIRC no way from program introspection to see if a uniform is a handle or a regular texture uniform. This means I don't think there's a way to find out after the fact if a uniform was set to a handle or not, which is the way renderdoc treats every other uniform. ARB_gpu_shader_int64 could help with this since it adds a 64-bit GetUniform, but you still need to know if the 64-bit value is a handle or not which is ambiguous after the fact.

**Comment by oscarbg** [comment]
Ok thanks for insight!

**Comment by baldurk** [comment]
I'm closing this meta-issue as it's not clear whether you are using these extensions in a project or requesting them just because they exist. If there's a specific extension you want to have supported please open an issue for it and provide a sample program using it.

**Comment by oscarbg** [comment]
yes can close by now, somewhat embrassed as I asked just because they exist..
