### ISSUE TITLE
Texure Viewer displays completely black instead of showing textures or render targets

### ISSUE THREAD

**Issue by nusus** [baldurk/renderdoc#1466]
## Description
Texure Viewer displays completely black instead of showing textures or render targets

## Repro steps
1. Capture a rdc file on android.
2. Open it on PC(Local mode).

## Environment

* v1.4
* Capture rdc file on Android 5.1 and Open it on Windows 10.
* OpenGL ES
![企业微信截图_15637953686587](https://user-images.githubusercontent.com/7028516/61630518-79de0a00-acba-11e9-8d29-1fc12b72950e.png)
[RenderDoc_2019.07.22_17.32.12.log](https://github.com/baldurk/renderdoc/files/3417193/RenderDoc_2019.07.22_17.32.12.log)

**Comment by baldurk** [comment]
Android 5.1 is not supported, RenderDoc's minimum requirement is Android 6. Also when capturing on Android it is quite possible to encounter errors if you replay anywhere else than that exact device, due to different extension/feature support and driver bugs on GLES.

It generally does not work to open Android captures on PC - GLES support on PC is not great and I've only found NV's emulation to work reliably. Your Intel driver is displaying a number of errors which may be driver issues (the driver is almost 3 years old) or incompatibilities between the Android device and the PC.
