### ISSUE TITLE
"Attempting to read off the end of the buffer"

### ISSUE THREAD

**Issue by stolk** [baldurk/renderdoc#1467]
## Description

renderdoc issues a warning:

`Warning - Attempting to read off the end of the buffer (16 2560000). Will be clamped (2560000)`

Which I think is bogus.

## Repro steps

Run https://stolk.org/tmp/train.tgz through renderdoc, launch game, and capture a frame.

When you click on the "stars" render, the warning is issued.
But if we examine the gl calls, I don't see anything out of range.

The VBO:
![image](https://user-images.githubusercontent.com/455280/61662356-213f4a80-ac83-11e9-8304-87557d181509.png)

The VAO:
![image](https://user-images.githubusercontent.com/455280/61662448-5055bc00-ac83-11e9-9dde-fbc6b3ca2650.png)

The draw-call does exactly 80000 points, starting at index 0:
![image](https://user-images.githubusercontent.com/455280/61662625-9b6fcf00-ac83-11e9-93f0-4b5692660f4a.png)

80,000 times the 32 byte stride, is a 256,000 byte buffer, exactly the length of the VBO, and which renderdoc, claims, gets exceeded.

## Environment

* RenderDoc build: v1.4
* Operating System: Ubuntu Linux
* API: OpenGL
* GPU: GTX 1650

**Comment by baldurk** [comment]
That warning is not an error or a problem in itself. What actual problem or incorrect behaviour do you see?

**Comment by stolk** [comment]
The rendering is fine, and the behaviour of renderdoc as well, it is just confusing if renderdoc warns you about exceeding a buffer, when you actually do not?

So mainly a problem of confusion.

Should I take this to mean that the renderdoc tool tried exceeding the buffer, and not my application?

**Comment by baldurk** [comment]
RenderDoc isn't warning you about exceeding a buffer, warnings intended for the user are displayed in the UI. You're reading an internal log file intended for diagnosing problems which contains messages that may or may not be relevant. When fetching mesh data the calculation is not tightly packed but fetches a conservative amount of data, which can lead to it being clamped.

If you actually have a problem then the log can be useful for myself or someone familiar with the RenderDoc code to see what the problem is, but it is not intended for user consumption so you shouldn't file bugs based on messages you see there.
