### ISSUE TITLE
How to install RenderDoc? (Linux)

### ISSUE THREAD

**Issue by regulator-g** [baldurk/renderdoc#1474]
Hi guys
I cant find any documentation on how to install RenderDoc?

I'm on Ubuntu,
I downloaded the TAR file, "tar -xvf" now what, there is no .sh file

do I just move the folder to /usr then add the steam launch option?

 (can the readme and documentation please be updated with how to install)

* RenderDoc build:  v1.4
* Operating System:  Ubuntu Linux

**Comment by baldurk** [comment]
I'm not sure what .sh file you're expecting. The binary tarball comes with standard bin, lib, share, etc folders. It's up to you where you want to install it as the prefix itself doesn't matter - the binary will work just as well from anywhere, whether system-global or user home-local. If you want to extract it under /usr that's up to you, though be absolutely sure that that's what you want to do, since typically /usr is managed exclusively by your package manager.

I also don't understand what you mean about a steam launch option. RenderDoc has nothing to do with steam.

If you're unsure about how to proceed with the tarball I'd suggest it might be easier to see if your distribution has a package that you can fetch which is then managed for you in the same way as all other packages.

**Comment by regulator-g** [comment]
I saw /usr has bin, lib etc so I extracted it there - the readme sort of suggests this

On this page https://renderdoc.org/docs/getting_started/quick_start.html

Can you please add this:

Installation:

(Windows - run the exe start the app)

Linux
1. extract the tar somewhere like your home directory probably not usr as that's managed by your package manager
2. open the bin folder and run `renderdoccmd vulkanregister`
3. you should now be able to launch games and use the tool with `renderdoccmd capture "game exe path"`

might seem a bit simple to mention but some people are new to linux (I've been using it over a year myself)

**Comment by dwilde1** [comment]
On Ubuntu, RenderDoc and all its variants are now available through the Synaptic package manager.
