### ISSUE TITLE
RenderDoc doesn't disassemble SPIR-V 1.3

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#1477]
## Description

SPIR-V 1.3 adds support for subgroup operations. RenderDoc doesn't disassemble SPIR-V 1.3 and thus cannot be used to inspect issues with these operations.

Please consider supporting this SPIR-V version.

## Repro steps

Add `--target-env spirv1.3` to glslang validator on any shader, take a capture and try to disassemble it with RenderDoc.

## Environment

* RenderDoc build: tag: v1.4
* Operating System: Linux
* API: Vulkan

**Comment by baldurk** [comment]
If you need to examine the SPIR-V in detail then I recommend that you use the output from a dedicated tool such as spirv-dis or spirv-cross, both of which ship with RenderDoc and are automatically configured if they are available in the path. RenderDoc's disassembly is not canonical and shouldn't be relied on, it exists only because it predates spirv-cross and is necessary when those tools aren't available.

I do plan to refactor RenderDoc's SPIR-V processing in future which should support SPIR-V 1.3, but I don't know what the disassembly will look like (it will not look like it does now) and it will always be superceded by those tools.

**Comment by baldurk** [comment]
The new processing has been pushed to the latest v1.x branch which now supports SPIR-V 1.3, though as above it is not a like-for-like replacement and the disassembly will be less readable. It's recommended that you use spirv-cross or spirv-dis to inspect the shaders depending on the output you want.
