### ISSUE TITLE
Looking at drawcalls makes persistent changes to target textures

### ISSUE THREAD

**Issue by yuriks** [baldurk/renderdoc#148]
Trace file: https://dl.dropboxusercontent.com/u/1990844/2015-08/bradef-bloom.7z

Looking at draws 16, 17, 18 in the linked trace file makes "permanent" changes to the target textures, which affect earlier draw calls in the trace. Each time they are viewed the bloom textures are blended against the framebuffer again, until eventually the entire frame is just white. The issue goes away when the trace is reloaded but re-occurs if you select the problematic draws again.

**Comment by baldurk** [comment]
I realised that I actually hadn't implemented the initial state stuff where if a texture's contents aren't stored, then I don't actually fill it out with anything to make sure that stuff from 'later' in the frame doesn't leak 'earlier' as you were seeing.

The fix is backwards compatible so your captured log opens fine and replays correctly now.

**Comment by yuriks** [comment]
Seems to be working fine on 0.26 beta! Thanks!
