### ISSUE TITLE
Question: Meaning of an error message connected to indirect draw

### ISSUE THREAD

**Issue by Destranix** [baldurk/renderdoc#1483]
## Description

Hello,
I have written a programm, that executes several VkCmdDrawIndirectByteBufferEXT commands.
In Renderdoc I got this Errormessage:
"Creating renderpass Resourceid::##### contains a subpass dependency that would allow writing indirect command arguments. Indirect command contents are read at the end of the render pass, so write-after-read overwrites will cause incorrect display of indirect arguments."

I don't really understand, what this message actually means. I could not find anything in the Vulkan Specification stating me, what I am doing wrong.

Maybe you can explain, what exactly this errormessage is referring to, so I can fix my application.

Thanks in advance!

## Environment

*RenderDoc build: v1.4, built from 214d8522
* Operating System: Windows 7
* API: Vulkan

**Comment by baldurk** [comment]
This isn't an error, it is a warning. It comes not from anything in the Vulkan specification but from RenderDoc's operation. There's not necessarily anything to 'fix' in your application but it is warning you that depending on what your program does RenderDoc may behave wrongly.

As in the warning message, you have a subpass dependency which allows the writing of indirect command arguments - i.e. it has an access mask containing `VK_ACCESS_INDIRECT_COMMAND_READ_BIT`. RenderDoc cannot read indirect command arguments precisely at the drawcall due to Vulkan limitations, it must read them after the renderpass is done.

This works fine if the arguments aren't modified between the draw and the end of the renderpass, but the subpass dependency declares allows you that ability. If you're not overwriting the arguments then there's no problem, but if you are then RenderDoc will display the wrong arguments which is what the warning is about.

**Comment by Destranix** [comment]
Ah, ok, now I understand. Thanks for your explanation!
