### ISSUE TITLE
Segfault when running on Android device

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1486]
## Description
I downloaded RenderDoc v1.4 and build it as per the instructions for Linux & Android.
I am able to build the RenderDoc application and the required apks successfully for arm 32 & 64.

When I tried to launch a debuggable application on target arm device running android P, I am getting segmentation fault issue. I attached the log file RDOC.log.

Can you help in running the application on arm devices running Android P?

[RDOC.log](https://github.com/baldurk/renderdoc/files/3475568/RDOC.log)

## Environment

* RenderDoc build:  v1.4 
* Operating System:  Ubuntu Linux
* API: OpenGLES
* Target device: Oppo Realme mobile device running Android P.

**Comment by baldurk** [comment]
Currently Android P is not supported, and given the unreliable nature of the platform I'm not surprised there are crashes with the new version.

I don't have any Android P devices, if support isn't contributed by someone else I will look at adding support once I can test it.

**Comment by baldurk** [comment]
Sorry I was mistaken, looking again Android P is Android 9 which has been out for a while. Android's versioning is almost as bad as windows 10's so I can't keep track of which one is which by the different version names.

Unfortunately that means I can't explain why you're seeing crashes, as Android 9 works for me in my testing and I know it works for others. It must be something more specific than just the android version and is likely device specific - unless I can reproduce the problem I can't debug it.

It looks like you're running a self-built version of v1.4, can you please test with an official build? On Android I can only properly support official builds because Android is far too fragile and broken to support custom builds - they may break for unpredictable reasons.

**Comment by gittmi** [comment]
Thanks Baldurk. I am building from the sources and I followed the same build instructions mentioned in RenderDoc's documentation. 
What do you mean by official build? What is the difference between building from sources and official build?

**Comment by baldurk** [comment]
Yes I understand that you're building from sources. That's why I'd like you to run an official build downloaded from [renderdoc.org](https://renderdoc.org/builds), either v1.4 or a recent nightly build, to know if it also fails. We can't completely be sure but if that also fails then we can probably eliminate your build process as a potential problem.

For example judging by the log you posted you have built **without** interceptor-lib, and as [noted in the build documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md#note) building without interceptor-lib may cause crashes and is only available because it is not feasible to have a hard requirement of interceptor-lib at build time.

On a proper platform like Windows or Linux, building from source at the same revision is reliable and trustworthy. On Android however there are many unpredictable things that can go wrong and I simply don't trust that the build process is reliable enough not to introduce bugs based on how it is built.

**Comment by gittmi** [comment]
The official binaries are working on Android P device. This means I need to build RenderDoc with interceptor lib instaed of PLT hooking. Am I correct? Do you see any other possibilities of it gets failing?

**Comment by baldurk** [comment]
If the official binaries work then the problem must be in your build process as it cannot be in the source itself (which is the same for the official build).

If you haven't built with interceptor-lib then that's definitely the first thing to try since technically I only support Android when building with interceptor-lib. The documentation explicitly states that compiling without it could cause bad behaviour or crashes.

If that doesn't help then I don't know what could be wrong, it might be your system environment or NDK version, or some other variance that affects the Android build in an unexpected way. It's not within the scope of this project to diagnose Android system bugs.
