### ISSUE TITLE
Can I capture a frame rendered to a D3DImage?

### ISSUE THREAD

**Issue by eladmaimoni** [baldurk/renderdoc#1488]
A issue resembling this is dicussed [here](https://github.com/baldurk/renderdoc/issues/117).

I have a WPF application that uses DX11 to render to a texture shared with WPF's D3DImage. My application creates a ID3D11Texture2D shared instance (D3D11_RESOURCE_MISC_SHARED flag), extract the shared handle from it and passes it to a D3DImage instance.

Since I render to a texture, I used the RenderDoc In-application API to manually capture frames.

```
if(rdoc_api) rdoc_api->StartFrameCapture(NULL, NULL);

RenderStuffToSharedTexture();
_immediateContext->Flush();

if(rdoc_api) rdoc_api->EndFrameCapture(NULL, NULL);
```

When I launch my application, it works as expected, RenderDoc correctly recognizes the DX11 context, and the manual capturing of frames in my code seems to trigger RenderDoc capturing as expected.

Yet, when I open up any of the captured frames, everything is empty, it seems as if no information is captured.

- What could be the problem?
- Is it possible to use RenderDoc in this scenario?
- Is there a work around?
- Can RenderDoc work with DirectX shared resources?

**Comment by eladmaimoni** [comment]
Well, I managed to get it working.

My Application Is using 2 distinct d3d11 devices & context. each one is responsible for a different kind of rendering.

Seems like render doc wasn't able to capture correctly when 2 device / context instances existed at the same time.

After disabling the creation of the second device, capturing works as expected. But maybe this is a bug?

**Comment by baldurk** [comment]
RenderDoc does support multiple devices from the same API, or different APIs. However if you have two devices then you need to specify which one to capture from. Usually this happens implicitly by seeing which device is presenting to the active window and starting and stopping the capture at two presents to that window.

The behaviour you're seeing is not a bug, it's precisely what your code does: When you call `StartFrameCapture` and `EndFrameCapture` you pass `NULL` for both parameters, which [as documented](https://renderdoc.org/docs/in_application_api.html#_CPPv217StartFrameCapture23RENDERDOC_DevicePointer22RENDERDOC_WindowHandle) means "I don't care which device or window to capture from, please pick any":

> `device` and `wndHandle` can either or both be set to NULL to wildcard match against active device/window combinations.
> If the wildcard match has multiple possible candidates, it is not defined which will be chosen. Wildcard matching should only be used when e.g. it is known that only one API is active on a window, or there is only one window active for a given API.

As mentioned this is usually only useful when you only have one device. If you have multiple devices then you should pass the handle of the device you want to capture from as the first parameter to each function, then RenderDoc will capture from that device specifically.

**Comment by eladmaimoni** [comment]
Thanks for the explanation. Though I did try to pass the right ID3D11DeviceContext pointer to StartFrameCapture / EndFrameCapture. It still did not work. Only after I disabled the second device creation then this worked as expected.

If I understand you correctly, it should work with multiple devices as long as you specify the device to capture from. So perhaps there is still an issue here?

**Comment by baldurk** [comment]
If you passed the `ID3D11DeviceContext` pointer then it would be unrecognised so that would still make sense. I recommend you read the [documentation linked above](https://renderdoc.org/docs/in_application_api.html), which explains that the device handle must be the `ID3D11Device` pointer for D3D11.

**Comment by eladmaimoni** [comment]
Well, you are right, passing `ID3D11DeviceContext ` seems to have the same effect as passing NULL. It works as long as there is only one device active in the process.

Yet, I tried to pass the ID3D11Device pointer as you said and manual capturing **simply stopped working** (either with one or 2 devices active).

I am very sorry for all the confusion, I am new to your tool. thanks again.

**Comment by baldurk** [comment]
If you can provide a repro case where passing the `ID3D11Device` pointer to `StartFrameCapture` doesn't work then please share it with me and I can look into it, be sure you are passing a valid device pointer and passing the same device to both calls.

I wrote a small test using two devices and it worked correctly for me so if there is a bug it requires more specific circumstances to hit.

**Comment by eladmaimoni** [comment]
Sending the whole program will be close to impossible as there are many dependencies and it is not portable. I will however try to invest some time to reproduce this in a more clean environment.

Regarding your test, I think I might have a few ideas why it works in your case.
The first device I create is being used to create an OpenCL device as well (sharing graphics / compute resources on AMD WX8200). It also initializes a proper debug layer (ID3D11Debug) and uses ID3D11Multithread to call SetMultithreadProtected(true).

This OpenCL interop alone is what prevented me from using any other tool other than RenderDoc.

Thanks again for your help and I will try to get back to you with a proper reproducible example.

**Comment by baldurk** [comment]
I understand, repros can definitely be hard to share but unfortunately it's difficult for me to investigate further without one.

It doesn't matter which other interfaces or interops you initialise, since the raw `ID3D11Device*` pointer value doesn't change. What is important that the device pointer you pass through is *exactly* the same value as was returned to you from `D3D11CreateDevice` or `D3D11CreateDeviceAndSwapChain`. That means you can't pass a `ID3D11Device2` or any other derived/alternate interface, and if you're using any bindings or helpers which might wrap the interface you can't pass those pointers either.

If you're willing to try, you could building RenderDoc from source and step inside the `StartFrameCapture` function to see what's going wrong, and compare your device pointer value to the expected handles it checks against. If you look in the log, do you see a message something like "Couldn't find matching frame capturer for device 0xdeadbeef window 0x0" ? That will tell you if the device pointer you're passing is invalid.
