### ISSUE TITLE
Rendering breaks inside renderdoc when loading an attached Vulkan capture (similar to #1309)

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#1489]
## Description

Rendering of the texture viewer (and more) is not working with the following .rdc loaded.

[mgsacid2.zip](https://github.com/baldurk/renderdoc/files/3480609/mgsacid2.zip)

Additionally, loading the .rdc immediately after capturing it fails with "Replay failed at the API level".

## Repro steps

Load the attached .rdc, try to inspect textures.

## Environment

* RenderDoc build: v1.4
* Windows 10
* API: Vulkan

**Comment by baldurk** [comment]
As far as I can see this is the same bug as #1309: The rendering is failing because of a device lost error, which depending on when it happened could also trigger the "Replay failed at the API level" message. It's triggered by the exact same cause - all the descriptor contents are missing.

The capture was made on v1.4, which is before the fix for #1309 landed. I can't tell from the capture why it happened, but given that you found the previous bug it seems quite possible you're hitting the same bug again. Do you believe that this is a different bug or that your code has changed such that you wouldn't hit the previous bug and so wouldn't need that fix?

Can you test on a recent nightly build after that fix landed to see if that works please? If it still fails can you share a capture made from that recent build.

**Comment by hrydgard** [comment]
This is when debugging a different game. For some reason I thought there had been a point release since that one so that your fix should have been in, but yeah, it's probably just the same thing. I'll self-close as duplicate.

**Comment by hrydgard** [comment]
Sorry again, it does work on nightly. Set up a new machine and had installed 1.4 on it..
