### ISSUE TITLE
Mesh viewer should display warning if no attribute is selected for Position

### ISSUE THREAD

**Issue by yuriks** [baldurk/renderdoc#149]
Currently, if you're using OpenGL and don't set an attribute to be the position by right-clicking on the table the pre-VS mesh viewer simply displays nothing. It is not immediately obvious why nothing is displayed and that you have to do this, so I think a warning should be displayed in the UI in that case.

**Comment by baldurk** [comment]
I haven't added a warning but I have made it so that no matter what, *some* element will be selected for display as position. rather than only matching "position" or "pos" names, it will look for those substrings if it can't find a better match, or if all else fails just pick the first attribute which is better than nothing.

There is a discoverability issue with even knowing you can right-click on the columns but that's a slightly separate issue.

**Comment by yuriks** [comment]
Seems to work ok, and the heuristics should catch the vast majority of cases indeed.
