### ISSUE TITLE
ANDROID_NATIVE_API_LEVEL is not setting the given value while building

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1496]
## Description
I am trying to build the RenderDoc from sources using 
cmake -DBUILD_ANDROID=On -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_ABI=arm64-v8a ..

Even though I setANDROID_NATIVE_API_LEVEL to 24 the the build system is using API level 21 only. This may cause the problem when I build for Andrid P where the value is 28.
It is always showing to 21 irrespective of whatever value we set through cmake build.

**The below is the output of cmake build.**
-- Using JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
-- Using Android SDK found in /home/hmakkena/Android/Sdk
-- Using Android NDK found in /home/hmakkena/android-ndk-r14b
-- Calculating version
-- Building RenderDoc version 1.4
-- Disabling qrenderdoc for android build
-- Disabling renderdoc python modules for android build
-- Using Android ABI arm64-v8a
**-- Using Android native API level 21**
-- LLVM 4.0.1 found - enabling android hooking using interceptor-lib.
-- Using Android build-tools version 28.0.3
-- Using android.jar from platform android-23
-- Building APK versionCode 14, versionName 2c080d1aea97df0431e862abb4b63cb668ed5bdd
-- Enabled APIs:
--   - OpenGL ES (EGL)
--   - Vulkan
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hmakkena/Test/RenderDoc_v1.4_Ubuntu/only_64-bit/renderdoc/build-android-arm64

## Environment

* RenderDoc build: v1.4
* Operating System: Ubuntu Linux
* API: Vulkan, OpenGL

**Comment by baldurk** [comment]
If you want to customise the android platform then you should use `-DANDROID_PLATFORM=android-28` to override the default setting. `ANDROID_NATIVE_API_LEVEL` is a derived value generated by the android cmake toolchain file.

However it's worth noting that there is little benefit to doing that, since apks built with API level 21 will work just fine on Android P and beyond with normal backwards compatibility. It definitely won't cause any problems by itself as all official RenderDoc builds are built with the default API level and they all work fine on Android P.

The only reason to build with a newer API level is to access features or behaviour added in newer versions of Android, at the cost of breaking compatibility with older versions of Android.
