### ISSUE TITLE
qrenderdoc crashes on launch

### ISSUE THREAD

**Issue by markonius** [baldurk/renderdoc#1499]
## Description

When running qrenderdoc I get the following error:
`free(): invalid pointer`
The application is terminated with SIGABRT

## Repro steps

Run qrenderdoc

## Environment

* renderdoccmd x64 v1.4 built from 214d85228538e71cc63a0d7fa11dd75b1d56cc81
* Fedora 30

## Aditional info

Version 1.1 from Fedora repos launches properly

**Comment by baldurk** [comment]
Did you compile RenderDoc yourself from source, are you installing a distro package, or are you running the binary builds from [renderdoc.org](https://renderdoc.org/builds)?

If you're running the binary builds, try compiling from source or installing a distribution package. Binary builds on linux are not reliable in all cases and while they will work on some distributions they'll break on others. They're there as a 'best effort' attempt for users, source builds or distribution packages should always be preferred.

**Comment by Lawrencemm** [comment]
Can confirm I get this with a fresh install of Fedora 30. Building Renderdoc seems also to be quite tricky on Fedora.

**Comment by baldurk** [comment]
What's the issue with building on Fedora? I was working on a Fedora 30 install yesterday and it built without any problems.

**Comment by Lawrencemm** [comment]
I'll give it another try, tried it a while ago.

**Comment by Lawrencemm** [comment]
OK it worked though I had to specify both `-DQT_QMAKE_EXECUTABLE=qmake-qt5` and  `-DQMAKE_QT5_COMMAND=qmake-qt5` which was kind of confusing :sweat_smile:

**Comment by baldurk** [comment]
Blech that's my fault for losing track of which variable is which. You should only need to set `QMAKE_QT5_COMMAND`, the `QT_QMAKE_EXECUTABLE` one is something that Qt creator sets if you're using it and overrides the default for `QMAKE_QT5_COMMAND`. So it should just be internal, but I accidentally used it for the version check I recently added. I'll fix that.

**Comment by lumonix** [comment]
fyi.
Same "Invalid Pointer" error happens on Ubuntu 19.04 for me when using the binary build 1.4.
18.10 on same machine worked ok.
(I've not tried building renderdoc for 19.04)

**Comment by lumonix** [comment]
This nightly build works ok for me on Ubuntu 19.04:
renderdoc_2019_09_01_e15a10a0

**Comment by baldurk** [comment]
As mentioned above binary builds are fundamentally not reliable on linux, so distribution packages or local builds from source should be preferred. I expect that any nightly build after `ea126251, 2019-06-25` will work for you as that's when the builds stopped static linking `libstdc++`, but correspondingly that may be when those builds start *breaking* for someone else on a different distribution.

What's relevant for this issue is knowing whether the original reporter was also running binary builds, which is ambiguous given the `v1.4 built from 214d852` phrasing. If they were running the binaries then it is a known issue as long as the latest nightly works for them, if not then it's something that needs to be investigated.

**Comment by baldurk** [comment]
Closing this due to lack of information. Assuming that the binary tarball of v1.4 was being run then it may be the known issue discussed above and should hopefully be fixed in newer builds.
