### ISSUE TITLE
Capture frame 1

### ISSUE THREAD

**Issue by eodabash** [baldurk/renderdoc#150]
I suppose there's a specific reason why you can't queue capture for frame 1, is this a fundamental limitation, or something that could be made to work?

**Comment by baldurk** [comment]
RenderDoc marks the frame boundaries as Present() calls, in the absence of any application triggered captures which can be arbitrary divisions. So when you hit F12 to capture, that capture starts at the next Present() call and runs until the Present() after that.

But being exactly correct, frame 1 contains all the commands from the start of the application to the first Present(), and frame 2 is between the first and second Present()s.

So the problem is that RenderDoc doesn't start capturing early enough to get frame 1, 2 is the earliest it can manage. This could be maybe be implemented by starting off the code in the capturing state immediately, but I'd be a little worried about doing that with an application that then does a lot of heavyweight work before ever Presenting. I guess that's up to the user not to queue a capture of frame 1 in that case.

If you need to do this in the meantime I'd suggest using the application API to start and stop a capture yourself within the bounds of frame 1.

**Comment by eodabash** [comment]
Sounds reasonable, thanks. Adding an extra Present at the beginning of the first frame also seems to do the trick :grin:

**Comment by baldurk** [comment]
Should work now I think, but no promises that there isn't some bug lurking in there somewhere that's exposed by this corner case. Of course, if that does happen then you can file a report :).

**Comment by eodabash** [comment]
Nice! Just did a quick test and it seems to work correctly so far.
