### ISSUE TITLE
Weird Crash with glCopyImageSubData in latest RenderDoc versions [1.4, 1.3, 1.2, and 1.1]

### ISSUE THREAD

**Issue by incetents** [baldurk/renderdoc#1509]
## Description

RenderDoc 1.4 crashes at a seemingly arbitrary OpenGL call [glCopyImageSubData] in my capture. It's particularly strange because the function is called twice already in the frame and it's only on the 3rd call that the crash occurs. Removing the 3rd call will remove the crash entirely.

Downgrading to RenderDoc 1.0 will omit the crash entirely.
It also crashes on RenderDoc Version 1.1, 1.2, and 1.3

I've attached my capture [~20mb] to this issue

As far as I know, no major OpenGL errors are being triggered by my executable.

## Repro steps

Simply running the program will cause crash once it hits the function: glCopyImageSubData.
This crash occurs in RenderDoc version 1.4, 1.3, 1.2, and 1.1
However, it does not crash on RenderDoc version 1.0

## Environment

RenderDoc 1.4, 1.3, 1.2, 1.1, and 1.0
Windows 10 Home 64bit
computer supports OpenGL 4.6, 
[WeirdCrash.zip](https://github.com/baldurk/renderdoc/files/3567710/WeirdCrash.zip)
using OpenGL 4.2 for window context.
GPU: Nvidia, GeForce GTX 1060 6GB

**Comment by incetents** [comment]
Just a quick note, the window context is using OpenGL Core. I've also tried switching the OpenGL context version to 4.5 and the crash still occurs.

**Comment by baldurk** [comment]
Your repro steps require running your program but you didn't include your program so I can't follow them to actually reproduce the problem. Can you please share your program either here or privately so that I can reproduce the problem?

I opened the capture that you attached in WeirdCrash.zip but it only has two glCopyImageSubData calls - I presume since the third one is crashing. I did notice that I get OpenGL error messages from the nvidia driver that both glCopyImageSubData calls are specifying `GL_RENDERBUFFER` for one of the images but the image itself is a texture, not a renderbuffer:

```
GL_INVALID_VALUE error generated. <srcName> or <dstName> does not correspond to a valid renderbuffer object.
GL_INVALID_VALUE error generated. <srcName> or <dstName> does not correspond to a valid renderbuffer object.
```

I would recommend running your program with the OpenGL debug validation enabled and make sure you have updated your drivers in case you have old drivers which are lacking all the checks necessary.

**Comment by incetents** [comment]
Thanks for the info, I'll do some debugging when I get some more free time. In the mean time. I'll attach the program I forgot to include. Thanks for all your help.
[Debug.zip](https://github.com/baldurk/renderdoc/files/3569572/Debug.zip)

**Comment by baldurk** [comment]
That commit should fix it - the debug messages are a result of RenderDoc's bug not your code, it was looking up textures instead of renderbuffers which is why the wrong texture got used. It worked with some warnings when the object name was valid for either a texture or a renderbuffer, but when there was a call where it only corresponded to a renderbuffer and *not* a texture then the crash happened.
