### ISSUE TITLE
Loading DDS textures crashes in 0.25 but not in 0.24

### ISSUE THREAD

**Issue by xoofx** [baldurk/renderdoc#151]
Using the texture preview feature of RenderDoc, it seems that lots of DDS textures are no longer working with 0.25 while 0.24 are able to load them. May be a regression?

**Comment by baldurk** [comment]
Yes unfortunately this didn't get caught when I released v0.25, but since it's a minor feature I decided not to do a followup bugfix release. I fixed it with 3e9f47f, so any nightly build after that will work - if you want just v0.25 + fix then take the nightly build from [master branch @ 13010b72, 2015-07-23](https://renderdoc.org/builds).

**Comment by xoofx** [comment]
Great, thanks!
