### ISSUE TITLE
CompType::Typeless is not handled when remotely replaying DX11 capture with Linux client

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#1516]
## Description

I'm running QRenderDoc on Linux machine and want to replay a DX11 capture on remote host (doesn't matter if server is running on Windows or under Wine). In this case QRenderDoc uses OpenGL to render output. 

In `MakeGLFormat` or one level higher in `GLReplay::CreateProxyTexture` `fmt.compType` is never tested for `CompType::Typeless` so DX11 typeless textures are displayed incorrectly.

## Repro steps

- On Linux connect to remote host which support DX11
- Open [D3DTemplate.zip](https://github.com/baldurk/renderdoc/files/3591067/D3DTemplate.zip)
- Select "DS" output in the only DrawIndexed
- The texture is not displayed and all values of pixels are incorrect
 
## Environment

* RenderDoc build: 2019-09-08 nightly build.
* Operating System: Linux + Windows

**Comment by baldurk** [comment]
This is a tricky one, since GL has no native concept of typeless textures so we need to decide a type at create time, but we don't have it until it's later rendered. It's kind of a problem of mapping a more capable to a less capable API.

GL has texture views in an extension but they're ugly and awkward to set up, as well as needing a fallback path if they're not supported. At the moment even if the proxy texture was created somehow the type hint used at render time is ignored on GL because there's no equivalent for native GL display.

Even if it's ugly that's probably the only feasible fix, but this does make it more appealing to implement proxy support for Vulkan so that we can use that wherever possible instead of GL for local proxying on linux.

**Comment by werman** [comment]
> but this does make it more appealing to implement proxy support for Vulkan so that we can use that wherever possible instead of GL for local proxying on linux.

This would be nice. Is this something you plan to do in near future? Or it's something that would be nice to have some day.

In case it's not planned I may try to implement it. Am I right that to implement proxying next methods should be implemented:
```
  virtual ResourceId CreateProxyTexture(const TextureDescription &templateTex) = 0;
  virtual void SetProxyTextureData(ResourceId texid, uint32_t arrayIdx, uint32_t mip, byte *data,
                                   size_t dataSize) = 0;
  virtual bool IsTextureSupported(const ResourceFormat &format) = 0;

  virtual ResourceId CreateProxyBuffer(const BufferDescription &templateBuf) = 0;
  virtual void SetProxyBufferData(ResourceId bufid, byte *data, size_t dataSize) = 0;
```

**Comment by baldurk** [comment]
Probably not in the near future, it's just a nice-to-have indeed. Especially it doesn't actually save any time for fixing this bug, because adding Vulkan proxy support doesn't help for people who don't have Vulkan.

Yes exactly, if you look in `vk_replay.cpp` there are a few functions that are not implemented yet. `VulkanReplay::NeedRemapForFetch` also needs an implementation in addition to what you have listed there.

**Comment by baldurk** [comment]
This took longer than I thought to address but I've now done the necessary refactoring to allow for this display. I've also added tests that should hopefully ensure that in future the remote proxying doesn't break between different APIs, even if vulkan support is added in future.
