### ISSUE TITLE
VK_ERROR_VALIDATION_FAILED_EXT returned by vkAcquireNextImageKHR 

### ISSUE THREAD

**Issue by Destranix** [baldurk/renderdoc#1526]
## Description

While having "VK_LAYER_RENDERDOC_Capture" and "VK_LAYER_LUNARG_standard_validation" enabled, by capturing a frame, some kind of race condition seems to be triggered causing the application to crash on vkAcquireNextImageKHR with VK_ERROR_VALIDATION_FAILED_EXT  and losing of the device at some random point in the futur.

This might not be directly connected to Renderdoc, it could also be caused by i.e. longer waits caused by Renderdoc Frame capture.

## Environment

*Renderdoc build: 214d8522
*Operating System: Windows 7
*API: Vulkan 1.1 in LWJGL

*Grafics card: Nvidia GTX 880M
*Driver version: 425.31

Might be connected to:
https://devtalk.nvidia.com/default/topic/1042819/vulkan/possible-vulkan-driver-bug-with-vkacquirenextimagekhr-/

**Comment by baldurk** [comment]
You haven't provided repro steps, and the problem doesn't apply to all vulkan applications universally - I can run e.g. Sascha Willems' samples with RenderDoc and the validation layers, or the SDK cube demo. I can't investigate this problem without specific steps e.g. your application if you can share that.

I would also recommend updating to newer nvidia drivers as yours are reasonably old, and try running without the validation layers as they have been known to cause problems in the past. This would isolate whether the problem is caused only by RenderDoc, by only the validation layers, or by the combination of both.

If that doesn't help further then make sure that the latest validation layers aren't reporting any warnings or errors and if you can provide repro steps that I can use to reproduce the problem I can look into it further.

**Comment by Destranix** [comment]
Also occures when disabling LunarG standard validation and updating to latest driver version(425.31).

I'll send you some captures and the rendered scene by mail. They are to big to upload them here.

If you also want me to provide some host-sourcecode, I can upload a shortened version of my mainloop, only containing Vulkan commands and synchronization structures.

**Comment by baldurk** [comment]
From email conversation this appears to be an application use-after-free error, closing.

**Comment by Destranix** [comment]
The error persists after removing that use-after-free of the command buffers.

The Resizing issue was fixed by that, but not the swapchaincrash.(On my system)

Did that swapchain crash appere on your system too?

I can sent you another application for testing with that use-after-free-Fix applied, if you want.

**Comment by baldurk** [comment]
If you send through the fixed application I'll look again.
