### ISSUE TITLE
It is unclear which samplers are bound for which combined image/sampler when viewing pipeline state

### ISSUE THREAD

**Issue by Dolphiniac** [baldurk/renderdoc#1533]
An app that I'm working in makes liberal use of combined image/samplers, some of which are unused, and I'm having trouble telling which sampler is being used by which descriptor due to some sort of grouping mechanism for shared sampler states in RD.

In the first image, there are three samplers shared among eleven descriptors.  From this capture alone, I might surmise that each sampler "belongs to" all descriptors listed above it, except I'm reasonably certain that the first sampler is used by both "DiffuseSampler" and "NormalSampler", and that the second sampler is used for all of the "BAD_TEX image" descriptors (in both of these cases, the sampler is listed below and above at least one descriptor to which it applies).

In the second image, there is only one sampler, but it appears between the two descriptors to which it logically must be applied.  It's fairly obvious in this example where the sampler applies, but it hints at some confusion about how I should be reading the groups.

Some clarification would be greatly appreciated.

RenderDoc build: v1.4 (built from 214d8522)
Operating System: Windows 10
API: Vulkan

**Comment by Dolphiniac** [comment]
![rd1](https://user-images.githubusercontent.com/2808134/65636290-9f7fdc00-dfa7-11e9-8f2a-03735bb69e50.PNG)
![rd2](https://user-images.githubusercontent.com/2808134/65636294-a1e23600-dfa7-11e9-8550-109e91c509a1.PNG)

**Comment by baldurk** [comment]
If you hover over the sampler row it is supposed to highlight all other rows using that sampler (and similarly hovering over an image will highlight the sampler that it uses). It looks like that behaviour never got correctly ported over to the Qt UI.

This is because I only list each sampler on the first descriptor that uses it, to reduce redundant noise that could make the pipeline state twice as long in the worst case.

The images using the same sampler can't be grouped because each combined descriptor can use any sampler in any order. The order is already defined by the bindings and can't be changed, so it's impossible to also group same-sampler-images together. Where a sampler is listed is just the lowest-numbered binding that uses it (or if it's also available as a separate sampler).

The existence of combined image/samplers is an ugly API wart that IMO should never have made it into vulkan from GL, especially since the use of separate image/samplers is required to be supported.

**Comment by baldurk** [comment]
That commit actually implements the intended highlighting, and also adds the sampler in combined image/sampler descriptors into the tooltip along with the image layout.
