### ISSUE TITLE
No API, no overlay since updating to Vulkan SDK/RT 1.1.121.2

### ISSUE THREAD

**Issue by Carandiru0** [baldurk/renderdoc#1536]
It seems to affect old builds and the latest build that I'm working on right now (MinCity)
So I can't capture with RenderDoc on builds that used an older VulkanSDK version, or the latest (1.1.121.2)

This is the only thing that has changed on my PC - so are you by chance having a similar issue if you update the Vulkan SDK, and install the Vulkan RT 1.1.121.2 ?

Just want to also say I really dig RenderDoc - its clearly the most stable and best tool of the like out there - good job! 

I should also note I tried uninstalling RenderDoc, deleting the directory and reinstalling RenderDoc 1.4 (installer version). Then updating the files in the directory with the latest RenderDoc nightly (9/29/2019) - same issue "no api" no RenderDoc overlay!

Thanks!

Attached a log file, if it will be of any help:
[RenderDoc_2019.09.30_14.10.16.log](https://github.com/baldurk/renderdoc/files/3673273/RenderDoc_2019.09.30_14.10.16.log)
note: the WSA connection forcibly closed pops into the diagnostic log when I close the app(MinCity)

**Comment by Carandiru0** [comment]
I also tried manually enabling the RenderDoc layer in the Vulkan configuration tool, that didn't seem to help.

**Comment by baldurk** [comment]
The vulkan SDK version has very little to do with how RenderDoc works so the version should be immaterial. I've tested with the latest SDK and it works fine for me.

On the launch process panel within RenderDoc do you have a banner telling you that the Vulkan layer is not configured correctly? If the SDK had a bug or problem that caused the implicit layer registration to be lost then that might explain what you're seeing:

![image](https://user-images.githubusercontent.com/661798/65914977-5a561280-e3ca-11e9-970f-556315f9092b.png)

Can you capture a simple test program, like vkcube that's included with the SDK? Or does that have the same issues?

You should absolutely never use the Vulkan configuration tool with RenderDoc nor use any other way of enabling the vulkan layer than launching your application through RenderDoc. The config tool in particular has caused many problems in the past so it should be avoided, and enabling the vulkan layer in an unexpected way might break things because that's not how RenderDoc is supposed to be used.

**Comment by Carandiru0** [comment]
Well, I rolled back drivers for my AMD Radeon 290 from 19.9.2 to 19.6.2 and now RenderDoc is capturing MinCity again! I'm not entirely sure why - just happy to see its working again.
If you need any more info / logs let me know.
I did try the Vulkan Cube before I rolled back and it would not capture either.
Oh and there was no warning label like you have displayed in RenderDoc for me ever.

**Comment by baldurk** [comment]
I've tested with them and the 19.9.2 drivers do work with RenderDoc, and generally a driver won't break things so badly that RenderDoc doesn't load into an application at all, which again suggests that this is some system problem and not a RenderDoc bug. You'd need to investigate the loader to know why it's not loading the layer.

Closing this if you have it working now.
