### ISSUE TITLE
Temporary captures are added to the recent captures list

### ISSUE THREAD

**Issue by ajweeks** [baldurk/renderdoc#1540]
When calling `RENDERDOC_API_1_4_0::LaunchReplayUI` and passing in a filepath to a file captured using `Start`/`EndFrameCapture`, the file is added to the list of recent captures even though it is temporary (it is deleted on shutdown).

I'm wondering if a flag could be set in the capture file itself which marks it as temporary? Then when saving a file manually, the flag could be cleared and it would then be added to the recent list. On shutdown any open temporary files could be safely deleted.

## Repro steps
1. Launch my application
1a. call `LoadLibraryA`, passing in a path to my locally-built `renderdoc.dll`
1b. Retrieve a pointer to `RENDERDOC_GetAPI` using the given module handle
1c. Call the retrieved function to retrieve a `RENDERDOC_API_1_4_0*`
2. Initialize my application, and begin rendering frames
3. Call `StartFrameCapture(NULL, NULL)` at the start of a frame, and `EndFrameCapture(NULL, NULL)` at the end of the same frame
4. Pass the file path retrieved from `GetCapture(0, ...)` to `LaunchReplayUI(1, captureFilePath)`
4a. qrenderdoc is launched
5. The capture appears in the connection tab, and it opens automatically
    - At this point it is present on disk, and already in the recent list, but marked as being unsaved (`LiveCapture::Capture::saved` is `false`)
6. Close RenderDoc
6a. Unsaved capture prompt appears, asking if the capture should be saved
6b. Choose "No"
6c. **The file is deleted from disk**
7. On future launches of RenderDoc, the now deleted file is still present in the recent captures list

See [#1531](https://github.com/baldurk/renderdoc/pull/1531#issuecomment-537168093) for more context.

**Comment by baldurk** [comment]
Adding a flag to the file would be quite problematic since then if RenderDoc crashed without removing the flag, or if the user copied the file out of the temp folder, the state would stick around when it really shouldn't.

I think this is a case where it's important to fail-safe, so instead we should detect when a temporary file is deleted and remove it from the recent captures if the exact path is listed, and allow the recent captures list to temporarily overflow in memory and truncate to 10 when saving the list to disk, so we don't lose anything if that happens. Then we only remove the list entry when we know it's been invalidated.

**Comment by baldurk** [comment]
That commit should sort it out I believe, I checked the various ways where a temporary file could get deleted and they will all remove the item from the recent file list.
