### ISSUE TITLE
Python bindings for replay only

### ISSUE THREAD

**Issue by djdeath** [baldurk/renderdoc#1550]
## Python bindings without Qt

I'm looking for a way to replay a single frame from a python script and dump the performance counters for each draw call into a csv file. Essentially automating the file generation.

I've tried to build the python bindings of renderdoc for a few hours on Linux and ended up giving up.
The 2 dependencies : Shiboken2 & PySide2 are actually available on Ubuntu but a couple of issues with CMake not finding those dependencies (actually I fixed that locally) and the Shiboken package not shipping a `.pc` file for the python3 bindings make this essentially unusable, unless you're will to build those 2 dependencies yourself (there was another issue where it was mentioned that the pip packages are not an option either).

I'm no expert in python binding but it seems pyside2 at least is used for the UI binding.
Would making bindings just for non UI bits of renderdoc be possible without those 2 dependencies?

**Comment by baldurk** [comment]
I think there's some kind of misunderstanding here, I don't know if it's on my side or your side.

PySide2 (and shiboken) are used for exposing the Qt widgets in the UI bindings to python. This allows you to do e.g. `pyrenderdoc.GetMainWindow().Widget().setWindowTitle("I am making a Qt call to set the title")` and then you set the Qt main window title to that string. All of Qt5 is exposed via those bindings when available.

If PySide2 isn't available at compile time, then the return of `Widget()` there is an opaque handle. So it's only useful for e.g. manipulating the docking window state etc with other qrenderdoc module functions that accept the opaque handle and unbox it on C++ side. It's not possible to have the Qt widgets fully accessible on scripting without PySide2 or some equivalent python Qt bindings library.

If you don't have PySide2, cmake will print a message like "PySide2 not found - Qt will not be accessible in python scripting." to indicate that you won't be able to access Qt in the python scripting, but the python bindings will be built as normal otherwise. On linux the standalone python module will be placed in the `lib/` output folder, and if you open qrenderdoc the python shell will work as normal aside from the limitations on accessing `Widget()` as above.

For your purposes can you not just use the replay bindings without requiring access to the Qt widgets? Either directly with the python module and command line python, or else with the UI scripting access just running normal replay commands. I guess I'm not understanding whether you want Qt scripting access or not - if you do then PySide2 is required, and if you don't then I don't understand what the problem is exactly.

**Comment by djdeath** [comment]
Yeah I'm not interested in manipulating any Qt widget. Maybe I got confused...

I was expected a `module` directory to be created and that I should point the python path to that.
Since it's not there I thought I was missing a build dependency.

**Comment by baldurk** [comment]
The python module is built by default, and is only disabled if `ENABLE_PYRENDERDOC` is turned off in cmake. There's no `module` directory, library is output as `lib/renderdoc.so`. I'm not sure where `module` would come from.

**Comment by djdeath** [comment]
Thanks, sorry for the noise.
