### ISSUE TITLE
Blank capture from simple openGL app

### ISSUE THREAD

**Issue by radgeRayden** [baldurk/renderdoc#1551]
## Description
Even though the capture miniature shows up in renderdoc, the capture itself contains nothing between the start of the frame and the SwapBuffers call.
![image](https://user-images.githubusercontent.com/8618621/66771389-bd8e7d00-ee7f-11e9-8283-4ddd9a50873e.png)

## Repro steps

Unfortunately there's nothing too specific here; my app draws a textured quad to an FBO and then displays that. I'd be glad to get some tips on how I can further troubleshoot this.

Capture:
https://drive.google.com/open?id=1hzNQrfz8hnSXwzyBWD3xkCihlaqz52mZ

## Environment

* RenderDoc build: 
RenderDoc v1.6 Linux 64-bit Release (d3a4f5dc09cd882ca8023f94698ef5ec9b0fb1ed)
(renderdoc-git package from the AUR, the issue was also present in the non-git version)
* Operating System: Arch Linux 64-bit
* API: OpenGL 4.5
* Driver: amdgpu
* GPU info: X.Org / AMD Radeon R7 M260 (ICELAND, DRM 3.33.0, 5.3.1-arch1-1-ARCH, LLVM 9.0.0) / 4.5 (Core Profile) Mesa 19.2.1

**Comment by baldurk** [comment]
I'll need more information to be able to investigate this. The capture is indeed empty but that in itself is not by definition a bug - if a program doesn't do any rendering then an empty capture file is valid and expected. To know why it was produced without the rendering you'd expect to be captured, I need to debug the program while it's capturing.

Can you share your program? Either here or in private, that way I can follow the repro steps and debug the problem.

**Comment by radgeRayden** [comment]
here's my program:
https://drive.google.com/open?id=1eiOFOFRZa0T5lSo_MrjQHrkT-Y9MIZ20
just extract and execute `launcher.sh`.

Only requirement to run is that SDL2 is installed on the system, and a 4.5 context is supported. If you need any more info feel free.

**Comment by baldurk** [comment]
`libscopesrt.so` depends on a number of clang libraries, and I'm not sure where they should come from. I installed `libclang-9-dev` but it provides _static_ libraries e.g. libclangCodeGen.a. From a quick look at the clang project it seems like these are static by default, if you built them as shared yourself can you send those in another tar.gz?

```
game => bin/game (interpreter => /lib64/ld-linux-x86-64.so.2)
    libscopesrt.so => bin/libscopesrt.so
        libclangCodeGen.so.9 => not found
        libclangFrontend.so.9 => not found
        libclangDriver.so.9 => not found
        libclangSerialization.so.9 => not found
        libclangParse.so.9 => not found
        libclangSema.so.9 => not found
        libclangAnalysis.so.9 => not found
        libclangEdit.so.9 => not found
        libclangASTMatchers.so.9 => not found
        libclangAST.so.9 => not found
        libclangLex.so.9 => not found
        libclangBasic.so.9 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
        libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6
            libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by radgeRayden** [comment]
Sorry about that! It turns out that unbeknownst to me arch linux only offers a shared version of the libclang libraries, and I was under the assumption I was linking statically. I installed LLVM locally and rebuilt libscopesrt so it should just work now:

https://drive.google.com/open?id=1xDvveT3Lkj9buBmguMxD-UiQjhxv7KiJ

**Comment by baldurk** [comment]
OK I see the problem. Your program is unfortunately crafted in such a way as to be very difficult to hook GL calls properly. While investigating I noticed that apitrace has the same problem.

The issue is that normally programs fetch symbols via one of a two ways - either by linking against the library directly and letting the runtime linker resolve the symbol, or by using `dlopen` to get the library handle and `dlsym` to fetch the symbol. RenderDoc intercepts both of these with `LD_PRELOAD`, in the latter case also by a detour via our own hook of `dlopen` to return our own library instead of `libGL` when requested.

Unfortunately your code is doing some extra steps which break free - it does `dlsym` to fetch `dlopen` (from `libSDL2.so` weirdly - which searches through its dependencies) and finds the _real_ `dlopen` in `libdl.so` instead of RenderDoc's hook, then it calls that dynamically fetched dlopen to load everything else from there. This looks like it's in aid of runtime code generation.

In that commit above I've added an opt-in setting to hook `dlsym` as well as `dlopen` and intercept this. It works in the test case for your game, but it relies on glibc internals and it's pretty unstable so I don't expect this to ever be enabled by default. This option is not considered officially supported so use it at your own risk.

If possible I'd recommend restructuring your code so that you use the `dlopen` that the runtime linker finds for you, which will point to RenderDoc's. Or else using `dlsym` with `RTLD_DEFAULT` instead of `libSDL2` which I think will also return RenderDoc's from the default search order. Then things should work without the use of `dlsym` above.
