### ISSUE TITLE
Feature(vk): Better support for custom ICDs

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#1552]
## Description

We're working with RenderDoc to capture Vulkan traces running in ANGLE/GLES. We've also been looking at using it to capture traces with a custom ICD for SwiftShader. The tricky part is when we try to load Vulkan from the custom ICD for the 'replay'. We've found that we need to use a fully qualified absolute path in the ICD json. RenderDoc seems unable to handle relative paths to the Vulkan ICD shared module itself.

## Repro steps

It's a bit tricky at the moment, but the gist of it is:

Follow the ANGLE build instructions here on Windows or Linux:
https://chromium.googlesource.com/angle/angle/+/master/doc/DevSetup.md

Build a Release version to `out/Release`.

Update `out/Release/swiftshader/libvk_swiftshader_icd.json` to use an absolute path to `out/Release/libvk_swiftshader.so` on Linux or `out/Release/vk_swiftshader.so` on Windows.

Set `VK_ICD_FILENAMES` to point to the absolute path of `libvk_swifthhader_icd.json`.

Set `RENDERDOC_HOOK_EGL=0` on Windows. On Linux you will need a custom build detailed here:

https://chromium.googlesource.com/angle/angle/+/master/doc/DebuggingTips.md#running-angle-under-renderdoc

Run RenderDoc with a Vulkan capture of `out/Release/simple_texture_2d --use-angle=vulkan`.

You should see a proper capture and attempted replay. Note that you might see a crash in SwiftShader.

To reproduce the issue, I moved the json file to the same folder as the .so/.dll and pointed `VK_ICD_FILENAMES` at it. RenderDoc couldn't load Vulkan properly for the replay at that point.

## Environment

* RenderDoc build: 2019-10-15 nightly build.
* Operating System: Windows 10
* API: Vulkan

**Comment by baldurk** [comment]
RenderDoc does supports custom ICDs without any special work, since it's all handled by the loader. Either you need to register the ICD system-wide in a per-platform way, or use `VK_ICD_FILENAMES` as you're doing now. All RenderDoc sees is an enumerated set of physical devices from the loader, it's up to you to ensure that the one you want is used on capture and available on replay.

You mention problems with the ICD paths in the json - that is nothing to do with RenderDoc, so if you're having trouble there you should investigate further what's happening. It's only the vulkan loader which parses those json manifests, RenderDoc does not touch those files or is even aware of them.

I'll try to repro this at some point although those steps are pretty involved so it might take a while before I get a chance. You didn't mention building swiftshader - does that happen as part of angle now or is that a separate step?

In the meantime I'd like to understand what exactly is going wrong. You've explained what you're trying to do but you've only said "RenderDoc couldn't load Vulkan properly for the replay" and I'm not quite sure precisely what kind of failure that means. Can you give more details about what goes wrong and share any relevant information there like an error log? Are you able to capture a simple demo like vkcube.exe with the swiftshader ICD (this should work as I did that a little while ago) - that would probably significantly reduce the scope of the repro.

**Comment by null77** [comment]
Looks like using `"library_path": ".\\vk_swiftshader.dll"` or `"./vk_swiftshader.so"` works nicely. I was wondering if we could get just `"library_path": "vk_swiftshader.dll"` working. But maybe that's overkill.

Sorry about the repro steps being difficult. Going to close this out for now.

**Comment by baldurk** [comment]
Difficult repro steps are better than no repro steps - I just wanted to frame expectations on how soon I can look at the problem.

For the manifest you should check out the [Vulkan Loader interface spec](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md#icd-manifest-file-format) - in particular how `library_path` is interpreted:

> The "library_path" specifies either a filename, a relative pathname, or a full pathname to an ICD shared library file. If "library_path" specifies a relative pathname, it is relative to the path of the JSON manifest file. If "library_path" specifies a filename, the library must live in the system's shared object search path. There are no rules about the name of the ICD shared library files other than it should end with the appropriate suffix (".DLL" on Windows, ".so" on Linux and ".dylib" on macOS).

So if you just pass a filename it needs to be in the normal dll search path, you do have to explicitly prepend `./` to make it relative.

**Comment by null77** [comment]
Gotcha. Thanks for the pointers. Seems to confirm it is my problem.
