### ISSUE TITLE
Filtering by GL context for multithreaded OpenGL

### ISSUE THREAD

**Issue by cmartel** [baldurk/renderdoc#1553]
This isn't an issue so much as a feature request/interest check, but I'd very much like better support of multiple context capturing and playback on multithreaded GL applications. The use case is basically: 

I'm in the process of separating our Qt Quick-based application's rendering into its own thread in order to have better control over said rendering. Qt creates a lot of GL contexts internally, and Qt Quick even more on top of that. Up until now, I've worked around this by reusing Qt's contexts and doing all of our own drawing when the context I need is active. This works fine for rendering to Qt Quick's framebuffers using the contexts created for them, but our application also needs to publish content rendered using OpenGL. 

I've optimized that rendering loop as much as I could, but now I'm hitting a wall where I can't submit work fast enough to the GPU when using Qt's own loop. So I'm looking into separating publish rendering into its own thread and context. I can initiate a RenderDoc capture on this thread using the in-application API, but since Qt still issues its own OpenGL commands at the same time, RenderDoc serializes all of these together. The resulting capture is nonsensical and doesn't reflect the actual state of the resources.

The closest existing issue I could find was https://github.com/baldurk/renderdoc/pull/943, and I get why that particular fix attempt doesn't work since the non-threaded approach to our application does use multiple contexts in this way and filtering them would clearly break that. As mentioned on that pull request, a proper fix would have to be considerably more complex, arguably more work than is warranted for what is a corner case. But this would be useful enough for us that I'd be game to tackle it. So I'm throwing this out here to discuss what would be considered a sufficient implementation. If it's not worth the work, I suppose I'll just have to merge the pull request mentioned earlier. ;)

**Comment by baldurk** [comment]
Being honest this is one of the cases where not only is it not a priority for me to work on but I don't think I would ever accept any PR that accomplished this due to the required changes it would mean. As mentioned in the other issue and as you allude to, it would be a large amount of work and added complexity for a pretty niche use-case with some _really_ horrendous corner cases.

To me GL is a legacy API that is already pretty terrible to work with in many ways even in a single-threaded case, and on top of that it wasn't properly designed for true multi-threading.

Of course one of the benefits of open source is that you can implement any support or features you want in your own build of RenderDoc, especially if you have a targetted set of requirements to narrow the scope of the problem. But this isn't something I'd ever expect to support upstream.

**Comment by cmartel** [comment]
> To me GL is a legacy API that is already pretty terrible to work with in many ways even in a single-threaded case, and on top of that it wasn't properly designed for true multi-threading.

That's fair and all too true. 

If anything, it's one more bullet point to the list of reasons why we need to invest the time and effort in a Vulkan/MoltenVK build, preferably before Apple kills OpenGL supports altogether. Now that Qt is coming out with imminent Qt Quick support for Vulkan, it might be time to pull that trigger.

**Comment by baldurk** [comment]
Yeh I didn't want to belabour the point - I know a lot of codebases have a legacy - but realistically a large majority of people who can't afford to just serialise their GL work onto a single thread will move to Vulkan (if they're not on D3D!).

That makes for this niche shrinking all the time, and I'd guess even today there are more people who'd benefit from old GL 1.x fixed function support.
