### ISSUE TITLE
Failed to launch x64 program

### ISSUE THREAD

**Issue by 1201yuge** [baldurk/renderdoc#1555]
## Description
After I have configured the path, click the Launch button, and the program will be stuck in the "please wait" dialog box.
![image](https://user-images.githubusercontent.com/26223594/67027530-4cc7b900-f13c-11e9-9976-d67905ed9323.png)

Then I debugged it, I found that the program was stuck in “WaitForSingleObject(hThread, INFINITE); win32_process.cpp line:290”.
![image](https://user-images.githubusercontent.com/26223594/67024690-6a465400-f137-11e9-99d3-cf160e52d68f.png)
In addition, I am very sure that my program can be opened and debugged normally in the old version of "renderdoc".

Can you help me?

## Environment

* New RenderDoc build: V1.5 (release) （can't works）
* Old RenderDoc build: unknown (works)
* Operating System: Windows 10
* API: OpenGL

**Comment by baldurk** [comment]
If it used to work in an old version of RenderDoc, which version of RenderDoc is that? It would be helpful to know if this problem was caused by a specific version. It would also make sure that the problem was introduced by a version of RenderDoc and not by a change in your program itself and it just so happened that last time it worked you used an older version.

The hung remote thread is in LoadLibrary which maybe suggests a deadlock in the target process, but that will depend on what's going on in the target process itself while the LoadLibrary thread is injected.

Please share a reproducible test case or set of repro steps as is requested in the issue template you edited to remove that section. If I can reproduce the problem then it's much more likely that I will be able to find the problem, as it is I do not have enough information to investigate the problem.

**Comment by 1201yuge** [comment]
Hi, I get the version of the old (can't work), it's also the version 1.5.... 
![image](https://user-images.githubusercontent.com/26223594/67059574-36494e00-f18c-11e9-858d-ad6e76f25a7d.png)

And the new version (can work) is:
![image](https://user-images.githubusercontent.com/26223594/67059693-ab1c8800-f18c-11e9-8e94-c84d18b7b0e4.png)

Step: 
1. Select the target program path for "executable path";
2. Select work path for "working directory";
3. Click "launch"“

Sorry, because our target program needs to be kept secret, I can't provide it.

**Comment by baldurk** [comment]
I don't understand, I thought you said that it used to work in an older build, and now it doesn't work in newer builds. Now are you saying that in an old build it doesn't work and in a new build it does work? Also where did that old build come from? Commit `a55b4c1c` doesn't exist in this repository.

**Comment by 1201yuge** [comment]
Oh~,  I'm sorry that my description was inaccurate.

**The truth is：**

The version which works is modified from your commit [db81116faed577282f63e0e2d5747f9de948d7d2](https://github.com/baldurk/renderdoc/commit/db81116faed577282f63e0e2d5747f9de948d7d2)

And the version which don't works is cloned from your [newest commit](https://github.com/baldurk/renderdoc/commit/7533c6b7ac7cac7cfab2d1a1ddc011c693202a47) ;

The modify of the old version is :
![image](https://user-images.githubusercontent.com/26223594/67084290-3f0f4380-f1cf-11e9-82f0-853eb09ef1c3.png)

At last, I made the same modify to the newest version, it works too, but I still don't known why?

**Comment by baldurk** [comment]
Does it work if you don't change anything but set the environment variable `RENDERDOC_HOOK_EGL` to 0? Does your program actually use EGL/GLES?

If you launch the program and the thread hangs, then attach a debugger to your process, what are the callstacks of all threads in the program?

**Comment by 1201yuge** [comment]
I'm not sure where to change the "RENDERDOC_HOOK_EGL" value. Like this?
![image](https://user-images.githubusercontent.com/26223594/67086240-e04bc900-f1d2-11e9-981f-77910f506871.png)

It dose't work.

**Comment by baldurk** [comment]
You're looking at an old version of the source code. I recommend doing any tests on the newest source code so that we look at the same thing, and since that's where any fix will be applied.

It is an environment variable - when launching your program you can set `RENDERDOC_HOOK_EGL` to value `0` in the capture dialog as an extra step between 2 and 3 in what you listed above:

> Step:
> 1. Select the target program path for "executable path";
> 2. Select work path for "working directory";
> 3. **Set the environment variable `RENDERDOC_HOOK_EGL` to value `0`**
> 4. Click "launch"“

I also asked other questions in the previous comment about whether your program uses EGL/GLES and the callstacks in the hung program - please answer them as without a reproducible test case I need all the information I can get from you to find the problem.

**Comment by 1201yuge** [comment]
1. Set RENDERDOC_HOOK_EGL to value 0 is works.
2. Our program don't use EGL/GLES;
3. I tried to attach a debugger to the  the thread hangs, but it's failed.
![image](https://user-images.githubusercontent.com/26223594/67086731-002fbc80-f1d4-11e9-83e6-e62681b1800c.png)

**Comment by baldurk** [comment]
That's quite strange and makes me think that something odd is going on in your program. If your program doesn't use EGL/GLES then adding a few more EGL hooks shouldn't change anything because they're added in the same way as all other hooks and are inactive until the API is used.

What if you set the "Debugger delay" capture option to e.g. 30 seconds, then attach to the process while it's waiting and let the process continue? You'll probably hit a breakpoint in `LdrBreakIn` or `LdrBreakPoint` which you can ignore and continue past. That way the debugger should be attached when the DLL is injected and you can pause it later once it has hung.

**Comment by 1201yuge** [comment]
Em... I've used Google to search around, but unfortunately I didn't find useful information about  "Debugger delay". Can you tell me the steps?

**Comment by baldurk** [comment]
It's an option in the capture dialog that you can set to the number of seconds to wait for a debugger after starting the process, before doing RenderDoc injection.

![image](https://user-images.githubusercontent.com/661798/67092968-80402d00-f1a8-11e9-88d1-ce81fe2b892f.png)

**Comment by 1201yuge** [comment]
Ok, here is the all callstacks.:

![image](https://user-images.githubusercontent.com/26223594/67094478-82c17780-f1e6-11e9-9d15-2f8642be9a94.png)

![image](https://user-images.githubusercontent.com/26223594/67094395-5ad21400-f1e6-11e9-8285-22067d2be8e9.png)

Note: I didn't change any code or set environment variables.

**Comment by 1201yuge** [comment]
And the ouput is:
![image](https://user-images.githubusercontent.com/26223594/67095421-73dbc480-f1e8-11e9-94b7-af957e4b1467.png)

**Comment by baldurk** [comment]
That's the callstack of only one thread, and it's in the wrong process - qrenderdoc.exe. I need to see the callstacks in the target process where the DLL injection has hung.

Also you said earlier that you aren't using EGL/GLES, but the output log shows that your process **is** using libEGL, in the final two lines. You must give me accurate information if I'm to help investigate the problem. Which EGL emulator are you using?

**Comment by 1201yuge** [comment]
I'm sorry. I'm new to our project, so I may have misunderstood it.   And how can I know which EGL emulator I am using?  Any key word can search?

**Comment by baldurk** [comment]
I can't really help much with that as it depends on your project - where does your libEGL.dll come from? What version/renderer strings do you get back from GLES when you create a GLES context through it?

**Comment by 1201yuge** [comment]
Our GLES version may be: version 1.5. Vendor: Imagination Technologies, Client APIs OpenGL_ES .
I'm sorry. If I can't provide enough information, I hope we can solve the problem.🙂

**Comment by baldurk** [comment]
I've tried the powervr GLES emulator before and I've found it quite buggy, my guess is that there is a deadlock somewhere inside there when calling `eglGetProcAddress` to fetch function pointers initially which is supposed to be valid at any time in EGL.

Even if this were to work on capture it would likely fail on replay as powervr's emulator I believe doesn't support enough of GLES to support RenderDoc's replay.

I would strongly recommend using proper OpenGL on desktop where it is always available, since it will use the graphics driver directly and work most reliably. Using a hobbled version of GL on purpose on windows and forcing yourself through an emulation library is asking for trouble.

As a workaround if you can't use OpenGL you could set the environment variable, or try loading `libEGL.dll` after your process has started instead of linking to it at compile time, that may avoid whatever deadlock is happening in powervr's emulator.

**Comment by 1201yuge** [comment]
Ok, thanks for your help! 👍

**Comment by 1201yuge** [comment]
Hey, I have a new discovery. My target program does not use EGL. It uses OpenGL, and after I delete libegl.dll in the project file, my target program still runs correctly.
