### ISSUE TITLE
[vulkan] Couldn't find matching frame capturer

### ISSUE THREAD

**Issue by Vincent-P** [baldurk/renderdoc#1556]
## Description

I am trying to use the in-application api, especially `StartFrameCapture` and `EndFrameCapture`.

The API seems to be correctly initilialized, but when calling `StartFrameCapture` there is this error message:

```
core.cpp( 463) - Error   - Couldn't find matching frame capturer for device 0000000000000000 window 0000000000000000
```

I also tried to pass the DevicePointer from the VkInstance and the winapi window handle, but it doesn't change anything. I also tried to add the layer `VK_LAYER_RENDERDOC_Capture` when creating the VkInstance but I think it is useless as the layer is implicit?

Regular captures taken from the Renderdoc app work fine.

## Environment

* RenderDoc build: v1.5
* RenderDoc API: 1.1.2
* Operating System: Windows 10 Pro 1809
* API: Vulkan 1.1.121
* GPU: RTX 2070, v431.07

**Comment by baldurk** [comment]
You should not try to enable the RenderDoc layer manually, as that could behave unpredictably.

With the error saying no matching capturer can be found for `NULL`/`NULL` that means that there's no active hooked vulkan instance, otherwise it would default to capturing that with the normal wildcard matching (assuming you don't have multiple instances or multiple windows).

How are you loading `renderdoc.dll` to fetch the in-application API? Are you calling `GetModuleHandle` to fetch it as recommended or are you loading it yourself with `LoadLibrary`? You could see the behaviour you're describing if you incorrectly load a second copy of `renderdoc.dll` from a different path.

Please share a reproducible test case that exhibits the problem, as is explicitly asked for in the issue template which you removed. Otherwise it's hard to guess what the problem is.

**Comment by Vincent-P** [comment]
I am really sorry about the lack of test case. I am working on a big project that I am not completely familiar with. That's why it is hard to share code/captures. I am also not sure if a simple test case would have the same behavior as the project Im working on.

I am more asking for potential problems that might cause this issue.

I think the dll is loaded with `LoadLibrary` as you guessed, but it is called only once. I will try to dig in this more tomorrow.

Thanks a lot for your help, and I apologize again for the lack of code/capture.
Just tell me if you don't want to bother to help without it, I don't want to waste your time.

**Comment by baldurk** [comment]
You should not load the dll yourself with `LoadLibrary` as that can cause problems like this or crashes. If you load one copy of the dll yourself but a different copy of the dll is registered as a vulkan layer then both copies will be loaded because they're loaded from different paths. They'll be mutually incompatible (you can't use the API fetched from one to capture from another), and other things may break or cause crashes. Instead you should launch your program through RenderDoc as normal and have code that looks for the dll via `GetModuleHandle`. That way it will pick up the correct dll that is injected.

It's not that I don't want to help without a repro but with any bug I need enough information to isolate the problem and fix it if needs be, a repro case is the easiest way to do that. If you can't share your program then it might help to modify an open source sample like vkcube or Sascha Willems' demos to load the API in the same way. If you can't reproduce it in a small sample then that itself can be a diagnostic tool - you can see what's different between your use case and the sample and try to simplify what you're doing.

Without being able to reproduce the problem I can only guess at the issue as I have above, and it can be a difficult process. In that case you need to provide as much information as possible.

**Comment by Vincent-P** [comment]
I am not familiar with the Windows API so I didn't think that the code to load the dll was wrong, I should have had included the code to load the dll indeed.
What you are describing is probably what is happening, the dll was copied in the project's folder but the layer is probably using the dll from renderdoc's folder.
The DX11 code path works fine with renderdoc, I assume it's specific to Vulkan and its debug layer.

Thanks again to take the time to help me, I will close the issue tomorrow if it works 😃.
