### ISSUE TITLE
When I install my own compiled APK for Android phone, the verification fails!

### ISSUE THREAD

**Issue by 1201yuge** [baldurk/renderdoc#1557]
## Description

When I try to use the newestRenderDoc(v1.6) to connect to my mobile phone, I am prompted that no relevant APK file has been found, so I compiled the corresponding Android APK according to your steps. But when I tried to connect to my phone again, the verification failed.

![image](https://user-images.githubusercontent.com/26223594/67149347-c696a880-f2dc-11e9-97b3-b10f1c4a3a97.png)

It can still capture frames normally, but when I try to open the captured frames, it shows "no active"：
![image](https://user-images.githubusercontent.com/26223594/67149607-c77d0980-f2df-11e9-9157-e8a14bf6b9c3.png)

### Apk compile steps:
Follow your [tutorial ](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md)exactly.

## Environment

* RenderDoc build: V1.6
* Operating System: Windows 10
* Phone: Android.

**Comment by baldurk** [comment]
Assuming that this only happens with your own compiled version of the code then you have made a mistake when building. Check to make sure that you've followed all of the steps correctly and have built all necessary APKs. As well as the error message itself you can use the diagnostic log to help see what the problem is or debug the code yourself to see where the error comes from.

If you find any problems when using only the nightly or stable builds then you can report them, but I cannot feasibly provide tech support for you building the code yourself when it is otherwise known to work.
