### ISSUE TITLE
D3D11 DrawInstancedIndirect correctly draws to mesh viewer if D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS is missing.

### ISSUE THREAD

**Issue by SimpsonGSD** [baldurk/renderdoc#1564]
## Description

If the draw buffer used in DrawInstancedIndirect is missing the flag D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS the GPU won't do the draw but RenderDoc mesh viewer draws it correctly causing a disconnect between the two outputs. Highlight draw call in the Texture Viewer works as expected and does not show the draw.

I don't know if this is a bug or a feature request but it would be really helpful if RenderDoc could catch this easy-to-make mistake and inform the user.

## Repro steps

Issue call to DrawInstancedIndirect with a draw buffer that doesn't have D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS set.

## Environment

* RenderDoc build: v1.5
* Operating System: Windows 10 1803.
* API: D3D11.
* GPU: GTX 1080ti.
* Driver: 430.86.

**Comment by baldurk** [comment]
RenderDoc does not try to do API validation, since that would be a huge task and is already done pretty well by each API's validation mechanisms. The D3D debug layers detect and emit a message for this error:

> `D3D11 ERROR: ID3D11DeviceContext::DrawInstancedIndirect: pBufferForArgs must be created with D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS. [ EXECUTION ERROR #2097207: DEVICE_DRAWINDIRECT_INVALID_ARG_BUFFER]`

Since you are invoking invalid behaviour the UI may behave inconsistently or even crash, depending on what the problem is.

You can enable API validation at capture time to get the errors/warnings listed in RenderDoc, but you should really use the API's validation directly yourself since as I say depending on the API and the error some errors could cause RenderDoc to crash before it can ever show you the validation messages.
