### ISSUE TITLE
Two captures for first draw frame

### ISSUE THREAD

**Issue by darkyellow** [baldurk/renderdoc#1570]
Hi

I have some code which renders some 3d / 2d to the screen using GLFW and LWJGL. I have a vulkan and opengl renderer. I am trying to debug something in opengl (vulkan renders correctly and works well in renderdoc) but am encountering some issues. When I load the app I get two captures straight away (in vulkan I only get one). I have tracked down the point where it generates the first capture and it this happens right after the GLFW window creation

    GLFW.glfwCreateWindow(

If I try and load this capture renderoc gets a segmentation fault

These are the settings I use to load the window

    GLFW.glfwWindowHint(GLFW.GLFW_RESIZABLE, GL_FALSE);
    GLFW.glfwWindowHint(GLFW.GLFW_DECORATED, GL_TRUE);
    GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, GL_FALSE);
    GLFW.glfwWindowHint(GLFW.GLFW_RED_BITS, value);
    GLFW.glfwWindowHint(GLFW.GLFW_GREEN_BITS, value);
    GLFW.glfwWindowHint(GLFW.GLFW_BLUE_BITS, value);
    GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_PROFILE, GLFW.GLFW_OPENGL_CORE_PROFILE);
    GLFW.glfwWindowHint(GLFW.GLFW_CLIENT_API, GLFW.GLFW_OPENGL_API);
    GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MAJOR, 4);
    GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MINOR, 5);

I am using Linux Ubuntu 19.10 (same on 19.04) and this has renderdoc 1.4 in the package manager. My video card is a built in Intel card.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
