### ISSUE TITLE
OpenGL Texture display broken

### ISSUE THREAD

**Issue by stohrendorf** [baldurk/renderdoc#1573]
## Description
Display of textures and framebuffer objects for (at least) OpenGL application is broken.

## Steps to reproduce

1. Launch application, take capture, everything is fine.
2. Launch application again, take capture, texture display is messed up.

## Environment

* RenderDoc version: 1.5
* Operating System: Windows 10 x64
* API: OpenGL 4.3 core

Application screenshot
![grafik](https://user-images.githubusercontent.com/7853507/68091577-bf959b80-fe81-11e9-879d-2d26258819c7.png)

Capture
![grafik](https://user-images.githubusercontent.com/7853507/68091603-05526400-fe82-11e9-9ced-dc06b0f656b9.png)

Please note the following:
* Pixel context is completely wrong
* All framebuffers are shown black in the outputs tab.
* The lower the zoom, the higher the chance the display completely disappears.
* The texture display stretches and shrinks with its viewport width (see below).

![grafik](https://user-images.githubusercontent.com/7853507/68091670-b658fe80-fe82-11e9-93f5-8cce40bf00a1.png)
![grafik](https://user-images.githubusercontent.com/7853507/68091674-beb13980-fe82-11e9-9453-eac213e05d26.png)

**Comment by baldurk** [comment]
Are you using an AMD GPU? This is a known issue which has been reported to AMD as a driver bug. It also affects the mesh viewer, showing it as very zoomed in as well.

If you're not using AMD then I will need more information about your system, because as described a bug this fundamental does not exist - I can follow those steps and it works fine for me. It may be specific to some interaction with your program, or your GPU & driver, so I'd need to narrow down exactly where it happens.

**Comment by stohrendorf** [comment]
Yes, it's AMD. Software version 19.10.1 on an RX 580, if that helps.

**Comment by baldurk** [comment]
Yeh unfortunately I'm not aware of anything you can do about this, aside from restarting RenderDoc every time you open a capture (or of course not using GL, or downgrading your AMD drivers to an older version). Hopefully it will be fixed in a future AMD driver but there's nothing I can do to fix it from my side.

I'll ask to see if I can add a workaround in the meantime until a fix lands in the driver.

**Comment by stohrendorf** [comment]
Thank you.

**Comment by baldurk** [comment]
I've asked but there doesn't seem to be any feasible workaround, this will have to wait until it's fixed in a later driver release.
