### ISSUE TITLE
Support of DX12 RenderPass

### ISSUE THREAD

**Issue by turanszkij** [baldurk/renderdoc#1574]
## Description
Render Passes have been introduced in DX12 recently, so an application can now use BeginRenderPass and EndRenderPass instead of OMSetRenderTargets and ClearRenderTargets: https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-beginrenderpass However, when the application uses render passes, RenderDoc is unable to attach to the application and instead it closes it when (probably) encountering the first BeginRenderPass command. 
It is a very new feature and Nsight also doesn't support it yet, but it would be nice to have in the future.

## Steps to reproduce
Use BeginRenderPass and EndRenderPass and RenderDoc will close the application.

## Environment
* RenderDoc version: 1.5
* Operating System: Windows 10, 1903
* API: DirectX 12

**Comment by baldurk** [comment]
There was code in there to capture and replay but it wasn't unwrapping the handles on capture (leading to the crash) and the replay was a bit buggy too.

This has still had only minimal testing because I don't have any example use cases to see the ins and outs, so there might still be bugs in there if you're using it. If you run into anything else please report it.

**Comment by turanszkij** [comment]
Thanks for the fix. Now capturing works, but RenderDoc will crash while trying to load a capture which contains render passes. I have some debug layer errors in there regarding resource states which I will fix before saying for certain.
