### ISSUE TITLE
cc1plus: out of memory when compiling for i686

### ISSUE THREAD

**Issue by obunden** [baldurk/renderdoc#1577]
## Description

I'm trying to update renderdoc to 1.5 in void linux, but they compile fails on i686 on both my machine and in the travis build system. See link for more information ->

https://travis-ci.org/void-linux/void-packages/builds/604794381?utm_source=github_status&utm_medium=notification

This is the error message:

```
cc1plus: out of memory allocating 65536 bytes after a total of 1137106944 bytes

make[2]: *** [renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/build.make:102: renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/spirv_gen.cpp.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:404: renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/all] Error 2

make: *** [Makefile:130: all] Error 2
```

## Steps to reproduce

Compile for i686

## Environment

* RenderDoc version: 1.5
* Operating System: Void Linux
* API: ???

**Comment by baldurk** [comment]
32-bit linux is not a supported platform, so for any problems building there you're on your own.

The error indicates that your system doesn't have enough memory to compile. If you can build 64-bit I'd assume you'd be able to build 32-bit as well as I'd expect that to use about the same or slightly less memory, so that may indicate a compiler bug or problem.
