### ISSUE TITLE
Enabling VK_AMD_shader_info extension crashes the application

### ISSUE THREAD

**Issue by onatto** [baldurk/renderdoc#1585]
## Description
Enabling VK_AMD_shader_info extension crashes the application when trying to debug with RenderDoc. RenderDoc doesn't crash.
## Steps to reproduce
Enabling and disabling VK_AMD_shader_info without any changes to the code.
## Environment
* RenderDoc version: 1.5 (6b3dc39b)
* Operating System: Linux 5.0.0-32-generic
* API: Vulkan 1.1.125
* GPU: AMD RX 480 8GB
* Driver: AMDVLK 2.0.117

**Comment by baldurk** [comment]
Your application is behaving invalidly if you are enabling `VK_AMD_shader_info` at all under RenderDoc. You must correctly query to determine what extensions are available before enabling them. When running under RenderDoc the `VK_AMD_shader_info` extension will be removed from the list of available extensions because it is not supported.

If you enable the extension anyway RenderDoc will cause the `vkCreateDevice` call to fail with `VK_ERROR_EXTENSION_NOT_PRESENT` which may lead to a crash in your code if you do not check for error return codes.
