### ISSUE TITLE
Replay API

### ISSUE THREAD

**Issue by mhuzai** [baldurk/renderdoc#1589]
(Wasn't sure where else to ask this question.)

Is there a programming API for the replay functionality? I am trying to replay frames from within an application and was wondering if it would be possible to do so via some function call to renderdoc (as opposed to doing it from the command line).

Thank you!

**Comment by baldurk** [comment]
Yes there is a C++ API for replaying that the UI is built on top of. It's also wrapped in python which is documented online: https://renderdoc.org/docs/python_api/index.html

In future please follow the issue template even for questions like this, otherwise your issue is liable to be closed automatically.

**Comment by pemgithub** [comment]
What is the python equivalent of (renderdoccmd.exe replay foo.rdc)?  Is it OpenCapture()?  Does OpenCapture() do a full replay of the entire frame?  I wasn't clear on this from the doc.  Or is "Display texture in window" the equivalent?  I want to write a simple python script that just replays the entire RDC frame (as close to what it captured as possible).

**Comment by baldurk** [comment]
Please do not comment on old closed issues.
