### ISSUE TITLE
renderdoc replay requires GLSL 4.20 for CS, but tests for ARB_compute_shaders

### ISSUE THREAD

**Issue by gerddie** [baldurk/renderdoc#1591]
## Description

On drivers that support compute shaders but expose only a pre- 4.20 OpenGL version, and hence, a pre-4.20 GLSL version the output is clobbered with error messages from compute shaders that fail to compile: 

```
Error   - GL_COMPUTE_SHADER compile error: 0:1(10): error: GLSL 4.20 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES
0:0(0): error: Compute shaders require GLSL 4.30 or GLSL ES 3.10
```
Culprit is likely that the `#version` tag in the compute shaders is set to `#version 420`  

The trace still replays fine, but some features that should be disabled beforehand are probably enabled now and are likely not working correctly. 

## Steps to reproduce

Capture and replay an OpenGL trace taken on a driver that supports compute shaders but exposes only OpenGL < 4.20. 

## Environment

* RenderDoc version: git-7a436e1463
* Operating System: Gentoo Linux 
* API: OpenGL 

llvmpipe: mesa git-084431ce45
softpipe/r600: mesa 19.1.8 

## Proposed solutions: 

- use the supported GL version too when enabling these features, or  
- base the compute shaders on some older GLSL version (150?) and then also enable the extensions that are additionally needed.

**Comment by baldurk** [comment]
I think the best solution for this is just to ignore implementations that support compute shaders but not at least GL4.2. Looking at [gpuinfo.org](http://opengl.gpuinfo.org/listreports.php?extension=GL_ARB_compute_shader) it seems like there are implementations as old as GL 3.0 that report the extension, but a lot of those look bogus because the hardware should definitely be capable of a newer GL version. I'd guess that mesa's software back ends are the only implementations in this very narrow niche.

Is there a reason you're using mesa software rendering instead of a proper driver? It's stuck on that ancient version of GL and I'm not really interested in supporting old versions of GL except by turning off features and handling everything in as stripped down way as possible, so you're probably going to run into other low-end problems. If you have the option you're much better off running a proper driver.

**Comment by gerddie** [comment]
It is work for the mesa CI: We want to replay traces on different drivers to see that there are no visual changes. The first step here is to use software rendering since it doesn't need any specialized hardware so we can just enable it.

**Comment by gerddie** [comment]
I think for some hardware (at least most r600) it's also fp64 that hinders exposing more than GL 3.3.

**Comment by baldurk** [comment]
As above, GL implementations that can't meet 4.2 are not useful for compute whether or not they report the extension, so I pretend the extension isn't supported.
