### ISSUE TITLE
Structured Buffer hidden counter display

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1593]
## Description

I have a Structured Buffer that has a hidden counter, and I'm using it a bit like an append buffer in a way that I can retrieve the counter using IncrementCounter(). However, in a renderdoc capture I can't see this counter unless it's bound to a drawcall or dispatch. Is there a way to could see the counter in a similar way as the Buffer Contents?

## Steps to reproduce

Bind a structured buffer, call IncrementCounter() on it, now try to visualize it in renderdoc.

## Environment

* RenderDoc version: 1.6 nightly
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
I'm kind of on the fence about this. I see what you mean that there's no way to inspect that data when it's not bound to the pipeline, but I'm kind of loathe to add dedicated UI and plumbing for this API-specific feature that's pretty niche. It would be one thing if there was no way to see the counter value at all, but it is visible in the pipeline state viewer as you say.

Being honest I'm leaning towards saying this is not important enough a feature to merit being added. The counter has never been visible anywhere else and no-one has mentioned this before, so I don't think it's something where there's a huge importance on being able to access that data another way. That's not the only factor, some features are rarely used but worth adding, I'm just not sure this is one of them.

Can you explain what situation you're hitting where you need to see the counter value when the buffer isn't bound? Is this a very important thing to be able to visualise, or is this just something you noticed in passing but you're fine checking the counter value through the pipeline state?

**Comment by redorav** [comment]
Honestly if it's going to be a huge hassle for you I'm probably fine with it not being visible, I thought it may have been a reasonably quick thing to fix. I was implementing the counter feature for something I'm doing and noticed that my count was being lost somewhere in the pipeline (due to a bug), but I couldn't really pinpoint where. 

As I've fixed it already and based on your comment it probably doesn't merit the time and effort you say it would take to implement it. Thanks a lot for looking into it.

**Comment by baldurk** [comment]
Good to know that it's not critical. It's a fair request to make it's just something where the associated costs may outweigh the value it brings. I'm usually pretty strict with myself too where I never remove features even if they cause problems because I find it annoying when I have something I rely on and it's removed from a program. I'd rather not add a feature at all, than add it then remove it because it's not worth the maintenance cost. Hence being careful sometimes about adding new features.

The hassle is that the counter isn't part of the buffer's data so it has to have special handling all the way along the codebase. For buffers in general all APIs have commonalities, and many API differences can be abstracted out in the buffer viewer. This can't though and that leaky abstraction will appear everywhere.

If this were a purely D3D11 tool and I had infinite time, it's something I would probably tackle. But to a certain degree little API quirks like this may not get perfect treatment - hence the counter being passed with the pipeline state instead of as a separate value with special display. There are other cases like shader linkage in D3D11 which isn't handled well at all but since no-one uses it I can get away with that :). With GL for example it has all sorts of weird and nonsensical edge cases that I probably won't ever support.

I'll leave this open for a little while in case I have a bright idea on how to handle it without adding too much cost, but otherwise I will close it.

**Comment by baldurk** [comment]
OK that commit is about as good a solution as I think is reasonable. It tries emulates the behaviour from D3D12 where the counter is explicitly stored in a buffer (which is what D3D11's boils down to, aside from API obfuscation), so each UAV has its own fake 4-byte buffer to contain the counter:

![image](https://user-images.githubusercontent.com/661798/69871439-b2b26f00-12aa-11ea-96f9-893d46f31005.png)

You can then jump to that resource and click 'view contents' and it will bring up the counter value as if it were a 4-byte buffer that's bound:

![image](https://user-images.githubusercontent.com/661798/69871481-d4abf180-12aa-11ea-8e0d-0ce95aaf5037.png)

![image](https://user-images.githubusercontent.com/661798/69871494-decdf000-12aa-11ea-8b2a-4448f536eae4.png)

And then you can view that at any time. It's not perfect and it does kind of "lie" about the API, but hopefully anyone using hidden counters will understand that it's not a real buffer.

**Comment by redorav** [comment]
Nice! I was thinking this was as good as dead, thanks for going the extra mile, it's much appreciated :)
