### ISSUE TITLE
Rebuilded RenderDoc remote server android APK file size is much bigger than original

### ISSUE THREAD

**Issue by spriteuv** [baldurk/renderdoc#1594]
## Description

Hi,
I've followed android apk compiling steps described [here](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md)
and managed to get perfectly working org.renderdoc.renderdoccmd.arm64.apk but file size is different (~69mb) than the same file included with precompiled RenderDoc binaries (~6mb) available for download on RenderDoc website (Latest Release: v1.5 - 9 Oct, 2019)

Am I missing some preprocessor or linking definitions?

## Steps to reproduce

Building for android:
mkdir build-android
cd build-android
cmake -DCMAKE_BUILD_TYPE=Release -DUSE_INTERCEPTOR_LIB=On -DLLVM_DIR=path/to/llvm/install_arm64/lib/cmake/llvm -DBUILD_ANDROID=On -DANDROID_ABI=arm64-v8a ..
make -j8

## Environment

* RenderDoc version: Branch v1.x, commit:  a94f238e37cfe2f142093eb8e5da7775abaa88c6
* Operating System: Windows WSL 
* API: GL

**Comment by baldurk** [comment]
The APKs in all official builds are stripped of symbols which are included in libraries by default, deliberately to save space. This doesn't otherwise affect functionality.

Please note due to the inherent instability and unreliability of the Android platform I cannot give any support for any builds you make. It would be too easy for a problem to be caused by a misconfiguration or compiler bug in your build environment.
