### ISSUE TITLE
[OpenGL] Binding different shaders for different draws in the same program pipeline doesn't show in the UI

### ISSUE THREAD

**Issue by moradin** [baldurk/renderdoc#160]
For the sake of simplicity I'm using one program pipeline and before every drawcall I just bind the necessary shaders in it. I know that this is not the best performance scenario but it works. The only problem is that RenderDoc seems to be caching the content of the program pipeline and it doesn't pick up the changes so when I'm looking at a drawcall that uses the pipeline the shaders are different from the ones that were actually used in the draw.
My current workaround is to delete the pipeline before the draw and recreate it in case I'm using RenderDoc, but it would be great to have this fixed.
I haven't looked into the sources to figure out why this happens.

**Comment by baldurk** [comment]
Yes this is RenderDoc treating glUseProrgamStages as an 'initialisation' type call, so it gets shunted first before the frame replay, rather than happening in-line. Should be an easy fix to just hoist it up so it gets replayed as it happens in the frame, and it will show up in the API calls as well.

**Comment by baldurk** [comment]
Closing as this was fixed for v0.27, although an additional fix is found in v0.28. Re-open if it's not properly resolved.
