### ISSUE TITLE
Failed to run RenderDoc capture

### ISSUE THREAD

**Issue by JingChangzz** [baldurk/renderdoc#1617]
I want to launch an UE4 Android game from RenderDoc on Windows， but failed
![企业微信截图_157484519366](https://user-images.githubusercontent.com/13314441/69708872-5713a480-1137-11ea-9bb0-89311aff8c5e.png)

The apk is development build.
When I seleted Executable Path，RenderDoc eject：
![企业微信截图_157484495463](https://user-images.githubusercontent.com/13314441/69708546-c89f2300-1136-11ea-9f2c-bd3755a39eb2.png)  

-------------------------------------------------
### Environment
------------
- RenderDoc version: 1.5
- Operating System: Windows 10
- Game Runnning System: Android
- Game engine： Unreal 4

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
