### ISSUE TITLE
D3D12: Ability to inspect root signatures

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#1621]
## Description
Root signatures are very important in D3D12 and provide bindings from the shader to the currently bound descriptor sets. RenderDoc only allows you to inspect resource bindings from the pipeline, but it would be handy to also be able to view root signatures. Currently it only shows the size of the blob.
There's a few functions that might be of use to you:
- [D3D12CreateRootSignatureDeserializer](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-d3d12createrootsignaturedeserializer)
- [GetRootSignatureDesc](https://docs.microsoft.com/nl-nl/windows/win32/api/d3d12/nf-d3d12-id3d12rootsignaturedeserializer-getrootsignaturedesc)   

However, I'm not certain if you can obtain the root blob from a created root signature.

## Steps to reproduce
Run a D3D12 app and try to inspect the root signature with the resource inspector.

## Environment
Win10 x64 D3D12

**Comment by baldurk** [comment]
Yes root signatures are possibly the ugliest wart in D3D12. If they were created through a normal set of structs it would be visible in the resource inspector, but since it's an opaque blob that's all you can see.

A proper implementation would require significant custom UI (either in a separate panel or API-specific-type customisations to the resource inspector) just for viewing root signatures. It's not impossible of course, but as with some other feature requests this might not be worth the implementation and maintenance cost.

I think it will be possible I can add an ugly hack to simulate what it would look like if the root signature API wasn't awful and it was created with a proper descriptor instead of a blob. It won't be very user-friendly but at least the information will be accessible in some form.

I know it's not exactly what you're asking for and it seems like you're aware of it anyway, but RenderDoc does show which root signature element each binding comes from which does give you the relevant parts of the mapping:

![image](https://user-images.githubusercontent.com/661798/69799708-bc18da00-11cb-11ea-8c19-d0ef2f653e7d.png)

Which shows a root CBV at element 1, and two SRV tables at elements 2 and 3.

**Comment by Nielsbishere** [comment]
The problem turned out to be because SRV/UAV/CBV descriptor heaps with shader visiblity are GPU only (so you have to copy them from a different heap). Though it would have been handy to be able to see all root signature parameters in the pipeline (and maybe color them differently if they aren't used), to make sure I knew the root signature was correct. 
EDIT: Also, I was aware of that, but some things that are bound in the root signature but not in the final shader aren't shown.

**Comment by baldurk** [comment]
What problem? I don't understand what you're referring to because you didn't describe what you were trying to investigate in the original report, and I'm not sure what shader visible heaps have to do with examining root signature parameters.

RenderDoc can show all parameters in the root signature. By default unused items are hidden, but there is a toggle `Show unused items` in the pipeline state which will show any bound-but-unused items from the root signature.

**Comment by Nielsbishere** [comment]
Sorry, I thought my root signature was invalid since it said it couldn't find resources for the pipeline. I inspected the descriptor heap and it had valid data. Problem was that it was marked as "shader visible" aka GPU access only and so the CreateShaderView didn't do anything, even though it showed up in RenderDoc in the creation info (CPU side had data but was never pushed to GPU).
I never knew that's an option, I'll keep that in mind, that's very nice. Regardless, some time in the future an ability to see root signatures and compare them would be nice nonetheless.

**Comment by baldurk** [comment]
That doesn't sound right, it's definitely valid to call `CreateShaderResourceView` on a shader-visible heap. From [the docs](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-createshaderresourceview):

> `DestDescriptor (Type: D3D12_CPU_DESCRIPTOR_HANDLE)`
>
> Describes the CPU descriptor handle that represents the shader-resource view. This handle can be created in a shader-visible or non-shader-visible descriptor heap.

It sounds like perhaps your application was hitting invalid behaviour somewhere. RenderDoc does not handle validation as that's the domain of the API-specific validation layers.

As mentioned above I'll see if I can hack something to view root signatures, however it sounds like you might want to make sure you're running with API validation. I'm not sure what you mean by comparing them but unless you mean just comparing by eye then that's a separate feature entirely.

**Comment by Nielsbishere** [comment]
Yup, it seemed like it is; but it just didn't send it to the GPU. You have to call CopyDescriptors from a CPU heap to a GPU visible heap. It works now that I do that, but it seems a bit strange to me as well. I am using the validation layer, maybe this is just something they don't report but should; or an invalid driver.

**Comment by baldurk** [comment]
You can't bind a non-shader visible heap to a command list, so if you create your descriptors on a non-shader visible heap then you'll have to call CopyDescriptors. However you can also create the descriptors directly on a shader visible heap and not do any copy at all, that is valid and does work. If you think that it's not working for you then it's likely that your application has a bug and introducing the copy just avoids the bug.

This has nothing to do with the original request and it doesn't sound like a RenderDoc bug, I'm just pointing this out because it sounds like you still don't quite have things right and you might have a bug lurking somewhere.

**Comment by Nielsbishere** [comment]
I understand, but why would the copy get around it? The only thing I do different in the one that works is create a new descriptor heap that is shader visible and copy the one that isn't to it and then release the old one. It's fine if I don't do that step for RTV and DSV heaps, but otherwise it doesn't work for me. Is there a flush I need to call after filling the CPU-visible heap, that is being done by the copy?

**Comment by baldurk** [comment]
It's impossible for me to know without seeing what your code is doing, and as this does not seem to be a RenderDoc bug this issue tracker is not the right place to ask for help debugging your application. I only wanted to let you know that you were under the mistaken impression that it was impossible to create descriptors directly on a shader visible heap. No copy is necessary, so whatever is going wrong must be something else.

**Comment by baldurk** [comment]
That commit adds a fake extra parameter to the details of CreateRootSignature which contains the unpacked/decoded blob, which allows root signature inspection:

![image](https://user-images.githubusercontent.com/661798/69873087-4b4aee00-12af-11ea-8c5e-3b4b70cbf58d.png)

**Comment by Nielsbishere** [comment]
Amazing, looks good!
