### ISSUE TITLE
Blank FBO Textures

### ISSUE THREAD

**Issue by timangus** [baldurk/renderdoc#1623]
## Description

I'm trying to debug a particular issue in the application which I develop (Graphia). RenderDoc seems like the ideal tool to help me out, but when I use it I find that texture data is not captured for a particular part of my frame. The correct size and configuration of the FBO is found, and if I turn the wireframe overlay on, I see the correct geometry, but the textures themselves are blank; all values are zero. I'm not sure if I'm doing something wrong, or if RenderDoc is at fault. It's very difficult to tell. Any help greatly appreciated!

## Steps to reproduce

1. Download Graphia: https://kajeka.com/graphia/download
2. Sign up for a 30-day trial (sorry!, alternatively send me your email and I'll manually create an account.)
3. Run Graphia.AppImage --appimage-extract
4. Run RenderDoc on squash-root/usr/bin/Graphia
5. In Graphia (if not already showing) start the tutorial by going to Help -> Show Tutorial...
6. In RenderDoc, capture a frame
7. Click and drag the main display in Graphia to generate a frame
8. Observe lack of texture data in RenderDoc

![Screenshot from 2019-11-29 13-43-19](https://user-images.githubusercontent.com/3159586/69873289-d926d900-12af-11ea-873b-751564e02c44.png)
![Screenshot from 2019-11-29 13-43-49](https://user-images.githubusercontent.com/3159586/69873298-e17f1400-12af-11ea-8e52-bca28db499a1.png)

## Environment

* RenderDoc version: 1.5
* Operating System: Ubuntu 18.04
* API: OpenGL

NVidia hardware, latest drivers. Same thing happens on Windows FWIW (also NVidia).

**Comment by baldurk** [comment]
This was an issue with the allocation of the depth texture, it was created with `glTexImage2DMultisample` and an old-style unsized `GL_DEPTH_COMPONENT` format. RenderDoc internally uses direct-state-access functions to avoid polluting state, but there's no DSA variant of `glTexImage2DMultisample` so instead it uses `glTextureStorage2DMultisampleEXT`. However the modern storage texture functions require a sized format, so that commit picks a sensible default sized format instead and uses that.

GL is messy :(.

**Comment by timangus** [comment]
Cool, looks to be working now with a HEAD build. Thanks for fixing it so quickly!
