### ISSUE TITLE
libEGL not available

### ISSUE THREAD

**Issue by JingChangzz** [baldurk/renderdoc#1624]
## Description

I open android capture file(*.rdc) with error today
![企业微信截图_15751071979376](https://user-images.githubusercontent.com/13314441/69898843-609c4700-1399-11ea-94a5-924582780803.png)

And I check the log:
![企业微信截图_15751073526704](https://user-images.githubusercontent.com/13314441/69898880-f506a980-1399-11ea-9c39-5de8e8fc1d5b.png)

Can you give me some advices to solve  this problem?
It was ok to open the same rdc file yesterday in the same renderdoc tool……

## Environment

* RenderDoc version: 1.5 win x64
* Operating System: win10
* API: XXX

**Comment by baldurk** [comment]
You're opening a capture created by an android device on windows. This is not supported and is likely to fail, and you will have received a message explicitly telling you that it was made on an android device and prompting you to select a remote replay context. Make sure that you open an android capture on the android device it was made to ensure compatibility.

Please note for the future that when filing a bug report the 'steps to reproduce' section is not optional. You must fill it out with steps I can take to reproduce the bug, otherwise in most cases I cannot help. In future any bug reports you create that do not properly follow the issue template will be closed.
