### ISSUE TITLE
Possibility to clear an output at different points

### ISSUE THREAD

**Issue by moradin** [baldurk/renderdoc#164]
Since I write every pixel in the render pipeline, I only clear the depth at the beginning of the frame. The result is that while debugging the drawcalls I get the content of the previous frame step by step overwritten by the current frame. It would be great if I could clear the target in RenderDoc at the beginning of the pass. It would also be useful to clear the buffer before the selected drawcall, this would allow checking one draw in isolation.

**Comment by baldurk** [comment]
I'd like to clarify a bit what you need here and what the current behaviour is.
By default unless 'save all initials' is enabled on capture, renderdoc will skip saving the previous frame's data in render targets that it thinks are going to be entirely overwritten. There's no way to verify this for sure, currently it goes by whether writes to a full-viewport happen before any reads. 

This is mostly to avoid costly restores and a load of wasted space in the capture file, but it would give you the results you're looking for - the previous frame wouldn't show up in those RTs. I guess that's not happening for you? (Actually it just occurred to me - IIRC you're capturing GL where I haven't implemented this optimisation yet, so that might explain this).

The other thing is you say you'd want to clear the target before the beginning of the pass, or even the current drawcall. The latter would probably be easier actually as it could be implemented the same way as the overlays (like highlight drawcall/wireframe/etc). Clearing before the current pass would be a bit harder. The only thing I could do automatically would be to clear the render target whenever it was last bound before this drawcall, but that might not always be what you want. Otherwise, there needs to be some way to identify what the current pass is.

The other thing is you say you'd want to clear the target before the beginning of the pass, or even the current drawcall. The latter would probably be easier actually as it could be implemented the same way as the overlays (like highlight drawcall/wireframe/etc). Clearing before the current pass would be a bit harder. The only thing I could do automatically would be to clear the render target whenever it was last bound before this drawcall, but that might not always be what you want.

**Comment by moradin** [comment]
Indeed I'm using RenderDoc mostly with GL and I see the content of the previous frame in the buffer. The overlay idea for the drawcall is nice and would be good to have. By pass I meant a collapsed range in the tree of drawcalls, RenderDoc calls them passes so I tried to use this terminology. If it's easier to implement maybe another overlay mode could be added that would render everything that is in the current pass or alternatively since the last time the inspected rendertarget was bound.

**Comment by baldurk** [comment]
So having the GL backend do skip large unneeded textures is sort of independent, it shouldn't be something we rely upon for this kind of feature. Especially since this might be useful even if you did select 'save all initials' on capture.

I've added two overlays, one which clears immediately before the current draw, and one that clears the last time the bound targets changed (which, note, is not *quite* the same as the auto grouping in the event browser, but is similar). It doesn't clear depth because it's hard to tell if the depth should be cleared to 0 or 1 for correct rendering, and any way I think it makes more sense to see the draws with correct depth testing but isolated.

**Comment by moradin** [comment]
I tried this quickly, the clear before pass works beautifully, but the clear before draw doesn't seem to work at all.

**Comment by baldurk** [comment]
Whoops. Should be working better now :).

**Comment by baldurk** [comment]
Closing as this was implemented for v0.27. Re-open if it's not properly resolved.
