### ISSUE TITLE
Loading 3D App after injecting into Chrome leads to crash

### ISSUE THREAD

**Issue by olie304** [baldurk/renderdoc#1641]
Diagnostic Log: https://gist.github.com/olie304/8440a622ca1c6abfa12635caaecfc501

I launch Chrome with the flags `--disable-gpu-sandbox --gpu-startup-dialog --use-angle=gl`
I tried specifying DX11 and DX12 Angles but it had the same result.
Injecting into Chrome is fine and gives no errors but as soon as I load a web page that loads 3D content (e.x. https://3dviewer.net/) RenderDoc disconnects and Chrome starts a new GPU process

## Environment
* RenderDoc version: v1.5
* Operating System: Windows 10
* GPU: RTX 2080 Ti
* API: All of them

**Comment by baldurk** [comment]
Injecting into processes can regularly fail for many reasons and is not directly supported. It's provided as an advanced feature for those who know what they are doing is safe.

In addition due to high numbers of people using RenderDoc with chrome for illegal copyright infringing uses I provide absolutely no support for capturing WebGL this way. RenderDoc is intended for debugging your own programs directly and debugging chrome does not qualify. I'm closing this and will not help with any similar issues.
