### ISSUE TITLE
Add export to Amber option

### ISSUE THREAD

**Issue by dj2** [baldurk/renderdoc#1649]
There have been a few requests to Amber (github.com/google/amber) to add an export option to RenderDoc to generate an AmberScript file which reproduces a rendering issue found in RenderDoc.

I'm not familiar with the internals of RenderDoc or how it would work from your side, but happy to help from the Amber side if there are questions or needed features.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
