### ISSUE TITLE
Stencil values for selected pixels always show 0 / 0x00

### ISSUE THREAD

**Issue by moradin** [baldurk/renderdoc#165]
I tested this only with GL but it looks like the values shown for stencil textures get lost somewhere. The texture looks correct when visualized but the exact value is always 0 / 0x00.

**Comment by moradin** [comment]
Also, binding the stencil texture with a view created like this:
glTextureView( view, GL_TEXTURE_2D, depthTexture, GL_STENCIL_INDEX, 0, mipCount, 0, sliceCount );
results in a fully black texture shown in the inputs section. When selecting pixels on this texture the stencil value seems to be returned as depth resulting in some weird depth values. I tried switching the depth/stencil radio buttons but it had no effect.

**Comment by baldurk** [comment]
I wouldn't be surprised if stencil-only textures are broken, I don't think I've tried that before.

What's the texture in the first case (the original comment)? Is it depth-stencil or just stencil? Can you give me the format and how you created it like with the glTextureView call so I can try and repro locally.

**Comment by moradin** [comment]
I was confusing in my wording so sorry for that, in all cases mentioned I'm using depthstencil textures and not stencil only ones. The texture has DEPTH24_STENCIL8 format to be exact.
The first one is happening when looking at the stencil channel of such a texture (with the radiobutton toggle). The second one is happening when looking at a texture view that is created based on the depthstencil texture with the code pasted above.
I don't have the code for the creation of the depthstencil texture right now at hand but it's very much just standard texture creation with this format.

**Comment by baldurk** [comment]
Ah yeh, when I said stencil-only textures, that's how the glTextureView will appear, since its internal format is GL_STENCIL_INDEX. It's roughly equivalent to creating a texture with glTexStorage et al with a stencil-only format.

Maybe stencil viewing has just broken, I'll check. It did work at one point but might have gotten busted along the line.

**Comment by baldurk** [comment]
I can't really repro this one, created a simple app to render a triangle to DEPTH24_STENCIL8 buffer, then read back from it, and it works fine in both cases:

![stencil values](http://bdrk.eu/f/Q6WTQ/Screenshot%202015-10-25%20133401.png)

![stencil readback](http://bdrk.eu/f/P7lgQ/Screenshot%202015-10-25%20134859.png)

Note that I had to make my glTextureView of format DEPTH24_STENCIL8 as well and set `glTextureParameteri(view, GL_DEPTH_STENCIL_TEXTURE_MODE, GL_STENCIL_INDEX);` to read back, otherwise I got driver crashes. Are you sure it's valid to alias a depthstencil texture as just stencil? Reading up on it, it seems like really you want to make a view of the same type, and set the read mode as above.

**Comment by moradin** [comment]
I'm not sure if it's according to the standards but it's not only not crashing for me but it also seems to work properly. I also have a mini unit test kinda thing to verify these features and when reading the stencil values from the view then I get back the expected values. It's extremely hard to find info on proper usage of stencil buffers as textures in GL for some reason so I'm not sure if I'm just lucky or the drivers should actually support this case.

**Comment by baldurk** [comment]
Yeh I know what you mean :(. If it works for you then fair enough - I think the changes I made in c7cfdcc might work for you then, since I tested them on 'real' stencil-8 textures, they might work for views as well. I saw the behaviour you were describing where the depth seemed to have values in it instead of stencil.

My understanding of glTextureView is that it's a raw re-interpretation of the bits, so you have to have a view that's the same size (the spec specifically has a list of equivalent formats of same bit-size, see table 8.22 in the GL 4.5 spec).

Also if I understand right, you were still not getting any picked pixel values even without the STENCIL_INDEX8 view anywhere in the picture, just with a normal DEPTH24_STENCIL8 texture as FBO attachment? Can you give me any more information on how to repro that, because it seemed to work for me. I'm particularly suspicious if you say that the visualisation of the stencil is correct because the pixel picking works by just doing the same visualisation render to a F32 buffer and reading back from it.

**Comment by moradin** [comment]
I just grabbed the latest code and tried to reproduce these problems. As far as I can tell things are a bit more consistent now but not exactly the way I expected. So here are some shots from my minimal test

![renderdoc_stencil](https://cloud.githubusercontent.com/assets/7690658/10724798/8e11415e-7bc7-11e5-8bea-1f43b23e5513.PNG)

Here you can see that I'm rendering into a depth-stencil texture with the mentioned format and I switched to the stencil view, changed the range of values to some really tiny range and now I see that there is a stencil value written in the buffer. At the same time you can see that I selected a pixel and I get a valid depth value but no stencil at all.

![renderdoc_stencil_texture](https://cloud.githubusercontent.com/assets/7690658/10724883/1f2c1556-7bc8-11e5-81d2-92e38ae30b8a.PNG)

A few drawcalls later, trying to use the stencil buffer through the created view I see no valid stencil values even after modifying the range (the depth/stencil radio button doesn't change anything in this case) and I get invalid depth values for the selected pixel.

**Comment by baldurk** [comment]
That commit there might at least change the results you're getting with the texture view. I didn't realise you were using an unsized format.

Something's definitely weird though, the fact that you need to make that range tiny explains why the values are coming back as 0 / 0x00 and suggests that something somewhere is broken. The stencil range '0 - 1' is mapped to 0-255 (not ideal I know, but it seemed the most sensible way of doing things), so as soon as your range is 0 - 0.00392 then you should be able to see stencil very clearly, since that will show stencil value 1 as 1/255, so full white in that range.

I'll follow up via email since this will probably need some more debug logging :).

**Comment by baldurk** [comment]
I believe this one was resolved over email and it worked as of v0.27. Re-open if you're still having issues.
