### ISSUE TITLE
[D3D12]CommandList->Close gives E_INVALIDARG with RenderDoc attached

### ISSUE THREAD

**Issue by cippyboy** [baldurk/renderdoc#1655]
This is my own engine, which works well without RenderDoc, but with RenderDoc attached, CommandList->Close throws E_INVALIDARG which is rather weird because Close() doesn't have any parameters. However the flow of my app may be weird because I initially close a command list that may have no commands in it ! I can provide a build of my app if someone wants to reproduce this. PIX for Windows works fine btw.

* RenderDoc version: 1.5
* Operating System: Windows 10 2004
* API: D3D12
RTX 2060, latest driver

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
