### ISSUE TITLE
Problem replaying frames with shadow effects

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1656]
## Description
When I open the game's shadow feature to capture the frame, and then play back, it will appear that the playback result is not consistent with the actual.

An error occurred here
ADRD 032444: [18:49:04]     gl_resources.cpp( 462) - Error   - Unhandled Base Format case GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC!

But this error is not the cause of the problem, I modified the error and the problem still exists.
[RenderDoc_2019.12.25_10.45.46.log](https://github.com/baldurk/renderdoc/files/3999461/RenderDoc_2019.12.25_10.45.46.log)

## Environment

* RenderDoc version: nightly v1.x branch @ a9a2c3e3, 2019-12-23
* Operating System: Android
* API: opengles

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
