### ISSUE TITLE
Couldn't find module 'renderdoc.dll' (possible duplicate, have repro)

### ISSUE THREAD

**Issue by asylum2010** [baldurk/renderdoc#1661]
## Description

RenderDoc fails to inject into a specific (multithreaded) sample program. Note that context sharing is not enabled atm. (my mistake), but fixing it doesn't resolve the issue.

## Steps to reproduce

The problematic sample is 51_MultiThreading:

https://github.com/asylum2010/Asylum_Tutorials

## Environment

* RenderDoc version: 1.5
* Operating System: Windows 10
* API: OpenGL

I debugged the RenderDoc source and it seems that the InjectDLL() function fails.

**Comment by baldurk** [comment]
The application in this case seems to be broken. You have a manifest declaration to enable visual styles using MS common controls:

```
#pragma comment(linker, "/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='x86' publicKeyToken='6595b64144ccf1df' language='*'\"")
```

Note particularly the `processorArchitecture='x86'` declaration, while the program is configured to build for x64.

This seems to run fine because you're not using any common controls so the DLLs never get loaded, however RenderDoc uses e.g. `GetOpenFileNameW` which means `comdlg32.dll` gets loaded, redirected to the common controls, and then fails so `renderdoc.dll` fails to load.

If you add a snippet to main like this to call `GetOpenFileNameW` in your program, it fails to run entirely:

```cpp
  {
    OPENFILENAMEW ofn = {sizeof(OPENFILENAME)};
    wchar_t outBuf[MAX_PATH * 2] = {};

    ofn.lpstrTitle = L"Title";
    ofn.lpstrFilter = L"All Files\0*.*\0";
    ofn.lpstrFile = outBuf;
    ofn.nMaxFile = MAX_PATH * 2 - 1;

    GetOpenFileNameW(&ofn);
  }
```

![image](https://user-images.githubusercontent.com/661798/71839936-37678880-30b4-11ea-9b69-d0ec4d0f0efc.png)

Fixing the manifest declaration to `processorArchitecture='amd64'` or building in 32-bit seems to allow RenderDoc to inject as normal.
