### ISSUE TITLE
[dx11/dx12] Couldn't find matching frame capturer

### ISSUE THREAD

**Issue by obfuscate** [baldurk/renderdoc#1670]
## Description
So, a little bit the background: I want to add an opportunity to capture a frame from my application (press a button, then capture frame and open UI using render doc API).

I took a simple application (imgui_impl_dx11/12.cpp for example) and wrote the next code.
Because SetActiveWindow fails RenderDoc doesn't capture frame and UI shows that there isn't active API (I used both TriggerCaptureFrame and Start/EndFrameCapture).
## Steps to reproduce

```
static RENDERDOC_API_1_4_0*         g_rdocAPI = NULL;
...
// Create device here.

//-- Here I tried to use both from the installed and compiled renderdoc dlls.
HINSTANCE hGetProcIDDLL = LoadLibrary(L"renderdoc.dll");
if (hGetProcIDDLL)
{
    HMODULE mod = GetModuleHandle(L"renderdoc.dll");
    if (mod)
    {
        pRENDERDOC_GetAPI RENDERDOC_GetAPI =
            (pRENDERDOC_GetAPI)GetProcAddress(mod, "RENDERDOC_GetAPI");
        int ret = RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_4_0, (void**)&g_rdocAPI);
        assert(ret == 1);

        g_rdocAPI->SetCaptureFilePathTemplate("../../RenderDoc/capture");

        g_rdocAPI->SetCaptureOptionU32(RENDERDOC_CaptureOption::eRENDERDOC_Option_CaptureCallstacks, 1);
        g_rdocAPI->SetCaptureOptionU32(RENDERDOC_CaptureOption::eRENDERDOC_Option_CaptureAllCmdLists, 1);
        g_rdocAPI->SetCaptureOptionU32(RENDERDOC_CaptureOption::eRENDERDOC_Option_SaveAllInitials, 1);
        g_rdocAPI->SetCaptureOptionU32(RENDERDOC_CaptureOption::eRENDERDOC_Option_APIValidation, 1);

        g_rdocAPI->MaskOverlayBits(RENDERDOC_OverlayBits::eRENDERDOC_Overlay_None, RENDERDOC_OverlayBits::eRENDERDOC_Overlay_None);

        //-- Here I got the message: "Couldn't find matching frame capturer ..."
        g_rdocAPI->SetActiveWindow(device, hwnd);
    }
}
```

Yeah, I read the [issue](https://github.com/baldurk/renderdoc/issues/1556) and the way "open renderdoc, launch your app from rdoc and then it will work" looks not fine.
That's why I have the question: Is here an opportunity to use a specific dll via LoadLibrary (for example, from the installed directory of rdoc or compiled version of rdoc) and force capture frames RenderDoc?

## Environment

* RenderDoc version: 1.5.
* Operating System: Win10.
* Graphics API: DX11, DX12 (GPU NVidia GeForce1070).

* Also I have tried to use a compiled version of RenderDoc (https://github.com/baldurk/renderdoc/commit/a94f238e37cfe2f142093eb8e5da7775abaa88c6 | https://github.com/baldurk/renderdoc/tree/v1.5).

**Comment by baldurk** [comment]
You cannot inject RenderDoc after initialising a graphics API, it's way too late by that point. Your code as described will never work.

If you are manually injecting you must load renderdoc as early as possible - the first line of `main()` is the best but even then that might be too late depending on what your code is doing, which is why it's strongly recommended that you don't try to load the DLL manually and instead launch your program through RenderDoc to ensure the injection works correctly and then use `GetModuleHandle` to detect the DLL and load the API from there.

You said that launching through RenderDoc "looks not fine" but I don't know what that means - if that doesn't work then please open an issue with repro steps I can follow.

**Comment by obfuscate** [comment]
> If you are manually injecting you must load renderdoc as early as possible - the first line of main() is the best

I'll try it, thanks!

> You said that launching through RenderDoc "looks not fine" but I don't know what that means

So, there are a few points:
- The first: it isn't too comfortable to start render doc, then press "load last setting", then launch the app via renderdoc, because, for example, I start the app in debug mode from Visual Studio.
- The second issue is integration looks redundant, because I have launched rdoc and might just press the button "capture frame" in its UI. In this case I don't see necessity to integrate it in the app.

I want to have an opportunity to start my app in any suitable way for me, then just press a button from my UI and capture a frame.

**Comment by baldurk** [comment]
It's ultimately up to you what you want to do, but if you are loading renderdoc yourself like this and you encounter problems then you are on your own. There is a reason that it is not supported and that's because it's difficult to guarantee that the hooking was successful and it's easy to mess up and cause unexpected problems.

The renderdoc in-application API is not designed as a time-saving device because the steps required to launch an application through renderdoc are already very simple. It allows customisation of the hooking such as removing the renderdoc overlay and providing a way in your application to trigger a capture on a button press. It's also critical if your workload can't easily be captured between two presents and you want to specifically control what region is captured. If that's not necessary for you then perhaps you don't need to use the API at all.

**Comment by obfuscate** [comment]
Well, I'll keep it my mind, thank you!
