### ISSUE TITLE
lack some gl extensions when launch from renderdoc

### ISSUE THREAD

**Issue by zhaijialong** [baldurk/renderdoc#1676]
## Description

We are using a OpenGL ES 3.2 context on PC which is created with `WGL_EXT_create_context_es2_profile`, it does support `GL_NV_sRGB_formats` on nvidia gpu. We checks that extension before load BC1/2/3 srgb texture. When launch from renderdoc, the extension doesn't exist, is that a expected behaviour or unimplemented feature ?

## Environment

* RenderDoc version: 1.5
* Operating System: Windows 10
* Graphics API: OpenGL ES 3.2
* GPU : RTX 2080 Ti (441.66)

**Comment by baldurk** [comment]
RenderDoc removes extensions which are unsupported from the extension queries. It also generally does not support vendor-specific extensions unless they are extremely trivial or widespread and commonly required.

This extension is neither since it adds new enum variants for existing formats as well as adding luminance variants, so it is not planned to be supported. OpenGL ES is generally only used on mobiles, since on PC proper OpenGL is available, meaning that NV extensions for GLES are a niche case.

**Comment by zhaijialong** [comment]
ok，thanks for your answer
