### ISSUE TITLE
Thread started by RENDERDOC_InitGlobalEnv() may outlive the main thread and lead to crashes

### ISSUE THREAD

**Issue by alexv1n** [baldurk/renderdoc#1685]
##  Description

renderdoccmd crashes on Linux-based systems when performing simple commands like 'thumb' or 'extract'. The problem lies with the fact that all the command's Execute method calls RENDERDOC_InitGlobalEnv() which starts a new thread which call into graphics driver to enumerate devices and whatnot.

The main thread may process and quit quickly since extracting a thumbnail or section of .rdc file could be relatively fast operation, compared to all the work that the thread started from RenderDoc::ProcessGlobalEnvironment() is doing.

When the main thread finishes before the secondary one, C++ runtime starts executing global destructors. Some GPU drivers might have global C++ objects as well and while main thread call global destructors, the secondary thread might still be running and still use those globals, leading to segfaults.

Technically, we should probably wait for that thread to terminate before exiting renderdoccmd. So, calling RenderDoc::SyncAvailableGPUThread() before exit would solve the problem but it is not available through public API at the moment.

## Steps to reproduce

execute the following command (reproduced on Stadia platform):

> renderdoccmd extract --section=renderdoc/internal/exthumb --file=exthumb.bin frame.rdc

## Environment

* RenderDoc version: 1.6 (commit 9ff7b04f6fa3ae5cb54ebd84a73fe3de2ea940a2)
* Operating System: Stadia
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I think I might have trouble reproducing this, could you test a fix of calling `RenderDoc::SyncAvailableGPUThread()` as you suggest, in `RenderDoc::~RenderDoc()` ? That's where other global destruction happens but due to destructor order it might be too late.

**Comment by alexv1n** [comment]
I'm going to try this, but this might cause issues on Windows since `RenderDoc` class is a global singleton, it will be destroyed when global destructors are called, effectively during `DllMain` stage which is serialized in kernel and other threads might be waiting on a lock to receive their `THREAD_DETACH` notifications. The current code in `RenderDoc::~RenderDoc()` also has a comment referring to this same issue when shutting down `m_RemoteThread`. I will try calling `SyncAvailableGPUThread()` in destructor and see what happens but I'm afraid it might deadlock on Windows from time to time.

**Comment by baldurk** [comment]
That's a good point. We might get away with it because that comment is about the capture-time thread in the injected application and the available GPU thread only runs on replay, but you're still right though that it's not safe regardless.

It might be time then to bite the bullet and have two separate shutdown paths, one implicit in a global destructor when capturing (since we can't get a nice function call before shutdown when injected into an application), and one explicit when replaying. _Most_ of the shutdown we need to do is replay only and can be explicit, but I've hoped to avoid it since I'm a little worried about bugs creeping in when having multiple paths like that.

**Comment by alexv1n** [comment]
I've been running `renderdoccmd extract` on Windows with the fix for past half-hour in a loop and so far it seems to be Ok. No deadlocks so far. Will need to do similar testing on Stadia to confirm it actually addresses the main issue. Will keep you posted

**Comment by alexv1n** [comment]
Well, unfortunately this does not fix the issue. The problem is the order of destruction is reverse of the order of construction for the global objects. The sequence of events that happens is as follows:

- `RENDERDOC_InitGlobalEnv()` is called which calls `RenderDoc::ProcessGlobalEnvironment()`, creating an instance of global RenderDoc if it wasn't created already.
- that spawns a new thread which makes some calls into a GPU driver. The driver might create and initialize a C++ global object which is actively being used on the background thread as calls to APIs like `EnumeratePhysicalDevices`.
- while the second thread is still busy enumerating devices and doing other things in the driver, the main thread finishes and goes into cleaning up global C++ objects
- Since driver's global object was created after `RenderDoc` instance, it will be destroyed first, and, since the secondary thread is still actively using that object this leads to a crash before `RenderDoc::~RenderDoc` has a chance to run.

I guess we'll have to add some RENDERDOC_SyncAvailableGPUThread() or something... Any suggestions?

**Comment by baldurk** [comment]
Rats, well that puts the nail in that coffin I think. The solution will have to be more general than `SyncAvailableGPUThread()` because that's only the thing which has hit this issue first, in general we shouldn't be relying on global destructors to do shutdown because it can lead to problems like this. There have also been issues in the past with other global singletons being destroyed before the `RenderDoc` instance is destroyed, which have been worked around but not truly fixed.

I think I'll have to split up the shutdown path. During capture we have no other choice than to use the destructor, so it'll need to just be very careful of what gets done to ensure the best chance of staying safe and shutdown only those things needed for capture. On replay we'll have an explicit shutdown function that any replay application is expected to call (an equivalent to `RENDERDOC_InitGlobalEnv()` essentially) before exiting `main()`. That will do any work that's replay time only and can happen safely before we start hitting global destructors.

It will just take a bit of care to ensure that nothing gets shut down twice, or not at all :).

**Comment by alexv1n** [comment]
Another thing that caught my eye was your earlier statement that "the available GPU thread only runs on replay". That got me thinking, why am I crashing in "thumb" and "extract" commands. Why does it even go into enumerating GPUs. But then after looking, GlobalEnvironment::enumerateGPUs defaults to true unless explicitly overridden by a specific command. But that flag is reset to `false` in `renderdoccmd()` function and only turned back on in `RemoteServerCommand::Execute`.

So, I wonder why we even start that thread for commands like EmbeddedSectionCommand. The call stack for GPU thread is as follows:

```
Threading::CreateThread(std::__1::function<void ()>) renderdoc/os/posix/posix_threading.cpp:266:13
RenderDoc::ProcessGlobalEnvironment(GlobalEnvironment, std::string const&) renderdoc/core/core.cpp:516:26
RENDERDOC_InitGlobalEnv renderdoc/replay/entry_points.cpp:267:21
EmbeddedSectionCommand::Execute(cmdline::parser&, CaptureOptions const&) renderdoccmd/renderdoccmd.cpp:1024:5
renderdoccmd(GlobalEnvironment const&, std::string&) renderdoccmd/renderdoccmd.cpp:1336:27
renderdoccmd(GlobalEnvironment const&, int, char**) renderdoccmd/renderdoccmd.cpp:1355:10
main renderdoccmd/renderdoccmd_ggp.cpp:207:13
```

But then I figured out that our copy of RenderDoc doesn't have GlobalEnvironment::enumerateGPUs flag yet (added in commit e6627542cf0d3b78f97f11b6b5086712fd152b5b).

So, I guess this specific issue that we have will be solved by just merging in latest changes from upstream. The underlying problem of race between shutting down the main and any secondary threads is still there but will be less of a problem for now.

**Comment by baldurk** [comment]
Yeh the undefined destruction order is still a problem but that will at least side-step the issue for you in those commands.

**Comment by alexv1n** [comment]
I can confirm that by cherry-picking commit e662754 we can side-step the issue on our platform for now.

**Comment by baldurk** [comment]
As discussed I've added an explicit replay shutdown function that needs to be called before program shutdown, to do any shutdown work that shouldn't be left for global destructors.

**Comment by alexv1n** [comment]
Thanks!
