### ISSUE TITLE
Dark theme still have white events in event browser

### ISSUE THREAD

**Issue by krupitskas** [baldurk/renderdoc#1686]
Hello.
I have a weird behavior with renderdoc in a dark theme.

It looks like this.
![image](https://user-images.githubusercontent.com/5683877/72586451-e0a74d80-3902-11ea-88d0-a00507006d84.png)

I've noticed that white color only applied to groups, as you can see single draw calls or single markers are dark.

RenderDoc version: v1.6 build from https://github.com/baldurk/renderdoc/commit/0e7f772596035137416be01766c2d61205efc63e
Operating System: Windows 10 Enterprise 1809
Graphics API: DirectX 11

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by AlexP-EpicGames** [comment]
FYI if you see bright background colors in the Event Browser even when using the dark theme - this is likely the colors from the Event Markers.  You can turn of `Apply Marker Colors` in **Settings > Event Browser** alternately, you could consider modifying `QVariante::data()` in EventBrowser.cpp to set the alpha to 128 when using the dark theme, but that might make it difficult to identify markers by color if you are using white and gray.
```
            if (role == Qt::BackgroundRole || role == RDTreeView::TreeLineColorRole)
            {
              if (IsDarkTheme())
              {
                col.setAlpha(128); // avoid bright colors
              }
              return QBrush(col);
            }
```
