### ISSUE TITLE
Inspecting StructuredBuffer multiple times displays different values

### ISSUE THREAD

**Issue by axellew** [baldurk/renderdoc#170]
When Inspecting a StructuredBuffer from the Output Merger in Pipeline State, it show different data values every time it's opened. 
![bad values](https://cloud.githubusercontent.com/assets/2884950/12266120/a5a401d2-b941-11e5-9330-193748cdbbd4.png)

**Comment by baldurk** [comment]
If this is an append buffer, likely this is due to the inherent non-determinism in the append operation - each time it is run the order will be different due to GPU scheduling, threads running faster or slower, etc.

If you open the buffer twice without doing anything else, I can probably fix that (so it will return the same results), but this is not too useful. As soon as you do anything that will require RenderDoc to replay the frame again, the shader will be re-executed and the results will be different again.

**Comment by axellew** [comment]
I'm using IncrementCounter() in the code, I wasn't sure how RenderDoc calculated the buffers and if it's replayed every time this makes sense that the non-determinism would do this and the data doesn't really make any sense. Thank you for the help.
