### ISSUE TITLE
Cant launch application

### ISSUE THREAD

**Issue by andre-ferreira** [baldurk/renderdoc#1700]
## Description

Hello @baldurk , this issue is related to #1464, which is still unsolved from my side.

When trying to launch an app trough the renderdoc my program opens and then crashes without even entering the main() function.

## Steps to reproduce

1. Launch the exe in renderdoc normally.
2. The command line will open and close immediately.

If a debugger delay is used then the debugger will crash with the following info:

![73121169-fbb33680-3f6e-11ea-8820-d31c56b65146](https://user-images.githubusercontent.com/5160177/73168187-42c93500-40f1-11ea-8cda-e137adebc035.png)

## Environment

* RenderDoc version: 1.6
* Operating System: Windows 10
* Graphics API: OpenGL
* Graphics Card: Nvidia 940m latest driver and AMD 5700XT, latest driver as well

I have sent you the exe and the required dlls to your gmail. I modified it to display a message ("Entered main") in the first line of the main function, so if you see it it means it successfully entered the main function, it wont do anything afterwards (infine loop) because it would require a lot of asset files.

Thanks for your time Baldur!

**Comment by baldurk** [comment]
This looks like it is an MSVCRT bug. Your program links against the static CRT, and you also use a coroutine library which defines a global `thread_local` variable containing C++ objects which need to be `new` 'd. That causes initialisation code to run whenever a new thread is created to allocate some memory, but if a DLL (such as RenderDoc's injected DLL) creates a thread before `main()` has run then the CRT hasn't initialised global objects and the call to `malloc()` fails.

Testing with the same coroutine library, I find that compiling with the dynamic CRT instead of static CRT works correctly. I can only suggest that you change to using the dynamic CRT - even if temporarily on a separate build when you need RenderDoc compatibility. Unfortunately there is no way for me to only inject RenderDoc's DLL after main has 'sufficiently run' to initialise a static CRT without also risking missing some code that needs to be hooked. Really this needs to be fixed in the CRT by ensuring that thread-local variables can be initialised before `main()` even with the static CRT.

This isn't unique to RenderDoc - it seems like blender ran into the same kind of thing with `opengl32.dll` and filed an issue: https://developercommunity.visualstudio.com/content/problem/672664/race-condition-on-g-tss-mutex-with-static-crt.html
