### ISSUE TITLE
VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM texture viewer U and V channels are the same

### ISSUE THREAD

**Issue by tambry** [baldurk/renderdoc#1710]
## Description
A YUV texture of format `VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM` when inspected is always greenscale.

Observations:
* Disabling both U and V channels results in a grayscale picture, as expected.
* Having either U or V channel enabled results in a greenscale picture. Unexpected for V.

Maybe both U and V enable the display of the U plane?

## Steps to reproduce
1. Capture a frame from the sample
2. Open the frame
3. Inspect the `FS0[0]` input of `vkCmdDraw(4, 1)` in `Colour Pass #1`
4. Try unchecking either of the U/V channels or both. Observe the results.

## Sample
[rd #1708.zip](https://github.com/baldurk/renderdoc/files/4157699/rd.1708.zip)
Same as in #1708.

## Environment
* RenderDoc version: da3bd8dbcb05f8686c527b227d633fd0aa2c0744 + [#1708 patch](https://github.com/baldurk/renderdoc/issues/1708#issuecomment-581965564)
* Operating System: Debian Unstable
* Kernel: `Linux 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19)`
* Graphics API: Vulkan
* Driver: Mesa 19.3.3 RADV
* Graphics card: AMD RX 5700

**Comment by baldurk** [comment]
I found a bug that the plane parameters for this format in particular were misconfigured. It lead to the U and V planes being completely black and reading zeroes including in pixel picking, so you only ever got to see the Y plane when it was enabled. It also meant the YUVA decode view was broken and displayed green as well.

This sounds like it matches up to what you're describing but I'm a little unclear if you were seeing something different, you don't mention U and V being black/empty you say they're the same - which is technically true so maybe this does fix what you were seeing. If you were describing a different bug let me know.

**Comment by tambry** [comment]
That commit fixes the issue. Thanks!  
Is there a reason why "YUVA decode" mode isn't the default instead of "YUVA" for YUV textures?

**Comment by baldurk** [comment]
Planar/subsampled formats are commonly used for storing YUV data but they don't have to be. There could also be application-specific unpacking/formatting needed that doesn't match the normal expectation meaning the YUVA decode actively does the wrong thing.

For a debugger it is much better to display the actual data in the texture first and foremost, and then possibly offer an alternate mode which applies a default interpretation. That way if you e.g. have a bug in your code that's causing the wrong data to be uploaded you see the wrong data directly, instead of having to work backwards from how it's interpreted to RGB.
