### ISSUE TITLE
Left arrow doesn't collapse open event in Event Browser

### ISSUE THREAD

**Issue by ajweeks** [baldurk/renderdoc#1722]
## Description

When navigating the event browser with the keyboard there is no way to collapse events. I would expect the left arrow key to collapse the currently selected group, or navigate to the previous call if the selected item is already collapsed, whereas currently it will always navigate to the parent item.

I tried finding where this behaviour is defined to make a PR, but I couldn't find it through all the key binding callbacks.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. I can't tell if this is a bug report that the standard keyboard shortcuts aren't working for you or a feature request for some new shortcut behaviour.

Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
