### ISSUE TITLE
Long constant and variable names reduce info visibility in the shader viewer

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1725]
## Description

When debugging a shader, variables or resources with lengthy names can make the views less than helpful - the columns resize to contents, and the variable values in the last column may be offscreen, depending on other panes open. Long variable names can easily occur with autogenerated HLSL snippets or shader graph implementations.

Ideally, the columns could be resized to allow for better control of data visibility while debugging.

## Steps to reproduce

1. Create a shader with long variables names
2. Capture with RenderDoc and debug the shader
3. In the high-level variables tab, as new variables come into scope, the column resizes, pushing some info out of view

In the attached capture, the pixel shader for both draws has an example of long variable names.
[long_variable_names.zip](https://github.com/baldurk/renderdoc/files/4203017/long_variable_names.zip)

## Environment

* RenderDoc version: 5977c2ef37609db4dd42ff616e182cbe7590e343
* Operating System: Windows 10
* Graphics API: D3D11/D3D12

**Comment by baldurk** [comment]
I'm not entirely sure what to do about this issue. Previously I had the columns be resizable but that would very often cause names to be clipped and require lots of user resizing. I changed it to auto-resize to fit the first few columns and then allowed the values column to be resizable to make extra space as needed. When you say that some info is out of view, do you mean until you resize that column and have the horizontal scroll available?

The difficulty with having a resizable column for the name is that it's difficult to pick an initial width and most of the time you pick a width that is too big or too small. Having a resizable column that also resizes to fit its contents is extremely annoying so that's not an option.

While I get that long variable names can happen I feel like having to then scroll when there's limited screen real estate is a reasonable consequence of doing this. Is your issue just that you sometimes have to resize the value column to get enough space? We could perhaps have the value column automatically resize up to fit its contents as well, though I worry that that might get annoying if it fights against the user's resizing.

**Comment by skarolewics** [comment]
It's more about needing to find more screen width or shuffling panes around to be able to see the values at all, since the name column can use so much.

What about allowing resize, but once you do, it stops trying to resize for the remainder of that shader viewer's lifetime? i.e., resize to be as helpful as possible, but once the user manually adjusts it, let them deal with it from then on.

**Comment by baldurk** [comment]
Having hidden state like that makes for a frustrating UI to use. It won't be clear to users why the columns are sometimes the right size and sometimes not. It's better to just have the columns always resizable and never autosized in that case.

I'll think about this more, but if the primary issue is that you don't have to scroll horizontally because your names are really long then while I get that it's annoying I lean towards saying that you're kind of getting what you ask for. Having manual resizing is annoying for the common case and unless there's a middle ground that is a better tradeoff I'd rather handle the common case better at the expense of the rarer case being a bit more annoying.

**Comment by baldurk** [comment]
I think for now the current approach is a reasonable compromise. In future the shader debugger may get a larger refactor which could open up opportunities for improving this in a different way.
