### ISSUE TITLE
D3D11 Rasterizer state changed between end of one frame and start of next

### ISSUE THREAD

**Issue by moradin** [baldurk/renderdoc#173]
This is really not an issue but a feature that in some special cases I would find useful. Sometimes I have some issues that disappear when using renderdoc so I can't use it to capture the problem. It would be good to be able to start it in a way that there is no change to any calls and there are no additional calls to any API at the end of the frame to make sure I see exactly the same in renderdoc as in the application.

**Comment by baldurk** [comment]
You can disable the overlay by using the [in-application API](https://github.com/baldurk/renderdoc/blob/master/renderdoc/api/app/renderdoc_app.h#L274-L305). If you do that before first flip, those calls will never happen.

But there are probably other changes RenderDoc makes. I don't have examples off the top of my head, but there are some changes I need to make to enable capturing and other API calls I make along the way for book-keeping. it depends on the particular API too.

To be honest I don't think there will ever likely be a mode where renderdoc is a *pure* read only man-in-the-middle interception except by coincidence. There will likely always be some minor variations - they should always be within API guarantees that don't affect the meaning of the capture, but that doesn't eliminate possible timing issues, undefined behaviour changes, etc etc. Even stuff like intercepting Map() calls can have subtle effects. Even if those could be eliminated while 'idle' it wouldn't really help because as soon as you capture suddenly everything will change and your bug goes away.

I'm going to close this because I think eliminating all that work is probably a non-goal for the foreseeable future. If you find specific cases or bugs where capturing with renderdoc changes the bug or semantics then you can file those as bugs and I can look and see if it's possible to fix - ie. if renderdoc is changing meaning where it shouldn't.

**Comment by moradin** [comment]
In this specific case the problem was that the rasterizer state was set to something weird at the end of the frame in a post process and at the beginning it was used as if it was still sensible but when using renderdoc the raster state was fine so I'm thinking that renderdoc might not restore the original raster state (talking about dx11). In general my request was about not rendering anything and not changing any states so that the cross frame information stay s the same regardless of using renderdoc or not. If you think it's an unreasonable request that's ok, but if you don't then please reopen this and I can clarify the original description.

**Comment by baldurk** [comment]
Yes RenderDoc should push/pop the entire state vector when it renders the overlay, but yes this would be a case where that's something I will fix, that's certainly not an unreasonable request. Anything application-visible should be identical, but there will still be additional API calls that I make for bookkeeping and such that should be application-invisible but will affect things upstream.

I've reopened and edited the description, if you can just post some more details about what the rasterizer state is set to and the end or start of the frame and what renderdoc is changing that it shouldn't.

**Comment by moradin** [comment]
email sent

**Comment by baldurk** [comment]
From memory in our email conversation we ended up not being able to repro the problem in the original issue (the problem transformed into something else), but re-open this issue if it's still breaking for you and there's more repro information.

**Comment by moradin** [comment]
I think the problem was connected with using another overlay together with renderdoc, I haven't encountered it recently but I will dig deeper if I see it another time.
