### ISSUE TITLE
save GL_EXTENSIONS  Incomplete

### ISSUE THREAD

**Issue by zhouhuamin** [baldurk/renderdoc#1758]
## Description
I print glGetString(GL_EXTENSIONS) return value as below：

const GLubyte *WrappedOpenGL::glGetString(GLenum name)
{
  if(name == eGL_EXTENSIONS)
  {
      rdcarray<rdcstr> implExts;
      rdcstr tmp = (const char *)GetCtxData().glExtsString.c_str();
      split(tmp, implExts, ' ');
      for (int i = 0; i < implExts.size(); i++) {
          RDCLOG("save eGL_EXTENSIONS---1 = %s", implExts[i].c_str());
      }
      rdcarray<rdcstr> implExts2;
      rdcstr tmp2 = (const char *)GL.glGetString(name);
      split(tmp2, implExts2, ' ');
      for (int i = 0; i < implExts2.size(); i++) {
          RDCLOG("save eGL_EXTENSIONS---2 = %s", implExts2[i].c_str());
      }
    return (const GLubyte *)GetCtxData().glExtsString.c_str();
  }
...
}

The print log is  
[print_log.txt](https://github.com/baldurk/renderdoc/files/4293082/print_log.txt)

So I think use GetCtxData().glExtsString is  inaccurate. Please check.

Thank you!

## Environment

* RenderDoc version: Nightly builds v1.x branch @ da17ebed, 2020-02-27
* Operating System: android
* Graphics API: gles

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
