### ISSUE TITLE
Debian linux: callstack always results in ??? symbols for those within main executable

### ISSUE THREAD

**Issue by kakashidinho** [baldurk/renderdoc#1772]
Hi, I'm facing a strange issue with the way callstack is recorded and resolved in Debian linux.
It always displays `???` symbols for those symbols within the main executable, while the symbols in the shared objects are fine.
- For example:
  - The content of /proc/self/maps is:
    - `00400000-05cdc000 r-xp 00000000 00:51 12974779926     helloworld`
    - Which means the base address of `helloworld` program is 0x400000.
  - The callstack in this example is:
    - 0x400001
    - 0x400003
  - When renderdoc tries to resolve the symbols, it deducts the value of callstack's address by the base address of the executable:
    - `0x400001 - 0x400000 = 1`
  - Then this offset is passed to addr2line like this:
    - `addr2line -fCe hellowork 0x1`
  - However this produces `???` result, i.e. invalid offset.
  - But if I don't deduct the callstack's address, but pass the actual value to add2line command:
    - `addr2line -fCe hellowork 0x400001`, then it returns correct file and line number.

The thing is if the address in within a shared object, then an absolute address won't work while a deducted offset will.

Do you know why is there such a difference in the way the addresses are mapped for the main executable and the shared objects? Or maybe this is `backtrace` implementation specific, such that it always returns an absolute address for a function within the main executable? This probably is linux version specific also?

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
