### ISSUE TITLE
how to reduce the size of built org.renderdoc.renderdoccmd.arm32.apk

### ISSUE THREAD

**Issue by shalouzx** [baldurk/renderdoc#1780]
## Description
Hi，I love this tool very much, and i have tried to modify some code. i don't have a linux environment, so i build the android apk in my mac book, however the apk i built has large size， it's about 80M, but the size of the apk you released is about 5M。i did the build work followed the Compiling.md, "cmake -DBUILD_ANDROID=On -DANDROID_ABI=armeabi-v7a ..", so i don't know if i miss something.Looking forward to your reply.

## Environment

* RenderDoc version: v1.5
* Operating System: Mac
* Graphics API: GLES

**Comment by baldurk** [comment]
The nightly/official builds have symbols stripped using `-DSTRIP_ANDROID_LIBRARY=On` which doesn't happen by default. I would not recommend doing this for local builds since the utility of symbols is worth any size increase.

For future reference the build scripts used to build the nightly builds are all public: https://github.com/baldurk/renderdoc/blob/v1.x/util/buildscripts/
