### ISSUE TITLE
Crash when inspecting dynamic uniform buffers

### ISSUE THREAD

**Issue by philoez98** [baldurk/renderdoc#1781]
## Description

When trying to inspect the contents of a dynamic uniform buffer in Vulkan, RenderDoc crashes.
The crash is caused by failing to allocate an enormous amount of memory:

```
RDOC 014828: [13:01:41]     entry_points.cpp( 411) - Fatal   - Allocation failed for 18446744073709551615 bytes
```

The amount of memory that fails to allocate is always the same, no matter how small / big the actual buffer is. Even if the buffer is empty!

Here's a screenshot of the view:

![Cattura](https://user-images.githubusercontent.com/40722053/77162659-c0377300-6aac-11ea-836b-e953a6a1d32e.PNG)

The offset and the buffer size are correct, although I don't get the provided bytes as I am always writing just n-bytes at a time (in this case 192).

For reference the buffer used is valid and I can inspect its content in other debuggers. 
This happens only when using dynamic uniform buffers.

If necessary I can also provide a mini-dump of the crash.

## Steps to reproduce

This is easy to reproduce on my part:

- Create a dynamic uniform buffer of any size
- [Optional]: Map it and write some bytes
- Bind the corresponding descriptor set with the buffer offset
- Try to inspect the content by clicking on the green arrow from the 'Uniform Buffers' panel

## Environment

* RenderDoc version: 1.7
* Operating System: Windows 10.0.18363
* Graphics API: Vulkan 1.1

**Comment by baldurk** [comment]
There was a bug I found this morning which is related but not exactly the same as what you're describing. If a constant buffer is bound with a non-zero offset and a size of `VK_WHOLE_SIZE` then a bounds calculation overflows and it tries to allocate a large amount of data.

If I follow your repro steps it doesn't crash unless the dynamic offset is non-zero and it then crashes exactly the same regardless of if it's dynamic or non-dynamic.

You say that this doesn't happen with non-dynamic uniform buffers, what is that based on? Does this happen if you have the dynamic offset set to 0, or specify a size rather than using `VK_WHOLE_SIZE`?

**Comment by philoez98** [comment]
> If I follow your repro steps it doesn't crash unless the dynamic offset is non-zero and it then crashes exactly the same regardless of if it's dynamic or non-dynamic.

So I tested this a bit more and indeed the crash happens only when the dynamic offset is not zero.

> You say that this doesn't happen with non-dynamic uniform buffers, what is that based on? Does this happen if you have the dynamic offset set to 0, or specify a size rather than using VK_WHOLE_SIZE?

I use different non-dynamic uniform buffers, for which I bind a descriptor set without dynamic-offsets. They are of variable sizes (both using VK_WHOLE_SIZE and not) and work fine for me.

**Comment by baldurk** [comment]
> I use different non-dynamic uniform buffers, for which I bind a descriptor set without dynamic-offsets. They are of variable sizes (both using VK_WHOLE_SIZE and not) and work fine for me.

What I'm getting at is - does it crash with a non-dynamic uniform buffer which has some non-zero offset and `VK_WHOLE_SIZE`. I know there is a bug I've just fixed with current code when doing that, but it has nothing to do with dynamic/non-dynamic. So I'm trying to understand if you are describing a different bug or not.

**Comment by philoez98** [comment]
> What I'm getting at is - does it crash with a non-dynamic uniform buffer which has some non-zero offset and VK_WHOLE_SIZE. I know there is a bug I've just fixed with current code when doing that, but it has nothing to do with dynamic/non-dynamic. So I'm trying to understand if you are describing a different bug or not.

I cannot reproduce this bug. Neither non-zero offsets nor VK_WHOLE_SIZE seem to give problems.
I can only trigger a crash when using dynamic buffers with non-zero offsets. So in my case it seems to be a different (although maybe related) bug.

**Comment by baldurk** [comment]
Just to clarify, the bug only happens if you have a non-zero offset AND use `VK_WHOLE_SIZE` both together on the same binding. Either one on its own won't break. It is definitely broken with current code, to the point where I don't think it's possible for it to avoid crashing no matter your case.

If you can share a specific repro case I can test to see if there's a different bug. Otherwise I think this is the same bug and you're only seeing it with dynamic buffers in your application.

**Comment by philoez98** [comment]
Yeah that's the condition that triggers the crash. I'll try to write a more specific test case and see if it triggers also with non-dynamic buffers.

**Comment by baldurk** [comment]
The commit 839c510 contains a fix for the bug I found. I'm closing this for now but if it still crashes afterwards for you please give more concrete repro steps, and I'll re-open and investigate.
