### ISSUE TITLE
SV_Position are exactly all the same value

### ISSUE THREAD

**Issue by niepp** [baldurk/renderdoc#1787]
## Environment

* RenderDoc version: 1.7
* Operating System: windows 10
* Graphics API: d3d11
![企业微信截图_15849392587796](https://user-images.githubusercontent.com/7009960/77283012-6205cc80-6d06-11ea-903a-92799832b04c.png)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
