### ISSUE TITLE
Vulkan: Crash on capture

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#179]
Hi,

we encounter a crash when we try to capture a frame:
In vk_queue_funcs.cpp at line 566: if(state.mapCoherent && state.mappedPtr && !state.mapFlushed)
the variable 'state' references a null pointer (eg at line 563 record->memMapState: memMapState is null).

As i understand it, it tracks all mapped vulkan memory?
If yes, a note about our usage of mapped memory. All host visible memory get mapped after allocation and gets unmapped if the memory get freed back to vulkan.

**Comment by TiemoJung** [comment]
Small update:

We never unmap, we just delete the memory if no longer needed.

It also crashes with invalid pointers, not just null

**Comment by TiemoJung** [comment]
Second update:
- we added in an unmap before each free and it solved it, but as far as i know it is not required ti do so, so it might be a bug of the mem free capture code

**Comment by baldurk** [comment]
OK I think that makes sense. I assumed that you had to unmap memory before freeing it, but there's no explicit language in the spec. I will file a bug on their github to ask for clarification. If it's legal, it should be easy to support.

The problem is the memory being left in a list of coherent persistent maps, as it is removed on unmap, not on free. NOTE: performance of coherent persistent maps is quite poor with normal use, so be aware that you might get slow capture speed due to the need to compare memory to detect changes. You can work around this by manually inserting vkFlushMappedMemoryRanges for each write even for coherent memory where it's not required. RenderDoc will use this as a signal to switch to the fast path, where it doesn't do any comparing and relies on the application to annotate which memory regions are changed. This of course isn't required, and RenderDoc will still work without it, but slower.

**Comment by baldurk** [comment]
See KhronosGroup/Vulkan-Docs#17

**Comment by baldurk** [comment]
As described in the Khronos issue, omitting the unmap before free is perfectly valid, so I will update RenderDoc to handle this case.

**Comment by baldurk** [comment]
Sorry for the delay. With the above commit, it should be safe to leave memory mapped when freeing it without needing an extra unmap.

**Comment by TiemoJung** [comment]
Hi,

works fine now, thanks!
