### ISSUE TITLE
Bug: Refresh on shader edit has no effect

### ISSUE THREAD

**Issue by Crisspl** [baldurk/renderdoc#1810]
## Description

When I go into **fargment** shader edit window (doesn't matter which one, choice of shader/drawcall is yours), change GLSL source and click Refresh nothing happens (i can't see any difference in what was drawn into color buffer in Texture Viewer tab). Instead, if I go back to Pipeline State tab (without closing shader edit tab), I can see that pipeline object name got corrupted. For instance: instead of usual "Pipeline 1053 > Program 292 > Program 292" I have "Unknown Resource 1000000000000063910 > Program 292 > Program 292".  
If you're interested in application's source code, here it is: https://github.com/Crisspl/IrrlichtBAW/blob/64518c79afe59619915a9da0cd629b76e409d18e/examples_tests/20.Megatexture/main.cpp  
All shaders are separable programs compiled from GLSL with `glCreateShaderProgramv` call (not from binary, however binary form was queried on each created shader program with `glGetProgramBinary`), then attached to pipeline objects.

## Steps to reproduce

Please download my capture. It's too big to attach it to post on GitHub, so here's GDrive link: https://drive.google.com/open?id=1btwoxWkGNul8niQCG7zzVquNiosXhWf-

## Environment

* RenderDoc version: 1.7
* Operating System: Windows 10
* Graphics API: OpenGL 4.6
* GPU: RTX 2070
* Driver version: 26.21.14.4219

**Comment by devshgraphicsprogramming** [comment]
To be confirmed, seems to work on my machine, we will make an example with less shaders

**Comment by baldurk** [comment]
This was caused by the initial state of the pipeline being reset without accounting for edited shaders. That commit should fix it.

Note that the change in pipeline you saw wasn't anything being "corrupted", it was because in order to edit the shader the object needs to be replaced, and on GL that cascades upwards to the program (if it's a shader bound to a program) and then possibly the pipeline. Since that could be confusing I've also made changes to ensure the original resource is still reported even if it has been replaced, but with an `(Edited)` suffix.
