### ISSUE TITLE
Recent change for memory type selection causes OOM crashes during replay

### ISSUE THREAD

**Issue by alexv1n** [baldurk/renderdoc#1812]
We have a heavy .rdc file that used to replay correctly. After recent renderdoc change (929bcfc0ce6b10e9479b842a86cff6b353bff2db), that trace now tries to allocate memory out of GPU memory (while before it was coming out of host memory) and `renderdoccmd replay` crashes with RDCASSERT because vkAllocateMemory from the driver returns `VK_ERROR_OUT_OF_DEVICE_MEMORY`

**Comment by alexv1n** [comment]
I can share an .rdc file with you privately, if needed

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
