### ISSUE TITLE
[Bug] Time duration not displaying

### ISSUE THREAD

**Issue by Cscotttaakan** [baldurk/renderdoc#1815]
## Description
Renderdoc does not show microsecond time duration on event browser.

## Steps to reproduce

Use [SwiftShader](https://github.com/google/swiftshader) as device driver on Linux VM using Ubuntu 18.04.

## Environment

* RenderDoc version: 1.7
* Operating System: Ubuntu 18.04 (VMWare Linux)
16 GB virtual RAM
1 GB virtual VRAM
4 cores

* Graphics API: Vulkan 1.2

I'm not exactly sure how RenderDoc queries for duration, but I'm guessing it most likely has to do with using SwiftShader.

**Comment by baldurk** [comment]
Your repro steps are unclear, but when running swiftshader on an Ubuntu 18.04 VM I encountered an infinite wait in `vkGetQueryPoolResults` leading to a soft-hang of the UI. Since there are no validation errors and all other drivers I've tested on work correctly, I suspect this is a swiftshader bug and should be reported there.
