### ISSUE TITLE
failed at loading trace on remote android device

### ISSUE THREAD

**Issue by zhangpaopao0215** [baldurk/renderdoc#1820]
hi 
   i use renderdoc to capture and game asphalt 9 on the android device sumsung note 10(qualcomm gpu Adreno 640 non root device). i can capture it . but when i loading the trace file. it report the following error
Android  PID   6293: [08:39:11]     remote_server.cpp(410) - Log     - File received.
Android  PID   6293: [08:39:16]     posix_network.cpp(312) - Warning - Timeout in recv
Android  PID   6293: [08:39:16]          streamio.cpp(415) - Warning - Error reading from socket
Android  PID   6293: [08:39:16]     remote_server.cpp(894) - Log     - Closing active connection from 127.0.0.1.
Android  PID   6293: [08:39:16]     remote_server.cpp(896) - Log     - Ready for new active connection...
Core     PID   3256: [16:39:18]    remote_server.cpp(1564) - Log     - Opening capture remotely
Core     PID   3256: [16:39:18]               core.cpp(49) - Log     - Not enabling API validation during replay
Core     PID   3256: [16:39:18]               core.cpp(54) - Log     - Using default GPU replay selection algorithm
Core     PID   3256: [16:39:18]               core.cpp(63) - Log     - Replay optimisation level: Balanced
Core     PID   3256: [16:39:18]          streamio.cpp(415) - Warning - Error reading from socket
Core     PID   3256: [16:39:18]    remote_server.cpp(1598) - Log     - Capture open complete
Core     PID   3256: [16:39:18]    remote_server.cpp(1602) - Error   - Error opening capture
Android  PID   6293: [08:39:46]    remote_server.cpp(1055) - Log     - Connection received from 127.0.0.1.
Android  PID   6293: [08:39:46]    remote_server.cpp(1088) - Log     - Making active connection
Android  PID   6293: [08:39:51]          streamio.cpp(415) - Warning - Error reading from socket

could you please help to resolve this issue. 

thanks

best wishes

harry

## Environment

* RenderDoc version: XXX
* Operating System: XXX
* Graphics API: XXX

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
