### ISSUE TITLE
Issue with nointerpolate float input when debugging DX11 pixel shader

### ISSUE THREAD

**Issue by apayen** [baldurk/renderdoc#1821]
Hello,

I've had an issue debugging a pixel shader in DX11: we have a nointerpolate float4 input which actually holds very uint values that are reinterpreted in the shader.

However, due to the code below, the generated shader to extract the input variables before emulating the DXBC code is missing the nointerpolate keyword for this input. All the DXBC gets is a flat 0.
https://github.com/baldurk/renderdoc/blob/dfc2013bdeb381da105f6e2ca1979d8b0a42141c/renderdoc/driver/shaders/dxbc/dxbc_debug.cpp#L4732-L4736
Removing ` && interpolation != DXBCBytecode::INTERPOLATION_CONSTANT` fixes the issue in my case, but this check looks intentional.

Are there cases where it is not desirable to add the nointerpolation qualifier to fetch the pixel shader inputs?

All our vertices have the same data for that input, but I assume interpolation is flushing floats to 0, even if we interpolate between same values. (as we have values that are like 0x00000300, this results in very small denormals), hence the register holding 0 at the beginning of debugging.

Cheers,
Alexis

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
