### ISSUE TITLE
Expand groups in timeline when selected in Event Browser

### ISSUE THREAD

**Issue by Trass3r** [baldurk/renderdoc#1822]
## Description

With (hierarchical) GL debug group markers selecting a draw call in the browser should not only move the cursor in the timeline but also automatically expand the groups.
Basically extending the sync between these views. It already works the other way around, at least when clicking on a draw call.

## Environment

* RenderDoc version: 5f925ee3a
* Operating System: Win10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
I don't think this change would be an improvement. The event browser groups must be expanded since otherwise there's no way to select an event within them, but in the timeline bar there's no value to expanding out the groups except to clutter up the view as different events are selected. It's better that there isn't a permanent effect to selecting a draw and that expanding a group is a deliberate action.

**Comment by Trass3r** [comment]
Maybe it could be made optional. Or a manual Expand/Collapse All command like in the Event Browser.
