### ISSUE TITLE
Long shader name isn't truncated or scrollable in pipeline state

### ISSUE THREAD

**Issue by johnIIIIX** [baldurk/renderdoc#1832]
## Description

Windows layout freezes. You could change application window height, but width is fixed. All subwindows' widths are also fixed. Trying to increase width in "Event browser" results in strobbing. Looks like it trying to change for one frame, and then returns to previous fixed width value. Opened captures from this engine before on non-4k display and never encountered such issue, so, I believed, display resolution could be the case, but switching from 4k to 1080 didn't resolve the issue.

## Steps to reproduce

RenderDoc font scale 150%. Win10 font scale 150%. Resolution 3840x2160.
Reproduces on DX11 and Vulkan alike.

1) Everything fine on "Pipeline State"

<img width="1033" alt="Before" src="https://user-images.githubusercontent.com/57046427/79334831-af521400-7f29-11ea-8825-b1fb67b4a75f.PNG">

2) Switching from "Input Assembler" to any other stage. Window grow much bigger than 4k, and if const buffer view is opened it goes for 6k in width.

<img width="1899" alt="after" src="https://user-images.githubusercontent.com/57046427/79335876-7155ef80-7f2b-11ea-97f5-69b0ae28855c.PNG">

3) Fullscreen allows to see everything in one window, but layout still frozen, so neither marker no const buffer contents could be seen.

<img width="1920" alt="fullscreen" src="https://user-images.githubusercontent.com/57046427/79336098-ce51a580-7f2b-11ea-819f-b9d262032518.PNG">

Capture: https://drive.google.com/open?id=1L5eqs89vMu-ccuLv8xnReShgxPpJeIUj

## Environment

* RenderDoc version: 1.5, 1.7, 1.8 (4/15/2020)
* Operating System: Win10
* Graphics API: DX11, Vulkan

Thank you for the great tool, baldurk!

**Comment by baldurk** [comment]
Looking at the screenshot this looks like it's be caused by the extreme length of the shader name in the pipeline state view, that control isn't set up to horizontally scroll or truncate the name so it tries to resize up large enough to fit, stealing space from any other panels.

I'll look at protecting against unreasonably long names in the UI there but using names that size will likely break in other places.

Note that fractional DPI scaling is not supported by Qt and so not by RenderDoc, so you may encounter other UI problems related to that which can't be fixed.

**Comment by baldurk** [comment]
That commit will truncate names over 64 characters when displayed elsewhere in the UI, the resource inspector still shows the whole name.

**Comment by johnIIIIX** [comment]
Thanks a lot.)
