### ISSUE TITLE
Frame capature only works with queue capture action

### ISSUE THREAD

**Issue by Inori** [baldurk/renderdoc#1835]
## Description

If I make a capture in the normal way, I mean, just launch the application and press F12.
The capture doesn't work correctly. e.g:

![image](https://user-images.githubusercontent.com/6732524/79672337-85d40980-8203-11ea-95ed-fb89c3431421.png)
The UI renders wrong.
![image](https://user-images.githubusercontent.com/6732524/79672347-9b493380-8203-11ea-9b59-c56947282a42.png)
All vertex are zero, the the mesh can not show.
![image](https://user-images.githubusercontent.com/6732524/79672367-c5025a80-8203-11ea-9be7-bb19484459b0.png)
Color buffer doesn't render.

There are many others, everything is totally wrong.
The capture will work if I check the `Queue Capture` box and let it do the capture automaticly upon start.

## Steps to reproduce

Simply launch the program with default option and press F12.
The program I test is just from [Vulkan Tutorial](https://github.com/Overv/VulkanTutorial/blob/master/code/26_depth_buffering.cpp),
I didn't change any code.
Here's the capture and test program.
https://drive.google.com/open?id=18MtIM-slXwTtpmgdJlPF0jjf-g6CJfOx

## Environment

* RenderDoc version: V1.7
* Operating System: Windows 10. 1909. 18363.778
* Graphics API: Vulkan
* GPU1: Intel(R) UHD Graphics 630
* GPU2: NVIDIA GeForce GTX 1660 Ti with Max-Q Design (DriverVersion:26.21.14.4120)

I'm using a laptop with dual GPU and with an external display, I've made sure both renderdoc and the test program run on dedicated Nvidia GPU, but even I remove the external display, problem still there.

**Comment by baldurk** [comment]
This 'non-rendering displays' effect happens when the underlying API gets a device lost error or otherwise fails in such a way that nothing will happen but the program hasn't completely crashed yet. You should see the error messages if you look in the diagnostic log.

The capture you've shared is using your Intel GPU for rendering, so my guess would be that it's quite possibly an Intel driver bug. The Intel driver in use is 25.20.100.6617 which is quite old, I'd recommend updating to the latest driver available to see if that fixes the problem. Otherwise ensure your application selects the nvidia GPU for use.

I don't have exactly the same Intel GPU but loading on a slightly older one with latest drivers works correctly. I'm also able to capture fine from the exe provided on the Intel system as well as on nvidia and AMD, further suggesting that this is an Intel driver bug on your older Intel driver.

**Comment by Inori** [comment]
`The capture you've shared is using your Intel GPU for rendering`
This is a previous capture I got on Intel GPU, I didn't change it because the problem remains the same when I change to use Nvidia GPU.
But your suggestion is right, after I update both Intel driver and Nvidia driver, problem solved, sorry for the disturb, I should check my drivers before raising an issue.
