### ISSUE TITLE
Error building: type »const rdcstr« of »constexpr«-variable »Vulkan_Debug_PSDebugDumpDirPath« is no literal 

### ISSUE THREAD

**Issue by random2324** [baldurk/renderdoc#1846]
## Description

Trying to compile renderdoc git HEAD aborts with following message:

In Datei, eingebunden von /tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/renderdoc/driver/vulkan/vk_shaderdebug.cpp:25:
/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/renderdoc/driver/vulkan/vk_shaderdebug.cpp:37:27: Fehler: der Typ »const rdcstr« der »constexpr«-Variable »Vulkan_Debug_PSDebugDumpDirPath« ist kein Literal
   37 | RDOC_DEBUG_CONFIG(rdcstr, Vulkan_Debug_PSDebugDumpDirPath, "",
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/renderdoc/core/settings.h:70:25: Anmerkung: in Definition des Makros »RDOC_DEBUG_CONFIG«
   70 |   static constexpr type name = defaultValue;
      |                         ^~~~
In Datei, eingebunden von /tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/renderdoc/core/settings.h:28,
                 von /tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/renderdoc/driver/vulkan/vk_shaderdebug.cpp:25:
/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/renderdoc/api/replay/rdcstr.h:58:7: Anmerkung: »rdcstr« ist kein Literal, denn: 
   58 | class rdcstr
      |       ^~~~~~
/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/renderdoc/api/replay/rdcstr.h:58:7: Anmerkung:   »rdcstr« hat einen nicht-trivialen Destruktor
make[2]: *** [renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/build.make:392: renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/vk_shaderdebug.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
[ 67%] Building CXX object renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/egl_platform.cpp.o
[ 67%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/preprocessor/PpScanner.cpp.o
[ 68%] Building CXX object renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/egl_hooks.cpp.o
[ 69%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/preprocessor/PpTokens.cpp.o
[ 69%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/reflection.cpp.o
[ 69%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/RemoveTree.cpp.o
[ 70%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/Scan.cpp.o
[ 70%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/ShaderLang.cpp.o
[ 70%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/SymbolTable.cpp.o
[ 71%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/Versions.cpp.o
[ 71%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/MachineIndependent/attribute.cpp.o
[ 71%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/glslang/OSDependent/Unix/ossource.cpp.o
make[2]: Verzeichnis „/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/build“ wird verlassen
[ 71%] Built target rdoc_spirv
make[2]: Verzeichnis „/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:461: renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/all] Fehler 2
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[2]: Verzeichnis „/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/build“ wird verlassen
[ 71%] Built target rdoc_gl
make[1]: Verzeichnis „/tmp/yaourt-tmp-greg/aur-renderdoc-git/src/renderdoc/build“ wird verlassen
make: *** [Makefile:147: all] Fehler 2

## Steps to reproduce

Using this AUR package: https://aur.archlinux.org/renderdoc-git

## Environment

System:    Host: greg-pc Kernel: 5.4.3-10-tkg-pds x86_64 bits: 64 compiler: gcc v: 9.2.0 Desktop: KDE Plasma 5.18.4 
           tk: Qt 5.14.2 wm: kwin_x11 dm: LightDM Distro: Antergos Linux 2015.12-ISO-Rolling 
CPU:       Topology: Quad Core model: Intel Core i7-4980HQ bits: 64 type: MT MCP arch: Haswell rev: 1 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 44799 
           Speed: 1823 MHz min/max: 800/4500 MHz Core speeds (MHz): 1: 1900 2: 1889 3: 1900 4: 1900 5: 1901 6: 1900 7: 1902 
           8: 1903 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] vendor: Micro-Star MSI 
           driver: amdgpu v: kernel bus ID: 03:00.0 chip ID: 1002:687f 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu compositor: kwin_x11 resolution: 1920x1080~144Hz 
           OpenGL: renderer: Radeon RX Vega (VEGA10 DRM 3.35.0 5.4.3-10-tkg-pds LLVM 11.0.0) 
           v: 4.6 Mesa 20.1.0-devel (git-ad3ef6d0fc) direct render: Yes

**Comment by baldurk** [comment]
This indicates that the package is misconfigured and broken. A package **absolutely must not** be built with `BUILD_VERSION_STABLE` enabled unless it is based specifically on a tagged stable version (potentially with minor patches if needed). Building the latest unstable code from git with that flag enabled is completely contradictory.

**Comment by random2324** [comment]
Thx for fixing this anyway! https://github.com/baldurk/renderdoc/commit/320b1cddd4fb0fcb1ac29a849114f00b3c9597f6

Reported this at AUR.

**Comment by baldurk** [comment]
The fix was necessary for _actual_ stable builds in future, it was not intended to fix your package.

I don't appreciate your comment that "the author moans that this package is broken". I rely on accurate information from people reporting bugs, so if someone says they encounter a problem on a stable build of 1.7 but they're actually running code from some unknown commit after that point that can cause significant problems for me.

I provide nightly builds myself so I understand the value of being able to run or test the latest code, but the difference is they are clearly marked as such. Misrepresenting a build as stable when it's not is not helpful for anyone.

I'll treat Archlinux the same as Debian as having untrusted/unreliable packages, any bug reports from those packages may be considered invalid unless replicated on a reliable build.

**Comment by 1ace** [comment]
Hey Baldur!

Sorry about the incorrect build flag, I didn't realize what it meant and should've read up instead of blindly copying it from the release package; that's my bad 😕

The issue has been fixed and the package version has been bumped, which will force everyone using this package to recompile it without that flag the next time they do an upgrade, so hopefully the lack of trust for Arch packages should fade away :upside_down_face:

Until then, if you ask bug reporter using Arch to update their system (which should be the first thing they try anyway) before giving the report a second thought, it will make sure that this particular issue is solved :+1:
