### ISSUE TITLE
Vulkan: RenderDoc attempts to use regular images for presentation

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#185]
When a captured frame is being loaded and a vkCreateSwapchainKHR() call is serialized, the debugger creates a set of images it later tries to present by calling vkCreateImage() as many times as there were swapchain images defined.

However, only images retrieved by calling vkGetSwapchainImagesKHR() can be used for presentation purposes. The language in the spec is, admittedly, a bit soft on this requirement:

```
VK_IMAGE_LAYOUT_PRESENT_SRC_KHR: must only be used for presenting a swapchain image for display. A swapchain’s image must be transitioned to this layout before calling vkQueuePresentKHR, and must be transitioned away from this layout after calling vkAcquireNextImageKHR.
```

![image](https://cloud.githubusercontent.com/assets/9154207/13222044/70383f38-d97e-11e5-85de-45b38d2fde32.png)

What RenderDoc is that it later on attempts to transfer images created the "usual" way from UNDEFINED to the PRESENT_SRC image layout, which is not exactly what our driver is expecting.

Is this intentional? If not, I'm happy to replace the create calls with vkGetSwapchainImagesKHR()-based solution. This, however, is only going to work correctly, assuming that at playback time, RenderDoc does acquire swapchain images before presenting them (I have not checked that yet so I can't tell for sure).

**Comment by baldurk** [comment]
Hmm, this is maybe a little trickier to solve. I think we need to keep the method of creating 'fake' backbuffer images via `vkCreateImage` that correspond to the presentable images.

Trying to create a real swapchain is going to be a path of pain, I think, since we don't have any surface to tie them to so we'd have to start creating invisible windows. I think it's the wrong route to go down since RenderDoc doesn't actually need any of the properties of real presentable images, it just needs an image to render to and then display from - the actual presentation all happens to RenderDoc's own windows entirely independently and a separate part of the code.

As long as the only problem is that transitioning into `PRESENT_SRC` is invalid for non-swapchain images then I think perhaps we just need to set up an exception in the image-layout handling code. On replay, no images managed by the core capture-replay loop should be transitioned to or from `PRESENT_SRC`, and we can just substitute `GENERAL` for example. The actual presentable images are all handled independently by manual code in `vk_replay.cpp`.

Does that sound like a reasonable solution? This should be fairly simple so I can commit something tonight for you to try and see if it works better.

**Comment by kbiElude** [comment]
Alternatively, for the replay driver, you could create a 2-image swapchain associated with the renderer window and then do image->image copy at vkPresent() time, where the source image is your "fake" image and the destination points at the swapchain image, right before you pass that presentation request to the driver.

But honestly, anything that works is fine by me! :-)

Admittedly, I'm not familiar enough with RenderDoc codebase to implement this in a reasonable time, but I'm happy to test your changes before they land in master :-) Let me know if there's anything else I can do to help.

**Comment by baldurk** [comment]
That's what I was meaning - the vkPresent itself isn't actually ever replayed, since it's basically a no-op as far as the actual capture is concerned.

The actual rendering onto windows in the RenderDoc UI happens separately in `vk_replay.cpp` and `PRESENT_SRC` is only used there for real presentable images. The problem is that in the replay loop I create fake images then treat them exactly as if they're presentable. But we don't actually care about the presentation - all the actual rendering to the backbuffer will be done in layouts that are valid for both the real and fake backbuffers.

I'll let you know once I have something pushed :).

**Comment by baldurk** [comment]
Should do the trick, but it's hard for me to verify since it was seemingly working before.

**Comment by kbiElude** [comment]
Yup, that does the magic! There's just one more issue I found and we should be good to close this issue. Please have a look at pull request 188 (https://github.com/baldurk/renderdoc/pull/188) for more details.
