### ISSUE TITLE
RenderDoc installation on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jimiblender** [baldurk/renderdoc#1855]
Hi there. I'm new to github and I've never compiled anything from source before. I don't actually understand what the process is and I'd like to clarify it before doing something stupid. I checked my dependencies were up to date, so there should be no issues there. 

I downloaded the renderdoc_1.7.tar.gz tarball but I get lost at the next step:
**cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild -H.
make -C build**
First, where should I put the tarball for installation? 
Second, do I have to extract it first, or do those compilation commands work on a zipped tar?

RenderDoc version: 1.7
Operating System: Ubuntu 18.04 LTS
Graphics API: I have no idea. Yes, I googled it. I tried to find a definition clear enough to be useful to me in the Ubuntu documentation, and I failed.

Any help for a struggling newbie would be greatly appreciated! My ultimate goal is to compile a Blender add-on from source which uses data extracted from RenderDoc to build 3D models. It's open source but it's only available for Windows, so I thought I'd give it a go, but the first step is to get RenderDoc working!
Cheers.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
