### ISSUE TITLE
Incorrect value for SV_VertexID when used with ID3D11DeviceContext::DrawIndexed

### ISSUE THREAD

**Issue by LazyLemonBen** [baldurk/renderdoc#1861]
--DESCRIPTION--
Renderdoc seems to use incorrect values for SV_VertexID when called with ID3D11DeviceContext::DrawIndexed with no vertex buffer set.
The argument "BaseVertexLocation" in the call "ID3D11DeviceContext::DrawIndexed" is given as the value added to each index before reading a vertex from the vertex buffer.  Renderdoc uses this combined value for SV_VertexID in a vertex shader.  This seems to be only correct if a vertex buffer has been set.
If there is no vertex buffer set, Directx11 does not seem to add BaseVertexLocation to the index value, but render doc still does seem to incorrectly use the combined value. 

--STEPS TO REPRODUCE--
No vertex buffer bound. and the index buffer is a single ushort value of 2
ID3D11DeviceContext::DrawIndexed(1,0,1) ---> SV_VertexID == 2, 
but renderdoc gives SV_VertexID == 3

--SYSTEM--
Windows 10 with Directx11 and renderdoc version 1.7

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
