### ISSUE TITLE
TextureViewer displays mips of BC1 texture as black if not divisible by 4

### ISSUE THREAD

**Issue by chrvoss** [baldurk/renderdoc#1870]
## Steps to reproduce

See the attached DDS file. This is a BC1 compressed texture filled with a constant color through all mip levels. It's easily verifiable in a hex editor that the entire file is filled with the same pattern tightly packed.

[mips.zip](https://github.com/baldurk/renderdoc/files/4592213/mips.zip)

Opening this file directly in the texture viewer shows the top level correctly as yellow, but of the lower mips, only the ones with a resolution divisible by 4 are displayed correctly, while all others are shown as completely black.

As required by the D3D11 spec the highest mip level of the texture is divisible by 4 (although this is a runtime restriction, rather than a necessity of the BC1 format), but the same requirement does not apply to lower mips, which are to be treated as virtually padded, with the additional pixels at the border to be discarded after decoding.

Curiously, the texture is displayed correctly when we inspect it in a RenderDoc capture of our D3D12 application using it. The bug occurs only when loading the texture directly outside of a capture.

## Environment

* RenderDoc version: 1.7
* Operating System: Windows 10
* Graphics API: N/A

We have reproduced this in our team across multiple versions of Windows 10 as well as both NVidia and AMD.

**Comment by jumeder** [comment]
The culprit is probably renderdoc\common\dds_readwrite.cpp:1134. The number of rows needs to be calculated as RDCMAX(1U, (numRows + 3) / 4) instead of  RDCMAX(1U, numRows / 4);.

**Comment by baldurk** [comment]
Yes I've already fixed it locally. There are some other issues I'm tidying up while in the same place.

**Comment by baldurk** [comment]
That commit should fix it. I'm looking at how to support opening DDS files that don't have a multiple-of-4 dimension on the top mip, since as you say it's only a D3D requirement and the file is still well-formed. I played around with padding up the texture dimension and just accepting that you'd see a border, but that breaks down in some cases where the real dimension drops down to a multiple of the block size in lower mips but the padded dimension doesn't.

An easier solution would be to just use OpenGL or Vulkan instead for displaying the textures where there's no such requirement, but that would also mean that using D3D11 as a local proxy for a remote capture in GL/Vulkan with such a texture wouldn't be able to display it, so I'd like to find a way to support it properly.

**Comment by jakrams** [comment]
Interesting anecdote: While we investigated the issue, it would show up the exact same way in 1) our engine 2) RenderDoc and 3) Photoshop. And of course on multiple vendor GPUs. So we assumed it might be a bug in D3D. Turns out, it's just the same kind of bug in three different applications :D

**Comment by baldurk** [comment]
Yes I created a texture myself with similarly odd dimensions to make sure that the data wasn't corrupted by a mistaken pitch somewhere (which was the case actually, the fixed-colour was hiding that), and I ended up going through a bunch of applications that either broke similarly or completely refused to open the file.

I guess people really don't commonly use unaligned sizes of textures with block compression :).
