### ISSUE TITLE
Can't run on Android simulator correctly.

### ISSUE THREAD

**Issue by hungry0** [baldurk/renderdoc#1887]
Hi, when I try to run renderdoc on Android simulator(On PC，the CPU structure is x86?), the renderdoc says can't find the abis.so I want to compile from the source code. 
So, my question is that can work? If works, where to find librenderdoccmd.so and libVkLayer_GLES_RenderDoc.so(x86) ?
thank you.
![snipaste_20200514_153434](https://user-images.githubusercontent.com/13111009/81906334-a7ed5b80-95f8-11ea-8e37-6a0e7bde997f.png)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
