### ISSUE TITLE
texture buffer view or export data  are not correct

### ISSUE THREAD

**Issue by zhouhuamin** [baldurk/renderdoc#1892]
## Description

open a depth texture and open the texture contents ina raw buffer view. The buffer contents is zero all. And change format to float also zero.
![image](https://user-images.githubusercontent.com/33196216/82117770-153def80-97a5-11ea-8596-c04940a60219.png)
![image](https://user-images.githubusercontent.com/33196216/82117782-31da2780-97a5-11ea-9bed-18e8c0f2e207.png)
![image](https://user-images.githubusercontent.com/33196216/82117819-6f3eb500-97a5-11ea-9bd5-7e65943d842f.png)

## Steps to reproduce

1.open a rdc file have depth texture.
2.view texture
3.Save selecte texture OR open the texture contents in a raw buffer viewr
4.Observed the texture contents is zero all.

## Environment

* RenderDoc version: v1.7
* Operating System: android
* Graphics API: gles

**Comment by baldurk** [comment]
You have shown yourself to be a persistent and problematic waste of time when reporting bugs, and I have said before that you have exhausted my (I think normally quite reasonable) patience.

In the [last bug report where you demonstrated this](https://github.com/baldurk/renderdoc/issues/1807) I said that all future bug reports from you would be closed if they didn't provide a precise and clear reproducible test case. This bug does not, and indeed I can trivially follow those repro steps and see no problem at all. Whether there is a real bug here or not is unclear but I will not waste my time trying to determine that.

Please do not comment further on this issue. If you can make a new report that does provide a precise and clear reproducible test case then you can do that, but it must be completely explicit and I will have no more patience for ambiguity or lack of information.

As I mentioned last time, and for complete context - to anyone else please don't take this as an indication that I'm unwilling to help with bugs. As long as you are willing to co-operate and help me to help you, there is no problem. This reporter has shown that they can or will not do that, so it would be harmful to the project and myself to continue to try and help.
