### ISSUE TITLE
Renderdoc crashes on capturing Nvidia Vulkan samples on Windows..

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#190]
Hi,
title says it..
4 samples are gl_vk_* ->https://github.com/nvpro-samples
3 are crashing on starting the capture the other (gl_vk_threaded_cadscene-master) is interesting by it's own see below..
of course samples work without capturing in Renderdoc.. also Renderdoc captures correctly tri and cube samples from Vulkan SDK so is working correctly for other samples..
really must be because they are using a OpenGL context for drawing the rendered image to display and Vulkan for creating the renderer image.. i.e. using GL GL_NV_draw_vulkan_image extension..
interesting sample that works is gl_vk_threaded_cadscene-master because this samples supports GL render mode and Vulkan mode and altough it works on the drop down menu to select rendering API+technique only list OpenGL variants.. so in some way Renderdoc is making detection of Vulkan support inside code fail..
Don't know if interested on fixing this Nvidia specific case of codes rendering via Vulkan but displaying via OpenGL or in general taking advantage of OpenGL-Vulkan interop that NV ext provides..

**Comment by baldurk** [comment]
I'll take a look and see what exactly is crashing. I know at one point nvidia's demos weren't going through the loader for all their functions, so this might not be realistically fixable (I don't mind doing some support of vendor extensions, but not if it's a large amount of work).

**Comment by baldurk** [comment]
I got around to trying the demos today. There are a couple of bugs in their vulkan code which I reported which caused two of the demos to crash. Now, they will run but just render a dark red screen. The third crashing demo still crashes, but if it had better error checking it would also just render dark red or similar.

The reason for these behaviours (three rendering nothing, gl_vk_threaded_cadscene only showing GL variants) is because RenderDoc isn't exposing the GL extension nvidia wrote to be able to render vulkan images onto a GL framebuffer. The demos have varying degrees of fallback: The cadscene will just fallback to only showing GL, two of the demos gracefully just render a default colour, and the one that still crashes doesn't check extension presence and just calls a NULL function pointer.

Looking at the actual extension, this isn't one of the vendor extensions that I can trivially/simply support. It would require capture of enough of the GL scene to reconstruct a GL 'harness' to render the vulkan onto - which means capturing GL and vulkan in the same log. Or a bunch of hardcoded workarounds to detect that GL is only being used for flipping and replay only the vulkan part. I think that would lose the UI anyway since that still seems to be GL even when running vulkan.

So the short answer is these demos will probably never capture in renderdoc, as it would be a lot of work to support a very niche and very dubiously useful extension.
