### ISSUE TITLE
Renderdoc freezes my entire system while analyzing frame of tiny Vulkan app

### ISSUE THREAD

**Issue by eligt** [baldurk/renderdoc#1911]
## Description

I'm in the process of learning Vulkan. Starting from the vulkan-tutorial.com sample code, I'm gradually building systems for an engine.

Now, I am **definitely** doing something wrong in my code, nothing shows on screen. I tried to run the app in Renderdoc but doing so runs my system to a crawl and I have to hard-reset it, which has made identifying the exact issue difficult.

The app is simply trying to render 3 2D vertices, no uniforms or textures used.

## Steps to reproduce
[app.zip](https://github.com/baldurk/renderdoc/files/4672714/app.zip)

As you might understand, it's very hard to get a capture as the system becomes unusable shortly after capturing the frame, but I'm attaching the app binary (for Linux).

I can also give a bunch of possibly useful information to further troubleshoot:
- if I remove the (only) `vkCmdDraw` call, the app behaves normally but of course, Renderdoc doesn't detect any issues then
- with the `vkCmdDraw` call in, the app starts but never clears the screen with the `renderPassInfo.pClearValues`, i.e. screen shows a frozen portion of the window underneath 

Edit: I found a way to generate a capture without freezing by only rendering 2 vertices instead of three and with `VK_POLYGON_MODE_POINT`. Still nothing shows on screen but I can see now there are 4 errors, can't copy and paste them but here's the capture:
[capture.rdc.zip](https://github.com/baldurk/renderdoc/files/4673460/capture.rdc.zip)

## Environment

* RenderDoc version: 1.8 from site downloads
* Operating System: Ubuntu 18-04
* Graphics API: Vulkan with GeForce GTX 1060 and NVIDIA driver 435.21

**Comment by eligt** [comment]
I found out what I was doing wrong, something really dumb, I was loading the wrong shaders. Pretty strange in my opinion that this should freeze the whole system while analyzing a frame, but maybe can be dismissed as an oddity.

For the specifics, I was loading a shader that had a uniform declared and different Vertex format from the defined pipeline.

**Comment by baldurk** [comment]
I can't reproduce the problem directly, the application provided doesn't issue any drawcall for me. Looking at the capture I can see many validation layer errors when opening it.

RenderDoc does not handle invalid API use any more than a driver does. Running your program on a different driver may crash the system without RenderDoc even being present if it has invalid API use. You should use the vulkan validation layers regularly and fix any issues they identify.

**Comment by eligt** [comment]
In the capture itself I only saw 4 errors, all caused by loading the incorrect shaders. Unless I'm doing something wrong, I did not see any validation errors when running the app in the form uploaded above.

What I found odd is that, after closing my app and while analyzing a frame captured, Renderdoc would freeze my system. I guess when analyzing a frame Renderdoc actually reloads everything as if the app was running.

**Comment by baldurk** [comment]
RenderDoc only shows validation layer messages generated during the frame, there are several more generated at initialisation time when creating the pipeline because the shaders specified are invalid with the pipeline's setup (the missing vertex attribute you mentioned above).

As above RenderDoc doesn't generally handle invalid API use so you shouldn't rely on RenderDoc to display the validation messages as it may not be able to capture or replay an invalid application at all. You should use the validation layers with a callback in your application to see the errors and warnings generated.

Undefined behaviour really means undefined behaviour. Especially on linux where there's no reliable TDR mechanism then hanging your computer is entirely possible. You can't expect that your error isn't serious enough to cause a system hang, or because there were only some errors you know about. Those errors alone are enough to potentially cause problems.

**Comment by eligt** [comment]
Thanks for the explanation! I just assumed Renderdoc would collect all validation problems since starting the app. I do have validation layers setup with a debug callback (taken straight from the vulkan-tutotial.com samples) but maybe it's not setup correctly as I wasn't getting any errors printed.
