### ISSUE TITLE
Feature request: optional frame validation using validation layers

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#192]
Would it be possible to replay a given frame with validation enabled? Such feature would be of tremendous value for people debugging third-party software without access to actual source code.

**Comment by baldurk** [comment]
If you uncomment the `FORCE_VALIDATION_LAYERS` define in [vk_device_funcs.cpp](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp#L46) then the replay will add the validation layers when creating the instance & device, and there's a debug report callback set up in [vk_core.cpp](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/vulkan/vk_core.cpp#L1928) which has some messages already muted that end up too spammy/poor signal-to-noise ratio.

I'm not sure if this is something I'd expose in the UI though. Generally RenderDoc assumes that applications are well-formed (ie. don't have much to complain about in the validation layers) since it makes some of the same assumptions ICDs will about valid use of the API.

One thing I do want to do is capture validation layer messages in-app and serialise them for replay. I support that on D3D11/GL, with the unfortunate downside that on Vulkan there's no way for me to force-enable the validation layers, it would have to be done by the application.

Having actually typed that out, maybe the alternative is exposing FORCE_VALIDATION_LAYERS in the UI after all. But the difficulty is that RenderDoc doesn't replay faithfully (e.g. adding usage flags and such), so there could be false positives. It's also a bit nasty to have a different way of enabling validation between one API and another, since now the UI has to have some kind of replay-time option.

I'll think about it some more, but in the meantime you can uncomment that define locally :)

**Comment by baldurk** [comment]
I think actually this should now work the same way as the other APIs, now that you can check "Enable API validation" on the capture dialog and force the validation layers to be enabled in the target application. The messages are then saved with the capture and displayed on replay.

Can you let me know if that works for you, or if there's something else you had in mind/something lacking?

**Comment by baldurk** [comment]
Closing this issue as the feature is implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
