### ISSUE TITLE
Hooking promoted extension APIs in respective previous Vulkan versions

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1921]
## Description
I am trying to understand how Vulkan hooking is done for promoted extension APIs. 
In vk_layer.cpp file of RenderDoc v1.7 code, I could see the below code for promoted extension hooking. In this case for the extension API also, we are returning function pointer without suffix. 
If we do so, are we not missing the backward compatibility for those extension APIs.
Ex: vkBindImageMemory2KHR API is part of VK_KHR_bind_memory2 extension which is promoted to vulkan 1.1. 

From the below code, I can understand that we can intercept vkBindImageMemory2KHR API only on devices with vulkan 1.1 because the alias name(vkBindImageMemory2) exists on vulkan1.1 only. On devices vulkan 1.0, there exists no vkBindImageMemory2 API so, we can't intercept the vkBindImageMemory2KHR extension API. But, from our code, we are still pointing to WrappedVulkan::vkBindImageMemory2() in case of vulkan 1.0. 

_// for promoted extensions, we return the function pointer for either name as an alias.
#undef HookInitPromotedExtension
#define HookInitPromotedExtension(cond, function, suffix)             \
  if(!strcmp(pName, STRINGIZE(CONCAT(vk, function))) ||               \
     !strcmp(pName, STRINGIZE(CONCAT(vk, CONCAT(function, suffix))))) \
  {                                                                   \
    if(cond)                                                          \
      return (PFN_vkVoidFunction)&CONCAT(hooked_vk, function);        \
  }_

Can you please explain me how it works? Are we able to intercept vkBindImageMemory2KHR API on vulkan 1.0? 

## Steps to reproduce
Try intercepting vkBindImageMemory2KHR API on vulkan 1.0 device. We will end up with segmentation fault because, we will be redirected to WrappedVulkan::vkBindImageMemory2() which further trys to call below API which doesn't exists on vulkan 1.0.
ret = ObjDisp(device)->BindImageMemory2(Unwrap(device), bindInfoCount, unwrapped));
## Environment

* RenderDoc version: 1.7
* Operating System: Android
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Your description and particularly your steps to reproduce are very unclear. You've written a lot about what you think that RenderDoc's code is doing but that's not helpful in understanding your problem. I also don't know what you mean by "try intercepting vkBindImageMemory2KHR API".

Do not describe your problem by talking about parts of RenderDoc's code. Please describe your problem clearly in itself only: what you are trying to do, what goes wrong, what do you observe happening that isn't expected. When providing steps to reproduce please provide clear steps I can follow in order to reproduce the problem.

**Comment by gittmi** [comment]
Sorry for the confusion. I would like to know whether RenderDoc supports vulkan 1.0 API including extension APIs like vkBindImageMemory2KHR.

I am trying to run an application on a device that supports vulkan 1.0. I am able to run the application on the device without any issues. 

When I try to launch that application using RenderDoc, I am getting segmenatation fault issue.
I tried to debug the issue and found the issue occurred at WrappedVulkan::vkBindImageMemory2.

When I browsed about that API, I came to know it is supported on vulkan1.1. I wonder how vkBindImageMemory2KHR call from application is coming to WrappedVulkan::vkBindImageMemory2 which is not supported on Vulkan1.0?  

This may not the bug in RenderDoc. But, I am trying to understand why the issue is occurring and how can we capture vkBindImageMemory2KHR API on vulkan 1.0 using RenderDoc. 
[vulkan.log](https://github.com/baldurk/renderdoc/files/4705385/vulkan.log)

**Comment by baldurk** [comment]
Yes RenderDoc supports VK_KHR_bind_memory2 if that's what you're asking. Any extensions that are not supported are removed from the enumerated extensions list. If you have an application that is crashing please provide it so that I can reproduce the problem.

You are again asking about RenderDoc's code and posting a log which is from a build you have modified yourself. As I said before this is not helpful, and for obvious reasons I do not support any customised builds of RenderDoc.

As above, if you have a problem such as a crashing application please provide the application itself or an equivalent test case that reproduces the crash so that I can investigate.

**Comment by gittmi** [comment]
Thanks ...
