### ISSUE TITLE
Is it valid to make a partial capture?

### ISSUE THREAD

**Issue by Ivan-Veselov** [baldurk/renderdoc#1929]
## Description

Hi,

Is it legal to use in-application API to capture a small part of a frame? For example if I want to debug a specific draw call that is not issued every frame. In this case I can use API to surround this particular draw call in application code and make sure that when it is issued the capture is saved. Or maybe there are some caveats and it is better to capture the whole frame?

## Environment

* RenderDoc version: 1.8
* Operating System: Any
* Graphics API: Any

**Comment by baldurk** [comment]
Yes that's perfectly legal. There's no meaningful definition of a frame apart from "whatever work happens between two present calls", so that could be just one drawcall. Starting and stopping a capture with the in-application API can be done at will at any time, and is often used when there is no default frame to consider anyway so what's included in the capture ends up being entirely arbitrary.
