### ISSUE TITLE
Cannot replay Unreal Engine DX12 capture

### ISSUE THREAD

**Issue by tbytedev** [baldurk/renderdoc#1933]
## Description
Created a new empty project in Unreal Engine. Set API to DX12, and captured a frame. I couldn't open capture because an error happened.

Core     PID  17776: [13:04:06] d3d12_device_wrap.cpp(1525) - Error   - Failed on resource serialise-creation, HRESULT: E_INVALIDARG

## Steps to reproduce

1. Open Unreal Engine Editor 4.25
2. Click File - New Project...
3. Create a new blank project. (Blueprint, Maximum Quality, Raytracing Disabled, Desktop / Console)
4. Click Edit - Plugins
5. Search for RenderDoc Plugin, and enable it.
6. Click Edit - Project Settings...
7. Under Platforms - Windows set Default RHI to DirectX12
8. Click on RenderDoc icon at the top right corner. RenderDoc opens with a capture.
9. Double click on the capture and a pop up window will appear with the error message.

## Environment

* RenderDoc version: 1.8 (built from 8b491e15)
* Operating System: Windows 10 Pro, version 1909
* Graphics API: DirectX 12
* Graphics card: GeForce GTX 1080
* Graphics driver version: 441.66

**Comment by baldurk** [comment]
I can't reproduce this by following the steps given. I created a new project (in 4.25.1 - that seemed to be the only version available to me, not sure if that's different to 4.25) and switched it to DX12, but the capture loaded correctly.

I'm on an GTX 2080 on a vulkan developer driver 443.15 but that error you listed comes from the DX runtime so that _shouldn't_ matter. I'm not sure what else could be different, are there any global settings in UE4 that could be inherited and not reset to the same value when making a new project?

Can you share an example capture that is failing? That will be the easiest way for me to reproduce the problem.

**Comment by tbytedev** [comment]
Sure. I can't attach the capture file, because it's too big for github, but you can download from here:
https://www.dropbox.com/s/i0wbibr6lpx2ixi/EmptyDX12.zip?dl=0

**Comment by baldurk** [comment]
OK I think that commit should fix it, it was actually the 1080 vs 2080 that made the difference - specifically tier1 vs tier2 resource binding.

One of D3D12's stupidities is that heaps opened through `OpenExistingHeapFromAddress` return heap properties that are impossible to replicate with a normal heap. On tier1 hardware I was adding `D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES` which had been reported to be enough before, but it seems like the D3D runtime wants all but one type of resource to be deny'd.
