### ISSUE TITLE
Feature request - Add support for older graphics APIs (like D3D9)

### ISSUE THREAD

**Issue by native-m** [baldurk/renderdoc#1939]
## Description

I'm currently working on game graphics modification using D3D9 API, and i found it hard to debug without graphics debugger.

It would be great if RenderDoc support older APIs like D3D9, which makes debugging on older APIs much easier.

Will there be a plan to support it?

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10 64-bit
* Graphics API: D3D11

**Comment by baldurk** [comment]
Normally I don't close feature requests if they are reasonable even if they're low priority. In this case though I think it is extremely unlikely that working on D3D9 will ever make sense in terms of cost vs benefit so it will never be supported.

When RenderDoc started in 2014 relevance of D3D9 was already going down, and as time goes on it gets even less relevant - there are only a handful of active users of D3D9 these days. It would be nice to have and it would be a fun project to work on, but there are many more important things to work on and I think that will always be the case.

**Comment by MeFisto94** [comment]
I would like to point out that this issue needs more visibility.
Both my search engine and https://github.com/baldurk/renderdoc/wiki/Roadmap#api point to a wiki page about D3D9 that is not present anymore. It might be worth to just add it back in, linking here or stating the support.

While I understand the stance towards the work this backend would be, I have two questions:

I'm currently trying to understand the rendering of some old program being based on D3D9. Now there are tools to proxy to D3D12 and VK. I guess those won't help me much, because the resulting structure will be a lot different than what is actually happening in the application?

How much work would D3D9 support (besides maintenance) really be? Because I could imagine that there are mostly feature additions with more recent versions, not so much deprecations. The only two/three things I saw on a quick glance are: HLSL instead of FX, DXGI for Context Creation and Removal of the Fixed Function Pipeline.
So if we were to only support programmable pipeline and HLSL on Direct X 9, wouldn't it be mostly the Context management that needs to be done? I'm thinking along the lines of some experimental/unsupported bindings

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by ipud2** [comment]
fuck
