### ISSUE TITLE
Incorrect calculation for data clamping in Mesh Viewer

### ISSUE THREAD

**Issue by martty** [baldurk/renderdoc#1946]
I have a problem where some of my draws are incorrectly rendered in Mesh Viewer. The cause seems to be this line, that clamps the rendered vertex/row count to 100:
https://github.com/baldurk/renderdoc/blob/19c066c6fc65bda0d75de0d2b8c8055081bf190d/qrenderdoc/Windows/BufferViewer.cpp#L1532

It seems to me that the correct arithmetic would be '+' instead of '-' to calculate the buffer byte offset.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
