### ISSUE TITLE
Incorrect calculation for data clamping in Mesh Viewer

### ISSUE THREAD

**Issue by martty** [baldurk/renderdoc#1948]
## Description
I have a problem where some of my draws are incorrectly rendered in Mesh Viewer. The number of indices shown in the buffer viewer/preview are incorrectly clamped to 100 and `...` are shown instead in the VS IN tab. I expect the full range of rows displayed and the entire mesh rendered.

## Steps to reproduce

Open any indexed draw in the Mesh Viewer with an index buffer offset smaller than the index buffer range. I can make a capture to demonstrate, let me know if needed.

## Environment

* RenderDoc version: HEAD
* Operating System: Windows
* Graphics API: Vulkan

https://github.com/baldurk/renderdoc/blob/19c066c6fc65bda0d75de0d2b8c8055081bf190d/qrenderdoc/Windows/BufferViewer.cpp#L1532
It seems to me that the correct arithmetic would be '+' instead of '-' to calculate the buffer byte offset.

Sorry for not using the template first time around. When opening an issue from browsing the source apparently Github does not give the selection of the templates and I didn't check.

**Comment by baldurk** [comment]
I've filed an issue with github to see if there's a way to disable that route of opening issues, since as you point out it skips the templates which is bad for users, and seems completely pointless when you can still copy a permalink and use that in the general case.

It looks like indeed this was wrongly refactored out when extracting out `offset` from a `length - ib.byteOffset - draw->indexOffset * draw->indexByteWidth` calculation.

**Comment by baldurk** [comment]
That commit should fix the offset calculation.
