### ISSUE TITLE
Python API target.ReceiveMessage returns TargetControlMessageType.Noop

### ISSUE THREAD

**Issue by keshavan-v** [baldurk/renderdoc#1949]
I am trying to write a Python Script which automatically captures trace on a local machine for a specific set of frames. However, the call to target.ReceiveMessage continuously returns TargetControlMessageType.Noop. I am not sure how to fix this. 

This is the main function which executes. The data input contains path to the binary, working dir path, cmdline argument and environment. 
```python
def executeAndCapture(data, opts, frameList):
    execResult = rd.ExecuteAndInject(data.binary_path, data.working_dir, data.cmdline, data.env, data.capture_file, opts, False)
    if execResult.status == rd.ReplayStatus.Succeeded:
        target = rd.CreateTargetControl(None, execResult.ident, "capture_trace.py", True)
        if target is None:
            print("Unable to trigger capture. Shutting down...")
            #rd.ShutdownReplay()
            #sys.exit(-1)
        else:
            target.QueueCapture(frameList[0][0], frameList[0][1])
            lastMsg = None
            while True:
                tgtCtrlMsg = target.ReceiveMessage(None)
                if tgtCtrlMsg.type == rd.TargetControlMessageType.Disconnected:
                    break
                if lastMsg != tgtCtrlMsg.type:
                    print(tgtCtrlMsg.type)
                    lastMsg = tgtCtrlMsg.type
                time.sleep(0.005)`
```
And this is invocation of this method:
```python
opts = rd.CaptureOptions()
opts.allowVsync = True
opts.allowFullScreen = True
frameList = list()
frameList.append((63, 1))
executeAndCapture(data, opts, frameList)
```
Application: It is a UE4 based test scene compiled for Windows using Vulkan API. Note that I am not trying to capture this from within UE4. I have compiled it into an executable and that is what I am using to capture the trace.

* RenderDoc version: v1.x (Git SHA: ff4a632fb)
* Operating System: Windows 10 Version 1809
* Graphics API: Vulkan v1.1.130.0
* GPU: Nvidia RTX 2080
* Driver Version: 441.66

Any guidance on what I am doing incorrectly will be greatly helpful.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by mechlya** [comment]
> I am trying to write a Python Script which automatically captures trace on a local machine for a specific set of frames. However, the call to target.ReceiveMessage continuously returns TargetControlMessageType.Noop. I am not sure how to fix this.

Hello @keshavan-v  did you solve this problem: if yes how !

**Comment by baldurk** [comment]
Please do not comment on old issues that were closed long ago.
