### ISSUE TITLE
Request that BufferViewer support buffer sizes > 2^31-1 bytes

### ISSUE THREAD

**Issue by RoboDad** [baldurk/renderdoc#1952]
## Description

Currently, with BufferViewer, a buffer whose size exceeds std::numeric_limits<int>::max() will cause the "Buffer Contents" window to display no contents, even if "Byte Start Range" and "Length" are reasonable values.

Consider switching to a long long version of QSpinBox (of which there seems to several examples on the internet) for any address or size_t spinners.

For the moment, I can work around this limitation by making this local change in BufferView.cpp (clamping range instead of truncating):

  ui->byteRangeStart->setMaximum((int)m_ObjectByteSize);
  ui->byteRangeLength->setMaximum((int)m_ObjectByteSize);

-->

  ui->byteRangeStart->setMaximum((int)std::min(m_ObjectByteSize, (uint64_t)std::numeric_limits<int>::max()));
  ui->byteRangeLength->setMaximum((int)std::min(m_ObjectByteSize, (uint64_t)std::numeric_limits<int>::max()));

Thank you!

## Environment

* RenderDoc version: v1.9
* Operating System: Windows 10
* Graphics API: Vulkan 1.1

**Comment by baldurk** [comment]
Unfortunately making a 64-bit spinbox without completely rewriting it from scratch seems prohibitive. Rather than going all that way, that commit (ab)uses the double spinbox to store 53 bits worth in the spinner which should be enough for hopefully the forseeable future. I tested on a 2.5GB buffer and it seems to work, let me know if you have any problems still.

**Comment by RoboDad** [comment]
53 bits should be sufficient, for now! XD

Thanks!
