### ISSUE TITLE
Meshes created using exported .csv data (from Mesh Viewer) appear to be missing vertices.

### ISSUE THREAD

**Issue by k3mono** [baldurk/renderdoc#1953]
I open the capture. I select a target in Event Browser.
I right click under the 'VS Output' file to export gl_Positions as a .csv file.

I use an application called 'csv2obj' (https://github.com/sergeyreznik/csv2obj) to convert the .csv into an obj file. 

When inspecting the mesh in Blender and 3D Viewer, it appears to have holes caused by missing vertices. 

![Screenshot (1755)](https://user-images.githubusercontent.com/67212600/85215467-f668e500-b370-11ea-8086-6527332d6588.png)

Under the Mesh Viewer tab in RD, meshes do not have missing geometry. I would like to export all the meshes in this capture file, but am unsure how to solve this issue. I deleted vertices that had identical positions, which resulted in csv2obj not reading the data at all. In addition to this, I noticed that there is no vertex input data found in the captures. 

![Screenshot (1759)](https://user-images.githubusercontent.com/67212600/85215375-89a11b00-b36f-11ea-8701-24d9bb0356a1.png)

I would be extremely grateful for any guidance you can give me. 

Thank you :)

* RenderDoc version: 1.8
* Operating System: Windows 10 Home v1909
* Graphics API: OpenGL

GPU: NVIDIA RTX 2060
CPU: AMD Ryzen 7, 3750H
RAM: 16GB

Application launched with RenderDoc: RPCS3 v0.010-524

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
