### ISSUE TITLE
Error opening capture after capture one frame on a Android device

### ISSUE THREAD

**Issue by twotruths** [baldurk/renderdoc#1955]
## Description

After capturing a frame on any Android devices, if I just double click on the frame, it would has error opening capture. It would work when I save it to local disk, and then open it again.
Diagnostic Log is as below:
Core     PID  89284: [19:29:27]    remote_server.cpp(1610) - Log     - Capture open complete
Core     PID  89284: [19:29:27]    remote_server.cpp(1631) - Error   - Capture open failed: File not found
Have tried that on different machines with different Android devices. No similar problems with older versions.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10 64bit
* Graphics API: Opengles

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
