### ISSUE TITLE
Replay issue with MSAA on DX12

### ISSUE THREAD

**Issue by martin936** [baldurk/renderdoc#1959]
Hi,

I'm implementing checkerboard rendering using msaa targets on DX12 and I'm having trouble replaying captures. I get "Failed to open capture for replay: Replaying the capture failed at the API level" every time. I'm able to replay captures of the same application without any issues when I don't use msaa targets. I'm using RenderDoc v1.8 on windows 10 (up to date) and the driver of my GTX 970 is up to date.

Please find attached the diagnostic log, and I'm sending you a faulty capture by email.

Thank you for your help,
Martin

[RenderDoc_2020.06.24_15.57.59.log](https://github.com/baldurk/renderdoc/files/4825871/RenderDoc_2020.06.24_15.57.59.log)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
