### ISSUE TITLE
Replay issue with MSAA on DX12

### ISSUE THREAD

**Issue by martin936** [baldurk/renderdoc#1960]
## Description

I'm trying to replay a capture for an application using msaa targets on dx12. Every time I get the error "Failed to open capture for replay: Replaying the capture failed at the API level". If I don't use MSAA targets, I have no problems replaying captures with the same application.

## Steps to reproduce

Try to replay a capture when rendering to MSAA targets.

Diagnostic log :
[RenderDoc_2020.06.24_15.57.59.log](https://github.com/baldurk/renderdoc/files/4826053/RenderDoc_2020.06.24_15.57.59.log)

I sent you a link to a faulty capture by email

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10 (up to date)
* Graphics API: DirectX 12

I'm using a GTX 970 with it's driver up to date (451.48)

**Comment by baldurk** [comment]
I'm unclear exactly what was wrong here but it seemed like something was causing the GPU to timeout sampling from a depth-formatted array texture (I copy between array and MSAA textures since MSAA textures can't be directly copied to buffers for serialisation to disk).

I don't see anything in the spec that requires `ALLOW_DEPTH_STENCIL` for depth-formatted textures that aren't ever used as a DSV, but this seems to fix the problem at least on my nvidia GPU. Let me know if the next nightly build works for you.

**Comment by martin936** [comment]
Thanks it works
