### ISSUE TITLE
Vulkan capture fails on Gnome/wayland, but works on Gnome/Xorg

### ISSUE THREAD

**Issue by janesma** [baldurk/renderdoc#1961]
## Description

Running renderdoccmd on a gnome/wayland desktop session fails to launch the target application.  Switching the gnome desktop environment to Xorg allows the application to be captured.

The same behavior can be observed when launching a Vulkan application through the qrenderdoc UI.

## Steps to reproduce

1. build a simple vulkan application: https://github.com/krh/vkcube
2. launch a default gnome session (in Debian testing, this is a wayland session).
3. launch renderdoccmd capture ./vkcube
4. note that the spinning cube does not appear
5. log out of gnome, select Gnome/Xorg for the desktop environment
6. launch renderdoccmd capture ./vkcube
7. note that the cube appears, and can be captured.

## Environment

* RenderDoc version: 1.8
* Operating System: Linux
* Graphics API: Vulkan
* GPU: Intel Icelake
* Driver: Mesa 20.1.1

**Comment by baldurk** [comment]
It's unclear if this is a RenderDoc build you made yourself from source or an official build. Wayland is not supported or enabled by default so unless you built from source and enabled it the wayland surface extension would not be available. I didn't check what the application does in that event, you might want to check and have an obvious error instead of silently exiting.

Also note that `renderdoccmd` is not intended to be user facing, it is an internal binary only and should not be considered supported. The only supported way to capture programs is running through `qrenderdoc`.

**Comment by janesma** [comment]
I built from source.  After enabling Wayland in CMake, capture works properly.

Is there any reason to disable Wayland support by default?  As a user, it was confusing when capture did not work.  Wayland is the default desktop environment for Debian now.  There is no error message, the app just fails to launch.

Even if Wayland support is experimental, it has to be better than the confusion over why Vulkan apps crash on launch.

Without RenderDoc's Wayland support, I was still able to launch and capture an OpenGL (Qt) application from RenderDoc, in the default Wayland desktop environment.  I'm not sure why that worked but Vulkan did not.

**Comment by baldurk** [comment]
Wayland is disabled by default precisely because it is not supported. It is an opt-in unsupported feature that you can enable if you know what you are getting yourself into. I don't want to have anyone use it accidentally and think it is supported, then get confused at crashes or problems that may occur.

It is not RenderDoc's place to do your application's work for you. When wayland support is not enabled the wayland surface extension will not be listed as available. Possibly then your application can choose to use an alternate codepath if available, meaning that there would be no error at all. Or if that isn't possible then it can show any error message you wish such as "no wayland surface extension available, can't create swapchain" before exiting. It's certainly not something RenderDoc can or should react to itself.

As to the GL application, I don't know what happened there either. GL is a mess when interacting with the OS and window system so maybe it worked through a compatibility route. Given that wayland is unsupported, using RenderDoc under wayland is undefined so it might work by coincidence in some cases but break in others.
