### ISSUE TITLE
Renderdoc D3D12 shader hash is incorrect

### ISSUE THREAD

**Issue by amd-jiahli** [baldurk/renderdoc#1967]
## Description
Renderdoc doesn't show the correct hash for D3D12 (DXBC and DXIL) shaders.
.

## Steps to reproduce
PIX:
1. Run analysis on"GPU Capture" a D3D12 app that uses DXBC and/or DXIL in PIX 2004.27.
2. In Pipeline tab, click on a draw/dispatch call. 
3. In the bottom Pipeline tab, click "Shader"->GPU Instructions->Disassembly (this option is only available on AMD GPU)
4. This "D3D12 Shader Hash" is used in driver for shader detection. 

Similar steps on Nsight Graphics using Nvidia GPU to see the correct D3D12 shader hash.

Renderdoc:
1.Capture and then open D3D12 app that uses DXBC and/or DXIL in Renderdoc
2. Click on same draw/dispatch call from PIX's step 2.
3. From Pipelineview go to shader disassembly
4.Renderdoc's shader hash is different fro Pix's step 4.

## Environment

* RenderDoc version:  ce908cf1da8691222ec8d692646697e1f1fd6613
* Operating System: Win10
* Graphics API: DX12
* AMD 5700XT (or any AMD GPU).

**Comment by baldurk** [comment]
I've double checked RenderDoc's hash display and it comes correctly from the hash stored in the DXBC container. I don't know where the driver hash comes from but I can't debug that hash code.

If you can provide a case where the hash displayed in RenderDoc does not match that in the file, I can investigate. For obvious reasons I can't debug why PIX might display something different because I'm not responsible for PIX or the driver.
