### ISSUE TITLE
Assertion failure when running simple application and crash when loading its replay

### ISSUE THREAD

**Issue by troughton** [baldurk/renderdoc#1977]
I've got a very simple Vulkan application that just retrieves a swapchain image, clears it in a render pass, and then presents it. The application runs successfully under RenderDoc, but seemingly every frame the following assertion is printed to the diagnostic log:

```
vk_resources.h(2073) - Error   - Assertion failed: 'bakedCommands->cmdInfo->imageStates.empty()'
```
I can capture a frame ([capture attached here](https://github.com/baldurk/renderdoc/files/4906429/FrameGraphTest.zip)), but RenderDoc crashes when I try to play it back. 

NVIDIA Nsight also fails to capture the application, so it's almost certainly something I'm doing incorrectly that's tripping RenderDoc up; however, the validation layers are silent and the visual output seems correct, so I'm somewhat at a loss to what it is. It may be worth noting that both the VkRenderPass and VkFramebuffer are recreated each frame.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
