### ISSUE TITLE
 Assertion failure when running simple application and crash when loading its replay

### ISSUE THREAD

**Issue by troughton** [baldurk/renderdoc#1978]
## Description

I've got a very simple Vulkan 1.2 application that just retrieves a swapchain image, clears it in a render pass, and then presents it. The application runs successfully under RenderDoc, but seemingly every frame the following assertion is printed to the diagnostic log:

```
vk_resources.h(2073) - Error   - Assertion failed: 'bakedCommands->cmdInfo->imageStates.empty()'
```

I can capture a frame ([capture attached here](https://github.com/baldurk/renderdoc/files/4906429/FrameGraphTest.zip)), but RenderDoc crashes when I try to play it back.

NVIDIA Nsight also fails to capture the application, so it's almost certainly something I'm doing incorrectly that's tripping RenderDoc up; however, the validation layers are silent and the visual output seems correct, so I'm somewhat at a loss to what it is. I though it worth filing a bug for both since crashing probably isn't the desired outcome even when it's user error and since I was hoping you may have a better idea of why the assertion is being tripped.

It may be worth noting that both the VkRenderPass and VkFramebuffer are recreated each frame.

(Also, sorry for missing the issue template the first time; I'm not sure why GitHub never prompted me for it).

## Steps to reproduce

Launch the application from within QRenderDoc (capture taken with the "Allow Fullscreen" and "Allow VSync" options). The above assertion appears in the diagnostic log. Takng and saving a frame capture (uploaded [here](https://github.com/baldurk/renderdoc/files/4906429/FrameGraphTest.zip)) succeeds, but viewing it immediately crashes the application with a segmentation fault.

I have also uploaded the source for a single-frame C++ capture taken using NVIDIA Nsight at [FrameGraphTestSource.zip](https://github.com/baldurk/renderdoc/files/4906525/FrameGraphTestSource.zip); this code exhibits the same issue. The zip includes a precompiled binary for Ubuntu 20.04 in the bin directory.

## Environment

* RenderDoc version: 1.8 and nightly (4c40549)
* Operating System: Ubuntu 20.04
* Graphics API: Vulkan 1.2

GPU is an NVIDIA GT 650M, running on the NVIDIA 450.51.05 drivers.

**Comment by baldurk** [comment]
This capture seems like it contains invalid vulkan API use. In particular evident in the serialised C++ is that you have mismatched calls to `vkBeginCommandBuffer` and `vkEndCommandBuffer` which is not allowed. My guess is that you perhaps do other commands in between as well and are missing one or the other which results in garbled command recording. It's unclear from the captures since I would guess both don't behave as expected with invalid calls.

For me the validation layers identify this straight away on the serialised C++ project (among some other errors that may or may not be accurate):

> Validation Error: [ VUID-vkEndCommandBuffer-commandBuffer-00059 ] Object 0: handle = 0x58c1f50, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xdf9fb6be | You must call vkBeginCommandBuffer() before this call to vkEndCommandBuffer(). The Vulkan spec states: commandBuffer must be in the recording state (https://vulkan.lunarg.com/doc/view/1.2.141.0/windows/1.2-extensions/vkspec.html#VUID-vkEndCommandBuffer-commandBuffer-00059)

I note that your capture appears to be referencing the deprecated `VK_LAYER_LUNARG_standard_validation` layer, instead of the latest `VK_LAYER_KHRONOS_validation`. If you're still using an old version of the validation layers they may be missing the necessary checks to identify all problems in your code, and if you're using the newest validation layers then you're not getting any validation at all by referencing the wrong layer name.
