### ISSUE TITLE
D3D12 device is not properly hooked

### ISSUE THREAD

**Issue by barycz** [baldurk/renderdoc#1986]
## Description

After launching our application in render doc, the UI says "API: None" but the application is already swapping frames and rendering as usual.
![image](https://user-images.githubusercontent.com/2946607/88175230-e1100080-cc25-11ea-8f5d-88245468fb4a.png)
We have never had the integration and were always using render doc in the "Launch Application" mode. The "Diagnostic Log" says it is adding a D3D11 device and frame capturer but our application is DX12 (and I am sure that it worked before on my old PC). It also complains about some GUIDs:
![image](https://user-images.githubusercontent.com/2946607/88175282-f2f1a380-cc25-11ea-85d1-08caa90440bf.png)

## Steps to reproduce

I am sorry, but I cannot provide you the target application as it is under NDA. But I could help you debugging the issue if you could point me in the right direction.

## Environment

* RenderDoc version: 1.8 (but I've also tried 1.5, 1.7 and 2020_07_21 nightly build)
* Operating System: Windows 10 Pro
* Graphics API: DX12

Thank you!

**Comment by baldurk** [comment]
Diagnosing this without being able to reproduce it will be difficult. If you're willing to debug the issue for me then I'm happy to help investigate that way. We can either do that here on the issue in public, or you can [email me](baldurk@baldurk.org) if that would make it easier for you.

The first step would be to check if this is application-specific or something related to your system setup. Try building a simple hello-world D3D12 sample e.g. from [MS's samples](https://github.com/microsoft/DirectX-Graphics-Samples) or [renderdoc's demos](https://github.com/baldurk/renderdoc/tree/v1.x/util/test) and see if you can capture that successfully.

Assuming it works, the next step would be to find out how your D3D devices are created and why the device used to create a swapchain isn't properly being hooked. Can you build RenderDoc from source and then use the 'debugger delay' capture option to attach a debugger to the process before it starts running? Then the error message in the swapchain create should trigger a breakpoint. I'd like to know what device is being passed in there, and exactly how it was created and how the pointer was managed (which will depend on what your code is doing). That might give a clue where the hooks are failing.

The D3D11 devices may be a distraction or they may be important, it would also be useful to know which API your code is using at that point. Maybe the devices are only used to enumerate capabilities. If you only intend to use D3D12 then commenting out any use of D3D11 would also be good to simplify the test case.

Can you also paste the full diagnostic log (which you can censor to remove any NDA/identifying information) in text please? Pasting logs as screenshots is difficult to work with since then it's impossible to copy-paste any text without manually transcribing it.

**Comment by barycz** [comment]
Hi again!
Thank you for your help, I have tracked the issue to its source. Our project is actually based on CryEngine, so we can talk some parts of the code publicly.
I guess the root of the problem is that the D3D12CreateDevice function is not hooked properly. RenderDoc misses its call and later complains about unknown device. CryEngine uses the d3d12.h function declaration of D3D12CreateDevice and gets it address using the standard dll linkage as can be seen here: https://github.com/CRYTEK/CRYENGINE/blob/667fe7e6e30937d0bd32da30452b01be1839dde2/Code/CryEngine/RenderDll/XRenderD3D9/DX12/API/DX12Device.cpp#L76 With this code the call goes directly to the d3d12.dll and not through RenderDoc hook.
If I change the code to retrieve the function pointer using GetProcAddress it retrieves the hook function from RenderDoc and the whole thing starts to work:
```
	PFN_D3D12_CREATE_DEVICE pD3D12CD = (PFN_D3D12_CREATE_DEVICE)GetProcAddress(LoadLibraryA("d3d12.dll"), "D3D12CreateDevice");

	D3D_FEATURE_LEVEL level;
	HRESULT hr =
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_12_1, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_12_0, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
//	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_11_3, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
//	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_11_2, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_11_1, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_11_0, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_10_1, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_10_0, IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_9_3 , IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_9_2 , IID_GFX_ARGS(&pDevice12)) == S_OK) ||
	  (pD3D12CD(pDXGIAdapter, level = D3D_FEATURE_LEVEL_9_1 , IID_GFX_ARGS(&pDevice12)) == S_OK) ? S_OK : S_FALSE;
```
I could take that as a fix, but isn't the original way supposed to work too?
Again, thanks for your support.

**Comment by baldurk** [comment]
Calling the function by directly linking it certainly should work and does work for samples I've tested. In the past CryEngine has caused some problems with the way it loads its DLLs but I have fixed the ones I've known about. Do you know how that dll links against d3d12.lib? is it delay load or normal? Either way should work but it will be slightly different in each case.

This will be harder to debug. If you go to `win32_hook.cpp` in renderdoc and change the definition at the top of `VERBOSE_DEBUG_HOOK` from `OPTION_OFF` to `OPTION_ON` you'll get a (very very) verbose log of the hooking process. When an executable or DLL is loaded RenderDoc should go through all of the imports of that module and if it sees e.g. `D3D12CreateDevice` from `d3d12.dll` as a dependency, it will hook it. This should also work if the function is referenced by ordinal. That log might shed some light, you can either read it directly or share it with me (again you might need to search/replace to anonymise if the included filenames are a problem). The idea would then be to debug why the loading of CryEngine's render DLL doesn't get that `D3D12CreateDevice` import hooked properly. It would be worth setting up a similar project (exe + dll that links to d3d12.dll) to compare the log against to see where it differs.

Note that if you have any kind of executable compression or copy protection on your builds then this can absolutely interfere with RenderDoc's hooking, so you should try to disable that first.

**Comment by barycz** [comment]
The process of creating a device is not straight-forward in CryEngine. The engine first tries to detect the system capabilities using a device created from one of its dlls (CrySystem.dll). Later it loads the render dll which creates the actual device that is used for rendering. The success of the hook of the second device depends on how the first device is created (or if the second function is retrieved with the GetProcAddress call) - that is the weird part of it. But we have found a workaround, so we can close the issue right now. Thank you.

**Comment by baldurk** [comment]
For what it's worth that shouldn't matter to whether the hooks apply, it seems like there must be some other factor since the upstream cryengine works just fine.
