### ISSUE TITLE
Application launched via RenderDoc does not Show any Contents in its Window

### ISSUE THREAD

**Issue by tquante** [baldurk/renderdoc#1987]
## Description

Since Version 1.7 I am unable to use RenderDoc for our Application. When i launch the programm via RenderDoc the window does not update its contents and simply shows a white box on black background. When i hit the capture button i need to focus the window to start the capture process and then refocus to complete the capture. Sometimes multiple swap buffer events are captured other times all DrawCalls of multiple frames are collected without recognizing the swap_buffer events between them.

The backbuffer should be sized 1280x1024 but Renderdoc records a texture with 2560x1600 (full screen size).  Strangely the contents of the framebuffer are looking reasonable.

The OpenGL context itself is not running in the main thread, but in its own thread, including the loading of all OGL function pointers.

## Steps to reproduce

The app unfortunately cannot be shared due to NDA reasons.

## Environment
* RenderDoc version: 1.7 - 1.9 (Version 1.6 is working as intended)
* Operating System: Windows 10.0.19041
* Graphics API: OpenGL  (latest Nvidia Quadro Driver 13.07.2020)

**Comment by baldurk** [comment]
I understand that you can't share the program but without it I don't really have any information to go on and there's not much I can do. Your description is fairly high level and I can't guess from it what the problem might be.

Can you simplify your program to the point where it's something you can share? Or take an open source sample and modify it to work like your program in such a way that reproduces the problem?

You could also try running nightly builds between 1.6 and 1.7 when the problem began to narrow down which commit started the problem. However unless it then becomes obvious what the problem is I still won't be able to do much.

**Comment by tquante** [comment]
Thank you for your fast reply. Bisecting revealed, that the issue started to appear with nightly RenderDoc_2020_01_22_4c9bb5d8_64. Skimming through the commits 4c9bb5d8444b9f9c51cd6a8563ab1607b3d744f0 seems suspicious. After compiling it and the Version before I can safely say that the "wgl push pop" change causes the issue

**Comment by baldurk** [comment]
That narrows down the cause but without being able to reproduce what's going on I still don't know what the problem is. Can you try to debug that code, perhaps to see where the code goes wrong with its pushing and popping of contexts? Or replicate how your program handles windows, DCs and contexts in a demo that you are able to share?

**Comment by tquante** [comment]
Thank you for your support. During the creation of the minimal sample i found a bug in our HDC handling, which used the wrong hdc during swap, which happens to be unnoticed for at least a year. After fixing that, the issue is gone. So we can close this. I consider this another bug found by RenderDoc. Thank you for this project.

**Comment by baldurk** [comment]
That wasn't exactly intentional but I'm glad it helped! :smile: OpenGL's context handling especially on windows is messy.
