### ISSUE TITLE
latest 1.9 release fails to build: "stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'"

### ISSUE THREAD

**Issue by david-geiger** [baldurk/renderdoc#1990]
Hi,

I tried on Mageia Linux (Cauldron) to build latest 1.9 release but I get an underlinking build issue:

> /BC7_Encode_Kernel.cpp.o CMakeFiles/rdoc.dir/data/glsl_shaders.cpp.o CMakeFiles/rdoc_version.dir/replay/version.cpp.o   -L/home/iurt/rpmbuild/BUILD/renderdoc-1.9/build/renderdoc  -lm -ldl -lrt -lX11 -lxcb -lxcb-keysyms -lpthread -lrenderdoc_libentry 
/usr/bin/ld: CMakeFiles/rdoc.dir/os/posix/linux/linux_process.cpp.o: in function `StringConverter<long, false>::Do(long const&)':
/home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: CMakeFiles/rdoc.dir/os/posix/linux/linux_process.cpp.o:/home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: more undefined references to `rdcstr DoStringise<long>(long const&)' follow
collect2: error: ld returned 1 exit status
gmake[2]: *** [renderdoc/CMakeFiles/renderdoc.dir/build.make:1320: lib/librenderdoc.so] Error 1

RenderDoc version: 1.9
GCC: 10.2.0
Qt: 5.15.0
cmake: 3.18.0

Attached full build log:
[build.0.20200725044602.log](https://github.com/baldurk/renderdoc/files/4974924/build.0.20200725044602.log)

Regards,
David

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
