### ISSUE TITLE
Append extension to saved files if not present

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#1992]
This is a quality of life bug report. And only needs a simple fix!  :smile: 

The GTK save filed dialog never automatically appends the extension.

Thus if I save file "MyCapture" it will save it as "MyCapture" instead of saving it as "MyCapture.rdc"

This is very annoying later on when trying to load the capture, because the open file dialog will filter any file not ending in *.rdc

Thus wherever getSaveFileName is used, code should do something like this:

```
void CaptureDialog::on_saveSettings_clicked()
{
  QString filename = RDDialog::getSaveFileName(this, tr("Save Settings As"), QString(),
                                               tr("Capture settings (*.cap)"));

  if(!filename.isEmpty())
  {
	  if( !filename.endsWith( ".cap" ) ) // New code!
		  filename += ".cap";
    QDir dirinfo = QFileInfo(filename).dir();
    if(dirinfo.exists())
    {
      SaveSettings(filename);
      AddRecentFile(m_Ctx.Config().RecentCaptureSettings, filename);
      m_Main->PopulateRecentCaptureSettings();
    }
  }
}
```

In some cases it's not possible to easily determine which extension to use (when multiple options are available), but .rdc and .cap are the most predominant because they're RenderDoc-specific (e.g. I easily know if I try to export csv, png, dds, etc).

To be more specific, this is my screen: At no point do I know that Capture Settings must end with .cap:

![image](https://user-images.githubusercontent.com/3395130/88468231-dae48300-ceb6-11ea-94d2-c0ca19f3afdb.png)

## Environment

* RenderDoc version: 1.8
* Operating System: Xubuntu 18.04 LTS
* Graphics API: N/A

To repro this bug, a GNOME-derivative needs to be predominant Desktop Environment. AFAIK KDE-derivatives DEs will use a different save dialog that is more reasonable.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
