### ISSUE TITLE
 Append extension to saved files if not present

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#1993]
## Description

This is a quality of life bug report. And only needs a simple fix!  :smile: 

The GTK save filed dialog never automatically appends the extension.

Thus if I save file "MyCapture" it will save it as "MyCapture" instead of saving it as "MyCapture.rdc"

This is very annoying later on when trying to load the capture, because the open file dialog will filter any file not ending in *.rdc

In some cases it's not possible to easily determine which extension to use (when multiple options are available), but .rdc and .cap are the most predominant because they're RenderDoc-specific (e.g. I easily know if I try to export csv, png, dds, etc).

To be more specific, this is my screen: At no point do I know that Capture Settings must end with .cap:

![image](https://user-images.githubusercontent.com/3395130/88468231-dae48300-ceb6-11ea-94d2-c0ca19f3afdb.png)

## Steps to reproduce

1. Open RenderDoc in Xubuntu 18.04
2. Hit Save Settings
3. Type "MySetting"
4. Look for the file, it won't be named MySetting.cap but rather MySetting

## Environment

* RenderDoc version: 1.8
* Operating System: Xubuntu 18.04 LTS
* Graphics API: N/A

To repro this bug, a GNOME-derivative needs to be predominant Desktop Environment. AFAIK KDE-derivatives DEs will use a different save dialog that is more reasonable.

## Possible solution

Wherever getSaveFileName is used and only one filter is available, code should do something like this:

```
void CaptureDialog::on_saveSettings_clicked()
{
  QString filename = RDDialog::getSaveFileName(this, tr("Save Settings As"), QString(),
                                               tr("Capture settings (*.cap)"));

  if(!filename.isEmpty())
  {
	  if( !filename.endsWith( ".cap" ) ) // New code!
		  filename += ".cap";
    QDir dirinfo = QFileInfo(filename).dir();
    if(dirinfo.exists())
    {
      SaveSettings(filename);
      AddRecentFile(m_Ctx.Config().RecentCaptureSettings, filename);
      m_Main->PopulateRecentCaptureSettings();
    }
  }
}
```

**Comment by baldurk** [comment]
This isn't a RenderDoc bug. The workaround you propose is not a simple fix as it doesn't account for all cases - for example if the user enters `file` and we automatically append a file extension, we may choose a filename that now overwrites an existing file without the user having been prompted because `file` doesn't exist but `file.ext` does. We would have to detect this case, prompt if the user is sure, and optionally loop back and prompt for the filename again. It also then means that it's impossible for the user to save with a different extension should they so wish.

The primary purpose of using Qt as a platform abstraction is to avoid needing to work around badly behaving platforms. This should either be filed with GNOME/gtk to improve their file browser's behaviour or else with Qt to workaround it for all programs. Otherwise this would have to be effectively hacked around in every Qt (GTK?) program that wants to save files, which is backwards from where it should be fixed.

It's unfortunate that there's no indication in the save dialog of what the current filter's extension should be, but that is the responsibility of your platform/DE, not RenderDoc.

**Comment by darksylinc** [comment]
OK I just took a deeper look.

Actually it IS a RenderDoc bug.

RenderDoc does:

```
if(!defaultSuffixes.isEmpty())
	fd.setDefaultSuffix(defaultSuffixes.first());
```

So far this works.

However you later use a lambda:

```
  QObject::connect(&fd, &QFileDialog::filterSelected, [&](const QString &filter) {
    int i = fd.nameFilters().indexOf(filter);
    fd.setDefaultSuffix(defaultSuffixes.value(i));
  });
```

By the time that lambda gets invoked, defaultSuffixes is empty (or invalid? I don't know). If I comment this line, it works as expected:

```
  QObject::connect(&fd, &QFileDialog::filterSelected, [&](const QString &filter) {
    int i = fd.nameFilters().indexOf(filter);
    // fd.setDefaultSuffix(defaultSuffixes.value(i)); //Now it works
  });
```

Hence I request this bug be reopened and the bug be fixed :) (pretty pleaaase??)

**Update:** ~~defaultSuffixes is very invalid, it doesn't crash as a happy accident.~~ Also `int i = fd.nameFilters().indexOf(filter);` returns -1

**Update 2:** defaultSuffixes is valid. The only problem is that `int i = fd.nameFilters().indexOf(filter);` returns -1

**Comment by darksylinc** [comment]
Proper fix seems to be:

```
QObject::connect(&fd, &QFileDialog::filterSelected, [&](const QString &filter) {
	  if( !filter.isEmpty() )
	  {
		  int i = fd.nameFilters().indexOf(filter);
		  fd.setDefaultSuffix(defaultSuffixes.value(i));
	  }
  });
```

It appears it gets called with an empty filter on startup, but later when selecting a filter the filter string is valid and everything works as expected.

Or alternatively:

```
QObject::connect(&fd, &QFileDialog::filterSelected, [&](const QString &filter) {
		  int i = fd.nameFilters().indexOf(filter);
                  if( i >= 0 )
		      fd.setDefaultSuffix(defaultSuffixes.value(i));
  });
```

**Comment by baldurk** [comment]
This still doesn't seem like a RenderDoc bug from what you've described. `QFileDialog::filterSelected` should not be getting called with an empty filter string unless that's an actual filter that was selected (somehow? maybe a platform specific 'all files' filter?).

If you actively ignore the case where it's an unrecognised filter I'm not sure if that's going to break on some other linux environment where maybe you can customise the filter on the fly. A better fix I think would be to call `getDefaultSuffixesFromFilter` if the filter passed in isn't found in `fd.nameFilters()` to figure out the extension on the fly (the only reason this lookup exists is to cache that regex work), though that would still leave you with an empty default suffix if an empty filter is passed. Garbage in, garbage out.

I'm also unsure what's happening when you say an empty string gets passed in at initialisation, but then a real filter string gets passed in later. Shouldn't that set the correct setDefaultSuffix? or is it broken because `.value(-1)` was called earlier?

I'll have a think about whether it's OK to ignore an empty string, since that has a pretty low chance of being deliberate.

**Comment by darksylinc** [comment]
> This still doesn't seem like a RenderDoc bug from what you've described. `QFileDialog::filterSelected` should not be getting called with an empty filter string unless that's an actual filter that was selected (somehow? maybe a platform specific 'all files' filter?).

While I'd agree on that, RenderDoc is letting an invalid index get to defaultSuffixes.value(i); hence my recommendation on doing:

```
if( i >= 0 )
      fd.setDefaultSuffix(defaultSuffixes.value(i));
```

> If you actively ignore the case where it's an unrecognised filter I'm not sure if that's going to break on some other linux environment where maybe you can customise the filter on the fly.

That does not exist when _saving_.
 
> I'm also unsure what's happening when you say an empty string gets passed in at initialisation, but then a real filter string gets passed in later. Shouldn't that set the correct setDefaultSuffix? or is it broken because `.value(-1)` was called earlier?

It breaks when the save dialog gets opened for the first time because an empty string is received, but if there is more than one filter that can be selected and another filter is selected by the user, it will begin to work correctly.

> I'll have a think about whether it's OK to ignore an empty string, since that has a pretty low chance of being deliberate.

Yes. You have to consider that a blank extension is barely an inconvenience (due to being a very rare ocurrence) while having _every saved file be saved without extension_ is a major usability inconvenience on all Linux DEs except KDE.

I started this ticket because I got fed up from this bug.

**Comment by baldurk** [comment]
I appreciate that it's annoying, but it seems like it's annoying because of a GNOME bug. I'm not opposed to adding a workaround, I just want to make sure that working around someone else's bug in one case doesn't then break some legitimate case elsewhere. With linux it's hard to know what legitimate cases might exist - it wouldn't surprise me if there were actually a way to customise the filter when saving to choose your own file extension.

It's certainly a good idea to add the check that `i` is non-negative and fall back to calling `getDefaultSuffixesFromFilter` otherwise in case an unexpected but valid filter comes back. What to do with an empty filter string then remains as a question and like I say I'll just need to think about it a bit to be sure I'm OK with ignoring it for this workaround.

**Comment by baldurk** [comment]
I went with the above compromise, so the code will now ignore that empty string from the GNOME bug. Hopefully that won't bite me in the future :smile:.

**Comment by darksylinc** [comment]
I love you!!!

Crowd cheers!
