### ISSUE TITLE
Problems installing renderdoc server

### ISSUE THREAD

**Issue by zgy001** [baldurk/renderdoc#2002]
## Description
i compile the project by myself.But both on windows and linux,when i select my mobile device,i got the info:Problems installing renderdoc server.Could not find APK folder . please check you installation is complete.
![image](https://user-images.githubusercontent.com/43093592/88927466-0813a580-d2aa-11ea-903e-6a9167dc573b.png)

## Steps to reproduce
i just followed the steps Compiling.md provides.

## Environment
on windows:win10,VS2019,x64,development
on linux:ubuntu20.0.4
my mobile device:mi5,android8,

* RenderDoc version:the source code on github now
* Operating System: XXX
* Graphics API: opengl
by the way,i can use the builded renderdoc.but why i failed when i build for myself?

**Comment by baldurk** [comment]
Have you compiled the android build? Where did you put the build folder?

If you want to have RenderDoc automatically pick up the APK location it must either be built in `build-android` in the repository root (or `build-android-arm32` and `build-android-arm64` if you need both ABIs for your device), or in the `plugins/android` folder next to the `renderdoc.dll` that you built to mirror the distributed builds.

Otherwise you will need to manually install the correct APKs to ensure that RenderDoc finds them and they pass the version check matching the git version that you built on the host. If your device supports both arm32 and arm64 you must install both APKs of the same version.

Given that android is a terrible platform I generally don't recommend trying to build renderdoc for it unless you absolutely need to. If the nightly builds work then I would recommend using them as they are built with the best GLES interception method that generally your local builds won't.

**Comment by zgy001** [comment]
Thanks for your answer！i'm using renderdoc on an app which will check whether the dynamic lib's path is legal. Because the libVkLayer_GLES_RenderDoc.so is loaded from org.renderdoc**,the app will find it and crash immdiately.so i want to change the source to let renderdoc first copy its .so to /system/lib64 and then load and run.(just use command adb remount and then copy the .so)i,m trying to build it by myself,but can you help build such one?which may be more stronger against the apk's anti-debug protection.Thanks.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
