### ISSUE TITLE
hangs at crash handler

### ISSUE THREAD

**Issue by qiankanglai** [baldurk/renderdoc#2015]
## Description

Cannot open RenderDoc. Task Manager shows qrenderdoc.exe exists but no GUI.

## Steps to reproduce

Just click `RenderDoc` in Start Menu. I created a dump and debug with symbols from server:
![image](https://user-images.githubusercontent.com/1546130/90105797-15846180-dd79-11ea-9287-d1f0253dfb2e.png)

Maybe we can add a timeout or add configuration to disable it?

## Environment

* RenderDoc version: 1.9
* Operating System: Win10
* Graphics API: DX11

**Comment by baldurk** [comment]
If CreateProcess is hanging then that suggests some problem outside of RenderDoc. Since this hasn't been reported before that I'm aware of that would also make sense if it's something specific to your system and not a general RenderDoc bug. Do you have any anti-virus or other security software installed? These can often interfere and cause problems, so try disabling them. If you have a different PC to run on does it work there?

**Comment by qiankanglai** [comment]
I think it is related to some anti-virus tool. In fact UE4's crash handler also hangs today.
But I don't have the permission to disable them on company's working computer which is annoying.

**Comment by baldurk** [comment]
If another program is also hanging in a similar way then it seems very likely that it is not either program at fault but instead something external like security software. Most anti-virus programs are unfortunately snake-oil that cause problems either like this or more severe - like creating their own vulnerabilities.
