### ISSUE TITLE
OpenGL 3.2 constant crashes while launching application from RenderDoc

### ISSUE THREAD

**Issue by live3v1l** [baldurk/renderdoc#2016]
## Description

I'm trying to launch my application with RenderDoc by clicking Lauch button in "Launch Application" tab.
I see application starting and that information text in injected process about pressing F12 to capture frame and it suddenly crashes at first render without even pressing F12 key. The crash is at glBindBuffer hook when it calls LockChunks function. m_ChunkLock is not a null but is a pointer to memory which is not readable therefore when executing m_ChunkLock->Lock() calls EnterCriticalSection it is cause of AccessViolation

MiniMemoryDump from crash - >[Halfbyte.exe.800.zip](https://github.com/baldurk/renderdoc/files/5081227/Halfbyte.exe.800.zip)
My test program which is crashing after injection -> [Debug.zip](https://github.com/baldurk/renderdoc/files/5081229/Debug.zip)

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10
* Graphics API: OpenGl 3.2

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
