### ISSUE TITLE
Cmake, Fetch Content, RenderDoc Api Static Library

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2031]
## Description

As far as I'm aware the only way to use the RenderDoc API is to load it at runtime:
https://renderdoc.org/docs/in_application_api.html

I need the ability to statically link against the RenderDoc API, using cmake.

I would like to use cmake's fetch content module to **statically** link against the RenderDoc API. 
Dynamic libraries don't work for my goals. I can elaborate why if needed.

Here is an example of the cmake code I would like to have.

```
# Fetch content is available in cmake 3.11
FetchContent_Declare(renderdoc
    GIT_REPOSITORY https://github.com/baldurk/renderdoc
    GIT_TAG v1.9
    GIT_SHALLOW ON
)

FetchContent_MakeAvailable(renderdoc)

# Specify the API should be a static library
set(BUILD_SHARED_LIBS OFF)

target_link_libraries(foo PRIVATE RenderDoc::API)
```

I don't believe this is currently possible, with the current cmake infrastructure that RenderDoc has.

## Environment

* RenderDoc version: XXX
* Operating System: XXX
* Graphics API: XXX

**Comment by baldurk** [comment]
RenderDoc will never be a static library. It is not a normal library and should never be linked against at all, even dynamically. The API is fetched at runtime because it depends on whether RenderDoc's library was injected into the process.

The only build time dependency is the header, which you can include in your project directly without any build system intervention.
