### ISSUE TITLE
GetDimensions on Texture3D returns zero inside compute shader

### ISSUE THREAD

**Issue by rorydriscoll** [baldurk/renderdoc#2040]
## Description

When debugging a compute shader which uses GetDimensions on Texture3D<float4>, RenderDoc returns zero for all dimensions:

```
uint3 GetDimensions(Texture3D<float4> t)
{
	uint w, h, d;
	t.GetDimensions(w, h, d);
	return uint3(w, h, d);
}
```

Disassembly:
```
      t.GetDimensions(w, h, d);
  31: resinfo_indexable(texture3d)(float,float,float,float)_uint r2.xyz, l(0), voxel_texture.xyzw
  32: mov r2.x, r2.x
  33: mov r2.y, r2.y
  34: mov r2.z, r2.z
```

Debugger:

```
d r2.z uint 0
h r2.y uint 0
w r2.x uint 0
```

## Steps to reproduce

 I emailed a capture. This is evident in the RenderProbeRays compute shader.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10
* Graphics API: DirectX 12

**Comment by baldurk** [comment]
Thanks for the repro case. The problem was the shader debugging assumed it could pull the view parameters from the corresponding `D3D12_UNORDERED_ACCESS_VIEW_DESC` or `D3D12_SHADER_RESOURCE_VIEW_DESC`, but it looked like the SRV in question was created with a `NULL` desc meaning the code assumed it was invalid. That commit generates a default desc from the resource which should fix the issue.

**Comment by rorydriscoll** [comment]
Thanks for the quick fix. That makes sense. IIRC I'm creating all my views using NULL desc pointers.
