### ISSUE TITLE
Invalid events in API Inspector

### ISSUE THREAD

**Issue by lstalmir** [baldurk/renderdoc#2042]
## Description

I recently updated from 1.7 to 1.9 and after capturing a frame I saw that some events in the API Inspector window were marked as "Indirect sub-commands", which made reading details (like function parameters) impossible. The issue seems to be caused by vkCmdDrawIndirectCount and is visible in subsequent command buffers. I checked 1.8 and it's also affected.

## Steps to reproduce

I've sent a simple application that reproduces the issue in an email.

1. Capture any frame from the application
2. Select vkCmdDraw(3, 1) from Colour Pass # 2
3. API Inspector shows EID:22, Event:"Indirect sub-command"

## Environment

* RenderDoc version: 1.8+
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I think it may have been broken on 1.7 just in a different way. A command buffer with an indirect count draw was re-ordering later commands in itself but not later comands in other command buffers. In older versions I was reserving all the data needed for indirect-count draws and then removing the excess, and in 1.8 I changed it to not reserve space since for very large maxCounts that's wasteful. In your case the draw was drawing exactly maxcount so in 1.7 nothing was re-ordering.

That commit should avoid the re-order entirely and fix the problem.
