### ISSUE TITLE
Unable to capture: application crash at startup

### ISSUE THREAD

**Issue by doomtr666** [baldurk/renderdoc#2043]
## Description

I've made a "triangle" demo application and I am unable to capture anything with renderdoc. The application crash at startup (see renderdoc.log in provided archive). Without renderdoc the app works fine, with no validation warnings.
The app use low level context switch to implement a parallel renderer. The crash is probably related, but how can I debug that kind of issue ?
 
## Steps to reproduce
[triangle.zip](https://github.com/baldurk/renderdoc/files/5183902/triangle.zip)

Simply try to capture a frame with provided app, immediate crash.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10
* Graphics API: Vulkan

Renderdoc works great with other vulkan app on my system.

**Comment by baldurk** [comment]
As far as I can tell some of the worker threads in this program are experiencing stack corruption. When RenderDoc's function calls are added that seems to shift things just enough that it ends up crashing further down the stack, but for example this was crashing for me even without RenderDoc because I have another program (displayfusion) which was also adding DLL code into the stack.

Without source I can't tell what's going wrong exactly or give you any more information than that. I'd suggest attaching a debugger when running under renderdoc and seeing if you can catch the corruption or see if you use tools like asan to help. Otherwise trying to simplify the code and/or adding extra debugging to try and bisect where the problem is.

If you can share the source I can try and help but most likely I won't be able to do any better than yourself as this does not look like RenderDoc bug.

**Comment by doomtr666** [comment]
This is a WIP experiment with a low level C / asm task system that changes the thread stack pointer hundreds of times per second in a "fiber-style" fashion. I'm not very familiar with the dll injection code, but it doesn't seem to interact very well with my context switch routine. Surely I missed something, and without a doubt the problem is with this part. I haven't released the source code yet, but I can provide it if needed. 

Anyway, I've a few more leads now. Thanks for your quick response and help !

PS: I just replace the renderer task by a regular thread, and it works like a charm... Thanks again !

**Comment by baldurk** [comment]
The crash happens well after the DLL is injected or before any threads are created. I'm saying there's likely a bug that is present but is only exposed when the memory layout changes and/or the stack is bigger because renderdoc adds extra stack frames. If you're changing rsp manually then that certainly explains the crashes.
