### ISSUE TITLE
Get*ProcAddr naming incompatible with Android loader

### ISSUE THREAD

**Issue by courtney-g** [baldurk/renderdoc#205]
RenderDoc's trace layer uses custom names

  RenderDoc_GetInstanceProcAddr
  RenderDoc_GetDeviceProcAddr

Android's loader does not use the json descriptor. It does know how to find vkGet*ProcAddr and LAYER_NAMEGet*ProcAddr (i.e. VK_LAYER_RENDERDOC_CaptureGetInstanceProcAddr and VK_LAYER_RENDERDOC_CaptureGetDeviceProcAddr).

Would you be okay if the names of these functions were changed to accommodate Android's loader?

**Comment by baldurk** [comment]
So just to clarify, you mean that the android loader doesn't support the json but will automatically concatenate the layer name with Get\*ProcAddr to try and find the function? That should be fine. Calling the functions vkGet\*ProcAddr would be more difficult since I expect to be able to call the *real* vkGet\*ProcAddr in the loader.

Out of interest, without the json how do you know which extensions are supported by the layer?

**Comment by courtney-g** [comment]
> So just to clarify, you mean that the android loader doesn't support the json but will automatically concatenate the layer name with Get*ProcAddr to try and find the function?

Correct. The Android loader will look first for the Get*ProcAddr prepended with the layer name and then with vk.

> Out of interest, without the json how do you know which extensions are supported by the layer?

The Android loader uses the Enumerate(Instance|Device)(Extension|Layer)Properties calls to get what it needs from the layer. If you don't already have those in your layer we'll need to add them if we want to use this layer for Android. As reference, the implementations for the standard validation layers are up-to-date.

Thanks!

**Comment by baldurk** [comment]
I think the Enumerate functions [should be implemented](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/vulkan/vk_tracelayer.cpp#L123-L190) but they might be a bit out of date or rusty since it hasn't been tested. It's a bit annoying to have to duplicate the definitions of the extensions, but I guess it shouldn't be too big a deal at least for the near future.

I'll rename the GetProcAddr functions tonight.

**Comment by baldurk** [comment]
That should do the trick I think.

**Comment by courtney-g** [comment]
Looks good. Thanks!

**Comment by RangerWu** [comment]
So courtney is working on running RenderDoc on android? Will you share the build file? Many thanks!
