### ISSUE TITLE
Python Api controller.SetFrameEvent is too slow， is there any better function can replace this api？

### ISSUE THREAD

**Issue by poople** [baldurk/renderdoc#2051]
## Environment

* RenderDoc version: 1.8.0
* Operating System: window10，18362.959
* Graphics API: opengl es 3.0
* Python version: 3.6  64bit

I try the code sample on python api to do some work on get mesh output， in the sample，I used controller.SetFrameEvent， I found that if too many drawcalls in my rdc file, this api would be too slow, in my computer enviroments, it spend almost 8 seconds to set frame event. But if the rdc file has little drawcalls the api can be faster, about 2 second. I know complicated structure may need more time，but i still be curious about that， is there any better way to complete the function like controller.SetFrameEvent？

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
