### ISSUE TITLE
Save/Save As dialog, default capture filename in save / save as dialog is not set

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2067]
## Description
Currently when making new capture, name of a capture is set in main window. But after clicking "save"/"save as" this default name isn't set in a dialog, which means every time "save" or "save as" is set, user has to reenter filename. I think it would be better to set this default filename to the one set in main window, so user can modify it or leave it as is and is not forced to reenter filename every time.

## Environment
* RenderDoc version: 1.10 (official)
* Operating System: Windows 10
dx11 (but I think issue will be visible on all api's
![rdc_save_feature_adjustment](https://user-images.githubusercontent.com/38103336/95297060-1ff34100-087a-11eb-893f-7b8da0c3fc3e.png)
)

**Comment by baldurk** [comment]
When a temporary capture is opened the name is an auto-generated internal name only, not a default name. It's there only to indicate that a capture is loaded. I don't want to enter a default name into the save dialog that people then need to delete as I expect it will rarely be the name they want, since it is autogenerated based on the executable filename and date&time and doesn't have any meaning or way to distinguish it.

When there's something a program can do automatically that may or may not be wanted, I personally heavily favour not doing it as I think the annoyance of a program 'automatically' doing something you don't want is greatly higher than a program **not** automatically doing something that you might want.

**Comment by ghost** [comment]
Well, I suppose it depends on end user. If I want to save capture I find it annoying to reenter new name each time after capture and this auto generated one is good enough for me.
