### ISSUE TITLE
OpenGL driver: "Couldn't make separable shader program for shader. Errors:" error reported when capturing a frame of a core-profile GL 4.3 app

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#207]
It seems like RenderDoc assumes all forward-compatible GL apps it debugs use separate shader programs, which is not necessarily true.

Here's what happens if I try to run one of my pet project engine's test apps:

1. I boot up TestComputeShaderSSBO test app directly from RenderDoc, after disabling GL_ARB_multi_bind support in the engine (*). 
2. I capture one frame and then kill the app.
3. When the frame is being loaded, the following calamity occurs:

![image](https://cloud.githubusercontent.com/assets/9154207/13613791/d591685a-e56d-11e5-906a-35c50646f526.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13613797/dc833c92-e56d-11e5-81dd-cc930b39a2be.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13613813/ec0377cc-e56d-11e5-9df4-6c8850f660b7.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13613832/ffbf7770-e56d-11e5-8969-376d31ae5a56.png)

(*) I have not looked at this closer yet, but it seems like there's something fishy going on with GL_ARB_multi_bind's support in RenderDoc. I'm going to have a look at this later tonight .

To reproduce,

* Clone https://github.com/kbiElude/Emerald
* Modify src/ogl/ogl_context, so that l. 1933 is as in the picture below:

![image](https://cloud.githubusercontent.com/assets/9154207/13613922/67c8a97c-e56e-11e5-8004-66c657d633a7.png)

* Build the solution. Some of the projects will fail to build. That's fine - I'm redesigning the underlying engine for proper Vulkan support. What matters is that the discussed app builds & runs.
* Follow the steps described in the beginning.

I'm seeing this issue on NV driver v356.39. Intel driver dies when RenderDoc sets up (sigh).

**Comment by kbiElude** [comment]
Oh, I just noticed RenderDoc does not report support for sparse buffers. This may ultimately mean this is an app-side issue. Let me close the issue for now. I'll re-open it if I run into this again after patching my project first.

**Comment by baldurk** [comment]
Yes I don't support any of the sparse or bindless extensions.

As to MakeSeparableShaderProgram() failing, that in theory shouldn't happen as long as the original shader compiles successfully. If it does fail then that's a bug - maybe the patching is failing on that shader because of the #ifdefs and #extensions ? What I try to do is patch up the shader so it can be built as separable by inserting the gl_PerVertex block redeclarations (which is *such* a stupid requirement...) but it's hard to insert it in the right place.

**Comment by kbiElude** [comment]
Fixed the sparse buffer issue in my app, and I'm still hitting the same error. Reopening, I think I'm going to need your eyes on this.

Haven't analyzed what happens inside RenderDoc. Let me know if you don't have the bandwidth right now to investigate this - I might be able to find some time for a bug-hunting session tomorrow evening.

**Comment by baldurk** [comment]
Yeh as above, it is probably the shader patching to make it separable-compatible (I say again, that is a *bass-ackwards* requirement) going wrong. With a repro shader it shouldn't be hard to identify the problem, but if the fix isn't simple I won't have time.

**Comment by kbiElude** [comment]
There we go:

```
#version 430 core

#ifdef GL_ES
    precision highp float;
    precision highp samplerBuffer;
#else
    #extension GL_ARB_shader_storage_buffer_object : require
#endif

buffer dataSSB
{
    restrict readonly vec4 data[];
};

uniform VSData
{
    int   n_origin_character;
    float scale;
};

out vec2 vertex_shader_uv;


void main()
{
   int   character_id    = gl_VertexID / 6;
   vec2  vertex_data;

    switch (gl_VertexID % 6)
    {
        case 0: vertex_data = vec2(0.0, 1.0); break;
        case 1: vertex_data = vec2(0.0, 0.0); break;
        case 2:
        case 3: vertex_data = vec2(1.0, 0.0); break;
        case 4: vertex_data = vec2(1.0, 1.0); break;
        case 5: vertex_data = vec2(0.0, 1.0); break;
    }

   vec2  x1_y1_origin = data[n_origin_character * 2].xy;
   vec4  x1_y1_u1_v1  = data[character_id * 2];
   vec4  u2_v2_w_h    = data[character_id * 2 + 1];
   float u_delta      = u2_v2_w_h.x - x1_y1_u1_v1.z;
   float v_delta      = u2_v2_w_h.y - x1_y1_u1_v1.w;

   x1_y1_u1_v1.xy   = x1_y1_u1_v1.xy * vec2(2.0) - vec2(1.0);
   x1_y1_origin     = x1_y1_origin   * vec2(2.0) - vec2(1.0);
   gl_Position      = vec4(x1_y1_u1_v1.x + (1.0 - scale) * (x1_y1_origin.x - x1_y1_u1_v1.x) + scale * (vertex_data.x * u2_v2_w_h.z * 2.0),
                           x1_y1_u1_v1.y + (1.0 - scale) * (x1_y1_origin.y - x1_y1_u1_v1.y) + scale * (vertex_data.y * u2_v2_w_h.w * 2.0),
                           0.0, 1.0);
   vertex_shader_uv = vec2(vertex_data.x * u_delta +       x1_y1_u1_v1.z, 
                          -vertex_data.y * v_delta + 1.0 - x1_y1_u1_v1.w);
}
```

**Comment by baldurk** [comment]
Well, I've fixed *this* particular case/shader. The problem was that the gl_PerVertex redeclaration was being inserted inside the #ifdef GL_ES. I've added code to skip over precision statements so hopefully this will land it in the right place.

However it shows the obvious flaw, you could break it again just by doing this:

```cpp
#if FOO
float blah;
#endif
```

With FOO being a macro that you don't define anywhere. The block will be inserted inside, do nothing, and the separable program will continue to fail.

That case could be fixed by only ever inserting the block outside of any preprocessor ifs, but then what if someone surrounds their whole shader in the equivalent of `#if 1 ... #endif`. You can't win.

Really the only reliable way to do this would be to construct a full pre-processor to parse every #if and figure out if it's active or not, so we can get to the first real bit of code and insert the block there. I utterly refuse to add all that complexity just for a completely pointless and stupid requirement for separable programs that shouldn't be there in the first place.

**Comment by kbiElude** [comment]
:+1:
