### ISSUE TITLE
Vulkan driver: Text atlas image is created for concurrent sharing but no compatible queue families are specified at creation time

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#208]
For concurrent sharing, queueFamilyIndexCount and pQueueFamilyIndices specify which family queues an object is going to be used with. However, in _VulkanDebugManager::VulkanDebugManager()_, the text atlas image is initialized with the following VkImageCreateInfo descriptor:
![image](https://cloud.githubusercontent.com/assets/9154207/13634137/edeb18de-e5f3-11e5-972f-8de03d5e0c6d.png)

**Comment by kbiElude** [comment]
Same story's with m_pPickPixelImage:

![image](https://cloud.githubusercontent.com/assets/9154207/13634217/a7fab090-e5f4-11e5-84e2-2f5457232da7.png)

**Comment by baldurk** [comment]
Hmm, this was maybe me being overzealous and not a little bit lazy trying to fix some validation errors that were complaining about using EXCLUSIVE mode. I might also have been mislead since there was at least one validation error that was firing wrongly. I'll check. Try reverting 7f73ecc02a835499390aed734ae898264aef2e8e.

Ultimately once I support multiple queues I will need a way to access and/or transfer ownership of objects between queues but for the moment I just want to do whatever is needed to not have to worry about it :P.

**Comment by kbiElude** [comment]
Here's one more image which is initialized incorrectly:

![image](https://cloud.githubusercontent.com/assets/9154207/13634484/2a2ebd80-e5f6-11e5-9138-5e646461eaa8.png)

That one comes from WrappedVulkan::EndFrameCapture().

For the time being, in order to work around past these issues, I simply force all images that get in my way to use exclusive mode, but thanks for the tip :)

**Comment by kbiElude** [comment]
..and then we also have a number of images created in VulkanReplay::OutputWindow::Create() which also need to be taken care of :)

**Comment by baldurk** [comment]
Right, now I remember why I moved them to `CONCURRENT` - if I use `EXCLUSIVE` then the image layouts need to move them into a queue rather than just passing `QUEUE_FAMILY_IGNORED` around. It's probably the simpler fix to revert the change to CONCURRENT since for right now I only have one queue. Probably ultimately I will move back to CONCURRENT and list all queue families.

**Comment by baldurk** [comment]
OK, back to EXCLUSIVE but to keep the validation layers happy I now use queue family 0 for image barriers at least initially moving from UNDEFINED layout to something useful. This will need to be fixed later but I assume in other places that we only have one queue so this doesn't break anything worse :).

**Comment by kbiElude** [comment]
You may want to consider enumerating available queue families and ensuring that the queue family you use is the one that supports compute & gfx operations. For instance, our hardware reports three different queue families, and only one of them is universal. If the app picked any of the other two, RenderDoc would likely crash or - at best - malfunction.

**Comment by baldurk** [comment]
Yeh this is what I meant that it is a stop-gap fix just to not break it any worse than it was before, until I can properly support multiple queues :).

**Comment by DominikWitczakAMD** [comment]
Does the trick for now! Thanks!
