### ISSUE TITLE
RenderDoc remote replay crash

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [baldurk/renderdoc#2082]
Hi,
I tried to replay a vulkan capture using a remote session.
Here's the process:
1) captured trace on Linux PC running Vulkan
2) opened trace file on macOS using renderdoc v1.10
3) on linux PC ran: renderdoccmd remoteserver -h <hostname> to start remote server
4) on mac PC: opened qrenderdoc, and selected remote target, and then tried to replay the capture

I get the following crash:

-[NSOpenGLContext setView:] must be called from the main thread.

Here's the trace:

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff66de425a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff66de45d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2f5ffd0b __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff2f5fe8e7 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff2f5fdbd3 CFRunLoopRunSpecific + 499
5   com.apple.HIToolbox           	0x00007fff2e15365d RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff2e15339d ReceiveNextEventCommon + 600
7   com.apple.HIToolbox           	0x00007fff2e153127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff2c7c3ba4 _DPSNextEvent + 990
9   com.apple.AppKit              	0x00007fff2c7c2380 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
10  libqcocoa.dylib               	0x0000000109291625 0x109259000 + 230949
11  org.qt-project.QtCore         	0x0000000106b4ffb7 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 439
12  org.qt-project.QtWidgets      	0x0000000105e6102e QDialog::exec() + 510
13  org.renderdoc.qrenderdoc      	0x0000000104d67bef ShowProgressDialog(QWidget*, QString const&, std::__1::function<bool ()>, std::__1::function<float ()>, std::__1::function<void ()>) + 799
14  org.renderdoc.qrenderdoc      	0x0000000104d3593e CaptureContext::LoadCapture(rdcstr const&, ReplayOptions const&, rdcstr const&, bool, bool) + 2750
15  org.renderdoc.qrenderdoc      	0x0000000104de8224 MainWindow::LoadCapture(QString const&, ReplayOptions const&, bool, bool) + 3124
16  org.renderdoc.qrenderdoc      	0x0000000104de7094 MainWindow::LoadFromFilename(QString const&, bool) + 212
17  org.renderdoc.qrenderdoc      	0x0000000104de6529 MainWindow::on_action_Open_Capture_triggered() + 345
18  org.renderdoc.qrenderdoc      	0x000000010517deae MainWindow::qt_metacall(QMetaObject::Call, int, void**) + 62

Please advise?
Is it supported to replay on a different OS (e.g. capture on Linux and replay on macOS using remote Linux host)?

Thanks,
Jeff

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
