### ISSUE TITLE
Unable to capture Vulkan frame on S20 5G

### ISSUE THREAD

**Issue by pauloAndroid** [baldurk/renderdoc#2084]
# Description
Unable to capture Vulkan frame on Galaxy S20 5G. I am able to reproduce issue with Khronos sample application. Will send built application over email.

## Steps to reproduce
* Build Vulkan Samples for Android (https://github.com/KhronosGroup/Vulkan-Samples).
* Launch application via RenderDoc.
* Select Hello Triangle on app.
* Wait for triangle to be displayed on phone.
* Select "Capture Frames immediately". Nothing shows up. The application shows “Inactive Window” on the top Renderdoc overlay.
![khronos-vulkan-hello-triangle-renderdoc](https://user-images.githubusercontent.com/73263411/97635342-70326e80-19f4-11eb-9c91-f8e2e57c6e44.png)
![khronos-vulkan-hello-triangle-renderdoc-UI](https://user-images.githubusercontent.com/73263411/97635352-74f72280-19f4-11eb-877c-b40406747862.png)

## Environment
- RenderDoc version: 1.10
- Host OS: Windows 10
- Device model: Galaxy S20 5G
- Android Version: 10
- Graphics API: Vulkan
- GPU: Adreno 650

**Comment by baldurk** [comment]
I can look into this tomorrow to check if something is misbehaving but typically this happens when the application creates multiple swapchains for multiple windows. It's unusual but not impossible on a mobile device, and if that's the case then this is behaving as expected.

You can usually see this in the diagnostic log if you look, and in the connection panel you can cycle the active window to get to the one that's displaying currently.

**Comment by baldurk** [comment]
As above this is working as intended. The application creates two windows; the first one uses GLES seemingly for the menu. The second window is created in vulkan but since the first GLES window still exists the vulkan window doesn't become active by default unless explicitly selected by cycling the active windows.

**Comment by pauloAndroid** [comment]
Thank you. I was able to do the capture once I cycled the active window.
