### ISSUE TITLE
Python - tkinter Import Fail

### ISSUE THREAD

**Issue by Waffle1434** [baldurk/renderdoc#2092]
## Description
Attempting to follow the [display texture in window](https://renderdoc.org/docs/python_api/examples/renderdoc/display_window.html) python example, but I'm getting the error: 
`ModuleNotFoundError: No module named 'tkinter'`

Verified tkinter is installed using `python -m tkinter`:
![image](https://user-images.githubusercontent.com/8021358/98912431-1d48c480-2494-11eb-8795-e661ba907dca.png)

## Steps to reproduce

Attempt to import tkinter in the python shell:
`import tkinter`

## Environment

* RenderDoc version: 1.10
* Operating System: Windows 10
* Graphics API: DirectX 11
* Python: 3.9
* Tk: 8.6

**Comment by baldurk** [comment]
RenderDoc distributes its own python interpreter and libraries so that it doesn't require anything installed on the system, which means that the modules available are only those it comes with - and `tkinter` is not one of them. To use `tkinter` or any other module you install into your own python you have to use the standalone python module, not the python shell within RenderDoc.

The documentation page you linked to states this:

> This is intended for use with the python module directly, as the UI already has a texture viewer panel to do this with much more control. The principle is the same though and it can be useful reference of how to iterate over a capture.
