### ISSUE TITLE
Inject into process by PID Linux

### ISSUE THREAD

**Issue by bhaktatejas922** [baldurk/renderdoc#2094]
## Description
Trying to use renderdoc on Debain (Ubuntu 18.04) to inject into chrome process. Wondering if the READMe is correct in saying injection does not work on linux? Saw in the --help that it has an inject method so wasn't sure if the READme was out of date

## Steps to reproduce

Install Chrome on ubuntu 18.04
start chrome: google-chrome --disable-gpu-sandbox --gpu-startup-dialog 
Run ./renderdoccmd inject --PID _________
  Injecting into PID 30870
  Failed to inject: RenderDoc injection failed

## Environment

* RenderDoc version: 1.10
* Operating System: Ubuntu 18.04
* Graphics API: XXX

GPU: AMD® Radeon (tm) r9 fury series

**Comment by baldurk** [comment]
I don't know what you're talking about with the README as it doesn't mention this at all, but yes injecting into processes is not supported on linux. I highly recommend against injecting into processes anyway as it is almost never the right thing to do and can cause unexpected problems, so you should run your program from RenderDoc regardless. In addition renderdoccmd is an internal tool that should not be used by users.

I also do not support capturing chrome at all due to the high incidence of scum who use RenderDoc for copyright infringement.
