### ISSUE TITLE
I can't capture my application

### ISSUE THREAD

**Issue by kissyoung** [baldurk/renderdoc#2106]
## Description

Capture the Opengles application on the Huawei Mate40. All texture resources and shaders can‘t be obtained.

## Steps to reproduce

1.Prepare a Mate40 series mobile phone.
2. install application com.gomdev.shader(download from github. Any application has this problem.)
3. launch this application such as com.gomdev.shader/com.gomdev.shader.MainActivity.
4.capture Frame Immediately.

Only mate40 series mobile phone has this problem.
If you don't have an environment to reproduce the problem, you can provide a log version, and I'll capture and send it to you.

## Environment

* RenderDoc version: v1.11
* Operating System: android
* Graphics API: gles

[1.zip](https://github.com/baldurk/renderdoc/files/5628847/1.zip)

**Comment by baldurk** [comment]
If this only happens on one device then it's quite likely to be a bug in the device itself. Unfortunately android is a terrible platform where many devices differ in behaviour from the standard, and there is very little that is required by android itself so almost everything can be customised and changed by the device.

I only have a small number of android devices for testing and this isn't one of them. Can you please explain what actually goes wrong and what exactly you see when you load the capture? I need more information to understand the problem.

Your steps to reproduce are quite generic and don't actually describe the **problem** at all. If you can't describe what goes wrong you could record a video, and you can also upload the diagnostic log from help -> view diagnostic log. If you're able to make a capture but it can't be opened, uploading the capture file could also help.

**Comment by kissyoung** [comment]
sorry,The 1.zip file is an incorrect attachment. I intended to upload the log and rdc files.

[test6.log](https://github.com/baldurk/renderdoc/files/5633136/test6.log)

![test6_resourcelist](https://user-images.githubusercontent.com/63411287/100953204-0b1aed00-354d-11eb-879f-fa2cee3e33b9.PNG)

![test6](https://user-images.githubusercontent.com/63411287/100953121-dc9d1200-354c-11eb-9a4e-5b5925989915.PNG)
![test6_textureview](https://user-images.githubusercontent.com/63411287/100953385-78c71900-354d-11eb-8028-3ed48a371e4e.PNG)

**Comment by baldurk** [comment]
You still haven't explained what the actual problem is, can you please say specifically what is actually wrong?

The log indicates some application errors - there are some lines about invalid buffers and shaders passed to functions, which you should check your application for:

```
ADRD 031725: [13:26:29]  gl_buffer_funcs.cpp(2507) - Error   - Assertion failed: 'record' Couldn't identify implicit object at binding. Mismatched or bad GLuint? (target=GL_ELEMENT_ARRAY_BUFFER)
ADRD 031725: [13:26:29]  gl_buffer_funcs.cpp(2512) - Error   - glMapBufferRange: Couldn't get resource record for target 8893 - no buffer bound?
ADRD 031725: [13:26:29]  gl_buffer_funcs.cpp(2802) - Error   - glUnmapBuffer: Couldn't get resource record for target GL_ELEMENT_ARRAY_BUFFER - no buffer bound?
ADRD 031725: [13:26:29]  gl_shader_funcs.cpp(1302) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=1)
ADRD 031725: [13:26:29]  gl_shader_funcs.cpp(1302) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=4)
ADRD 031725: [13:26:31]  gl_shader_funcs.cpp(1302) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=10)
ADRD 031725: [13:26:31]  gl_shader_funcs.cpp(1302) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=16)```

**Comment by kissyoung** [comment]
The problem is：
All draws replay are black images.

The following is my analysis：
I found the root cause of the problem was capturing.Because RDC does not save all the textures and shaders used by the app.
In addition, I have found that the Mate40 does process the gles layer differently. The glGenTextures  API is not called to the layer and therefore is not intercepted.It may have some processing performed in the framework and cannot be processed at the layer.If that's the case, is there any other way to intercept it? Or we can't intercept it right now.

**Comment by baldurk** [comment]
Can you share the capture file? Or if you can't share the capture itself then screenshots of the drawcalls that are black and the texture viewer inputs/outputs and the pipeline state at that point?

Please don't tell me what you think the problem is because you may be mistaken with your analysis, and that will only cause further confusion and difficulty. Please provide only the direct information that you find.

The GLES layering has been broken on android devices before. RenderDoc tries to detect some cases but if it's broken in a new way then that may not easily be fixable.

**Comment by kissyoung** [comment]
[test7.log](https://github.com/baldurk/renderdoc/files/5635844/test7.log)
If you need more information, please let me know.
![test7_textureview](https://user-images.githubusercontent.com/63411287/101015437-5f9c8780-35a2-11eb-88f2-19b9967a47cd.PNG)

![test7_piplineVTX](https://user-images.githubusercontent.com/63411287/101015592-9a9ebb00-35a2-11eb-9ebb-1e86a6304756.PNG)

![texture7_piplineVS](https://user-images.githubusercontent.com/63411287/101015614-a1c5c900-35a2-11eb-984b-e55750561da9.PNG)

![test7_piplineFB](https://user-images.githubusercontent.com/63411287/101015121-de44f500-35a1-11eb-8888-24c30592790a.PNG)

![test7_piplineRas](https://user-images.githubusercontent.com/63411287/101015124-e00eb880-35a1-11eb-8934-0c328855b554.PNG)

[test7_rdc.zip](https://github.com/baldurk/renderdoc/files/5635918/test7_rdc.zip)

**Comment by kissyoung** [comment]
And The following example is used for the rdc captured.
https://github.com/zesty98/opengl-es-shader
You can also give me an app you want to test, if it's convenient.

**Comment by baldurk** [comment]
The capture doesn't seem to have any shaders created or programs bound. Looking at the source code in that repository I can't see anywhere that calls any program or shader functions like glCreateProgram, glUseProgram, glShaderSource, glCompileShader, glAttachShader. If this is using OpenGL ES 1.0 fixed function pipeline functionality then that is not supported by RenderDoc.

I'm unable to compile that project to check it in more detail. I don't have much experience on building programs for android, I have the latest version of android studio but after fixing some errors and problems I get to the error "error: package com.gomdev.gles does not exist" and I'm not sure where it should come from. If you can give me instructions on how to build it I can investigate further, or else if you can share an APK I can install and run it directly.

I don't have any android apps for testing, I only ever debug other people's apps when there is a problem. Searching google [this repository](https://github.com/JimSeker/opengl) seems to be up to date and maintained. Can you run the `OpenGL30Cube` sample there?

Or [this repository](https://github.com/the3deers/android-3D-model-viewer) is a bit more complex but uses textures, can you run that? I've uploaded the apk too:  I clicked on `Demo` to get a model rendering with textures and different shaders. Because that sample creates multiple GLES windows, you'll either need to click `Cycle Active Window` in renderdoc to select the one rendering the plane, or wait a few seconds until it becomes active.

I've uploaded the APKs for [OpenGL30Cube](https://github.com/baldurk/renderdoc/files/5636287/opengl30cube.zip) and [android-3D-model-viewer](https://github.com/baldurk/renderdoc/files/5636281/model-viewer.zip) in case that helps. They are test APKs so I install them with `adb install -g -t -r ....apk`. If you have problems with these samples can you share the capture file and diagnostic log?

**Comment by kissyoung** [comment]
Here are the rdc and logs captured using OpenGL30Cube apk on mate40 device.
[test_3Dcube.log](https://github.com/baldurk/renderdoc/files/5640124/test_3Dcube.log)
[test_3dcube.zip](https://github.com/baldurk/renderdoc/files/5640127/test_3dcube.zip)
![test_3dcube](https://user-images.githubusercontent.com/63411287/101112484-5cdc7980-3618-11eb-8779-13d12c9499e1.PNG)

**Comment by baldurk** [comment]
That's strange, this capture is completely empty. Can you try to increase the number of frames to 5 in the `Capture X Sequential Frame(s)` before clicking capture, and see if any of those frames have rendering in them?

I also see that the log still has errors about invalid objects being passed to GL functions. I guess that means this invalid code comes from a system library on your device, and it's not the first time I've found android system libraries to be broken in serious ways. Unfortunately there's nothing that can be done about that except hope it doesn't cause too serious problems.

**Comment by kissyoung** [comment]
I also tried arm's tools(arm MS graphics Analyzer 2020.2version), which also couldn't intercept any useful api,only some eglSwapbuffers. So I think the mate 40 device made some modifications to the layer.If that's true, I don't know if there's any other way to intercept.
[test9_capture5.log](https://github.com/baldurk/renderdoc/files/5642451/test9_capture5.log)
[test9_capture5_1_5.zip](https://github.com/baldurk/renderdoc/files/5642455/test9_capture5_1_5.zip)
![test9_capture5](https://user-images.githubusercontent.com/63411287/101159967-3266dc80-3669-11eb-99e8-7056c2a9dbaa.PNG)

**Comment by baldurk** [comment]
I've uploaded a special build with logging [here](https://renderdoc.org/RenderDoc_android_logging_64.zip). Can you download and run that build, it will need to reinstall the renderdoc server on the device.

If you launch the OpenGL30Cube apk and take a capture, then close the app once the capture has completed because it will be logging quite a lot. Upload the logfile from that please.

**Comment by kissyoung** [comment]
[test11.log](https://github.com/baldurk/renderdoc/files/5643827/test11.log)

new version log

**Comment by baldurk** [comment]
Thanks for that, something is definitely strange. Can you use adb logcat to retrieve the log directly from the device? Ideally if you can clear logcat, then run the same test, then save the log and upload it. I think RenderDoc's logcat processing has missed some lines which could be important.

Just to check, does your device have any special optional developer settings that would need to be enabled? A similar problem came up in #2041 where it turned out to be that the device had a special device-specific option which blocked proper functioning. I added some checks to try and detect that case and fallback to an alternative method, but they may not work perfectly.

**Comment by kissyoung** [comment]
I am not sure if there have any special optional developer settings that would need to be enabled. I can screenshot it to you.
![Uploading Screenshot_20201205_002418_com.android.settings.jpg…]()

this is logcat:
[test12.log](https://github.com/baldurk/renderdoc/files/5644021/test12.log)

**Comment by baldurk** [comment]
You need to wait for the upload to finish before posting the comment, the screenshot didn't come through.

**Comment by baldurk** [comment]
I've uploaded a new logging build [here](https://renderdoc.org/RenderDoc_android_logging2_64.zip) which also reverts to a different hooking mechanism which doesn't use the android layers. Can you try the same experiment with it and upload the logcat output? And also see if this works for you.

**Comment by kissyoung** [comment]
[rdc_log.log](https://github.com/baldurk/renderdoc/files/5647264/rdc_log.log)
[logcat.log](https://github.com/baldurk/renderdoc/files/5647265/logcat.log)
[error_screenshot.zip](https://github.com/baldurk/renderdoc/files/5647267/error_screenshot.zip)
This version can't capture.

**Comment by baldurk** [comment]
That's unfortunate. As far as I can tell from the earlier information the manufacturer of your device has fundamentally broken the layering system that RenderDoc normally uses to work on Android 10 and above, whether deliberately or through incompetence is not clear.

I was hoping that this version which falls back to the old version of hooking would work, which might mean the possibility of some fallback path for broken devices, but it was a bit unreliable even before and it may also have been deliberately broken by the manufacturer.

I don't think there's anything more I can do, your manufacturer has broken your device and unfortunately Android makes no guarantees that this system will work.
