### ISSUE TITLE
libSPIRV-Tools.so has been renamed

### ISSUE THREAD

**Issue by foreverWIP** [baldurk/renderdoc#2113]
## Description

Upon attempting to run `qrenderdoc` from the terminal, I got only this message:
```
qrenderdoc: error while loading shared libraries: libSPIRV-Tools.so: cannot open shared object file: No such file or directory
```
After doing some snooping in /usr/lib I noticed that at some point the files provided by my distro's `spirv-tools` package were changed to static libraries, with the shared version renamed to `libSPIRV-Tools-shared.so`. I tried using a symbolic link to it with the proper name but still got the same error, only with it looking for `libSPIRV-Tools-opt.so`. Considering the renderdoc package has me stuck on an older version, I'll try building 1.11 later and see if it also has the issue.

## Environment

* RenderDoc version: 1.6
* Operating System: Ubuntu 20.04.1 LTS
* Graphics API: Mesa 20.0.8

**Comment by baldurk** [comment]
RenderDoc does not build or link against SPIRV-Tools at all, so this must be a problem with your distribution's package which has somehow pulled in a dependency that the project doesn't even have. Unfortunately I can't be responsible for supporting distribution packages, especially those that make significant changes to the build process, so you'll need to report this bug elsewhere.

If you build RenderDoc from source and have problems please open another issue. You could also try the binary releases I provide on renderdoc.org, though unfortunately due to the nature of linux these may not work as distributing binaries is difficult to make completely portable.
