### ISSUE TITLE
The time which the glInvalidateFrameBuffer function spend seems to be wrong.

### ISSUE THREAD

**Issue by chena1982** [baldurk/renderdoc#2115]
When i profile on SamSung S20, i found that glInvalidateFrameBuffer function seems to use too much time.

![1111](https://user-images.githubusercontent.com/5953033/102061427-6c389f80-3e2e-11eb-9907-81f5a6926686.png)

when i use snapdragon profiler, it seems the glInvalidateFrameBuffer function is very fast.

![image](https://user-images.githubusercontent.com/5953033/102061611-a73ad300-3e2e-11eb-96b4-4d8f2e32ddda.png)

glInvalidateFrameBuffer is in the glClear
![image](https://user-images.githubusercontent.com/5953033/102061684-be79c080-3e2e-11eb-9b30-67433b4c8f00.png)

So, is the renderdoc get the wrong time or the snapdragon profiler get wrong time?

I create a simple project to reproduce the problem, it's a unity project:

[testshadow.zip](https://github.com/baldurk/renderdoc/files/5687704/testshadow.zip)

If you can't test it on android, you can test it on windows, set project api to opengles, you can test the function time use renderdoc and nsight, you will get similar result.

![image](https://user-images.githubusercontent.com/5953033/102066390-b9b80b00-3e34-11eb-8180-0a39e19213ae.png)

It seems renderdoc fill the RT with string "invalidate", is this process use too much time?

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
