### ISSUE TITLE
Hang when inspecting a vulkan draw call 

### ISSUE THREAD

**Issue by wilberton** [baldurk/renderdoc#2122]
I'm seeing a hang with a particular vulkan capture when clicking on any draw call in the event browser. It seems to be stuck in a loop in Editor::SetName in spirv_editor.cpp line 200, because the offset in the iterator is never increasing despite the call to ++it. 
It's 100% reproducable here, I may be able to share a capture privately, but I'd have to check with my superiors first.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
