### ISSUE TITLE
build error 127 in Linux----recipe for target 'qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure'

### ISSUE THREAD

**Issue by zxl5595** [baldurk/renderdoc#2125]
I have build renderdoc with Ubuntu. When I run the command "make -C build", I have faced the error 127 "recipe for target 'qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure'".  I also meet error 2 "*** [qrenderdoc/CMakeFiles/custom_swig.dir/all] ".

I saw there is a similar error someone found in OSX, I have tried to remove "> /dev/null 2>&1" in renderdoc/qrenderdoc/CMakeList.txt, but it doesn't work.  How can I solve this problem?

I have meet some problems to attached screenshot with this issues. There is the text blew:

[ 94%] Performing configure step for 'custom_swig'
qrenderdoc/CMakeFiles/custom_swig.dir/build.make:127: recipe for target 'qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure' failed
make[2]: *** [qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure] Error 127
make[2]: Leaving directory '/home/z00575165/Desktop/Renderdoc/renderdoc-1.x/build'
CMakeFiles/Makefile2:619: recipe for target 'qrenderdoc/CMakeFiles/custom_swig.dir/all' failed
make[1]: *** [qrenderdoc/CMakeFiles/custom_swig.dir/all] Error 2
make[1]: Leaving directory '/home/z00575165/Desktop/Renderdoc/renderdoc-1.x/build'
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/z00575165/Desktop/Renderdoc/renderdoc-1.x/build'

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
