### ISSUE TITLE
Warning Querying ID3D11Device for unknown/unhandled interface: GUID {26c5dc23-e49c-4b0a-8f79-e7b1ac804d32}

### ISSUE THREAD

**Issue by gig67** [baldurk/renderdoc#2127]
I am new to this software (thanks for writing it!) and apologize in advance for lack of clarity. I am trying to capture a few buildings from Google Maps into Blender via RenderDoc.

I start Chrome in Debug mode without "OK" to the PID modal message box (PID 6232). 
I inject the Process with RenderDoc, which works fine (11:07). At this point there is connection with the process but no API associated to it in RenderDoc
When I then OK the PID modal messagebox (11:10), the connection is closed by remote host
I tried this several times with no difference.
The log is below. I use Win 10 with a Dell Latitude e7240 and an Intel HD Graphics 4400 card with drivers just recently updated.

RDOC 005052: [11:07:40]    win32_process.cpp( 597) - Log     - Injecting renderdoc into process 6232
RDOC 006232: [11:07:40]             core.cpp( 440) - Log     - RenderDoc v1.11 Windows 64-bit Release (c5480aa622a2f5447c87d23ccc0b08fb320b0169) capturing application
RDOC 006232: [11:07:40]             core.cpp( 282) - Warning - Disabling crash handling server due to detected chrome.
RDOC 006232: [11:07:40]         settings.cpp( 460) - Log     - Loading config from C:\Users\giuli\AppData\Roaming\renderdoc\renderdoc.conf
RDOC 006232: [11:07:40]   win32_libentry.cpp(  66) - Log     - Loading into C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
RDOC 006232: [11:07:40]  sys_win32_hooks.cpp(  82) - Log     - Registering Win32 system hooks
RDOC 006232: [11:07:40]      d3d11_hooks.cpp(  44) - Log     - Registering D3D11 hooks
RDOC 006232: [11:07:40]        amd_hooks.cpp( 151) - Log     - Registering AMD hooks
RDOC 006232: [11:07:40]      nvapi_hooks.cpp( 117) - Log     - Registering nvidia hooks
RDOC 006232: [11:07:40]      d3d12_hooks.cpp( 173) - Log     - Registering D3D12 hooks
RDOC 006232: [11:07:40]       d3d8_hooks.cpp(  36) - Log     - Registering D3D8 hooks
RDOC 006232: [11:07:40]       d3d9_hooks.cpp(  45) - Log     - Registering D3D9 hooks
RDOC 006232: [11:07:40]       dxgi_hooks.cpp( 250) - Log     - Registering DXGI hooks
RDOC 006232: [11:07:40]        egl_hooks.cpp( 941) - Log     - EGL hooks disabled by RENDERDOC_HOOK_EGL environment variable - if GLES emulator is in use, underlying API will be captured
RDOC 006232: [11:07:40]         gl_hooks.cpp( 263) - Log     - Registering OpenGL hooks
RDOC 006232: [11:07:40]        egl_hooks.cpp( 941) - Log     - EGL hooks disabled by RENDERDOC_HOOK_EGL environment variable - if GLES emulator is in use, underlying API will be captured
RDOC 006232: [11:07:40]        wgl_hooks.cpp( 616) - Log     - Registering WGL hooks
RDOC 006232: [11:07:40]         vk_layer.cpp(  99) - Log     - Registering Vulkan hooks
RDOC 005052: [11:07:40]   target_control.cpp( 585) - Log     - Got remote handshake: chrome [6232]
RDOC 006232: [11:10:40]      dxgi_common.cpp(1633) - Warning - Querying IDXGIAdapter for unsupported/undocumented interface: IDXGIAdapterInternal2
RDOC 006232: [11:10:40]             core.cpp(1798) - Log     - Adding D3D11 device frame capturer for 0x000001CDD2775798
RDOC 006232: [11:10:40]     d3d11_device.cpp( 159) - Log     - New D3D11 device created: Intel / Intel(R) HD Graphics Family 20.19.15.5063
RDOC 006232: [11:10:40]      dxgi_common.cpp(1659) - Warning - Querying ID3D11Device for unknown/unhandled interface: GUID {26c5dc23-e49c-4b0a-8f79-e7b1ac804d32}
RDOC 005052: [11:10:55]    win32_network.cpp( 261) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host. 

Thanks in advance for any help you can provide!

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
