### ISSUE TITLE
Cant capture from UE4 Pacakged Game

### ISSUE THREAD

**Issue by OptimisticMonkey** [baldurk/renderdoc#2139]
Hi Baldurk!

Thank you for creating RenderDoc - it is an awesome tool :-)

I am having a problem trying to get a capture from a UE4 Packaged executable.
(I am launching the exe from WindowsNoEditor from RenderDoc with CaptureChildProcesses checked)

The game launches and shows the Render doc stuff in the top left.  F12 seems to take a capture correctly, and even says "1 Captures saved.".

But the captures never show up in the RenderDoc application and the "Capture Frame Immediately" button is disabled.

* RenderDoc version: 1.11
* Operating System: Windows 10 Pro Version	10.0.18363 Build 18363
* Graphics API: D3D11

[UPDATE]
Was testing using the inner (WindowsNoEditor\XXXX\Binaries\Win64)  packaged exe in the Binaries and it works!  Wasnt gonna send bug- but thought you might want to know there is still issue using the "outer" packaged exe.....

Thanks again for making RenderDoc

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
