### ISSUE TITLE
Debug labels can't be collapsed via left arrow key

### ISSUE THREAD

**Issue by ajweeks** [baldurk/renderdoc#2144]
## Description

When navigating the event browser via keyboard debug label sections often can't be collapsed with the keyboard. This behaviour is not perfectly deterministic and sometimes takes a few attempts to reproduce.

## Steps to reproduce

1. Load any capture with debug labels (one attached)
2. Navigate through the event browser with the keyboard, using the right arrow to expand a section
3. Navigate to the node above with up arrow, then back to the open node with down arrow
3. Notice that the left arrow will not collapse the open node, and instead selects that node's parent

![RenderDoc_tree_node gif](https://user-images.githubusercontent.com/4230924/104092879-bb7fbd80-527e-11eb-8424-be19e694d9e2.gif)

Capture with debug labels: https://www.dropbox.com/s/5b4suvc281reurf/Flex_2020_01_09.zip?dl=0

## Environment
* RenderDoc version: 1.12 nightly (c63d222c)
* Operating System: Windows 10
* Graphics API: Vulkan

I tried various previous versions and found this issue present in all versions tested (between 1.12 & 1.0). So it seems the issue has been existed for a long time. Any other application with a similar tree structure (e.g. Unity's scene view or Visual Studio's performance profiler) allows nodes to be collapsed with left arrow.

**Comment by baldurk** [comment]
Does this only happen when you have a horizontal scrollbar in the event browser? I can only reproduce this if I have a horizontal scrollbar _and_ it's scrolled to the right somewhat. If it's at its leftmost point the keyboard shortcuts behave normally.

This behaviour is controlled by Qt so without wholesale reimplementing all the keyboard handling I don't think I can change this. It might be related to the way I move the tree controls into the second column, which IIRC isn't all that well supported by Qt.

If it only fails in this specific situation and not generally in all cases as you describe I can try and look and see if there's a simple way I can fix it, but it may be just a Qt issue that's infeasible to fix.

**Comment by ajweeks** [comment]
Ah, interesting observation. I am seeing the behaviour on my end. The scroll box might be consuming the input event and attempting to scroll left by selecting a different node. Fair enough if it's a Qt issue, at least knowing the cause and having a work around (widening the event browser or shrinking the name column) helps.

**Comment by baldurk** [comment]
It looks like this is [deliberate Qt behaviour](https://github.com/qt/qtbase/blob/dev/src/widgets/itemviews/qtreeview.cpp#L2244-L2247). It only collapses if the scrollbar is all the way to the left, otherwise if keyboard navigation (left to jump to parent when in a non-expandable node) is enabled it goes immediately to the parent and only if there's no parent does it move the scrollbar. I might be able to override just that function with a more sensible implementation.

**Comment by baldurk** [comment]
That commit should tweak the behaviour so that hitting left will move the scrollbar first, and then it will do the normal collapse thing before jumping to the parent node. That said when there's a scrollbar it still acts a little weird because selecting a node will select the name column, and if it's larger than the viewport it will then scroll *right* to fit in as much of the name column. That's more fundamental behaviour and generally makes sense so I wouldn't want to change that even if I can.

I'd recommend resizing either the columns or window to fit so there isn't a scrollbar. Note that if the name is the last column it will get stretched to fit the remaining space, which is the default behaviour. That way you don't get a scrollbar and larger names just get clipped (with the full name appearing in a tooltip).

**Comment by ajweeks** [comment]
Thank you! The behaviour now is as I'd expect it 🙂
