### ISSUE TITLE
RenderDoc records OpenGLES on an Android Vulkan app on Xiaomi Redmi Note 8.

### ISSUE THREAD

**Issue by alecazam** [baldurk/renderdoc#2147]
## Description

My app only uses Vulkan, but there seems to be no way to force only Vulkan to record.   It looks like RenderDoc connects to an ES overlay, but I just see glClear and eglSwapBuffers in the captures.  There is an initial error message on launch, but I'm able to "attach to instance", but it seems like RenderDoc is stuck in "ES" mode.  None of the Vulkan calls are recorded, even with multi-frame capture. 

## Steps to reproduce

1. Set "USB Debugging" in developer mode on the Android device
2. Connect to device from RenderDoc from Windows 10 Pro from MacOS Parallels connected to USB connection
3. Error dialog pops up about "Error connecting to debugger".  Says Android Studio is possibly connected, but that's not the case.  App has isDebuggable set.   See image below.
4. Overlay says "OpenGLES Connected" and there are various timings underneath that.
5. Run "Attach to Instance" and pick the app and #DefaultActivity within that.
6. RenderDoc says "Vulkan (active), OpenGLES (Not Presenting).
7. All captures are not Vulkan, but a tiny ES capture.  See image below.

## Environment

* RenderDoc version: 11.1
* Operating System: WIndows 10 Pro (on Parallels)
* Graphics API: Vulkan on Android 9

## Additional Data

This is the error dialog when Launch is pressed
![image](https://user-images.githubusercontent.com/3750359/104238238-1b589e80-540e-11eb-8c1b-16538a1e2338.png)

This is the capture of ES calls from a Vulkan only application
![image](https://user-images.githubusercontent.com/3750359/104238002-c7e65080-540d-11eb-8b9a-796703928b56.png)

**Comment by baldurk** [comment]
Unfortunately Android is an unreliable and awful platform, and many devices behave in unexpected ways. Xiaomi devices have caused problems in the past. I believe there is a special Xiaomi-only setting that needs to be configured for RenderDoc to work - see #2041. I would recommend trying to use a different device and see if you get better results there, since this seems quite possibly a device bug to me.

RenderDoc can't capture GL commands that aren't there, so there must be some part of your process submitting GL commands. Perhaps you're using a utility framework that uses GL without your knowledge.

Generally speaking if an application uses multiple APIs you can toggle between them by cycling the active window, but this only works if your application only uses one API for each window. I'm unclear what your application does, if you are using multiple APIs on the same window this may not work properly. You would have to use RenderDoc's [in-application API](https://renderdoc.org/docs/in_application_api.html) to specify exactly which device to capture from.

If you can share your application I can try it on a known-good device here and see if I reproduce the problem. Otherwise there's not much I can do without a reproducible test case, and I suspect this is likely either a device or android bug or both.

**Comment by alecazam** [comment]
Well this is our game engine running on Android, so it's not small.  But I think the scenario is worth addressing.   We have Android UI floating view atop the Vulkan rendered view.  The Android UI is the one using ES, and we can't control that AFAIK.   There is also no way to select/focus one view or the other.  They are visually combined.

Most Android apps if they're all ES likely don't encounter this, since they are using the same API.  In this case, certain UI commands happen in ES but the render commands happen in the Vulkan layer.

A preference for capture only (or block) ES or Vulkan would be useful in the GUI to address this.  I never want to see the ES content in this case if that is possible.

**Comment by baldurk** [comment]
Even if it's not small a reproducible test case would be very helpful. If you need to share it privately you can get in contact with me [via email](mailto:baldurk@baldurk.org).

This isn't a problem with Vulkan applications on Android in general, as there are plenty of people debugging that use case. However having two APIs presenting to the same window is likely to hit problems and is not something I intend to support. You could try cycling the active window when connected as they _may_ be detected as if they're two windows, but I don't know if that will work.

I would also still recommend testing another device that doesn't have bugs causing these connection problems, as this may be contributing to the bad behaviour.

Otherwise you would either have to make a build of your game that doesn't use Android UI commands that invoke GL ES, or else use the in-application API linked above to specify which API and window to capture from.

**Comment by alecazam** [comment]
I was able to fix the recording with the "Cycle Active Window" button.  This is my first time using RenderDoc, and so I didn't even see that button.  But that kicked the recording over to the Vulkan command buffer.   

Now I'm trying to figure out why none of our textures and passes have names (we set the in the create info fields), but that's a different issue I guess.  I'm going to close this, since there is a workaround.  Thanks for creating such a nice tool!   I just released my own texture tool at https://github.com/aleczam/kram for dealing with textures and viewing.

**Comment by baldurk** [comment]
That would be consistent with a GLES context existing and presenting, though there's possibly a minor bug if RenderDoc really reported the GLES context as not presenting and it didn't ever update to list it as presenting/active. RenderDoc can't editorialise and decide that your vulkan work is more important than your GLES work and it also can't know, so it's a simple first-come-first serve for which window is active by default and then you can change it later if desired.

I'm not sure what you mean by setting names in create info fields, I don't believe there is any way to provide debug names in a create info struct. Object names in vulkan are specified using `vkSetDebugUtilsObjectNameEXT` from `VK_EXT_debug_utils`, and similarly command buffer or queue level markers are specified with `vkCmdBeginDebugUtilsLabelEXT` etc. (There's a deprecated extension `VK_EXT_debug_marker` but that shouldn't be used for new code).

**Comment by alecazam** [comment]
Sorry, I was thinking of setting names in VMA's createInfo fields.  Yes, we're using the VK_EXT_debug_marker, so that likely needs to be updated.  I found the doc on names here:  https://renderdoc.org/docs/how/how_view_texture.html

**Comment by baldurk** [comment]
VK_EXT_debug_marker will still work, I was suggesting VK_EXT_debug_utils in case you didn't already have any code. Thanks for linking the docs, I should update that for Vulkan. Indeed I don't think VMA's names are passed through to the API this way.

**Comment by alecazam** [comment]
So I found we were requesting those procs for VK_EXT_debug_marker before the device was initialized.  I changed that, but it's like this Redmi on Android 9 doesn't support the extension.   Does RenderDoc's extension running on the phone supply these, or does the device OS natively have to supply the extension?

I don't see that VK_EXT_debug_marker listed in this database for the phone.  Would they leave out something this important?
https://vulkan.gpuinfo.org/displayreport.php?id=10094#extensions

Is support really this small on Android?

![image](https://user-images.githubusercontent.com/3750359/105787212-61941e80-5f33-11eb-829e-96c22b499413.png)

**Comment by baldurk** [comment]
The debug extensions are entirely software only so they don't need OS or driver support, RenderDoc provides them purely in software on any platform. As long as you properly check for them being available before use and have a fallback path if they aren't, you should get markers while capturing with RenderDoc and do nothing otherwise.

This has diverged quite a lot from the original bug report so please stop commenting here. If you have further questions/comments there's an active discord and IRC channel, or you can email me directly.
