### ISSUE TITLE
Build error: offset 25 is out of the bounds [0, 24] of object ‘baseTypeName’

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2151]
Updating RenderDoc sources, calling `cmake` followed by `make`, got me the following error:

```
[  0%] Built target rdoc_arm
[  1%] Built target renderdoc_libentry
[  1%] Built target rdoc_version
[ 30%] Built target rdoc
[ 30%] Built target include-bin
[ 41%] Built target rdoc_gl
[ 55%] Built target rdoc_vulkan
[ 69%] Built target rdoc_spirv
[ 71%] Built target rdoc_amd
[ 72%] Built target rdoc_intel
[ 93%] Built target renderdoc
[ 96%] Built target custom_swig
[ 97%] Built target swig-bindings
[ 97%] Generating QRenderDoc
compiling renderdoc_python.cxx
In file included from ../../renderdoc/api/replay/renderdoc_replay.h:56,
                 from renderdoc_python.cxx:4358:
In member function ‘void rdcstr::insert(size_t, const char*, size_t)’,
    inlined from ‘void rdcstr::append(const char*, size_t)’ at ../../renderdoc/api/replay/rdcstr.h:325:61,
    inlined from ‘rdcstr& rdcstr::operator+=(const char*)’ at ../../renderdoc/api/replay/rdcstr.h:602:11,
    inlined from ‘static swig_type_info* TypeConversion<T, isEnum>::GetTypeInfo() [with T = D3D11Pipe::ConstantBuffer; bool isEnum = false]’ at ../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:43:18,
    inlined from ‘static int TypeConversion<T, isEnum>::ConvertFromPy(PyObject*, T&) [with T = D3D11Pipe::ConstantBuffer; bool isEnum = false]’ at ../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:51:44,
    inlined from ‘static int TypeConversion<rdcarray<U>, false>::ConvertFromPy(PyObject*, rdcarray<U>&, int*) [with U = D3D11Pipe::ConstantBuffer]’ at ../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:579:49:
../../renderdoc/api/replay/rdcstr.h:379:11: error: ‘void* memcpy(void*, const void*, size_t)’ offset 25 is out of the bounds [0, 24] of object ‘baseTypeName’ with type ‘rdcstr’ [-Werror=array-bounds]
  379 |     memcpy(str + offset, instr, length);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from renderdoc_python.cxx:4362:
../../qrenderdoc/Code/pyrenderdoc/pyconversion.h: In static member function ‘static int TypeConversion<rdcarray<U>, false>::ConvertFromPy(PyObject*, rdcarray<U>&, int*) [with U = D3D11Pipe::ConstantBuffer]’:
../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:42:12: note: ‘baseTypeName’ declared here
   42 |     rdcstr baseTypeName = TypeName<T>();
      |            ^~~~~~~~~~~~
In file included from ../../renderdoc/api/replay/renderdoc_replay.h:56,
                 from renderdoc_python.cxx:4358:
```
A few more errors that look exactly like this follow.

## Environment

Revision: ee5d3f5837803a12d47bdcd8e4471bb93c5e8cf9
OS: Linux ant 5.10.7-168.current
GCC:  gcc (Solus) 10.2.0

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by kvark** [comment]
Bah, that's rather unsettling. There is all the information in the issue, I don't see a reason to dismiss it.
