### ISSUE TITLE
Incorrect line counter

### ISSUE THREAD

**Issue by LuridHound** [baldurk/renderdoc#2161]
## Description
Let's return to the issue :
https://github.com/baldurk/renderdoc/issues/2160
I've checked the same on my work project. I see the same problem.
Due to NDA, I cannot provide any capture or application.
It looks like this is the problem of indexing.

## Steps to reproduce
 
 
1)    Open a command with in Event browser with any EID.
2)   Go to Pipeline State window.
3)    Choose any shader.
4)   Click on "View" near the shader.
5)   Press "Crtl" + "F" and write down any string that is contained in the disassembly window.
6)    Find all.

## Environment

* RenderDoc version: 1.11
* Operating System: Windows 10
* Graphics API: DirectX11

The problem can be reproduced not only on Disassembly Type : DXBC, but on any other type.

**Comment by baldurk** [comment]
I closed the previous issue because capturing copyrighted programs that are not your own is not supported or tolerated **in any way**. This is a clear and blanket rule, I will not spend any time looking at such issues and there are no exceptions. It was certainly not an invitation to disingenuously open an identical issue but now say that it's about your own project.

This policy is not up for debate and is there for the protection of the project and myself. Do not open another issue or I will temporarily block you.
