### ISSUE TITLE
Logcat output in RenderDoc

### ISSUE THREAD

**Issue by alecazam** [baldurk/renderdoc#2164]
## Description

I was looking for someway to see our our logs to logcat to see if VK_EXT_debug_marker was found, but didn't see any of that output within the "Diagnostic Log".   I realize the "Diagnostic Log" is just meant to show errors.  But having logcat output somewhere in RenderDoc would simplify our analysis and debugging RenderDoc startup issues.  I would use the marker API if I could get it to work, but alas in this case I'd need logs.

I'm assuming that RenderDoc is expected to be run alongside an IDE, but in this case our games build process is intricately tied to scripts on the macOS side.  So we don't run an IDE on the Windows side.  Also I know logcat is a flurry of messages to deal with in a QT app.

## Environment

* RenderDoc version: 11.1
* Operating System: macOS and Windows 10 Pro
* Graphics API: Vulkan

**Comment by alecazam** [comment]
Alternatively, just some confirmation that VK_EXT_debug_marker (or VK_EXT_debug_utils) is or isn't initialized is really what I need in this case.  I don't see anything about that in the "Diagnostic Log".

**Comment by baldurk** [comment]
The diagnostic log isn't just for errors but it's for _RenderDoc_ diagnostics, it's not intended for general application output.

There's no particular expectation of an IDE, more that it's a separate problem for applications to solve however they want either with a custom logging solution or whatever else. On android that could be logcat, and if you want to view the logcat you can do that independently with `adb logcat`. Most likely you'll want to send that through a `grep` since general logcat can be **incredibly** spammy.
