### ISSUE TITLE
Make borders in the dark theme darker

### ISSUE THREAD

**Issue by DataBeaver** [baldurk/renderdoc#2168]
## Description

Some UI areas in the dark theme have white (#E1E1E1) borders which stick out really badly.  See this screenshot:
![image](https://user-images.githubusercontent.com/1126732/106579744-b3e3c980-6549-11eb-9f85-ae609c4d4977.png)

Some other borders on the other hand are a nice dark grayish-teal color (#43525A).  The white ones really stick out and ruin the aesthetic in my opinion.  Could they be made dark too or is there a reason for them to be like that?

## Environment

* RenderDoc version: v1.12+dfsg-1
* Operating System: Debian (unstable/experimental)
* Window manager: Sawfish (no desktop environment)
* Graphics API: OpenGL

**Comment by baldurk** [comment]
I don't think this is feasible to fix because of the limited palette system in Qt. Likely those borders in the Qt widgets are using the window text colour as their border colour, which can't be changed independently because it's the same palette role for both.

Also I don't really want to get into aesthetic/subjective tweaks like that. You may prefer a different colour there while someone else may prefer the colours as they are or want the other borders changed to be brighter. Normally I'd try to judge myself to arbitrate as best I can, but in this case I can't because I think all dark themes look utterly awful. Realistically I've already done my best when I created it.

**Comment by DataBeaver** [comment]
Well, you were partially correct; those Qt widgets do use WindowText for drawing their borders by default.  However you have already overridden the drawing of those parts in RDStyle.  There's also a function called outlineBrush which selects an appropriate color based on theme.  It's already used for drawing many other controls so I simply used it for CE_ShapedFrame as well.

TimelineBar was a little more difficult since it handles its own drawing.  I had to expose m_Scheme from RDStyle and do a dynamic_cast of the widget's style() to RDStyle in order to be able to select a suitable colour.  It's not a very elegant solution but it works.

The result looks like this:
![image](https://user-images.githubusercontent.com/1126732/106600159-b30b6180-6562-11eb-92c0-901a3b0f88f2.png)

I can prepare a pull request later if you'd be willing to accept one.  However I first have to solve some issues I'm having with making my custom build actually run programs, so I can also check the parts of the UI which only appear with a capture session.

**Comment by baldurk** [comment]
Ah OK, I didn't realise that was one of the styled elements that's already overridden. Qt is unfortunately highly inconsistent on what can and can't be overridden.

The change you describe in `CE_ShapedFrame` sounds fine, but the `TimelineBar` painting should not depend on `RDStyle` since aside from being kind of messy there's no guarantee that the style is actually an instance of `RDStyle`. I don't want to make widget painting be dark-theme specific, so any fix would have to be limited to `RDStyle` and style-neutral changes to `TimelineBar`.

I'm still concerned about making stylistic changes based on a single person's preferences, but if the fix is only to consistently use `outlineBrush` in a place where it should be then that's probably fine. If I remember right I added that function to work around this exact kind of problem inherent to dark themes. If needs be then at least that's a single function that can be tweaked to always use a different colour, though I don't know how I would assess that if different people want different things.

**Comment by DataBeaver** [comment]
Yeah, I agree that making TimelineBar depend on RDStyle is messy.  I'll see if I can come up with a better solution.

I asked for additional opinions on some chat channels.  Responses so far: "the lower one is better", "the tweaked one is less of an eyesore" and one thumbs up to my message here.

This is also more in line with e.g. Visual Studio:
![image](https://user-images.githubusercontent.com/1126732/106607565-24034700-656c-11eb-98e7-e801b1b970b7.png)

I'd like to think that Microsoft has done some testing to find out what users prefer.

**Comment by baldurk** [comment]
This is the same Microsoft that has jumped headlong into flat design so I wouldn't be so sure :grin:. I do take your point though, at least for consistency's sake all the borders/outlines should be the same so I'm fine with changing it that way. I initially thought it was hardcoded in the qt source to use the text colour.

My other concerns are me thinking aloud with my reasoning. I don't want to worry about problems that might not occur, but with something like this which is so heavily subjective and when I can't make an effective judgement call myself I need to be wary about just listening to the first or loudest voices. I'm a little reticent about making changes beyond palette & minor tweaks, so keeping the dark theme to 'just' an inverted palette from the proper theme helps bound any issues.

**Comment by DataBeaver** [comment]
Well yeah, admittedly not all of Microsoft's UI decisions have been super good.  But if you look at pretty much any application with a dark theme, they use various dark shades for borders.

I got a couple more chat comments: "the lower one is more tranquil; the upper one kinda looks like a debug rendering", "the modified one is way better".  And there's two more thumbs up here as well.  I hope this gives you some confidence that this is not just my opinion.

After digging some more into the Qt painting code, I've determined that QStylePainter::drawComponent with CE_ShapedFrame would be appropriate for drawing those lines as well.  The outer border can be drawn as just a normal frame of course, and the various separators can be drawn with a frame shape of HLine or VLine.

I still haven't solved my issue with running programs though, better open another issue for that I suppose.

**Comment by baldurk** [comment]
That's OK, and I appreciate you garnering some other feedback. I'm just admitting that it's not really possible for me to compare or judge either way since I can't say personally if it looks any better or worse, or compare to other applications (where dark themes tend to correlate with modern/flat designs which muddies the waters). That doesn't mean I'm unwilling to change anything, but it limits how far I'm willing to go on customisations that aren't just factoring painting as dark mode being based purely on an inverted palette.

Like I say above I'm completely fine with this change when you're ready for a PR, and anything else under a similar umbrella of fixing consistency which is even arguably a bug.

I just wanted to set expectations for any other future changes. What you're saying about refactoring the TimelineBar to use standard elements would also be good - though beware that you'd need to be sure this is a like-for-like replacement, if the user has native styling enabled then lines might not work as expected.
