### ISSUE TITLE
Close open capture together with session

### ISSUE THREAD

**Issue by DataBeaver** [baldurk/renderdoc#2169]
## Description

When I capture multiple frames and close my application, the tab for the session in RenderDoc stays open.  When I close the tab and confirm that I don't want to save any of the captures, the currently open capture still stays open and I have to separately confirm not saving it when I launch the application again.  If I close the open capture first, there's no confirmation (because the capture is still available in the session).  Would it be possible for the session save confirmation dialog to have a checkbox to close the open capture as well if it's part of the session to be closed?

## Environment

* RenderDoc version: v1.12-dfsg-1
* Operating System: Debian (unstable/experimental)
* Graphics API: OpenGL

**Comment by baldurk** [comment]
Indeed not closing the active open capture when you "close/delete all" by closing the connection window is deliberate, since it's an expected workflow that someone may make many captures and then close them all once they find the one that they want. There's enough ambiguity there that I want to keep an explicitly separate confirmation for the open capture and not unexpectedly lose work. As you say if you close in the other order it's much less ambiguous about the user's intent because they no longer have a capture open, so doesn't need separate confirmation.

Adding a checkbox to the close-all dialog to do this would work for an explicit confirmation, but it doesn't feel particularly 'natural' to me in UX terms and I don't think it's sufficiently valuable over the existing close menu item to justify adding it. It's still an opt-in either way, the only thing it changes as I see it is removing a separate confirmation dialog.

You could always add this customisation in a fork, or with [a UI extension](https://renderdoc.org/docs/python_api/ui_extensions.html) something along these lines in response to [a menu item](https://renderdoc.org/docs/python_api/qrenderdoc/extensions.html#qrenderdoc.ExtensionManager.RegisterWindowMenu) or [keyboard shortcut](https://renderdoc.org/docs/python_api/qrenderdoc/windows.html#qrenderdoc.MainWindow.RegisterShortcut):

```py
# Close current open capture
pyrenderdoc.CloseCapture()

# Get Qt helper
mqt = pyrenderdoc.Extensions().GetMiniQtHelper()

# Find connection window 
cap = mqt.FindChildByName(pyrenderdoc.GetMainWindow().Widget(), 'LiveCapture')
# this assumes there's only one connection
# you could filter with mqt.GetWidgetText(cap) to get the window title

# Close the connection, will prompt for saving
mqt.CloseToplevelWidget(cap)
```
