### ISSUE TITLE
Support KTX file loading

### ISSUE THREAD

**Issue by expenses** [baldurk/renderdoc#2174]
## Description

Renderdoc has lovely support for [loading and viewing DDS images](https://renderdoc.org/docs/getting_started/faq.html#i-d-like-to-use-renderdoc-s-texture-viewer-for-dds-files-or-other-images-can-i) and it would be great to have the same support for [KTX images](http://github.khronos.org/KTX-Specification/) as well. I'm not sure how much of an ask this is, but it seems like it should be easy to build onto of the dds code.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
