### ISSUE TITLE
RenderDoc Android not reporting VK_EXT_debug_utils layer, but RenderDoc Switch does

### ISSUE THREAD

**Issue by alecazam** [baldurk/renderdoc#2175]
## Description

I was under the impression that VK_EXT_debug_report/marker were deprecated, and we were supposed to be using VK_EXT_debug_utils instead.  But this extension doesn't show up on Android when I launch our app from RenderDoc.   That means that we'll have to maintain both versions to work across Android/Switch.  Why would this extension be suppressed on Android, and not other platforms.

Since I had removed the deprecated extension support, all of our scoping and names disappeared on the Android build.  Also I have two different installs of RenderDoc here, so I'm hoping they don't interfere with one another and lead to this issue.

## Steps to reproduce

1. Launch a debuggable App through RenderDoc
2. Note the available extension to the app don't include "VK_EXT_debug_utils", but does include the deprecated extensions for "VK_EXT_debug_report/marker".

## Environment

* RenderDoc version: v1.12
* Operating System: Windows10 Pro
* Graphics API: Vulkan 1.1

**Comment by baldurk** [comment]
Please note that **absolutely no discussion** of the Switch version of RenderDoc should take place, this is strictly covered by NDA and should not be mentioned at all in the public repository.

Looking at it, this seems like an android bug. I added logging into RenderDoc's implementation of `vkEnumerateInstanceExtensionProperties` and it doesn't get called, so RenderDoc isn't able to add its own extension to the list. Android has its own loader implementation and it's often broken or buggy, and on top of that every phone manufacturer can customise android in their own ways which sometimes leads to functionality being broken like this. There's unfortunately no way to know whether it will work or not on Android. This is also bad because it means RenderDoc can't filter out any unsupported instance extensions at the same time as it adds its own implemented ones.

I can't suggest any fix for this since it's not a RenderDoc bug. As a workaround you could try enabling VK_EXT_debug_utils anyway and see if that "just works" even if it's not enumerated. If that does work, you could maybe detect renderdoc an alternate way by looking for its library being available and then enabling the extension if you see that. I'll contact folks at Google and see if they have any better suggestions.

**Comment by alecazam** [comment]
I guess we could detect the presence of VK_EXT_debug_marker and assume RenderDoc is active then, and try to force enable the VK_EXT_debug_utils.  Thanks for the find, it did seem like the RenderDoc code looked reasonable to me.

**Comment by baldurk** [comment]
That's difficult because VK_EXT_debug_marker is a device extension so you would have to have already created an instance, and VK_EXT_debug_utils is an instance extension so you need to know if it's present before creating that instance.
