### ISSUE TITLE
Vulkan capture set up message formatting is broken

### ISSUE THREAD

**Issue by bioglaze** [baldurk/renderdoc#2177]
## Description

I launched RenderDoc 1.12 on Ubuntu 20.04 and saw the message about configuring Vulkan capture. The text showed some HTML formatting which is unexpected. I also deleted ~/.renderdoc to see if it helps but it did not.

## Steps to reproduce

Launch RenderDoc without Vulkan capture being configured.

## Environment

* RenderDoc version: 1.12
* Operating System: Ubuntu 20.04
* Graphics API: Vulkan
* GPU: AMD Radeon R9 Nano
![bug](https://user-images.githubusercontent.com/7099779/107871660-4ff7c400-6eac-11eb-90f5-3db8807dd5ab.png)

**Comment by baldurk** [comment]
This is a bug that has been fixed since v1.12, specifically in 76fabedbe66fac4c86106a21d102e90b12b20021 . This only happens on high-DPI systems which means the label text contains `information@2x.png` for the double-size icon, and that was incorrectly parsed as an EID link.

Updating to a recent build will fix the bug, and you'll need to click on the button either way to configure the vulkan layer properly to be able to capture vulkan. If you don't need vulkan capture but can't update to a recent build you can still click the button to workaround the issue on v1.12.
