### ISSUE TITLE
How to get a log file of functions from a captured rdc file?

### ISSUE THREAD

**Issue by vinjn** [baldurk/renderdoc#218]
![image](https://cloud.githubusercontent.com/assets/558657/13694609/0ebe9fbe-e792-11e5-8b1e-51fab1d698e1.png)

I would like to see all the functions and arguments W/O open the GUI.

**Comment by baldurk** [comment]
If you're just wanting a text dump of all of the API calls from an application, the api_dump layer from LunarG is more appropriate to this purpose, since that's exactly what it tries to provide.

If you are willing to open the UI to run a script, the event data is accessible from the python shell. This one-line command gives the idea, but it will depend on your exact capture so you can write a script to iterate the structures:

```python
print renderdoc.GetDrawcalls(0)[0].children[1].events[0].eventDesc
```

Otherwise if you want to be able to do this without opening the UI, you would need to write a program that uses the replay API. This API is not very stable so I wouldn't recommend this path, but you can [use this code](https://github.com/baldurk/renderdoc/blob/master/renderdoccmd/renderdoccmd.cpp#L122-L132) in `renderdoccmd` as an example. The array `rdctype::array<FetchDrawcall> draws;` of draws will contain the drawcalls available and their events can be accessed just like in the python line above.

Let me know if that answers your question.

**Comment by vinjn** [comment]
Thanks! It explains.

I will pick the Python path first, where can I find doc of Python interfaces?
In long term, I will pick the `renderdoccmd` path.

**Comment by baldurk** [comment]
There isn't really any documentation of the Python interfaces :confused:. If you look at `Core.cs` this class is the one exposed with the `renderdoc` variable in Python, so you can look at what is available and see from the C# project code. Also if you do write any code with the replay API like `renderdoccmd` does, be aware that this will break or change without warning :smile:.

I would still recommend using the api_dump layer if this is all you are wanting, RenderDoc is not the best suited program for a raw view of all API calls, since in some cases it will rearrange or make small changes where necessary to capture.

**Comment by vinjn** [comment]
The background of this issue is I have captured a rdc from a *real* game.
When I replay the rdc, the windows is black.
Thus I need a tool to understand the rdc.

**Comment by baldurk** [comment]
OK, this sounds like a real bug that should be created with any reproduction information you can provide. The replay should match what was visible in the game, so any error that only shows in the rdc is a bug in renderdoc :).

I think for this purpose listing the vulkan API commands will not be useful for debugging, since it will not list any information about the creation of objects and their parameters and it will not show any data buffers uploaded to the GPU.
