### ISSUE TITLE
Renderdoc cannot load 3D BC6 dds files.

### ISSUE THREAD

**Issue by expenses** [baldurk/renderdoc#2186]
## Description

I am able to view 128x128x128 `BC6_UFLOAT` textures that have been captured in the viewer. However, when I use the `Save selected Texture` action and save the texture to a `.dds` file, I cannot drag the texture back into the viewer to view it again. I get the following error:

```
Core 82228 21:16:52 image_viewer.cpp(841)     Log Format BC6_UFLOAT not supported for local display and can't be converted manually.
Core 82228 21:16:52 image_viewer.cpp(853)     Error Couldn't create proxy texture for image file      
Core 82228 21:16:52 replay_controller.cpp(2012) Error Couldn't create a replay device.
```

I _can_ load 2D `BC6_UFLOAT` textures just fine.

## Steps to reproduce

Unzip `bc6h_3d.dds.zip` and attempt to load `bc6h_3d.dds` with renderdoc.

## Environment

* RenderDoc version: RenderDoc v1.12 Linux 64-bit Release (40b86b63fbb990b26cc083ced32cb55f11ad263c)
* Operating System: Arch Linux x86_64 5.10.16-arch1-1
* Graphics API: OpenGL 4.6

[bc6h_3d.dds.zip](https://github.com/baldurk/renderdoc/files/6016264/bc6h_3d.dds.zip)
[log.log](https://github.com/baldurk/renderdoc/files/6016262/log.log)

**Comment by baldurk** [comment]
This is a factor of the underlying implementation, if the driver doesn't report support for the texture type & format it can't be viewed. E.g. the dds provided works fine for me on windows because my driver supports 3D BC6U textures.

Since the format is supported this is probably just because support for block-compressed 3D textures can be a bit sketchy. On GL this is complicated even further because some GL drivers (nvidia only I think) will report support, but then try and use some different encoding other than normal BC6. I'll look into working around it by opening the texture as a 2D array instead.

**Comment by expenses** [comment]
Thanks for looking into this. Seeing as I'm using vulkan normally, is there a way to get the viewer to use that instead?

**Comment by baldurk** [comment]
No unfortunately not, currently I don't have the proxying capabilities implemented for vulkan and the local API isn't selectable anywhere.

**Comment by baldurk** [comment]
That commit should workaround the issue by remapping to a 2D array texture and allow loading these textures on linux.

**Comment by expenses** [comment]
That works great, thanks!
