### ISSUE TITLE
python standalone module to capture frame on local machine

### ISSUE THREAD

**Issue by davidzxiong** [baldurk/renderdoc#2202]
Hi, baldurk. I am working on automation of gpu profiling using renderdoc python api. I want to launch a PC app and trigger capture. I am using renderdoc pymodule as a standalone module rather than using it from the GUI python shell.
 When I try to renderdoc.ExecuteAndInject, the result status is InternalError. When I renderdoc.ExecuteAndInject from GUI python shell, the status is successful.
I also tried to connect to rd.CreateRemoteServerConnection(URL) with URL blank, however the status is rd.ReplayStatus.NetworkIOFailed.
I am using python 3.6.4    
How should I fix it? Any insights is appreciated.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
