### ISSUE TITLE
Support for Tiled Resources in D3D12

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2203]
## Description

I understand this might be a big ask, but I was wondering if there were any plans to support tiled resources in D3D12? We've never really had renderdoc support in this engine and I was trying to get it to work, tiled resources is a core feature so nothing we can really disable. It fails to report support for TILED_RESOURCES and even if I let it run, it fails in the call to CreateReservedResource.

Thanks!

## Environment

* RenderDoc version: 1.12
* Operating System: Windows 10
* Graphics API: D3D12

**Comment by baldurk** [comment]
That commit adds support for capturing and replaying sparse resources on D3D12. It's only lightly tested since I couldn't really get a hold of many non-trivial sparse resource samples (on any API), possibly because I think IHVs recommend against using them so it's a rarely used feature. Especially on D3D12 this may be an issue since the D3D12 API for sparse resources is... awful.

One thing to note: the memory overhead for capturing such resources is proportional to their total virtual size not how much physical memory is currently mapped. This isn't a problem if you're using sparse resources to defrag/remap and they're mostly always bound anyway, but it may be if you are reserving a lot more memory than is available on the GPU or system.

**Comment by redorav** [comment]
@baldurk you are a total machine. I was not expecting this at all, I was eager to try it out, booted up our game and hey presto it loaded and ran! I could also take a capture but during replay renderdoc crashes, accessing a null command list in d3d12_initstate.cpp

```
// transition to copy dest
if(!barriers.empty())
  list->ResourceBarrier((UINT)barriers.size(), &barriers[0]);
```

This is the callstack

```
renderdoc.dll!D3D12ResourceManager::Apply_InitialState(ID3D12DeviceChild * live, const D3D12InitialContents & data) Line 1181	C++
renderdoc.dll!ResourceManager<D3D12ResourceManagerConfiguration>::ApplyInitialContents() Line 1351	C++
renderdoc.dll!WrappedID3D12Device::ApplyInitialContents() Line 1291	C++
renderdoc.dll!WrappedID3D12Device::ReadLogInitialisation(RDCFile * rdc, bool storeStructuredBuffers) Line 3837	C++
renderdoc.dll!ReplayController::PostCreateInit(IReplayDriver * device, RDCFile * rdc) Line 2042	C++
renderdoc.dll!ReplayController::CreateDevice(RDCFile * rdc, const ReplayOptions & opts) Line 2009	C++
renderdoc.dll!CaptureFile::OpenCapture(const ReplayOptions & opts, std::function<void __cdecl(float)> progress) Line 364	C++
qrenderdoc.exe!ReplayManager::run(int proxyRenderer, const QString & capturefile, const ReplayOptions & opts, std::function<void __cdecl(float)> progress) Line 450	C++
```

If that's not enough, I can try to move the necessary strings to get a capture to you when I'm back at work on Monday. Seriously thank you so much for the effort, it's quite game-changing.

**Comment by baldurk** [comment]
You're lucky that I had already implemented sparse resources for vulkan and was already planning on rolling in D3D12 too at the same time :smile: . 

I'm not surprised that there are bugs but please open it as a new issue, I don't want this to become a mega-issue for every tiled resource bug.

For that one it sounds like you hit a device removed earlier which is why the list is NULL, you could double check in the diagnostic log. Yes I'll definitely need either a repro case or a lot more information so that I can tell what's wrong/repro it locally in isolation - e.g. you could run with debug layers enabled to see if it points out any problems.

**Comment by redorav** [comment]
Of course, I will do. I'll get more details tomorrow and open a new issue. Thanks!
