### ISSUE TITLE
vkQueueSubmit event appearing earlier in the frame than the recording of the associated CommandBuffer

### ISSUE THREAD

**Issue by SergioAlapontARM** [baldurk/renderdoc#2204]
## Description

I was capturing a PC build of Unity 2DRP's LostCrypt project using Vulkan. 
![image](https://user-images.githubusercontent.com/53938158/110921462-79263b80-8316-11eb-8947-9e89b00cfe23.png)

I can confirm that the order of events displayed is wrong and that the submit event is recorded later in the frame (after the primary command buffer is done being recorded).

## Steps to reproduce

It should be fairly easy to check building a PC built of LostCrypt with Unity.

## Environment

* RenderDoc released version: v1.12
* Operating System: Windows 10
* Graphics API: Vulkan

* GPU: My GPU is an NVIDIA GeForce RTX 2080
* Driver: GeForce GameReady Driver (Version 451.67, released the 07/09/2020

**Comment by baldurk** [comment]
That behaviour is deliberate, the order of events shown in the event browser and API inspector show things in submission order not recording order, since that's generally the way you want to browse the frame. Otherwise you would see commands recorded at random points, potentially interleaved with other command buffers which are executed later or earlier, and it would be very difficult to browse the frame consistently.

**Comment by SergioAlapontARM** [comment]
Thank you @baldurk for your quick answer :). Good to know thanks!
