### ISSUE TITLE
[Vulkan][FR] Show KHR_pipeline_executable_properties of modified shaders

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2210]
## Description

At the moment `KHR_pipeline_executable_properties` is shown only for the original shader, however I'd like to have it also shown for edited shaders.

While developing drivers it's common to investigated shaders mis-compilations, in many cases I'm trying minimize the shader until I see the specific instruction causing the issue; after that it would be much simpler for me to be able to see the result of modified shader's compilation directly in RenderDoc - in order to quickly understand the difference the problematic instruction causes.

## Environment

* RenderDoc version: 1.13 795d7e0910056bf1971dbb8752581dc5bfa06fdf
* Operating System: Linux (any supporting Vulkan)
* Graphics API: Vulkan

**Comment by baldurk** [comment]
It's not true that `KHR_pipeline_executable_properties` is only shown for the original shader. You can view the properties and other disassemblies the same way for edited shaders as for original shaders by opening up the shader details from the pipeline state view. After an edit is applied the pipeline state will show the edited shader and its properties in place of the original.

It is by design that once opened this shader window is persistent for a given instance of the shader and does not reflect edits, so if you want to see the properties for an edited shader you'd need to open a new window for that edited shader.

**Comment by werman** [comment]
Sorry, I'm still lost...

What I'm doing is:
1) Open pipeline, open e.g. FS
2) Edit -> Decompile with SPIRV-Cross
3) Shader is edited -> hit Refresh
4) There is no tabs opened with the shader beside the tab for editing

From here:
- if I click "View" I see the original shader (spirv, pipeline properties, etc.)
- if I click on "Shader Module 111 (Edited)" -> "View contents" - I would still see original shader

**Comment by baldurk** [comment]
If you are seeing that then it's a bug, and you'd need to open a bug report with a reproducible test case I can investigate.

For reference for me I just tried it, after I've edited a shader and then I view it again from the pipeline state then I see the updated shader source as well as updated SPIR-V and AMD disassembly (I'm on an NV system that doesn't return anything significant in KHR_pipeline_executable_properties).

**Comment by werman** [comment]
I see, thanks for checking! Then I'll recheck more carefully.
