### ISSUE TITLE
Texture View fails to draw correctly, getting VK_ERROR_DEVICE_LOST in logs

### ISSUE THREAD

**Issue by eligt** [baldurk/renderdoc#2216]
## Description

Whenever accessing the Texture View, no texture is drawn - instead, whatever was last displayed in that area on the screen is taking the space of the texture view. See screenshot:
![desktop 1_220](https://user-images.githubusercontent.com/2043211/112224607-661f3f80-8c23-11eb-92d8-7a9e460b9a48.jpg)

## Steps to reproduce

I'm not getting any Vulkan validation errors in my application. I think I'm getting a similar issue to https://github.com/baldurk/renderdoc/issues/1420

Log is attached: [renderdoc.log](https://github.com/baldurk/renderdoc/files/6192970/renderdoc.log)

## Environment

* RenderDoc version: 1.12
* Operating System: Lubuntu 20.04 with Linux 5.9.16-050916-generic
* Graphics API: Vulkan using NVIDIA 460.32.03 on GeForce GTX 1060

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly completing the prompted sections. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) which is linked from the template you used and open a new issue which does fill out the sections properly. Do not reply to this issue with more information, please open a new issue.

As detailed in the documentation and evident by the section title, for "steps to reproduce" you must actually provide steps I can take to reproduce the problem. Most commonly and simplest for everyone would be for example sharing your application or a capture file that shows the problem. If you can't share these publicly you can [email me privately](mailto:baldurk@baldurk.org?subject=RenderDoc%20bug%20repro%20case) with a google drive/dropbox/etc link. If you can't share these even privately you should say that and provide a significant amount of information about what you are doing so I can hope to construct a reproducible test case, or suggest further diagnostic steps. If you don't do any of this your bug report is unlikely to be useful and will be closed like this one.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

As linked above and in the issue template you were provided with there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
