### ISSUE TITLE
Support Android x86 / x86_64 apk for RenderdocCmd

### ISSUE THREAD

**Issue by ricardoquesada** [baldurk/renderdoc#2224]
[patch.renderdoc.txt](https://github.com/baldurk/renderdoc/files/6226049/patch.renderdoc.txt)

## Description

Currently RenderDocCmd  has APKs for:
- arm64
- arm32

But more and more devices (Chromebooks) are supporting x86 / x86_64 ABIs.
Please consider adding support for x86 / x86_64 for RenderdocCmd APKs.

I attached a possible patch.
I was able to use RenderdocCmd as a server a replay a trace successfully on a Chromebook x86_64.
~~But I failed to capture a trace on it in a game that supported the x86 APK (perhaps a bug unrelated to Renderdoc?)~~

UPDATE: I was able to capture a trace on x86 binaries

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
