### ISSUE TITLE
Textures used by SPIR-V shader in OpenGL are not recognized

### ISSUE THREAD

**Issue by DataBeaver** [baldurk/renderdoc#2226]
## Description

I'm working on porting my graphics engine to Vulkan and as an intermediate step I added SPIR-V shader support to the OpenGL renderer.  While debugging this I noticed that RenderDoc does not show the textures used by the SPIR-V shader in any way.  They're not in the input panel in the texture viewer nor in the fragment shader section of pipeline viewer.  The timeline shows no accesses to the texture.  Replay also does not work; the color output shows up as blank.

If I add a binding layout qualifier matching what the program uses to the sampler uniform in the shader, replay in RenderDoc does work, but the texture is still not recognized as used anywhere.

## Steps to reproduce

1. Create a SPIR-V shader program using glShaderBinary and glSpecializeShader
2. Bind textures and other necessary things for the shader
3. Render a mesh

Capture of affected application: [opengl_spirv.zip](https://github.com/baldurk/renderdoc/files/6232785/opengl_spirv.zip)
opengl_spirv.rdc has only location layout qualifier on the sampler uniform (the compiler generates a binding of zero), opengl_spirv_binding.rdc additionally has a manually specified binding.

I can share the application if needed, but it requires some preparation so I'll wait for your word on whether you need it in addition to the capture.

## Environment

* RenderDoc version: v1.14 (cd5d0ede4)
* Operating System: Debian unstable
* Graphics API: OpenGL
* GPU: GeForce 980Ti
* Driver: Nvidia 460.56

**Comment by baldurk** [comment]
FYI I'm not working for the next couple of weeks so I can look into this when I get back. Taking an extremely quick look I'd guess this is because you have two entry points named "main" in the SPIR-V module. I don't remember off hand if that's legal, try giving them unique names or having a SPIR-V module each.

**Comment by DataBeaver** [comment]
The SPIR-V specification says "A module must not have two OpEntryPoint instructions with the same Execution Model and the same Name string." (in the description of the OpEntryPoint instruction).  To me this means that the *combination* of execution model and name must be unique, but there may be two identical names if the execution model is different.

I'm not sure how to generate a SPIR-V module consisting of multiple stages with different entry point names using existing tools.  glslangValidator seems very insistent that the entry point must be named "main".  I might try separate modules to see if that's the problem here, though I would like to use linked modules.  I'm also working on my own shader compiler which will give me more freedom about what goes into the SPIR-V.

**Comment by baldurk** [comment]
OK, that's a little annoying but makes sense. Most likely that's the problem as I doubt I'm handling using that tuple everywhere and I think the only cases I've seen of multiple entry points use unique names anyway.

I assumed you had your own compiler since I didn't think glslang could generate a module with multiple entry points itself. This still sounds like a RenderDoc bug to fix I was just suggesting a possible workaround in the meantime until I can investigate.

**Comment by DataBeaver** [comment]
My own compiler isn't ready to produce SPIR-V yet, so I compiled both stages separately with glslangValidator and then combined them with spirv-link.  But glslangValidator doesn't accept anything other than "main" for the source entry point and seems to ignore the -e option which I had assumed would rename the entry point put into SPIR-V.

I realized that it would be easy enough to tweak the SPIR-V binary with a hex editor, so I did a quick test by changing the entry point names and the associated OpName instructions to "mainv" and "mainf".  This indeed makes RenderDoc recognize that the fragment shader is using a texture in the pipeline state panel, however it's still shown as "no resource" and the inputs panel in the texture viewer shows nothing.  This could be a different bug; I don't know how usual it is to use glUniform1i to change sampler bindings for SPIR-V shaders, and I plan to discontinue doing that as I develop my engine further.

Here's a capture for this: [opengl_spirv2.zip](https://github.com/baldurk/renderdoc/files/6235224/opengl_spirv2.zip)

Workaround is how I interpreted your suggestion.  I'll try it if I come across a situation where the need for debugging exceeds the effort of making the necessary code changes (or if I come up with a way to do it with less changes).

**Comment by baldurk** [comment]
Ah right I wasn't aware of spirv-link, that makes sense.

I'm not sure it's valid to set textures in SPIR-V shaders with `glUniform`, I think the expectation is that only new drivers would support SPIR-V so you can specify the binding directly in the shader rather than using legacy methods. From the [GL extension spec](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gl_spirv.txt):

> 26. How do we change the location of samplers and images?
> 
>     RESOLVED. You don't. Well you can using Uniform1i as usual, but you have
>     no way of knowing which location corresponds to which sampler or image
>     variable as GetUniformLocation won't work without a named variable. Best
>     to just treat them as immutable bindings which are specified in the
>     shader source or binary.

Though you can totally specify a location for a SPIR-V variable even if you can't query it, so that's not entirely accurate. It seems like it wasn't _intended_ to work, whether or not there's a way to do it.

**Comment by DataBeaver** [comment]
Good catch from the extension spec.  I kinda suspected that using glUniform1i to change bindings for SPIR-V shaders is not really supported.  So far I haven't found anything explicitly saying it would be invalid, but indeed OpenGL doesn't give any guarantees about reflecting names from SPIR-V shaders ("When the Op*Name instructions are present, it is
implementation-dependent if these are reported via the name reflection APIs.").

Removing the location layout specified from the shader prevents my engine from setting the uniform and makes RenderDoc recognize the texture correctly.  This is somewhat puzzling since in the non-working case it's setting the same binding (40) that was already specified in the SPIR-V module, yet RenderDoc shows the texture at slot 0.  Is the mere presence of the glUniform1i call confusing RenderDoc somehow?  This isn't hugely important since it's such an edge case, but if it's not too hard to fix that would be nice.

**Comment by baldurk** [comment]
I'm guessing there might be some misfiring code that when it sees a location it expects to then be able to get the value via `glGetUniform`, since you _are_ supposed to specify locations for bare uniform values like floats and ints (not textures) :/. I wouldn't be surprised if drivers don't return the binding from the SPIR-V in that case. I'll look at that when I fix up the handling of entry points.

**Comment by baldurk** [comment]
That commit should fix the handling of entry points as (name, stage) pairs instead of just looking them up by name. I also put in a second commit which will ignore the Location decoration if a Binding exists (i.e. for texture/buffer type uniforms), so that Location is only used for bare value uniforms as I believe is the intention of the extension.
