### ISSUE TITLE
renderdoc.dll hang UE4Editor.exe

### ISSUE THREAD

**Issue by wangyongxina** [baldurk/renderdoc#2232]
ntdll.dll!NtWaitForAlertByThreadId()	Unknown
 	ntdll.dll!RtlpWaitOnAddressWithTimeout()	Unknown
 	ntdll.dll!RtlpWaitOnAddress()	Unknown
 	ntdll.dll!RtlpWaitOnCriticalSection()	Unknown
 	ntdll.dll!RtlpEnterCriticalSectionContended()	Unknown
 	ntdll.dll!RtlEnterCriticalSection()	Unknown
 	ws2_32.dll!DCATALOG::GetCountedCatalogItemFromAttributes()	Unknown
 	ws2_32.dll!WSASocketW()	Unknown
 	renderdoc.dll!Network::CreateServerSocket(const rdcstr & bindaddr, unsigned short port, int queuesize) Line 364	C++
 	renderdoc.dll!RenderDoc::Initialise() Line 397	C++
 	renderdoc.dll!add_hooks() Line 66	C++
 	renderdoc.dll!**DllMain**(HINSTANCE__ * hModule, unsigned long ul_reason_for_call, void * lpReserved) Line 78	C++
 	renderdoc.dll!dllmain_dispatch(HINSTANCE__ * const instance, const unsigned long reason, void * const reserved) Line 195	C++
 	ntdll.dll!LdrpCallInitRoutine()	Unknown
 	ntdll.dll!LdrpInitializeNode()	Unknown
 	ntdll.dll!LdrpInitializeGraphRecurse()	Unknown
 	ntdll.dll!LdrpPrepareModuleForExecution()	Unknown
 	ntdll.dll!LdrpLoadDllInternal()	Unknown
 	ntdll.dll!LdrpLoadDll()	Unknown
 	ntdll.dll!LdrLoadDll()	Unknown
 	KernelBase.dll!LoadLibraryExW()	Unknown
>	UE4Editor-Core.dll!FWindowsPlatformProcess::LoadLibraryWithSearchPaths(const FString & FileName, const TArray<FString,TSizedDefaultAllocator<32> > & SearchPaths) Line 1774	C++
 	UE4Editor-Core.dll!FWindowsPlatformProcess::GetDllHandle(const wchar_t * FileName) Line 92	C++
 	UE4Editor-RenderDocPlugin.dll!00007ffd23fe68a4()	Unknown
 	UE4Editor-RenderDocPlugin.dll!00007ffd23fe581c()	Unknown
 	UE4Editor-RenderDocPlugin.dll!00007ffd23fe9225()	Unknown
 	UE4Editor-Core.dll!FModuleManager::LoadModuleWithFailureReason(const FName InModuleName, EModuleLoadResult & OutFailureReason) Line 550	C++
 	UE4Editor-Projects.dll!FModuleDescriptor::LoadModulesForPhase(ELoadingPhase::Type LoadingPhase, const TArray<FModuleDescriptor,TSizedDefaultAllocator<32> > & Modules, TMap<FName,enum EModuleLoadResult,FDefaultSetAllocator,TDefaultMapHashableKeyFuncs<FName,enum EModuleLoadResult,0> > & ModuleLoadErrors) Line 596	C++
 	UE4Editor-Projects.dll!TryLoadModulesForPlugin(const FPlugin & Plugin, const ELoadingPhase::Type LoadingPhase) Line 970	C++
 	UE4Editor-Projects.dll!FPluginManager::LoadModulesForEnabledPlugins(const ELoadingPhase::Type LoadingPhase) Line 1035	C++
 	UE4Editor.exe!FEngineLoop::AppInit() Line 4916	C++
 	UE4Editor.exe!FEngineLoop::PreInit(const wchar_t * CmdLine) Line 1846	C++
 	[Inline Frame] UE4Editor.exe!EnginePreInit(const wchar_t *) Line 42	C++
 	UE4Editor.exe!GuardedMain(const wchar_t * CmdLine, HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, int nCmdShow) Line 131	C++
 	UE4Editor.exe!WinMain(HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 265	C++
 	[Inline Frame] UE4Editor.exe!invoke_main() Line 102	C++
 	UE4Editor.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!00007ffda0b67034()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

When enabled renderdoc plugin in UE4 project, UE4Editor will load renderdoc.dll LoadLibrary(acquire LdrLoaderLock)
renderdoc.dll DllMain will try to create socket which may try to acquire LdrLoaderLock, which cause DeadLock.
DllMain should not do heavy initialization work, maybe start thread maybe better.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
