### ISSUE TITLE
No capturing child processes

### ISSUE THREAD

**Issue by spiiin** [baldurk/renderdoc#2234]
I am trying to capture frame for android emulator Nox - https://www.bignox.com/
It create child process NoxVMHandle.exe (look's like it virtual box headless vm, other android emulators works similar), but renderdoc can't capture it (I tried "capture child processes" option, and "enable global hook" option - both didn't work, I use renderdoc 1.13).

Solution for intel gpa - https://community.intel.com/t5/Intel-Graphics-Performance/Unable-to-capture-frame-on-NoxPlayer-Android-Emulator/m-p/1210260#M2025, it can capture child process with "Auto-detect launched applications").

NoxVmHandle can use directx (looks like virtualbox somehow translate android opengl calls to directx) and opengl 4.6 backends for render, but intel gpa only works with directx backend to capture and analyze frames, and some games only works with opengl backend, so it will be cool to use renderdoc to able analyze it too.

Also, looks like some previous pair of versions RenderDoc+Nox was worked together (post in Russian, author only wrote, that he got success to capture frame from Nox with RenderDoc, but he didn't point, what versions of apps he tried :( )
https://uengine.ru/forum/viewtopic.php?p=39804&sid=f6995d42f6067b203fa68ff7c8d0d7f4#p39804

Also, just for clarify - android emulator is windows app, so issue is about windows, not android platform.

Sorry for my english, it's not my native.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
