### ISSUE TITLE
RenderDoc won't start

### ISSUE THREAD

**Issue by Zarthania** [baldurk/renderdoc#2236]
Hello, I'm trying to open RenderDoc and it won't even start. Months ago I already installed it and it was working perfectly. Since then, I have uninstalled the software wich I reinstalled today and anything works.

When I have a bit of luck, the window appears and works for like 10s but then it crashes. But everytime, as you see on this screenshot, the processes are running but no window appears.
![Screenshot_2](https://user-images.githubusercontent.com/64792678/113603337-1dfd1580-9644-11eb-95da-87662e4c81cf.png)

I already tried uninstalling and reinstalling multiples times and even older versions but still nothing.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
