### ISSUE TITLE
Report: Error  Invalid RDC capture file. With the latest version of both soft. Sample files are usable...

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2239]
I am using Render doc 1.13 and MapsModelsImporter-v0.3.7 It says this reports... 
Also, I installed MapsModelsImporter-v0.3.3 but it did no good...
Blender 2.92
```
Report: Error
 Invalid RDC capture file. Please make sure that:
1.	You are using the recommended RenderDoc Version for this AddOn	E
•	RenderDoc Version 1.5 -1.9 for MapsModelsImporter <= 0.3.2	
•	RenderDoc Versi on > = 1.10 for MapsModel si mporter >=0.3.3
1.	You are importing from Google Maps or Google Earth web
2.	You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).
4
/
Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading.
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.conVeliemiche|/MapsModelslmporter-samples
If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"
If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems, you have to run Blender from the console to get the debug output
I I WUJCUl V_UI ILCAL 1*10 IU
```

Anybody have any solutions. Should I use an older version of RenderDoc?

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by gamil2** [comment]
Invalid RDC capture file . Please make sure that : 1. You are using the recommended RenderDoc Version for this AddOn Version 1.5 1.9 for MapsModels Importer < 0.3.2 - RenderDoc Version 1.10 for MapsModels Importer 0.3.3 and 0.3.7 - RenderDoc Version 1.13 for MapsModels Importer > 0.4 .0 2. You are importing from Google Maps or Google Earth web 3. You were MOVING in the 3D view while taking the capture ( you can use the " Capture after delay " -button in RenderDoc ) . Before opening a new Isque on GitHub please download a working sample file to check if this works on your computer . Please be patient . If there's no error message it might still be loading . It can take a minute or two to load it and Blender will get unresponsive during this time . Find sample files here : https://github.com/eliemichel/MapsModels Importer - samples If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderD OC . Find instructions about using RenderDoc by searching YouTube for " Capturing Google Maps with RenderDoc "
