### ISSUE TITLE
Meet 'nan' when export mesh vertex with renderdoc python plugins.

### ISSUE THREAD

**Issue by qqdy** [baldurk/renderdoc#2243]
## Description

- use renderdoc python API to export mesh vertex data from a *.rdc capture.
- write vertex data to csv file.
- will meet 'nan' in csv file and the following data is broken.

## Steps to reproduce

- capture a frame from mobile, the mobile running opengl graphics api.
- open *.rdc capture with python api.
- export mesh data from *.rdc capture, same as offical example code https://renderdoc.org/docs/python_api/examples/renderdoc/decode_mesh.html
- write export mesh data into csv format file.

## Environment

* RenderDoc version: 1.10
* Replay Operating System: windows 10
* Mobile Graphics API: opengl es

**Comment by baldurk** [comment]
Please provide a reproducible test case. The export certainly can produce NaNs if there is NaN data in the vertices, you haven't explained if that's the case or not. Does the mesh data exported match what's visible in the mesh viewer? does exporting from the mesh viewer directly produce different results? If your python script doesn't match the example code exactly please share that as well since it could be the cause of the bug.

You're also using an old version of RenderDoc, I'd suggest you update to the latest version and try again.

**Comment by qqdy** [comment]
thanks for your quick response.
Does the mesh data exported match what's visible in the mesh viewer? => the mesh in viewer is ok, but exported mesh data is damaged.
does exporting from the mesh viewer directly produce different results? => if I use export from viewer windows GUI button, it is ok and same with viewer.

here are some attachments included the snapshot capture and my export scripts.
"RdcParser.zip" is my python export script.
"show.zip" is the renderdoc capture.
unzip and put "show.rdc" along with "RdcParser.bat" then run it, the damaged export mesh data will generate in folder "exportMesh".

[show.zip](https://github.com/baldurk/renderdoc/files/6310600/show.zip)
[RdcParser.zip](https://github.com/baldurk/renderdoc/files/6310578/RdcParser.zip)

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
