### ISSUE TITLE
Feature request - performance metrics triggered auto-capture

### ISSUE THREAD

**Issue by ylz-at** [baldurk/renderdoc#2253]
## Description

In complex scenes, the performance metrics may vary rapidly and it is quite difficult to capture the frame we are interested in manually.
It would be great if Renderdoc can capture automatically when a performance metric like draw call hits the user set bar.

UI: add an option to "Caption Options" with an on/off button like "Auto-capture". With "Auto-capture" on, a user should be able to select from a drop list like "Metrics Type", then set the related value.
renderdoc: If the feature is on, should be able to calculate related Metrics in a frame, such as a number of draw calls. When the condition is fulfilled, start the capture process.

## Environment

* RenderDoc version: v1.13
* Operating System: Win10
* Graphics API: GLES 3.2

**Comment by baldurk** [comment]
RenderDoc is not a profiler so supporting performance analysis workflows is not currently a goal of the project. This could maybe be accomplished manually using the [in-application API](https://renderdoc.org/docs/in_application_api.html) to trigger a capture on a custom condition, but note that it would be off by one frame since it's not possible to retroactively capture a frame.
