### ISSUE TITLE
Renderdoc cannot reproduce the bug on the android machine

### ISSUE THREAD

**Issue by aidexie** [baldurk/renderdoc#2256]
## Description

There is a rendering bug on my Huawei mate40 machine, but when I start the app with renderdoc, the rendered image is normal. I closed the renderdoc and started the app, and the bug reappeared at this time. 
This is only the case for this one bug, other bugs and renderdoc can be reproduced normally
Can anyone tell me why this happens?

## Environment

* RenderDoc version: 1.13
* Operating System: Android

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly completing the prompted sections. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) which is linked from the template you used and open a new issue which does fill out the sections properly. Do not reply to this issue with more information, please open a new issue.

As detailed in the documentation and evident by the section title, for "steps to reproduce" you must actually provide steps I can take to reproduce the problem. Most commonly and simplest for everyone would be for example sharing your application or a capture file that shows the problem. If you can't share these publicly you can [email me privately](mailto:baldurk@baldurk.org?subject=RenderDoc%20bug%20repro%20case) with a google drive/dropbox/etc link. If you can't share these even privately you should say that and provide a significant amount of information about what you are doing so I can hope to construct a reproducible test case, or suggest further diagnostic steps. If you don't do any of this your bug report is unlikely to be useful and will be closed like this one.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

As linked above and in the issue template you were provided with there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
