### ISSUE TITLE
Renderdoc in mac

### ISSUE THREAD

**Issue by lionel008** [baldurk/renderdoc#2261]
## Environment  Macos BigSur 11.2.3
* RenderDoc version: from git
* Operating System: Macos
* Graphics API: XXX

Hello , I compiled renderdoc for mac successfully  , however when i run chrome , error comes out "no output from lsos".  Any idea what it could be?

![image](https://user-images.githubusercontent.com/25028836/116110372-8b352100-a6ad-11eb-82c4-fa45d395fddb.png)

![image](https://user-images.githubusercontent.com/25028836/116110452-9b4d0080-a6ad-11eb-82b0-492c0c4a38e5.png)

Regards,
John

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
