### ISSUE TITLE
Renderdoc isn't working for me

### ISSUE THREAD

**Issue by SydWil223** [baldurk/renderdoc#2263]
I keep getting these warnings from Renderdoc. 

Core 2980 02:21:34 core.cpp(459)          Log   RenderDoc v1.13 Windows 64-bit Release (cc05b288b6d1660ab04c6cf01173f1bb62e6f5dd) loaded in replay application
Core 2980 02:21:34 core.cpp(470)          Warning **Couldn't open socket for target control** What does this mean?         
Core 5952 02:21:34 core.cpp(459)          Log   RenderDoc v1.13 Windows 64-bit Release (cc05b288b6d1660ab04c6cf01173f1bb62e6f5dd) loaded in replay application
Core 5952 02:21:34 core.cpp(470)          Warning **Couldn't open socket for target contro**l  Same thing here.   
Core 5952 02:21:34 settings.cpp(460)      Log   Loading config from C:\Users\Sydni\AppData\Roaming\renderdoc\renderdoc.conf
Core 2980 02:21:34 crash_handler.h(150)   Log   Timer Waiting for crash handling server - 92.294 ms
Core 2980 02:21:34 crash_handler.h(156)   Log   Created crash-handling server \\.\pipe\RenderDocBreakpadServer75197005163
Core 2980 02:21:34 crash_handler.h(87)    Log   Connecting to server \\.\pipe\RenderDocBreakpadServer75197005163
Core 2980 02:21:34 settings.cpp(460)      Log   Loading config from C:\Users\Sydni\AppData\Roaming\renderdoc\renderdoc.conf
UI 2980 02:21:34 qrenderdoc.cpp(94)     Log   QRenderDoc initialising.                          
Core 2980 02:21:34 crash_handler.h(51)    Log   Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer75197005163
Core 2980 02:21:34 crash_handler.h(87)    Log   Connecting to server \\.\pipe\RenderDocBreakpadServer75197005163
Core 2980 02:21:35 d3d11_replay.cpp(125)  Log   Running replay on nVidia / NVIDIA NVS 5400M 23.21.13.9265
Core 2980 02:21:35 android_tools.cpp(347) Log   Initialising adb using 'C:\Users\Sydni\Desktop\RenderDoc_1.13_64/plugins/android/adb'
Core 2980 02:21:35 d3d12_replay.cpp(102)  Log   Running replay on nVidia / NVIDIA NVS 5400M 23.21.13.9265
Core 2980 02:21:35 vk_core.cpp(3830)      Warning [loader] setupLoaderTermPhysDevs:  **Failed to detect any valid GPUs in the current config** ???
Core 2980 02:21:35 vk_core.cpp(3830)      Warning [loader] setupLoaderTrampPhysDevs:  **Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.** VK?
Core 2980 02:21:35 vk_device_funcs.cpp(498) **Error Assertion failed: '(vkr) == (VK_SUCCESS)' (vkr=VK_ERROR_INITIALIZATION_FAILED, VK_SUCCESS=VK_SUCCESS)** What? 
Core 2980 02:21:35 vk_manager.h(172)      **Error Assertion failed: 'm_LiveResourceMap.empty()'**  O
Core 2980 02:21:35 vk_manager.h(175)      **Error Assertion failed: 'm_CurrentResourceMap.empty()'** M
Core 2980 02:21:35 vk_manager.h(176)      **Error Assertion failed: 'm_WrapperMap.empty()'** G
Core 2980 02:21:35 core.cpp(633)          **Warning Couldn't create proxy replay driver for Vulkan: Current hardware unsupported or incompatible with captured hardware** (I must be missing something.) 
Core 2980 02:21:40 android_tools.cpp(362) Log   Started adb server

Whenever I tried to load a program, it kept crashing and giving me this warning:

Core 2980 02:23:31 win32_network.cpp(261) Warning recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.

I tried different builds but kept getting the same results.

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: OpenGL/Direct3D11 (presumably, I don't have Vulkan) 

Not sure what's going on but I'll provide other details:

Processor: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz   2.90 GHz
Drivers (display adapters): Intel(R) HD Graphics 4000 and NVIDIA NVS 5400M

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
