### ISSUE TITLE
Crash when launching a Game Maker Studio 2 project with RenderDoc

### ISSUE THREAD

**Issue by thatcosmonaut** [baldurk/renderdoc#2266]
## Description

My team is developing a game using Game Maker Studio 2.2.5, which has a D3D11 renderer. When attempting to launch the project using RenderDoc, a Windows popup appears with the message "C++ runtime: This application has requested the runtime to terminate it in an unusual way". This happens before the project becomes capturable. 

The project launches normally if not using RenderDoc.

Oddly enough, this wasn't happening last week, but we just merged a rendering overhaul. However I'm not exactly sure of any particular change that would have caused this and we aren't doing anything non-standard for Game Maker. 

## Steps to reproduce

Launch our project with RenderDoc. I can't provide a build publicly but I can provide one privately on request.

## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: D3D11

* GPU: AMD Radeon RX 5600XT

**Comment by baldurk** [comment]
Yes, please provide a build to me privately, otherwise I have no information to go on.

**Comment by thatcosmonaut** [comment]
Emailed you a build.

**Comment by baldurk** [comment]
This looks to be a out-of-memory failure. The application is a 32-bit process and while it's large address aware it looks like it uses around ~1.5GB at peak during load itself and then uploads at more than 1GB of data to the GPU (there are four 8192x8192 RGBA8 textures). The overhead of recording and shadowing that that triggers an allocation failure, presumably due to VA space fragmentation/exhaustion.

If you build your application as a 64-bit executable (even just temporarily/locally for use with RenderDoc) it should work fine, or else reduce the size of those GPU uploads as it's _probably_ only just going out of bounds with back of the envelope maths. It depends on whether there are more uploads coming behind those though which don't happen due to the crash.
