### ISSUE TITLE
Segmentation fault error when loading frame 0 capture

### ISSUE THREAD

**Issue by bobtedbob** [baldurk/renderdoc#2267]
## Description

I have a very simple app drawing two quads. 

I have the following extension enabled

VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT

And I enable this feature :

VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT

And I get this error when running (one per buffer used)

[VULKAN DEBUG CALLBACK][ERROR][VALIDATION] Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x710000000071, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDrawIndexed: Hazard READ_AFTER_WRITE for index VkBuffer 0x710000000071 in VkCommandBuffer 0x7ff59ce903d0[]. Access info (usage: SYNC_VERTEX_INPUT_INDEX_READ, prior_usage: SYNC_TRANSFER_TRANSFER_WRITE, write_barriers: 0, command: vkCmdCopyBuffer, seq_no: 9, reset_no: 1).

When loading this simple app up in renderdoc and loading the frame 0 capture I get a segmentation fault and the application crashes to the command line. 

## Steps to reproduce

Some times the application crashes when I load the capture, other times when I expand the events in the capture.

Loading the extension is not the cause of the segmentation fault but the error might be causing something wrong in renderdoc. When I load the frame 1 capture (which doesn't have the vkCmdCopyBuffer run) the capture loads fine. In a previous iteration of my code where I didn't have these SYNC errors renderdoc did not crash. I decided to design the pipeline barriers slightly differently hence there being a difference.

## Environment

* RenderDoc version: RenderDoc v1.14 Linux 64-bit Development (f530392bc1892775be9adc583483647b1f45cf68)
* Operating System: Ubuntu 21.04
* Graphics API: Vulkan

GPU Intel 620 integrated

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly completing the prompted sections. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) which is linked from the template you used and open a new issue which does fill out the sections properly. Do not reply to this issue with more information, please open a new issue.

As detailed in the documentation and evident by the section title, for "steps to reproduce" you must actually provide steps I can take to reproduce the problem. Most commonly and simplest for everyone would be for example sharing your application or a capture file that shows the problem. If you can't share these publicly you can [email me privately](mailto:baldurk@baldurk.org?subject=RenderDoc%20bug%20repro%20case) with a google drive/dropbox/etc link. If you can't share these even privately you should say that and provide a significant amount of information about what you are doing so I can hope to construct a reproducible test case, or suggest further diagnostic steps. If you don't do any of this your bug report is unlikely to be useful and will be closed like this one.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

As linked above and in the issue template you were provided with there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by bobtedbob** [comment]
Shall I edit this issue or create a new one? seems like I am just missing the capture being uploaded (which I can add) and a comment saying I don't want to share my code.

**Comment by baldurk** [comment]
As in the comment above: Do not reply to this issue with more information, please open a new issue.
