### ISSUE TITLE
Improve usability of Launch Application - Environment Variables

### ISSUE THREAD

**Issue by StefanoLanza** [baldurk/renderdoc#2273]
## Description

Under the Launch Application tab you can list environment variables for your application. After fighting with these settings for few hours, may I suggest these improvements:
* It should be possible to maximize the environment variables window. By default it opens with a small size, which is annoying. Also, it does not remember its previous size.
* Environment variables should be able to include and expand other environment variables e.g.
```
 ANOTHER_PATH   Set     someFolder
 PATH           Append  %ANOTHER_PATH%
```
I had to copy n paste the value of ANOTHER_PATH in the sequence of values for PATH. That is unexpected behaviour.
* It should be possible to append multiple values to the same var:
```
  PATH Append   someFolder
  PATH Append   anotherFolder
```

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
