### ISSUE TITLE
Visualizer shader code doesn't seem to support #includes

### ISSUE THREAD

**Issue by ldecarufel** [baldurk/renderdoc#2275]
## Description

We have complex code to pack and unpack our GBuffer data, and it would be very useful to include the packing code from our engine directly.

However, the visualizers don't seem to support #includes.

For example, If I add this line in the visualizer HLSL file:

`#include "C:\Users\name\AppData\Roaming\qrenderdoc\GBufferAccess.hlsl"`

I get the following error:

`// Can't find file C:\Users\name\AppData\Roaming\qrenderdoc\GBufferAccess.hlsl`

Even though I know the file exists.

## Steps to reproduce

Add an #include preprocessor instruction in a visualizer shader, inside RenderDoc's visualizer editor, the click "Refresh".

RenderDoc will remove the #include code and replace it with the error in a comment.

## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10 20H2
* Graphics API: DirectX
* NVIDIA GeForce GTX 1070, driver 27.21.14.5671

**Comment by baldurk** [comment]
That commit adds include handling for custom visualisation shaders. I also set it up so that `#include <foo>` system includes will search the places where custom visualisation shaders are searched for. This might not be useful if the shader you're writing is next to the include, but could be useful if you have e.g a custom shader stored in your local directory and want to reference a project/shared directory for utilities like this.

**Comment by ldecarufel** [comment]
Well that was quick!
Thanks for the update! :-)
