### ISSUE TITLE
Pixel debugger needs a "Step Over" button

### ISSUE THREAD

**Issue by BBI-JohnwillKeating** [baldurk/renderdoc#2276]
## Description

When debugging a pixel and tracing through the shader code, it would be useful to have a "Step Over" button in addition to the "Step Next" button, which essentially does a "Step Into."  The "Step Over" functionality can be accomplished by selecting the next line and then pressing "Run To Cursor" button, however, this is an awkward action to perform repeatedly when I'm trying to step line by line.  The "Step Next" button does not do what I want in the case where each line contains a function call that I don't want to step into.
I suggest using F10 for "Step Over" and F11 for "Step Next," similar to Visual Studio.

## Environment

* RenderDoc version: 1.13
* Operating System: Windows10
* Graphics API: DirectX

**Comment by baldurk** [comment]
I can look into it, but from memory I've considered this before and run into issues with imprecise/broken debug info on D3D. I'm not sure if it can be implemented entirely reliably there since shaders are effectively fully inlined into a single bytecode function, and the debug inlining info doesn't always match up correctly. It could be implemented easily enough on vulkan though.

**Comment by baldurk** [comment]
That commit adds stepping functions forward and backwards that distinguish between into/over/out. This only applies when source debugging (when debugging assembly everything is always one instruction step), and is only as good as the callstacks in the underlying debug information.

The shortcuts match VS for the most part except for step out. Shift is used consistently to indicate backwards running, so Shift-F10 is not step out it's step backwards. Control-F11 is used for step out (and so Control-Shift-F11 can be used to step out from a function, backwards to where it was called.
