### ISSUE TITLE
"D3D11: Removing Device." leads to hung UI

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#228]
Trying to diagnose a bug in Chrome's rendering, I've been capturing a stream with Renderdoc. When I try to replay the stream, inspecting certain API calls leads to a removed device in D3D11, which hangs the UI in Invoke (while (!cmd.processed)).

I tried debugging this but I'm not sure what's going on. If you want me to upload the stream I can share it on Google Drive.

**Comment by baldurk** [comment]
This error comes from D3D itself and just kind of generally means "something went badly wrong and it's not recoverable". Could be GPU hang/timeout, driver crash or other such fatal error. It's not too surprising the UI then hangs in Invoke since it might be waiting on some result which is never going to return.

If you can upload the .rdc I'll certainly try and take a look if I can repro the bug. What particular action were you doing on inspecting the event? If it was just selecting it, the most likely suspect (although not the only possibility) is the mesh output view fetching output data, since that's the most 'stressful' action that takes place just by selecting.

**Comment by null77** [comment]
Thanks for following up. I've uploaded the capture to Google Drive [here](https://drive.google.com/file/d/0Bx8afYwPAVAOSTlIeEhWbml0UTA/view?usp=sharing).

I was selecting the event in the inspector, and I believe the hanging call was something to do with meshing or texturing. I think possibly the command stream was trying to do something wrong (due to the the buggy app here) but it would be nice at least if the UI didn't hang.

To repro open the capture log and click on event 958, or probably any of the draw calls around there.

**Comment by baldurk** [comment]
This looks like it was down to a little known (at least to me) feature - that the BaseVertexLocation on indexed draws is actually signed and can be negative. I wasn't handling this properly so it was wrapping around and trying to copy from waayyy off the end of a buffer.

![image](https://cloud.githubusercontent.com/assets/661798/14022535/883b614e-f1e0-11e5-8745-2f325fb59718.png)

As a side note I wonder if this negative basevertex value is intended, since if I manually clamp it to 0 then the mesh looks a lot more healthy both in transform and in output:

![image](https://cloud.githubusercontent.com/assets/661798/14025581/0e9d2b92-f1ef-11e5-8049-424015d92621.png)

compared to what it looks like with just replaying the log faithfully:

![image](https://cloud.githubusercontent.com/assets/661798/14025545/ec39e5a4-f1ee-11e5-8b9a-9eb7f221fe26.png)

**Comment by null77** [comment]
thanks for the follow-up.

Yes the negative start vertex location is something ANGLE uses a fair bit - we normally use it in conjunction with the 'offsets' to the vertex buffer to reference multiple vertex attributes in a single buffer.

You're right there's a bug here, where we were using an incorrect offset. I was trying to diagnose this bug with renderdoc, hence the crashes. What was happening (I think) is that the negative offset was correctly applied in a prior call, then the bug was that it wasn't being update in a subsequent call, making the previously sensible negative value invalid.

I've fixed the bug in ANGLE but handling this out-of-bounds-ness could make Renderdoc more robust.

**Comment by null77** [comment]
I tried to verify today, but it seems I can't use renderdoc with Chrome on Windows 10 at the moment. I was having success with Windows 7 earlier. I am not sure how to diagnose this, but I inject into the process, and clicking Trigger Capture doesn't seem to do anything. Anyway, I'm happy to trust your verification that the bug is fixed for this.

**Comment by baldurk** [comment]
This wouldn't be OS-specific, but if you're injecting into the process (rather than launching via renderdoc) you need to be careful that D3D initialisation happens after the injection. The easiest way to tell is if the overlay appears or not.

I've never even considered trying to debug Chrome so I'm not sure what's the best way to get renderdoc working with it :).

I'll close this bug for now but if you're still having issues, feel free to reopen. You can also get in touch if you want help with getting renderdoc injected.

**Comment by null77** [comment]
The method I use to inject into Chrome is with a flag "--gpu-startup-dialog", which hard-codes a MessageBox to pop up very early in the process start. It shouldn't be loading D3D11 DLLs by then, since we load those at run time somewhat later, but I should double-check just to be sure.

Using this method I did get the overlay and capture to work on Windows 7 but not on my home machine running Windows 10. I also have Nsight installed on my home machine but not at work, so I should try removing that as well.
