### ISSUE TITLE
Win Arm64 RenderDoc Support

### ISSUE THREAD

**Issue by nopjne** [baldurk/renderdoc#2288]
Allow RenderDoc to launch and capture native Windows Arm64 apps.

I am porting a DX12 project to the Surface Pro X and found that RenderDoc can't launch my app when it's built as native Windows Arm64, because the profiler shim isn't built for native Arm64.
Could this support be added to RenderDoc please?

It will probably require upgrading to VS2017+ instead of VS2015 and some minor porting to Arm64. (May not be too many changes from quick review..)
If the x64 profiler shim can't be injected, the tool could try to inject the Arm64 version instead or maybe the user could hint to the launcher with UI options to use: Arm64 instead of x64.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
