### ISSUE TITLE
Failed to load the RenderDoc Module

### ISSUE THREAD

**Issue by aladebaran** [baldurk/renderdoc#2293]
I did my screen and i'm having problem to upload those on Blender.Mainly with this error: 

Error: Failed to load the RenderDoc Module.
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output

And with this: 

location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:\Users\RWCephei\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\RWCephei\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\google_maps.py", line 304, in importCapture
    prefix = makeTmpDir(pref, filepath)
  File "C:\Users\RWCephei\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\utils.py", line 67, in makeTmpDir
    os.makedirs(base)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'C:\Users\RWCephei\Documents\Andria-l5co0mn'

Please, help me to solve this. I'll be very grateful!
Thanks, hoping you will answer me

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
