### ISSUE TITLE
Indicate that depth writes are not happening without depth tests in Vulkan

### ISSUE THREAD

**Issue by Novum** [baldurk/renderdoc#2296]
## Description

Right now RenderDoc will show this for Vulkan:
![image](https://user-images.githubusercontent.com/112222/122509727-dee72b00-cfc9-11eb-9092-2779249e14eb.png)
I fell into this trap again today. There are no depth writes without depth test enabled by Vulkan spec.

Would it be possible to just show it as disabled or indicate otherwise that it's implicitly disabled?

## Environment

* RenderDoc version: 1.14
* Operating System: Win 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit changes the `Write` and `Func` entries to read 'Disabled' when the depth test isn't enabled, across all APIs (since this behaviour is the equally true and equally non-obvious everywhere). Depth bounds is excluded since as far as I can tell it's independent - it's spec'd so on GL and VK, and D3D12 doesn't mention either way.

**Comment by Novum** [comment]
Awesome Baldur, thanks! I'm sure this will safe a lot of people some head scratching.
