### ISSUE TITLE
Vulkan shader editing

### ISSUE THREAD

**Issue by wheelmac92** [baldurk/renderdoc#2297]
I try to recompile shaders and I get an error that a flag --use-storage-buffer is not found by glslangValidator, while using Vulkan SDK 1.2.176.1, and RenderDoc 1.14

Running "C:/VulkanSDK/1.2.176.1/Bin/glslangValidator.exe" -g -V -o C:/Users/nproc/AppData/Local/Temp/shader_output C:/Users/nproc/AppData/Local/Temp/shader_input -S frag --client vulkan100 --target-env vulkan1.0 --entry-point main --client vulkan100 --target-env spirv1.3 --target-env vulkan1.1 --entry-point main --use-storage-buffer
glslangValidator: Error: --use-storage-buffer: unrecognized command-line option (use -h for usage)

Process exited with code 1.
Output file is 0 bytes

![image](https://user-images.githubusercontent.com/58401060/122655823-93489480-d123-11eb-855b-0cad6a90b7c2.png)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
