### ISSUE TITLE
[GL] Failed to cap frame - we saw an Unmap() that we didn't capture the corresponding Map() for

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2303]
## Description

Just trying to capture something running on GLES-3.2 on Linux

## Steps to reproduce

```bash
# install Rust and Git on Linux
git clone https://github.com/kvark/wgpu -b gles
cd wgpu
cargo build --example shadow
# launch `./target/debug/examples/shadow` from RenderDoc with environment `WGPU_BACKEND=gl` and try to capture any frame
```
My application is definitely matching any Map with Unmap.

Looking through [RenderDoc code](https://github.com/baldurk/renderdoc/blob/f2f8578a195e1aff26d5d952db9222910df01b7b/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp#L2728), it might be just that the error message is misleading. There are many conditions that make it go `Mapped_Direct`, and somehow the Unmap thinks that `GL_MAP_WRITE_BIT` can't be on this buffer.

## Environment

* RenderDoc version: 1.14 (also tried 1.10)
* Operating System: Linux
* Graphics API: OpenGL ES 3.2

Side note: working on https://github.com/gfx-rs/wgpu/pull/1510
Still unable to build RenderDoc because of #2283 .

**Comment by baldurk** [comment]
Can you give more details - this error you mentioned is not a fatal one and is expected as normal depending on the application, it just means that the particular frame can't be captured and RenderDoc will try again to capture the next frame. Do you get no capture at all? Can you share the RenderDoc log from the run where you're trying to capture?

Also would you be able to share a binary build of your program? If not that's OK and I can try to build it myself, but it will take a little bit before I can make the time necessary to do that.

btw #2283 as mentioned in that issue is a compiler bug, I'd suggest using clang instead of gcc or seeing if you can build RenderDoc without any extra compile flags that may be introduced by your distro, or worst case building in release so that warnings are not treated as errors and ignore the false warnings.

**Comment by kvark** [comment]
Yep, nothing is being captured at all. I uploaded both the executable (Linux x64) and the capture log to https://wormhole.app/l3AN5#_p05LwX6h87jpyEIzKA7NQ . Note that it needs to be run with `WGPU_BACKEND=gl` environment to reproduce.

**Comment by baldurk** [comment]
I get an error going to that link:

> We're sorry! This link is invalid
> The secret key is invalid

**Comment by kvark** [comment]
Looks like wormhole is having issues with this (or somebody is messing with my executable?). I've just sent this to your email instead.

**Comment by baldurk** [comment]
That commit should fix the issue. Each frame the application was creating/mapping/unmapping buffers with the `PERSISTENT_BIT` set. I'd previously only seen such maps be actually persistent so the codepath for handling those maps wasn't properly accounting for them being unmapped in the captured frame.
