### ISSUE TITLE
Texture Viewer UI corrupt with LDA aka SLI setup 

### ISSUE THREAD

**Issue by monamimani** [baldurk/renderdoc#2307]
## Description

I am exploring a capture that I made and Renderdoc is behaving weirdly.  when I select an API call like CopyTextureRegion or DrawIndexedInstanced it "corrupts" the UI and the Inputs and Outputs of the Texture Viewer don't update.
My feeling is that RenderDoc doesn't support SLI? This capture is done in Linked display adapter mode using 2 RTX8000 and I have a feeling there is an issue here. I don't have more insight for now. But I am opened to answer any question.

## Steps to reproduce

Open a capture and navigate the Event Browser to EID 423 for example or EID 1053
I will send you a link to the capture.
![parsecd_0Qzs0Bpp78](https://user-images.githubusercontent.com/492860/123870886-f941d280-d900-11eb-8aa0-7e28fac6d4ea.png)
![parsecd_3xLrQNcrbD](https://user-images.githubusercontent.com/492860/123870901-fe9f1d00-d900-11eb-8117-bb771cbecb84.png)

## Environment

* RenderDoc version: 1.14
* Operating System: Win10 1809
* Graphics API: D3D12

To give you more context here, this is a capture of Unreal 4. I am using Ue4 with nDisplay and Textureshare. I am sharing textures between a proprietary software and Unreal. As for the hardware setup it is 2 RTX8000 in LDA (linked display adapter, aka SLI in the nVidia control panel). The I dea is to give each software a gpu. Through nDisplay I have configured the Unreal viewport to be on gpu node index 1 ( gpu mask 2) where the proprietary software is on node index 0 ( gpu mask 2). I am trying to debug why Ue doesn't show the texture it is receiving. But when I try to look at the Texture in the Texture viewer Renderdoc seems to have issues. it doesn't give me and warning or errors.

I hope that explains enough the context. If not I can answer other questions!

**Comment by baldurk** [comment]
The corruption most likely comes from a TDR error, which would also trigger a stall of the desktop and a brief flash to black (possibly with some minor corruption of any other programs using the GPU like browser windows).

In general yes RenderDoc does not support SLI/multi-gpu setups and I don't have plans to add that. Unfortunately from my understanding of D3D12 there's no way to fake reporting to force the application to use it as separate individual GPUs because the device itself gets reported as a combined blob.

That commit allows the capture you sent to open correctly on my machine by forcing all `NodeMask`s to 0, but I don't have a SLI setup to test to see whether it works there and I can't promise if it will work for other captures. I can only suggest if you have further problems to debug your program in single-GPU mode.
