### ISSUE TITLE
"Run to Cursor" only works forwards, not backwards

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2312]
## Description

The "Run to Cursor" function only works if the cursor is past the current location, not before it.  This applies to both pixel and vertex shaders, and applies to both assembly and source views.  When trying to use it when the cursor is behind the current location, it instead jumps to the end of the shader.

There are a few workarounds:
* Clicking "step back" a ton.  This works, but is annoying.
* Clicking "run backwards" and then using "run to cursor".  This would work, except that "run backwards" moves the cursor and resets scrolling, so you need to find your place again.
* Setting a breakpoint and then using "run backwards".  This works, but it requires several extra clicks.  (That it does work, though, makes me think it wouldn't be too hard to implement "run to cursor" in this case, though that's only the case if the actual implementation uses breakpoints, which I don't know for sure.)

## Steps to reproduce

1. Open [this capture](https://github.com/baldurk/renderdoc/files/6780711/Lesson08.zip), which includes frames from Vulkan, D3D11, and D3D12.
2. Start debugging either a pixel or vertex.
3. Click somewhere ahead, and then click "run to cursor" (either by right-clicking and selecting run to cursor, or by using the button in the toolbar); execution will properly advance to the cursor.
4. Click somewhere behind where you just clicked, and then click "run to cursor".  Instead of going to the place you clicked, execution will go to the end of the shader.

In the event that this is something that should work, but only fails with that capture, I generated the above capture with [Dolphin](https://dolphin-emu.org/) running the [lesson08](https://github.com/devkitPro/gamecube-examples/tree/master/graphics/gx/neheGX/lesson08) test case; a Dolphin fifolog that can be used with Dolphin's fifo player is also included in the zip file.  The "Enable API Validation Layers" check box on the advanced tabs in graphics settings also enables debug symbols for shaders, which was done here.  (I couldn't use Dolphin's OpenGL backend with renderdoc, but the other backends did work.  This may be a separate bug, but I'm not immediately worrying about it.)

## Environment

* RenderDoc version: v1.14
* Operating System: Windows 10
* Graphics API: I've confirmed that run to cursor doesn't currently work like this on D3D11, D3D12, and Vulkan; I was unable to test on OpenGL.

**Comment by baldurk** [comment]
Yes, run to cursor goes forward only as that's the only way it could work. Without a specific direction it would often be ambiguous.

I'll treat this as a feature request for a "run backwards to cursor" feature, which is reasonable. Likely there's the same benefit from running backwards to inf/nan or sample as well.

**Comment by Pokechu22** [comment]
Ah, I didn't realize it could be ambiguous, but I guess it could be with loops or with function calls. I was mainly using it to jump around in a single, mostly flat, shader (that was generated, so it didn't have any loops or the like).

One other thing that would make it useful is if "run to cursor" didn't move execution (and more importantly, the cursor) if it goes past the cursor and hits the end of the shader.  However, that could be confusing since if it didn't move it, then it would seem like the button did nothing; it could maybe be disabled if there's nothing past the cursor, but I suspect that'd be terrible for performance.  Or maybe the cursor could be left in the same place when using "run to cursor", even if execution ends up somewhere else.

**Comment by baldurk** [comment]
I'm not sure what you mean about running past the cursor, or there being "nothing past the cursor"?

Run to cursor effectively behaves like setting a temporary breakpoint on the cursor, and running forwards. If you have control flow and you use it on a branch which isn't taken, then yes execution will continue on past that point and stop at the next breakpoint or the end of the shader, whichever comes first. That's the same as a normal debugger though and I believe is the expected behaviour.

As you say, it's important that the user understands and can see clearly where execution is at any time especially if it changes significantly after a non-stepping action, so scrolling and moving the cursor is deliberate.

**Comment by Pokechu22** [comment]
I think it's fair to say that I don't know exactly what I want.  I don't/didn't use "run to cursor" when debugging normally (I only now found that Visual Studio has such a feature when trying to compare its behavior; now that I know it exists I'll probably use it though).  The behavior in VS is basically what you describe, except that in a GUI application, if it never terminates it just resumes execution (but doesn't change scroll position or anything like that).  Of course, shaders usually terminate so that's not exactly analogous.  VS also lets you drag the arrow indicating the next statement to be executed, but "this may have unintended consequences" (i.e. it usually crashes horribly if you try to do it).  I haven't used any other time-travel debugging features, so I don't have experience with them.

My main goal is to navigate quickly around a somewhat long, generated shader, which is composed of several similar looking sections right next to each other.  (The capture I uploaded probably isn't a perfect example of this, as it only has one TEV stage, but I wanted to pick one where there was also source for it.)  The issue with scrolling to the bottom is that it makes it easy to lose my place in the shader, and since things look fairly similar, it's annoying to find the previous position.  I guess what I'm looking for is more along the lines of "jump to here" regardless of whether that's forwards or backwards from the current position, but I understand now that that's ambiguous for most shaders.

Hopefully that makes some sense?

**Comment by baldurk** [comment]
You can see the exact behaviour in VS if you put a breakpoint somewhere else afterwards that will get hit. Running to cursor on a location that isn't executed will then immediately continue and then stop on that breakpoint with the same behaviour as RenderDoc.

The cursor dragging (or 'set next statement' in VS) is not currently possible in RenderDoc, and it means changing the current instruction pointer without actually executing anything between where you are and it. It's possible to use to e.g. re-run a function twice which can be handy and safe if the function has no side-effects.

It seems like you've thought through the consequences and come to realise why it is like it is. As I mentioned earlier, having a 'run backwards to cursor' feature is reasonable, but otherwise the way it works is necessitated by UI constraints/requirements and simply how the feature is expected to work. Unfortunately it's not possible to read your mind to determine intent beyond what the action does :).

I don't have any suggestions on how you should step through shaders except maybe to set breakpoints instead, or alternatively step only to before branches if you're unsure if they'll be taken, then step further. I don't think this is really any different than debugging a program that runs once on the CPU and that's roughly how I'd work.

**Comment by Pokechu22** [comment]
I just thought of one other thing that might help: being able to undo a step/run action.  Then if e.g. run to cursor goes past the expected location, it would be fairly easy to revert to the previous position and try again (especially if it reset the cursor and scroll position in addition to the execution location).  I'm not sure how hard it would be to implement that though.

**Comment by baldurk** [comment]
I don't want to start adding a level of history on top of the existing operations. That feels like it would be complex to manage especially with the different interactions like stepping and running etc, and in either case I don't feel like there is a problem that needs to be solved there.

**Comment by baldurk** [comment]
That commit adds backwards versions of run-to-cursor as well as run-to-sample and run-to-nan/inf. Run backwards to cursor gets the shortcut ctrl-shift-F10, the others are only accessible via the menu items.

**Comment by Pokechu22** [comment]
Thanks!
