### ISSUE TITLE
Override the type of a watch entry in shader debugger

### ISSUE THREAD

**Issue by cskilbeck** [baldurk/renderdoc#2313]
## Description

Shader model registers can contain `float`s and `int`s at different times. It would be useful to be able to set the type of an entry in the watch window so I can inspect the value correctly without resorting to the global int/float setting.

One solution could be a dropdown combobox in the Type field of the watch entry.

Apologies if there is another way to accomplish this which I've missed. I'm aware of the "Integer Register Display" and "Float Register Display" entries in the popup menu which appears when you right click on the source, and that's what I'm using now. This new feature would allow me to get simultaneous views of the register as both integer and float at the same time (by creating two Watch entries pointing at the same register).

## Environment

* RenderDoc version: v1.13
* Operating System: Windows 10 Pro 21H1 19043.1083
* Graphics API: Direct 3D 11

**Comment by baldurk** [comment]
As mentioned in [the documentation](https://renderdoc.org/docs/how/how_debug_shader.html#debugging-displays) you can use visual-studio style type overrides in the watch window. E.g. if you wanted to see `r0` as both float and int, you could add one watch for `r0,f` and one watch for `r0,i` or `r0,x` if you prefer hex.

However if you're debugging on D3D11 I'd very strongly recommend that you build your shaders with debug information enabled so that you can debug at the source level, that way you'll see the variables with their correct types automatically.

**Comment by cskilbeck** [comment]
Super, thanks! I didn't know about the suffix thing, sorry, should have looked closer at the docs. I do have debug info enabled but sometimes it doesn't get the right type during intermediate operations.
