### ISSUE TITLE
Pixel shader output as shown in the debugger doesn't match the actual pixel value.

### ISSUE THREAD

**Issue by Card1Dominik** [baldurk/renderdoc#2316]
## Description

I pick a pixel to debug in the texture viewer but when stepping through the pixel shader and inspecting the value of the output colour it does not match the actual pixel colour displayed in the the texture viewer. I expect them to have the same value. The calculations that happen in the pixel shader seem to be correct in itself, but they don't seem to belong to the pixel that is actually being debugged.

## Steps to reproduce

1) Debug a pixel by selecting a pixel in the texture viewer and pressing the "Debug" button.
2) Step through the debug shader and observe that the reported values don't match the pixel being debugged, most notably the output colour, which does not match the pixel colour that is actually displayed in the texture viewer.

The issue only happens for a few select pixels in the capture, not for every pixel. More precisely, it seems to happen only for the coloured pixels that are surrounded by the black pixels (see attached picture) which are of course the pixels I am interested in.

The picture highlights the issue pretty well. If you need the capture I would have to check with our legal department whether it would be okay to share.

![diff_pixel_col](https://user-images.githubusercontent.com/87380254/125500033-a4f48640-27e3-44ba-b9f9-632b42400b51.png)

## Environment

* RenderDoc version: 1.14
* Operating System: Windows 10 Pro 64-bit Version 20H2
* Graphics API: DirectX11
* Graphics card:  Nvidia Quadro P2000, driver-ver: 461.92

**Comment by baldurk** [comment]
This kind of discrepancy can be caused by a few different things. Aside from bugs in the shader debugger if your shader hits undefined behaviour or is too sensitive to precision issues (beyond what's guaranteed by the API) you may get a different debug result.

Without a reproducible test case though there's nothing I can do to determine what this is. If you can share the capture please do, otherwise I would need you to remote debug which can be painstaking in cases like this, if you'd like to do that instead please email me to co-ordinate it.

**Comment by Card1Dominik** [comment]
I have sent the capture file to baldurk@baldurk.org

**Comment by baldurk** [comment]
Yes this is because your shader is invoking undefined behaviour. You're doing a `smoothstep()` where the min and max values are identical (in the y component) which is illegal - `smoothstep()` is only defined for `min < max` componentwise. The underlying instructions end up flipping between -INF and INF for the delta depending on behaviour around signed zero, so you end up with unpredictable interpolation of the value.

If you open the capture on WARP you may see the artifacts disappear entirely, it does for me at least.
