### ISSUE TITLE
Is three any plan to support the vulkan raytracing capture

### ISSUE THREAD

**Issue by jiaolu** [baldurk/renderdoc#2317]
## Description

Is three any plan to support the raytracing capture?
we hope the renderdoc could support the these two new vulkan extensions, 

VK_KHR_ray_tracing_pipeline
VK_KHR_ray_query

so we can debug issues arise from developing the raytracing application. 

## Environment

* RenderDoc version: 1.14
* Operating System: windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I currently don't have any plans to work on ray tracing support.

**Comment by jiaolu** [comment]
thanks for response . 
I am interested to implement this feature, but i am not familiar with renderdoc code base, can you point some directions to get going?

**Comment by baldurk** [comment]
This is a **huge** feature to implement and would impact many parts of the codebase significantly. I can't point you to a starting place because it's much too wide in scope to have simple directions.

To be honest this isn't something I would suggest that you tackle as your first entry to the project, and unless you expect that you will be able to dedicate sufficient time (e.g. one full-time year) to implement the support and analysis features robustly and ideally contribute to maintaining them going forward I would not recommend spending time on it.

**Comment by expenses** [comment]
Even though I know you don't take donations @baldurk (https://github.com/baldurk/renderdoc/issues/328), I'd just like to say mention here that if someone did start implementing raytracing support I would be very happy to sponsor that effort. I know others would be as well.

**Comment by GabeRundlett** [comment]
I would love some RT support. I currently prefer renderdoc for everything debugging related, but for my RT projects I need to use NSIGHT's debugger 💀

**Comment by michaelonchrome** [comment]
Just checking in to see if there are any updates on RenderDoc support for ray tracing (RT)?

**Comment by baldurk** [comment]
The recently released [v1.36](https://github.com/baldurk/renderdoc/releases/tag/v1.36) includes support for capturing raytracing work on D3D12 and Vulkan. Note that this allows for debugging all non-raytracing work happening in a capture with accurate raytracing results, but no debugging of the raytracing work itself is supported.

Note that on vulkan RenderDoc uses the API builtin capture support for pipelines, which is not currently implemented on nvidia drivers, so on those systems only ray query functionality will be available. I have contacted nvidia and they plan to implement this in a future driver, when it does RenderDoc's support should work automatically.
