### ISSUE TITLE
Mapped buffer contents are replayed as zeroes on DX12

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2323]
## Description

Capturing a DX12 application and then replaying it shows some of the (staging) buffer contents as zeroes. As a result, replaying isn't usable, since it works on a different set of data and shows no useful rendering.

What I expect: replaying in RenderDoc produces the same render as the original, assuming the application is written correctly. Here is what the original render looks like:
![render](https://user-images.githubusercontent.com/107301/126736700-8e9cfb75-3bcd-4ec0-833b-31621995b47f.JPG)

Here you can find both the application itself (Windows x86_64 executable, debug built from Rust) and the RenderDoc capture I took:
[shadow.zip](https://github.com/baldurk/renderdoc/files/6866508/shadow.zip)

In order to run the application on DX12, the following environment variable is needed: `WGPU_BACKEND=dx12` (!).
Otherwise, it will run on Vulkan and show no issue.
This reproduces 100% of the times for me.

## Steps to reproduce

Configure RenderDoc to run the EXE from the "shadow.zip" file under "WGPU_BACKEND" environment variable set to "dx12".
Make a capture and see it. The data in "_Staging" buffer is all zero.

## Environment

* RenderDoc version: 1.14
* Operating System: Windows10
* Graphics API: DX12

* GPU: Ryzen 3500U

**Comment by baldurk** [comment]
RenderDoc is behaving consistently with the calls the application is making. When those buffers are unmapped, the `pWrittenRange` passed in is empty: `Begin = End = 0` so no bytes are recorded. That commit will display this explicitly instead of dropping the calls.

From the [docs for `ID3D12Resource::Unmap`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-unmap):

> `pWrittenRange`
> 
> A pointer to a D3D12_RANGE structure that describes the range of memory to unmap.
> 
> This indicates the region the CPU might have modified, and the coordinates are subresource-relative. A null pointer indicates the entire subresource might have been modified by the CPU. It is valid to specify the CPU didn't write any data by passing a range where End is less than or equal to Begin.
> 
> This parameter is only used by tooling, and not for correctness of the actual unmap operation.

So while this is valid (but strange) for an actual driver and the writes will still happen, tooling like RenderDoc that uses this parameter expects it to be a bound on the modified range, and it's an important optimisation for applications that use it correctly since it can significantly reduce the overhead of maps of large resources.

If you can't determine the written range you can pass `NULL` which indicates the whole resource is written.

**Comment by kvark** [comment]
Hmm, this is interesting.

Is my program correct? So far both the spec text and the lack of validation warnings imply that it's correct. Do you consider this UB anywhere? Notably, PIX captures and replays just fine.

Is RenderDoc expected to capture and replay correct programs properly? My expectation is YES. So in this case, it fails to do its job.

**Comment by baldurk** [comment]
I explained the problem in my comment above. D3D12 doesn't really have a solid spec and the behaviour of this function is particularly unhelpful, but it's quite clear. When unmapping you provide a range that has been modified that is explicitly noted as being for tools to use to determine what has been modified, and in this case your application is saying that no data has been modified which RenderDoc respects.

**Comment by kvark** [comment]
I guess my reading of this part of the spec
> not for correctness of the actual unmap operation

I read it as - the parameter doesn't affect the behavior of the program. I suppose your reading is something like "the parameter affects the behavior but doesn't make it invalid".

There is an indirect sign that my reading is correct: the native tooling for DX12 is PIX, and pix is happy to ignore this rectangle.

**Comment by baldurk** [comment]
If you take that reading then it's all reduced to absurdity because that means the parameter must be ignored in all cases and never means anything. I suspect that it's phrased like that because in practice for drivers there's no actual work being done on unmap (I don't believe D3D12 ever has explicit cache flushes, memory is made visible either way) so except on WARP it's likely impossible to enforce a range and impossible to validate.

Certainly it's an error-prone part of the spec, it should either have been made completely invalid (tooling or not) or removed entirely. Making things only applicable for tools or other rare circumstances tends to lead to problems in practice, because unless care is taken it's easy to rely on behaviour that works by coincidence.

I can't comment on how PIX works since I have nothing to do with that program. As with truly undefined behaviour, something that's "undefined behaviour in tools" means it might work by coincidence in one tool or break in another, or work today in one tool and break tomorrow.

**Comment by kvark** [comment]
That sounds reasonable. Yet, it would be great to have *some* indication from RenderDoc that things may capture poorly.
Perhaps, if RD sees Map/Unmap with a range (as opposed to NULL), it can add a warning to the log saying that the behavior of the program may be different on replay because of that, if the writes where done outside of the ranges (which I don't expect RD to detect).

**Comment by baldurk** [comment]
As I mentioned already in the first comment, the commit which closed this issue now shows those maps explicitly and shows that the range is empty (and so that 0 bytes were written).

**Comment by kvark** [comment]
That's great, I missed the "That commit will display this explicitly instead of dropping the calls" part of the message. Thank you!
