### ISSUE TITLE
Timeline GUI does not draw passes

### ISSUE THREAD

**Issue by TheJackiMonster** [baldurk/renderdoc#2327]
## Description

The timeline does not show the passes anymore. The UI looks incomplete now.

![image](https://user-images.githubusercontent.com/13867397/127478519-12f1e374-e681-410a-a3d8-78c311b7c28c.png)

## Steps to reproduce

I encountered this issue when I updated from v1.14 to v1.15. So I assume there have been some changes on the GUI which now prevent the separate passes from being drawn. The accesses of buffers, images and others will still get visualized and changing the debug position inside of the timeline still works as well. So it should only be a visual bug.

Edit: The scenes to encounter this issue contain a lot of drawcalls inside of a renderpass. I could not encounter this issue in a project which only rendered a single triangle (all passes were visualized correctly there). But when I used projects which rendered the Sponza scene, the issue occured.

- Capture of "first_scene" project (rendering Sponza with basic frustum culling): [link](https://drive.google.com/file/d/1MXmF03dB6sLbrRVcpd78SKj3XOqSLKh3/view?usp=sharing)
- Capture of "voxelization" project (rendering Sponza with multiple graphics effects - origin of the screenshot above): [link](https://drive.google.com/file/d/1FHzxHlsbkxht_RZjJuJVY_CEd-B-vQZC/view?usp=sharing)

## Environment

* RenderDoc version: v1.15
* Operating System: Archlinux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Under the section "Steps to reproduce" you need to actually provide steps to reproduce the problem as requested, ideally sharing for example a capture or the program in question so I can reproduce it directly or if that's not possible giving as much information as possible about your program so that I can build a reproducible test case. Providing a second part of the problem description without providing reproduction steps makes it significantly harder to investigate the problem.

**Comment by TheJackiMonster** [comment]
Well, I can't upload the .rdc file because Github does not allow the extension and when I try to upload it as .zip archive, I get following error:
![image](https://user-images.githubusercontent.com/13867397/127481016-5f1a0ac9-aef0-4761-a8bd-034fea4a5403.png)
^^'

**Comment by TheJackiMonster** [comment]
But otherwise I could figure out that it actually depends on the project. Other smaller projects seem to work fine.

**Comment by baldurk** [comment]
You can upload the .rdc to a free file sharing service like google drive or dropbox etc, and either paste the link here or send it in an email to me if you want to keep it private. Github attachments are generally only for images, videos, text documens, etc.

It being project specific is what I suspected as the timeline bar works fine for me, that's why reproduction steps are important to ensure I can actually look into the bug :smile:.

**Comment by TheJackiMonster** [comment]
I have linked two captures now which cause the issue for me. Hope this helps. ^^

**Comment by baldurk** [comment]
This only happened for the auto-generated fake marker regions, which is why I couldn't reproduce it. That commit should fix the problem.

I strongly recommend you provide your own marker regions and don't rely on the automatic ones, as you will be able to provide much better context and organisation for your program.
