### ISSUE TITLE
Weird black stripes in final render view

### ISSUE THREAD

**Issue by BenLubar** [baldurk/renderdoc#2328]
## Description

I've uploaded the capture file to https://renderdoc.org/bugreporter/report/RRF8KXbxuFFxi because I couldn't get GitHub to accept it.

The backbuffer view in RenderDoc shows weird black stripes:

![backbuffer](https://user-images.githubusercontent.com/4257305/127581699-43e1825b-343f-4ced-b09d-e8832c3d4831.png)

## Steps to reproduce

Capture is above. Alternatively, if you want to run the application to capture it directly:

https://git.lubar.me/ben/spy-cards/src/commit/00c2ac17855f361f9deb61850b0362221ea48c6d

```
go build
./spy-cards -path /bugtables.html
```

## Environment

* RenderDoc version: v1.15 (built from a4906060) (Qt version 5.15.2)
* Operating System: Windows 10
* Graphics API: OpenGL ES (I think it's ES 2.0)
* GPU: NVIDIA GeForce RTX 2060
* Driver: (GeForce Experience seems to be broken right now, but the version number Device Manager shows is 30.0.14.7141)

**Comment by baldurk** [comment]
This seems like it is an application issue with low precision. The depth sampler in the final draw looks like it's being sampled at low precision, and since the depth range is extremely crushed (0.98 - 1.0 or thereabouts) this leads to quantisation in the depth being compared for the SSAO kernel, leading to some bands where they all pass and some where all the SSAO taps fail (leading to a heavy black stripe).

Visualising the depth being returned in the first tap with the noise disabled:

![image](https://user-images.githubusercontent.com/661798/127866600-2f5c6c9c-5066-4218-b622-54b926fc10c1.png)

and if I change the depth declaration to `uniform highp sampler2D depth[2];` :

![image](https://user-images.githubusercontent.com/661798/127866656-8d4f6758-26d8-4e53-9756-4a20ac1dfcea.png)

It might be preferable to fix your depth range to use more of 0.0-1.0 around your scene, but that's up to you.

I tried to build the application to see if I could see obviously why this didn't show up when running the program itself but I couldn't - I got some compile errors about missing dependencies. My best guess is that this is some difference between ANGLE (the capture seems to be made on ANGLE) and the native GLES support in the nvidia driver that's used on replay, since these precision hints are implementation defined and only provide a lower bound, not an upper bound.

For what it's worth I don't recommend using GLES on desktop as the support can be quite dodgy and proper GL is available.
