### ISSUE TITLE
Capturing counters on render passes

### ISSUE THREAD

**Issue by djdeath** [baldurk/renderdoc#2335]
## Capturing counters on render passes

I'm interested in capturing counters on render passes begin/end rather than what seems to be per draw call at the moment. 
For things like computation units occupancy, it's more interesting to have that across the renderpass.

I don't mind doing the work, but I would prefer some kind of direction.

Right now I'm thinking to extend the FetchCounters() method to add a selector :
  * renderpass (from begin to end)
  * drawcall/dispatch/copy-operations/resolve-operations
  * entire command list

Would that be an acceptable change? Should there be other selection items?

Thanks for the feedback.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
