### ISSUE TITLE
Vulkan: Random Crashes

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#234]
Hi,

encounter random crashes on startup of vulkan programs (with both 32bit and 64bit executable),even after the fix #230 is applied, not sure what the cause this. It happens even with the vulkan sdk samples tri and cube (with both 1.0.3 and 1.0.5 sdk).

Even after changing the default calling convention to __stdcall the random crashes do persist.

Compiled with vc 2015 Update 2 and vc 2013.

Also when the cube demo of the sdk sometimes run, then with --validate a lot of errors pop up about mismatching values and some semaphore usage errors.

**Comment by TiemoJung** [comment]
As a additional info, the vulkan-1.dll is a freshly compiled one with the latest github src.

**Comment by baldurk** [comment]
Can you give any details about your environment or more information about what the crashes actually are? Have you attached in the debugger to see what the crash is? I've not seen anything like this locally so I'd need more information to either reproduce or estimate how to fix.

**Comment by TiemoJung** [comment]
When the layer VK_LAYER_LUNARG_standard_validation is used then it crashes inside `vkGetPhysicalDeviceSurfaceSupportKHR` of the object tracker. With attached debuger it shows that the dispatch table lookup fails and it tries to read from a null pointer and crashes. This happens only if the layer of renderdoc is active, without it it does not crash.

**Comment by baldurk** [comment]
What operating system and vulkan driver are you using?

**Comment by TiemoJung** [comment]
Windows 8.1
Nvidia 364.72

**Comment by baldurk** [comment]
I've had one other report from someone on nvidia with kind of similar symptoms. It could be the same and they weren't using the validation layers. After some debugging, it turned out that some nvidia driver thread was overwriting some of the information inside the renderdoc wrapped object, which ended up causing a crash under a sort of race condition.

Unfortunately I can't reproduce it so I'm not able to prove anything or investigate further. This might be because I'm on windows 7, I don't know. I'll ask the other user to see whether they got a response from nvidia about what's happening.

In the meantime, are you able to test on another IHV's hardware to test if the crash still happens?

**Comment by TiemoJung** [comment]
Sorry, i can't test it on a different implementation, only nvidia available :(

**Comment by baldurk** [comment]
OK. It seems like it's the same problem, which went away on AMD for the other user I mentioned. I will leave this bug open for now but I can't do anything more unless I have some information or a way to reproduce. I don't get it on my nvidia machine, possibly since it is Win7.

If I hear back from nvidia I will update.

**Comment by TiemoJung** [comment]
The really strange thing is, it worked just fine until some time ago and then suddenly starting to crash all over the place and only if renderdoc active.
Tried to roll back to older drivers but no luck.

**Comment by baldurk** [comment]
Some other things to try, just in case it shows anything interesting: does it work if you only enable renderdoc, no validation layers? What if you roll back to an older renderdoc build (in case something has been subtly broken since 0.27)?

**Comment by TiemoJung** [comment]
I crashes with and without enabled debug layers.
Simple tests like `renderdoccmd C:\VulkanSDK\1.0.5.0\Bin\cube.exe`, crash, don't start or just work at random.
I will try a older version.

**Comment by TiemoJung** [comment]
Now i am really confused...
i rolled back to 144a91ea9797674db8f4d2ecd5c5eeeaf574979e where i am sure that it worked fine.
And its crashing too, so something is very odd here.
I just reinstalled the vulkan sdk (1.0.5.0) and the restributable, no change.

**Comment by baldurk** [comment]
I was able to reproduce what I think is this bug on one machine of mine while investigating #236. I think I've found what the problem is, but I caught it at 2am last night so I will need to try to fix it tonight, but I'll keep this bug updated.

**Comment by TiemoJung** [comment]
Did also more testing, rolling back to a older driver and rolling back to the sdk 1.3.1 fixed it.
As soon as i update to the 1.5.1 sdk it starts crashing again so i would assume its the loaders fault?

**Comment by baldurk** [comment]
I think that commit will fix it. Let me know what you find.

The problem seems to be that the loader now since [this commit](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/876604386e5a6b9e5177716fa0a57ff669859683) will free() and then malloc() the physical devices every time they are enumerated. This means the pointers are different each time. RenderDoc was wrapping the pointers once since I need to serialise the initialisation data, and then returning the same wrapped objects each time.

The problem is the second time, I return a valid wrapped object but the unwrapped pointer is now pointing at free'd memory. If you're lucky then nothing overwrites that memory and it still works, but if you're unlucky then the dispatch table is corrupted when some other heap allocation jumps into that spot.

Instead now I just re-wrap the returned physical devices every time, modifying my wrapped object.

**Comment by TiemoJung** [comment]
Hi,

it is working fine now, tanks!
