### ISSUE TITLE
RenderDoc Can't create a capture for OpenGL 4.5-4.6 Core Profile

### ISSUE THREAD

**Issue by Andreyogld3d** [baldurk/renderdoc#2340]
## Description

RenderDoc Can't create a capture for OpenGL 4.5-6 Core Profile

## Steps to reproduce

1. Run RenderDoc
2. Launch Application: Light Indexed Deferred Shading_mod/Source/DeferredLighting/DeferredLighting2019.exe

## Environment

* RenderDoc version: 1.15 and nightly build 87e08feb7c94588cb1a4f37b5b57b66dad3a4b25
* Operating System: Windows 10 X64
* Graphics API: OpenGL

AMD RX 560 (Driver 27.20.22023.1004) was used for RenderDoc 1.15 and and nightly build 87e08feb7c94588cb1a4f37b5b57b66dad3a4b25
Intel UHD 630 (Driver: 30.0.100.9684) was used for for RenderDoc 1.15 

[Application's link](https://www.dropbox.com/s/k32baggviktr5s6/Light%20Indexed%20Deferred%20Shading_mod.7z?dl=0)

**Comment by baldurk** [comment]
Your reproduction steps are unclear, I'm not sure if it's crashing for you or if you're unable to capture (I'm not sure exactly what that means). Trying to run it I have quite a few problems with the application.

For me the built application doesn't run at all on its own. Compiling from source, it seems to be because the `nPFormats` variable passed to `wglChoosePixelFormatARB` is uninitialised, and comes back with with a garbage value (I don't know if that's expected or not for the function off the top of my head).

Fixing that it then runs OK on its own but crashes when run from RenderDoc. At first that seemed due to some heap corruption, but when looking closer I see the program makes use of the legacy extension GL_ARB_shader_objects without checking for it, as RenderDoc does not support that extension.

RenderDoc doesn't support compatibility profile OpenGL or deprecated extensions like GL_ARB_shader_objects. If you have a program that uses core profile GL that you have problems with please open an issue, but this seems to be a crash due to the application invoking undefined behaviour.

**Comment by Andreyogld3d** [comment]
Hi @baldurk 
> but when looking closer I see the program makes use of the legacy extension GL_ARB_shader_objects without checking for it, as RenderDoc does not support that extension.

Yes, I have replaced ARB/EXT to core function. It has been fixed problem! 
![image](https://user-images.githubusercontent.com/8597425/128923845-a302d0a0-c839-44ab-884a-35c0bd3b2f1b.png)

Thank you!
Any way, I have not seen error messge in log about legacy extensions. May be should extend dyagnostic information

**Comment by baldurk** [comment]
There's not supposed to be an error message from RenderDoc. Your application is responsible for ensuring that it checks for extensions to be available before using them. If you use an extension that isn't available then that's undefined behaviour and may lead to crashes or other problems.
