### ISSUE TITLE
No more Inject into process 

### ISSUE THREAD

**Issue by AmiranB** [baldurk/renderdoc#2350]
## Description

 
When updating from V. 1.14 to V 1.15 in the File drop-down menu changed

There is no more inject into process command 
## Steps to reproduce
I have deleted and installed, the renderdoc, installed V. 1.14 again but still no inject command 

![Inject into process gone ](https://user-images.githubusercontent.com/50584561/130976074-3a0101fa-cd0b-44c8-8e54-ed5b9aecedc8.jpg)

## Environment

* RenderDoc version: 1.14, 1.15
* Operating System: Win11
* Graphics API: Dont know how to learn which API is used 
![System](https://user-images.githubusercontent.com/50584561/130976180-b424f997-a051-45c2-b793-c7a653410cba.jpg)

**Comment by baldurk** [comment]
The inject into process option was put behind an opt-in option because it was causing confusion to new users who were trying to use it for no good reason and getting confused when it didn't work properly or broke.

Unless you are _absolutely sure_ that you know what you are doing and what the risks and trade-offs involved are, you should not inject into running processes. Instead in almost every case you should launch your application from RenderDoc as normal and recommended, and that will be the most reliable and stable workflow.

**Comment by AmiranB** [comment]
> The inject into process option was put behind an opt-in option because it was causing confusion to new users who were trying to use it for no good reason and getting confused when it didn't work properly or broke.
> 
> Unless you are _absolutely sure_ that you know what you are doing and what the risks and trade-offs involved are, you should not inject into running processes. Instead in almost every case you should launch your application from RenderDoc as normal and recommended, and that will be the most reliable and stable workflow.

I did not expect such a swift reply! 
Tried launching from the app: API NO

![Treid launching google map from the app says API  NONE ](https://user-images.githubusercontent.com/50584561/130980081-737c56d5-2df1-4c98-96b3-cb64bc8bac16.jpg)

Many thanks

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
