### ISSUE TITLE
qrenderdoc: cannot proceed because VCRUNTIME140_1.dll was not found.

### ISSUE THREAD

**Issue by jpaver** [baldurk/renderdoc#2359]
## Description

Installing and running latest renderdoc does not launch when vcruntime140_1.dll is not on the system.

## Steps to reproduce

- Install RenderDoc 1.15 (28 July 2021) for Win x64 -- either installer or ZIP.
- Run qrenderdoc.exe
- notice vcruntime140_1.dll message box 3 times -- cannot get in.

![image](https://user-images.githubusercontent.com/8569715/132257085-9e64b225-6d6c-42d1-8e68-143a934170f2.png)

## Environment

* RenderDoc version: 1.15 (28 July 2021) for Win x64
* Windows 10 home
* OpenGL

My Windows/System32 folder has just these DLLs:

![image](https://user-images.githubusercontent.com/8569715/132257202-c2f400dd-a320-4a82-b43a-5b033c883e99.png)

Consider statically linking VC libraries into your exe -- or shipping all the DLLs with it.

EDIT: I was previously running an earlier version of renderdoc just fine -- hit this issue only when trying to get on the latest version. Thanks!

**Comment by baldurk** [comment]
The zip builds does require you to have the appropriate VC runtimes set up, but the installer should be shipping the proper redistributable and installing it as needed. Can you please check to see which VC runtimes you have installed?

If you completely uninstall RenderDoc and reinstall v1.15 from fresh, does that work correctly?

**Comment by jpaver** [comment]
Hi Baldur, Unfortunately not - hitting the same problem.

![image](https://user-images.githubusercontent.com/8569715/132633169-e7182d36-f4dc-4adc-be22-805dfd57c821.png)
![image](https://user-images.githubusercontent.com/8569715/132633368-df1466a1-d91c-4270-a0c3-40a8f258e6dc.png)

I had to go all the way back to 1.11 to get a build that works. 1.12 is the earliest build that does not.

**Comment by baldurk** [comment]
That makes sense as in v1.12 I updated the version of Qt, and it's only Qt that needs the VS2019 runtime.

I also asked you to please check which VC runtimes you have installed, can you do that and let me know which ones you have installed?

**Comment by jpaver** [comment]
Hi sorry, I forgot about that part. These are the only ones I have installed...
![image](https://user-images.githubusercontent.com/8569715/132728664-460865b4-af0d-40a0-85cb-c90037786f04.png)

**Comment by baldurk** [comment]
OK thanks, so you are missing the 2019 redist that the newer Qt builds require, for some reason that's not getting detected by the installer. The 2017 redist you have covers the RenderDoc build itself which is presumably why older versions of RenderDoc work.

Can you export the registry key at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio` and share that? either just pasting the contents or into a pastebin somewhere.

**Comment by jpaver** [comment]
Thanks Baldur. Sorry this took so long:
[vs.reg.zip](https://github.com/baldurk/renderdoc/files/7182635/vs.reg.zip)

**Comment by baldurk** [comment]
OK that's annoying, it looks like the registry key I was using to determine if the redist is available _is_ present, but the version number is too low. Looking on google there's not an easy key to look for and instead you're supposed to compare against the major/minor version. Which of course is incredibly obtuse to do in an installer.

Can you test [this installer](https://renderdoc.org/installer_test_2359.msi)? it's built from latest code as of the above commit. If that works, please uninstall it and then re-install v1.15. Because of how the redistributables work it should stay installed even when you uninstall the temporary RenderDoc build, so v1.15 will work. And the above fix will apply to the real installers from v1.16 onwards.

**Comment by jpaver** [comment]
Hi Baldur, unfortunately that installer didn't work either.

**Comment by baldurk** [comment]
Can you uninstall RenderDoc completely and run that installer with `msiexec /i "installer_test_2359.msi" /L*V "installlog.txt"` and upload that log so I can see what's going on?

**Comment by jpaver** [comment]
Absolutely, log attached: 
[installlog.zip](https://github.com/baldurk/renderdoc/files/7200445/installlog.zip)

**Comment by baldurk** [comment]
That log shows that the installer is requesting to install the vc redist. If it's still not working I don't think this is a RenderDoc bug but I think it's a bug with the vc redist, or maybe the msm merge modules.

One curious note - the log shows that you have the 2019 runtime installed for 32-bit (you can double check in the registry by looking at `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\X86` but the installer is reading a version of 14.20, which is the oldest 2019 runtime available AFAIK). Maybe the bug is that the vc redist installer is falsely detecting the 32-bit version as being installed and so refusing to install the 64-bit version when RenderDoc needs.

Either way I don't think there's anything more I can do from my side on this, and I think trying to file a bug on this with Microsoft is pointless as it will most likely get ignored.

I'd suggest that instead you manually install the latest x64 and x86 VS2019 runtimes [from MS](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) and then RenderDoc will run fine.
