### ISSUE TITLE
Please consider adding support for VK_EXT_load_store_op_none

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2363]
## Description

`VK_EXT_load_store_op_none` adds two ops, `VK_ATTACHMENT_LOAD_OP_NONE_EXT` and `VK_ATTACHMENT_STORE_OP_NONE_EXT`. The latter is the same op as `VK_ATTACHMENT_STORE_OP_NONE_QCOM` (and will find its way to core Vulkan eventually). Currently, if an application uses these ops in a render pass, RenderDoc instead replays with `LOAD_OP_LOAD` and `STORE_OP_STORE`.

This is not only less efficient, but can lead to VVL's syncval generating errors where there shouldn't be. For example, if a render pass uses a read-only depth stencil attachment, it can use `LOAD_OP_LOAD` and `STORE_OP_NONE`. A following image barrier would select its src access based on the fact that the image was used read-only. There is no synchronization hazard with that. However, when RenderDoc turns the store op to `STORE_OP_STORE`, there's now a WaW synchronization hazard as reported by syncval.

## Environment

* RenderDoc version: 1.13 (although looking at the code, the current top-of-tree (adb2b659) doesn't handle these ops either).
* Operating System: Linux (but that's irrelevant)
* Graphics API: Vulkan

FYI, the latest Nvidia beta driver release on Linux (470.62.02) includes this extension. SwiftShader also has an implementation.

**Comment by baldurk** [comment]
This extension was only released a few days ago which is why you don't see any support in any stable version, certainly not 1.13 as that's many months old :smile:. Typically there is a gap between release of an extension publicly and it being implemented, depending on its complexity and demand.

Note that a valid application cannot be using these ops with RenderDoc, because the application must check for the extension and enable it, and when RenderDoc is enabled the extension will not be reported as supported. So I'm not quite sure what you mean about validation hazards or RenderDoc replaying different ops, since it's impossible to use these ops until the extension is supported.

**Comment by ShabbyX** [comment]
> This extension was only released a few days ago which is why you don't see any support in any stable version, certainly not 1.13 as that's many months old :smile: 

Hah, that's courtesy of having known about the extension for a few months in advance!

> when RenderDoc is enabled the extension will not be reported as supported

You're right, I verified that that is the case. I didn't know RenderDoc did that.

> So I'm not quite sure what you mean about validation hazards or RenderDoc replaying different ops

RenderDoc is replaying with correct ops (based on above info that the unknown extension is not exposed). The application itself is generating hazards without this extension, which is expected. So nothing for RenderDoc to worry about regarding that.

**Comment by baldurk** [comment]
That commit should add support for VK_EXT_load_store_op_none (as well as VK_EXT_color_write_enable since that's the most convenient way to realistically test the extension, rather than using VK_EXT_extended_dynamic_state for a depth attachment).

I've tested it with a simple trivial demo, but let me know if you run into any issues on real programs.

**Comment by ShabbyX** [comment]
Thanks. FYI, storeOp=NONE is also useful for read-only depth-stencil attachments. I'll be sure to let you know if I spot any issues.
