### ISSUE TITLE
Insecure XML Parser in use

### ISSUE THREAD

**Issue by bt-nia** [baldurk/renderdoc#2365]
https://github.com/baldurk/renderdoc/blob/adb2b65951dd73e6f12ed38c6447e4057ac04a0e/renderdoc/driver/vulkan/gen_dispatch_table.py#L22
https://github.com/baldurk/renderdoc/blob/adb2b65951dd73e6f12ed38c6447e4057ac04a0e/renderdoc/driver/shaders/spirv/gen_spirv_code.py#L27

Instead of using `xml.etree.ElementTree`, which suffers from XXE issues and can thereby be exploited for data exfiltration, denial of service and other attacks, the `defusedxml` package should be used as a replacement. I'm no expert with this code base, but `defusedxml` acts as a drop-in replacement in many cases and especially here, it seems to be a viable alternative. 

More details about `defusedxml` and its `ElementTree`:
https://pypi.org/project/defusedxml/#id14

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
