### ISSUE TITLE
Vulkan performance issue seems incorrect: "Unmapped memory overlaps tiled-only memory region"

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2368]
## Description

I'm following Vulkan Memory Allocator's best practices by creating CPU-only buffers (VMA_MEMORY_USAGE_CPU_ONLY), then copying them to GPU-only images/buffers (VMA_MEMORY_USAGE_GPU_ONLY). I also create these GPU-only resources with the VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT flag. Data gets transferred from CPU to GPU via a command buffer.

I'd expect that following these steps would not cause the performance warning to be raised in Renderdoc, however this doesn't appear to be the case.

I've gone through all of my code, confirming that the GPU-only buffers are never mapped on the CPU, so I'm out of ideas as to how to address this particular issue.

I've also gone through Vulkan Memory Allocator itself and I've confirmed that it never attempts to map the GPU resources.

## Steps to reproduce

Capture can be accessed here:

https://file.io/d707hw6cxy8G

## Environment

* RenderDoc version: 1.15
* Operating System: Windows 10 Pro 21H1
* Graphics API: Vulkan 1.1
* GPU: Intel Iris Plus Graphics 655

**Comment by baldurk** [comment]
In the capture you provided there is only one memory allocation (Memory 166). Since it is the only memory allocation all of the images (which are all tiled) in the capture are bound to it, and it is also mapped/unmapped in its entirety several times in the frame.

The warning is functioning correctly and is telling you about the problems with exactly this situation, since RenderDoc can no longer copy the entire mapped region of memory in one go and it has to loop over and copy each region which doesn't overlap with tiled resources. There's nothing incorrect about the warning, or about your vulkan code, all it's telling you is that you're doing something valid which will penalise replay performance in RenderDoc. It's up to you if you want to change your code for that reason or not.
