### ISSUE TITLE
andoid textureview can not capture frame

### ISSUE THREAD

**Issue by ab503044120** [baldurk/renderdoc#2369]
andoid textureview can not capture frame

![image](https://user-images.githubusercontent.com/5219122/133719978-9d4d4457-0cce-4ff3-8e5b-2ed505ff0dd1.png)
get thread dump 
![image](https://user-images.githubusercontent.com/5219122/133736883-a2c3bd7b-f31b-4ae9-9ee2-ac14fe1a686e.png)

## Environment

* RenderDoc version: 1.15
* Operating System: android

* Graphics API: opengles 3.0
* model xiaomi note3   , goolge pixel2 

follow the code
[GLTextureView.zip](https://github.com/baldurk/renderdoc/files/7182412/GLTextureView.zip)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
