### ISSUE TITLE
Can I use log file to represent the workload of application?

### ISSUE THREAD

**Issue by vinjn** [baldurk/renderdoc#237]
If not, does renderdoc introduce API overhead and what kinds of overhead?
Is overhead introduced during capturing or replaying?

Thanks

**Comment by baldurk** [comment]
I'm not entirely clear on what you're asking. Are you wanting to know how much overhead renderdoc introduces into an application while the layer is active?

Or are you wanting to know about what renderdoc does on replay and how that differs from what the application did on capture?

What definition of "representative" are you using exactly?

**Comment by vinjn** [comment]
If the original app have 100 API calls, will the log file also have 100 API calls?

**Comment by vinjn** [comment]
Representative means the GPU workload of log file is pretty close to the frame from original app.

Thanks

**Comment by baldurk** [comment]
I don't think there can be guarantees of either.

The application might make 100 API calls, but renderdoc only saves a single frame, not the whole dump of the application's calls from startup. So only the API calls that are needed for a frame are saved - anything that happens between two Present() calls and the command buffer recordings.

Likewise on replay renderdoc needs to do a lot of additional bookkeeping work to actually sustain the replay, including restoring memory and image contents to what they were at the start of the frame each time it replays, making additional calls to support partial replay of command buffers, as well of course as all of the work to actually perform the analysis - render images, fetch mesh contents, all sorts of things. The replayed work should be close to identical, but there's lots of other work needed too.

I'm still not sure what actual problem you're having or what goal you're trying to accomplish. Whether the API calls to the driver are identical to the application doesn't matter, since it's all an implementation detail behind the scenes of the UI. What I do is make sure that the semantic meaning of the calls are preserved, so that wherever possible renderdoc doesn't change what happens in the frame from what the application did. But to perform the replay it would be pointless to try and stick as close to the application's API calls as possible since there is zero benefit.

Can you back up from this narrow focus and explain what you're trying to do at a higher level?

**Comment by vinjn** [comment]
Thanks baldurk,

In short, I want to use `renderdoc` as a profiler in stead of a debugger. So I need to preserve the API calls as close to original app as possible. Uour recent answer has almost cleared my concerns.

What I want to keep
- restoring memory and image contents to what they were at the start of the frame each time it replays, I will keep it and make it optional.

What I don't need
- making additional calls to support partial replay of command buffers, since the profiling will be frame-based.
- render images
- fetch mesh contents
- all sorts of things

**Comment by baldurk** [comment]
OK, I understand now. In this case, I think this will never be practical since has too different needs to what renderdoc tries to do. RenderDoc is currently a debugger and does not have the infrastructure or design considerations needed to be a useful profiler. I'm hopeful that in future it could become a useful **GPU** profiler - but again in that case the actual API calls do not matter, only the GPU work that is profiled. However it will never be useful as a profiler of API calls since it makes many changes there and is far away from a faithful reproduction of application calls with minimal overhead. E.g. it is impossible to "make optional" the restoring of memory/image contents since then the replay will be completely wrong.

I would suggest looking at vktrace/vkreplay, which is intended to be what you want - a literal and faithful reproduction of API calls without interference or change.

**Comment by vinjn** [comment]
vktrace/vkreplay has been evaluated.
However it doesn't work on non-trivial apps :(
Anyway, thanks for the information.
