### ISSUE TITLE
andoid textureview can not capture frame

### ISSUE THREAD

**Issue by ab503044120** [baldurk/renderdoc#2370]
## Description
andoid textureview can not capture frame
I use TextureView to build opengles Environment, but renderdoc can't capture frame 

follow the code
[GLTextureView.zip](https://github.com/baldurk/renderdoc/files/7182412/GLTextureView.zip)

![image](https://user-images.githubusercontent.com/5219122/133719978-9d4d4457-0cce-4ff3-8e5b-2ed505ff0dd1.png)
get thread dump 
![image](https://user-images.githubusercontent.com/5219122/133736883-a2c3bd7b-f31b-4ae9-9ee2-ac14fe1a686e.png)

## Environment

* RenderDoc version: 1.15
* Operating System: android
* Graphics API: opengles 3.0
* model xiaomi note3   , goolge pixel2

**Comment by baldurk** [comment]
Your program is broken - it stops calling present or GL commands which is why RenderDoc says that it's not presenting. Modifying the source to change the clear colour to random colours shows that it's not rendering continuously. It also seems to use unsupported OpenGL extensions without checking if they are available, so I recommend that you also fix that as otherwise it may cause further problems.

You need to fix your code and then RenderDoc should work. Try running a known-good sample or a built apk from e.g. Unity or Unreal to see that it is working as expected. Note that on xiaomi devices they are broken out of the box, so you need to change some settings to make them debuggable.

**Comment by ab503044120** [comment]
> Your program is broken - it stops calling present or GL commands which is why RenderDoc says that it's not presenting. Modifying the source to change the clear colour to random colours shows that it's not rendering continuously. It also seems to use unsupported OpenGL extensions without checking if they are available, so I recommend that you also fix that as otherwise it may cause further problems.
> 
> You need to fix your code and then RenderDoc should work. Try running a known-good sample or a built apk from e.g. Unity or Unreal to see that it is working as expected. Note that on xiaomi devices they are broken out of the box, so you need to change some settings to make them debuggable.

the GLTextureView  copy from [gpuimage](https://github.com/cats-oss/android-gpuimage) and my program can display well, 
but i try [gpuimage ](https://github.com/cats-oss/android-gpuimage)program(use textureview model) and can't correct capture frame 
follow is my program apk
[app-debug.zip](https://github.com/baldurk/renderdoc/files/7189051/app-debug.zip)

follow is gpuimage apk ,click gallery button and capture frame by use renderdoc  ,u can find the bug
[gpuimage apk](gpuimage.zip](https://github.com/baldurk/renderdoc/files/7189042/gpuimage.zip)

**Comment by baldurk** [comment]
This other program you've linked also uses an unsupported OpenGL extension without checking for it, and it also presents very inconsistently. If I capture while it is presenting it works correctly, so this still doesn't appear to be a RenderDoc bug.

If you need to capture a program that doesn't present interactively you may find it easier to use the [in-application API](https://renderdoc.org/docs/in_application_api.html) as RenderDoc is designed for programs that render continuously and so uses presents as capture boundaries. However you should still make sure your program uses valid OpenGL and doesn't try to use unsupported extensions.
