### ISSUE TITLE
Vulkan: All buffers show up as zero although the application runs correctly

### ISSUE THREAD

**Issue by gardell** [baldurk/renderdoc#2372]
## Description

All buffer content is shown as zero even though it's not (the application runs as normal).

## Steps to reproduce

Check out the `wgpu` fork at https://github.com/gardell/wgpu with the branch `renderdoc-zero-buffers` that contains the commit https://github.com/gardell/wgpu/commit/c65681bb33ccd4726d5f173a838edc49148b700e that causes the issue.

```sh
cargo test --example hello-compute tests::test_compute_1
```
runs the problem that has been patched by the above commit to cause the issue.

Running the binary produced by `cargo test` with RenderDoc (the binary appears in `target/debug/examples/hello_compute-*`) will show the problem where all buffers show up as all zeros.

Running the binary without the above commit applied will not cause the problem and the values of the buffers will be correct.

## Environment

* RenderDoc version: 1.15
* Operating System: Ubuntu 20.04.3
* Graphics API: Vulkan

There is an issue about this at `wgpu` as well, https://github.com/gfx-rs/wgpu/issues/1902

**Comment by baldurk** [comment]
The problem here was that RenderDoc had an optimisation, such that if an application flushes mapped memory it assumes the application will flush every change it makes and it turns off the automatic (and slow) detection of mapped memory writes to coherent memory. In your case your application flushes mapped memory behind a buffer *then* writes data into it. As a result of the optimisation RenderDoc then doesn't detect the write properly.

I've turned off the optimisation and it should work correctly now. Note that you should consider turning off the flushes in your code as it doesn't do anything on drivers with coherent memory. It might also be worth checking to make sure it works on drivers with non-coherent memory if you want to support that, as in that case if you followed the same flushing pattern it would not be spec-correct.
