### ISSUE TITLE
Buffer Contents format decoding missing padding for std430 mat4x3 arrays in Vulkan

### ISSUE THREAD

**Issue by Ralith** [baldurk/renderdoc#2378]
## Description

RenderDoc interprets a storage buffer such as
```glsl
layout(set = 2, binding = 0) readonly restrict buffer Transforms {
    mat4x3 model_to_stage[];
};
```
as
```
struct Transforms_var
{
    float3x4 model_to_stage;
}
```
This is semantically correct, but the actual decoding is using incorrect padding/alignment. GLSL 4.6 section 4.4.5 says:
> The initial state of compilation when generating SPIR-V is as if the following were declared:
> ```
> layout(std140, column_major) uniform;
> layout(std430, column_major) buffer;
> ```
indicating that `Transforms` is laid out according to std430 rules. Those rules, in OpenGL 4.5 section 7.6.2.2, state:
> If the member is a three-component vector with components consuming N basic machine units, the base alignment is 4N. [...] If the member is an array of scalars or vectors, the base alignment and array stride are set to match the base alignment of a single array element [...] If the member is a column-major matrix with C columns and R rows, the matrix is stored identically to an array of C column vectors with R components each

In other words, the column-major `mat4x3` elements in this array are each laid out as an array of 4 `vec3`s, each with a base alignment of 16, i.e. each having a float of padding at the end. RenderDoc seems to instead be treating the data as densely packed.

Manually adjusting the buffer format to a `float4x4`, which trivially has the expected layout, is an effective work-around. The correct data does seem to get loaded in the vertex shader debugger; however, the mesh viewer VS output seems to be corrupt (e.g. all zeroes, despite non-degenerate triangles visible in texture viewer).

## Steps to reproduce

1. Populate a storage buffer with a std430 array of mat4x3
2. Read it from a vertex shader
3. Navigate to Pipeline State -> Vertex Shader, then click the "Go" arrow for the buffer in question
4. Observe mangled data
5. Adjust buffer format to use a `float4x4`, observe correct data.

Can provide a capture if needed.

## Environment

* RenderDoc version: 1.16
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Can you please provide a reproducible test case, as a capture or an executable I can run to capture.

**Comment by Ralith** [comment]
See EID 337 and 338 in [misaligned-matrices.zip](https://github.com/baldurk/renderdoc/files/7272085/misaligned-matrices.zip), for example. Vertex shader descriptor set 2 binding 0, `Transforms_var`.

**Comment by baldurk** [comment]
This was an issue handling the vulkan/GL behaviour of allowing some fixed-sized elements before the repeated array in the buffer. If the last element was a struct it would properly handle all the elements including matrix padding, but if the last element was a plain type (including a matrix like in your example) it wouldn't properly go through the path to declare padding elements. That commit should fix it.

I also ran into driver crashes trying to open the capture for some reason, one of the early terrain draws with many instances seemed to barf part-way through. I tried investigating but couldn't see anything wrong, and since I had to modify the capture to make it compatible with my GPU and you didn't report any issues like that I'm going to chalk it up to gremlins. Let me know if you run into something like that though.

**Comment by Ralith** [comment]
Awesome, thanks!

I haven't had any other issues with captures from this project recently, but I'll keep an eye out. There has been some weird stuff in the past--e.g. SteamVR used to crash when a renderdoc-attached process exited--but that stopped happening a while back, and the captures still worked fine.
