### ISSUE TITLE
dx11 oculus: unpatched dx11 calls inside oculus dll (loaded by application)? crashes in UnwrapResource()

### ISSUE THREAD

**Issue by damianhammondclimax** [baldurk/renderdoc#238]
since > ~oculus sdk 0.7 they've moved the call to create their render targets inside their dll.
application-side, after the dll creates it's texture, the samples CreateRenderTargetView() 
based on the ID3D11Texture2D it created, which fails with a crash inside UnwrapResource().

it looks like somehow the dll used an unpatched dx interface, so the texture creation call wasn't wrapped.

are you aware of any similar issues with texture creation inside dlls, or can you suggest a workaround?

i've also posted on the oculus developer forums to see if they/other developers have a solution.

great product btw

**Comment by baldurk** [comment]
Possibly these textures are being retrieved through a non-wrapped DXGI interface. Might be related to #232 if you're running on win8 or win10. Do you have any log messages about unknown GUIDs? If so please paste them in.

Otherwise I'm not sure how much I can do without more information but I will ask around. I can't repro locally since I don't have any kind of VR thing to use the oculus sdk on.

**Comment by baldurk** [comment]
From what I understand (Thanks to Jamie Hayes on twitter for investigating!) the crucial problem was oculus doing a `QueryInterface()` for IUnknown. With the above change, please try again and see if you have more luck.

**Comment by damianhammondclimax** [comment]
fantastic, yup that's got it :)

huge thanks to yourself and jamie for nailing this and apologies for not getting back to you sooner (was win7 btw).
