### ISSUE TITLE
Mesh viewer vertex selection is rendered in the wrong location

### ISSUE THREAD

**Issue by Firestar99** [baldurk/renderdoc#2385]
See Image below, a cube is rendered with this draw call but when using left-click to select nearest vertex or from the vertex table above, the selected vertex blue box and red triangle is not rendered in the correct spot. (Selection works just fine on the actual object)

![image](https://user-images.githubusercontent.com/31222740/136174537-72f038c7-e580-4af6-a042-7683b02251f4.png)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
