### ISSUE TITLE
not support Python API replay：Error Function glFramebufferTexture2DMultisampleEXT not available on replay

### ISSUE THREAD

**Issue by shaomluo** [baldurk/renderdoc#2391]
not support Python API replay，prompt “Failed to open capture for replay：Current replaying hardware unsupported or incompatible with captured hardware” , It can be opened on the real machine. Is this a known bug? I read the Diagnostic Log prompt：Core 22952 09:52:00 gl_framebuffer_funcs.cpp(623) Error Function glFramebufferTexture2DMultisampleEXT not available on replay.

Looking forward to receiving a reply, thanks

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
