### ISSUE TITLE
RenderDoc Capture a frame Error

### ISSUE THREAD

**Issue by Tokyo2024** [baldurk/renderdoc#2397]
## Environment

* RenderDoc version: RenderDoc1.16
* Operating System: Win10，Android10
* Graphics API: OpenGLES(UE4 packaged game)

       When I capture a frame from a game packaged in UE4, it seems that some DrawCall will be abnormal, can you tell me the reason, thank you !
![本地打开](https://user-images.githubusercontent.com/37432400/138792812-62e87216-1ca9-452e-8c94-6cdfb96c0df8.png)
![暴露问题](https://user-images.githubusercontent.com/37432400/138792837-fb583885-c68f-4e93-8f16-295dff1288e6.png)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
