### ISSUE TITLE
Blue channel pixel content of SNORM texture always shows 0.0

### ISSUE THREAD

**Issue by BigGucciBoss** [baldurk/renderdoc#2398]
While debugging my normal GBuffer (_DXGI_FORMAT_R16G16B16A16_SNORM_), I noticed that when trying to view the contents of a pixel, the blue and alpha channels always come up as 0.0:
![nrm](https://user-images.githubusercontent.com/17811155/138922724-b95c3ad9-8f72-45b4-acc3-d26972fec93d.jpg)

As you can see this can't be correct because the frame visibly has blue pixels, and I explicitly set the alpha channel in my shader output to 1.0f:

``` 
input.normal = normalize(input.normal);
input.tangent = normalize(input.tangent);
float3 binormal = normalize(cross(input.tangent, input.normal));

float3 normal = (normalMap.Sample(SampleType, input.tex).rgb * 2.0) - 1.0f;
float3x3 texSpace = float3x3(input.tangent, binormal, input.normal);
float3 finalNormal = normalize(mul(normal, texSpace));

output.normals = float4(finalNormal.rgb, 1.0f); 
```

The same happens with the UNORM texture format. FLOAT works fine. 

**Steps to reproduce:**

1. Create a normal GBuffer with the SNORM or UNORM format and output the normals as shown above

or

2. Download the capture (The normal buffer is RT0 inside the 'GBuffer Pass' event)
[rd.zip](https://github.com/baldurk/renderdoc/files/7419941/rd.zip)

Windows 10, DirectX 11, RenderDoc v1.16

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
