### ISSUE TITLE
Null pointer crash after failed HRESULT returned by DX12

### ISSUE THREAD

**Issue by BBI-JohnwillKeating** [baldurk/renderdoc#2404]
## Description

My Unreal Engine game "Raven.exe" crashes when I take a Renderdoc capture but it does not crash otherwise.  It's not clear if this is a RenderDoc bug so feel free to close this issue if crashing is the expected behavior.
What happens is that DX12 returns the error 0x887A0006: DXGI_ERROR_DEVICE_HUNG (See the attached log file of the Raven.exe process), and then Renderdoc dereferences an internal null pointer.  What I expect to happen is for Renderdoc to propagate the error to the application instead of crashing internally inside Renderdoc.

## Steps to reproduce

My game is very large and under NDA so I can't upload it.
I've attached a log file and some debugger screenshots which show how the game crashes inside Renderdoc:
"Raven_Process_Log.txt" shows the output of the Raven.exe process launched by Renderdoc.
"First_Exception.png" shows the DXGI_ERROR_DEVICE_HUNG exception.
"Crash.png" shows where Renderdoc dereferences a null pointer.

## Environment

* RenderDoc version: v1.16 (compiled on my local machine at git tag v1.16)
* Operating System: Windows 10
* Graphics API: DX12
See attached file, "Hardware_Specs.png"

[Raven_Process_Log.txt](https://github.com/baldurk/renderdoc/files/7489581/Raven_Process_Log.txt)
![First_Exception](https://user-images.githubusercontent.com/75271593/140593780-b9a7abc7-39f9-4e52-8766-00ed87d84795.png)
![Crash](https://user-images.githubusercontent.com/75271593/140593784-3cfe0058-ea13-4af0-b886-0622e100d40d.png)
![Hardware_Specs](https://user-images.githubusercontent.com/75271593/140593787-77fac06e-cbaa-4c19-8de6-5908c1e2e9c2.png)

**Comment by BBI-JohnwillKeating** [comment]
There are some variants of this problem where the crash happens at other code locations inside Renderdoc.

**Comment by baldurk** [comment]
Are you able to share your program with my privately? I understand that you can't share it publicly due to NDAs but unless I can reproduce the problem there's no way I can investigate this issue.

**Comment by bjarnia** [comment]
That's a GPU driver crash. Everything from the attached log is essentially useless after line 2, when wer.dll is loaded (windows error reporting). All logging/behavior after that is just reacting to the GPU driver crash unfortunately. Causes for that can be extremely hard to figure out but one thing you should always do when hitting those types of issues is updating your drivers.

**Comment by baldurk** [comment]
Yes I'm aware of what the error messages mean. That's why I asked above for a reproducible test case to investigate with.

**Comment by BBI-JohnwillKeating** [comment]
I'm having difficulty reproducing the crash in a small test project that doesn't contain private content.  However, I did manage to get the same crash in Unreal without running Renderdoc at all, which means Renderdoc is not the cause of the crash.  However, unreal responds by catching the DX12 error and exiting gracefully with a message.  Ideally, Renderdoc would also respond by exiting gracefully instead of dereferencing a null pointer.  (The Renderdoc UI window process does not crash but the game process it spawns crashes inside the Renderdoc libraries)

**Comment by baldurk** [comment]
I treat device lost errors about as equally as fatal as memory allocation failures, and trying to detect and gracefully handle it in all cases it can happen is similarly not always feasible or even particularly useful (since the worst is you get a crash instead of a message box before a fatal error, _if_ the application would handle it as well).

If the device lost is caused by RenderDoc work then it papers over the real problem, so I'd still want to investigate it regardless, but if you're seeing it without RenderDoc then it sounds like it might be caused by invalid use on the application side which is not something RenderDoc is intended to handle.

FWIW I do try to handle these on the replay side since it's a much more controlled environment and I know the exact flow rather than being injected into another program, but most importantly I can actually prompt the user to share a repro case with the capture itself - which is not possible when capturing.
