### ISSUE TITLE
Failed launch in Android 9

### ISSUE THREAD

**Issue by Fanweifu** [baldurk/renderdoc#2407]
## Description

![image](https://user-images.githubusercontent.com/20275504/141040485-7ad4de55-cfb1-460f-ab62-75894c0e4c67.png)

## Steps to reproduce

just click launch and wait , then failed

this is my renderdoc log
![image](https://user-images.githubusercontent.com/20275504/141042244-00970df4-cc96-4793-b8db-5b36a22056c6.png)

## Environment

* RenderDoc version: v1.16
* Operating System: Android 9
* Graphics API: OpenglES 3.1 +
* Device : SM-G9700

it is ok that debug my app by snapdragon profiler , but i want renderdoc , please help me

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly completing the prompted sections. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) which is linked from the template you used and open a new issue which does fill out the sections properly. Do not reply to this issue with more information, please open a new issue.

As detailed in the documentation and evident by the section title, for "steps to reproduce" you must actually provide steps I can take to reproduce the problem. Most commonly and simplest for everyone would be for example sharing your application or a capture file that shows the problem. If you can't share these publicly you can [email me privately](mailto:baldurk@baldurk.org?subject=RenderDoc%20bug%20repro%20case) with a google drive/dropbox/etc link. If you can't share these even privately you should say that and provide a significant amount of information about what you are doing so I can hope to construct a reproducible test case, or suggest further diagnostic steps. If you don't do any of this your bug report is unlikely to be useful and will be closed like this one.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

As linked above and in the issue template you were provided with there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
