### ISSUE TITLE
[OpenGL] Issue with captures and ARB_query_buffer_object

### ISSUE THREAD

**Issue by cmp-** [baldurk/renderdoc#2409]
## Description

When recording the result of a query into a buffer (extension ARB_query_buffer_object) the capture does seem to modify the buffer.

The example that I provide does the following:
- renders a full screen triangle during a GL_SAMPLES_PASSED query
- stores the query result into a buffer
- renders a full screen triangle with the query result buffer as an input, with some conditional logic in the vertex shader to skip drawing if the query result is 0

When running the application the second triangle is drawn (the framebuffer is red), but in the RenderDoc capture it is not (the framebuffer is blue), and inspecting the query buffer contents shows 0.

Both the DSA version (`glGetQueryBufferObject`) and the non-DSA version (`glBindBuffer(GL_QUERY_BUFFER)` + `glGetQueryObject`) exhibit the same issue.

## Steps to reproduce

Run this program:
[Repro.executable.zip](https://github.com/baldurk/renderdoc/files/7531993/Repro.executable.zip)

or compile and run this code:
[Repro.source.zip](https://github.com/baldurk/renderdoc/files/7531995/Repro.source.zip)

or replay this capture:
[Repro.capture.zip](https://github.com/baldurk/renderdoc/files/7531998/Repro.capture.zip)

## Environment

* RenderDoc version: 1.17 Nightly (2e4905a6a833e55f5c5acec0ad1f20d0651199a7)
* Operating System: Windows 10
* Graphics API: OpenGL 4.6 Core
* Graphics Adapter: NVIDIA GeForce GTX 1080 Ti
* Driver Version: 496.49

**Comment by baldurk** [comment]
Blerch, looks like I hadn't accounted for the fact that an otherwise read-only CPU function takes on a special meaning depending on a buffer binding. `glGetQueryObject` with/without DSA isn't serialised much like all of the rest of the `glGet` functions. I'm also guessing that like vertex attrib bindings reading from an offset and/or CPU pointer this is going to lead to dozens of bugs where drivers read from near-NULL pointers depending on weird conditions.

Why is OpenGL always so completely terrible. It of course would have been utterly unthinkable to just have a different function for copying a query result to a buffer, since after all there are so few GL entry points it would be wasteful to add another...

**Comment by baldurk** [comment]
That commit should serialise the buffer-writing versions of those glGet functions and works correctly on the repro case for me.
