### ISSUE TITLE
Freeze of several seconds when selecting a draw call

### ISSUE THREAD

**Issue by DataBeaver** [baldurk/renderdoc#2413]
## Description

I'm porting my graphics engine from OpenGL to Vulkan and using RenderDoc to help me see what's happening in the pipeline.  I'm almost at the point where I can draw stuff, but RenderDoc is being annoyingly slow in inspecting API calls.  When I select a call where a pipeline is bound, RenderDoc freezes for several seconds.  Probably this is due to the remaining errors in my application (missing dynamic viewport as well as descriptor set layouts with some extra stuff), but I wonder if there's something that could be done in RenderDoc to shorten or avoid the freeze?

## Steps to reproduce

1. Load this capture: [vulkan_capture.zip](https://github.com/baldurk/renderdoc/files/7546463/vulkan_capture.zip)
2. Select the vkCmdDrawIndexed call
3. RenderDoc freezes for about 15 seconds the first time the call is selected, about 3 seconds on subsequent times (YMMV on the exact times)

## Environment

* RenderDoc version: Debian's 1.16+dfsg-1, self-compiled v1.16-98-g37fd59313
* Operating System: Debian unstable
* Graphics API: Vulkan
* GPU: GeForce GTX 980Ti
* Driver: 460.91.03-1

**Comment by baldurk** [comment]
This is caused by the use of specialisation constants with unexpectedly huge IDs. I'd assumed these IDs would be in a fairly low natural range (say <= 1000 or so typically) but this shader seems to use anything up to UINT32_MAX - I am guessing they are hashes? I'll need to fix my handling since I typically use these IDs as indices but with these values I can't, I'll need to add a remapping step.

Also please note that this capture has a number of validation errors - RenderDoc absolutely does not work with invalid code and any such errors could cause RenderDoc to misbehave or crash, in future please fix any issues identified by the validation layers before submitting a bug since otherwise it may cause false positives.

**Comment by DataBeaver** [comment]
Yes, the specialization constant IDs are indeed hashes.  I wanted automatic constant ID assignment in my custom shader compiler and could not find any indication in the various specifications that IDs should be constrained to any particular range, so I went with the full range afforded by the data type.  I only left out the sign bit because the compiler internally uses negative values to indicate that the constant ID is still pending automatic assignment.

**Comment by baldurk** [comment]
That commit should fix the issue and remap spec constant IDs and not expect to directly index via them.
