### ISSUE TITLE
Vulkan loader change breaks RenderDoc capture

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2424]
## Description

The following Vulkan-Loader change: https://github.com/KhronosGroup/Vulkan-Loader/commit/b21acf16e seems to have broken RenderDoc capture. I get a crash in `WrappedVulkan::vkCreateDebugUtilsMessengerEXT` (which just so happens to be the first function ANGLE calls), when `ObjDisp(instance)` is being dereferenced (which contains 0x10aded010110aded).

Debugging further, I found out that in that function, the `instance` that's passed is the real instance not the wrapped one, and indeed ANGLE gets the unwrapped instance back from `vkCreateInstance`. In contrast, when reverting that Vulkan Loader change, I see the wrapped instance getting returned to ANGLE and consequently passed to that function and everything works.

## Steps to reproduce

- Take top of tree ANGLE (which includes the Vulkan Loader change)
- Build
- Run any test through RenderDoc (here's one at random: `angle_end2end_tests --gtest_filter=TransformFeedbackTest.NoCaptureThenCapture/ES3_Vulkan`
- Observe crash in stdout

Also observe that checking out the commit prior to https://github.com/KhronosGroup/Vulkan-Loader/commit/b21acf16e in `third_party/vulkan-deps/vulkan-loader/src` will fix the issue.

## Environment

* RenderDoc version: Built-from source with v16 and v17 tags, but probably any. Using `-DENABLE_GLES=OFF -DENABLE_GL=OFF` cmake args to make RenderDoc work with ANGLE.
* Operating System: Linux
* Graphics API: Vulkan

**Comment by MarkY-LunarG** [comment]
I am looking into this on the loader side.  I think I found the issue, but I'm running some tests first.  Don't close this yet in case I'm wrong.

**Comment by baldurk** [comment]
I haven't debugged it but looking at the diff in `vkCreateInstance` in `trampoline.c` the loader is writing the returned output variable with its own structure instead of what's returned by calling down the dispatch chain, which will presumably break the object wrapping:

https://github.com/KhronosGroup/Vulkan-Loader/commit/b21acf16e7f703fed6e6604c9dffdc36e162b2c8#diff-da7a8effbcec5e2caadb672da36da4e69e2e238835dc3bc110804ed5109b8634L535

Since you already isolated this to a particular loader commit as well as identified that the wrong instance pointer is being returned I'm not sure why this issue was opened here instead of on the loader repository. If Mark is already double checking I'll leave this open for now but I don't see any indication this is a RenderDoc bug.

**Comment by ShabbyX** [comment]
> Since you already isolated this to a particular loader commit as well as identified that the wrong instance pointer is being returned I'm not sure why this issue was opened here instead of on the loader repository.

I wasn't actually sure what's going wrong; i.e. whether the loader has a bug (which turned out to be the case) or RenderDoc was making an assumption that wasn't valid.

**Comment by MarkY-LunarG** [comment]
@ShabbyX , can you try this change?  https://github.com/KhronosGroup/Vulkan-Loader/pull/760

**Comment by MarkY-LunarG** [comment]
This should be closed because it really is a loader issue.  I created loader issue [#761](https://github.com/KhronosGroup/Vulkan-Loader/issues/761).

**Comment by ShabbyX** [comment]
Thanks, and sorry for any confusion opening the issue here might have caused.

**Comment by MarkY-LunarG** [comment]
Not your fault.  This is mine. :-)  Best to start logging where you know an issue occurs and just move it later.
