### ISSUE TITLE
Can we keep RD Android running with screen off?

### ISSUE THREAD

**Issue by vito0719** [baldurk/renderdoc#2425]
## Description

It's similar to this https://github.com/baldurk/renderdoc/issues/1178 but since I'm using an OLED phone, I'd rather keep my screen off than having it displaying a static image while I'm working with RD on my computer...

## Environment

* RenderDoc version: any
* Operating System: Android
* Graphics API: Vulkan/GLES

**Comment by baldurk** [comment]
If you want to turn your screen off then you can turn your screen off, RenderDoc itself doesn't care at all if the device's display is turned on or off. My understanding is that after some time Android will start killing processes, so if that happens on your device then you'd have a problem but that's not RenderDoc's doing.

**Comment by vito0719** [comment]
But is it possible to add a flag or something to prevent the killing, like you did in the referenced issue?

Or is there a way to perhaps turn off the text overlays? Currently I just add a black screen in my game on four finger touch, but the texts are still there and pose a risk for burn-ins...

**Comment by baldurk** [comment]
I don't expect so otherwise every app could set that and then nothing would be closed. Keeping the screen on is a way for games/etc to indicate that they are still running even without interactivity. If there is a way I'm happy to review a pull request.

You can disable the overlay if you wish using the [in-application API](https://renderdoc.org/docs/in_application_api.html).
