### ISSUE TITLE
Invalid frameCapture

### ISSUE THREAD

**Issue by xiongjisen** [baldurk/renderdoc#2433]
## Description
Nothing happened when  clicked the Capture Frame Immediately。It is a VR hardware device made in China。
diagnostic log：
 Android 17110 19:54:40 core.cpp(1873) Error Invalid FrameCapturer 0x000000704ED3B3E8 for combination: 0x0000007022599500 / 0x0000000000000000
Android 17294 11:54:38 libc(0)      Fatal CANNOT LINK EXECUTABLE "sh": can't read file "/system/lib64": Is a directory
Android 17294 11:54:38 libc(0)      Fatal Fatal signal 6 (SIGABRT), code -6 in tid 17294 (sh), pid 17294 (sh)
Android 17297 11:54:38 DEBUG(0)     Fatal *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Android 17297 11:54:38 DEBUG(0)     Fatal Build fingerprint: 'Android/sdm845/sdm845:8.1.0/OPM1.171019.026/sueche09281059:user/release-keys'
Android 17297 11:54:38 DEBUG(0)     Fatal Revision: '0'
Android 17297 11:54:38 DEBUG(0)     Fatal ABI: 'arm64'
Android 17297 11:54:38 DEBUG(0)     Fatal pid: 17294, tid: 17294, name: sh  >>> sh <<<
Android 17297 11:54:38 DEBUG(0)     Fatal signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Android 17297 11:54:38 DEBUG(0)     Fatal Abort message: 'CANNOT LINK EXECUTABLE "sh": can't read file "/system/lib64": Is a directory'
Android 17297 11:54:38 DEBUG(0)     Fatal x0   0000000000000000  x1   000000000000438e  x2   0000000000000006  x3   0000000000000008
Android 17297 11:54:38 DEBUG(0)     Fatal x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000028
Android 17297 11:54:38 DEBUG(0)     Fatal x8   0000000000000083  x9   0000000010000000  x10  0000007fff04a180  x11  9cee3474b4639f3f
Android 17297 11:54:38 DEBUG(0)     Fatal x12  9cee3474b4639f3f  x13  0000000000000020  x14  ffffffffffffffdf  x15  00000079c1daea40
Android 17297 11:54:38 DEBUG(0)     Fatal x16  0000000000000008  x17  9cee3474b4639f3f  x18  9cee3474b4639f3f  x19  000000000000438e
Android 17297 11:54:38 DEBUG(0)     Fatal x20  000000000000438e  x21  0000000000000083  x22  0000007fff04b9ff  x23  0000000000000000
Android 17297 11:54:38 DEBUG(0)     Fatal x24  00000079c1c0d350  x25  00000079c1c0d350  x26  000000559d

## Environment

* RenderDoc version: 1.17
* Operating System: windows11
* Graphics API: gles 3.2

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
