### ISSUE TITLE
Reduce RAM requirements for loading a capture

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2434]
## Description

I'm trying to replay a capture on a machine with 64Gb of RAM, and it's going OOM.
When replaying smaller captures, I can see that the RAM usage peaks when the capture is loaded, but it's lower when I'm just navigating a capture state. So there is hope that I can work with this giant capture if only it was able to load.

Would it be possible to reduce RAM consumption on initial capture load?

## Environment

* RenderDoc version: 1.16
* Operating System: Linux (packaged for NixOS)
* Graphics API: OpenGL ES 3.0

[actual zipped capture](https://drive.google.com/file/d/1LU7GrM5IIO922F10qOIM9RV7EzA78SPx/view?usp=sharing)

**Comment by baldurk** [comment]
Can you please test this with either a binary build from renderdoc or a clean build from source using default configuration (i.e. no compile or cmake flags) to make sure the issue is not caused by the distribution package you're using? Distribution packages can be unreliable and are not directly supported.

**Comment by kvark** [comment]
Built f8476b53b55e21b640897a8bdc5c0e11a777de28 from source "-DCMAKE_BUILD_TYPE=Release". Still able to reproduce the issue (computer hung this time, completely).

**Comment by baldurk** [comment]
I've started looking into this capture, but at least from back-of-the-envelope calculations the memory use isn't too far away from what I expect. The capture itself allocates about 25GB worth of textures (calculating as tightly packed over all dimensions/formats) and uploads about 12GB of texture data within the frame. On GL the textures that are modified within the frame get duplicated first to allow for resetting their contents for read-before-write situations, so the total footprint is roughly speaking 62GB. Assuming the driver has extra stipulations for how it allocates textures and allowing for other overheads and not all physical RAM being available it's not too surprising that it hits OOM.

This might just be a case where the capture itself is very resource intensive and it requires a large system to replay. If you're able to split your work up such that not all of those resources and that data are needed at once you can probably get better results - possibly using manual start/stop of captures for only parts of the frame you care about using the [in-application API](https://renderdoc.org/docs/in_application_api.html).

I'm going to do some more digging and see if there's any low hanging fruit improvements I can make. Even hacking out some of the overhead the drivers I tested on windows at least crashed with just that number of textures so my results aren't completely conclusive. There may be optimisations and heuristics that can improve this situation, but I'm not sure if there are any that would be worth the implementation cost and potential slowdown/extra code complexity for the large majority of cases.

**Comment by baldurk** [comment]
Looking into this further, I don't see any reasonable wins to make. As mentioned above the issue primarily comes from the total footprint of textures in the capture, and relatedly how most of them are written within the capture. I believe additional shadow CPU/orphaning allocations within the driver on each texture update in the frame itself is adding to the overhead.

There are optimisations here in theory but they are unfortunately not trivial. For example the frame itself doesn't have to be kept in memory, but that means I/O and decompression for every replay (on each event selection at minimum) which is definitely not something I'd want aside from this exceptional scenario where the whole capture may not all fit into memory.

It would also be possible in principle to do more advanced read/write tracking to see that many textures are not ever read from, or at least have undefined contents before being written, so the duplicates mentioned above are unnecessary. This does happen on Vulkan, but Vulkan has a _significantly_ smaller API surface and manners of reading and writing which makes this feasible. On GL there are so many different ways to do either that I'd be concerned of the overhead of such tracking as well as the chances of getting it wrong.

I suspect GL makes this worse as it does seem like there are more allocations going on behind the scenes in the driver to keep CPU copies of textures and handle orphaning, which wouldn't happen on Vulkan with more explicit memory allocation. Since this is a relatively rare problem I don't think it's worth the effort and code churn to optimise for currently.

If you're not able to reduce the scope of the capture (I noticed a lot of textures are created and updated, but never used) one workaround you could make would be to go to `GLResourceManager::Create_InitialState` in `gl_initstate.cpp` and comment out the call to `PrepareTextureInitialContents`. This prevents the duplicate snapshot I mentioned above and will reduce the memory load fairly significantly. When I did that on my main system with 64GB of RAM I was just about able to load the capture, with some swapping to disk. Note however that this is *not* safe to do in the general case and I didn't check to see if it resulted in incorrect replay of your capture.

**Comment by kvark** [comment]
Thanks for looking into this!
