### ISSUE TITLE
python API can't take a capture

### ISSUE THREAD

**Issue by aminefsm** [baldurk/renderdoc#2440]
## Description
I wrote this python script to capture frame from local machine . I thing the code is correct but I don't know exactly where the problem here.

## Steps to reproduce
here is the code :

``` 
import renderdoc as rd
from time import sleep

app = "C:\Program Files\FSm\Fsm.exe"
workingDir = "D:\files"
cmdLine = ""
env = []
capturefile = ""
opts = rd.GetDefaultCaptureOptions()
waitForExit = False

result = rd.ExecuteAndInject(app, workingDir, cmdLine, env, capturefile, opts, waitForExit)
sleep(20)
print(result.status)
target = rd.CreateTargetControl('', result.ident, "capture.py", True)
print("Triggering capture")
target.TriggerCapture(1)
# Pump messages, keep waiting until we get a capture message. Time out after 30 seconds
msg = None
start = time.clock()
while msg is None or msg.type != rd.TargetControlMessageType.NewCapture:
    msg = target.ReceiveMessage(None)
    if time.clock() - start > 40:
        break
# Close the target connection, we're done either way
target.Shutdown()
target = None
cap_path = msg.newCapture.path
cap_id = msg.newCapture.captureId
print(f"Got new capture at {cap_path} which is frame {msg.newCapture.frameNumber} with {msg.newCapture.api}")


```
the output of this code is :
Got new capture at  which is frame 0 with 
and target.ReceiveMessage  returns TargetControlMessageType.Noop

## Environment

* RenderDoc version: 1.17
* Operating System: Windows 10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
You need to handle and ignore `TargetControlMessageType.Noop` messages since there isn't a guarantee that the next message received after triggering a capture will contain the information with that new capture, as the capture may take long enough that several messages are received. `ReceiveMessage` doesn't block until the next 'meaningful' message, it will return quickly after ticking the connection to allow you to do other processing, etc. If no message is available it will return `Noop`.

See the [documentation for ReceiveMessage](https://renderdoc.org/docs/python_api/renderdoc/capturing.html#renderdoc.TargetControl.ReceiveMessage) which explains this:

> If no message has been received, this function will pump the connection. You are expected to continually call this function and process any messages to kee pthe connection alive.
> 
> This function will block but only to a limited degree. If no message is waiting after a small time it will return with a No-op message to allow further processing.

As a side note, if all you're doing is triggering a capture after some number of seconds or when a condition is hit, you might find it easier to use the [in-application API](https://renderdoc.org/docs/in_application_api.html) and trigger the capture from your application instead as this gives you better control.

**Comment by aminefsm** [comment]
yes I want to trigging a capture after a condition and I need to do it with python. I ignore TargetControlMessageType.Noop messages  and I used` target.TriggerCapture(1)`. Even when use  target.QueueCapture(10, 50)  but when I check my workingDir I don't find any file.rdc. and the 
do I have to specify the extension (.rdc) of the capture file path. or shoud I change the set of the capture options, cause I used the default options.

**Comment by baldurk** [comment]
Sorry, it's not feasible for me to help debug and assist writing python scripts using the API unless the API itself is broken. If you have a bug you can reproduce using the program itself, or you have reasonable certainty that there is a bug in RenderDoc as accessed via the python API then please open an issue indicating what is happening that's wrong and what should be happening.
