### ISSUE TITLE
Failed to open capture caused by VK_EXT_debug_marker not supported...

### ISSUE THREAD

**Issue by tlf30** [baldurk/renderdoc#2455]
## Description

When trying to open a created on the same machine, during the same renderdoc session that the capture was taken from (or in a different sessino) , the capture fails to open with the following error:
![image](https://user-images.githubusercontent.com/10089434/150224204-6dae244a-9bb9-450c-8fd9-76e391b46e40.png)

The log file has the following snippet in it:
```
RDOC 007412: [13:23:45]          vk_core.cpp(4081) - Warning - [Loader Message] loader_validate_device_extensions: Device extension VK_EXT_debug_marker not supported by selected physical device or enabled layers.
RDOC 007412: [13:23:45]          vk_core.cpp(4081) - Warning - [Loader Message] vkCreateDevice: Failed to validate extensions in list
RDOC 007412: [13:23:45]  vk_device_funcs.cpp(3318) - Error   - Failed to create logical device: VK_ERROR_EXTENSION_NOT_PRESENT

```

## Steps to reproduce

1. Run the application (Running Vulkan 1.2)
2. Take a capture
3. Renderdoc attempts to open it and this fails

Please see attached capture and log (in the same zip).

[capture.zip](https://github.com/baldurk/renderdoc/files/7900932/capture.zip)

I have not attempted a different vulkan application, currently I am working with an in-house engine, which normally works fine. There are no errors at runtime in the application, and the capture is taken fine. 

If you would like a copy of the application, please let me know and we can work something out to get you a build. 
If you have any applications you would like me to run to test with please let me know and I can do so. 

## Environment

Build info:
![image](https://user-images.githubusercontent.com/10089434/150224873-f67dfb81-21ef-4b8a-aa3a-57cfd74d8dd1.png)

GPU:
![image](https://user-images.githubusercontent.com/10089434/150225104-0ec4eb56-cd39-43be-8497-516d88b54fe6.png)

OS:
![image](https://user-images.githubusercontent.com/10089434/150226427-548a618a-f2c0-4301-9fd7-6147b37695f8.png)

Please let me know if you need anything else.
Thank you,
Trevor

**Comment by baldurk** [comment]
This looks like it may be caused by an error in the application.

At instance creation time you are not enabling any layers, but at device creation time you are enabling several, including two that are incompatible and some layers from other capture tools which are definitely not supported to be enabled at the same time as RenderDoc: VK_LAYER_LUNARG_standard_validation, VK_LAYER_KHRONOS_validation, VK_LAYER_NV_GPU_Trace_release_public_2021_5_1, VK_LAYER_NV_optimus, VK_LAYER_NV_nsight, VK_LAYER_LUNARG_monitor.

In addition [device layers are deprecated](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#extendingvulkan-layers-devicelayerdeprecation) and have been for several years since very soon after Vulkan was released. You should pass exactly the same set to both instance and device creation. It looks like RenderDoc doesn't handle this case, which is arguably invalid now.

Does this still occur if you fix that issue?

**Comment by tlf30** [comment]
Thank you for the very detailed and helpful response. I will dig into the engine code and see what I can find.

**Comment by tlf30** [comment]
OK, found it. Thank you so much for your help on this @baldurk . In fact the validation pointer array was populated for both the instance and device, but right before instance creation was being set to null. 😨 
I will have to test and see if this fixes any of the bugs we have in the issue tracker, there are several validation issues we were having and I feel like this could be the cause. I also dug into the validation config which sets which layers are loaded and stripped out everything. I imagine I will get cursed at the next time someone opens it in nsight 😆 

![image](https://user-images.githubusercontent.com/10089434/150574331-40a99c3b-f389-45d9-97c5-f1647d19c114.png)

If it is easy to do, it would be great to get some kind of message indicating errors like these for when the capture cannot be opened.

As always, thank you so much for all your work on this amazing tool. I do not know how I would do my job without RenderDoc (Actually, I do know, it would be in a deep dark metaphorical cave with lots of coffee 😆 )

**Comment by baldurk** [comment]
I've made a change that will ignore the device layers when checking for extensions, which addresses the issue. The problem was that it was looking at the device layers, enumerating them assuming they would be available, and seeing that the debug marker extension could be enabled. Normally it checks extensions and displays a more useful error when an extension is required but not supported.

It's not within RenderDoc's scope to validate correct API use, so I would hope that if you enabled the validation layers at instance scope they would warn if the device layers were wrong like this. RenderDoc doesn't handle invalid API use so the behaviour is undefined when that does happen.

FWIW I don't know about those other tools but generally I expect you shouldn't be enabling those layers manually either. Also you definitely should not try to enable both LUNARG (which is old and deprecated) and KHRONOS validation layers.
