### ISSUE TITLE
RenderDoc file got imported to blender with errors

### ISSUE THREAD

**Issue by AliAlherz64** [baldurk/renderdoc#2472]
I booked a ticket (https://developer.blender.org/T93972) in blender support regarding the subject,
I am facing some issues:

Some blender function like knifescut crashes blender.

Black faces.
![image](https://user-images.githubusercontent.com/96901891/151677217-ae94a1ee-72cc-44ac-af41-fd0b26fc976f.png)

corruption in view port.

![image](https://user-images.githubusercontent.com/96901891/151677273-9b18a44c-c445-4528-9ca1-ff3a186196a4.png)

![image](https://user-images.githubusercontent.com/96901891/151677285-570f9efd-d8ba-463e-8a00-568b09c94102.png)

at the end we found that the rdc file was imported with errors.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
