### ISSUE TITLE
Vulkan: vkGetImageMemoryRequirements doesn't work on swapchain images with RenderDoc attached

### ISSUE THREAD

**Issue by 4dhesive** [baldurk/renderdoc#2476]
## Description
With RenderDoc attached, calling `vkGetImageMemoryRequirements` with a swapchain image as the parameter, fills the corresponding `VkMemoryRequirements` object with all zeroes.

## Steps to reproduce
* Create a swapchain with `vkCreateSwapchainKHR`
* Fetch swapchain images using `vkGetSwapchainImagesKHR`
* Call `vkGetImageMemoryRequirements` on one of the returned swapchain images.
* Observe that the `VkMemoryRequirements` struct has been filled with all zeroes.

## Environment
* RenderDoc version: 1.18 official. Issue couldn't be reproduced on version 1.16.
* Operating System: Windows 10
* Graphics API: Vulkan
* GPU: NVIDIA RTX 2070 Super
* Driver version: 511.23

**Comment by baldurk** [comment]
This is invalid behaviour, swapchain images are fully bound to memory so it should be invalid to query for their memory requirements - even if you could query for it the return values would not be actionable since you can't bind their memory so you shouldn't expect any particular values.

I can't see an obvious VUID in the spec preventing this which seems like a spec bug, I'll file an issue.
