### ISSUE TITLE
vkEnumeratePhysicalDeviceGroups access violation exception on NVidia 511.65

### ISSUE THREAD

**Issue by frank-ourmachinery** [baldurk/renderdoc#2489]
## Description
When trying to query the number of physical device groups using `vkEnumeratePhysicalDeviceGroups` RenderDoc will get an access violation exception which crashes the application. This was discovered using [volk](https://github.com/zeux/volk), but the snippet below uses the Vulkan SDK.

![image](https://user-images.githubusercontent.com/70658773/152959847-63342d8b-7560-45f7-be0f-b14b8156c66c.png)

## Steps to reproduce

As I cannot share my code so I've written a minimal reproducible snippet. When running without RenderDoc the output is:
```
vkCreateInstance 0
vkEnumeratePhysicalDeviceGroups 0
```

But when running with RenderDoc the application will crash on `vkEnumeratePhysicalDeviceGroups `. Only the first line of the expected output is printed.

```cpp
#include <vulkan/vulkan.h>
#include <cstdio>
#include <thread>

int main(int argc, char *argv[])
{
	const VkApplicationInfo application_info = {
		VK_STRUCTURE_TYPE_APPLICATION_INFO,
		nullptr,
		"application-name",
		VK_MAKE_API_VERSION(0, 1, 0, 0),
		"engine-name",
		VK_MAKE_API_VERSION(0, 1, 0, 0),
		VK_API_VERSION_1_2
	};

	const VkInstanceCreateInfo instance_create_info = {
		VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
		nullptr,
		0,
		&application_info,
		0,
		nullptr,
		0,
		nullptr
	};

	VkInstance instance = VK_NULL_HANDLE;
	VkResult res = vkCreateInstance(&instance_create_info, nullptr, &instance);
	printf("vkCreateInstance %d\n", res);

	uint32_t num_device_groups = 0;
	res = vkEnumeratePhysicalDeviceGroups(instance, &num_device_groups, nullptr);
	printf("vkEnumeratePhysicalDeviceGroups %d\n", res);

	std::this_thread::sleep_for(std::chrono::seconds(5));
	vkDestroyInstance(instance, nullptr);
}
```

## Environment

* RenderDoc version: v1.18 (built from 3996d037) (Qt version 5.15.2)
* Operating System: Windows 10 Pro 21H1
* Graphics API: Vulkan 1.2 (Vulkan 1.3 capable)
* GPU: NVIDIA GeForce RTX 3090
* Driver: 511.65
* Vulkan SDK: 1.2.189.2 (used in the snippet)
* Volk Header Version: 198

**Comment by baldurk** [comment]
Thanks for the clear repro case. This it looks like a vulkan loader bug, which by coincidence someone ran into independently and fixed just recently: KhronosGroup/Vulkan-Loader#831

There's unfortunately nothing reasonable that I can do about this on RenderDoc's side, it will need to wait until a fix is available via the vulkan loader. The fix is included in version [v1.3.205](https://github.com/KhronosGroup/Vulkan-Loader/releases/tag/v1.3.205) so it will depend on when drivers pick that up build.

You could temporarily drop a recent build of the loader locally into your application for use if this is blocking you, but note that RenderDoc has no 'true' support for device groups, and will always report every device in a different group regardless of what the driver reports (which is valid, if degenerate).
