### ISSUE TITLE
Device Removal under high memory usage

### ISSUE THREAD

**Issue by amuTBKT** [baldurk/renderdoc#2496]
## Description
I am seeing a consistent DMA page fault causing device removal when trying to capture a frame under high GPU memory usage.
The crash is happening inside **D3D12ResourceManager::Prepare_InitialState**, there are no errors/warnings from D3Dd debug layer.
The issue happens only if ResidencyManager is enabled, and I suspect making resources resident inside Prepare_InitialState might be causing eviction of existing resources without notifying the application. One workaround that seems to work is to force **MakeResident** call on all the resources (I guess that might be bringing in the evicted resources).

I am planning on reducing memory usage in my application, just wanted to check if this is a known issue/limitation. I don't see how Renderdoc might be able to work with third party engines to manage resource lifetime.

The crash doesn't occur when using D3D11.
The crash doesn't occur if I run 3-4 instances of UE4 with similar workload (GPU memory usage maxed out)

## Steps to reproduce
1. Make sure the GPU memory usage is ~70-80%
2. Open a memory intensive level in UE4 with D3D12ResidencyManager enabled (enabled by default)
3. Try to capture frame and notice crash in renderdoc.dll

## Environment
* RenderDoc version: 1.18 release version (built from 3996d037)
* Operating System: Windows 10 v1909
* Graphics API: D3D12
* Unreal Engine 4 (D3D12 Residency enabled)
* GPU: RTX 2080

**Comment by baldurk** [comment]
I don't know what D3D12ResidencyManager is, I guess from context this is referring to something in your code?

The residency management in RenderDoc is fairly simple and just aims to ensure that resources are resident while they're being snapshotted, by temporarily making them resident then evicted again. Aside from affecting the overall memory footprint temporarily this should have no side-effects according to the API docs (which are admittedly quite unreliable as this is D3D12).

It's certainly the case that capturing in RenderDoc does require some memory headroom and you can run into out of memory issues, however I don't understand how that could manifest with it only occurring when memory is mostly-but-not-completely full. Are you absolutely sure that's the cause and this isn't a random crash which happens intermittently and by coincidence has only happens when you have memory partly full?

I need more information and detail in the steps to reproduce to be able to investigate this. I have UE4 available but I don't know what D3D12ResidencyManager is nor do I have any memory intensive projects to open. If you understandably can't share your own then could you point at a sample or demo project which does reproduce this issue?

**Comment by amuTBKT** [comment]
Hi, thanks for getting back so quickly :)

By D3D12ResidencyManager, I meant the default residency management solution Unreal is using (https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/UWP/D3D12Residency/src/d3dx12Residency.h)
I am on UE 4.26.2

**The residency management in RenderDoc is fairly simple and just aims to ensure that resources are resident while they're being snapshotted, by temporarily making them resident then evicted again.**
Yes, Renderdoc is using ref counting (m_Resident) to check if resource is evicted/resident. My theory was that this ref count might be unreliable if due to some reason an existing resource is evicted by system but Renderdoc thinks it's already resident (m_Resident  > 0). This is what I tested by forcing m_Device->MakeResident(..) call on the resource irrespective of m_Resident value.

I am almost 90% sure System is evicting the source texture (used for copy operation). I can see a resource which has similar description as the destination resource (buffer for copy op) getting evicted a few calls before Renderoc tries to use it. I wasn't able to verify if its indeed the resource used by copy op as I am not sure how to get that info from GPUView and I am not aware of any other software available to diagnose this issue :)

**However I don't understand how that could manifest with it only occurring when memory is mostly-but-not-completely full**
I wasn't clear on this one. My project uses a lot of memory so by the time capture is almost done the memory utilization is maxed out, so the issue also happens if memory is almost full.

 **If you understandably can't share your own then could you point at a sample or demo project which does reproduce this issue?**
 Sadly I won't be able to share the project :( , this issue happens on my work project.
 I'll try to see if I can hack something up for you to try :)
 
 Regards

**Comment by baldurk** [comment]
Yeh I mostly wondered if you could reproduce the same behaviour with a public project of some kind - tech demo, tutorial, or others - I believe there are a lot out there, but without being able to know exactly it would take a long time (and if the repro isn't 100% reliable I may not be able to tell at all).

Without being able to reproduce the problem it's difficult to investigate any further. There shouldn't be any way for RenderDoc to miss a call to make resident or evict, as the only APIs that do that are intercepted, but with what you say possibly this is a multithreaded race condition or similar?

If you're able to test, you could try adding a lock in to prevent MakeResident/Evict from happening while RenderDoc is gathering resources. Most other work is already prevented from happening since this is intended to be 'atomic'. A patch something like this (not heavily tested, might deadlock) should work: [residency.txt](https://github.com/baldurk/renderdoc/files/8073849/residency.txt) Just in case that patch also adds a GPU flush before starting the work, just in case an EnqueueMakeResident is still pending, but I don't think that should be possible.

In principle it would be feasible to always call MakeResident (since the eviction status is refcounted as you say), but the problem is currently we flush the GPU after the copy to be able to evict again. This would either require flushing after every copy, or else the resident set would increase by every resource we want to copy (or at least all up to some limit), so I'd rather not do that unless it's absolutely necessary for correct functioning.

**Comment by amuTBKT** [comment]
Ok, I was able to repro this on a sample project as well :)
May I know how much VRAM your system has? I will tweak the memory consumption according to that. My system uses 11gigs so my test case might not load on your system :p 

I will be attaching the project built on UE 4.27.2, its available through Epic Launcher.

**Comment by baldurk** [comment]
I have a couple of different systems available but I have a 2080 Ti with 11GB VRAM so it makes sense to most closely match your system.

**Comment by amuTBKT** [comment]
https://drive.google.com/drive/folders/1CkwHPHvm1WA-vYBvbKbTZHMtDvZbE2ge?usp=sharing

You can grab the sample from that link.
its a modified version of https://www.unrealengine.com/marketplace/en-US/product/sun-temple?lang=en

I've added a Niagara system NS_EatMemory which should allocate huge chunk of memory.
the memory usage by Niagara fluctuates a bit (i couldn't get it to maintain high mem usage), so what works is to compile the system and then try to grab capture.
I've added some steps with the zip file.

Let me know if you need any more info :)

**Comment by amuTBKT** [comment]
**If you're able to test, you could try adding a lock in to prevent MakeResident/Evict from happening while RenderDoc is gathering resources. Most other work is already prevented from happening since this is intended to be 'atomic'**

Just to be clear, what I interpreted from GPUView capture was that the resource was being evicted by **Windows System**, not renderdoc or host application.

**Comment by baldurk** [comment]
Yeh to clarify I don't know how the windows memory system works under the hood, but it would only be a bug in RenderDoc if there is some API-level evict happening followed by use of the resource. If everything is correct according to the API (as in everything properly resident and synchronised such that residency is ensured while the GPU is executing) then even if windows is evicting something behind the scenes and faulting on that, that's a windows bug and not something I can realistically do anything about.

I'll test the repro you've given tomorrow and look into it in more detail - I suspect it will come down to an API level residency issue but I'd need to dig in to see what it is.

**Comment by baldurk** [comment]
I tried testing this, though I wasn't able to click 'compile' in your repro steps without my whole machine locking up quickly after. Fortunately I did get the necessary 10GB VRAM allocated just by opening up the second window and not clicking compile.

Unfortunately though my secondary windows 10 dev machine only has 16GB of RAM so I ran into (I assume) unrelated issues failing to allocate readback buffers. I'm sorting out ordering more RAM to be able to reproduce properly but I think this will have to wait until that arrives.

**Comment by amuTBKT** [comment]
😅
No worries, I can wait :)
fyi, my system has 32GB CPU RAM.

**Comment by amuTBKT** [comment]
Also, if you can swap GPU (one with lower VRAM), you should be able to disable some of the allocations from Niagara system.
![image](https://user-images.githubusercontent.com/6421759/154290452-64d4dfab-43a7-4d24-92d2-1d5762f4caa6.png)

**Comment by baldurk** [comment]
Yeh I did try playing with something along those lines as a workaround, but the other card I have is still 8GB of VRAM so I still hit out of memory errors.

**Comment by amuTBKT** [comment]
Hello, did you get a chance to test this with more CPU RAM? :)

**Comment by baldurk** [comment]
I only got the extra RAM delivered a day or two ago and I've had other things to look at. I'll let you know when I'm able to test it.

**Comment by baldurk** [comment]
I've tried to reproduce this now with 48GB of CPU RAM and unfortunately I still can't. Most of the time I'm now able to capture and open it successfully. Sometimes it does hit a hang/out of memory but I'm not reading into that too much yet since the UE4 editor is still running in the background eating a lot of resources. I didn't see any crashes while capturing though, it always successfully captured.

I can try and dig in further into the intermittent crashes on replay and see if they're even reproducible with normal memory use, but from your description you were always seeing the crash on capture?

Are you able to reproduce this on any other system? is it possible that there's any other external configuration that might be affecting the repro?

**Comment by amuTBKT** [comment]
Hello, yes I was able to reproduce it on my work (Intel cpu + 2080Ti) and home PC (AMD cpu + 1080Ti).
Its also crashing for everyone on my team, we have very different PC specs (including AMD gpus as well).

Can you try with 32GB CPU Ram if possible? I am wondering if exhausting GPU shared mem could be a factor as well :?

**Comment by baldurk** [comment]
I tried with 32GB of RAM but I still get similar results (no crash during capture, replay fails more regularly with out of memory errors since it's needing more shared GPU memory for uploading data).

Just to completely nail down the reproduction steps in case I'm doing anything wrong or differently:

1. I launch UE4 4.27.2, installed from the epic games launcher, with `...\UE4Editor.exe "...\RenderdocRepro\SunTemple\SunTemple.uproject"`
2. Wait for it to load, the RenderDoc plugin is active with plain v1.18 loaded.
3. Memory use at this point  is about ~5GB dedicated memory, negligible (0.2GB) shared memory.
4. Select the NS_EatMemory object and double click on the 'Niagara System' button to open the popup window.
5. At this point for me the dedicated memory reliably increases to ~10GB, shared memory still the same.
6. Capturing here doesn't reproduce the crash during capture.
7. If I click 'compile' as in the repro steps, the GPU memory tends to drop to ~6GB dedicated, sometimes with some shared memory use sometimes without. I'm unsure if that's intended, but capturing in that situation also doesn't reproduce for me.

And to clarify, when you're able to reproduce on your different PCs are you using this above repro, or your actual original project? I'm assuming if you can reliably reproduce on both it's probably interchangeable, but I just want to check.

I don't know why this would be 100% consistent for you and not reproducible at all for me, but this difficulty does make me wonder if it is a timing bug after all (perhaps affected by some other variable we're not controlling for, or some difference in our systems). Can you test with [this build](https://renderdoc.org/RenderDoc_wip_2496_64.zip) with some speculative fixes and locking around residency calls, to see if it fixes the problem for you?

**Comment by amuTBKT** [comment]
Hi, I tried that sample project on work PC and wasn't able to reliably reproduce the crash :(

Using the **custom build** you provided:
1. Sample project on my local pc didn't crash, It would mostly just error out with "Out of Memory" error.
2. Work project on work PC is not crashing :)
    - I also tried launching sample project in the background to increase memory usage but it was still able to capture.
    - With multiple instances of project running each with their own Renderdoc capture caused device lost error when trying to replay capture, just to stress test. But still no crashes!

I guess the changes you made seem to work :)

**Comment by baldurk** [comment]
And just to clarify, those OOM or device lost errors you encountered were no worse than it was before, and/or only in stress test conditions? i.e. with that build you're able to capture successfully the same as you used to be able to, and the cases that crashed before now either capture fine (hopefully?) or rather than crashing they gracefully report a failure to replay if they're out of resources?

The fixes were adding locking around MakeResident/Evict, since possibly what was happening was another thread was evicting resources in between RenderDoc checking if they were currently resident and trying to use them. Or I also noticed while adding that locking that I wasn't properly tracking residency of heaps - only resources - so possibly a heap was evicted behind a placed resource.

I'll push them shortly, but I wanted to check that there's no lingering issue here.

**Comment by amuTBKT** [comment]
I encountered OOM issue only on my SampleProject under very high stress. I don't think it would be a likely scenario in real world application.
On work project I didn't encounter any issues using the same steps that were crashing v1.18. It was able to cope with multiple instances running as well. Also seemed to work fine for my colleagues :)
