### ISSUE TITLE
Failure To Load Capture For Simple Vulkan App

### ISSUE THREAD

**Issue by JackStouffer** [baldurk/renderdoc#2507]
## Description

I'm writing a custom 2D Vulkan renderer and at the moment it's pretty simple, with only seven different shaders and everything on screen is either a textured quad or a solid colored quad. However, when I try to load a capture from this renderer, RenderDoc gets suck loading the capture forever. I've waited for about 15 minutes before I gave up. I can't even close the app normally; I have to end the task in task manager.

![Screenshot 2022-02-23 13 36 25](https://user-images.githubusercontent.com/680068/155385298-3146d358-3a09-4818-8ea5-4f7af4a92382.png)

## Steps to reproduce

Here is the failing capture file.

[failing_capture.zip](https://github.com/baldurk/renderdoc/files/8126937/failing_capture.zip)

1. Open RenderDoc
2. Hit "Open Capture" in the menu
3. Click on the failing capture file
4. It should now be stuck in the loading process and never finish

If you need a copy of the exe/source, please let me know. I'd be happy to email it. The source is proprietary so I'd rather not share it publicly. 

## Environment

* RenderDoc version: v1.18
* Operating System: Windows 10
* Graphics API: Vulkan
* GPU: NVidia GTX 1060 6GB 
* Driver Version: 511.65

**Comment by baldurk** [comment]
I'm not able to reproduce this unfortunately, the capture loads successfully for me. However I have noticed recently that nvidia's drivers no longer reliably report device lost and instead tend to hang, so I suspect this is a device lost error.

I fixed a couple of validation errors that were found when loading the capture (they didn't seem to be your fault, but mine). Can you test again on the next nightly build to see if that fixes it? if not we can go from there, though if you have a different GPU you're able to test on that would be good to try.

**Comment by JackStouffer** [comment]
I don't think your commits are in the nightly build yet. When the Feb, 24 build goes up on the website I'll download it and report back.

**Comment by baldurk** [comment]
Yes sorry, nightly builds go up at the end of the day UTC (UK time) around 4AM or so.

**Comment by JackStouffer** [comment]
Downloaded the nightly and also upgraded my driver version to 511.79 in case that would fix the device error you were talking about.

The application no longer hangs, but I get a new message saying "Replaying the capture failed at the API level"

I've attached the log output

[failing_capture.log.txt](https://github.com/baldurk/renderdoc/files/8144895/failing_capture.log.txt)

**Comment by baldurk** [comment]
Looks like there's a minor bug that doesn't properly report device lost on open as device lost, I've fixed that but going by the log that's still what's happening so it doesn't change much but the text of the dialog message.

Unfortunately I'm still not able to reproduce this at all. I don't have an exact match for your GPU and driver, partly because the closest GPU I have a 1080 is in my primary development machine on windows 7 so it doesn't have the same driver available.

Without any validation errors and without being able to reproduce there's not much I can do directly. Do you have a different machine or GPU you're able to test this on? Are you able to capture other vulkan programs OK e.g. [Sascha's demos](https://github.com/SaschaWillems/Vulkan)? if so can you try simplifying your program down to the smallest possible case that still fails to load - if you can get it down to a single triangle draw I can try and inspect what's going on by hand to see if I see anything suspicious, or compare to a working program to see what's different.

**Comment by JackStouffer** [comment]
Narrowed it down to the text renderer. Trying to create a minimal case

**Comment by JackStouffer** [comment]
Ok, I was able to narrow it down to two draw calls with two quads. It has something specifically to do with rendering the texture of the little red enemy and then a font texture. I have no idea why.

If you replace the enemy texture with anything other texture the capture loads fine. If you don't draw the font quad, just the enemy texture the capture loads fine, and vice versa.

[failing_capture2.zip](https://github.com/baldurk/renderdoc/files/8183347/failing_capture2.zip)

**Comment by baldurk** [comment]
Unfortunately that capture still loads fine for me. I'm not quite sure what you mean with

> If you replace the enemy texture with anything other texture the capture loads fine. 

Do you just mean changing the _contents_ of the texture, or since I see you're using descriptor indexing do you mean indexing a different descriptor?

On that note I see you're using descriptor indexing without enabling the physical device feature. I don't know if nvidia does anything with them, but you should be enabling `shaderSampledImageArrayDynamicIndexing`. In fact both of the draws use a fragment input as a descriptor index which is _not_ dynamically uniform, so this usage would require the `EXT_descriptor_indexing` extension and the `shaderSampledImageArrayNonUniformIndexing` feature, and the access would need to be marked as `NonUniform` in the shader.

This also suggests a further avenue of simplification: what happens if you pass that index via a dynamically uniform source such as from a uniform buffer or push constant? Or if that doesn't work, if the index is hardcoded to a constant? What if you don't use descriptor indexing at all and only bind a single non-arrayed texture?

**Comment by JackStouffer** [comment]
All textured quads are drawn with a single draw call and a large instance count with the index into the array of textures set as a member of the per-instance data SSBO to reduce descriptor set rebinding calls. So using push constants or uniform buffers for the index into the array of textures wouldn't work in this case.

I'll take a look at your other suggestions and get back to you.

**Comment by JackStouffer** [comment]
Made your suggested changes and renderdoc now back to the infinite loop rather than the error message. It was hard to find resources on nonuniformEXT, and I'm a graphics API newbie so I might have made an obvious mistake in the code:

[failing_capture3.zip](https://github.com/baldurk/renderdoc/files/8188902/failing_capture3.zip)

Per your suggestion I hard coded the texture indexes just to see what happens. Still hangs:

[failing_capture4.zip](https://github.com/baldurk/renderdoc/files/8188908/failing_capture4.zip)

Is there some sort of debug build I can download to get a stack trace of what it's getting stuck in?

**Comment by baldurk** [comment]
That first one looks fine now. Though in the hardcoded case the second draw still uses a non-uniform instance index to look up the texture, so it's not a complete test of that factor.

If hardcoding both shader indices doesn't fix it though I'd suggest then trying to simplify further and remove the descriptor array entirely and sample directly from a single texture binding, see if that fixes it.

You don't need a debug build to see the stack trace, you can attach VS to renderdoc directly and use the symbol server at https://renderdoc.org/symbols - though you can build the source from this repository if you want a true debug build. However I'm 99.9% sure that you will find it is hanging inside the nvidia driver code, as I have found that very often when a device lost error happens they don't report it properly and instead hang inside the next call that might need to block. That's especially likely since sometimes you see a device lost error actually reported.

**Comment by obiwanus** [comment]
This may be unrelated by the latest version (1.18) fails to load captures as well for me - tried it on 2 different Vulkan apps, it simply exits when I close the app to check the captured frame. Downgraded to 1.17 and it seems to work fine there.

**Comment by baldurk** [comment]
Please do not comment on existing bugs with an unknown problem, please open a new bug and fill out the template to provide the relevant information for me to investigate.

**Comment by JackStouffer** [comment]
I apologize, but I can't devote any more time to debugging this. I need to rewrite the text rendering for the app anyway, and I got nvidia's debugger working so I need to move on. Thanks for your time.
