### ISSUE TITLE
Texture only shows its final state in frame

### ISSUE THREAD

**Issue by Veeloxfire** [baldurk/renderdoc#2508]
## Description

I was writing a very simple 2d Opengl renderer and reusing the same texture object but replacing the texture in a single frame
i.e. code a bit like this
```c++
glBindTexture(GL_TEXTURE_2D, gl_texture);
glTexImage2D(...);
glDrawElementsInstanced(...);
glTexImage2D(...);
glDrawElementsInstanced(...);
SwapBuffers();
```

In the viewer when you inspect a single pass it shows that all draws using that texture as the last state of that texture, disregarding state changes

This was very confusing as **I thought I had a bug** in code that tries to batch renders with the same texture.
I expected this to come out correctly (recognising that the texture changed to hold different data midway through the draw)

This is true of all places the texture can be viewed in the app as far as I can tell but it was most noticable to me in the frame viewer.
I also noticed that texture upload are not included in the event browser ... which perhaps might be helpful for debugging but thats a feature request rather than a bug

## Steps to reproduce

As far as I can tell you only need to structure code like this using opengl:
```c++
glBindTexture(GL_TEXTURE_2D, gl_texture);
glTexImage2D(...);
glDrawElementsInstanced(...);
glTexImage2D(...);
glDrawElementsInstanced(...);
SwapBuffers();
```
Original:
![image](https://user-images.githubusercontent.com/58116051/155579210-c79102de-0726-4bc7-af4b-bb74003e38fa.png)
Renderdoc:
![image](https://user-images.githubusercontent.com/58116051/155579060-e3fbb25c-94b2-4a4c-8933-198e7abecbf3.png)

## Environment

* RenderDoc version: v1.18
* Operating System: Windows 10
* Graphics API: Opengl 4.5

**Comment by baldurk** [comment]
For steps to reproduce, please share a specific and complete reproducible test case that I can use to investigate the problem, such as a capture or executable depending on what is most relevant to the bug. Without a repro case it can be difficult or impossible for me to replicate the situation you are running into, and it can easily waste time trying to reproduce a problem that is not as expected or described.

**Comment by Veeloxfire** [comment]
Ive just created a repo which is hopefully a reproducable test case. It has all the code needed to reproduce the the error on a windows machine as far as I can tell (window setup, opengl setup, vertex and fragment shaders, draw loop)

 https://github.com/Veeloxfire/Renderdoc-Bug-Example

**Comment by baldurk** [comment]
Thanks for sharing the repro, I see the issue now.

Your use of `glTexImage2D` to re-create a texture dynamically is not something I intend to support in RenderDoc. This allows textures to change in dimension or format mid-frame which would cause many complexities to handle and is not supported in any other sensible API. RenderDoc instead pushes all of these to load-time so only the last captured `glTexImage2D` has any effect.

If you initialise the texture only once with `glTexImage2D` and use the normal `glTexSubImage2D` to just update the texture contents this works as expected, or any other similar function that's intended for repeated update instead of one-time creation.

I also noticed you're using a very modern creation function (glCreateTextures) together with the legacy/deprecated mutable texture initialisation `glTexImage2D`. If you're not needing to use really old versions of GL I'd recommend using immutable texture initialisation like `glTexStorage2D` to get better error checking and more reliable behaviour.
