### ISSUE TITLE
3 errors when trying to capture

### ISSUE THREAD

**Issue by Decentrana1** [baldurk/renderdoc#2511]
![RenderDoc_DiagnosticLog_Error](https://user-images.githubusercontent.com/97415780/156616886-eafc65c0-91fb-44c1-ac43-0f4ae0222651.png)

I'm getting the following three (3) errors: 

"Couldn't allocate remote memory for DLL . . . " 
"Couldn't create toolhelp dump of modules in process 8432" 
" Can't locate renderdoc.dll in remote PID 8432" 

Diagnostic Log attached. Any help is much appreciated.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
