### ISSUE TITLE
Cannot have more than one debug path

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2521]
## Description

I have a debug shader path set, and renderdoc remembers it across runs. If I add another one, it remains there for the duration of the program, but forgets it if I close and reopen. It works if I edit the only path, just not adding a new one.

## Environment

* RenderDoc version: 1.18
* Operating System: Windows 10
* Graphics API: DX11

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by redorav** [comment]
I thought I'd filled this correctly, the steps to reproduce are in the description. I'll open a new one
