### ISSUE TITLE
Cannot have more than one shader debug path 

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2522]
## Description

I have a debug shader path set, and renderdoc remembers it across runs. If I add another one, it remains there for the duration of the program, but forgets it if I close and reopen. It works if I edit the only path, just not adding a new one.

## Steps to reproduce

1. Go to Settings > Choose Paths and add a second path (if you already have one)
2. Close renderdoc
3. Reopen and observe that the second paths isn't saved

![image](https://user-images.githubusercontent.com/700032/158397842-fc93058c-e6f9-4f3e-8d22-04c3946d3858.png)

## Environment

* RenderDoc version: 1.18
* Operating System: Windows 10
* Graphics API: D3D11

**Comment by baldurk** [comment]
Yeh this is a bug that someone else ran across a couple of weeks ago, it should be fixed in 60e1f865719c8c88644e548f66cbee3d1d4cfa8c so if you run a recent nightly build it will work and preserve multiple paths correctly. Unfortunately the bug will kick in if you run 1.18 (or any build before the fix) and remove the other paths from your config :(.

**Comment by redorav** [comment]
Ah I see! Alright no worries, for now I've just deleted the path I least care about, I can wait until 1.19, thanks for the quick turnaround!
