### ISSUE TITLE
Add OpenGL ES support

### ISSUE THREAD

**Issue by FslNopper** [baldurk/renderdoc#253]
Would be great, if we could see in a future version support for OpenGL ES.

**Comment by baldurk** [comment]
This would be feasible I think but there are a few different issues to unpack:

* Supporting GLES 1.0 is likely never going to happen, but I believe it's not really relevant anymore so that's probably OK.
* GLES 2.0 is certainly still relevant but it's more possible to support. AFAIK from a very loose understanding its deprecation of old functionality brings it close to a small subset of core profile GL 3.2, rather than still having loads of old compatibility profile features. The lack of features though might make some operations in renderdoc more difficult to implement.
* GLES 3.0 and above is probably much easier as it's comparable to desktop GL, but you still might run into some features that are more difficult to implement without compute in 3.1 for example.
* You could possibly get around the above issues with feature-lack by having some kind of emulation/shim layer that would actually create a desktop GL4.3 context and then just running the same commands with modifications to emulate GLES semantics. That depends a lot on how different GLES and GL are...
* So while I think most of the hard implementation work is likely already done, the most time consuming part of supporting GLES would be going through the specs to find out where it differs from GL. If there's already a comprehensive 'semantic diff' like this between GLES and any desktop GL version, that would save a lot of time.
* Using GLES on desktop is non-trivial I believe, relying on vendor extensions and such. Probably it's possible to support, but I don't know if anyone actually seriously uses GLES on desktop. So GLES support in RenderDoc would really only be a worthwhile investment when it supports mobiles. After that, possibly supporting desktop as well would be easy enough that you might as well.
* The one place GLES is relevant on desktop is WebGL. Supporting it isn't impossible, but would need some careful consideration and a bunch of legwork to hook up to the browser as necessary.

**Comment by FslNopper** [comment]
Thanks a lot for the analysis.

Actually I was thinking of OpenGL ES 2.0 and OpenGL ES 3.x. Did not think about ES 1.x. And probably OpenGL ES 3.x would be sufficient.

It would be great using renderdoc on mobile and/or embedded devices.

Does renderdoc need a minimum feature set from the GPU to work (without workarounds)?

**Comment by baldurk** [comment]
Yeh I figured people these days wouldn't be interested in ES 1.x, I just wanted to clarify :smile:. I know from Unity at least, ES 2 is still a large concern, but yeh potentially ES 3.x would make sense to start off with, then expand backwards as makes sense.

Support for mobile/embedded is definitely on the TODO list but it's lower down the priorities for me to get to. I think it's something that others might be looking into implementing support for. RenderDoc already has the concept of capturing and replaying remotely, so you could have a desktop host machine running the UI and doing the bulk of the work, and the remote target running ES just doing the basic replay.

RenderDoc uses compute for some analysis, transform feedback for fetching vertex outputs, and it will use SSBOs for pixel history/shader debugging when they are implemented. I also require some extensions like ARB_buffer_storage and EXT_direct_state_access but that's mostly for convenience rather than a hard requirement. There might be other things I'm using without consciously considering but in general those are the obvious things it requires over and above whatever the captured application uses.

It's worth noting though that the remote target architecture means that some of those features are only required on the desktop machine doing the analysis, so they wouldn't need to be implemented on GLES in the desktop-mobile scenario.

**Comment by FslNopper** [comment]
I was thinking of the host and target scenario.

I will have a deeper look at the source code and architecture of renderdoc.

Again, thanks a lot for clarifying things!

**Comment by baldurk** [comment]
There's a [presentation](http://renderdoc.org/RenderDoc_organisation_05_2014.pdf) I wrote up that covers the high level architecture. It should still be pretty accurate, and it also describes how the remote host and target organisation works. Good places to start in the code are [replay_driver.h](https://github.com/baldurk/renderdoc/blob/master/renderdoc/replay/replay_driver.h) for the interfaces implemented, and [replay_proxy.cpp](https://github.com/baldurk/renderdoc/blob/master/renderdoc/core/replay_proxy.cpp) for the implementation that runs the host/target bridge over the network.

If you have any questions, feel free to ask. Either here or drop me an email or something :smile:.

**Comment by adrianbu** [comment]
Just a quick notification on this thread... 

We have a preliminary OpenGL ES (2,3x)/EGL implementation for Android under evaluation currently.
It works in a similar fashion to the Android Vulkan support in terms of RenderDoc work flow and UI.

We hope to have it up for review soon (early next week).

**Comment by Atrix256** [comment]
RenderDoc for webgl (and webgl2 which should be on by default in chrome starting this month i believe?) would be amazing.

**Comment by englercj** [comment]
Looks like this hasn't been bumped in a while, and #445 was closed without comment. Is there an update on this?

**Comment by baldurk** [comment]
Yeh I hadn't updated here since it's not a small/simple thing that can just get marked as 'done' easily. However it's looking like the next release of renderdoc will have GLES support.

To clarify: #445 was closed due to being unmanageable, and instead the authors of that code at Samsung worked on making smaller changes to the shared GL codebase over the past year or so. At this point GLES3 capture and replay is looking to be in good shape, and I believe that is both on desktop and android but this is primarily aimed at android dev.

More updates will follow as v1.x gets stabilised into v1.0 hopefully soon.

**Comment by baldurk** [comment]
v1.0 has now been released, adding support for GLES2 and 3 on Android and Linux.
