### ISSUE TITLE
Error Unexpected enum as texture target: GL_TEXTURE_EXTERNAL_OES

### ISSUE THREAD

**Issue by SssWen** [baldurk/renderdoc#2531]
Description
Steps to reproduce
* I successfully connected,Remote server is ready,and launched the app.
then the app crash.

* RenderDoc version: 1.18
* Devices: Google Pixel4 Adreno 640/OpenGL ES 3.2

Android 7505 03:29:59 gl_driver.cpp(1345) Log Activating new GL context: Qualcomm / Adreno (TM) 640 / OpenGL ES 3.2 V@0490.0 (GIT@85da404, I46ff5fc46f, 1606794520) (Date:11/30/20)
Android 7505 03:30:00 gl_common.cpp(1323) Error Unexpected enum as texture target: GL_TEXTURE_EXTERNAL_OES
Android 7505 03:30:00 gl_hooks.cpp(158) Error Function glEGLImageTargetTexture2DOES not supported - capture may be broken
Android 7505 03:30:00 gl_common.cpp(1323) Error Unexpected enum as texture target: GL_TEXTURE_EXTERNAL_OES
Android 7505 03:30:00 gl_resources.cpp(1989) Error Unexpected target GL_TEXTURE_EXTERNAL_OES
Android 7505 03:30:03 core.cpp(1917) Log Removing frame capturer for 0xB4000070397AFA50 / 0xB40000714976CAF0
Android 7505 03:30:03 core.cpp(1926) Log Removed last refcount
Android 7505 03:30:03 core.cpp(1930) Log Removed active windo
![Bugpng](https://user-images.githubusercontent.com/37821777/160116682-5084e582-8093-4097-9437-ec928c8687d3.png)
w

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
