### ISSUE TITLE
Crash debugging UE4.26 shaders.

### ISSUE THREAD

**Issue by vito0719** [baldurk/renderdoc#2536]
## Description
RD tends to crash when debugging shaders with UE4.26. I switched back to RD1.18 and it's not crashing.

## Steps to reproduce
1. Set UE4 cvars to turn off optimizeation and keep debug info. Enable RD plugin in UE4.
2. Launch RD from UE4.
3. Find a drawcall and a pixel and click Debug, and debug...
5. Sometimes it shows some assembly-ish code and crashes right away (Usually UE shaders, like AO). Sometimes it shows hlsl source and doesn't crash until a couple of step over/intos (Usually user created shaders, Base Pass).

## Environment

* RenderDoc version: 1.19
* Operating System: Win10 21H2
* Graphics API: DX11

**Comment by jkinz3** [comment]
I can confirm that this crash isn't specific to Unreal Engine. It's happening with my own renderer as well.
I've tracked it down to the function `ShaderViewer::makeSourceVariableNode()`
In that function, the debug variables are retrieved and stored in a variable
`const ShaderVariable *reg = GetDebugVariable(r);`

The code then adds RDTreeWidgetItem entries in the `children` list declared at line 4438. But it only inserts an entry into the list if `reg->members` is NOT empty.
If it is, then the `children` list remains empty.

Then at 4639 this code is run
```
  for(RDTreeWidgetItem *c : children)
    node->addChild(c);
```
This adds the children in the node's member variable `m_children`.
Again, this does not occur if `children` is empty.

The crash occurs at line 4652
```
    for(uint32_t i = 0; i < childCount; i++)
      node->child(i)->setText(1, getRegNames(node, ~0U, i));
```
This is because the algorithm does NOT check to see if the node has any children before trying to iterate through them, thus leading to a crash.
Here is the output in the console when this crash occurs
>QTRD 026300: [17:58:24]            qvector.h( 427) - Fatal   - ASSERT failure in QVector<T>::operator[]: "index out of range", file A:\Git\renderdoc\qrenderdoc\3rdparty\qt\include\QtCore\qvector.h, line 427
The thread 0x8844 has exited with code 0 (0x0).

**Comment by baldurk** [comment]
This was an issue handling matrix source variables on D3D where each row/column of the matrix maps to a different register. That commit should fix the issue.
