### ISSUE TITLE
Threaded compression/decompression

### ISSUE THREAD

**Issue by ishitatsuyuki** [baldurk/renderdoc#2540]
## Description

RenderDoc's current compressor performs compression and decompression inside the same thread that is producing/consuming capture data. While this approach has the benefit of simplicity and not having to deal with threads and the overhead of it, it seems to be a bit underutilizing when the bulk of RenderDoc's (startup) workload is single-threaded.

A common alternative is to spin up a dedicated thread for compression and IO offload, and sending buffers to it from the main thread. This allows utilizing some power of the second core, and improves main thread's throughput.

This can also provide a sizable improvement for recompressing.

---

I'm thinking of implementing this and making a PR by myself, but while looking through the current stream processing code, I had a few questions:

1. What does the "backward window" in the reader do? It does not seem necessary since we only access data after the read head.
    https://github.com/baldurk/renderdoc/blob/4a43325693a70bea5b1ac0d7eead52a8746e5b6b/renderdoc/serialise/streamio.cpp#L212-L213
2. Is there a reason that both LZ4 and Zstd compressor do their own framing at a fixed decompressed size (64k/128k)? Seeking operations are not supported right now, and a large contiguous compressed stream can provide compression ratio benefits.
3. When there's not enough data in the buffer, the reader will resize the buffer before exhausting the current data in buffer.
    https://github.com/baldurk/renderdoc/blob/4a43325693a70bea5b1ac0d7eead52a8746e5b6b/renderdoc/serialise/streamio.cpp#L209-L234
    This has a bit of logical and processing overhead. Since the only caller of `StreamReader::Reserve` is `StreamReader::Read` and we have a destination buffer to directly put data into, what do you think of copying the remainder into that first so that we don't need to do the memmove() logic?

<summary>

**Environment**

</summary>
<details>

* RenderDoc version: 1c265bd1df661851f04059f8c39e2708b84795ae
* Operating System: Linux
* Graphics API: Vulkan

</details>

**Comment by baldurk** [comment]
I do keep an eye on performance, but the unfortunate fact is that I don't have the time to cover all aspects of the project especially when it comes to optimisations/improvements that aren't new features or better functionality. I'm sure there are gains to be made here but I don't know how large they are in practice so this hasn't been a priority to look at, especially considering the additional complexity and bug surface that would be involved. If there are good wins to be made here then I would welcome a PR - but I would say that it would have to be a sufficient improvement to justify that.

I'll answer the questions here, but I'm going to close this issue as using issues for general questions aren't good since there's no clear 'endpoint' as there can always be more questions. For future reference if you have general code questions like this for PRs you're working on it's better to use email or discord/IRC.

1. This is a legacy thing, and shouldn't have been ported over to the streamio system, it likely got missed in amongst the larger refactor. It's a holdover from when the serialiser was reading directly from the file and it used a limited amount of backwards lookback when processing chunk headers to read the chunk length after processing. As you point out though, with the StreamReader interface this is not possible so the window is no longer needed.
2. My understanding from their docs is that lz4/zstd require the previous data to remain in memory for each decompress/compress call, so the current scheme to double buffer with pages satisfies that. It was originally based on their example code. I'm not sure what you're suggesting to do instead.
3. That sounds like it would be fine, I think this is possibly also leftover from previous code and has been made redundant with refactors, since as you say we only go down the path to Reserve() when we know the current buffer will be entirely consumed and then more is required.
