### ISSUE TITLE
RenderDoc keeps constantly crashing at startup

### ISSUE THREAD

**Issue by TaaTT4** [baldurk/renderdoc#2541]
## Description

RenderDoc has suddenly crashed after trying to reset window layout to default and, since then, it doesn't start anymore. A while after having lauched it (the loading time seems a way longer now), I see a blank empty window and then it crashes:
![image](https://user-images.githubusercontent.com/7291478/161807192-d697795e-db5b-42b3-97af-7325c8e6cf0f.png)

Rebooting the PC, updating RenderDoc (from 1.18 to 1.19), fresh re-installing it, deleting config directory `~\AppData\Roaming\renderdoc` doesn't change a thing. It keeps constantly crashing. Please let me know if there's also something in the Windows registry or somewhere else that I can look for.

I presume it's something _just_ related to Qt/UI since RenderDoc core module works launching it in this way:
```.\renderdoccmd.exe capture S:\Lab\LearnOpenGL\bin\6.pbr\Debug\6.pbr__2.2.1.ibl_specular.exe```
![image](https://user-images.githubusercontent.com/7291478/161812412-0bdf9c61-a56e-477b-97e2-33fb95c8e91c.png)

This is the log file: [RenderDoc_2022.04.05_19.21.47.log](https://github.com/baldurk/renderdoc/files/8420507/RenderDoc_2022.04.05_19.21.47.log). Unfortuantely, the error message in log file is localized in italian, but it should be translated in:
```The current process has used all of its system allowance of handles for Window Manager objects```

## Steps to reproduce

1. Just launch RenderDoc;

## Environment

* RenderDoc version: 1.19 (1.18 when the problem occured for the first time);
* Operating System: Windows 10 Pro 19044.1620;
* Graphics API: N/A (NVIDIA GeForce GTX 1060; 512.15 driver version);

**Comment by baldurk** [comment]
Can you first back up the contents of `%APPDATA%\qrenderdoc`, then delete the file at `%APPDATA%\qrenderdoc\DefaultLayout.config` and see if that fixes the issue?

Please note, renderdoccmd is an **internal** tool only and should not be used directly by users.

**Comment by TaaTT4** [comment]
I'm sorry, but I was in a hurry with a thing and I desperately needed RenderDoc that I took the drastic choice to format and re-install the OS from scratch.
But you're lucky: I made a backup copy of my hard-drive before wiping it. Here is [DefaultLayout.config.txt](https://github.com/baldurk/renderdoc/files/8457464/DefaultLayout.config.txt). And I believe that the insanely long and empty `floatingWindows` array was the source of my issues.

**Comment by baldurk** [comment]
Thanks for sharing that file, the large number of empty floating windows is definitely the problem but unfortunately it's impossible to tell how it got into that state. Normally floating windows are destroyed after the last item in them is removed.

I don't see any path through the code where a floating window would become empty without being deleted and so not be around to be saved into the layout. I do see though that empty windows will be created when loaded and then saved out again because they're only deleted when a panel is actually removed from them, so however these did appear they would accumulate until it becomes a problem.

I can add protection though to skip loading any empty windows which do end up in the layout, which isn't perfect but should at least avoid this issue in future. I don't know how you are docking your windows or managing things, but if you're able to determine how to reproduce that layout file ending up with empty floating windows (even one would be enough to accumulate over time) please let me know.
