### ISSUE TITLE
VulkanDebugManager::CopyTex2DMSToBuffer doesn't respect minStorageBufferOffsetAlignment requirement

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2543]
## Description

Capturing MS textures on Turnip could trigger an assert in driver `Assertion (buffer_info->offset & 63) == 0 failed.` because the offset in `destdesc` is not a multiple of `minStorageBufferOffsetAlignment`:

https://github.com/baldurk/renderdoc/blob/8c57a14bede0980a4c990d056072dada24bcf91d/renderdoc/driver/vulkan/vk_msaa_buffer_conv.cpp#L96
https://github.com/baldurk/renderdoc/blob/8c57a14bede0980a4c990d056072dada24bcf91d/renderdoc/driver/vulkan/vk_msaa_buffer_conv.cpp#L160

On Turnip `minStorageBufferOffsetAlignment = 64`

## Steps to reproduce

Ugh, I caught this while running `arb_sample_locations` piglit test on Zink over Turnip. That's not an easy way to reproduce...

I don't have a good test at the moment to point at.

## Environment

* RenderDoc version: 8c57a14
* Operating System: Linux
* Graphics API: Vulkan
* GPU: Adreno A6xx (Turnip)

**Comment by baldurk** [comment]
Eyeballing it, it looks like it would be possible to reproduce with an odd-sized texture even on drivers with more forgiving alignment requirements. E.g. a 3x5 R8_UINT MSAA texture.

Probably the simplest fix is just to enforce 64 (or 256?) byte alignment between each sample, rather than trying to rejig or add different paths, that just means it's a bit of a leaky abstraction as the calling code needs to be aware to allocate enough buffer space and in the case of `GetTextureData()` do multiple memcpy's to tightly pack the data again.

Ping @tuxerr to look at this.

**Comment by baldurk** [comment]
The above PR from @tuxerr should fix this by refactoring the code such that the binding offset is always 0 and doing offsetting within the compute shader, but I don't believe either of us has access to hardware where this restriction could be properly tested so please let me know if it's not fixed.

**Comment by werman** [comment]
Seems to be working correctly, no crashes, no hangs.
