### ISSUE TITLE
Custom shader abstract bindings not found

### ISSUE THREAD

**Issue by berniegp** [baldurk/renderdoc#2561]
## Description
I'm following the instructions from https://renderdoc.org/docs/how/how_custom_visualisation.html to create a custom texture visualization shader. The new abstract bindings introduced in 3ac4bd0ebd4b64fbef67553e11fe89e127fef79f do not work for me (see below). Perhaps I'm missing a (potentially undocumented) step or there is a bug.

I unfortunately couldn't find an example of a fully formed custom shader using the new abstract bindings format to validate my usage.

## Steps to reproduce

Create a custom texture visualization shader.

This works as expected with the previous non-abstract bindings format.
```
uint RENDERDOC_TextureType;

float4 main(float4 pos : SV_Position, float4 uv : TEXCOORD0) : SV_Target0
{
    if (RENDERDOC_TextureType == 5)
        return float4(1,0,0,1);
    return float4(0,0,0,1);
}
```

This gives an error
```
// possible values (these are only return values from this function, NOT texture binding points):
// RD_TextureType_1D
// RD_TextureType_2D
// RD_TextureType_3D
// RD_TextureType_Depth
// RD_TextureType_DepthStencil
// RD_TextureType_DepthMS
// RD_TextureType_DepthStencilMS
// RD_TextureType_2DMS
uint RD_TextureType();

float4 main(float4 pos : SV_Position, float4 uv : TEXCOORD0) : SV_Target0
{
    if (RD_TextureType() == RD_TextureType_DepthStencil)
        return float4(1,0,0,1);
    return float4(0,0,0,1);
}
```

Error:
```
C:\Program Files\RenderDoc\main(14,26-52): error X3004: undeclared identifier 'RD_TextureType_DepthStencil'
```
Changing `RD_TextureType_DepthStencil` to a numerical constant (e.g. `5`), causes this error instead:
```
C:\Program Files\RenderDoc\main(14,6-21): error X3510: function 'RD_TextureType' missing implementation
```

## Environment

* RenderDoc version: v1.19
* Operating System: Windows 10
* Graphics API: D3D11

**Comment by berniegp** [comment]
The docs for the old syntax are available here: https://github.com/baldurk/renderdoc/blob/41d39b58cedb00fbba53e5eca09c81d19ad457c2/docs/how/how_custom_visualisation.rst

**Comment by baldurk** [comment]
This looks like an omission for D3D11/D3D12 where hlsl is natively consumed by the backend and doesn't have to be compiled to bytecode manually. That commit should fix it to work correctly for this case. Old shaders will still work due to backwards compatibility, but I don't recommend doing that and in particular care must be taken with HLSL shaders written in that style as they may fail catastrophically when used on vulkan.

Also for information there are custom shader templates available [in the contrib repository](https://github.com/baldurk/renderdoc-contrib/tree/main/baldurk/custom-shader-templates) which should work for the new v1.19 shader system (barring this bug).

**Comment by berniegp** [comment]
I didn't know about the contrib repository. That's very useful.

Might I suggest adding a link to it in this page: https://renderdoc.org/docs/how/how_custom_visualisation.html ?
