### ISSUE TITLE
Error Opening capture

### ISSUE THREAD

**Issue by zrp2016** [baldurk/renderdoc#2565]
Well,I downloaded one .rdc file from UPR as below
![image](https://user-images.githubusercontent.com/17512844/165259514-5aeef8aa-a564-4eab-be30-28406f4ef20d.png)
![image](https://user-images.githubusercontent.com/17512844/165259917-baa9db5f-52c9-47f1-910d-e2a57e7331bb.png)
As I doubleclick it,I got an error
![image](https://user-images.githubusercontent.com/17512844/165260128-4c3ad3de-c016-4dfb-ae7a-155e00e874d7.png)
whats going on?

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
