### ISSUE TITLE
Renderdoc crashes immediately on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by char8t** [baldurk/renderdoc#2568]
On a freshly installed Ubuntu 22.04 LTS Renderdoc crashes immediately on application startup:

```
marvin@Marvin-PC:~$ qrenderdoc 
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

It seems the crash is due to an error or bug in QT as other applications such as owncloud-client are also affected:

```
marvin@Marvin-PC:~$ lldb qrenderdoc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb.embedded_interpreter'
(lldb) target create "qrenderdoc"
Current executable set to 'qrenderdoc' (x86_64).
(lldb) run
Process 5127 launched: '/usr/bin/qrenderdoc' (x86_64)
Process 5127 stopped
* thread #1, name = 'qrenderdoc', stop reason = signal SIGSEGV: invalid address (fault address: 0x17)
    frame #0: 0x00007ffff6b7c73f librenderdoc.so`___lldb_unnamed_symbol17179 + 63
librenderdoc.so`___lldb_unnamed_symbol17179:
->  0x7ffff6b7c73f <+63>: testb  $0x40, 0x17(%rbx)
    0x7ffff6b7c743 <+67>: jne    0x7ffff6b7c970            ; <+624>
    0x7ffff6b7c749 <+73>: movdqu (%rbx), %xmm1
    0x7ffff6b7c74d <+77>: movaps %xmm1, (%rsp)
(lldb) 

```

Steps to reproduce:
* Install Ubuntu 22.04 LTS
* Install renderdoc via apt
* Start renderdoc

Environment:
* Ubuntu 22.04 LTS (x86_64)
* Renderdoc 1.18+dfsg-1

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
