### ISSUE TITLE
 Can't open a frame caputured.

### ISSUE THREAD

**Issue by defcool** [baldurk/renderdoc#2575]
## Description
I can't open a frame caputrued, there was such a message in the Diagnostic log: 
 "Error Can't verify the digital signature of the D3D12Core.dll embedded in capture, it won't be loaded. If the capture came from a trusted source and you want to load unsigned dll's, set D3D12.Debug.IgnoreSignatureCheck to true."
But I don't know how to set D3D12.Debug.IgnoreSignatureCheck to true.  can someone help me?

> 

> 

## Environment

* RenderDoc version: 1.19
* Operating System: Windows10
* Graphics API: d3d12

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by 10yac** [comment]
Tools->Settings->Core->ConfigerEditor->D3D12->Debug->IgnoreSignatureCheck
