### ISSUE TITLE
Renderdoc only reporting DX calls when using WGL_NV_DX_interop 

### ISSUE THREAD

**Issue by Gpinchon** [baldurk/renderdoc#2576]
## Description

When using WGL_NV_DX_interop to use DXGI SwapChain on OpenGL, RenderDoc reports DirectX context and doesn't see OpenGL operations.
[WGL-DX mapping tools](https://github.com/Gpinchon/OCRA/blob/d7d8abdf19fc8561f2029257bcb86333393be322/Driver/OpenGL/include/GL/Win32/WGLDXMapping.hpp)
[D3D "interface"](https://github.com/Gpinchon/OCRA/blob/d7d8abdf19fc8561f2029257bcb86333393be322/Driver/OpenGL/include/GL/Win32/D3DContainerInterface.hpp)
[D3D11 implementation](https://github.com/Gpinchon/OCRA/blob/d7d8abdf19fc8561f2029257bcb86333393be322/Driver/OpenGL/include/GL/Win32/D3D11Container.hpp)
[SwapChain "bridge" between OGL and DX](https://github.com/Gpinchon/OCRA/blob/d7d8abdf19fc8561f2029257bcb86333393be322/Driver/OpenGL/src/Win32/SwapChain.cpp)

The way it works :
- Create a SwapChain on Resize
- Register every DXGI buffers using wglDXRegisterObjectNV
- Acquire current back buffer (this locks the buffer using wglDXLockObjectsNV)
- Clear the buffer using glClearTexImage
- Present the result (this unlocks the buffer using wglDXUnlockObjectsNV)

You can find a test project showing the call sequence [here](https://github.com/Gpinchon/OCRA/blob/d7d8abdf19fc8561f2029257bcb86333393be322/tests/SwapChain.cpp#L116)

## Steps to reproduce

- Compile [this project](https://github.com/Gpinchon/OCRA)
- Launch UnitTests.exe with RenderDoc
- Do a capture and open it
- Only Present operation is here, no glClearTexImage

Capture file : [OCRA.zip](https://github.com/baldurk/renderdoc/files/8645404/OCRA.zip)

## Environment

* RenderDoc version: v1.19 (built from eb1e625b)
* Operating System: Windows 11 Pro 21H2
* Graphics API: Gigabyte RTX 3060 Ti EAGLE OC

**Comment by baldurk** [comment]
This is working as expected from your description and looking briefly at the program. You're using a D3D11 swapchain to delimit frames, so RenderDoc expects that you're capturing from D3D11 so it will capture from that API. In this case because there's no other D3D11 work the capture ends up empty.

I do not plan to ever support mixed captures containing work from multiple APIs. If you want to capture from the GL work instead you can either use an OpenGL swapchain and presentation in which case it will be captured automatically (or offered as an option if you have multiple windows with different APIs), or use the [in-application API](https://renderdoc.org/docs/in_application_api.html) to specify which device to capture from by starting and stopping it by hand.

**Comment by Gpinchon** [comment]
Well, that's clarified then thank you very much.
It might be a good idea to add that information to the api-support section of the README.md ?

It seems NSight is able to capture both GL and DX operations if I add a glFinish after presenting so I will stick with it for now.
I will take a look at the in-application API though 😊
