### ISSUE TITLE
Instrumented app crashes when glDepthRangedNV is used

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#258]
I just added a call to glDepthRangedNV to my game and it now crashes on a NULL deference when run via RenderDoc:

First-chance exception at 0x0000000000000000 in game.exe: 0xC0000005: Access violation executing location 0x0000000000000000.
Unhandled exception at 0x0000000000000000 in game.exe: 0xC0000005: Access violation executing location 0x0000000000000000.

Interestingly, if I directly look up glDepthRangedNV() via wglGetProcAddress(), then the game always works, even when hosted by RenderDoc. That is, if you change this #if 1 to a #if 0 then the game will crash when run via RenderDoc:

#if 1
	PFNGLDEPTHRANGEDNVPROC myDepthRangedProc = (PFNGLDEPTHRANGEDNVPROC)
		wglGetProcAddress( "glDepthRangedNV" );
	myDepthRangedProc( -1, 1 );
#else
	glDepthRangedNV( -1, 1 );
#endif

Runs in the debugger confirm that the symbol "glDepthRangedNV" is NULL when the game is hosted by RenderDoc. I'm using glew 1.13.0 for extension management, if that matters. Why would glDepthRangedNV be NULL when hosted by RenderDoc and not NULL otherwise? Thanks!

**Comment by baldurk** [comment]
I think this is because glew is doing the right thing and checking whether the extension is present before fetching the function pointers for glDepthRangedNV. Your code is not checking and calling the function anyway. I would guess that your code would crash on AMD or intel without renderdoc present where there is no function to call.

Here's what glew does:

```cpp
#ifdef GL_NV_depth_buffer_float
  GLEW_NV_depth_buffer_float = _glewSearchExtension("GL_NV_depth_buffer_float", extStart, extEnd);
  if (glewExperimental || GLEW_NV_depth_buffer_float) GLEW_NV_depth_buffer_float = !_glewInit_GL_NV_depth_buffer_float(GLEW_CONTEXT_ARG_VAR_INIT);
#endif /* GL_NV_depth_buffer_float */
```

RenderDoc does *not* report the GL_NV_depth_buffer_float extension, since I haven't hooked it and so it isn't supported (and so chances are the replay would be broken, and maybe worse things would happen like crashes at runtime depending on the extension).

For a kind of last-resort failsafe with buggy code to try and avoid crashes where possible, as well as just for information, RenderDoc returns a stub function for unrecognised/unhooked entry points that prints a log message saying that you're using an unsupported function and then forwards to the real thing.

**Comment by baldurk** [comment]
Closing this issue as there hasn't been activity in a while. Re-open if it's not clear what's wrong or if you think there's a RenderDoc bug here.
