### ISSUE TITLE
RenderDoc freeze adb if it try to bring the background RenderDoc app back to foreground in Android device

### ISSUE THREAD

**Issue by owuntu** [baldurk/renderdoc#2584]
## Description

Whenever RenderDoc exit on PC, and run another apps on the Android device, such as Facebook, Youtube, etc., RenderDoc app will be resided as background app. Then launching RenderDoc again on PC, will try to bring the app back to foreground, this will cause  adb freeze. Right now the workaround to break the freezing issue is stop the RenderDoc app on device physically. But for those working remotely (such as using Android screen mirror app [Vysor ](https://www.vysor.io/)), there is no way to get around because Vysor no longer being able to use adb to copy device's screen to PC.

## Steps to reproduce

* Have an Android device connect to PC
* (Optional) Open [Vysor ](https://www.vysor.io/), connect it to the device, showing the mirror screen of the device
* Launch RenderDoc on PC, connect it to device
![image](https://user-images.githubusercontent.com/3681042/168065955-a69c3c20-d654-476f-b18e-f6c7f2856f10.png)
* Launch an app from RenderDoc, here I am debugging a Vulkan app
* After the app successfully executing on the device, exit RenderDoc on PC (but not on the phone)
* Launch other apps on the phone (Facebook, Youtube, other games, etc.). Step here is to make sure the RenderDoc app on the phone is moved to the background.
* Launch RenderDoc on PC again. This time, adb will freeze (if you have Vysor mirroring the device's display, you can see the mirror screen freeze, and cannot be operated). Trying to connect the device from RenderDoc not works (it stuck in "Checking server status").

## Environment

* RenderDoc version: 1.19
* Operating System: Windows 10 Enterprise
* Graphics API: Vulkan
* Android device: Samsung Galaxy S22
* GPU: Xclipse 920

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
