### ISSUE TITLE
RenderDoc freeze adb if it try to bring the background RenderDoc app back to foreground in Android device

### ISSUE THREAD

**Issue by owuntu** [baldurk/renderdoc#2585]
## Description

Whenever RenderDoc exit on PC, and run another apps on the Android device, such as Facebook, Youtube, etc., RenderDoc app will be resided as background app. Then launching RenderDoc again on PC, will try to bring the app back to foreground, this will cause  adb freeze. Right now the workaround to break the freezing issue is stop the RenderDoc app on device physically. But for those working remotely (such as using Android screen mirror app [Vysor ](https://www.vysor.io/)), there is no way to get around because Vysor no longer being able to use adb to copy device's screen to PC.

## Steps to reproduce

* Have an Android device connect to PC via USB
* (Optional) Open [Vysor ](https://www.vysor.io/), connect it to the device, showing the mirror screen of the device
* Launch RenderDoc on PC, connect it to device
![image](https://user-images.githubusercontent.com/3681042/168065955-a69c3c20-d654-476f-b18e-f6c7f2856f10.png)
* Launch a device's app from RenderDoc, here I am debugging a Vulkan app
![image](https://user-images.githubusercontent.com/3681042/168189192-91918d3e-cfc4-41bb-93ec-8ea3ffd880cd.png)
* After the app successfully executing on the device, exit RenderDoc on PC (but not closing it on the phone)
* Launch other apps on the phone (Facebook, Youtube, other games, etc.). This step is to make sure the RenderDoc app on the phone is moved to the background.
* Launch RenderDoc on PC again. This time, adb will freeze (if you have Vysor mirroring the device's display, you can see the mirror screen freeze, and cannot be operated). Trying to connect the device from RenderDoc not works (it stuck in "Checking server status").

## Environment

* RenderDoc version: 1.19
* Operating System: Windows 10 Enterprise
* Graphics API: Vulkan
* Android device: Samsung Galaxy S22
* GPU: Xclipse 920

**Comment by baldurk** [comment]
This looks firmly like an adb bug. adb should never block on non-blocking commands, which after reproducing this issue is exactly what's happening.

Unfortunately in my experience adb is quite buggy and this is not too surprising. All I can suggest is trying to report the bug on the android side and see if it gets fixed, or see if there is some workaround like restarting adb. It might also be possible to workaround if you explicitly close the remote server via renderdoc before quitting the program, but I don't know what is causing adb to hang.
