### ISSUE TITLE
D3D12 Usage in Frame for Barrier

### ISSUE THREAD

**Issue by mickbeaver** [baldurk/renderdoc#2588]
Hello,

I found an odd edge case this week. If I executed a command list that contained nothing but a single call to `ID3D12GraphicsCommandList::ResourceBarrier()`, that barrier would not show up in the resource's "Usage in Frame." If I added other calls to the command list, such as `PIXBeginEvent()`, then the barrier usage would show up in the resources "Usage in Frame."

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
