### ISSUE TITLE
Issue capturing a frame with Unity 2021.3 (only) on Mali GPU

### ISSUE THREAD

**Issue by ronanbel** [baldurk/renderdoc#2594]
## Description

I'm trying to capture (renderdoc 1.19) a frame of a game using Unity 2021.3
The capture runs fine on TegraX1, Snapdragon GPU (**eternal thanks for making renderdoc**), but doesn't on Mali GPU
I tried on 2 devices.
Each time with a list of :
**Unmapped memory overlaps tiled-only memory region**
resulting in an unusable catpure
I don't know if it comes from Renderdoc, from Unity, from Mali drivers

## Steps to reproduce

I can't say if it is specific for my dev, or common to some Unity engine version.

## Environment

Renderdoc 1.19 official version
Windows 10 (latest) to run renderdoc
Android 10 Mali G72 vulkan driver r20p0

**Comment by baldurk** [comment]
For steps to reproduce, please share a specific and complete reproducible test case that I can use to investigate the problem, such as a capture or executable depending on what is most relevant to the bug. Without a repro case it can be difficult or impossible for me to replicate the situation you are running into, and it can easily waste time trying to reproduce a problem that is not as expected or described. If you don't provide me with any useful information then there's not really much I can do.

Please ensure that you have run your program on its own (not from RenderDoc) with API validation and have checked that your program does not produce any validation errors or warnings, since RenderDoc does not handle invalid API use. If you can't share your test case publicly due to privacy or NDA concerns you can contact me via email. If you're unable to share your test case even privately then please share as much information as you possibly can, and I'd suggest getting in touch via email so I can help to remote debug.

**Comment by baldurk** [comment]
Clarified over email that there is no RenderDoc bug or problem here.
