### ISSUE TITLE
Could not connect to target program issue when running vulkan application with renderdoc

### ISSUE THREAD

**Issue by Makogan** [baldurk/renderdoc#2600]
## Description
I have a program developed in vulkan and c++. I am able to run this program successfully form the terminal and get a correctly rendered window. Validation layers are enabled and silent, so is undefined behaviour sanitizers using ubsan. 

When i attempt to run the program through renderdoc version 1.20 I get this error:
![image](https://user-images.githubusercontent.com/17284362/171308567-674cbfa5-7c9f-4561-afa0-fd323c67a318.png)

There is a game loop, this program runs indefinitely until the window is closed. The program takes no command line arguments. 

I cannot share the program because it;s part of a research project subject to confidentiality clauses.

## Steps to reproduce
I have compiled the program under linux enabling undefined behaviour sanitizers as well as profiling symbols with the -pg flag. I then opened renderdoc, typed the address to the executable, the address to the expected working directory, and pressed launch. Renderdoc almost immediately launches the error message.

## Environment

* RenderDoc version: 1.20
* Operating System: Ubuntu 22.0
* Graphics API: Vulkan 1.3
* NVIDIA-SMI 510.73.05    Driver Version: 510.73.05

Things that may be causing issues: 

* Program uses tracy for profiling
* Part of the program is runtime loaded shared libraries
* the flag -pg is enabled in both linking and compilation
* program uses imgui
* program uses vma-allocator
* when renderdoc is launched through the terminal and the program is run, there is no output to the terminal, but the program is guaranteed to emit output to the terminal.

**Comment by baldurk** [comment]
If you can't share your program with me either here or privately I understand, but I'll need more information or help to remotely debug otherwise there's nothing I can do.

You mention using sanitisers but I'm unclear if you're saying you've tried both cases of using and not using them. Please try disabling them as I believe they are not compatible with RenderDoc's library injection. I'm not familiar with the -pg flag but it seems like some profiling related gcc option, I'd suggest trying to disable that too in case it is an issue. Also please check that if your program requires any specific environment variables that you have configured them too, as this kind of error is most often caused by an incorrectly configuration for launching the process.

If that doesn't work you would need to see if the process is failing to create entirely, or if it's crashing in early initialisation. Assuming you've configured it correctly to run it should be creating, so if you can configure your system to create core dumps you may be able to load that in a debugger and see why it's going wrong.

**Comment by Makogan** [comment]
It seems disabling profiling collection i.e. the pg flag solved the problem, thank you for the suggestion.
