### ISSUE TITLE
[Bug] RenderDoc crashes at rdcstr when glGetString(eGL_EXTENSIONS) returns null 

### ISSUE THREAD

**Issue by yhyu13** [baldurk/renderdoc#2601]
## Description

I've encoutered a nullptr error when loading RenderDoc for a version of Unity with opengles3.2 api on windows.

It happens when RenderDoc tries to get enabled extensions, I think RenderDoc should handle fail cases explicity instead of crashing the application:

As [winapi glgetstring](https://docs.microsoft.com/en-us/windows/win32/opengl/glgetstring) stated:

![msedge_WOBeIll1cL](https://user-images.githubusercontent.com/19365678/171836482-f8677550-d5d8-4802-8fa7-06fa4c8db2d8.png)

The crashe happens at here:

![devenv_cL5r1QlKPb](https://user-images.githubusercontent.com/19365678/171836565-a36f7521-ca31-406d-b30a-f19382325417.png)

where the copy constructor does not check if 'in' pointer is null. Thus crashing at ```strlen``` as it does not accept a nullptr.

![devenv_BlUGJhW4Ro](https://user-images.githubusercontent.com/19365678/171836700-a2f6e50c-d240-46cd-9e4e-2a8b037a63a0.png)

## Steps to reproduce

If glGetStringi is null, then RenderDoc would crash. 

To reproduce, you can comment out the branch under ```if(GL.glGetStringi && ctxVersion >= 30)``` and let it pass to use glGetString in [this line](https://github.com/baldurk/renderdoc/blob/c4b4c528a3d19af735009bb286b9455b38d3a6dd/renderdoc/driver/gl/gl_common.cpp#L438)

## Environment

* RenderDoc version: 1.21 (c4b4c528a3d19af735009bb286b9455b38d3a6dd)
* Operating System: win x64
* Graphics API: opengl es 3.2

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by yhyu13** [comment]
@baldurk Please do not close thie bug report.

I found it is a bug long found in GLEW, best described [here](https://github.com/nigels-com/glew/pull/24#discussion_r24985362). I've just print the error code and can confirm that ```glGetString(eGL_EXTENSIONS)``` returns error code ```GL_INVALID_ENUM```. 

This bug will persists if glGetStringi is null (where RenderDoc fallback to glGetString) which could be bad.

**Comment by baldurk** [comment]
Please open a new bug report and correctly fill out the issue template as requested above, specifically including steps I can follow to reproduce the problem - such as your program or any demo project that shows the problem.
