### ISSUE TITLE
Improved response to Vulkan device loss

### ISSUE THREAD

**Issue by meup** [baldurk/renderdoc#2605]
## Description

Recently RenderDoc's handling of device loss on Vulkan has improved considerably, to the point that now that just a couple more improvements could hugely improve RenderDoc's friendliness for certain use cases.

The feature I would like is, upon Vulkan device loss, the ability to automatically:
1) reinitialize Vulkan, and
2) reload the current capture, and
3) restore most of the UI state, except for the current event (to avoid a "boot loop")

It happens to me frequently that I'll be clicking around a capture and I'll select a draw event that causes a device loss.
This used to crash RenderDoc, but recently, it's improved significantly such that it gives an error and the UI remains running.
However, it does seem to leave the Vulkan driver in an unusable state, so restarting RenderDoc is still required before reloading.
Assuming this is fixed, the logical next step would be to automatically restore the state needed to get back to where I was right before selecting the bad draw event.
This may require some refactoring of the Vulkan device setup to allow it to happen an arbitrary number of times.

Presently, when I try to reopen a capture immediately after device loss, I get the message:
```
    Failed to open 'CaptureName.rdc' for replay

    Replaying the capture failed at the API level:Error creating logical device, VkResult:
    VK_ERROR_INITIALIZATION_FAILED
```

## Environment

RenderDoc version: 1.20
Operating System: Windows 10
Graphics API: Vulkan
Graphics GPU: Nvidia RTX 20xx

**Comment by baldurk** [comment]
This is not something I want to do, for various reasons. For one it would be too easy to trigger subsequent device lost events without knowing what the previous was caused by, there's certainly no guarantee that it is _always_ triggered by selecting an event or that the cause is deterministic. It also adds a significant amount of complexity and management trying to restore all of the user's state back to where it was. If the replay is not local it may not be possible to reset automatically at all. It is simpler and clearer (and so more robust) to ask the user to reload the capture _if_ they want to do that at all.

The desired behaviour is what is currently in place - if a fatal error is detected the UI remains running and notifies the user, and then if they want they can decide to close the now-defunct capture and re-open it. Generally a device lost error indicates a bug somewhere which should be investigated - either in the application if invalid/undefined work was captured, in RenderDoc if the analysis is causing undefined behaviour, or in the driver if the API use is not invalid at all.

The error you are seeing is not RenderDoc's responsibility, it's up to the nvidia driver which from what I've seen doesn't support re-initialising vulkan in a process where a device lost previously happened (I've also seen it hang infinitely trying to destroy the vulkan device/instance). On other drivers that don't have this behaviour the capture can be immediately re-opened. It's difficult to say if it's actually a bug, as the spec doesn't really say what happens in a device lost scenario especially when it is most often caused by undefined behaviour in the first place.
