### ISSUE TITLE
Self-built Android, unable to launch apps

### ISSUE THREAD

**Issue by AndyCGYan** [baldurk/renderdoc#2607]
## Description

Unable to launch apps on Android, on a self-built copy from the [v1.19](https://github.com/baldurk/renderdoc/tree/v1.19) tree. It finds the Android device and installs RenderDocCmd just fine, but when clicking Launch, it always warns...

    A running app on this device is already being captured with RenderDoc. First please close the app then try to launch again.

...despite no such apps / a fresh reboot / an entirely new device.

## Steps to reproduce

- Confirm that official v1.19 works on the target Android device, launching any chosen app
- Clone and checkout v1.19 source
- Build for Windows with Visual Studio 2022 + Build Tools 2015 (no retargeting or change to code whatsoever), OR just use the Windows client from official v1.19 (commit ID matches)
- Build for Android with Ubuntu
- With the built copy, try launching an app again, and the aforementioned warning blocks the way

Notably:

- It used to work ~1month ago (I've raised an issue before on opening captures, i.e. launching apps used to work), but for some reason fails now
- The problem is on the Android side - official Windows v1.19 + self-built Android v1.19 fails; self-built Windows v1.19 + official Android v1.19 works
- Tried adding a bit more log when self-building - it fails [this check](https://github.com/baldurk/renderdoc/blob/eb1e625b96bb2e9d43df4f8a2245438b29524721/renderdoc/serialise/streamio.cpp#L387), i.e. socket exists and is connected, but failed to receive even the required data

## Environment

- RenderDoc version: v1.19 (https://github.com/baldurk/renderdoc/commit/eb1e625b96bb2e9d43df4f8a2245438b29524721)
- Operating System: Windows 10
- Graphics API: OpenGLES

**Comment by AndyCGYan** [comment]
Set up my Android build environment anew (upgrading to WSL Ubuntu 22.04 in the process), and the problem seems gone for now. But since it happened out of nowhere, and resetting the environment takes quite some time, I feel I should remain alert. What should I look out for when it happens again?

**Comment by baldurk** [comment]
I don't think I can really be of help here. If it works in the official builds then I don't believe this is a bug in RenderDoc, and especially so if changing your build environment fixed it for you too. Unfortunately android is a completely terrible platform at every step so an unreliable build is not surprising, perhaps you were using a broken android SDK that somehow miscompiled (I can't imagine how) and are now using a different SDK?

The check for that error is straightforward - it tests connecting to the socket on the device and if it connects successfully then there's a program running on the other end, if it times out or gets a refused connection then there's not. Since the socket is connected by name and not pure port number to avoid android limitations, it shouldn't be possible for any other program to interfere by also listening on that socket.

**Comment by zakur0** [comment]
Wanted to update that had the same exact problem on an aosp (android open source) device and on an official device

AOSP - Android 12L aosp-oriole version on Pixel6  
fixed by running renderdoc on windows somehow, and deleting the RenderDocCMD from the device + reboot

Pixel6 Official - was fixed after unistalling both RenderDocCMD from the device and rebooting.

Renderdoc versions used: prebuilt tarball - v1.20 Linux  (the same problem appeared on  v1.17 - v1.20, but the fix happened on v1.20)
