### ISSUE TITLE
API cant activated

### ISSUE THREAD

**Issue by FrankDogdog** [baldurk/renderdoc#2609]
Dear all,

by using RenderDoc_1.20_64 I just couldn't find the API ...I am not sure if I am using the right word to describe...
I am following the instruction step by step. It works 2020 on my PC. But Today when I use the same PC then it dosen works anymore...
I tried the PC of my colleagues which is much older than I have, and it works...I dont understand why...
The Main issue I guess is that it shows API : none! (pls see attached images)
I also attachd the specification of my graphics card...

Any hints will be appreciated, thx in advance!

![image](https://user-images.githubusercontent.com/107257672/173067540-a861dc08-038a-4813-92e8-b7453aadd866.png)
![image](https://user-images.githubusercontent.com/107257672/173067579-05047e14-5f41-4a00-866a-5f8fa5dc817b.png)
![image](https://user-images.githubusercontent.com/107257672/173067650-20de3db8-ed93-49e3-8a7a-d0b70dbb72ce.png)
![image](https://user-images.githubusercontent.com/107257672/173067681-dec09a6a-1909-40bb-8212-5a5a86512074.png)
![image](https://user-images.githubusercontent.com/107257672/173067704-e045e7f9-d91f-40ba-9baa-2e90b2e6b80d.png)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
