### ISSUE TITLE
RenderDoc crashes on processing vkCmdPipelineBarrier2KHR

### ISSUE THREAD

**Issue by tquante** [baldurk/renderdoc#2627]
## Description

My application runs fine when when starting it outside of RenderDoc with no validation errors regarding synchronisation, but as soon as I start it via RenderDoc it keeps crashing on the first call of vkCmdPipelineBarrier2KHR with a nullptr exception. I loaded the pointer myself and the pointer is non zero pointing to RenderDoc dll. The function has been called with the following parameters:
```
      VkImageMemoryBarrier2KHR layoutTransissionBarrier = {};
      layoutTransissionBarrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2_KHR;
      layoutTransissionBarrier.pNext = nullptr;
      layoutTransissionBarrier.srcStageMask = VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT_KHR;
      layoutTransissionBarrier.srcAccessMask = 0;
      layoutTransissionBarrier.dstStageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT_KHR; 
      layoutTransissionBarrier.dstAccessMask = VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT_KHR; 
      layoutTransissionBarrier.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
      layoutTransissionBarrier.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
      layoutTransissionBarrier.srcQueueFamilyIndex = m_queueFamily.queueFamilyID;
      layoutTransissionBarrier.dstQueueFamilyIndex= m_queueFamily.queueFamilyID;
      layoutTransissionBarrier.image = m_swapChainImages[m_activeImage];
      layoutTransissionBarrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT ;
      layoutTransissionBarrier.subresourceRange.baseMipLevel = 0;
      layoutTransissionBarrier.subresourceRange.levelCount = 1;
      layoutTransissionBarrier.subresourceRange.baseArrayLayer = 0;
      layoutTransissionBarrier.subresourceRange.layerCount = 1;

      VkDependencyInfoKHR dependencyInfo = {};
      dependencyInfo.sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO_KHR;
      dependencyInfo.pNext = nullptr;
      dependencyInfo.dependencyFlags = 0;
      dependencyInfo.memoryBarrierCount = 0;
      dependencyInfo.pMemoryBarriers = nullptr;
      dependencyInfo.bufferMemoryBarrierCount = 0;
      dependencyInfo.pBufferMemoryBarriers = nullptr;
      dependencyInfo.imageMemoryBarrierCount = 1;
      dependencyInfo.pImageMemoryBarriers = &layoutTransissionBarrier ;

      vkCmdPipelineBarrier2KHR(cmdBuf, &dependencyInfo);
```
At first I assumed that the nullptr in the structs are a problem, but the Vulkan - Api states that if the corresponding count is 0 the pointer is not required to point to valid memory.

## Steps to reproduce

Unfortunately i cannot share the application due to NDA reasons. The crash location in renderdoc.dll can be seen in the attached picture
![RenderDocCrash](https://user-images.githubusercontent.com/2655704/175076495-d0537c06-e215-4cb9-843c-8f6286800f34.PNG)

## Environment

* RenderDoc version: 1.19 and 1.20
* Operating System: Windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Without a reproducible test case this will not be possible to investigate, the attached screenshot only shows that it's crashing in the driver underneath RenderDoc's code which could be caused by any number of things. It can't be as simple as any call to `vkCmdPipelineBarrier2KHR` crashing because [one of the nightly tests](https://github.com/baldurk/renderdoc/blob/v1.x/util/test/demos/vk/vk_sync2.cpp) tests this function with quite similar parameters and it works fine, and this is a common function to call for applications using VK_KHR_synchronization2 or vulkan 1.3.

Can you try modifying a public sample to demonstrate the bug and share that? You could use the demo above if that's convenient. I would also strongly recommend that you run your program with the validation layers to ensure you don't have any invalid API use, as RenderDoc will not be tolerant of that.

If it's possible to share the application or a minidump privately (perhaps under NDA) you can also [email me](mailto:baldurk@baldurk.org) to discuss it further.

**Comment by baldurk** [comment]
Discussed over email, this crash happens due to the validation layers not RenderDoc.
