### ISSUE TITLE
Can't launch app under certain conditions...

### ISSUE THREAD

**Issue by blitz-research** [baldurk/renderdoc#2638]
Hi,

I was initially having problems launching my WIP app in renderdoc, ie: I'd get that "Can't launch app, unknown renderdoc API" message that usually indicates the app has crashed due to bad working dir etc. But I could run the app find from the console.

This reminded my of a problem I used to have consistently when coding in QtCreator (moved onto CLion since), where GLFW3 based opengl apps (which mine is) would consistently crash within the IDE if launched in their own terminal window, but only in debug builds. The combo of Qt + Glfw3 + Debug is looking a bit suspicious to me.

So I tried a release build of my app instead of the debug build I had been using and it lauched fine, so I'm thinking that, since qrenderdoc is written in Qt, it could be the same underlying issue?

Anyway, it's probably not worth your time trying to track down, but maybe it's worth a mention in the docs to try to a release build if they get this error? If you do want to look into this further, I'd be happy to send you debug+release builds of my project, which is currently just a  spinning cube! 

Either way, I thought it was worth mentioning so thanks for your time and please close this whenever.

Bye,
Mark

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
