### ISSUE TITLE
"Global Hook" cannot work when renderdoc installed outside outside the c disk.

### ISSUE THREAD

**Issue by rockyvon** [baldurk/renderdoc#2645]
## Description

i cannot enable global hook when i install renderdoc in d disk.
i find that the path recorded in registry excludes the shim dll name: 
"![image](https://user-images.githubusercontent.com/19643272/177935113-77ac41ed-e673-4d40-956d-a0fb411b5652.png)"
when i click "enable global hook",and change value to "D:\RenderDoc\renderdocshim64.dll", it works.
after debug, i find that "GetShortPathNameW" returns wrong shortpath. when i move renderdoc to c disk, the function returns true path.
the function is used in BackupAndChangeRegistry function, win32_process.cpp.

## Steps to reproduce
1. install renderdoc to d disk;
2. run as admin, and enable global hook;
3. run target, and capture not work.

## Environment
* RenderDoc version: 1.17
* Operating System: win10, 64
* Graphics API: dx12.

**Comment by rockyvon** [comment]
when i expand buffer size, the result is true:
`c++
    rdcwstr shortpath(shimpathNative.size() * 4);
    LSTATUS ret1 = GetShortPathNameW(StringFormat::UTF82Wide(shimpathNative).c_str(), shortpath.data(),
                    (DWORD)shortpath.length());
`

**Comment by baldurk** [comment]
It seems like this can happen if RenderDoc is installed on a volume that doesn't have short names enabled. The global hook requires short names to be available to work reliably, so that commit will now show an error message to that effect and prevent the global hook from being enabled.

Note that the global hook should be used with care and it is virtually always better to launch your program directly from RenderDoc instead.
