### ISSUE TITLE
Looking at Textures while RenderDoc is on non-primary monitors hangs

### ISSUE THREAD

**Issue by AtomicBlom** [baldurk/renderdoc#2650]
## Description

When attempting to use the texture viewer or the mesh preview, if the application is not on my primary monitor, then the panes becomes unresponsive, and while I can visit other tabs, if I try to close the application, it application hangs must be killed forcefully.

## Steps to reproduce

1. Open RenderDoc
2. Load Overwhelmed-RenderDocBugCapture.rdc
3. Move RenderDoc to a non-primary window
4. Switch to the Texture Viewer

(Consider re-opening the texture viewer on your primary monitor to confirm it's working there)

Expected Results:
Textures are shown and I can close the application normally

Actual Results:
The panel containing the resource contains the contents of the preview view and doesn't re-render.  The application cannot be closed.

Capture file: (https://1drv.ms/u/s!Aqd0GRdPyzYskowSrWw1dm2kJ0lSKg?e=DBKRN0)

## Environment

* RenderDoc version: Tested on 1.20, 1.19, 1.16, and 1.10
* Operating System: Windows 11 22000.739 (21H1)
* Graphics API: OpenGL

* CPU: AMD Ryzen 5950x
* RAM: 128gb 3200
* MB: Asus ROG Crosshair VII Hero (Wi-Fi) v4201
* GPU: NVIDIA 2080ti (Driver 516.40 Game Ready)

**Comment by baldurk** [comment]
I'm not able to reproduce this, either on my primary machine (with three monitors, primary in the middle) or if I temporarily connect a second monitor to my windows 10 machine - the closest I can get to matching your OS. In either case it works fine for me.

This sounds to me like a systemic issue and not something to do with RenderDoc, since the handling of panel rendering is entirely independent of what monitor the window is on. If things were generally broken on multiple monitors this would be a common report.

I'd first recommend making sure you have the latest graphics drivers and try doing a clean driver reinstall using DDU. Also check that you have any OS updates applied and try a computer restart if you haven't. If you have any software installed that produces overlays or game bars or FPS monitors etc try disabling or uninstalling that to see if that makes a difference.

I'd also suggest doing some experimentation to see if you can narrow down the cause:

- Are you dragging a single window for the application, or are you dragging panels into separate windows and moving them? if one approach is triggering the hang, does the other also fail the same way?
- I'm unclear from your description if you can drag the window back onto the primary monitor and have it begin working again or not. Once it hangs, is it done forever?
- Do your monitors have different DPI settings, and if you set them temporarily to a normal DPI does that change anything?
- Does it behave differently if you change which monitor is primary, or the relative locations of the monitors?
- Your capture is an OpenGL capture. Do D3D11, D3D12, and Vulkan behave the same or do any of them work correctly?

If none of the above works then you could try building RenderDoc from source and attach a debugger, to see where it's hanging and if there is any information to be had that way. Unfortunately unless I can reproduce this all I can suggest are debugging steps like the above, but as I say given what you describe this sounds less likely to be a RenderDoc bug, unless it's something quite specific to your setup.

**Comment by AtomicBlom** [comment]
Thanks for your response.

I tried with a Vulkan experiment I had lying around and that seemed to work ok.

I just updated my graphics card driver, and have been experimenting with various system settings and it seems to be even more specific than I had anticipated.

While testing out the various DPI settings, I stumbled onto the fact that it ONLY hangs, when my LG Ultrawide is hooked up. I actually have four monitors, and it doesn't matter what combination of them I have enabled, if the LG is hooked up, then any of the non-primary monitors causes it to hang.

I think it's pretty safe to say this is a pretty damn esoteric error, and it's honestly not realistic for me to expect us to implement a fix, for one specific monitor, for one specific graphics API. I'll try to make a point of disabling that monitor while developing/debugging my game.

Thanks for your time

**Comment by baldurk** [comment]
Yeh I'd agree that it's probably not realistic to fix, especially if you have a workaround that you're happy with. With it being that specific I'd lean even harder towards this being a driver issue somewhere in the GL driver. I wonder if it's something like when the max desktop dimension/co-ordinate goes over a certain value (16k, if that's possible?) then presentation fails?

**Comment by AtomicBlom** [comment]
I thought that might be the case too, when I run with 2x2k monitors and a 1080p graphics tablet it's perfectly fine, but a single 2k monitor and the 2560x1080 ultrawide goes weird.

I'll just jot down a couple more answers to your question in case someone else just HAPPENS to also encounter this in the future.

I haven't customized the application at all, the layout is completely default, and the views are still embedded in their normal locations.

Dragging the application back to the primary does not resolve the issue.

I haven't tried changing the default monitor, or testing DirectX 11 or 12 APIs before parking this.

I also haven't tried hooking up a Debugger, it's a bit of a daunting prospect as I'm generally a C# developer and I'm not accustomed to native development beyond some really rudimentary C I wrote 10 years ago.

If anybody else finds this message, I pity you, try a different monitor.

And thank you so much @baldurk for RenderDoc, it's an amazing piece of software that has saved my sanity SO many times while I teach myself how this game dev thing goes.
