### ISSUE TITLE
Request to not require/fail when bufferDeviceAddressCaptureReplay is not supported (Vulkan)

### ISSUE THREAD

**Issue by meup** [baldurk/renderdoc#2653]
## Description

I am working with Vulkan with a device that supports bufferDeviceAddress, but not bufferDeviceAddressCaptureReplay.
RenderDoc fails to work in this case.  Despite the fact that the feature is not advertised, RenderDoc requests it, and CreateDevice fails.
(It returns a feature not present error.)

As far as I can tell, this feature isn't required by the code I'm working with.  However, since the app links in a VkPhysicalDeviceVulkan12Features struct, RenderDoc seems to automatically fall into the failure situation mentioned above.

I've asked the device vendor about supporting bufferDeviceAddressCaptureReplay, and while this has not been resolved yet, I'm sensing some resistance.  In any case, it would not happen soon.

Since the feature is optional, it seems like RenderDoc is in violation for demanding it when it isn't supported.  Could this be remedied please, such that RenderDoc won't request the feature if it's not supported?

As far as I can understand, the feature seems to only be required for ray tracing, which the device doesn't support anyway.  I also see that there are other potential uses, but again none seem to apply to the situation at hand.

## Environment

* Hardware device: (private)
* RenderDoc version: 1.20
* Operating System: (private)
* Graphics API: Vulkan

**Comment by baldurk** [comment]
You need to provide more information about your situation because the description is not accurate as stated. RenderDoc does work fine on systems that support `bufferDeviceAddress` and not `bufferDeviceAddressCaptureReplay` even when using vulkan 1.2, as my main dev machine is one of those. Some of my automatic tests enable vulkan 1.2 and use `VkPhysicalDeviceVulkan12Features` and they capture correctly.

You didn't say it explicitly but it sounds like you are describing a failure in the application being captured, when RenderDoc enables the capture replay feature as a dependency of the main feature being enabled. In the situation you describe though with only baseline support then `bufferDeviceAddress` should be reported as unsupported because `bufferDeviceAddressCaptureReplay` is unavailable, meaning the application should never enable it.

If the application behaves illegally and enables `bufferDeviceAddress` anyway even if it's not reported as supported, then the vkCreateDevice call would fail in the way you describe. Is your application doing this? Or are you seeing features be reported such that `bufferDeviceAddress` is available but `bufferDeviceAddressCaptureReplay` is not, while running under RenderDoc?

Also as an aside though it's not directly relevant, buffer device address certainly is not only used for ray tracing. It is a dependency for ray tracing (among other extensions), but it is much more useful a feature on its own than ray tracing.

**Comment by meup** [comment]
The application is enabling bufferDeviceAddress and it is not enabling bufferDeviceAddressCaptureReplay.

I see code in RenderDoc that enables bufferDeviceAddressCaptureReplay if it sees bufferDeviceAddress enabled.

As I indicated, the device supports bufferDeviceAddress, but not bufferDeviceAddressCaptureReplay.

The application works without RenderDoc enabled.

As an aside, I don't know why the application is requesting bufferDeviceAddress, since aside from setting the bits when making allocations and creating buffers, it never requests any addresses back.

**Comment by baldurk** [comment]
You didn't answer my questions. Does the application query for which features are available via a call to `vkGetPhysicalDeviceFeatures2` with `VkPhysicalDeviceVulkan12Features`? Does it see a returned struct with `bufferDeviceAddress` set to true showing that it is allowed to enable the feature?

**Comment by meup** [comment]
The application is calling vkGetPhysicalDeviceFeatures2 with a struct chain of VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2 and VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_KHR.

It records the available features, and passes this chain back to CreateDevice (linked from Create Info).

If the bufferDeviceAddress feature is enabled, it will set appropriate bits in allocate and buffer create requests.

**Comment by baldurk** [comment]
Those structs are different, so that does change things. Does the application check for the extension `VK_KHR_buffer_device_address` being listed as available before passing the `VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_KHR` chain to `vkGetPhysicalDeviceFeatures2`?

In the situation where the platform doesn't support the capture/replay feature, that extension should _not_ be listed as available from `vkEnumerateDeviceExtensionProperties` and so an application must not pass the feature struct to `vkGetPhysicalDeviceFeatures2`.

**Comment by meup** [comment]
Hmm, that may be the problem.

I'm not 100% sure what the app is doing, but if I run a test to list all the extensions, I see that VK_KHR_buffer_device_address is listed as available with the Khronos validation layer (which is available but not requested), but not listed as a base device extension or a RenderDoc capture layer extension.

**Comment by baldurk** [comment]
RenderDoc takes control over which extensions are reported as supported, and it will remove any extensions which it doesn't support at all as well as extensions which have conditional support that is not satisfied like this one.

A well written application *must* check for an extension being available before enabling it or trying to use any of its functionality.

**Comment by meup** [comment]
I think this is how the problem came up:

The spec states:
Support for the bufferDeviceAddress feature is mandatory in Vulkan 1.3, regardless of whether this extension is supported.

The application was written for a device that was known to have Vulkan 1.3 support, so that's probably why they didn't query the extension.

However, RenderDoc does this:
Vulkan feature bufferDeviceAddressCaptureReplay is not available. Clamping physical device [name removed] from reported version 1.3 to 1.2

Apparently, one cannot assume anything :-)

**Comment by baldurk** [comment]
No, or at the very least assumptions should be checked and asserted/fatal error'd.
