### ISSUE TITLE
Ubuntu 16.04 xenial build "fix"

### ISSUE THREAD

**Issue by MattGuerrette** [baldurk/renderdoc#266]
Currently there is a bug in the distrubuted version of GCC-5 which causes renderdoc to fail in linking.

Bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65612

It is apparently fixed in the GCC 6.0 Ubuntu toolchain ppa.

`sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
`sudo apt update`

Result after installation of GCC6 and building.

![screenshot from 2016-05-03 03-45-04](https://cloud.githubusercontent.com/assets/6388953/14977404/88b5f6f0-10e1-11e6-97f7-b4fdcf701925.png)

**Comment by baldurk** [comment]
It's not clear from the bugzilla, is there any distinct compiler error message you get when compiling/linking? If there's anything can you paste it here so that people google or github searching can find this issue.

Otherwise it seems like there's no sense trying to workaround it in code, so not much to do from renderdoc's side.
