### ISSUE TITLE
DX11 DrawAuto numVerts calculate error

### ISSUE THREAD

**Issue by Mario-Cui** [baldurk/renderdoc#2662]
## Description
Replay DrawAuto Cmd, Draw VertexCount Is Error

## Steps to reproduce
Use the following steps to reproduce this error
1. IA Set Primitive Topology Triangle list ,So Set Out Buffer, Then call Draw Command, Buffer hidden count is PrimitiveNum * 3
2. Set So Out Buffer To IA used as Vertex Buffer
3. IA Set Primitive Topology Triangle list, call DrawAuto Command,  numVerts  is NumPrimitivesWritten * 3, result is ok
4.  IA Set Primitive Topology Point list, call DrawAuto Command, numVerts  is NumPrimitivesWritten * 1, result is error

So, in my opinion, one should not use CurrentPipelineState IA Primitive Topology to calculate numVerts  

## Environment

* RenderDoc version: 1.20
* Operating System: win10
* Graphics API: dx11

**Comment by baldurk** [comment]
Your reproduction steps are not entirely clear and are not concrete, please share a capture or application showing exactly what the problem is so I can be sure I know what you're describing.

If you're saying that the current input topology is used for DrawAuto, then that is correct. According to the D3D11 specification:

> The primitive type for DrawAuto is the current primitive topology set via IASetPrimitiveTopology, regardless of the geometry shader output topology used while the buffer is filled.

**Comment by Mario-Cui** [comment]
[so_test.zip](https://github.com/baldurk/renderdoc/files/9164269/so_test.zip)
This is an intercepted rdc file

**Comment by Mario-Cui** [comment]
![nsight_capture](https://user-images.githubusercontent.com/53861236/180356458-2ee59281-3816-44a9-84e2-cd8590cf063f.PNG)
This is a screenshot captured using nsight

**Comment by baldurk** [comment]
I've clarified how this is intended to work and it indeed the hidden counter counts _bytes written_ rather than primitives generated as the query would imply, allowing you to do this kind of aliasing with topologies or even I think in theory different VB formats.

That commit fixes the issue, though in your case you will need to make a new capture as the hidden counter data saved from old versions is insufficient to accurately replay the case where you stream-out data in a previous frame and then use it in the captured frame.
