### ISSUE TITLE
Pixel history miss color values

### ISSUE THREAD

**Issue by Inori** [baldurk/renderdoc#2665]
## Description

![QQ截图20220723133641](https://user-images.githubusercontent.com/6732524/180592110-8e7b104c-4bd5-4be1-8b14-8102261b1637.jpg)

Like the image above, when I select a green pixel on the framebuffer and show it's history, there is no event result in a green value.
Such that I don't know why the pixel is green.

## Steps to reproduce
1. Uncompress and open the capture file I sent you via email.
2. Select EID 1353, which shoud be `vkCmdDrawIndexed(42, 1)`
3. Open Texture Viewer tab and select Outputs.
4. Pick any green pixel, and press History button.

## Environment

* RenderDoc version: V1.20 and  also nightly build RenderDoc_2022_07_22_ce60dd40_64
* Operating System: Windows 10
* Graphics API: Vulkan
* GPU: Nvidia GTX 1660Ti MaxQ

**Comment by baldurk** [comment]
This capture seems to contain undefined behaviour, in that the fragment shader is returning the contents of undefined variables. v[0] and v[4] are not always written into before being returned as the result, if the branch at SPIR-V ID 678 is false. Setting those explicitly to 0 in the else branch removes the artifacts, though the pixel history will still show some pixels as discarding when they wrote 0 (and I think sometimes vice-versa)

As best as I can tell the incorrectness in the pixel history comes from this undefined behaviour, it seems like depending on the way the shader is run sometimes the same pixels are discarded and sometimes not. My guess is that this is caused by using subgroup operations after the discard, and if the subgroup order is different then different pixels are discarded. If I remove the discard then the pixel history seems consistent.
