### ISSUE TITLE
Trying to build on RHEL8; can't find xcb-util-keysyms-develop

### ISSUE THREAD

**Issue by jcortell68** [baldurk/renderdoc#2675]
This is a shot in the dark. I'm trying to build RenderDoc on RHEL8. Dependencies.md shows the yum cmdline for Fedora. I figured it might equally works for RHEL8.

All the packages install fine except one:

```
# yum install xcb-util-keysyms-develop
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
cfengine                                                                                 65 kB/s | 2.1 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                    83 kB/s | 2.4 kB     00:00
EPEL8                                                                                    73 kB/s | 2.1 kB     00:00
ucs_sw_rhel8                                                                             78 kB/s | 2.1 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                 95 kB/s | 2.8 kB     00:00
hpsut_rhel8                                                                              77 kB/s | 2.1 kB     00:00
No match for argument: xcb-util-keysyms-develop
Error: Unable to find a match: xcb-util-keysyms-develop
```

I tried running the host-build cmake cmd and it confirms the missing dependency
```
-- Checking for modules 'xcb;xcb-keysyms'
--   Package 'xcb-keysyms', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:556 (message):
  A required package was not found
```

Again, a shot in the dark. Fully expect the ticket to be closed as it's not a bug.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
