### ISSUE TITLE
Cannot capture on Linux

### ISSUE THREAD

**Issue by manu-silicon** [baldurk/renderdoc#268]
I'm able to start my application using renderdoccmd -c but I'm unable to capture anything when pressing F12. I'm afraid that my program might be processing the F12 key. Is there a work around/suggestion to get capture working?

I'm using Ubuntu 14.04 x64

**Comment by baldurk** [comment]
You could try with the print screen key as well, perhaps?

I think keyboard input might currently be broken on linux if you're using X11, because I switched it over to xcb since that's what the early Vulkan samples were using. I will support either though once I get to implementing it.

FYI RenderDoc is still not particularly useful on linux, because while you can capture on linux you will still need windows to replay the log in a UI for analysis. If you do have a windows machine around though, you could also try `File -> Attach to Running Instance` and input the IP of your linux machine, then use the 'trigger capture' button. This will trigger a capture the same as `F12`/`PrtScrn` but also then copy the resulting log over the network to the windows machine for replay.

**Comment by manu-silicon** [comment]
Actually did not know about attaching to a different machine. It works great!!! 

The windowing I'm using is based on SDL which is using X11, so that might explains a few things.

Thanks a lot for your speedy answer!

**Comment by baldurk** [comment]
Great! :smile:

Getting a seamless linux user experience is a high priority but it's not ready yet. For now hopefully the windows UI should work fine as a stopgap.
