### ISSUE TITLE
No 'Inject into process' command under [file] tab ?

### ISSUE THREAD

**Issue by ongian1978** [baldurk/renderdoc#2685]
## Description

I've seen a report on this issue from about a year ago, but I still can't seem to get it to work.

## Steps to reproduce

>Downloaded RenderDoc (latest version - 1.2.1) for win64 and the tab for Inject into Process isn't there under [file]
>Downloaded an earlier version 1.0 and still no luck
>Watched heaps of youtube vids and googled solutions. Tried running as admin user, tried opening from app, from exe file. Tried installing from windows and launching from the zip file. 

## Environment

* RenderDoc version: 1.2.1
* Operating System: Win11
* Graphics API: unsure?

Sorry, not great at computers...they seem to outgrow me everyday. If I could get clear instructions for a a layman it would be great. Even right down to which button to press.

**Comment by baldurk** [comment]
The inject into process option was removed by default because it was causing confusion to new users who were trying to use it for no good reason and getting confused when it didn't work properly or broke.

You should launch your application from RenderDoc as normal and recommended, and that will be the most reliable and stable workflow.

**Comment by ongian1978** [comment]
I see... so this 'inject into process' function has been totally removed from the app. 
Thanks for the fast reply.
