### ISSUE TITLE
Move to `cmake-qt` for Building `qrenderdoc`

### ISSUE THREAD

**Issue by COM8** [baldurk/renderdoc#2687]
## Description
Modern CMake provides the [`cmake-qt`](https://cmake.org/cmake/help/v3.0/manual/cmake-qt.7.html) module. Currently renderdoc relies on an external invocation of `qmake` for compiling.

Using [`cmake-qt`](https://cmake.org/cmake/help/v3.0/manual/cmake-qt.7.html) would simplify building qrenderdoc drastically since then the whole process around specifying where to find the `qmake` command would be removed. Also it simplifies passing flags to compile targets.

The only issue is, that this would require at least CMake version 3.0 to be somehow functional.

In case this is something that you are happy to see in the future I can try to look into it.

## Environment

* RenderDoc version: v1.21
* Operating System: Linux Fedora 36
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I don't want to make this change, no. The qt project file is used so that qrenderdoc can be built in qt creator standalone, and I don't want to maintain three parallel build systems (default VS solution, qt project, and cmake).

It might be a really small simplification but mostly would move complexity from one place to another, and inevitably with linux some distribution will need new special considerations and flags because the new system of building won't work for them, and those will have to be discovered and fixed. Since the current build works well and is tested I don't see a compelling reason to change it.
