### ISSUE TITLE
Add default search path for missing #includes in D3D shader edit/replace

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#269]
In RenderDoc 0.29 when you select 'edit and replace' of a shader (either HLSL or GLSL, doesn't matter) if that shader has a #include directive that line is ignored, leading to build errors. Those build errors can be fixed by manually processing the #include - that is, by cut-and-pasting the #included file's contents into the edit window. Given that RenderDoc creates tabs for every #included file, displaying their contents, can the editor window implement the those #include directives eliminating this need to cut-and-paste? Thanks!

**Comment by jshofmann** [comment]
Actually, it appears this should be a bug report, not a feature request - the problem is that there's a #included file missing from the tab list. The missing file contains a set of #defines necessary for compilation. This could result from the use of nested #include files - the missing #include is the first #include in the top-level #include - that is, the file structure looks like this:

shader.psh:

#include "StdPSInclude.psh"

main() { ... }

StdPSInclude.psh:

#include "StdMacros.psh"
#include "StdConstants.psh"
#include "StdFunctions.psh"
// and other #includes...

Tabs are created in the edit-and-replace window for shader.psh and all #includes except for StdPSInclude.psh and StdMacros.psh. Since StdPSInclude is just a container for other #includes, its omission is not fatal, but the omission of StdMacros.psh creates build errors.

I'll send you a capture demonstrating the problem via email if you want.

**Comment by baldurk** [comment]
Yes in general #include files are supported but unfortunately this is a limitation that comes from the D3D compiler, there's not much I can do directly to fix it. I mention it in the [docs here](http://docs.renderdoc.org/how/how_edit_shader.html?highlight=contain+compiled+code#how-to-edit-a-scene-shader).

When the D3D compiler embeds source files in the PDB data, it only embeds files that contain code that was compiled. Presumably this is because it's only intended for looking up the source lines that correspond to assembly statements, not for recompiling the shader later.

Possibly I could add a fallback search path so that if an include file is completely missing, it searches some configurable folders on disk in order to try and locate it? It's not perfect but maybe better than nothing.

**Comment by baldurk** [comment]
Looking at this again, I believe the new SPDB debug info format used by modern fxc includes all files that were used in compilation regardless of their contents, even if it doesn't contain any code or only has comments or macro definitions.

The SPDB format is fully supported now, so there should no longer be any cases where files are missing that need a search path to locate them.
