### ISSUE TITLE
OpenGL Application Crashes in SetPixelFormat(...) (wingdi) on version 1.21

### ISSUE THREAD

**Issue by tlochner-rightware** [baldurk/renderdoc#2690]
I updated to RenderDoc 1.21 and some of my applications would crash on startup when launched through RenderDoc. I attached a debugger and found that it was crashing somewhere deep inside of a call to `SetPixelFormat()`. No errors or warnings are emitted in the Errors and Warnings window.

The callstack inside of `SetPixelFormat(...)` looks like this: 
![image](https://user-images.githubusercontent.com/48250479/184935699-949e4395-c1d0-489a-a2ed-cef2037e89dc.png)

Known Workaround: Reverting to version 1.20 makes the issue go away.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by tlochner-rightware** [comment]
Ooof. Sorry I didn't see any of the documentation about filing issues. The readme page has a link to create a new issue and there is no template pre-populated.

![image](https://user-images.githubusercontent.com/48250479/184939265-cffe20ee-d59f-431d-b87e-e9f044f6a666.png)

Perhaps this link should be removed or modified (maybe linking to https://github.com/baldurk/renderdoc/issues/new/choose ) from the readme page.
