### ISSUE TITLE
64 bit atomic support?

### ISSUE THREAD

**Issue by iiiwk** [baldurk/renderdoc#2700]
## Description

When I use Unreal Engine, if the renderdoc plugin is enabled, under the D3D12 API, it reports that 64 bit atomic is not supported, and when the plugin is turned off, it is supported. Is this normal? Will it be supported in the future?

## Environment

* RenderDoc version: 1.20
* Operating System: Windows 10 20H2
* Graphics API: D3D12
* Graphics card: AMD RX6700XT
* Graphics driver version: 22.7.1
* Unread Engine version: 5.0.3

without-renderdoc-plugin-enabled
![without-renderdoc-plugin-enabled](https://user-images.githubusercontent.com/84572644/186324121-e7bb6f89-cf03-425a-9f75-0b05b124577e.PNG)

with-renderdoc-plugin-enabled
![with-renderdoc-plugin-enabled](https://user-images.githubusercontent.com/84572644/186324130-1fd53ed3-21b0-4ee7-9fd9-a21f64e84677.PNG)

**Comment by baldurk** [comment]
This is an issue on Epic's side I believe. On AMD it uses AGS for 64-bit atomic extensions, but it seems to link directly to the static library which cannot be intercepted by RenderDoc to provide support properly, it must use amd_ags_x64.dll and the dynamic library to allow support through RenderDoc. This was reported a while ago but doesn't seem to have changed. It works on nvidia since it goes via the nvapi dynamic library.

I also noticed one other thing which is that it seems to require the `UAVBindSlot` feature which is only on DX12, even though it doesn't actually use it. That commit supports it though now, but this won't do anything and it won't work until UE5 uses the dynamic AGS library.

**Comment by iiiwk** [comment]
> This is an issue on Epic's side I believe. On AMD it uses AGS for 64-bit atomic extensions, but it seems to link directly to the static library which cannot be intercepted by RenderDoc to provide support properly, it must use amd_ags_x64.dll and the dynamic library to allow support through RenderDoc. This was reported a while ago but doesn't seem to have changed. It works on nvidia since it goes via the nvapi dynamic library.
> 
> I also noticed one other thing which is that it seems to require the `UAVBindSlot` feature which is only on DX12, even though it doesn't actually use it. That commit supports it though now, but this won't do anything and it won't work until UE5 uses the dynamic AGS library.

Thank you very much! I tried to modify UE to use the amd_ags_x64 dynamic link library and set `UAVBindSlot` to true and it works fine!
