### ISSUE TITLE
Capturing a simple application using `glBlitFramebuffer()` behaves strangely

### ISSUE THREAD

**Issue by OrichalcumCosmonaut** [baldurk/renderdoc#2707]
## Description

Capturing a simple application using `glBlitFramebuffer()` behaves strangely, specifically the texture viewer.
A capture of frame №0: has a backbuffer with a size of 1×1, only capturing the pixel at (0, 0), the renderbuffer with the gradient does get shown correctly though.
Captures of frames after: the backbuffer is the expected size, but if you look at the renderbuffer the gradient is stored in, it appears completely black, despite not having been `glClear()`ed.  The backbuffer is also completely black.
I’m not certain whether this is a bug, or me misunderstanding some aspect of framebuffers or renderbuffers; but visually, the program works as intended, showing the gradient square scaled 10×, so it seems like a bug.

## Steps to reproduce

Compile the attached C program as `cc $(pkg-config epoxy --cflags --libs) $(sdl2-config --cflags --libs) -o renderdoc-glblitframebuffer-mve main.c`, and capture it (there is a `.cap` JSON included, only needs the path to the executable to be modified).  There are also captures of the first 8 frames attached.

[renderdoc-glblitframebuffer-mve.zip](https://github.com/baldurk/renderdoc/files/9447106/renderdoc-glblitframebuffer-mve.zip)

## Environment

* RenderDoc version: v1.21
* Operating System: Void Linux
* Graphics API: OpenGL
* GPU: AMD Radeon RX 6600 XT
* Driver: Mesa 22.1.7
* `glxinfo -t -l -s` output: Attached

**Comment by baldurk** [comment]
I don't have a linux machine running to test this immediately but I believe I can see the problem looking at the source.

The backbuffer being 1x1 in frame 0's capture is expected, because GL is a badly designed API and the backbuffer is not very well defined. RenderDoc treats the backbuffer as being resized only at the time a present happens to 'snapshot' the association between a window and a context, since otherwise the backbuffer could change size mid-capture which is not feasible or useful to support. Since frame 0 is everything up to the first present, there's nothing to snapshot so the backbuffer is empty.

The renderbuffers are black because RenderDoc does not save the contents of renderbuffers from previous frames for subsequent frames. This is because renderbuffers in general are a pointless legacy holdover from decades ago before render-to-texture existed, and now the only realistic use is for framebuffer attachments which explicitly never need to be sampled from (basically just depth textures when only depth testing is needed). It is _possible_ to read from them as your sample proves, but this is awkward and not worth supporting in RenderDoc.

Tomorrow I can verify this is definitely accurate since as I say it's only from a surface reading of the small sample source.

**Comment by OrichalcumCosmonaut** [comment]
That seems to be correct, if I change `rbo_colour` to a texture it works fine, e.g. with:

```c
glGenTextures(1, &rbo_colour);
glBindTexture(GL_TEXTURE_2D, rbo_colour);
glTexImage2D(GL_TEXTURE_2D, 0, GL_SRGB8, 100, 100, 0, GL_RGB, GL_UNSIGNED_BYTE, NULL);
// …
glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, rbo_colour, 0);
```

That’s unfortunate but understandable, from what I understand about renderbuffers (mostly just the Khronos OpenGL wiki’s page on them, <https://www.khronos.org/opengl/wiki/Renderbuffer_Object>), considering I don’t need to sample it from a shader in this case, it seems like the more “correct” & possibly slightly more performant(?) option; but I can just add an option `--no-renderbuffers` to my game that uses textures instead for debugging, since apart from that they’re interchangeable.  At some point I will probably add Vulkan too, but one of the things I would like to try to support is at least slightly older hardware; e.g. until recently my main PC was ~10 years old with a GTX 750 Ti (I think) with no Vulkan support (or well, the proprietary drivers did IIRC, but they stopped working for some reason), but otherwise worked fine.

Thank you for responding so quickly, too.

**Comment by OrichalcumCosmonaut** [comment]
Also, a minor issue is that in the event browser, it says `glBlitFramebuffer(fbo, No Resource)` instead of (I assume) `glBlitFramebuffer(fbo, Backbuffer FBO)`

**Comment by baldurk** [comment]
As far as I'm aware the distinction is not significant and drivers do not do anything drastic with it, if they do anything at all. Especially since the blit you are doing is a scaling blit which likely means it's going to run through a shader and be sampled _anyway_, there's not likely to be anything a driver can do with the fact that 'technically' these can't be sampled from (except when they can).

Renderbuffers work fine in RenderDoc if you're using them as temporary storage - only if the contents are generated within the frame you're capturing. Generating them once and holding onto them indefinitely won't work as you've found, but while a niche number of GL programs use renderbuffers I have never seen a program that uses them for anything but discardable rendertargets, usually depth or maybe MSAA before a resolve.

The display of `No Resource` is an inevitable result of again OpenGL's terrible API design. At the time the parameter is serialised, it's serialised as no binding because it's '0', and this is only later replaced and identified as referring to the current backbuffer (which depends on the current context at the time).

Closing this then since it seems to be working as expected, and there are no plans to implement renderbuffer preservation.
