### ISSUE TITLE
I'm using renderdoc(1.21), ue5 and D3D12, but the shader debug button is disabled.

### ISSUE THREAD

**Issue by Lunewcome** [baldurk/renderdoc#2710]
## Description
As the title says, I'm using renderdoc(1.21), ue5 and D3D12, but the shader debug button is disabled.
![image](https://user-images.githubusercontent.com/4586049/187589552-ba88f11f-927d-445a-90f5-902062b0ea67.png)
![image](https://user-images.githubusercontent.com/4586049/187589611-9d9df4bd-93eb-45b7-9b93-2b52dbd4d694.png)

## Steps to reproduce
1. capture frame by clicking renderdoc plugin button in ue5
2. select event "Light::StandardDeferred" in renderdoc. The EID is 4104-4120
3. select SceneColor in Outputs and right-click the 'Cur output 0 - SceneColor' which display it in 'Pixel Context'
4. then it does displays, but with both 'History' and 'Debug' buttons disabled.

## Environment
OS: windows 10
RenderDoc version: 1.21 (built from 98a93408)
Graphics API:  D3D12

Looking forward to any help.

**Comment by baldurk** [comment]
Pixel history is not supported on D3D12. If the shader debug button is not available that is because your shaders are using DXIL, which is not supported for debugging, only normal DXBC shaders.

In either case, hovering the mouse over the button will show the reason for it not being available in the tooltip.
