### ISSUE TITLE
Renderdoc crashing on opening capture

### ISSUE THREAD

**Issue by Jark5455** [baldurk/renderdoc#2717]
## Description

Opening a capture results in the renderdoc crashing with the following error

```
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

## Steps to reproduce

Compile and run [this](https://github.com/Jark5455/BananEngine) application or load [this](https://anonfiles.com/qaW7O067yb/drug_rdc) capture

~30% of the captures made with the application end up being bad captures that cause the error. The file attached is an example of one of the captures when an error occurs.

## Environment

* RenderDoc version: 1.21-1
* Operating System: Arch Linux
* Graphics API: Vulkan

GPU - RTX 2060 Super w/ proprietary drivers
CPU - AMD Ryzen 3600
RAM - 16gb @ 3200mhz

**Comment by baldurk** [comment]
This appears to be caused by invalid behaviour in the application. A descriptor set layout is created with multiple bindings specified with `VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT`. In fact one has some invalid bits set:

```
<array name="pBindingFlags">
  <enum typename="VkDescriptorBindingFlags" string="VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT | VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT | VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT">13</enum>
  <enum typename="VkDescriptorBindingFlags" string="VkDescriptorBindingFlagBits(0)">0</enum>
  <enum typename="VkDescriptorBindingFlags" string="VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT | VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT | VkDescriptorBindingFlagBits(32720)">32729</enum>
</array>
```

As a result RenderDoc writes off the end of an array on replay since it is only handling a single variable sized descriptor array, and it crashes.

The [vulkan spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-03004) says that only the highest binding value should be variable sized, all others must not have this bit set. Looking at [the relevant code](https://github.com/Jark5455/BananEngine/blob/master/banan_descriptor.cpp#L38-L39) it seems that you are passing a single value as an array, which explains the invalid bits as it is reading garbage memory.

I tried to run the program, but I couldn't since the repository was missing necessary assets.

You should run your program with the vulkan validation layers as they do check for this, and fix the problems they find. RenderDoc does not handle invalid API use and you are expected to have checked for errors like this before using RenderDoc (or at least when you encounter problems). Though in this case it's possible due to reading garbage memory that the problem would not always be detected, since it depends on whether or not the other values of those flags after the first contains the relevant bit.
