### ISSUE TITLE
Crash when opening snapshot

### ISSUE THREAD

**Issue by kikonen** [baldurk/renderdoc#2723]
## Description

When opening snapshot, renderdoc crashes, in intel iris plus graphics laptop. Same app with desktop with nvidia gtx 970 does not crasah opening snapshot. Tested and this seems to occur with any version of renderdoc (including current github head version)

Ran renderdoc in visual studio debugger and seeing that crash seems to happen in,

WrapperOpenGL
````
    // use ARB_direct_state_access functions here as we use EXT_direct_state_access elsewhere. If
    // we are running without ARB_dsa support, these functions are emulated in the obvious way. This
    // is necessary since these functions can be serialised even if ARB_dsa was not used originally,
    // and we need to support this case.
    GL.glClearNamedFramebufferfv(framebuffer.name, buffer, drawbuffer, value);
````
>>> crash at this point

"Exception thrown at 0x00007FFFB4FDDF10 (ig11icd64.dll) in qrenderdoc.exe: 0xC0000005: Access violation reading location 0x0000000000000098."

![image](https://user-images.githubusercontent.com/478935/190012751-7c1bae20-acb0-4609-944b-e1a6b8298e15.png)

## Steps to reproduce

Try to open snapshot with latop with intel iris plus graphics adapter, created with same laptop with same version of renderdoc.
=> crashes always

I can provide app with debug build and or capture producing crash if it helps to reproduce issue.

## Environment

renderdoc doesn't seem to matter much, but above error I reproduced with cset 336e90d412879c69323ec318b944a0f38736e436 (i.e. all version what I've tried have now crashed)

* RenderDoc version: cset 336e90d412879c69323ec318b944a0f38736e436
* Operating System: Windows 11
* CPU: i7-1065G7
* Graphics API: Intel Iris Plus Graphics
* Intel driver: v27.20.100.9365 (newer version didn't help)

Since I've now situation happening and can reproduce error in debugger, I will peek a bit into it, in caseI would be able to gain more insights out of it.

**Comment by baldurk** [comment]
For steps to reproduce, as detailed in [the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) please share a specific and complete reproducible test case that I can use to investigate the problem, such as a capture or executable depending on what is most relevant to the bug. Without a repro case it is usually impossible for me to replicate the situation you are running into, and it can easily waste time trying to reproduce a problem that is not as expected or described.

Please ensure that you have run your program on its own (not from RenderDoc) with API validation and have checked that your program does not produce any validation errors or warnings, since RenderDoc does not handle invalid API use. Make sure that you have updated your drivers and if you have a different GPU or hardware available try testing on that to eliminate your hardware as a potential problem.

If you can't share your test case publicly due to privacy or NDA concerns you can contact me [via email](mailto:baldurk@baldurk.org).

**Comment by kikonen** [comment]
For curiosity's sake I simply commented out that line hitting crash; and after that snapshot opened. However, it's not clearly not working properrly since this is being constantly hit

GLReplay
```
    if(status == 0)
    {
      char buffer[1025] = {0};
      drv.glGetProgramInfoLog(feedbackProg, 1024, NULL, buffer);
      RDCERR("Failed to fix-up. Link error making xfb vs program: %s", buffer);
```
=> "Out of resource error.\n"

![image](https://user-images.githubusercontent.com/478935/190017151-5d29fb82-56aa-48d0-b8d0-57b2ec7f0a0b.png)


=> I need to dig into this a bit more

**Comment by kikonen** [comment]
okey, got more info, which might be useful

**With renderdoc 1.20**

1) https://drive.google.com/drive/folders/1Vf5dMg7Z_aEUmth_SfOWVlkwWhGj7UJE?usp=sharing
- one of them crashes with this intel setup, other one does not
- there is only *single* line difference

https://github.com/kikonen/learnopengl/commit/caf28a46eb0be318d59006d0054be3dadfa1e65b
TAG: renderdoc_no_crash => does not crash
TAG: renderdoc_crash => does crashes

App itself is runnable via Visual Studio

**Comment by baldurk** [comment]
This looks like a driver bug to me, crashing on a dubious/incorrect API call.

The `glClearBufferfv` call that's crashing is using a framebuffer which is set up using a previous `glDrawBuffers` call to point to `GL_COLOR_ATTACHMENT0`, `GL_COLOR_ATTACHMENT1` as draw buffers, and is clearing draw buffer 1 in the clear call. However the framebuffer has nothing attached at color attachment 1, it only has color attachment 0 and a depth-stencil attachment.

Strangely looking at the GL spec this isn't specified as an error condition, so I guess it's intended to silently do nothing. Regardless though the driver should not crash - on AMD and nvidia the call is silently dropped.

**Comment by kikonen** [comment]
Forgot to mention, I managed to see api validation error on that line with my hack compiled (see in my comments, commented out one line on renderdoc code) version of renderdoc, thus was able to figure it out. With version without my hack I was not just able to get so far as to see problem (due to renderdoc crash)
