### ISSUE TITLE
fix Serialise_glPointParameteri calling follow issue

### ISSUE THREAD

**Issue by bigPillowOMG** [baldurk/renderdoc#2750]
The chunk of glPatchParameteriEXT and glPatchParameteriOES should be followed via Serialise_glPatchParameteri not the function of Serialise_glPointParameteri

diff --git a/renderdoc/driver/gl/gl_driver.cpp b/renderdoc/driver/gl/gl_driver.cpp
index 4b0219ed2..b1c6a6f2d 100644
--- a/renderdoc/driver/gl/gl_driver.cpp
+++ b/renderdoc/driver/gl/gl_driver.cpp
@@ -4310,12 +4310,12 @@ bool WrappedOpenGL::ProcessChunk(ReadSerialiser &ser, GLChunk chunk)
     case GLChunk::glMinSampleShadingOES:
     case GLChunk::glMinSampleShading: return Serialise_glMinSampleShading(ser, 0);
     case GLChunk::glRasterSamplesEXT: return Serialise_glRasterSamplesEXT(ser, 0, 0);
+    case GLChunk::glPatchParameteriEXT:
+    case GLChunk::glPatchParameteriOES:
     case GLChunk::glPatchParameteri: return Serialise_glPatchParameteri(ser, eGL_NONE, 0);
     case GLChunk::glPatchParameterfv: return Serialise_glPatchParameterfv(ser, eGL_NONE, 0);
     case GLChunk::glLineWidth: return Serialise_glLineWidth(ser, 0);
     case GLChunk::glPointSize: return Serialise_glPointSize(ser, 0);
-    case GLChunk::glPatchParameteriEXT:
-    case GLChunk::glPatchParameteriOES:
     case GLChunk::glPointParameteri: return Serialise_glPointParameteri(ser, eGL_NONE, 0);
     case GLChunk::glPointParameteriv: return Serialise_glPointParameteriv(ser, eGL_NONE, 0);
     case GLChunk::glPointParameterfARB:

**Comment by bigPillowOMG** [comment]
![image](https://user-images.githubusercontent.com/105406910/195239434-0cc92340-25e1-4c93-8b21-92f14069addf.png)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
