### ISSUE TITLE
D3D11_CreateReplayDevice failed on Intel UHD Graphics 630

### ISSUE THREAD

**Issue by shiguowang** [baldurk/renderdoc#2753]
## Description

I want to try renderdoc on my desktop, but it can't initialize, I can create device like this:
![image](https://user-images.githubusercontent.com/3189971/196083139-97a5f710-2624-4a63-8bba-d54fe93f938c.png)
but it failed use renderdoc
![image](https://user-images.githubusercontent.com/3189971/196083397-22983607-d991-4d80-9c55-0b301e919152.png)
the problem is "The application requested an operation that depends on an SDK component that is
missing or mismatched".

## Environment

* RenderDoc version: Date:   Fri Oct 14 20:50:51 2022 +0100 commit d024f062c2d5c337a72adcde101480e87a579989
* Operating System: windows 10
* Graphics API: XXX

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
