### ISSUE TITLE
D3D11_CreateReplayDevice failed when Initialization

### ISSUE THREAD

**Issue by shiguowang** [baldurk/renderdoc#2754]
## Description

I try to use visual studio 2017 to compile latest code and run RenderDoc on my desktop. But it failed.
The error is "Couldn't create any compatible d3d11 device.\n\nDevelopment RenderDoc builds require D3D debug layers available, ensure you have the windows SDK or windows feature needed."
In addition,  I find the code fail when call D3D11_CreateReplayDevice of d3d11_replay.cpp

## Steps to reproduce

Run RenderDoc under visual studio 2017 debug mode
![image](https://user-images.githubusercontent.com/3189971/196173725-1cb2155b-58e4-4ceb-bfe5-feff96b2116f.png)

In addition I call function D3D11CreateDevice  successfully in other sample code on my desktop

![image](https://user-images.githubusercontent.com/3189971/196173226-cd3f003b-afa1-4b53-9dc5-0a7ef4052476.png)

## Environment

* RenderDoc version: 1.22, also on latest HEAD
* Operating System: win10
* Graphics API: D3D11
* GPU: Intel UHD Graphics 630)

**Comment by shiguowang** [comment]
@baldurk please correct me if i don't make a good isssue again, thanks.

**Comment by baldurk** [comment]
The error message that you quoted explains exactly what the problem is. Debug builds of RenderDoc require that you can enable D3D debug mode, which needs either the windows SDK or debug features depending on your version of windows (for windows 10 you will need to google for the steps as they are unnecessarily complicated).
