### ISSUE TITLE
vkEnumeratePhysicalDevices ignores spec, can overwrite memory

### ISSUE THREAD

**Issue by brianosman** [baldurk/renderdoc#2766]
## Description

After getting surprising crashes while running the Vulkan version of our application inside RenderDoc (1.22), I debugged to understand what was happening. We're actually getting stack smashing when RD is involved. This appears to be because of the implementation of vkEnumeratePhysicalDevices, which disregards `pPhysicalDeviceCount`, and always copies the number of underlying devices to the client [1]. That differs from the spec [2], which says: "If pPhysicalDeviceCount is less than the number of physical devices available, at most pPhysicalDeviceCount structures will be written, and VK_INCOMPLETE will be returned instead of VK_SUCCESS, to indicate that not all the available physical devices were returned."

I'm testing on Linux, but this seems like a universal problem.

[1] https://github.com/baldurk/renderdoc/blob/86807180d14c7982011cca066e3985730db49347/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp#L1505
[2] https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkEnumeratePhysicalDevices.html

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
