### ISSUE TITLE
Replay captured rdc file on Samsung S22 cause crash

### ISSUE THREAD

**Issue by Zieng** [baldurk/renderdoc#2773]
## Description

Open the capture file on samsung s22 will fail because the renderdoccmd crashed.
The render doc shows:
![image](https://user-images.githubusercontent.com/9816923/201819010-be367310-2d28-4e6d-be50-9fff5cd80e3b.png)

The adb logcat shows:
![image](https://user-images.githubusercontent.com/9816923/201818935-b734ee9a-d855-428b-9152-6e38e3dce622.png)

## Environment

* RenderDoc version: 1.18
![image](https://user-images.githubusercontent.com/9816923/201818714-605b9be2-2cd6-41a4-ac5b-3c0828941d31.png)

* Operating System: Win10
* Graphics API: Vulkan
* Android System:  GLES: Samsung Electronics Co., Ltd., ANGLE (Samsung Xclipse 920) on Vulkan 1.1.179, OpenGL ES 3.2 ANGLE git hash: c7c78c41d520

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly completing the prompted sections. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) which is linked from the template you used and open a new issue which does fill out the sections properly. Do not reply to this issue with more information, please open a new issue.

As detailed in the documentation and evident by the section title, for "steps to reproduce" you must actually provide steps I can take to reproduce the problem. Most commonly and simplest for everyone would be for example sharing your application or a capture file that shows the problem. If you can't share these publicly you can [email me privately](mailto:baldurk@baldurk.org?subject=RenderDoc%20bug%20repro%20case) with a google drive/dropbox/etc link. If you can't share these even privately you should say that and provide a significant amount of information about what you are doing so I can hope to construct a reproducible test case, or suggest further diagnostic steps. If you don't do any of this your bug report is unlikely to be useful and will be closed like this one.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

As linked above and in the issue template you were provided with there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
