### ISSUE TITLE
Need a way to inspect integer values in SPIR-V debugging (Vulkan)

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#2784]
## Description

This is almost the same problem as #128 except that such ticket applied to HLSL debugging.

The problem with SPIR-V debugging is that I am met with this:

![RD](https://user-images.githubusercontent.com/3395130/204160422-c0a24154-82e5-4806-887f-a53c3abc14b9.png)

RenderDoc says the value of `_90` is 1.00

However as I can later find out, it's most likely be 0.99999999... which is the problem I'm trying to debug.

If I right click I see "Integer register display". However toggling that doesn't seem to do anything

![RD02](https://user-images.githubusercontent.com/3395130/204160527-fdf34042-8311-4197-a52d-df7ba6cba163.png)

Having the ability to see the values of all registers reinterpreted like it is possible in HLSL would be of great help:

![HLSL](https://user-images.githubusercontent.com/3395130/204160610-3342c844-c9ca-4469-b8b5-110151f93a74.png)

## Environment

* RenderDoc version: 1.20
* Operating System: Xubuntu 20.04 LTS
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That option is only used for DXBC shaders because DXBC shaders actually have registers that are typeless and it can't be reliably determined what type the data actually is. It's not used for SPIR-V or any other shaders where there are no registers and they are fully typed, I'll look into hiding it.

The shader viewer respects the normal [global RenderDoc options](https://renderdoc.org/docs/window/settings_window.html#general-options) for formatting floats, so if you want to change the precision visible to determine ULP differences you can increase the 'maximum decimal places on float values' the same as you would to see that difference in the texture viewer.

If you want to reinterpret a value to see the bitwise pattern you can use [the watch window](https://renderdoc.org/docs/how/how_debug_shader.html#debugging-displays), and add the value with a typecast suffix like `,x` for example to see it as hex, or `,i` as signed integer.
