### ISSUE TITLE
Add static const textures to the texture viewer window that are set via the ResourceDescriptorHeap

### ISSUE THREAD

**Issue by jay1975h** [baldurk/renderdoc#2801]
## Description

Dynamic resources in Shader Model 6.6 allows you to set a static const texture using the ResourceDescriptorHeap.
For example:
```
cbuffer Ids { int id1; };
static const Texture2D<float4> texture = ResourceDescriptorHeap[id1];
```
These textures are not visible in Renderdoc's texture viewer window. The only way to look at these textures right now is to open the descriptor heap and scroll until you find the correct index, which is rather troublesome. Adding these textures to the texture viewer window would help a lot for debugging.

## Environment

* RenderDoc version: 1.24
* Operating System: Windows 11
* Graphics API: DX12, Shader Model 6.6.

**Comment by baldurk** [comment]
SM6.6 direct heap feedback is already supported but it looks like there was a regression in v1.23/v1.24 which caused resources not to properly show up in the pipeline state viewer. That commit should fix it, so you can find the accessed resources that way. I'm not sure what you mean about 'opening the descriptor heap' since there's no way to do that in RenderDoc?

Getting thumbnails in the texture viewer is more complex because they're based on reflection data, and there is no reflection data for SM6.6 heap access. This may have to be a longer-term refactor to figure out some way to represent that nicely.

**Comment by jay1975h** [comment]
Thanks for the fast response. 

_"I'm not sure what you mean about 'opening the descriptor heap' since there's no way to do that in RenderDoc?"_
I am looking at the descriptor heap through this window.

![image](https://user-images.githubusercontent.com/80248118/209089790-95b0dcca-6c92-49cc-b6ba-ce03af117814.png)

**Comment by baldurk** [comment]
That does not show the current contents of the descriptor heap and you should not be using it as a way to view the current bindings, that's what the pipeline state is for. Maybe I need to look at hiding that, since as it says in your screenshot that is really an internal piece of data.

**Comment by baldurk** [comment]
I've pushed a refactor to how RenderDoc handles descriptors, which includes more generalised support for SM6.6 access so they should now show up in the texture viewer thumbnails. This should be present in the next nightly build.
