### ISSUE TITLE
RenderDoc crashes/shows VK_ERROR_DEVICE_LOST error when selecting vkCmdDraw or vkCmdDrawIndexed events

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2805]
## Description

Any time I try to debug a Vulkan capture, renderdoc either shows a `VK_ERROR_DEVICE_LOST` error or completely hangs upon selecting a `vkCmdDraw` or `vkCmdDrawIndexed` event. Other events (e.g. `vkCmdBeginRenderPass`, `vkCmdCopyImageToBuffer`) do not result in a hang and update the displayed image in the texture viewer properly.

Actually, this isn't 100% the case: in the capture I link below, I can select EID 56 just fine without a hang, and even debug pixels/vertices. EIDs 26, 37, and 82 result in the `VK_ERROR_DEVICE_LOST` message, while EID 45 results in an endless progress bar at the bottom of the screen, and renderdoc stops responding when I try to close it.

## Steps to reproduce

1. Open this capture: [Lesson08_2022_12_24.zip](https://github.com/baldurk/renderdoc/files/10299337/Lesson08_2022_12_24.zip) (generated in Dolphin using the [Lesson08 fifolog](https://fifo.ci/media/dff/Lesson08.dff))
2. In the event browser, select EID 26 (`vkCmdDraw`).
3. Observe the `VK_ERROR_DEVICE_LOST` message that appears.

## Environment

* RenderDoc version: v1.23, v1.24 (I ran into this in v1.23, but then got distracted and never reported it. Sorry!)
* Operating System: Windows 10.0.19044.2364
* Graphics API: Vulkan

This issue affects both my integrated Intel GPU (driver version 30.0.100.9684, dated 7/9/2021) and my NVIDIA GeForce GTX 1650 Ti (driver version 30.0.15.1278, dated 5/5/2022). This issue also affects older captures (e.g. one from January 2022).

OpenGL, D3D11, and D3D12 are unaffected, but are undesirable for debugging (due to Renderdoc's lack of support for OpenGL, and dolphin generating HLSL from SPIRV (see https://github.com/dolphin-emu/dolphin/pull/10673) in a way that loses info for debugging (at least currently).)

Logs: [Intel](https://github.com/baldurk/renderdoc/files/10299331/renderdoc_report_173101.zip), [Nvidia](https://github.com/baldurk/renderdoc/files/10299332/renderdoc_report_173600.zip).

**Comment by baldurk** [comment]
I believe this is an issue which is fixed on the latest nightly build already. When using a fallback path without bufferDeviceAddress it had broken descriptor copies, so any vertex shader that used a descriptor resource (so most any non-trivial VS) would likely fail.

This fallback path is being used in both cases for you because you have the `Vulkan.Debug.DisableBufferDeviceAddress` config option set which forces it down this path. I don't know why you have this set, perhaps you used it as a workaround in the past but if I told you to do so I would most likely also have told you to only use it temporarily. I strongly recommend you turn this config option off.

I'm also not sure what you mean by "RenderDoc's lack of support for OpenGL".

**Comment by Pokechu22** [comment]
Thanks, I can confirm that the issue is not present in Nightly v1.25 - 2cd474c.

It looks like you recommended I set that option in #2360 due to bad behavior in the mesh viewer. If I turn that option off, v1.24 also works properly, and that issue no longer occurs (probably it was fixed in a newer NVIDIA driver).

By "lack of support for OpenGL" I mean lack of support for debugging shaders and pixel history, both of which I use fairly frequently. Sorry for not being clear initially.

**Comment by baldurk** [comment]
Yes you definitely shouldn't leave debug workarounds enabled since by their nature they often have limitations or problems.

Someone is working on contributing pixel history for GL, though it is still currently a work in progress. I don't expect debugging shaders will ever be fully supported as that is primarily down to API design flaws having a text shader format instead of a proper one.

**Comment by manaboy** [comment]
I've got the latest version on Google pay store 5.0.19870 and it's still has this issue, I've now downloaded the latest developments version and still testing it. Android RK3588.

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
