### ISSUE TITLE
Can not read depth buffer when enable msaa on android, using opengles

### ISSUE THREAD

**Issue by xuetaolu** [baldurk/renderdoc#2808]
## Description

1. when enable msaa2 on android, using opengles, the pixel of depth buffer is always zero.
rdc file: [problem_using_opengles_msaa2.zip](https://github.com/baldurk/renderdoc/files/10317434/problem_using_opengles_msaa2.zip)
![image](https://user-images.githubusercontent.com/36478973/209898982-5074abc2-f726-4b21-9fd6-fea1fb49ef6b.png)
![image](https://user-images.githubusercontent.com/36478973/209898995-519cce8a-11a4-43b8-83a8-e09e3e78f853.png)

2. but it is was ok when enable msaa2 using vulkan,
rdc file: [ok_using_vulkan_msaa2.zip](https://github.com/baldurk/renderdoc/files/10317435/ok_using_vulkan_msaa2.zip)
![image](https://user-images.githubusercontent.com/36478973/209899166-ce2e350b-ec9b-4ef5-ae58-10199768f23f.png)

3. and also it is ok when disable msaa using opengles
rdc file: [ok_using_opengles_disable_msaa.zip](https://github.com/baldurk/renderdoc/files/10317438/ok_using_opengles_disable_msaa.zip)
![image](https://user-images.githubusercontent.com/36478973/209899440-f61d55ae-de7d-458f-8355-e3880ee22e88.png)

## Environment

* RenderDoc version: v1.24 built from e5e68ef2
* Operating System: win10 apu 5600G
* Graphics API: opengles android, redmi k30s ultra
* unity 2019.4.40f1 LTS
unity project: 
[test_render_scene_with_depth.zip](https://github.com/baldurk/renderdoc/files/10317447/test_render_scene_with_depth.zip)
![image](https://user-images.githubusercontent.com/36478973/209899781-a81d26b6-f6f1-4de9-bba5-8b813edb06de.png)

**Comment by baldurk** [comment]
I believe this scenario is impossible to support given the limitations of the GLES API. There is no way that I am aware of to retrieve the contents of a multisampled renderbuffer, as the only way to retrieve a renderbuffer's contents is via a framebuffer blit, and it is not possible to have a multisampled destination in a blit on GLES.

The data is still present but impossible to observe, seemingly by design of the API.

If you use a proper texture instead of a renderbuffer as you are already doing for the colour target that should work correctly. Renderbuffers are a legacy concept from before render to texture existed and hold no meaning anymore. Or else if you have a vulkan renderer I would highly suggest you use that, as GLES is a flawed API.

In future please properly fill out the issue template and list steps to reproduce under the proper section, even if they are as simple as opening a capture and observing a result at a given point. If you do not your issue is liable to be closed.

**Comment by CloudSAMA001** [comment]
> I believe this scenario is impossible to support given the limitations of the GLES API. There is no way that I am aware of to retrieve the contents of a multisampled renderbuffer, as the only way to retrieve a renderbuffer's contents is via a framebuffer blit, and it is not possible to have a multisampled destination in a blit on GLES.
> 
> The data is still present but impossible to observe, seemingly by design of the API.
> 
> If you use a proper texture instead of a renderbuffer as you are already doing for the colour target that should work correctly. Renderbuffers are a legacy concept from before render to texture existed and hold no meaning anymore. Or else if you have a vulkan renderer I would highly suggest you use that, as GLES is a flawed API.
> 
> In future please properly fill out the issue template and list steps to reproduce under the proper section, even if they are as simple as opening a capture and observing a result at a given point. If you do not your issue is liable to be closed.

So to bother, you mentioned that "it is not possible to have a multisampled destination in a blit on GLES". Does it means there is no way to get unresolve color/depth (for some special effect like custom msaa or CBR)

**Comment by baldurk** [comment]
I don't know what you mean by 'unresolve' as that's not a concept in the API. The block is that there is no way I can see to copy or duplicate the contents of an MSAA renderbuffer, it is effectively write-only.
