### ISSUE TITLE
Add type checking to OpenGL driver

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#281]
Would it be possible for RenderDoc to validate the type of the buffer object being passed to OpenGL API functions? e.g. validate that a vertex array object is being passed to glBindVertexArray, as opposed to a uniform buffer object or element array object. It's been the #1 problem that I've encountered in these porting projects, in part because the effects can be subtle and non-obvious, like in the case I just fixed where a VBO was being passed to glBindVertexArray. Having a validation layer perform type checking would have saved me hours of debugging. Perhaps the thunking layer can assign non-overlapping ranges to the different object types - e.g. 0 - 999999 for textures, 1000000 - 1999999 for VBOs, etc - when a special 'type validation mode' is enabled? I suspect that monkeying with the object id values might break the spec, so this is best limited to a special validation mode, but it would trap an entire category of sometimes very non-obvious bugs.

**Comment by baldurk** [comment]
This should be feasible for distinct types, like buffers vs. VAOs vs textures, but it would mean adding an optional remapping call for every case where I pass along a GLuint to the API, which is fairly intrusive.

Validating buffer types (like element array vs UBO vs vertex array) should happen to some extent I think, although it could maybe be improved. It's a bit harder to validate though as it's perfectly legal to change a buffer's type at any time just by calling glBindBuffer - so it'd be impossible to tell if that re-type was intentional or not.

**Comment by jshofmann** [comment]
Perhaps RenderDoc could manage a table mapping object IDs to types, updated when glBindBuffer is called? That might introduce a prohibitive time and space overhead, but there are times when I'd be willing to pay that price - assuming that the price was optional, of course. Such a table could provide a history for each object, which would be useful for several different debugging tasks.

**Comment by baldurk** [comment]
Ah that's not quite what I meant - RenderDoc does already track the current binding type of a buffer. But bind-to-edit is still by far the most common usage of GL, and that means before anyone uses a buffer for an 'invalid' type - they do glBindBuffer for it. How do I know if that was an unintentional or intentional type change? For DSA you could validate of course.

To be honest I think the chances are that most people don't ever deliberately re-type buffers (from array to element array or to uniform), so adding an option to warn whenever that happens would then be useful. Together with validation of DSA (which is easier, although not a tiny task) would get you majority of the benefit for minimal cost.

**Comment by baldurk** [comment]
I'm closing this now, validation is a non-goal for RenderDoc in general as it's duplicated work over existing validation and is a huge amount of work in its own right. Small checks here and there can be done, or checks that are in a grey area, but this kind of task is complex and definitely validation related. Lack of typechecking on GL is a clear failing of the API but there's no point leaving this issue open indefinitely when it's never planned to be resolved.
