### ISSUE TITLE
VK_LAYER_KHRONOS_validation listed twice when API Validation is enabled

### ISSUE THREAD

**Issue by bndbsh** [baldurk/renderdoc#2813]
## Description

When launching my app from RenderDoc with API Validation enabled, it segfaults in `vkCreateInstance`. I traced this down to `VK_INSTANCE_LAYERS` being set to `VK_LAYER_KHRONOS_validation:VK_LAYER_KHRONOS_validation`.  With API Validation disabled, `VK_INSTANCE_LAYERS` is not set at all.

I can't find anything in the spec disallowing listing the same layer twice, and I suspect the crash is a driver bug, however I don't understand why it would be listed twice in the first place so it may be something to fix in RenderDoc as well.

## Steps to reproduce

1. Enable "API Validation"
2. Launch vulkan application from RenderDoc
3. Observe `VK_INSTANCE_LAYERS` and `VK_DEVICE_LAYERS` environment variables

## Environment

* RenderDoc version: 1.23
* Operating System: Linux 6.1.1
* Graphics API: Vulkan 1.3
* GPU: Radeon RX 5700 XT
* GPU Driver: 22.3.1

**Comment by baldurk** [comment]
I cannot reproduce this crash. Running on the same setup (as much as possible, you didn't specify loader or validation layers versions so I used the latest version of each) I'm able to run a vulkan program fine with API validation enabled.

This isn't surprising as I don't expect this is a universal problem across all possible vulkan applications, it may be a problem that reproduces with _your specific_ vulkan application though. If you share that I can try and reproduce it there.

**Comment by bndbsh** [comment]
Do you mean it just doesn't crash or it doesn't list `VK_LAYER_KHRONOS_validation` twice in the env vars? Is that supposed to happen?

I can try to minimally reproduce the crash as well.

**Comment by baldurk** [comment]
The bug is that it crashes, and I couldn't reproduce that. I didn't check the environment variables because that is irrelevant.

**Comment by bndbsh** [comment]
It's actually the other way around. The crash is how I noticed the issue, but what I'm reporting here is `VK_INSTANCE_LAYERS` being set to a weird value by RenderDoc. The crash itself is unrelated to RenderDoc and happens if I try to load the validation layer twice. For example here's a reproduction with vkcube:

```
$ VK_INSTANCE_LAYERS="VK_LAYER_KHRONOS_validation:VK_LAYER_KHRONOS_validation" vkcube
[1]    2634 segmentation fault (core dumped)  VK_INSTANCE_LAYERS="VK_LAYER_KHRONOS_validation:VK_LAYER_KHRONOS_validation"
```

It's not a big deal as I enable the validation layer separately and can just leave the checkbox turned off in RenderDoc, just thought I'd report that it's setting the environment variable to a confusing value in case it causes problems for others down the line. If there's no reason to list the same layer twice, RenderDoc shouldn't be doing it.

**Comment by baldurk** [comment]
You are still mixing up cause and effect. There is no problem with having duplicate entries in the environment variable, and running that command works entirely fine for me as I'd expect. If that is crashing then the problem is with whatever is crashing, not with any environment variable values.

I would recommend making sure you are running an up to date loader and validation layers, check that you don't have any implicit layers being loaded which could be breaking, and find out where the crash is happening exactly. If there is no obvious culprit then I would report this to the loader for investigation.

This crash is not a RenderDoc bug though since you can reproduce it on its own without RenderDoc, which is an important distinction. The use of environment variables within RenderDoc is an implementation detail and not a concern for users.

**Comment by bndbsh** [comment]
I'm not confusing anything, I made it very clear that I don't think the crash is because of RenderDoc. The issue name, description, steps to reproduce and everything I've been telling you has been about the environment variable. I'm not sure I can state this any more clearly. If listing out the validation layer twice is intended valid behavior, please say clearly that instead of making assumptions about me.

Thanks for your time.
