### ISSUE TITLE
Run forward to cursor stopping one statement short when debugging shader source

### ISSUE THREAD

**Issue by greg-lunarg** [baldurk/renderdoc#2823]
## Description

Run forward to cursor stopping one statement short when debugging shader source

## Steps to reproduce

Clone and build git@github.com:SaschaWillems/Vulkan.git

Use the SPIR-V deferred.frag.spv that I emailed you and copy it into data/shaders/glsl/deferredshadows

It has been compiled with glslangValidator -V --target-env vulkan1.3 -gVS -Os -o deferred.frag.spv deferred.frag

Run renderdoc on sample deferredshadows 

Use command option: --shaders glsl

Debug a pixel in the knights red front plate.

Set the cursor on source line 123. Do Run Forwards to Cursor. It will stop on line 121.

Similarly, set a breakpoint on 123. Press F5. Debugger will stop on 121.

If shader not optimized (-Os removed), the problem does not occur.

The optimized SPIR-V looks correct to me.

FYI, this problem can also be seen with the HLSL shaders which are often optimized as part of legalization in dxc.

## Environment

We are seeing this with the latest release 1.24 as well as latest nightly 1-16-2023

Seeing on Windows and Linux

* RenderDoc version: XXX
* Operating System: XXX
* Graphics API: XXX

NVidia

**Comment by baldurk** [comment]
That commit should fix this. There was an issue with the same disassembly line being mapped to multiple source lines, which caused some confusion. This was because DebugValue is considered an instruction for stepping but it wasn't being disassembled. Although it adds noise to the disassembly the most reliable fix is to include DebugValue in the disassembly and this should now work correctly.

**Comment by greg-lunarg** [comment]
Nice! Thanks!
