### ISSUE TITLE
Part of qrenderdoc UI window becomes unredrawn

### ISSUE THREAD

**Issue by djdeath** [baldurk/renderdoc#2825]
## Description

In all of the captures I have, once I double click the one of the attachment, the part of the tabs on the right end side of the renderdoc UI, stop redrawing itself. So I'm left with part of the UI window unredrawed.

Might be a Qt bug, not sure :(

## Steps to reproduce

Open a trace, find a event that draw to one of the attachment, double click the attachment thumbnail in the "Texture Viewer" tab.

I think it starts once more than 1 attachment tab is opened in the "Texture Viewer"

## Environment

* RenderDoc version: tip of tree fce1920d5b4f4f1c0e6613fa5049ff75abf5fb65
* Operating System: Ubuntu 22.10
* Graphics API: Vulkan

Using a DG2 A380 GPU

**Comment by baldurk** [comment]
This gives me extremely little to go off to investigate the problem. Can you please share a capture in case this is something capture-specific? A screenshot or video would also be very helpful so I can understand what is going wrong.

Does this reproduce on a different GPU or system, in case it's something system specific? If you think it might be a Qt bug does this reproduce on a nightly build binary with statically linked Qt, or if that's all you've tried does it reproduce if you build RenderDoc from source yourself using your system's Qt?

I can follow these steps and not reproduce the bug, which is not surprising as they are very general, so I need more information to have a hope to do anything.

**Comment by djdeath** [comment]
Thanks for pointing me to the nightly builds. The lastest one works fine. So I guess it's a Qt build with whatever version I have installed on my system.

**Comment by baldurk** [comment]
It may also be caused by plugins or injected code, some distributions contain that kind of thing. I was testing on Ubuntu (22.04 to be fair since I only use stable editions) with no problems for what it's worth but not running anything like KDE or other programs that might inject code into Qt.

If it only happens on a local build then you could try [building the same version of Qt 5.15.2 locally, even non-statically](https://github.com/baldurk/renderdoc/blob/v1.x/util/buildscripts/scripts/docker/prepare.sh#L102) if you wanted to test. But it sounds like this is outside anything I can deal with unfortunately.
