### ISSUE TITLE
Support for EGL_KHR_no_config_context

### ISSUE THREAD

**Issue by n-morales** [baldurk/renderdoc#2830]
## Description

This is a mix between a bug/feature. My application makes use of [EGL_KHR_no_config_context](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_no_config_context.txt), but this is not currently supported by RenderDoc. The bug part of it, I guess, is that `EGL_KHR_no_config_context` is still listed as a supported extension when querying `eglQueryString( ..., EGL_EXTENSIONS )`, so applications checking this value will get an incorrect result because the RenderDoc hooks do not support the extension.

The feature request would be to support the `EGL_KHR_no_config_context` extension, since it is quite useful.

The current behavior when attempting to call `eglCreateContext` with `EGL_NO_CONFIG_KHR` is that the call generates `EGL_BAD_CONFIG`. 

The error occurs because of [this call](https://github.com/baldurk/renderdoc/blob/v1.24/renderdoc/driver/gl/egl_hooks.cpp#L331), since `EGL_NO_CONFIG_KHR` is an invalid argument for the call. I'm not familiar enough with the renderdoc source, but maybe these calls could be moved to a hook for `eglCreatePlatformWindowSurface` or `eglCreateWindowSurface`?

## Environment

* RenderDoc version: 1.24
* Operating System: Linux Mint 20.3
* Graphics API:  EGL API version: 1.5 (while instantiating an OpenGL 4.6 context)

**Comment by baldurk** [comment]
I don't have any plans to add support for new EGL extensions that require implementation work, but the query string is a problem I hadn't considered. Modifying the string is not hard but I will need to check to see what to do with extensions. I'm wondering if it's best to do a block list of extensions that fail instead of an allow list since EGL being a platform-specific API it may have platform undocumented extensions that should be preserved, I'm concerned about the unforeseen problems that would come from some random Android device stopping working if an extension disappears.

**Comment by baldurk** [comment]
I went through the EGL extensions, only at a quick look given the number & complexity but it seems like this is the only extension which intersects with the subset RenderDoc cares about enough to need to be blocked.

I don't have an android test program that I can easily modify to test with, if that is still reporting the extension as supported please let me know and I can look into it.
