### ISSUE TITLE
a error warning when i lauch an application in renderdoc

### ISSUE THREAD

**Issue by 1064347558** [baldurk/renderdoc#2832]
## Description

Excuse me, I met a problem when i lauch an appllication in latest version of renderdoc but warning error connenting to debugger... 
![image](https://user-images.githubusercontent.com/112362267/214589309-ad733aa2-d29a-411e-a30c-1bfed1d30638.png)
i have ensured my phone's "ro.debuggable" = 1, but still can't fix the problem.
i searched in issue page and found the "Can't connect android device using version 1.0 "  which include the same problem.
so i tried to use the nightly build version 2018_3_14, 2018_3_13, but they all get the same problem, i wonder how can i fix it and lauch the application successfully, thank you!

my test phone's SOC is snapdragon 616, a littile bit old

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
