### ISSUE TITLE
Crash when opening Vulkan capture after upgrading from v1.22 to v1.24

### ISSUE THREAD

**Issue by AirGuanZ** [baldurk/renderdoc#2837]
## Description

Hi,

Renderdoc crashes when opening the given Vulkan capture file.

When I capture & open the same program with v1.22, everything is ok. After upgrading to v1.24, it captures well but cannot open it. When using v1.24 to open the capture file created with v1.22, it also crashes.

For comparision, the capture file created with v1.22 (`v1.22_capture.rdc`) is also attached. 

## Steps to reproduce

[captures.zip](https://github.com/baldurk/renderdoc/files/10527239/captures.zip)

1. Open the attached capture file `v1.24_capture.rdc` with renderdoc 1.24

## Environment

* RenderDoc version: v1.24
* Operating System: Windows 11 22621.1105
* Graphics API: Vulkan 1.3

**Comment by baldurk** [comment]
I'm not able to reproduce this because on your nvidia GPU there's a 4th queue family reported which has `VK_QUEUE_TRANSFER_BIT | VK_QUEUE_SPARSE_BINDING_BIT | VK_QUEUE_OPTICAL_FLOW_BIT_NV` properties which your application is using, but my nvidia GPU only has three queues.

Can you share your program so I can try to reproduce it on my system? or since your application cannot be using that queue functionality, could you choose the `VK_QUEUE_TRANSFER_BIT | VK_QUEUE_SPARSE_BINDING_BIT` queue instead which is then the same on my device?

**Comment by AirGuanZ** [comment]
Thanks for the quick reply.

After choosing the `VK_QUEUE_TRANSFER_BIT | VK_QUEUE_SPARSE_BINDING_BIT` queue without `VK_QUEUE_OPTICAL_FLOW_BIT_NV`, v1.24 works perfectly. It seems that the crash occurs only when the 4th queue family is used.

Here are the programs (with/without using VK_QUEUE_OPTICAL_FLOW_BIT_NV queue) and the new capture file. The program has been tested only on a win11 & 3080ti laptop.

[programs_and_captures.zip](https://github.com/baldurk/renderdoc/files/10527450/programs_and_captures.zip)

**Comment by baldurk** [comment]
I couldn't reproduce this on my system as I don't have any GPU with the optical flow extension. It looks like this is only available in the 30x0 series and up. I'm only able to run the program on one of my test machines, since my primary machine has a 1080 and the program has higher minimum feature requirements, but even on that test machine it didn't reproduce without the queue in place.

However I did look into the code in more detail and I think the issue is some queue-remapping code going wrong. Those commits should fix the problem I believe regardless of which queue you use.

**Comment by AirGuanZ** [comment]
It works. Thank you!
