### ISSUE TITLE
Quad Overdraw is confusing/false when viewing instanced draws

### ISSUE THREAD

**Issue by dkyeck** [baldurk/renderdoc#2841]
## Description

when you chose overlay = quad overdraw (pass) or quad overdraw (draw) the previev looks odd when investigating a "DrawIndexInstanced" draw with multiple instances: last instance will add overdraw to areas where it is occluded by instances that drew before 

## Environment

* RenderDoc version: 1.20
* Operating System: win 10
* Graphics API: dx11

![renderDocQuadOverdraw](https://user-images.githubusercontent.com/492095/215873711-e3cf7912-ac4f-43f1-9e12-f0bfa0215da1.PNG)

**Comment by baldurk** [comment]
This seems to me to be working as intended. The quad overdraw measures the overdraw based on pixel shaders running as best as is possible in the API, and only when the pixel shader doesn't run will there be no overdraw shown. Graphics APIs deliberately do not have strong guarantees about when shaders will and won't run due to early depth test failures. In this case it seems that occlusion by previous instances does not happen, perhaps because those pixel shaders are already in flight but that kind of detail may be architecture specific. If you split this into multiple draws you should see that depth occlusion is respected, indicating that the shader was not run.

As a note, in future please fill out the issue template properly or your issue is liable to be closed. You should provide proper steps to reproduce the problem, do not leave the field blank.

**Comment by dkyeck** [comment]
>  In this case it seems that occlusion by previous instances does not happen, perhaps because those pixel shaders are already in flight but that kind of detail may be architecture specific. 
thanks. this would explain it. i thought that the gpu would guarantee the right order when drawing the quads. might no be the case of instancing.
splitting it up into multiple draws actually helps and depth occlusion works as expacted.
