### ISSUE TITLE
Texture Viewer defaults to range 0-1 for 8-bit unsigned integer formats

### ISSUE THREAD

**Issue by leidegre** [baldurk/renderdoc#2862]
## Description

This took me by surprise but the default range for the texture viewer is 0,1 which I guess is a fine default but then I started using GL_RGBA8UI texture formats they show up as all white with this default. Would it be possible to make it so that the range has 0-255 as default for integer formats (or the appropriate size depending on the format)?

![image](https://user-images.githubusercontent.com/63085/220373704-77df7799-dc55-4ec8-9abe-36d93c9c9490.png)

![image](https://user-images.githubusercontent.com/63085/220373801-872782a0-972a-4d16-9680-59f4e4a9bf41.png)

I'm quite new at this and maybe I should not be using integer formats but I managed to wonder into this world trying to write a compute shader to compute mipmaps. I had some trouble getting everything to work but when it finally did I was a bit perplexed by the texture showing up all white in RenderDoc. I noticed that the pixel values were there and eventually found the range settings so this is a minor inconvenience nothing more.

## Environment

* RenderDoc version: 1.25
* Operating System: Windows Version 10.0.19043.2364
* Graphics API: OpenGL 4.6

**Comment by baldurk** [comment]
I've considered this before and while it's not perfect I do think it's the best compromise. There is not really a good sensible fixed default to apply to integer textures - for 8-bit textures 255 is somewhat reasonable as it just turns it into UNORM and even single digit values will be somewhat visible, but 8-bit integer textures are rarely used from what I've seen and as soon as you have 16 or especially 32 bits the range is so large that instead of everything showing as "white" everything shows as "black" for typical values.

This problem is not unique to integer textures, it's also possible for float textures to have the majority or all values over 1.0, at which point you also need to adjust the range. Similarly there there is no possible fixed default to apply either.

The only alternative would be to use the auto-fit to always automatically set the range to the minimum and maximum, but that would really have to be done for all textures for consistency otherwise you have unpredictable behaviour, and is often not desired. Also generally I err on the side of RenderDoc _not_ doing something automatically which you _do_ want, rather than _doing_ something that you _don't_ want, as I think the latter is much more irritating as a user when you're undoing something from a program that tried and failed to be smart.

So the 0-1 range as a default is then universal and predictable across all textures, and while it's not a great default for integer textures changing the range is a very common operation and the visualisation is easily discoverable when someone is familiar with how to use the texture viewer.

**Comment by leidegre** [comment]
No worries makes sense. I agree that having a sensible default is the better option and that it would be irritating if it started having automatic nonsensical defaults.
