### ISSUE TITLE
ReplayStatus::AndroidAPKFolderNotFound when building from source code.

### ISSUE THREAD

**Issue by MaxLykoS** [baldurk/renderdoc#2867]
I built v1.3 from source code because I cant open it from installer.
The code was perfectly build and running until I started to debug android, and I encountered this:

    RDCERR(
        "APK folder missing! RenderDoc for Android will not work without it. "
        "Build your Android ABI in build-android in the root to have it "
        "automatically found and installed.");
    return ReplayStatus::AndroidAPKFolderNotFound;

Where can I find build-android? Define "root" and I didnt find it neither.

**Comment by MaxLykoS** [comment]
Also this exception on PersistantConfig.cpp: 423, right after the "return ret;" both occurs on development and release.
Stack cookie instrumentation code detected a stack-based buffer overrun. 
I have set stack reserve size to somewhat 104857600 bu it doesnt help.

**Comment by MaxLykoS** [comment]
More specificly, the bugged code is among this:

``` c++
// see which known tools are registered
  for(const ShaderProcessingTool &dis : ShaderProcessors)
  {
    // if it's declared
    if(dis.tool != KnownShaderTool::Unknown)
      tools[(size_t)dis.tool] = true;
    for(KnownShaderTool tool : values<KnownShaderTool>())
    {
      if(QString(dis.executable).contains(ToolExecutable(tool)))
        tools[(size_t)tool] = true;
    }
  }
```

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
