### ISSUE TITLE
Application closes without error while trying to run it in renderdoc

### ISSUE THREAD

**Issue by Jark5455** [baldurk/renderdoc#2875]
## Description
When I run my application in renderdoc it closes without error. What is weird is that If I attach gdb renderdoc registers it as the process exiting early but gdb doesn't register the process closing or crashing and keeps the process alive long after renderdoc closes. 

## Steps to reproduce

1. Install the dependencies OpenEXR, Imath, Assimp, and SDL2 (Should be automatically detected by cmake if not a manual installation path can be specified in a  `.env.cmake` file)
2. clone the [this](https://github.com/Jark5455/BananEngine.git) repo
3. `cd BananEngine`
4. `mkdir build`
5. `cd build`
6. `cmake ..`
7. `make`
8. download the assets from [here](https://www.dropbox.com/sh/d7rj4aea820230n/AACyzs2NqyVHfjyscROBfQb_a?dl=0) and put them in the build folder
9. Run the application in renderdoc with the working directory set to the build folder and the executable set to `BananEngineTest`

## Environment

* RenderDoc version: 1.25-1
* Operating System: Manjaro Linux
* Graphics API: Vulkan

I believe this issue could potentially be related to a synchronization issue in the application that has not been fixed yet.

**Comment by baldurk** [comment]
I'm not able to reproduce this with the repo provided.

I had to make a couple of edits/changes to get it to compile, but once I was able to get it running I was able to run it from RenderDoc successfully and capture, both from the 1.25 build and from a local build from latest git.

One thing that jumped out was the RenderDoc version you list is invalid, RenderDoc versions do not use a patch, so it's 1.25 not 1.25-1. Are you using a RenderDoc build you compiled yourself or downloaded from the website, or a distribution package? I recommend not using the distro packages since many are out of date and/or just broken.

Are you able to reproduce this on other machines or does it only happen on yours, is it perhaps a driver/hw specific issue? If you add any file logging are you able to see if the process at least reaches the first line of main() ?

**Comment by Jark5455** [comment]
Hmm you are correct, I am not able to reproduce it on my windows dualboot. Currently I am using renderdoc listed as "renderdoc-bin" on AUR.

**Comment by baldurk** [comment]
arch packages have been broken in the past and I do not recommend using them. If you can test with a locally compiled build or with the RenderDoc package from the website that would be helpful.

FWIW I was testing on linux since I didn't know if it were possible to run on windows.

**Comment by Jark5455** [comment]
Hmm, I went back to kernel 5.15 and it appears to be work fine, I think its an issue with kernel 6, Ill also try using a locally compiled version soon.

**Comment by Jark5455** [comment]
Kernel 61 LTS appears to work fine with render doc. I will close this issue.
