### ISSUE TITLE
[Feature Request] Support Shader Code Formatting

### ISSUE THREAD

**Issue by DudeRenderer** [baldurk/renderdoc#2881]
## Description

Add a Button or Setting Options to support shader code formatting. Because now the shader code has a lot of Marco that will occur in multiple blank lines and Inelegent code style. 
![image](https://user-images.githubusercontent.com/33353769/224529678-e7106443-45c1-4f27-af0d-d80bf0a320e6.png)

or integrate clang-format could be solve this problem : ) 

## Environment

* RenderDoc version: v1.25
* Operating System:  Windows10
* Graphics API: DX11/12

**Comment by baldurk** [comment]
No, this has been asked for before and I do not plan to add it. RenderDoc is not a shader IDE and I don't want to start to scope-creep in that direction.

You are in control of your shader source and what it looks like, so if you want a formatting step to be applied due to macro expansion you can do that yourself before compilation, or else make sure you compile the original source and let the compiler do the macro expansion so that the original source is displayed in RenderDoc too.
