### ISSUE TITLE
Support for HLSL dissasembly

### ISSUE THREAD

**Issue by Makogan** [baldurk/renderdoc#2882]
## Description

It seems that under the current version at the tie of this writing (1.25). Renderdoc cannot dissassemble code into HLSL. THe options are:

* SPIR-V
* GLSL
* SPIR-V asm
* KHR_pipeline_executable_properties
* AMD GCN ISA

I am wondering if it would be possible to have one for HLSL. Since HLSL was recently open sourced and it offers a lot of flexibility that GLSL does not currently provide, it would be useful to have disassembly that more closely resembles the original code. For example this code:

```hlsl
#include <linalg.hlsl>

struct Particle
{
	vec4 pos;
	vec4 vel;
	float pinned;
};

[[vk::binding(0)]]
RWStructuredBuffer<Particle> particles;

[numthreads(10, 10, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
	particles[0] = particles[1];
}
```

Is disassembled into this (using the second option which gives the cleanest output):

```glsl
 #version 450
layout(local_size_x = 10, local_size_y = 10, local_size_z = 1) in;

struct Particle
{
    vec4 pos;
    vec4 vel;
    float pinned;
};

layout(set = 0, binding = 0, std430) buffer type_RWStructuredBuffer_Particle
{
    Particle _m0[];
} particles;

void main()
{
    particles._m0[0u] = particles._m0[1u];
}

```

This is not the end of the world, as it is still clear what the shader is doing. But it can be more complicated for the user to mentally translate from GLSL back and forth vs having native HLSL dissassembly.

I would like to see an additional option in the above list that allows for HLSL disassembly.

## Environment

* RenderDoc version: 1.25
* Operating System: Ubuntu 22.04
* Graphics API: Vulkan

**Comment by baldurk** [comment]
If you want to have a conversion from SPIR-V to HLSL you can configure that as a [shader processing tool](https://renderdoc.org/docs/window/settings_window.html#shader-processing-tools-config) in the settings. SPIR-V to HLSL is not provided by default because all valid SPIR-V can always be representable as GLSL, but the same is not true of HLSL which is less powerful and cannot represent some SPIR-V functionality. DXC was open sourced many years ago that's not recent, but it's also not related to any of this so I'm not sure I understand that.

Note however that this cross-compilation is probably not going to look as close to the HLSL as you want, especially if you seemingly have local defines to use GLSL typenames instead of HLSL ones. For example compiling the shader and converting it back gave me this output:

```
struct Particle
{
    float4 pos;
    float4 vel;
    float pinned;
};

RWByteAddressBuffer particles : register(u0);

void comp_main()
{
    Particle _19;
    _19.pos = asfloat(particles.Load4(48));
    _19.vel = asfloat(particles.Load4(64));
    _19.pinned = asfloat(particles.Load(80));
    particles.Store4(0, asuint(_19.pos));
    particles.Store4(16, asuint(_19.vel));
    particles.Store(32, asuint(_19.pinned));
}

[numthreads(10, 10, 1)]
void main()
{
    comp_main();
}
```

I would suggest that you instead make sure to build your shaders with debug information so you can see the original shader source and not rely on cross-compilation at all.
