### ISSUE TITLE
Textures appear garbage/black in Android capture replay

### ISSUE THREAD

**Issue by snagy** [baldurk/renderdoc#2887]
Description
Textures aren't recording/replaying (not 100% which) properly on Android GLES captures. Most textures are black, and some are garbage. This does not apply to rendertargets - those show up fine during replay, usually showing silhouettes of the geometry which would have a texture applied but instead just has black applied to it.

I took captures both with the Meta fork of RD as well as stock v1.25 - on both captures, I've captured content from the Quest Browser and replayed them, only to see all my captured texture data is either black or garbage.

Steps to reproduce
Here's a capture with a single texture that shows up as garbage for me:

[rd_125_badtex.rdc.zip](https://github.com/baldurk/renderdoc/files/11021383/rd_125_badtex.rdc.zip)

This capture was taken as follows:

attach to my Quest 2
Launch com.oculus.browser from renderdoc
navigate to https://immersive-web.github.io/webxr-samples/reduced-bind-rendering.html
capture a frame
exit browser
replay the frame on the quest 2 (preview screenshot looks good)
the texture looks grey and garbage, both in texture viewer and when rendered in replay
I have other captures taken using the Meta fork but this is taken with standard RD.

Environment
RenderDoc version: 1.25
Operating System: Windows 10
Graphics API: GLES

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
