### ISSUE TITLE
Renderdoc shows that attachment is discarded every vkCmdNextSubpass() call if the attachment has VK_ATTACHMENT_STORE_OP_DONT_CARE

### ISSUE THREAD

**Issue by ggkbsn** [baldurk/renderdoc#2895]
## Description
We are creating a render pass with some attachments having a store op VK_ATTACHMENT_STORE_OP_DONT_CARE. Right-Clicking on one of these attachments shows this:
![image](https://user-images.githubusercontent.com/129847929/229774064-1a3b3d4c-0063-447e-b654-8a287cb24192.png)

The line marked as GREEN shows the correct discard call, which happens when we end the render pass. The ones marked with a RED line, they show the wrong discards and clicking it will show the vkCmdNextSubpass() call:
![image](https://user-images.githubusercontent.com/129847929/229773063-b2efd853-edf6-46db-8923-5bdae608d9a5.png)
The line marked as BLUE is also a false discard call (or a discard call shown incorrectly) but this time is when a barrier is added for this image before the render pass.

This attachment is loaded with VK_ATTACHMENT_LOAD_OP_CLEAR.

Changing the store op for this attachment to VK_ATTACHMENT_STORE_OP_STORE will result in the expected behavior:
![image](https://user-images.githubusercontent.com/129847929/229773436-1b98b4eb-5d43-40cd-b2fa-a81786af783d.png)

This happens for all the attachment that have VK_ATTACHMENT_STORE_OP_DONT_CARE as their store op in the same render pass. The behavior of the attachment throughout the pass is correct and the final image is also correct, so we believe it might be an issue with RenderDoc displaying wrong information. What we would expect to see is the discard label only when vkCmdEndRenderPass is called.

## Steps to reproduce

- Create a render pass with more than one subpasses
- Set the store op of one of the attachments to VK_ATTACHMENT_STORE_OP_DONT_CARE

This should be enough to reproduce this.

What we run in our application is a regular deferred render pass with a GBuffer subpass, an in-between subpass, a lighting subpass and a post fx subpass. Overall, we have 5 color attachments (3 gbuffers, 1 for the in-between subpass and the final color) + a depth-stencil attachment. The GBuffer attachments and the in-between attachment have store op VK_ATTACHMENT_STORE_OP_DONT_CARE since we don't care about them after the lighting subpass. The attachment usages are:

GBuffer subpass:
- GBuffer0 -> Color attachment (render target)
- GBuffer1 -> Color attachment
- GBuffer2 -> Color attachment
- In-Between attachment -> Unused
- Final color -> Unused
- DS -> Write DS

In-Between subpass:
- GBuffer0 -> Preserve
- GBuffer1 -> Preserve
- GBuffer2 -> Preserve
- In-Between attachment -> Color attachment
- Final color -> Unused
- DS -> Write DS

Lighting subpass:
- GBuffer0 -> Input
- GBuffer1 -> Input
- GBuffer2 -> Input
- In-Between attachment -> Input
- Final color -> Color attachment
- DS -> Input

Post fx subpass:
- GBuffer0 -> Unused
- GBuffer1 -> Unused
- GBuffer2 -> Unused
- In-Between attachment -> Unused
- Final color -> Input
- DS -> Input

## Environment

* RenderDoc version: v1.26
* Operating System: Windows
* Graphics API: Vulkan
* GPU: RTX 2070 super (also tested on 3080)
* GPU Driver: 531.29

**Comment by baldurk** [comment]
Just to be sure I have this clear since I don't have a direct repro case and can't test this, the only issue is the multiple discard listings within the multi-subpass renderpass? The discard patterns aren't showing up incorrectly with filling the wrong attachment or at the wrong time?

I can see that yes discard usage will be added every time instead of just at the end, though in theory it's undefined where the discard actually happens between final use of an attachment & end of render pass, in RenderDoc it logically happens at the end.

**Comment by ggkbsn** [comment]
Thank you for your very quick response!

Yes, we believe that RenderDoc is incorrectly showing that the contents of the attachment were discarded even though the attachment is later used as an input, color attachment or preserved. As you can see in the first picture , the attachment is used after a discard label is shown. For example, after the clear (which happens when the attachment is loaded) there is a discard, then the attachment is used as a color attachment (Where the green flag is) then it shows to be discarded again and then it's used as input. We can clearly see that the attachment is properly used as input later and we don't get any validation errors from the validation layers (or any other visual artifacts).

We only expect to see a possible discard at the last subpass where the attachment is no longer used and/or when we end the render pass. What I cannot tell is what the driver actually does. If the driver indeed discards the contents with every vkCmdNextSubpass call then what render doc shows us should be correct but it would mean that we should probably see garbage values for these attachments in every subpass, but we don't, we see that the attachment is correct. This is why we strongly believe this might be an issue related to RenderDoc.

Thanks again for the quick response and if you need any more information let me know. Unfortunately, I cannot share any captures with you as this is a private project.

**Comment by baldurk** [comment]
No problem at all, I just wanted to make sure I wasn't missing the main bug if it's only this. The resource usage is entirely generated by RenderDoc, it looks like there's just an omission that applied discards on every subpass - likely not noticed before now because subpasses are rarely used.

It's fine that you can't share a capture - most likely I would not be able to load it successfully since really only desktop captures can be portable, there is too much hardware/driver variation that can't be resolved for captures from mobile devices. That commit should fix it I believe, but it would take me longer to reconstruct your repro case (given its complexity) than it is for you to re-test. If you're able to build RenderDoc could you try to see how it behaves with that change, or if not could you check the next nightly build and update this issue?

**Comment by ggkbsn** [comment]
Perfect, thanks!

I will give the next nightly build that includes this commit a try and let you know.

**Comment by ggkbsn** [comment]
Hi @baldurk, just took a look at the latest nightly build and the issue is now fixed:
![image](https://user-images.githubusercontent.com/129847929/230066540-9071621b-248a-4808-b834-2961fa98b8ab.png)
