### ISSUE TITLE
OpenGL replay incorrect / stale

### ISSUE THREAD

**Issue by Dakror** [baldurk/renderdoc#2896]
## Description

I'm using RenderDoc to debug OpenGL code of a quite complex rendering engine. Since a few updates ago, the replay state and reported texture contents have somehow become very unreliable to the point that i need to use NSight Graphics instead of RenderDoc to verify the program execution. Textures in the Texture Preview do not correctly produce the output that the application produced, making me second guess the contents of the capture.

## Environment

* RenderDoc version: 1.26
* Operating System: Win10
* Graphics API: OpenGL 4.3

* GPU: Nvidia Geforce 3060 TI

**Comment by baldurk** [comment]
For steps to reproduce, as detailed in [the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) please share a specific and complete reproducible test case that I can use to investigate the problem, such as a capture or executable depending on what is most relevant to the bug. Without a repro case it is usually impossible for me to replicate the situation you are running into, and it can easily waste time trying to reproduce a problem that is not as expected or described.

Please ensure that you have run your program on its own (not from RenderDoc) with API validation and have checked that your program does not produce any validation errors or warnings, since RenderDoc does not handle invalid API use. Make sure that you have updated your graphics drivers and if you have a different GPU or hardware available try testing on that to eliminate your hardware as a potential problem.

If you can't share your test case publicly due to privacy or NDA concerns you can contact me [via email](mailto:baldurk@baldurk.org). Even if you can't share your test case privately email is typically the best avenue if you can discuss more details than you can privately.

**Comment by Dakror** [comment]
Thank you for your quick response. I've reached out to you via email.

**Comment by Dakror** [comment]
After a lot of investigation, @baldurk discovered that some buffers were erroneously deleted by the application, causing a technically illegal GL state which the driver seemingly accepted regardless but renderdoc couldn't handle. 

So there is no bug in RenderDoc, but our application.
