### ISSUE TITLE
Fails to capture on Vulkan

### ISSUE THREAD

**Issue by disks86** [baldurk/renderdoc#290]
I tried to use renderdoc to diagnose a rendering issue I'm having with SchaeferGL but when I try to capture the sample I'm running closes quickly and I get validation errors/warnings in my log. There are no validation errors if I run without renderdoc.

My project was built with the 1.0.17.0 LunarG SDK. The test machine uses an AMD HD 7000 series GPU. I am currently running the 16.6.1 Radeon driver. The test machine is currently running Windows 10.

[log.txt](https://github.com/baldurk/renderdoc/files/342621/log.txt)

**Comment by baldurk** [comment]
Hey, I tested on SchaeferGL and I think that should fix this issue. It was an issue on 32-bit specifically, where dispatchable and non-dispatchable handles are a different size.

Please take a look at a nightly build or compile yourself when you have a chance, and let me know if this sorts it out as you expect. Otherwise I'll close this issue after the next stable release.

**Comment by disks86** [comment]
I retested with the 20160612 nightly build. The sample application no longer crashes when running inside of render doc. It does produce an error about the render path but it does not appear to stop render doc nor the sample application.
[SchaeferGL.txt](https://github.com/baldurk/renderdoc/files/360431/SchaeferGL.txt)

**Comment by baldurk** [comment]
Yeh that's just because the renderpass I create for initialising the text rendering uses R8G8B8A8, but your swapchain is using B8G8R8A8, so it's technically incompatible (although unlikely to cause issues in practice since the text is greyscale). I'll fix it some time soon though.

If it's not crashing for you anymore, do you mind if I close this issue?

**Comment by disks86** [comment]
No, It can be closed. Also thank you for fixing this. RenderDoc has helped me immensely since I've been able to use it.
