### ISSUE TITLE
Only captures OpenGL frames when mixed rendering with OpenGL and Vulkan

### ISSUE THREAD

**Issue by keith2018** [baldurk/renderdoc#2910]
## Description

Hi, my project uses OpenGL (glfw) as window rendering, and then renders the result (color attachment) of vulkan rendering as texture of OpenGL, that is, my project uses a mix of OpenGL (on-screen) and Vulkan (off-screen) rendering. 

When I use RenderDoc to capture frames, only the api call of OpenGL is captured but not the api call of Vulkan. Is there a bug or does it not support multiple contexts ? 

## Steps to reproduce

1、Compile and run the project: https://github.com/keith2018/SoftGLRender
2、Switching the renderer to Vulkan
3、Capture frames using RenderDoc

<img width="998" alt="image" src="https://user-images.githubusercontent.com/23111762/232263563-af488f71-0cb3-4346-bf5f-22ef694ccb8c.png">

## Environment

* RenderDoc version: [v1.26 - 31 Mar, 2023](https://github.com/baldurk/renderdoc/releases/v1.26)
* Operating System: Windows 10
* Graphics API: OpenGL 3.3 & Vulkan 1.2

**Comment by baldurk** [comment]
In this case the use of GL is not related - even if you weren't using GL at all, on any API if you are not presenting to a swapchain you can't use the default capturing method since it has no way to know when to start or finish. You will need to use the [in-application API](https://renderdoc.org/docs/in_application_api.html) to capture any entirely headless/offscreen work.
