### ISSUE TITLE
Python API bug:I found that when using the Python API to extract performance counter data in RenderDoc, all CSInvocations are 0, but they are not 0 in the table in the RenderDoc UI

### ISSUE THREAD

**Issue by eddiedong** [baldurk/renderdoc#2914]
I found that when using the Python API to extract performance counter data in RenderDoc, all CSInvocations are 0, but they are not 0 in the table in the RenderDoc UI.
![企业微信截图_16818155143172](https://user-images.githubusercontent.com/29911130/232757766-6384d99b-1ec0-4b3c-8e98-d7710123526e.png)
when i use different data type .its results are zero. But Original data is not zero. 
<img width="390" alt="企业微信截图_16818157574429" src="https://user-images.githubusercontent.com/29911130/232758034-79dc1ce3-402c-4675-a013-6fb6e3778184.png">

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
