### ISSUE TITLE
renderdoc performance counter python api bug-about csinvocations

### ISSUE THREAD

**Issue by eddiedong** [baldurk/renderdoc#2915]
## Description
I found that when using the Python API to extract performance counter data in RenderDoc, all CSInvocations are 0, but they are not 0 in the table in the RenderDoc UI.
## Steps to reproduce
1. When I view Performance Counter data using UI, the csinvocations is not 0；2. but when I get it using python api, all of them are 0, and I still can't get the correct data when I switch to different formats. Other indicators are correct, only csinvacations is wrong.
## Environment

* RenderDoc version: 1.26
* Operating System: windows
* Graphics API: DX11

**Comment by baldurk** [comment]
For steps to reproduce, as detailed in [the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) please share a specific and complete reproducible test case that I can use to investigate the problem, such as a capture or executable depending on what is most relevant to the bug. Without a repro case it is usually impossible for me to replicate the situation you are running into, and it can easily waste time trying to reproduce a problem that is not as expected or described.

Please ensure that you have run your program on its own (not from RenderDoc) with API validation and have checked that your program does not produce any validation errors or warnings, since RenderDoc does not handle invalid API use. Make sure that you have updated your graphics drivers and if you have a different GPU or hardware available try testing on that to eliminate your hardware as a potential problem.

If you can't share your test case publicly due to privacy or NDA concerns you can contact me [via email](mailto:baldurk@baldurk.org). Even if you can't share your test case privately email is typically the best avenue if you can discuss more details than you can privately.

**Comment by eddiedong** [comment]
- I captured a frame file s.rdc of the original God game using renderdoc； 
- then used renderdoc. Then I clicked the "File" menu and selected "Open Capture" to open the s1.rdc file；
- At last in the "API Inspector" window, I clicked the "Performance Counters" button to view the performance counter data. It was found that csinvocations was not 0, but when I extracted the data with python api, I found that csinvocations were all 0, and other indicators were normal.

**Comment by baldurk** [comment]
What do you mean 'the original god game'. Is this your project that you created?

You are leaving out the two vastly most important parts - the actual capture you are using, and your python script. Without those you are not giving the information I would need to reproduce the problem since there is no way I can follow the same steps as you, steps like opening the capture are not relevant.

**Comment by eddiedong** [comment]
our game LostArk. clerical error！Thanks!

**Comment by eddiedong** [comment]
Our Game：fantasy of tower. thanks！

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own is not endorsed or allowed for any reason, and I will provide absolutely no support for it.

EDIT: As a note for anyone in the future, this user claimed they were capturing two separate and unrelated commercial games in two comments, one of those comments has been deleted. For that reason I did not try to ask for proof of legitimacy, it was clearly not a legitimate use case.
