### ISSUE TITLE
Capturing apps running in OpenXR is not normally possible

### ISSUE THREAD

**Issue by rpavlik** [baldurk/renderdoc#2921]
## Description

I'm trying to run RenderDoc to inspect an XR app running on an arbitrary OpenXR runtime.

Because OpenXR apps do not use a normal "present", there's no frame that RenderDoc can see. There is one runtime (Windows Mixed Reality) that attempts to work around this issue, by detecting RenderDoc and creating a hidden window on the client side to present to. Monado tries to help by using the renderdoc API to start and stop capture, but it's only capturing the server/compositor side, and it's capturing every single frame. That's useful if you're working on the compositor, but useless if you're trying to debug an app (the app's graphics API will show up as loaded but inactive because there are no presents). Meta has simply forked RenderDoc for the Quest.

Ideally, there would be a way for the client side of a runtime to signal to RenderDoc that the present-equivalent call has been executed. Alternately an OpenXR API layer could be made to intercept xrEndFrame, which would be easier for runtime developers but more work in RenderDoc. Although, it would avoid adding a capability to the API that you've previously been opposed to (in e.g. https://github.com/baldurk/renderdoc/issues/1155 ). Honestly, this would be ideal I think.

On some runtimes, we get an error like this instead https://github.com/baldurk/renderdoc/issues/1957 though not due to any dll path issues.  NSight has an option to choose frame delimiter, but doesn't have the option to specify an arbitrary call. apitrace just appears to trace everything as a single frame so it does work as long as you can get to the problem code immediately, it's just not nearly as nice as RenderDoc.

Thanks for your consideration!

## Environment

* RenderDoc version: 1.26
* Operating System: Windows 10 (but also linux)
* Graphics API: OpenGL (right now, but also Vulkan, D3D11/12...)

**Comment by baldurk** [comment]
I don't have any plans to add any explicit support for OpenXR. In my experience most VR programs will by default show a preview window on the desktop that can be used for capturing, or at least can do so optionally.

Otherwise (not being familiar with OpenXR, considering it as any other helper library) your application should be able to follow the same path as any other application which does not have a traditional window rendering loop and is either rendering headless - as far as the graphics API is concerned - or not regularly, and use the [in-application API](https://renderdoc.org/docs/in_application_api.html) that you've mentioned to control its captures. It should only take a dozen lines of code or so to attach an external trigger (keypress, debug command, whatever makes sense for your application) to code that will start and stop a capture at the same point in the frame if you do have a repeated rendering loop.
