### ISSUE TITLE
[Feature Request] Global hex/dec toggle for offsets/sizes

### ISSUE THREAD

**Issue by Kelebek1** [baldurk/renderdoc#2924]
## Description

Currently in RenderDoc, all offsets and sizes seem to use decimal by default, but in some windows, over a certain number they switch to hex. This is pretty inconvenient, as in my case I'm trying to find where certain buffer ranges are used in the frame.

![Untitled](https://user-images.githubusercontent.com/34639600/234601464-d6ca0f64-8ce1-4d19-91d6-7dc105df14e6.png)
The event viewer seems to be one of the places where automatic decimal -> hex conversion happens, where src here is decimal, but dst is hex. So in this case I want to find where offset 0x71FDDD0 is accessed for this buffer in any following events.

Checking subsequent commands though, the pipeline state windows only print in decimal
![Untitled2](https://user-images.githubusercontent.com/34639600/234601912-5abd9776-8f1f-46ed-b009-5b2065162064.png)
This is quite awkward, as I can't directly compare values. Is 0x71FDDD0 an intersection on 119551872 + 4224? I don't know, I must manually convert either the hex to dec or visa versa to be able to compare them. The same thing applies to sizes as well. I would really like to just set everything to hex.

My ultimate goal is to find where specific *ranges* of buffers are used within frames. For the example above if I could filter all events for the range 0x71FDDD0 - 0x71FDDD4 that would solve my problem instantly. Currently, the resource inspector only shows any usage of a buffer in an event, and your only option to find a certain range is to manually check all uses, which can be hundreds of manual comparisons. It would be amazingly useful to filter EIDs for certain ranges, and RenderDoc should have the information available to it to do that filter, since it knows all the buffer usages already, if it could compare copy offset/size, and any draw binding offset/size. That would be the dream, but at least being consistent with dec or hex throughout RenderDoc would help.

## Environment

* RenderDoc version: 1.26 https://github.com/baldurk/renderdoc/commit/c8b011344d300959bd768875f5a24f60db60caf0
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I think you might be giving more credit on how this is handled than is deserved 😄 . The heuristic is incredibly simple, just that whenever raw API parameters are displayed in the event browser and API inspector, unsigned integers are displayed with a function that detects simple constants like UINT32_MAX or UINT64_MAX, as well as with a threshold of `0xffffff` for displaying them as hex. There is nothing special about offsets and sizes except that they're more commonly high values, and crucially the display code has no knowledge over what values are offsets and sizes.

I can see the problem with the threshold, I really wasn't thinking about digging through the raw API details to be the primary method of getting any information, so it was more about trying to get the best display possible with as little information as is available. It probably does more harm than good though, so I'll remove it so that decimal is always used.

Also regarding this:

> It would be amazingly useful to filter EIDs for certain ranges, and RenderDoc should have the information available to it to do that filter, since it knows all the buffer usages already, if it could compare copy offset/size, and any draw binding offset/size.

That's technically true in the sense that the information is gatherable somehow, but not true in that there is currently no metadata or tracking of any of that. Only the current pipeline state is ever stored, not the pipeline state for every event or every action, and as above the meaning of any API parameters displayed is not stored so nothing can currently automatically differentiate between what's an offset or not.

If you were willing to write the logic for identifying which calls & parameters you wanted to filter it on, and you only wanted to check for 'direct' usage in a command (rather than indirect through a descriptor binding), then you could implement this kind of filter in a UI python extension. You could define a new event filter like `$bufferRange(0x71FDDD0, 0x71FDDD4)` and have it filter on either `vkCmdCopyBuffer` or `vkCmdBindVertexBuffers` or whichever other functions you wanted to check against.

**Comment by Zorro666** [comment]
Added support to choose how to format offset/size fields.
Default matches the current mode which is decimal for values below a threshold and hexadecimal above the threshold.
There is also "Decimal" and "Hexadecimal" option to force the formatting mode.

1b4b9ebc529894
