### ISSUE TITLE
It's there any plan to support openxr vulkan capture frame ?

### ISSUE THREAD

**Issue by tonykee** [baldurk/renderdoc#2929]
Hi sir 
    I'am a 3d engine graphic developer, now using renderdoc to capture mobile gpu frame,  I shall integrate openxr to support vr device,  such as oculus  quest2 , pico nero 3  and so on...   ,but I find renderdoc does not work to capture any frame, the capture button is disabled, I've searched on google, realized that only the renderdoc meta fork version can support capture frame oculus quest2 device,   any other device can not work with this fork version,   and I'am using vulkan for rendering api,  I think the OpenXR API is  khronos‘s  unified api, more and more vr producer implements the api  public , it's good for our engine's integrate the interface,   so I suggest renderdoc trunk version  to support the api, it's quite necessary

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
