### ISSUE TITLE
It's there any plan to support openxr vulkan capture frame

### ISSUE THREAD

**Issue by tonykee** [baldurk/renderdoc#2930]
## Description
I'am a 3d engine graphic developer, now using renderdoc to capture mobile gpu frame, I shall integrate openxr to support vr device, such as oculus quest2 , pico nero 3 and so on... ,but I find renderdoc does not work to capture any frame, the capture button is disabled, I've searched on google, realized that only the renderdoc meta fork version can support capture frame oculus quest2 device, any other device can not work with this fork version, and I'am using vulkan for rendering api, I think the OpenXR API is khronos‘s unified api, more and more vr producer implements the api public , it's good for our engine's integrate the interface, so I suggest renderdoc trunk version to support the api, it's quite necessary

## Environment

* RenderDoc version: 1.26
* Operating System: Windows 10
* Graphics API: vulkan1.1

**Comment by tonykee** [comment]
the demo this here, very simply,  it's odd that opengles model can capture frame, but vulkan can not
https://sdk.picovr.com/developer-platform/sdk/PICO_OpenXR_SDK_220.zip

**Comment by baldurk** [comment]
I'm not sure exactly what you are asking for here but it sounds like you want OpenXR support of some kind? You can see #2921 recently for more discussion but I have no plans to ever support OpenXR.

If you're on a desktop platform you can use a preview window that presents normally, which lets RenderDoc detect frame boundaries. If you're on a mobile device you can use [RenderDoc's in-application API](https://renderdoc.org/docs/in_application_api.html) to start and stop captures at custom points, to capture work that is otherwise offscreen as far as the graphics API is concerned.

**Comment by tonykee** [comment]
yes, I meet the same problem , like https://github.com/baldurk/renderdoc/issues/2921
just  now I can use oculus quest2  to debug gpu rending, real device debug is necessary
I hope renderdoc can do this things as renderdoc  meta fork version just do for more devices
and your last  advice use [renderdoc's in API](https://renderdoc.org/docs/in_application_api.html), I've no idea, I'll do study on it

**Comment by tonykee** [comment]
ooh, It's look's like that I'can define frame begin and end trigger by myself? 
that's great!  I will try it!
