### ISSUE TITLE
Stepping through drawcalls of a vkCmdDrawIndexedIndirectCount doesn't appear to be correct 

### ISSUE THREAD

**Issue by godlikepanos** [baldurk/renderdoc#2936]
## Description

I'm having an application that uses vkCmdDrawIndexedIndirectCount and I'm trying to inspect what each nested drawcall does by looking at the texture viewer. Stepping through the nested drawcalls doesn't appear to be correct. Clicking to the next drawcall sometimes clears the color buffer or it selectively removes previous drawcalls. Things appear to be a bit erratic. 

I think the following gif can illustrate the problem.

![renderdoc_mdi](https://github.com/baldurk/renderdoc/assets/2602423/8e481af9-fa79-43e4-bd73-b0e41844a872)

## Steps to reproduce

Here is a RenderDoc capture: https://drive.google.com/file/d/1LKPXQC2UdLl67LQRxWPcnUTM61_mN23r/view?usp=sharing

To see the issue navigate to the `GBuffer` tag and to the 1st vkCmdDrawIndexedIndirectCount drawcall. 

If the capture doesn't work please let me know and I can share instructions on how to build from source.

## Environment

* RenderDoc version: 1.26
* Operating System: Windows 11
* Graphics API: Vulkan
* GPU: nVidia 4080

**Comment by baldurk** [comment]
This is caused by non-determinism in the capture, the draw arguments are unpredictable and will change every time the capture is replayed. This is not something that RenderDoc can support, so this kind of randomness and unpredictability is the result. The effect is limited to anything between the points of divergence and convergence (abusing those terms to refer to the point where determinism stops & resumes), but when it affects the structure of the frame with draw parameters like this it will also behave inconsistently in that respect.

There's not much I can suggest if you need to introspect this non-deterministic work apart from having a debug mode that makes it deterministic - either inserting a sort to 'converge' sooner before the work you care about inspecting, or putting the generating work into a deterministic mode.

**Comment by godlikepanos** [comment]
Thanks for the answer. I wrongly thought that RenderDoc will use some pre-captured buffer for the draw params. Will add some sorting.

Going a bit on a tangent, maybe a visualization for the whole vkCmdDrawIndexedIndirectCount call could be useful as well.

**Comment by baldurk** [comment]
Pre-capturing a draw buffer would break when the geometry is also generated non-deterministically to match. You would have to then capture the geometry data as well. Then there's every chance that constant data is generated so you'd have to snapshot uniform buffers, but it would not be possible to determine just which buffer is used - especially if bufferDeviceAddress is used. Effectively the problem can move to requiring a full snapshot of all modified memory after every draw, which is not feasible.
