### ISSUE TITLE
Pixel History is not supported on OpenGL

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#294]
Whenever i tried it, clicking on "History" or "Debug" in the Pixel Context pane always gave me an empty event list, even on pixels that clearly have been shaded.

I have a GTX 750 Ti, driver version 364.72, Windows 10, using OpenGL. i also tested it with another random OpenGL app (tesseract) i had on the machine.

separated from #293

**Comment by cgrant78** [comment]
I've noticed the same thing too. I was going to log an issue related to this.

AMD RX 470 Crimson ReLive Edition 17.2.1

**Comment by baldurk** [comment]
Yeh as mentioned in #293, pixel history and shader debugging are only implemented on D3D11 currently. This issue is tracking for that feature being added.

**Comment by limingchina** [comment]
Any plan to support this? Is it not working in general for both windows and linux? Or it's a windows-specific issue? For me, the "History" and "Debug" buttons are grey. Is there any requirement for the shader compilation? E.g. optimization needs to be disabled?

**Comment by pippijn** [comment]
Any update on this?

**Comment by Trass3r** [comment]
A first baby step has been made: #2610

**Comment by baldurk** [comment]
Note that it is heavily incomplete and not guaranteed to be correct or stable, so do not file any bugs or comment here if you encounter problems.

It was added behind an opt-in config setting precisely to avoid having everyone try it immediately before it's ready and without proper understanding of its status. When it is ready for wider attention I will comment here - I didn't comment because it's not ready.

**Comment by baldurk** [comment]
Closed by #2865
