### ISSUE TITLE
Renderdoc renders differently from my standalone application

### ISSUE THREAD

**Issue by tigert1998** [baldurk/renderdoc#2941]
## Description

I am using OpenGL 4.6 to implement a little rendering engine. But I found that the captured backbuffer by renderdoc is different from my own standalone application. I found that this issue happens **ONLY** when I enable OIT (order independent transparency). When I disable OIT, they render the same. The OIT technique I implemented is the linked list based OIT, which stores all transparent fragments into a linked list, sort them by depth, and finally blends them according to opacity. 

Here are the images:

My standalone application renders like:
![](https://gcdnb.pbrd.co/images/pBeif4GDd4qp.png?o=1)

The renderdoc renders like:
![](https://gcdnb.pbrd.co/images/pNOp8bUZdZNU.png?o=1)

## Steps to reproduce

My little game engine is open-sourced at: https://github.com/tigert1998/tiger-game-engine. Build the model visualizer from the main branch can check this out. I also linked the captured rdc file here: https://drive.google.com/file/d/13A3A2RDDv-t10GpMtjgWoXaJsQ0dE2qB/view?usp=sharing.

## Environment

* RenderDoc version: 1.26
* Operating System: Windows 11
* Graphics API: OpenGL 4.6

**Comment by baldurk** [comment]
From a quick look I suspect this is because of the use of glTexImage2D to clear a texture via a buffer copy, which is not being recorded correctly and leading to the linked list going wrong. glTexImage2D and friends are rather horrible since they can be either creation or update depending on the context.

I'll try to get a fix in for this next week, but I might not be able to until later on. If you want a workaround in the meantime I'd suggest simply using a glClearBuffer call instead. Performance might not be a priority for you but I suspect a clear will also work faster than a buffer copy so it might be worth changing regardless.

**Comment by tigert1998** [comment]
Thank you so much for your instant reply. I did use glTexImage2D to clear the texture. https://github.com/tigert1998/tiger-game-engine/blob/main/engine/src/oit_render_quad.cc#L84

**Comment by baldurk** [comment]
Yes I know, that's why I was saying that's my guess of the problem having only looked quickly and without having tested a fix. I'm suggesting that you use a normal glClearBuffer for clearing instead as a workaround and potentially a general improvement.

**Comment by baldurk** [comment]
I believe that commit should fix the problem, at least it did when I tried to repro on your github though I had to hack a couple of things to get it to work.

**Comment by tigert1998** [comment]
Thank you so much for making such marvelous software!
