### ISSUE TITLE
Array out-of-bounds when `elemtype` is empty

### ISSUE THREAD

**Issue by mickbeaver** [baldurk/renderdoc#2946]
When loading the XML config, it is possible to have an empty string as the `elemtype` of an array. This causes us to index into the `types` array with an index of `-1`. On instrumented builds, this can cause an error.

Example XML config snippet:
```
  <DXBC>
    <Debug>
      <!-- DXBC.Debug.SearchDirPaths

Paths to search for separated shader debug PDBs.

Default value: '[]' -->
      <SearchDirPaths type="Array" elemtype=""></SearchDirPaths>
    </Debug>

```

https://github.com/baldurk/renderdoc/blob/35b13a8e8fd2a331854dba6da81a20452e142d6f/renderdoc/core/settings.cpp#L188

**Comment by mickbeaver** [comment]
Locally, I just have the following code:

```
    if(type == SDBasic::Array)
    {
      // Empty arrays may not have an elemtype. Default to String.
      const int32_t basicTypeIndex = basicTypeStrings.indexOf(obj.attribute("elemtype").as_string());
      type = (basicTypeIndex != -1) ? types[basicTypeIndex] : SDBasic::String;

```

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
