### ISSUE TITLE
Difficult to see what makes an application close

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2948]
## Description

In a simple case, the app performs exactly the same as it does outside of RenderDoc, and we can capture it and analyze.
If it doesn't behave the same, however, and specifically if it fails to start, it's dire needed to be able to see what's going on.

Here is what happens right now:
  1. I put the launch info, hit the launch button
  2. A window briefly pops up, prints some error in the console, then closes immediately
  3. Not seeing any logs inside renderdoc. The Errors and Warnings tab is empty.

In order to investigate this, I need to at least be able to see the output of the program.
I do know that, on Linux, I can start `qrenderdoc` from terminal, and it would contain the program output. This is not the same on Windows, unfortunately - the console detaches upon `qrenderdoc` starting.

Suggestion:
  - add a checkbox in the launch panel for "keep console window open after termination".

## Environment

* RenderDoc version: 1.27
* Operating System: Windows-11
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I'm not entirely sure if there exists a clean way of keeping the console open after the process has quit since it is owned by the target process, but either way this is outside the scope of what I want RenderDoc to handle.

I'd personally recommend having a better way of logging your error/warning messages, such as writing to a log file or using debug output (which would also have the benefit of being visible in CPU debuggers). If you really need the stdout/stderr then I'd suggest either adding the pause in your program or writing a .bat file to launch your program and then run `pause`, and launch that from renderdoc with child process capturing enabled.
