### ISSUE TITLE
Unable to debug using dxc compiled shaders?

### ISSUE THREAD

**Issue by vulkan101** [baldurk/renderdoc#2950]
I've recently moved my hlsl shaders (DX12 on windows/visual studio) to SM 6, some of them 6.6. I'm using the -Qembed_debug flag, but am unable to debug these shaders. When these were using SM 5.5, I could debug them without issue.
Is this expected?

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
