### ISSUE TITLE
RenderDoc crashes when loading a vulkan capture

### ISSUE THREAD

**Issue by Alihene222** [baldurk/renderdoc#2959]
When loading a capture for my vulkan application, renderdoc crashes with a segmentation fault. I ran RenderDoc through GDB, here is the output: https://pastebin.com/wWpxnkAd

RenderDoc built from source, version 1.27, https://github.com/baldurk/renderdoc/tree/367d55d88d332be1f1a40ff840166b583d483faa
OS: Ubuntu 22.04 LTS
GPU: Mesa Intel® HD Graphics 4000 (IVB GT2)
Vulkan version on system: 1.3.243
Vulkan version used by application: 1.0

The vulkan application:
[volcano.zip](https://github.com/baldurk/renderdoc/files/11771987/volcano.zip)

Steps to reproduce:
Run the application through renderdoc
Take a capture
Close the application

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
