### ISSUE TITLE
How renderdoc hook wglCreateContext?

### ISSUE THREAD

**Issue by POLO-huhu** [baldurk/renderdoc#2965]
## Description
How renderdoc hook wglCreateContext? This may not a bug strictly, but I really want to get your help. In **ApplyHooks** function, if dll named opengl32.dll, renderdoc will return. How wglCreateContext PFN been hooked by wglCreateContext_hooked PFN? 
## Steps to reproduce
win32_hook.cpp, in ApplyHooks function:
    // for safety (and because we don't need to), ignore these modules
    if(!_stricmp(modName, "kernel32.dll") || !_stricmp(modName, "powrprof.dll") ||
       !_stricmp(modName, "CoreMessaging.dll") || !_stricmp(modName, "**opengl32.dll**") ||
       !_stricmp(modName, "gdi32.dll") || !_stricmp(modName, "gdi32full.dll") ||
       !_stricmp(modName, "nvoglv32.dll") || !_stricmp(modName, "nvoglv64.dll") ||
       !_stricmp(modName, "vulkan-1.dll") || !_stricmp(modName, "nvcuda.dll") ||
       strstr(lowername, "cudart") == lowername || strstr(lowername, "msvcr") == lowername ||
       strstr(lowername, "msvcp") == lowername || strstr(lowername, "nv-vk") == lowername ||
       strstr(lowername, "amdvlk") == lowername || strstr(lowername, "igvk") == lowername ||
       strstr(lowername, "nvopencl") == lowername || strstr(lowername, "nvapi") == lowername)
      return;

## Environment

* RenderDoc version: v1.6
* Operating System: win10
* Graphics API: WGL

**Comment by baldurk** [comment]
If you only have a question about the code then that is not something that you should open an issue for. I can't provide personalised explanations of the code and answer questions about how it works - the code is open source for you to browse and explore, but you have to do that on your own and I can't feasibly provide support for learning it.

If you have a bug then please explain what the actual problem is, but it seems like you're saying yourself already that there is no bug. In future please do not open bug reports when you do not have an actual bug.
