### ISSUE TITLE
HLSL StructuredBuffer.GetDimensions bufinfo(structured_buffer) returns 0 for numStructs

### ISSUE THREAD

**Issue by calvindhsu** [baldurk/renderdoc#297]
`StructuredBuffer.GetDimensions` consistently returns 0 for `out uint numStructs`
https://msdn.microsoft.com/en-us/library/windows/desktop/ff471515(v=vs.85).aspx

**Comment by baldurk** [comment]
This opcode was just all sorts of wrong - it was swizzling based on the wrong operand (that didn't exist), then applying a return type format that isn't applicable for this opcode. It looks like just too much copy-paste from the OPCODE_RESINFO. I think that should fix this issue, at least it does on a toy sample I wrote.

Please check the next nightly build when you have a chance, and let me know if this sorts it out as you expect. Otherwise I'll close this issue after the next stable release.

**Comment by baldurk** [comment]
Closing this issue as the bug should be fixed in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
