### ISSUE TITLE
Adding working directory option to renderdoccmd

### ISSUE THREAD

**Issue by manu-silicon** [baldurk/renderdoc#298]
Currently if you need a program to start in a specific directory this is not possible as it will take the location of the executable as working directory. Unless I miss something I could not find a way to achieve that.

**Comment by baldurk** [comment]
I've revamped the renderdoccmd command line interface, and I've included setting the working directory as well as some other things that weren't supported before like where the capture will go and the capture options.

It's now less painful to add new options than it was before, since it started out as a hacky thing that didn't see much use on windows - on other platforms where command line is more used, it's much more likely to get use.

**Comment by manu-silicon** [comment]
Great news! Thanks a lot for adding this.

**Comment by baldurk** [comment]
Closing this issue as the feature was implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
