### ISSUE TITLE
Direct2D / 3D Program Crashes During ID2DCreateDevice Creation Under Renderdoc

### ISSUE THREAD

**Issue by kayomn** [baldurk/renderdoc#2982]
## Description

When loading the provided repro case with Renderdoc, the application fails to initialize the `ID2D1Device` with the following Windows error (presented as a message box):

![image](https://github.com/baldurk/renderdoc/assets/15730577/c8727392-c2a7-4b10-891a-2a2162a5e2fb)

My understanding from looking at Microsoft's documentation is that `E_NOINTERFACE` isn't listed a potential error that any of the Direct2D device creation functions can throw, so I went a little further to investigate to try and gather more information.

Attempting to run D2D's debug layer to find what's happening yields no information, but a logged Renderdoc warning can be observed after attempting to create the device.

![image](https://github.com/baldurk/renderdoc/assets/15730577/4a84f959-a686-422f-9f4a-f235cc12f114)

Unless there is some critical misuse of the Direct2D API that I am not aware of that Renderdoc isn't reporting back, I wouldn't expect it to crash. My understanding is Direct2D is beyond the scope of the project, so I'm confused as to why Renderdoc is trying to add hooks to it unless it's accidental.

## Steps to reproduce

1. Download the provided [repro case](https://github.com/baldurk/renderdoc/files/12051216/Repro.zip).
2. Open with Visual Studio or an equivalent IDE.
3. If prompted, do not upgrade the project files to a more recent version.
4. A debug executable using the project.
5. Run the application under Renderdoc with the working directory set to the same directory as the executable.
6. Click "Ok" on any message boxes to progress through the stages of the crash (or use them as a chance to attach a debugger remotely).
7. Observe the program crash.

## Environment

* RenderDoc version: 1.27
* Operating System: Windows 10 Version 22H2
* Graphics API: Direct3D 11 & Direct2D 1.1

* Processor: AMD Ryzen 9 5900X 12-Core Processor @ 3.70 GHz
* Graphics Card: Nvidia GeForce RTX 3080 Ti
* Installed RAM: 64.0 GB

**Comment by baldurk** [comment]
My understanding is that Direct2D is not exactly a real separate API, but more like a software library that is based on D3D11. At least it uses D3D11 heavily, and in particular it uses undocumented private Microsoft-only interfaces which cannot be captured. RenderDoc blocks this to ensure that the program can be captured, and gracefully notifies any calling code that the interface is unsupported, and it seems D2D does not have a fallback for this case to not rely on those undocumented interfaces.

**Comment by lhecker** [comment]
Hey @baldurk, I just recently updated to 1.27 and started hitting this issue. On 1.26 the exact same code works just fine. In my case the `E_NOINTERFACE` is returned by `ID2D1Factory::CreateDxgiSurfaceRenderTarget`. Given that it still worked in the most recent previous version, do you think we could reopen the issue?
Do you have a suspicion what could've caused this regression? I'd be happy to help investigate this and contribute any changes necessary to make it work again. 🙂 Unless you meant to imply that this was done intentionally, because of the undocumented interfaces... In that case would an opt-out be reasonable to add?

**Comment by baldurk** [comment]
If this behaviour has changed in the most recent version I would guess it is caused by the fix for #2923 blocking the undocumented interface there, but I haven't investigated. Possibly D2D uses the same interface but purely by coincidence you were getting lucky and not triggering a path that crashes.

It's not possible to conditionally allow undocumented/private interfaces depending on the caller, and indeed it's quite possible that D2D would crash in earlier versions the same way if the right code path was hit. There's no safe fix here, so this cannot be supported and an opt-out that can easily and unpredictably cause crashes is not something I would want to have.

The real fix here would need to be D2D not using private undocumented interfaces.

**Comment by whbwhb521** [comment]
I have also encountered the same problem. May I ask how this will be resolved

**Comment by baldurk** [comment]
As above this can't be fixed unless Direct2D changes. Direct2D relies on undocumented private interfaces which it is impossible for RenderDoc to support.

In future please do not comment on old closed issues. If you have a bug to report please open a new issue with full information and a reproducible test case.
