### ISSUE TITLE
How to add a external vulkan validation layer before the renderdoc capture layer on android

### ISSUE THREAD

**Issue by linglingzhou** [baldurk/renderdoc#2984]
I want to use the renderdoc to capture some applications data. I need to add a external layer or the validation layer to make the application work. How can a adding a external layer before the renderdoc capture layer on android?
For the desktop, the renderdoc has the 'environment variables' item of  'launch application' window to support the status. But for android,  the 'environment variables' item is disable.  
In the code, renderdoc enables the layers on per-app basis by using the command which is ' adb shell settings put global gpu_debug_app VK_LAYER_RENDERDOC_Capture'. 

## Environment
* RenderDoc version: 1.27

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
