### ISSUE TITLE
Status on macOS

### ISSUE THREAD

**Issue by manu-st** [baldurk/renderdoc#299]
I was trying to compile on macOS and found a few minor issues that were easy to fix. However running renderdoccmd to capture it doesn't seem to work. Thus this issue to see if this is expected or not.

**Comment by baldurk** [comment]
Yeh currently OS X might compile but that's about it I'm afraid. I added simple compiling support with some patches I got from @zorro666, but I guess there are issues that have cropped up in recent commits because no-one is actively testing it. I might try and add it to travis CI some time, or if you want to PR the fixes that would be welcome.

At the moment though, it indeed won't capture. A bunch of stuff in the GL code is [stubbed](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/gl/gl_hooks_apple.cpp) [out](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/gl/gl_replay_apple.cpp). Particularly this involves whatever library is the equivalent to glx/wgl on apple - that needs to be both hooked for capture, and implemented for creating windows on replay.

The other problem is that modern opengl isn't supported on OS X, and even the opengl version that is supported is buggy and unofficially not supported either (no bugfixes etc). Unless vulkan support appears on OS X this means the only way renderdoc would be useful is by implementing metal support.

This isn't out of the question, but it's low priority enough that it's not going to be seen any time soon - realistically the vast majority of developers on OS X are only there as a porting target, and have access to linux or windows to debug on. I could be wrong, but I think suspect there are other more important features to be prioritised above metal support.

**Comment by jherico** [comment]
If I were willing to integrate something into my application to facilitate this, would that make it any easier?  I already funnel all my GL calls through GLAD.  Would it be possible to create a GLAD-like drop-in replacement for an app that would allow capture and playback?

**Comment by baldurk** [comment]
That would at least remove the need to implement hooks on GL, but you'd still have the problem that a few extensions required for replay currently aren't available on OS X.

**Comment by baldurk** [comment]
Just updating, GL hooking is now (tentatively) implemented on mac. In my testing I'm able to capture simple programs and the replay works on windows for example.

There's still a lot of hacks though e.g. the window size is currently hardcoded and not queried, and replay it a fair bit off. I'm not prioritising working on this but I experimented and got some progress made while looking at vulkan support on mac.

**Comment by Saahiljeet-Singh** [comment]
@baldurk : can you please share your solution for Mac.
Would it be able to capture Open GL calls specially Geometry shaders.
Also, if you anyone can suggest a good tool to debug Geometry shaders in Open GL on mac ?

**Comment by baldurk** [comment]
I don't know what solution you mean. As I mentioned in the last comment capture may work to some limited degree (although I am sure there are bugs) but replay doesn't work natively on macOS.

**Comment by baldurk** [comment]
Closing in favour of #1272 which should contain current status for GL & Vulkan capture on Mac.
