### ISSUE TITLE
visualize texcoord with texture

### ISSUE THREAD

**Issue by qiankanglai** [baldurk/renderdoc#2998]
## Description

Visualizing textures with uv is useful in cases like check corner pixels. 
Maybe this could be done with Mesh Viewer: since we can already visualize texcoord with `Select As Position`, just applying textures as background just works.

Any suggestion for this? If it sounds reasonable, I could try implementing this in part time.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
