### ISSUE TITLE
Could not use other vulkan layers on top of capture layer on Android

### ISSUE THREAD

**Issue by franklei01** [baldurk/renderdoc#3001]
## Description

We have an application which needs one customized layer to make it work on Android. Everything works fine without RenderDoc.

We are trying to capture this application by RenderDoc on Android , but failed to launch application due to our own layer could not be found in this case.

We use the following two methods to enable our layer before launching application in RenderDoc, but both of them do not work.

1. Per-app basis
- adb shell settings put global enable_gpu_debug_layers 1
- adb shell settings put global gpu_debug_app <apk_name>
- adb shell settings put global gpu_debug_layer_app <apk_name>
- adb shell settings put global gpu_debug_layers <our_layer_name>
or
- adb shell settings put global gpu_debug_layers <our_layer_name:VK_LAYER_RENDERDOC_Capture>

2. Global layer
- adb shell setprop debug.vulkan.layers <our_layer_name>
or
- adb shell setprop debug.vulkan.layers <our_layer_name:VK_LAYER_RENDERDOC_Capture>

The main reason seems to be in AndroidRemoteServer::ExecuteAndInject(),
1. gpu_debug_layers is hard-coded as following:
Android::adbExecCommand(
          m_deviceID, "shell settings put global gpu_debug_layers " RENDERDOC_VULKAN_LAYER_NAME);

2. global layer are set to null
Android::adbExecCommand(m_deviceID, "shell setprop debug.vulkan.layers :", ".", true);

I am wondering if it is possible to read predefined gpu_debug_layers value first and add this value before RENDERDOC_VULKAN_LAYER_NAME in AndroidRemoteServer::ExecuteAndInject() to give a chance to make other layers work with capture layer?

## Steps to reproduce

1. Find a debugable vulkan application which can work well with a layer (for example validation layer) on Android.
2. Enable the layer by above two methods.
3. Open RenderDoc, connect android device in RenderDoc.
4. Launch that vulkan application to check validation layer does not work as before.

## Environment
* RenderDoc version: v1.27 (official binary release)
* Operating System: Ubuntu 22.04
* Graphics API: Vulkan
* Android version: 13

**Comment by baldurk** [comment]
No RenderDoc does not support interoperability with other implicit layers on Android, so this is not intended to work. Due to Android having its own broken customised loader and layer system instead of using the normal proper loader, RenderDoc only allows the use of its own layer being activated implicitly while it is active. Similar to how it is not possible to use Android Studio at the same time as RenderDoc because that tool requires exclusive access of adb connections.

Provided that the layer is not required for the captured commands itself and only provides additional functionality (like the validation layers), you may be able to enable it explicitly at capture time via `vkCreateInstance` and embedding it in your application. It will then be stripped out and not used on replay as it will be unavailable there.

**Comment by franklei01** [comment]
Understand your concerns.

Thanks for pointing out this alternative way.
But unfortunately, we still need to support those applications w/o source code by our layer.

Is it possible to add a debug/experimental feature for this in the UI which is disabled by default and let the user to enable it explicitly?
This should work from my naive point of view, but maybe it breaks RenderDoc design principle.

**Comment by baldurk** [comment]
No I don't want to add an option that I believe will likely cause problems, especially on a platform like Android that is so terrible and broken that it barely works normally - some devices have removed the layer functionality entirely let alone allowing multiple layers to co-exist.
