### ISSUE TITLE
Samsung Galaxy Z Fold4 / Android 12 / Can't select executable properly

### ISSUE THREAD

**Issue by MarkMendell** [baldurk/renderdoc#3006]
## Description

When I browse for an application in Android, it hangs for a bit, then the file explorer appears but the replay context switches back to local. (I am still browsing the apps.) Then when I choose the app, it prepends the path with C:\...\RenderDoc\ and launching the activity subsequently fails. The workaround is to write down the app name, and type it manually in the path instead of browsing. (So the file browser cannot be used for selecting, only for browsing.)

## Steps to reproduce

1. Open RenderDoc.
2. Choose the phone under remote host.
3. Click browse for apps.
4. Observe that by the time it selects, the host has switched back to local.
5. Select an activity.
6. Notice the executable path is C:\... <android app>

## Environment

* RenderDoc version: v1.27, also nightly 2023_07_28_a6fed120_64
* Operating System: Windows 10 Pro 21H2, Android 12, One UI
* Graphics API: Vulkan
* Android Version: Android 12, One UI 4.1.1
* Phone: Samsung Galaxy Z Fold4 SM-F936U1

https://github.com/baldurk/renderdoc/assets/6289391/beadb542-563c-433d-a391-190c379e3275

(The file browser itself was not captured by the recording, from 0:17-0:25)

(This was the root cause of https://github.com/baldurk/renderdoc/issues/3005)

**Comment by baldurk** [comment]
This is really an Android flaw, since it's such a completely garbage platform. On some devices enumerating installed programs can take so long that it hits a timeout on the device due to lack of communication. This should complete in a fraction of a second but sometimes it takes 5+ seconds. I've seen sometimes things get cached and it is faster after the first time, though not always. At least on my test device this is 2 seconds which is much slower than it should be but within the timeout period.

That commit will at least make the manual workaround unnecessary - I presume you meant to say you were deleting the path rather than manually typing out the package name, but with that commit it at least won't treat the executable selected as a local path and normalise it when such a disconnect happens. I also added a couple of extra pings before/after the adb command to try and reduce the chance of a timeout, though it's an imperfect solution at best.

**Comment by MarkMendell** [comment]
Thanks, the problem is fixed.
