### ISSUE TITLE
Pixels in pixel context widget get larger in higher miplevels

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#301]
The pixel's size in the pixel context widget get larger in higher miplevels, which is not helpful.

a side effect is that when heavily enlarging a texture and then rightclick-dragging inside a pixel, the context widget actually scrolls although i stay in the same pixel. screenshot illustrating this:

![2016-07-11 14_55_15-mfs-viewer_2016 07 11_11 40 18_frame321799 rdc - renderdoc unofficial release v](https://cloud.githubusercontent.com/assets/1891915/16731404/2c6fe50e-4778-11e6-89fa-4cd8863fe030.png)

i'd expect the widget to have a single pixel selected, not some small part inside it.

**Comment by baldurk** [comment]
Changed as you suggest, since indeed it doesn't make any sense. I think I noticed this before some time but didn't get around to fixing it properly and forgot about it so it's always good to get a reminder :smile:. I might change it again to make the pixel context more zoomed in for lower mips (since it's kind of silly at 2x2, 4x4) but for the moment I'd rather keep it a consistent size than have the zoom flip back and forth:

![image](https://cloud.githubusercontent.com/assets/661798/16739857/726c2c10-479c-11e6-9ac6-eca658400d35.png)

**Comment by karyon** [comment]
works as expected for me.
