### ISSUE TITLE
Renderdoc failed to capture cubemap and compressed textures on AMD RX 6700XT

### ISSUE THREAD

**Issue by dreamelon** [baldurk/renderdoc#3013]
## Description
I'm debugging GL_Texture_Zoo test on AMD RX 6700XT. There are two kinds of failures including cubemap and compressed textures. And I found the root cause was renderdoc failed to capture a valid trace in which cubemap textures are all black.  In fact, renderdoc could capture a valid trace in only the first frame, but always got corrupted results in the next frames.

There are two traces for comparison.
[cubemap.zip](https://github.com/baldurk/renderdoc/files/12248110/cubemap.zip)

## Steps to reproduce

1. Build the demos test
2. Use renderoc to launch GL_Texture_Zoo
3. Capture the first frame by selecting Queue Capture and then capture a frame after a while
4. You could see the first trace is valid but the second is corrupted in which the cubemap textures are all black

## Environment

* RenderDoc version: v1.28
* Operating System: Windows
* Graphics API: OpenGL
* Grapchis Card：AMD RX 6700 XT

**Comment by baldurk** [comment]
This is a known AMD driver bug.

**Comment by dreamelon** [comment]
> This is a known AMD driver bug.

Hi @baldurk, 
I am actually an OpenGL driver engineer from AMD. I don't find any valuable clues about where it is broken from driver side. When debugging the corrupted trace, the uploading data of textures are all null. But otherwise, renderdoc did record the uploading data in the first frame. I'm curious why renderdoc could get the data in the first frame but fails to retain it in the next frames. After all the output image looks alright too.
Could you please clarify how renderdoc records OpenGL commands or add more details about your conclusion?

**Comment by baldurk** [comment]
The important difference is that if you capture the first frame then you capture the texture initialisation and data upload commands directly, which go through fine as they are captured directly on the CPU. If you capture any subsequent frame then RenderDoc needs to copy and capture the texture contents, and that fails for some texture types/formats. From memory I believe it hits an unexplained and (as far as I can tell) wrong GL_INVALID_OPERATION trying to do `glCopyImageSubData` to copy from the textures into a readback texture.

I believe this bug was reported to AMD years ago, but there are quite a lot of known bugs in the RenderDoc autotests on AMD so I don't remember if or when this one was reported.

**Comment by dreamelon** [comment]
Thanks a lot! really helpful information.
