### ISSUE TITLE
Segfault with Vulkan debugging and textures

### ISSUE THREAD

**Issue by 3DDean** [baldurk/renderdoc#3020]
## Description
In short loading a capture causes render doc to seg fault. I think it has something to do with textures because I can get it to load if I compile from source and remove some stuff from the TextureViewer function UI_PreviewResized. This seems to allow me to interact with  render doc until I click on the texture viewer tab. This causes render doc to crash, due to a segfault.

## Steps to reproduce

Not sure if this is reproducible on other systems, but this capture can cause the crash
[test.zip](https://github.com/baldurk/renderdoc/files/12314018/test.zip)

## Environment

* RenderDoc version: 1.28
* Operating System: Pop!_OS 22.04 LTS
* Graphics API: Vulkan
Source compiled version is version 1.28
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
GPU:  Iris Xe Graphics

I have also encounter the bug on the release binary on versions  1.28, 1.27, 1.24

The following is the modifications I made to render doc to get it 
```
void TextureViewer::UI_PreviewResized(ResourcePreview *prev)
{
  QSize s = prev->GetThumbSize();

  ResourceId id = prev->property("id").value<ResourceId>();
  Subresource sub = {0, 0, ~0U};
  sub.mip = prev->property("mip").toUInt();
  sub.slice = prev->property("slice").toUInt();
  CompType typeCast = (CompType)prev->property("cast").toUInt();

  m_Ctx.Replay().AsyncInvoke(lit("preview%1").arg((qulonglong)(void *)prev),
                             [this, prev, s, sub, id, typeCast](IReplayController *) {
                            //Commented out this
                            //    bytebuf data =
                            //        m_Output->DrawThumbnail(s.width(), s.height(), id, sub, typeCast);
                            //    // new and swap to move the data into the lambda
                            //    bytebuf *copy = new bytebuf;
                            //    copy->swap(data);
                            //    GUIInvoke::call(prev, [prev, s, copy]() {
                            //      prev->UpdateThumb(s, *copy);
                            //      delete copy;
                            //    });
                             });
}
```
## Possibly unrelated information
At some point renderdoc opened a window complaining about a gpu mismatch between the capture and renderdoc. I don't remember the order, but it was on was llvm_pipe 15.0.7 256 and one was Intel Xe Graphics(TGL GT2). In this message it also complained about an image2D being larger than the memory it is being bound. The image size was 0x20024 and the memory's size was 0x20000

**Comment by Zorro666** [comment]
I notice there is a Vulkan Validation warning when opening the capture. It would be great if you could run your application without RenderDoc attached and with the Vulkan validation layers enabled and fix any errors and ideally warnings that get reported ie.

```
Validation Error: Missing extension required by the device extension VK_KHR_buffer_device_address: VK_KHR_device_group. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.3.250.1/linux/1.3-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)
```

It would be helpful if you can run your application on a different driver ie. nVidia and try capturing and replying on that driver.

Opening the capture with the llvm_pipe driver results in a crash inside the llvm_pipe driver when the Texture Window is displayed, there are no validation errors or warnings triggered which hints at a driver (or validation layer) problem.

I think this might be a specific issue to do with the llvm_pipe driver or something specific to your application and perhaps a problem with the Vulkan API usage. It does not look to be a RenderDoc issue.

Opening the capture with the AMD or nVidia driver results in an error due to a failed `vkMapMemory` call and also a Vulkan validation warning

```
vkMapMemory(): Mapping memory without VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT set. Memory has type 0 which has properties VkMemoryPropertyFlags(0) The Vulkan spec states: memory must have been created with a memory type that reports VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-vkMapMemory-memory-00682)
```

If I change the replay code to work around that error then on Windows + nVidia driver the capture loads and replays i.e.
![image](https://github.com/baldurk/renderdoc/assets/39392/327a7be2-0fd4-4bec-b64e-4ed044e04d01)

**Comment by Zorro666** [comment]
Using the same replay code tweak allows the capture to be loaded and replayed on Linux with AMD or nVidia driver, however llvm-pipe crashes in the same place.

**Comment by Zorro666** [comment]
Investigating this further, this is caused by an llvm_pipe driver bug.

A solution is to capture & replay using a different driver (not llvm_pipe).
