### ISSUE TITLE
Inconsistency in stencil state display between OpenGL and DX11 drivers

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#303]
When viewing a DX11 capture, the stencil masks and ref value are displayed as hex values; when viewing an OpenGL capture, the masks and ref are displayed in decimal. It would be nice if the OpenGL driver used hex values same as DX11 - that would make debugging OpenGL ports a little easier. Thanks!

**Comment by baldurk** [comment]
Whoops! This was a silly oversight, because the GL refs/masks are per-face so they went in the table. I think that commit should fix this issue.

Please take a look at a nightly build or compile yourself when you have a chance, and let me know if this sorts it out as you expect. Otherwise I'll close this issue after the next stable release.

**Comment by jshofmann** [comment]
Works great, it's exactly what I wanted, thanks!
