### ISSUE TITLE
RenderDoc crash when trying to capture nvidia perf counter from perf counter view

### ISSUE THREAD

**Issue by luckyyang-github** [baldurk/renderdoc#3035]
## Description
RenderDoc crash when trying to capture nvidia perf counter from perf counter view

first I enabled all nvidia counters, it crashed.
then I tried to remove some nvidia counters, it still crashed
then I removed all nvidia perf counters, it worked.

## Steps to reproduce
RDC capture is uploaded to here : https://renderdoc.org/bugreporter/report/Q63OEozU4l366

1. use Renderdoc v1.28 to open the capture
2. goto perf counter view, 
3. enabled all nvdia perf counter
4. click sample counters
5. Renderdoc crashed

## Environment

- RenderDoc version: v1.28
- Operating System: Windows10
- Graphics API: DirectX11
- GPU RTX NV3070
- NV Driver 31.0.15.3623

**Comment by baldurk** [comment]
If this crash only happens when enabling nvidia's perf counters you will need to contact nvidia to ask for help with the problem. The crash is happening in their driver and both the integration/implementation of those counters and the library behind them are nvidia's responsibility.

EDIT: It is possible this problem is related to the capture being created on "Moore Threads MTT S80" and not an nvidia GPU. I would recommend making the capture on an nvidia GPU and seeing if that helps.

**Comment by luckyyang-github** [comment]
thanks for the advice!
