### ISSUE TITLE
Multiple issues with custom shaders

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#304]
heh, pressed enter when i shouldn't have :)

1. the selected custom shader always stays the same when switching textures. e.g. select texture A, select shader A, then select texture B, shader A is still selected (that might be ok, but i'd expect "RGBA" the default, to be selected), so select shader B, and switch back to texture A, shader B is still selected and THAT's the annoying part.

2. i created the first custom shader a week ago. today i tried to create a second one and was heavily confused why the "add custom shader button" was grey. i needed quite a few minutes to remember that the dropdown itself is a text field. so i replaced the name of the current shader with something else and then pressed the button, which felt really weird. i'd expect the button to always be available, and ask me for a name when pressed.

3. is there a way to access the slice/face setting in opengl custom shaders? i couldn't find one and hard-coded the slice i wanted to access in a 3d texture.

4. that gl_FragCoord should be used to access the input shaders might be obvious to some, but it wasn't to me :) i was used to uv coordinates as well, and when i read in the docs that this parameter exists only for direct3d, i thought "well thanks and what should i do instead?". a sentence like "on openGL, use gl_FragCoord instead" would be nice.

let me know if i should create separate issues.

**Comment by baldurk** [comment]
I think those commits should sort out each point. I'm not sure I want to actually have a pop-up prompt for the shader name but I made it so that the button is always enabled and will throw up a message box and blank out the entry box. That way if you're not clear or forget to enter the name then you'll be reminded.

It's probably less of an issue with 1. fixed because you won't have a custom shader left-over from elsewhere, so the box will start blank.

The last one I think is simply that at the time I wasn't aware of the location matching in GL (I think I was working with by-name matching at link time) so I didn't think there was a good way to define UV inputs in GLSL that would work with a custom shader, like semantic matching in D3D.

**Comment by karyon** [comment]
wow that was fast, thanks!

i'll verify hopefully tomorrow.

**Comment by baldurk** [comment]
You caught me at just the right time as I was starting work today :smile:.

**Comment by karyon** [comment]
two remarks: the SliceFace and multisample parameters (and actually, the uv parameter as well) do not appear in the "insert code snippet" menu.

also, the `: SV_Target0` in the GLSL code in the last commit seems to be a copypaste leftover?

otherwise i'd say all four issues are fixed!

**Comment by baldurk** [comment]
Yes you are right on both counts :).
