### ISSUE TITLE
Renderdoc crash when replaying with UE5.3.2

### ISSUE THREAD

**Issue by wangyongxina** [baldurk/renderdoc#3104]
## Description

UE 5.3.2:
I'm using github 5.3 branch, SHA1 : 83b91c69da1c2f9233c3ce5becf22b72b9a612de

Renderdoc: 
1.29 with renderdoc.dll (TAG v1.29) applied https://github.com/baldurk/renderdoc/commit/ecd47ca40c2282371818d6462f2582124fbbd3ff patch

![image](https://github.com/baldurk/renderdoc/assets/1614448/24118fd6-609d-4ad2-8341-1e4ef2ccd47c)

I'm trying to fix https://github.com/baldurk/renderdoc/issues/3092 this issure. so I applied patch.

## Steps to reproduce

1. Launch UE Editor and enable renderdoc
2. capture snapshot.
3. after loading snapshot, renderdoc crash

## Environment

* RenderDoc version: 1.29
* Operating System: win11
* Graphics API: directx12

NVidia driver : 546.01

**Comment by wangyongxina** [comment]
Creating default level could reproduce this bug. I can post snapshots file if you need

**Comment by Zorro666** [comment]
Thanks for the report and updates. It would be very helpful if you can recreate this with a stock released version of UE5 instead of from a git branch and locally compiled (it makes recreation much simpler).

It would also be helpful to share the capture file that is crashing for you, then the file can be investigated and debugged.

To help with testing and to make sure we are all using the same versions it would be helpful to try using this nightly build of [RenderDoc](https://renderdoc.org/autobuilds/v1.x/2023/RenderDoc_2023_10_29_aec25cfc_64.zip). It has the fix for UE5 and nVidia in the build and has been shown to work for other reports which had crashes on nVidia and UE5.

**Comment by wangyongxina** [comment]
I've download stock released version of UE5.3.1 from Epic Game Launcher, Created default level, capture snapshot
![image](https://github.com/baldurk/renderdoc/assets/1614448/e2b68753-1e01-408e-a235-01c55cb768b2)
https://renderdoc.org/autobuilds/v1.x/2023/RenderDoc_2023_10_30_aec25cfc_64.zip
![image](https://github.com/baldurk/renderdoc/assets/1614448/a686de29-cae9-4e25-94d1-091304f58831)

**Comment by wangyongxina** [comment]
I compiled renderdoc.dll, the crash stack is below:
![image](https://github.com/baldurk/renderdoc/assets/1614448/834da3c2-947e-4a7f-8386-deae9a14ef4d)
I'm trying to find some place to hold the snapshots file, so you can download and test it.

**Comment by baldurk** [comment]
Are you forcibly enabling the debug layers in D3D12? what happens if you don't force them on?

**Comment by wangyongxina** [comment]
> Are you forcibly enabling the debug layers in D3D12? what happens if you don't force them on?

by disabled  this option
![image](https://github.com/baldurk/renderdoc/assets/1614448/5125420c-d98c-4634-a0e2-25ac36ab7b52)
It ok now. thanks.

**Comment by baldurk** [comment]
Then it looks like this is a bug in the D3D12 validation layers and not a RenderDoc bug. I strongly recommend that you do **not** force the validation layers on for all captures. Only enable it on a per-capture basis as necessary, and be aware that RenderDoc does not handle invalid API use so it may have false positives and false negatives. I would suggest using the validation directly against your program for best results.
