### ISSUE TITLE
Doom Demo Vulkan support?

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#311]
Hi,
I have Doom Demo with Vulkan support installed via Steam and seeing 0.30 release notes mention some Vulkan Doom support I have installed Renderdoc 0.3..
can't make Renderdoc hook into Doom Demo by launching either:
C:\Program Files (x86)\Steam\steamapps\common\DOOM Demo\DOOMx64.exe
or
C:\Program Files (x86)\Steam\steamapps\common\DOOM Demo\DOOMx64vk.exe
I have also tried disabling/enabling Steam in game launcher but no success..
Finally I checked option "Hook into children" in case would help but no success..

Anyway vkQuake is working so Renderdoc is correctly installed..
Is that due to DRM in Doom?

**Comment by baldurk** [comment]
RenderDoc does work fine on the full DOOM game, so I imagine it would work on the demo too.

Generally injecting into retail applications is not supported since it's a bit of a grey area and I don't want to encourage nefarious use (even if this isn't). Steam games are launched from steam.exe itself even if you run the exe, which is why you're having trouble. I'd suggest perhaps you look at the global process hooking functionality, but otherwise actually capturing doom is up to you.

If you have any problems with the capture/replay, then you can open a bug for that.
