### ISSUE TITLE
Resizing texture viewer is slow.

### ISSUE THREAD

**Issue by AbdullahAmrSobh** [baldurk/renderdoc#3110]
## Description
I often like to view both the texture viewer and the pipeline state viewer side by side. The issue is, when I drag the texture viewer right sash to resize, RenderDoc becomes unresponsive, I think what happens here is that RenderDoc recreates the entire texture objects, for each resize step. 
![image](https://github.com/baldurk/renderdoc/assets/9056576/ddcac0f6-299a-4a97-9b68-cf2e4b658c43)

I think RenderDoc can only recreates the texture on mouse release, instead of at each resize event. 

## Environment

* RenderDoc version: v1.29
* Operating System: Win11 x64
* Graphics API: DirectX11

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. When filing a bug you should choose the bug report option and fill in the information for a bug report, do not the feature request option.

Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
