### ISSUE TITLE
Add support for glEGLImageTargetRenderbufferStorageOES

### ISSUE THREAD

**Issue by MaxVerevkin** [baldurk/renderdoc#3116]
## Description

This function is defined in [OES_EGL_image](https://registry.khronos.org/OpenGL/extensions/OES/OES_EGL_image.txt) extension. It binds a renderbuffer to a given EGLImage. A request to implement glEGLImageTargetTexture2DOES (#2726) (which is part of the same extension) has been closed https://github.com/baldurk/renderdoc/issues/2726#issuecomment-1460032613:

> From email discussion this extension is extremely badly designed to an extent that I had not fully appreciated, in particular that external textures are considered an entirely separate fundamental type of texture of the degree that they are accessed via a different type in shaders. As opposed to every other graphics API and several other supported GL extensions where they are normal textures, but created/initialised in a different way to perform the import operation.
> ...
> The conclusion I've come to is that this means a significant amount of implementation cost and maintenance burden which I do not feel is justified by the value of supporting this extension.

glEGLImageTargetRenderbufferStorageOES does not interfere with textures, so maybe it has greater chances of being implemented.

## Environment

```
$ renderdoccmd version
renderdoccmd x64 v1.29 built from NO_GIT_COMMIT_HASH_DEFINED
Packaged for Arch (1.29) - https://archlinux.org/packages/renderdoc
APIs supported at compile-time: Vulkan, GL, GLES.
Windowing systems supported at compile-time: xlib, XCB, Vulkan KHR_display.
```

* Graphics API: OpenGl, EGL.

**Comment by baldurk** [comment]
GL extensions are not pick-and-choose, it is not legal to implement one function in an extension but not another. The only valid way to report an extension as supported is to handle all functionality it implements. The other issue and pull request were badly titled as I don't think the reporters fully understood entirely how GL extensions worked as they only asked about the function that they were calling themselves and so saw an error about - especially as calling the function in the first place indicates that their code was not correctly checking for extensions in the first place.

This request is then still the same - to implement `OES_EGL_image` - and the situation is the same as in the comment you quoted. Realistically I do not see this ever being valuable enough to be worth the cost of the implementation due to how badly designed the extension is.

**Comment by MaxVerevkin** [comment]
> due to how badly designed the extension is

Sorry for off-topic question, but do you happen to know a better way to render to an EGLImage?

**Comment by baldurk** [comment]
No sorry, I'm not familiar with EGLImages at all.
