### ISSUE TITLE
"Failed to open rdc for replay" on local capture

### ISSUE THREAD

**Issue by mcclure** [baldurk/renderdoc#3124]
## Description

On attempting to display a frame capture taken from a locally running application, I get this error

![Screenshot from 2023-11-09 14-44-07](https://github.com/baldurk/renderdoc/assets/277318/8f527048-9091-47c7-9a99-a17fd9f78376)

There was no additional error text, for example nothing seems to have been printed to stderr.

**Note:** It is possible that the answer to this is going to turn out to be "it did not work because you were running on Wayland and Wayland is not supported". **If this is the case, my "expected behavior"** is that there would be a more specific error message, such as "Failed to open [rdc] for replay: This is a capture of a Wayland app, which is not supported in Renderdoc." (Although it is reasonable you cannot support all configurations, it is also reasonable to expect inline guidance as to when and how we have violated the supported configuration, so we can correct our configuration to a supported one.)

## Steps to reproduce

I am on an almost totally stock installation of Ubuntu 23.10. I am using the Wayland desktop environment, which is the default in 23.10 (I have not at this second investigated whether it is out-of-box possible to run in an X11 environment as it was in 23.04). I download a TGZ of RenderDoc v1.29 from the website, unpack it to `~/usr/renderdoc_1.29`, and run it with `~/usr/renderdoc_1.29/bin/qrenderdoc`.

I have a Rust program I want to debug, targeting the "wgpu" WebGPU framework. You can find the test application [here](https://github.com/mcclure/webgpu-tutorial-rs/tree/webgpu-tutorial-iced-debug), commit [f83d4c2](https://github.com/mcclure/webgpu-tutorial-rs/commit/f83d4c2a0bf71db7dd67d2c03e508387e7a6bcef). (**Warning**, this application currently will emit a loud sound at launch.) It can be run with a simple `cargo run`. The test app is supposed to display a scrolling black-and-white diagonal grid, and on top of that the text "TESTING DEBUG UI". In the current revision, the text is not seen (this is the problem I wish to debug in RenderDoc). Because this application targets the WebGPU API, and is intentionally designed to use features not available in WebGL, I would expect it to be running in Vulkan, *but* wgpu on desktop supports both Vulkan and OpenGL backends so it's possible I have accidentally configured the app to run in the OpenGL fallback mode. (In an ideal world RenderDoc would be able to inform me that this has happened.)

Inside RenderDoc, I click the button to install the Vulkan hooks and say to do it for the current user only. I select `target/debug/wgpu-hello` in the Launch Application window and tell it to queue capture of the first three frames. I touch nothing else. The application runs successfully (and with the renderdoc injected text in the corner), although on every single frame it prints to stderr:

```
2023-11-09T19:43:50Z ERROR wgpu_hal::gles::egl] EGL 'eglGetConfigAttrib' code 0x3005: eglGetConfigAttrib
```

It does not normally do that, and I am surprised to see an egl error since I would have expected the app to use Vulkan.

Having captured the three frames, I close the application and double-click the third frame. I get the "failed to open for replay" message. Here is the capture:

[COULDNT-OPEN-CAPTURE.rdc.zip](https://github.com/baldurk/renderdoc/files/13312644/COULDNT-OPEN-CAPTURE.rdc.zip)

### Unusual steps

In addition to the binary copy of qrenderdoc, I have a local git checkout of `74b0a8b1a73` where I have built a custom qrenderdoc with (in CMake) X11 support turned off, XCB turned off, OpenGL and EGL turned off (leaving only Vulkan), and the experimental/unsupported Wayland support turned on. This unsupported Wayland copy **is** able to capture the same test app and is able to successfully load the capture, although I cannot get any information from it as (as expected from the various warnings) the Wayland version has visual glitching and crashes in most panes. I mention this in case it contextualizes the error seen in the "official" qrenderdoc.

## Environment

* RenderDoc version: RenderDoc 1.29 
* Operating System: Ubuntu 23.10
* Graphics API: Believed Vulkan, but (as described above) may be EGL
* GPU: "AMD Ryzen™ 5 PRO 6650U with Radeon™ Graphics × 12" (Lenovo ThinkPad)
* Desktop environment: Default (Wayland/Mutter plus GNOME, I think)
* Rust version: 1.73.0

Additional configuration notes: I run with 150% display "fractional scaling". Once the `wgpu-hello` app has been launched by RenderDoc, I can use xeyes to verify that RenderDoc is running in xwayland and `wgpu-hello` is running as a Wayland app.

**Comment by mcclure** [comment]
Follow-up: After filing this I tried to see if I could get Ubuntu to run without Wayland. I found I could get in to X by logging out, selecting the "Ubuntu on Xorg" setting, and logging back in. Once I did this, I repeated the above steps and RenderDoc was able to open and display information from the frame capture, showing the captures as "Vulkan" captures. (I did not get the repeated EGL errors.) So in the short term my problem is resolved. However:

- It is worth noting that the configuration that did not work was a very "normal" configuration— newest release Ubuntu, wgpu which is a currently mainstream Rust graphics library, all with the default settings untouched.
- *If* the problem is the original configuration is unsupported: The fact it worked on the same machine with different settings IMO increases the importance of a clear error message which guides the user toward choosing the settings which qrenderdoc would support

**Comment by mcclure** [comment]
Follow-up follow-up: After the successful test with "Ubuntu on Xorg" I switched back to "Ubuntu" (Wayland/Mutter) and ran the test one more time. This time I noticed that in the list of captures, all three captures (the three that "fail to open") are listed as "OpenGL ES". I also notice that when the program is running, the injected text in the upper right said "Capturing OpenGL ES".

![image](https://github.com/baldurk/renderdoc/assets/277318/31f64789-dbf6-45b6-9558-918b6f0ff7cf)

It is unexpected to me that when asked to boot a program while running in xwayland in a Wayland environment Renderdoc would run the program as OpenGL ES, but when asked to run the same program on the same computer while running in regular Xorg Renderdoc would run it as Vulkan. It is also surprising to me that OpenGL ES would run on this computer at all as it is an x86_64 laptop which normally ships with Microsoft Windows. I would have thought it would be normal OpenGL.

**Comment by baldurk** [comment]
There are a few different things here but only so much I can actually address.

Regarding Wayland I'm not really going to touch on that side of things. Wayland as you've said is not supported and so using RenderDoc needs to go through the X compatibility layer. I'm not familiar with Wayland so I can't help with any configuration or settings needed to get that working, as far as I'm aware it should be seamless. I don't keep any linux systems with Wayland available so although I have latest ubuntu to repro it doesn't sound like I'd be able to since you're saying that it works fine when run on X?

The only thing I'd say is that on Vulkan RenderDoc can report its lack of Wayland support but not reporting the Wayland surface extension. The idea being that applications can then fall back and use an X surface instead. As far as I'm aware this is not possible on GL, and it's also not possible to reliably detect if an application is using Wayland at runtime to give a warning/error/block as unsupported. As far as I'm aware (with next to no Wayland knowledge) there isn't any way for me to do a more graceful job of supporting Wayland on the GL side. If there is I'm open to suggestions and as long as they're not too invasive - I don't mind making small quality of life changes to make it easier for applications to find the correct codepath.

You've mentioned a couple of times the different APIs that your program is using. To be clear, RenderDoc has nothing to do with what API your program uses and it's not possible for RenderDoc to "run the program as OpenGL ES". It's not something I can help debug the logic of, you'd need to see in your code & libraries what causes it to select one API or another as that is as much application logic as is the rendering that you do. I would certainly agree and recommend never using OpenGL ES on desktop, as in my view there is no reason and it is only a broken version of proper OpenGL as you say.

---

I think the only actionable thing here is the original error message. From the capture you shared I think this is a plain old bug, unrelated to any windowing systems or anything in use. I can't tell for certain without running the application (which I haven't done yet, given the above challenges to actually repro'ing and needing to re-figure out how to install a compatible rust binary) but I was able to reproduce the problem in a synthetic test - it looks like if an application makes a persistent read-only map and then unmaps it, RenderDoc incorrectly serialises that as a write and fails on replay. If it were not persistent, or persistent and... actually persistent and not unmapped, it would have been fine.

The generic error message could be improved at least to say that a buffer map failed, but it's an unexpected case and I don't know if it would have helped you much.

Since you have RenderDoc built locally can you try with this patch?

```patch
diff --git a/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp b/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp
index f409a8b09..5d6b32180 100644
--- a/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp
+++ b/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp
@@ -2728,7 +2728,12 @@ GLboolean WrappedOpenGL::glUnmapNamedBufferEXT(GLuint buffer)
         // case we have to ensure we handle this otherwise it won't be captureable.
         if(IsActiveCapturing(m_State))
         {
-          if(record->Map.persistent)
+          if((record->Map.access & GL_MAP_WRITE_BIT) == 0)
+          {
+            RDCASSERT(record->Map.persistent);
+            RDCDEBUG("Read-only persistent map-unmap detected, ignoring.");
+          }
+          else if(record->Map.persistent)
           {
             // serialise the write to the buffer
             USE_SCRATCH_SERIALISER();
```

**Comment by mcclure** [comment]
> You've mentioned a couple of times the different APIs that your program is using. To be clear, RenderDoc has nothing to do with what API your program uses and it's not possible for RenderDoc to "run the program as OpenGL ES". It's not something I can help debug the logic of, you'd need to see in your code & libraries what causes it to select one API or another as that is as much application logic as is the rendering that you do. I would certainly agree and recommend never using OpenGL ES on desktop, as in my view there is no reason and it is only a broken version of proper OpenGL as you say.

Well the reason I am stressing this is that I strongly suspect that the application *is* running in Vulkan, under all circumstances\* and RenderDoc is simply mis-reporting it as OpenGL ES. I would even speculate this could lead to a situation where RenderDoc gathers a capture from a Vulkan app, attempts to parse it as if it were an OpenGL ES capture, fails, and causes the error message I saw.

\* (Because running in Vulkan is what I would expect, it is what I remember it doing on Windows last time I checked, and when run on Linux under Xorg RenderDoc reports it as Vulkan.)

> Since you have RenderDoc built locally can you try with this patch?

Sure, to be clear what version of the RenderDoc source should I apply it to (eg, v1.x branch head, a particular tag)?

**Comment by baldurk** [comment]
What you're describing is definitely not possible. If captures are being made with GL(ES) then GL(ES) is in use. In theory I could imagine a bug that confuses GLES when GL is used but not GL for vulkan. In practice though I think the chances of such a bug are relatively low, I would expect rather that your program is indeed using the API that's being reported. Unless you are positive that it is using a different API than RenderDoc is reporting that would not be my expectation.

Pretty much any version is fine to apply the patch to as that code hasn't changed in quite a while, latest v1.x is reasonable target but also whichever code you were building before as long as it's not months old is also fine.

**Comment by mcclure** [comment]
Three things:

1. With that patch applied to trunk 1.x 74b0a8b1a73e, built with `-DENABLE_PYRENDERDOC=0` but otherwise all cmake defaults, I see these differences vs release renderdoc_1.29 running my test:

    * Seem to be unrelated to patch: I got the "Running directly on wayland is unsupported!" error on launch; renderdoc correctly supports my 150% display scaling; running xeyes, qrenderdoc appears to be running in wayland not xwayland. Either these changes are due to running on trunk or it's about xcb vs x11 (I did NOT build with -DENABLE_WAYLAND). Doesn't matter.
    * When I run the test, I get this error message:

    ![Screenshot from 2023-11-10 12-22-54](https://github.com/baldurk/renderdoc/assets/277318/68b58b83-1edb-4fcb-ba13-a3370f4f2ad2)

    This error message would have been more helpful than the one I got in 1.29. (However, the "Running directly on wayland is unsupported!" message I get with trunkwould have helped me most of all, as it would have lead me to the thing that works: Logging back in in xorg mode.) So the patch appears to be good.

    Here is the capture from the trunk version.

    [CAPTURE_DELETE_ME.rdc.zip](https://github.com/baldurk/renderdoc/files/13322468/CAPTURE_DELETE_ME.rdc.zip)

2. The answer to the "GLES" mystery is that apparently, if a wgpu program is launched by RenderDoc inside a Wayland session, it will come up with a GL [GLES] backend instead of a Vulkan one. I added `println!("Adapter info {:?}", adapter.get_info());` to my code and I found that I got a Vulkan¹ backend when running from the command line on Xorg or Wayland or when launched by RenderDoc on Xorg; but I got a GL backend when launched by RenderDoc on Vulkan.

    I asked the wgpu Matrix if this was surprising and they said it is expected because RenderDoc, by apparent necessity, disables all Wayland extensions when booting a program inside Wayland, and without extensions wgpu cannot request a Vulkan context and falls back to egl. (They also said their GL context is always GL ES because that's what egl vends even on desktop.) Armed with all this information, I discovered something:

3. **The "replaying the capture failed" bug is not related to Wayland.** I changed my sample program above so that instead of requesting `wgpu::instance::default()` i create my wgpu instance with `let instance = wgpu::Instance::new(wgpu::InstanceDescriptor { backends: wgpu::Backends::GL, dx12_shader_compiler: Default::default() });`. This forces wgpu to always use the GL fallback backend instead of the preferred Vulkan one. I then booted into "Ubuntu on Xorg" so that Wayland was not anywhere involved, and re-ran my test in both official Renderdoc 1.29 and my self-built trunk with your.

    Running with this "xorg plus forced GL" test: With official Renderdoc I get the "failed to open for replay" error I screenshotted at the top of this post. With self-built trunk it (the wgpu app) crashes on startup². I find the startup crash does not happen if Renderdoc simply launches the app, it only happens if RenderDoc additionally tries to capture one or more frames. Note, these tests were all with a wgpu 0.16 app, but if I re-run them with a 0.18 app I have I get the same results.

To conclude, I believe I am seeing two different "bugs" here. First, when launched by Renderdoc in a Wayland session, wgpu apps silently switch to GL [GLES] backend; this caused me to encounter the second bug, which is that if a wgpu app is running in the EGL/GLES backend for any reason, on either Xorg or Wayland, Renderdoc will either gather a capture which it cannot then interpret or do something that causes the launched app to crash.

I do not at this moment need support because I have a fix for my problem (run RenderDoc in xorg so I get the desired Vulkan backend). Moreover, the first of these two "bugs" can be excused on grounds RenderDoc does not support Wayland (and appears to now warn about this on boot). However it seems to me the second bug (RenderDoc can capture but not play back EGL captures in wgpu apps) could potentially impact supported cases that other users might hit.

---

¹ I doubt it matters but the adapter info I get in the Vulkan case is `Adapter info AdapterInfo { name: "AMD Radeon Graphics (RADV REMBRANDT)", vendor: 4098, device: 5761, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 23.2.1-1ubuntu3", backend: Vulkan }` and the adapter info I get in the GL case is `1Adapter info AdapterInfo { name: "AMD Radeon Graphics (rembrandt, LLVM 15.0.7, DRM 3.54, 6.5.0-10-generic)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }`.

² Ran three times and got the following messages:

```
Adapter info AdapterInfo { name: "AMD Radeon Graphics (rembrandt, LLVM 15.0.7, DRM 3.54, 6.5.0-10-generic)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
[2023-11-10T18:58:54Z ERROR wgpu_hal::gles::egl] EGL 'eglGetConfigAttrib' code 0x3005: eglGetConfigAttrib
double free or corruption (!prev)
Boot
Adapter info AdapterInfo { name: "AMD Radeon Graphics (rembrandt, LLVM 15.0.7, DRM 3.54, 6.5.0-10-generic)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
[2023-11-10T18:59:07Z ERROR wgpu_hal::gles::egl] EGL 'eglGetConfigAttrib' code 0x3005: eglGetConfigAttrib
double free or corruption (!prev)
malloc(): unaligned tcache chunk detected
Boot
Adapter info AdapterInfo { name: "AMD Radeon Graphics (rembrandt, LLVM 15.0.7, DRM 3.54, 6.5.0-10-generic)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
[2023-11-10T18:59:18Z ERROR wgpu_hal::gles::egl] EGL 'eglGetConfigAttrib' code 0x3005: eglGetConfigAttrib
double free or corruption (!prev)
```

On another test I got a `free(): corrupted unsorted chunks`. This was just printed in the terminal window I ran qrenderdoc from. The "Adapter info" and "Boot" lines are printed by my application. I do not know how to tell if the "double free or corruption" and "tcache chunk" lines are printed by qrenderdoc or the wgpu app, but probably it's the wgpu app.

**Comment by baldurk** [comment]
If you're getting a message about "Running directly on wayland is unsupported" then that's already a problem, and everything after that is suspect/liable to be broken. I'd certainly expect things to break from there trying to replay. That warning has been in there a long time, if Qt is detected to be running in wayland mode. Possibly you don't get that on the stable releases because they have Qt statically linked and it doesn't have wayland support at all, whereas your distro's Qt may have wayland support automagically?

The GLES fallback in your application makes sense. If it were me writing the code I would fallback from Vulkan Wayland -> Vulkan Xorg first, as I would prefer to have Vulkan at all (agnostic of window system) than prefer Wayland (agnostic of graphics API), but that's up to your application's logic. I'd note that it's not a bug per se - as you say the Wayland extensions on vulkan are enumerable so it's up to the application to decide what to do if they're not available. It is technically possible to access proper GL through EGL, but it makes sense that straightforward use of EGL will give you GLES - EGL is the Android vendor API and GLES is the Android GL API so they are linked in some sense.

It sounds like this patch is unconfirmed still since it should allow the GL version of your application to run under Xorg. The memory corruption errors are concerning but it's impossible to say where they're coming from without investigating more. Would you be able to share a branch or executable of your application that's set to forcibly use GL? I can make sure that it works when running under X either way since that should all be supported.

For the situation under Wayland I really don't know what I can do. I would hope it's possible for applications to use the X compatibility in Wayland seamlessly since that's usually the point of backwards compatibility. For the UI, I'm not sure if I can force-disable any wayland use at compile time or not, I'd need to look into Qt and this is low priority since it's on an unsupported system. For captured applications I already report that wayland is not supported under Vulkan but there's no way to do that under GL and no way to even detect it to throw a useful error message. Hopefully in future applications will target only Vulkan, or fallback to Vulkan on X rather than all the way back to GL, but I can't control that.

**Comment by mcclure** [comment]
Okay, thank you for the explanations. I understand Wayland makes things very difficult.

Based on what I know right now, I don't think I can think of a specific change recommendation on the "GLES fallback" issue for either RenderDoc or wgpu (given the only repro for the wgpu problems I know requires running in debug tooling—RenderDoc— and the existence of an easy workaround for that case—run renderdoc in xorg).

> Would you be able to share a branch or executable of your application that's set to forcibly use GL?

Sure, try this branch.

https://github.com/mcclure/webgpu-tutorial-rs/tree/wgpu-tutorial-0.18-fork-force-egl

Here is a release binary (the debug binary was a little too large to attach to a github issue).

[wgpu-hello-release.zip](https://github.com/baldurk/renderdoc/files/13323368/wgpu-hello-release.zip)

Also, here is another potentially interesting data point. It occurred to me the wgpu-hello demo is just a little bit complex (it does multipass rendering, it copies data from a gpu buffer back to the cpu, it is running with wgpu 0.18 plus a small bugfix PR instead of basic 0.18). I decided to also make you a version of wgpu's basic "hello-triangle" example with forced-EGL mode. Here is that demo (build with `cd examples/hello-triangle && cargo run`, will place output in `target/debug/hello-triangle` relative to project root):

https://github.com/mcclure/wgpu/tree/v0.18-force-egl-test

release build:

[hello-triangle.zip](https://github.com/baldurk/renderdoc/files/13323420/hello-triangle.zip)

When I ran this demo with RenderDoc 1.29 and captured the first frame (it is not animated) I did *not* see the "could not replay" problem. So the problem is not inherent to wgpu EGL, it requires certain wgpu features to be engaged (or wgpu has a buffer management bug which has to be hit).

If there is a demo more complex than hello-triangle but less complex than wgpu-hello that would help in debugging this, I could probably put that up easily.

**Comment by mcclure** [comment]
By the way, I described the discussion here in the wgpu Matrix and the following discussion ensued [abridged]:

> &lt;@cwfitzgerald&gt; [@mcclure]: there's a known issue on linux with malloc corruption on linux - this has only actually showed up in practice on cpu implementations, but it very much could be rearing its head here. We have an idea what could be calling this, but we're waiting for arcinization to land to look into it.
> 
> &lt;@mcclure&gt;: In your view, should Renderdoc Guy be warned that this is a potentially known issue before he spends time trying to debug why RenderDoc is unable to gather captures from a process which may in fact be heap corrupted?
>
> &lt;@cwfitzgerald&gt; If you're getting heap corruption, then yes anything could be happening here… this is almost certainly a bug in wgpu, at least in this point in the investigation

It is less obvious to me that heap corruption is happening in the renderdoc-1.29+xorg case than the renderdoc-trunk+xorg case, but FYI.

**Comment by baldurk** [comment]
Thanks for including the binaries, though unfortunately I couldn't run them as they needed a different glibc than I had - classic linux binary portability :(. I tried building and running the first demo you had but it ran in Vulkan for me on X? I blindly copy-pasted over the change from the other branch you linked and that seemed to get it to run in GLES, but not sure if that invalidated the testing.

Unfortunately though I can't repro any problems - the behaviour I see is such: Running on latest v1.x, I get the original buffer map bug addressed in a comment above. After applying my patch from the earlier comment the captures open successfully, I don't get any errors about replaying that you do. Were you running on a completely normal build aside from the patch for that fix? You didn't have any extra build options enabled or disabled?

I've now pushed the fix for the buffer mapping since I was able to confirm it myself definitely on your application, as well as a couple of QoL commits to help avoid Wayland. It would be good if you could test on the next nightly build to see if any problems remain, because it seems like that was the only bug possibly.

**Comment by mcclure** [comment]
> I tried building and running the first demo you had but it ran in Vulkan for me on X? 

Ugh, my sincere apologies— I messed up with git and pushed without committing. \*_\*

The [wgpu-tutorial-0.18-fork-force-egl](https://github.com/mcclure/webgpu-tutorial-rs/tree/wgpu-tutorial-0.18-fork-force-egl) branch should now now be updated correctly. But there's only 2 lines difference so if you recreated it from my wgpu-triangle you probably got the same code. 

> Were you running on a completely normal build aside from the patch for that fix? You didn't have any extra build options enabled or disabled?

`QT_SELECT="default" QTTOOLDIR="/usr/lib/qt5/bin" QTLIBDIR="/usr/lib/x86_64-linux-gnu" cmake .. -DENABLE_PYRENDERDOC=0`

So one disabled feature.

I will test with the next nightly. Thank you for looking into it.

**Comment by mcclure** [comment]
Hi,
I just tested with nightly `renderdoc_2023_11_14_caef1b9c`
It solves the problem **fully**, in both Xorg-with-forced-ES and Wayland mode.
I don't know why I had problems with my self-built version; I assume I did something wrong.
This bug can be closed.
Thanks!

**Comment by baldurk** [comment]
There are some build differences on the nightly because making portable linux binaries is quite challenging, but I think the only one I can think of that should make a difference is the statically linked Qt with no wayland support, but that should only change behaviour there.

Either way glad it's working now.
