### ISSUE TITLE
cmake build can fail without error message if bison is not installed

### ISSUE THREAD

**Issue by mcclure** [baldurk/renderdoc#3127]
This is admittedly quite clear "user error" because the compile instructions are very clear bison is required (and even include instructions for installing Bison). But just to document this…

## Description

If you build current renderdoc default branch (74b0a8) on a system which does not have bison, cmake will execute this step:

```
cd /home/mcc/work/g/other/renderdoc/build/qrenderdoc/custom_swig-prefix/src/custom_swig && /usr/bin/gmake > /dev/null 2>&1
```

If the system does not have bison/yacc installed, the custom_swig gmake step will fail. However because of the `2>&1`, this error will be totally swallowed. The entire build will fail with no message clearer than "Error 2":

<img src="https://files.mastodon.social/media_attachments/files/111/387/352/130/782/732/original/3019b1350884c404.png">

## Steps to reproduce

I cloned renderdoc in git, installed all packags recommended in CONTRIBUTING/COMPILING.md except Bison and built with
```
mkdir build && cd build
QT_SELECT="default" QTTOOLDIR="/usr/lib/qt5/bin" QTLIBDIR="/usr/lib/x86_64-linux-gnu" cmake .. -DENABLE_PYRENDERDOC=0
QT_SELECT="default" QTTOOLDIR="/usr/lib/qt5/bin" QTLIBDIR="/usr/lib/x86_64-linux-gnu" cmake --build .
```

(It was silly of me to skip the Bison install but on a previous build with different flags (`-DENABLE_PYRENDERDOC=0 -DENABLE_WAYLAND=1 -DENABLE_XLIB=0 -DENABLE_XCB=0 -DENABLE_GL=0 -DENABLE_GLES=0 -DENABLE_EGL=0`) it had not turned out to be needed.)

This lead to the error above. I ran cmake verbosely and saw the failing command was the custom_swig gmake, I ran that by hand and saw the problem was no bison. I installed yacc and ran cmake again and there were no problems.

## "Expected behavior"

I'd expect that if a build step fails its underlying error messages would be printed. (If there were in future some non-yacc error in this step, this could bite even someone who followed the instructions.) However I understand cmake may make that difficult… 

## Environment

<ul>
<li>RenderDoc version: 74b0a8b1a7</li>
<li>Operating System: Ubuntu 23.10</li>
<li>Graphics API: n/a</li>
<li>GPU: "AMD Ryzen™ 5 PRO 6650U with Radeon™ Graphics × 12" (Lenovo ThinkPad)</li>
</ul>

**Comment by baldurk** [comment]
Yes unfortunately I had to silence stderr and stdout there because otherwise they spam output in parallel from configure & make and cmake's build and the overall output is totally corrupted. I couldn't find a way to only display errors and not any normal output from that build step so it got completely muted as the best alternative.

The only option I can think of is independently checking manually for all of swig's dependencies in cmake, which seems bug-prone and hard to be free of false positives and/or negatives.

As you say the need for bison is documented, indeed I have a one-line copy pasteable package manager install command for the most common distros. I don't think there's sufficient justification for any changes here. Maybe cmake could print a custom error message if the swig step fails to direct people to the documentation but I'm not sure if that would help (or if it's possible in general).
