### ISSUE TITLE
[d3d] 'SV_InnerCoverage' was not handled properly

### ISSUE THREAD

**Issue by SevenIsSeven** [baldurk/renderdoc#3135]
'SV_InnerCoverage' was displayed as 'oUnsupported', which I can fix by some easy modifications in the source code, but I'm not able to get the replay of underestimate conservative rasteriazation work as expected.

**Comment by SevenIsSeven** [comment]
![sv-innerCoverage](https://github.com/baldurk/renderdoc/assets/150881358/93ecd2e9-135c-48f4-ba3c-bf6f06284872)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
