### ISSUE TITLE
Error importing renderdoc.pyd DLL file

### ISSUE THREAD

**Issue by bentaylorhk-arm** [baldurk/renderdoc#3141]
## Description

When trying to run `util/test/run_test.py`, the script silently fails when hits `import renderdoc as rd` at line 5 in `capture.py`. The script exits with error code -1073741819, and in git bash is states `Segmentation fault`. When running python verbosely with `-vvv`, the following is outputted...
```
...
# trying C:\<PATH>\util\test\renderdoc.cp311-win_amd64.pyd
# trying C:\<PATH>\util\test\renderdoc.pyd
# trying C:\<PATH>\util\test\renderdoc.py
# trying C:\<PATH>\util\test\renderdoc.pyw
# trying C:\<PATH>\util\test\renderdoc.pyc
# trying C:\<PATH>\x64\Development\pymodules\renderdoc.cp311-win_amd64.pyd
# trying C:\<PATH>\x64\Development\pymodules\renderdoc.pyd
```
...at which point it fails. This shows that it does find the correct .pyd file, but there's an error loading the .dll file itself.

My build is compiled with VS 17.7.3, but even when compiled with `msbuild` on the command line with different `vcvars_ver`s set the same failure occurs.

## Steps to reproduce

Compile RenderDoc on windows and run the functional tests with `python run_tests --pyrenderdoc <PATH_TO_PYMODULES> --renderdoc <PATH_TO_LIBS>`. Add `-vvv` after 'python' to show the verbose output.

Alternatively, a simple script like the one below (ran from within the `x64\Development\pymodules` directory) achieves the same result.
```
import os
import sys

pyrenderdoc_path = os.path.abspath(os.path.dirname(__file__))
renderdoc_path = os.path.abspath(os.path.dirname(pyrenderdoc_path))

sys.path.insert(0, pyrenderdoc_path)
os.add_dll_directory(renderdoc_path)

import renderdoc as rd
```

## Environment

* RenderDoc version: v1.x (0d9ea809dd436b631874f65d100eac95764ef349)
* Operating System: Windows
* VS Version: 17.7.3
* Python Version: 3.11.6 (Alternative versions tried to no result)

**Comment by baldurk** [comment]
If you're running the tests with python 3.11 are you also building the python modules with python 3.11?

You say "Alternative versions tried" but you don't say which one, and there is only one version that can be used. As [documented](https://renderdoc.org/docs/python_api/examples/renderdoc_intro.html#loading-the-module) you must run with the exact major & minor version of python as you built with, otherwise it will crash.

**Comment by bentaylorhk-arm** [comment]
No I didn't realise it was built with an different python version. Running the tests with Python 3.6 fixes it, thanks @baldurk
(For the record the alternative versions were 3.10 and 3.4)

**Comment by baldurk** [comment]
3.10 or 3.11 would work too but you would need to configure the build to use them, as by default it will use the python version in the git repository which is 3.6. I'm not sure if 3.4 would work - I think so, but I haven't tried that.

Unfortunately the API access we need for python integration is not stable across minor versions, there's a limited API that's stable but it provides insufficient access. Doubly unfortunately there's no good way to detect this case and print a graceful error, as it crashes 100% in python code before our module code runs. python311.dll loads renderdoc.pyd which is linked to python36.dll which then either crashes or depending on search paths fails to load the pyd because of that missing dependency.

**Comment by bentaylorhk-arm** [comment]
That's great actually, apologies for missing that part of the documentation.
