### ISSUE TITLE
Dumping binary context of 2D array texture only works for selected layer.

### ISSUE THREAD

**Issue by reduz** [baldurk/renderdoc#3149]
## Description

Inspecting an array texture as binary and saving it to a file only saves _one_ layer of the whole texture.

## Steps to reproduce

When inspecting an array texture as binary:

![image](https://github.com/baldurk/renderdoc/assets/6265307/2a099bcf-7b09-4992-bcfd-6f5839ada415)

This has 24 layers, hence the total size should be 68*612*8*24 = 7990272

Exploring as binary shows the whole thing:
![image](https://github.com/baldurk/renderdoc/assets/6265307/26a93c8c-ef26-484e-85ff-739fac682b48)
![image](https://github.com/baldurk/renderdoc/assets/6265307/65e7e7d8-c056-4dfc-9c75-60d2b64e2ae0)

But RMB -> Export to Bytes

Only saves one layer:
`332928    save_data.bin`

7990272 / 24 = 332928

Either the whole texture should be saved, or an option to save either the whole texture or the current layers should be offered.

I found this error while trying to workaround #3148, by the way.

## Environment

* RenderDoc version: 1.28
* Operating System: Ubuntu
* Graphics API: Vulkan
* GPU: GTX 1650

**Comment by baldurk** [comment]
When viewing a texture's bytes in the buffer viewer it is intentional that only one subresource is displayed at a time, since the physical layout of subresources is not necessarily defined or consistent. That commit clarifies this (and disables the byte offset/length fields as those are not supported for textures).

If you want to save the whole texture to a file without conversion, you can save to dds which supports all texture formats natively and has a defined layout. You could also use a python extension to save to a custom format if you want the raw bits with no headers and custom alignment/ordering.
