### ISSUE TITLE
Event Browser highlights can be unreadable on white text color schemes

### ISSUE THREAD

**Issue by imccown** [baldurk/renderdoc#315]
![renderdoc_white_bug](https://cloud.githubusercontent.com/assets/8538777/17417963/ed422334-5a4a-11e6-9531-c4e3cca35128.png)

In the event browser the categories are labeled with white text on a white background. The text color doesn't appear to be the system color since my text color isn't quite white. The screenshot is on win10 with the attached high contrast color scheme.
[destroyertheme.zip](https://github.com/baldurk/renderdoc/files/402692/destroyertheme.zip)

Thanks for all your work on Renderdoc!

**Comment by baldurk** [comment]
I think this is caused by the marker regions - judging from the vertical white bars on EIDs 1967, 1978, 1989 all of the marker regions are full white.

I have some code in place to check for very dark marker region colours and switch the text colour from the system colour to white, but that's assuming the default light-coloured windows theme - in the inverse case it needs to be backwards. Should be easy enough to fix, I'll look at this tomorrow.

**Comment by baldurk** [comment]
Fixed this specific bug, but while I was looking at the high contrast themes I noticed a load of other controls that weren't rendering very nicely on white-on-black themes (or white-on-black high contrast). Hopefully things should be better now without significantly affecting the normal themes.

I only tested on windows 7's high contrast (black) and (white) themes but hopefully that covers the different extremes. Let me know how it looks in the next nightly build please!

**Comment by imccown** [comment]
Fixed in build 2016_08_06_51107824. Thank you very much!
