### ISSUE TITLE
Display Triangle on Texture UVs

### ISSUE THREAD

**Issue by Raildex** [baldurk/renderdoc#3156]
## Description
In the Mesh Viewer, we can inspect a mesh pre and post Vertex Shader.
It also neatly displays all attributes in a table.
I would like to have the ability to select vertices and have it's UVs displayed over a texture.
![image](https://github.com/baldurk/renderdoc/assets/14938934/4716c7f6-21c8-4433-936c-b5a067a9aeb8)
![image](https://github.com/baldurk/renderdoc/assets/14938934/ab362688-7e82-42f1-accb-796ec6158ac1)

This would help debugging texture coordinates a lot.

## Environment

* RenderDoc version: 1.29
* Operating System: Windows 11 x64
* Graphics API: D3D11

**Comment by baldurk** [comment]
This is something that I do not intend to support due to the difficulties in mapping a vertex attribute or output to the actual sampled UVs (as they're not guaranteed to be used unchanged) as well as the extra burden and complexity required in building a UI to map between a given element in the mesh viewer and a given texture since it's not guaranteed that there's only one texture or indeed one set of texture co-ordinates.

For this kind of case you can select the attribute and display it as position, to view the texture co-ordinates in UV space. This is still local to the mesh-viewer and doesn't display it overlayed on the texture but is more useful in visualising texture co-ordinates:

![texture co-ordinates rendered in UV space](https://github.com/baldurk/renderdoc/assets/661798/8597e5cd-52bd-4d80-bcbe-45112a2a9bb2)
