### ISSUE TITLE
Stop the log icon flashing

### ISSUE THREAD

**Issue by crazydef** [baldurk/renderdoc#3184]
## Description

Today when opening a capture if there are any messages in the log, the log icon in the bottom left corner of the RenderDoc window flashes constantly in the most irritating manner possible.  (Which is obviously the point.)

Please stop it flashing.  It's so annoying and forces me to open the Errors and Warnings pane just to make it stop flashing even though I'm just trying to get on with other things.

(It's doubly annoying because I have some low severity OpenGL "issues" that are never going to be fixed.)

## Environment

* RenderDoc version: 1.24
* Operating System: Linux + Windows
* Graphics API: OpenGL + DirectX

Please stop the icon from flashing.
An improvement would be to have a different icon that indicates the level of the most severe message in the log.

**Comment by baldurk** [comment]
As you say, the flashing is intentional to get the user's attention as otherwise it is likely to be missed.

These messages usually only come from the API's own validation when enabling API validation when capturing - I generally do not recommend enabling this as standard, especially since invalid API use should be fixed first. If you don't want to have an alert of validation issues then I'd recommend that you don't enable API validation when capturing, or fix the problems identified.
