### ISSUE TITLE
RenderDoc reports conflicting texture slots, which might be a false positive report.

### ISSUE THREAD

**Issue by tigert1998** [baldurk/renderdoc#3191]
## Description

Currently, I am implementing my little engine, which is open-sourced at https://github.com/tigert1998/tiger-game-engine.
Everything works fine. The test scenes are rendered correctly. However, I noticed that RenderDoc thinks differently.
It reported that there is a conflicting binding in slot 0 at the fragment shader stage for all drawcalls.
I am not sure whether it's a bug in my code (but not causing OpenGL to render incorrectly) or that RenderDoc reports false positives.
Here is a piece of pseudocode about how I set the texture slots:

```c++
glActiveTexture(GL_TEXTURE0 + unit);
glBindTexture(GL_TEXTURE_2D, 0);
glBindTexture(GL_TEXTURE_2D_ARRAY, 0);
glBindTexture(GL_TEXTURE_3D, 0);
glBindTexture(GL_TEXTURE_CUBE_MAP, 0);
glBindTexture(texture.target(), texture.id());
SetUniform<int32_t>(identifier, unit);
// the following is SetUniform<int32_t>
// auto location = glGetUniformLocation(id_, identifier.c_str());
// if (location < 0) throw ShaderSettingError(identifier, GetUniformVariables());
// glUniform1i(location, value);
```

## Steps to reproduce

The rdc file is linked here: https://drive.google.com/file/d/1ap0yyxwlFEduQnYY_HwdQ111gbM278VM/view?usp=drive_link.
You can also download my engine code. Compile it (px-demo) and test it.
The model (Sponza) I used for testing is available at: https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/Sponza.

## Environment

* RenderDoc version: 1.30
* Operating System: Windows 11
* Graphics API: OpenGL 4.6

**Comment by baldurk** [comment]
I can't look at the repro case right now as I'm not at my computer, I will look when I can but it might be a week or so. 

In the meantime your description is a little vague but it's worth asking - _are_ you binding different texture types to the same binding slot? If so that is invalid regardless of whether it works by coincidence or not. Undefined behaviour can sometimes work on one driver by coincidence. Especially on OpenGL with how badly designed the API is and how lenient some drivers are.

**Comment by tigert1998** [comment]
RenderDoc shows that the conflicting bindings are "shadowMap", "ambientOcclusionTexture", "ambientTexture" and "specularTexture". In fact, all the textures are all written in the shader's code. But "ambientOcclusionTexture", "ambientTexture" and "specularTexture" are not set (because they are not used). The only texture being set is "shadowMap" (bind to texture slot 0).

**Comment by tigert1998** [comment]
It seems that RenderDoc assumes that the bindings for "ambientOcclusionTexture", "ambientTexture" and "specularTexture" are all zero. So these textures conflict with "shadowMap"'s binding, which is indeed zero.

**Comment by Zorro666** [comment]
Hi I requested access to the capture file to download it (jake.turner.*@gmail.com)

**Comment by tigert1998** [comment]
> Hi I requested access to the capture file to download it (jake.turner.*@gmail.com)

Access granted.

**Comment by Zorro666** [comment]
The RenderDoc error is correct. Those textures are all bound to binding 0. It looks like from the engine code that "ambientOcclusionTexture", "ambientTexture" and "specularTexture" do not have any specific binding set which would be one way to avoid the problem. The textures need to have unique bindings (even if the textures aren't used because of runtime if's in the shader).
