### ISSUE TITLE
Layout of "Update Available" Window breaks when resizing

### ISSUE THREAD

**Issue by jkoenen** [baldurk/renderdoc#321]
The "Update Available" Window is resizable (I'm not sure if this is intentional). When the window is resized the layout breaks (Buttons stay where they are and the text-field doesn't resize.

**Comment by baldurk** [comment]
You are quite right, the update dialog wasn't intended to be resizeable, which is why the layout didn't update :).

Since this is a trivial fix and kind of difficult for anyone but me to test I'm just going to close the issue now rather than ask for verification, but let me know if you think something is amiss!
