### ISSUE TITLE
Feature Request: set default state for gamma space toggle

### ISSUE THREAD

**Issue by jeremyabel** [baldurk/renderdoc#329]
It'd be super convenient to be able to set whether the gamma space toggle defaults to on or off. Every time I go to look at a depth buffer it looks empty and then I realize that it defaults to displaying in gamma space, so I have to turn it off.

**Comment by baldurk** [comment]
Do you mean setting defaults based on a per-type basis? Or to force-off that feature entirely across the board.

FYI I find for depth buffers the most useful thing is to hit the 'auto-fit' button ![image](https://cloud.githubusercontent.com/assets/661798/17749651/f60fc952-64be-11e6-8d11-c21a358da45a.png) to set the black/white points (since usually it's something like 0.9 - 1.0 or 0.0-0.1 unless something is very close to the camera). That provides an even more useful visualisation than disabling the gamma display toggle.

Potentially it would be a sensible default to disable the gamma by default for depth textures, since really the reason for the gamma space toggle is for when you're displaying things like normal maps which are conventionally displayed as gamma even though they're linear data. I might experiment with that and add a heuristic to disable it in that case.

**Comment by baldurk** [comment]
Just to clarify - I'd like some idea of what exactly the issue you're running into so I can understand the best solution. I don't want to rush implement a fix/feature without knowing the actual workflow problem you have - e.g. if it's only depth buffers, if you just want the toggle off globally, etc.

**Comment by baldurk** [comment]
FWIW I ended up not making the gamma space view default to off for depth buffers, since it's still more common in my experience to have depth buffers with 1 at the far plane, so in this case the gamma display actually helps (a little).

For lack of any other input I'm going to close this but if you clarify what you're after exactly I can see what can be done.
