### ISSUE TITLE
[vulkan] AGBR texture channels are not correctly displayed in the image viewer

### ISSUE THREAD

**Issue by PtrMan** [baldurk/renderdoc#331]
The format for the experiment was VK_FORMAT_A2B10G10R10_UINT_PACK32

screenshot:
https://picload.org/image/rriddpoi/channelbug.png

**Comment by PtrMan** [comment]
here is the rdc file  http://www.file-upload.net/download-11861191/swizzledChannels.rdc.html

**Comment by baldurk** [comment]
I don't believe there is a bug here in RenderDoc.

The capture is (loosely speaking) a `vkCmdDrawIndexed` to an `A2B10G10R10_UINT_PACK32` image followed by a `vkCmdCopyImage` from that to a `B8G8R8A8_UNORM` image.

The shader bound at the draw just returns constant colour `uint4(0, 255, 512, 1024);` . The alpha gets clamped to `3`, the maximum representable value in 2 bits, so the output you see is light/cyan blue - which is exactly what the output should be from these values. Note that RenderDoc is showing the uint values in range 0-1 by default so the green and blue are saturating to 1 - if you click autofit, the output is dark blue:

![image](https://cloud.githubusercontent.com/assets/661798/17788244/f680fff4-658c-11e6-8b78-12bb069f705e.png)

When we pack in the uint values, as per the spec for `A2B10G10R10_UINT_PACK32`:

> `VK_FORMAT_A2B10G10R10_UINT_PACK32`
> A four-component, 32-bit packed unsigned integer format that has a 2-bit A component in bits 30..31, a 10-bit B component in bits 20..29, a 10-bit G component in bits 10..19, and a 10-bit R component in bits 0..9.

We get a hex value of `0xE003FC00` which comes from `(B:0 << 0) + (G:255 << 10) + (R:512 << 20) + (A:3 << 30)`.

The `vkCmdCopyImage` then reinterprets these bits as `B8G8R8A8_UNORM` without conversion, because the formats are compatible in the same number of bits per pixel. Unpacking according to the spec:

> `VK_FORMAT_B8G8R8A8_UNORM`
> A four-component, 32-bit unsigned normalized format that has an 8-bit B component in byte 0, an 8-bit G component in byte 1, an 8-bit R component in byte 2, and an 8-bit A component in byte 3.

So we have alpha `0xE0`, red `0x03`, green `0xFC` and blue `0x00`. When we normalise per `UNORM` by dividing through by `0xFF` we get: Alpha = `0.8784313725`, Red = `0.01176470588`, Green = `0.9882352941` and Blue = `0.0`. This is exactly what RenderDoc displays for the final output, and is also the bright green we see in your screenshot as well as RenderDoc's output:

![image](https://cloud.githubusercontent.com/assets/661798/17788377/a3c2a258-658d-11e6-981d-de81ed2cb77d.png)

If you think there's something wrong either with my interpretation or there's another bug, let me know. Otherwise if this makes sense I'll close the issue.

**Comment by PtrMan** [comment]
ah indeed, thx for the detailed explaination, you can close it
