### ISSUE TITLE
Expander arrow icon not visible on top of black header rows, such as those used by Unreal Engine

### ISSUE THREAD

**Issue by geordiemhall** [baldurk/renderdoc#3319]
## Description

When making a capture from Unreal Engine, the arrow icon shown on group/header rows seems to stay black despite the background also being black. This means you can't see the arrow, and is a little bit confusing whether a group is expanded or not.

Apparently programs can choose the header color, so I'm guessing it's probably Render Doc's responsibility to choose an icon color that has enough contrast. The text already seems to turn white correctly, so maybe the icon could use whatever the text color gets resolved to?

## Steps to reproduce

I can't attach an Unreal capture since they're all like 1GB, but hopefully you're able to easily repro by forcing black to be output by some test program?
![image](https://github.com/baldurk/renderdoc/assets/3511383/38130900-2e35-4caa-b65d-71849de70af9)

## Environment

* RenderDoc version: 1.31
* Operating System: Windows 11
* Graphics API: DX12

**Comment by baldurk** [comment]
Yes this is something that your program/unreal engine is explicitly requesting, as the default isn't black but transparent (which renders as normal in RenderDoc, e.g. the `FFXSystem::PostRenderOp...` region.

I thought this would be an easy fix but it needed an extremely gross hack since Qt can be extremely hard to customise sometimes 😞.

**Comment by geordiemhall** [comment]
Woah thanks for such a quick fix! Sorry about adding to the hack debt 😛
