### ISSUE TITLE
Vulkan: Sparse Images

### ISSUE THREAD

**Issue by pascal-aman** [baldurk/renderdoc#333]
Just tried out RenderDoc 0.3, and my application crashes as soon as i try to create a sparse image. Specifically:

Type: VK_IMAGE_TYPE_2D
Format: VK_FORMAT_BC7_SRGB_BLOCK
Usage: VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT
Width: 768
Height: 512
Depth: 1
Levels: 10
Flags: VK_IMAGE_CREATE_SPARSE_BINDING_BIT | VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT
Samples: VK_SAMPLE_COUNT_1_BIT
Tiling: VK_IMAGE_TILING_OPTIMAL
Sharing: VK_SHARING_MODE_EXCLUSIVE
Layout: VK_IMAGE_LAYOUT_UNDEFINED

If Flags are 0 the same call works (but obviously the application fails later when trying to sparse bind). Sparse buffers on the other hand seem to work, at least as far as i can tell (creating, binding and uploading didn't crash).

I know that sparse images are low priority for quite a few people because AMD has yet to implement it in their vulkan drivers, but is there any chance this might get a fix?

**Comment by baldurk** [comment]
Yes at the moment sparse images are only supported if they are 2D with `levels` and `depth` 1. This was primarily a limitation of time though (since I need to track all the sparse mappings that go on) and there's nothing technically stopping other sparse images from working.

You're right though that sparse image support isn't super high on the priority list, although this is more because sparse images just are generally very rarely used in _any_ API where they're supported, rather than driver problems.

If you can share your application (with source is ideal, but binaries are fine) this would help a lot in getting it implemented, as for the previous support I had to create my own toy application and I didn't want to go too out on a limb creating artificial samples. That was before vulkan released though so API samples in general were scarce.

**Comment by pascal-aman** [comment]
Sadly i can't share either the source nor the binary, which of course doesn't help getting this fixed :(

But i can give you a rough overview: The full use case is to basically create a bunch of large sparse texture arrays that could contain all the textures, and then stream the actual data in and out at runtime while reusing the actual memory. So only a few layers are actually bound, and the bound levels vary for each one.

Yeah i haven't seen a lot of people use it, even though it's a pretty powerful feature that already has a couple of years of hardware support.

**Comment by baldurk** [comment]
Sure I understand. I'll look at writing a small demo myself to test against, but my concern is I'm not going to use it in a realistic way so I might miss some big holes in support.

At least though it will be better than nothing and you can report further bugs if it doesn't work for you :).

**Comment by SaschaWillems** [comment]
Support for sparsely bound and resident images would be nice addition. Started on an example for this recently (it's in my repo, but it's still a wip) and having RenderDoc support that function would be nice :wink: 

Note sure how practical my example is (or better: will be), but my idea for it is to have a layered mip-mapped texture (mip-tail ahead!) with many sparse bindings (depending on image granularity) that will be backed up with actually memory over time (to simulate some kind of streaming).

If you're interested in testing out the basics for RenderDoc, you can find it [over here](https://github.com/SaschaWillems/Vulkan/tree/master/texturesparseresidency). Compiles and runs, but doesn't show anything of particular interest yet.

**Comment by tblut** [comment]
Is there an update on when this might get implemented?

**Comment by baldurk** [comment]
It's currently still low priority, since as above it's a very rarely used feature in any API. If you're able to share an application that uses it in a significant way for me to test against that would help, but I still can't promise any particular timeline.

**Comment by redfeatherplusplus** [comment]
I'm writing an application that uses sparse textures and running into crashes now on renderdoc. Guessing this still isn't supported. Any idea what might be worth looking at if I wanted to take a shot at fixing this? Also get a crash on Sascha's sample sparse texture program.

**Comment by baldurk** [comment]
Yes this issue is still open precisely because it isn't supported, if support were added I would close this issue.

Honestly I would advise against trying to implement this yourself. You're free to look into it of course but it's a task of high complexity anyway to be able to track and update all the page tables in a spec-accurate way, and if you're not familiar with the renderdoc code base that will make it a lot harder.

**Comment by Wunkolo** [comment]
Currently working with multi-mip-level sparsely-resident images here as well. Hoping my comment gauges that there is interest in support of this feature as I currently have to disable all of my texture streaming features during debug mode captures if I intend to use renderdoc at the moment.

**Comment by doitsujin** [comment]
Gonna give this a nudge as well. With vkd3d-proton we've been running into content that requires this feature.

As a small test case, vkd3d-proton's test app can be built with RenderDoc support as detailed [here](https://github.com/HansKristian-Work/vkd3d-proton#advanced-shader-debugging), and run as follows:
```
meson -Denable_tests=true -Denable_renderdoc=true build
cd build
ninja
export ENABLE_VULKAN_RENDERDOC_CAPTURE=1
export VKD3D_AUTO_CAPTURE_COUNTS=0,1,2,3,4,5,6,7 # or something like this, dunno which are relevant
export VKD3D_TEST_FILTER=test_update_tile_mappings # or test_copy_tiles, test_texture_feedback_instructions_sm51
./tests/d3d12
```

**Comment by Wunkolo** [comment]
Thank you, currently limited to Nsight for sparse-texture enabled captures

**Comment by baldurk** [comment]
I've committed support for capturing and replaying sparse resources. It's only lightly tested since I couldn't really get a hold of many non-trivial sparse resource samples (on any API), possibly because I think IHVs recommend against using them so it's a rarely used feature.

One thing to note: the memory overhead for capturing such resources is proportional to their total virtual size not how much physical memory is currently mapped. This isn't a problem if you're using sparse resources to defrag/remap and they're mostly always bound anyway, but it may be if you are reserving a lot more memory than is available on the GPU or system.
