### ISSUE TITLE
renderdoc 1.13 use TextureSave R8G8B8 png not work!

### ISSUE THREAD

**Issue by wsqat** [baldurk/renderdoc#3331]
I use renderdoc 1.13 version. It is found that the picture saved in RGB format is black.
`       texsave.alpha = rd.AlphaMapping.BlendToCheckerboard

	texsave.mip = 0

	texsave.slice.sliceIndex = 0

	texsave.resourceId = sd.textures[0].resourceId

	texsave.destType = rd.FileType.PNG

	texsave.comp.blackPoint = 0.0

	texsave.comp.whitePoint = 1.0

	filename = "./capture/" + os.path.basename(sys.argv[1]).split('.')[0] + ""

	controller.SaveTexture(texsave, filename + "_0.png")
`

![0-1_0](https://github.com/baldurk/renderdoc/assets/5681594/385075fb-7b1e-419e-825e-3446b058643c)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
