### ISSUE TITLE
In renderdoc 1.13, I use TextureSave to save R8G8B8, but it's not work! 

### ISSUE THREAD

**Issue by wsqat** [baldurk/renderdoc#3332]
## Description

In renderdoc 1.13, I use TextureSave to save R8G8B8, but it's not work! The saved picture is black.

## Steps to reproduce

In renderdoc 1.13

` texsave.alpha = rd.AlphaMapping.BlendToCheckerboard

texsave.mip = 0

texsave.slice.sliceIndex = 0

texsave.resourceId = sd.textures[0].resourceId

texsave.destType = rd.FileType.PNG

texsave.comp.blackPoint = 0.0

texsave.comp.whitePoint = 1.0

filename = "./capture/" + os.path.basename(sys.argv[1]).split('.')[0] + ""

controller.SaveTexture(texsave, filename + "_0.png")`
'
## Environment

* RenderDoc version: 1.13
* Operating System:  Windows 10 企业版
* Graphics API: no

**Comment by baldurk** [comment]
For reasons of practicality I do not provide assistance with writing python scripts, if you are having problems with your scripts you will need to debug them yourself. Image saving is known to work as it is part of the automated testing so unless you can reproduce this issue using the UI only then this is not considered a RenderDoc bug.

You are also using an extremely old version of RenderDoc from many years ago. There is no reason whatsoever to do this as RenderDoc is backwards compatible and does not remove functionality. You should update to the latest version as there have been numerous improvements and bugfixes since v1.13.
