### ISSUE TITLE
the overlay does not appear, and no additional information appears after launch mingw glfw application

### ISSUE THREAD

**Issue by zenbooster** [baldurk/renderdoc#3335]
## Description

I have a project that uses mingw, glfw, opengl 3.3:
https://github.com/zenbooster/alphawater/tree/mpshader
that I would like to debug. I downloaded and installed the latest version of renderdoc, launched my application through it, and saw that my application worked. Renderdoc reported:
`Connection Status: Estabilished`
`API: OpenGL (Active)`
then, after ~11 seconds:
`API: OpenGL (Not Presenting)`

At the same time, the overlay does not appear, and no additional information appears either.

## Steps to reproduce
1. Open the application in renderdoc.

## Environment

* RenderDoc version: 1.32
* Operating System: Windows 10 Pro 22H2 x64
* Graphics API: OpenGL 3.3

Sample:
[test.zip](https://github.com/baldurk/renderdoc/files/15499431/test.zip)

**Comment by baldurk** [comment]
This is caused by your application unbinding the GL context before presenting. Due to limitations in how the GL API is designed RenderDoc needs a context current when presenting to properly associate a window with a particular context.

As far as I'm aware there's no reason to unbind a context before presenting, so leaving your context bound should fix this issue.

**Comment by zenbooster** [comment]
Yes thank you! This really helped.
