### ISSUE TITLE
Replaying the capture failed at the API Level.

### ISSUE THREAD

**Issue by enchanEnchan** [baldurk/renderdoc#3339]
### Title:
[Issue with Frame Replay on Nut Pro 2/SDM660/Android 7.1.1]

### Body:

Hello Developer,

I am encountering an issue with your application when attempting to replay a captured frame. Here are the details of my device and the problem I am facing:

RenderDoc Version:1.33
Device Model: Nut Pro 2
Processor: Qualcomm Technologies, Inc SDM660
Android Version: 7.1.1
Issue Description:
I am able to capture frames successfully, but when I try to replay them, the application displays an error message: "Error opening capture."
The error details are: "Failed to open 'test.rde' for replay" and "Replaying the capture failed at the API level."
I have tried the following steps to resolve the issue:

Ensuring the app has permission to access storage.
Checking if the file path is correct and the file is not corrupted.
Restarting the device and attempting to replay again.
However, the problem persists. I have attached a screenshot of the error for your reference.

Additional Information:

I am using the latest version of the app.

I can provide more log information or perform further tests if needed.
I hope you can assist me in resolving this issue. Thank you!

![Snipaste_2024-06-03_13-48-26](https://github.com/baldurk/renderdoc/assets/38781402/e4e7e21e-c00a-41b4-b287-ff2e798b08fe)
![20240603-134350](https://github.com/baldurk/renderdoc/assets/38781402/8f1087b7-45b1-4a8f-ba6d-1a1be97f0678)

**Comment by enchanEnchan** [comment]
[test.rdc.txt](https://github.com/user-attachments/files/15529350/test.rdc.txt)
Use it by removing the txt suffix。thanks

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
