### ISSUE TITLE
Filter Resource Inspector to show only resources used in current frame

### ISSUE THREAD

**Issue by ccosse** [baldurk/renderdoc#3348]
## Description

The application I'm inspecting has roughly 1000 resources, each of which is duplicated per each of 3 frames-in-flight.  If the currently captured frame is using swapchain image #1, for example, then 2/3 of the resources in the resource list do not apply.

I would like to be able to filter the resource list to show only those resources used by the currently captured frame, and thus pare-down the resource list so that everything showing is relevant to the currently captured frame.

## Environment

* RenderDoc version: 1.33
* Operating System: Windows 10/ RHEL9/ Linux Mint
* Graphics API: Vulkan 1.3.261.0

**Comment by baldurk** [comment]
RenderDoc captures by default only include resources referenced in the captured region, though this is a conservative set and it is not feasible to precisely determine the exact set. It only includes every resource that exists when requested.

Are you sure that there are 1000s of resources being included which are not referenced in any way, including e.g. being bound in descriptor sets or otherwise indirectly used, or that you're setting the option that forces it to include every resource?

If you are sure, can you share a sample application that exhibits this behaviour?

**Comment by ccosse** [comment]
Hi, thank you for the reply; the resources I am referring to probably are referenced somewhere after all.  Thanks again!
