### ISSUE TITLE
Feature Request: default save folder

### ISSUE THREAD

**Issue by bejitt** [baldurk/renderdoc#335]
When saving a capturefor the first time after starting RenderDoc, the Save As dialog defaults to the Capture Executable directory. Given that I prefer to save my captures in a less volatile location, I have to navigate to a completely different folder every time I do a new capture.

Could we get an option for specifying a default folder for saving captures to?

**Comment by baldurk** [comment]
Good point, I hadn't thought of that! I think by default it was just using whichever directory windows picks for the save dialog, which is probably whichever directory was last browsed to. For lack of another better default I've left that alone, but I've also added an option to the settings menu to choose a default directory for your captures.

**Comment by bejitt** [comment]
I just got 0.31 and the default works great for File->Save Log, but it doesn't work on the Save option when you right-click a capture from the "captures collected" list (what's a better name for that?). Once I open a capture and then save it, the right-click Save option does start using the default.

In addition, this seems to force the save dialog to always go to the folder set in preferences. I'm used to having the option as a 'default' but all saves after that would default to the last folder you saved to. This behavior is exactly how it worked before this version.

As I was writing this, I found that I can't even un-set the new option to test w/ it disabled :/

For reference, the reason I asked for this is because in my workflow. I have a root folder that I save my captures under, but each task/bug I work on goes into a different folder under that folder.

**Comment by baldurk** [comment]
Thanks for the feedback. The inconsistent behaviour between the save options was just me forgetting that there's two different save dialogs (some of the log handling is shared between windows but not that one apparently). I can fix that easily enough.

Also you should have been able to set it back to blank to go back to the old behaviour, but it seems like that doesn't work properly, I'll fix that too. In the meantime you can manually edit `%APPDATA%\renderdoc\UI.config` and erase the contents of `<DefaultCaptureSaveDirectory>`.

As to the behaviour you want though, I'm not sure that's entirely possible to do :(. As far as I'm aware the windows built-in file dialog has two modes - one where you specify the directory, and one where you leave it blank and then it goes to the windows default behaviour, which it seems is the one where it picks up whichever folder was last browsed to by a file dialog.

I'm worried that even if it was feasible, there will then be someone who wants the opposite behaviour - ie. always picking the same folder rather than sometimes picking the folder from the settings and sometimes from previous browsing.

**Comment by baldurk** [comment]
There doesn't seem to be a built-in way to do what you're after. I found that a reasonable compromise was to just remember whether or not a capture had been saved, and if so use that directory instead of the one in the settings window. It'll remain sticky until the UI is closed, it'll default back to the settings-specified directory next time you launch.

I _think_ this should now do what you're after. Please take a look at a nightly build after today to see if it behaves as you expect. If so, I'll leave it as-is and hopefully no-one will want a slightly different variant on that behaviour :).

**Comment by bejitt** [comment]
Apologies for the quite late response. I tried again with 0.32 and it's definitely looking like what I was after!
