### ISSUE TITLE
Load/Save Settings in the Launch Application Tab to open specific folder

### ISSUE THREAD

**Issue by vkaytsanov** [baldurk/renderdoc#3350]
## Description

Currently, the Load/Save Settings in the Launch Application Tab will always open the folder that the currently debugged executable is located at.
![image](https://github.com/baldurk/renderdoc/assets/49615597/8eea01a8-8b5b-4045-8104-49d11cc36fa6)

However, when working on multiple projects, it takes time to locate the specific folder that I, personally, keep all my capture settings for all my projects, select it and start debugging.

Would be nice if it is possible for the windows that open through these buttons open a specific folder, that is either set from settings or by default, the last opened.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
