### ISSUE TITLE
Load/Save Settings in the Launch Application Tab to open specific folder

### ISSUE THREAD

**Issue by vkaytsanov** [baldurk/renderdoc#3351]
## Description

Currently, the Load/Save Settings in the Launch Application Tab will always open the folder that the currently debugged executable is located at.
![image](https://github.com/baldurk/renderdoc/assets/49615597/8eea01a8-8b5b-4045-8104-49d11cc36fa6)

However, when working on multiple projects, it takes time to locate the specific folder that I, personally, keep all my capture settings for all my projects, select it and start debugging.

Would be nice if it is possible for the windows that open through these buttons open a specific folder, that is either set from settings or by default, the last opened.

## Environment

* RenderDoc version: 1.33
* Operating System: Windows
* Graphics API: N/A

**Comment by baldurk** [comment]
I don't think that adding a config entry for this is a justified change because while it might provide you an incremental improvement it might make things worse for someone else. The file browser does not open to the folder of the currently debugged executable, it defaults to the last directory that was browsed to in a file browser. That's certainly not going to be ideal for everyone in every case but I think it is a reasonable general default not knowing how people might locate their files in different contexts.

If you want to have customised logic to save you a click and open always on the exact folder you want, you could write a UI extension. Or alternatively you could use the 'recent capture settings' entry under the file menu to open them directly providing you have fewer than 10, or also drag and drop the settings file onto the UI to open it.

**Comment by vkaytsanov** [comment]
Recent Capture Settings is an elegant solution. Thank you for sharing and excuse me for bothering
