### ISSUE TITLE
crash if "VK_KHR_get_physical_device_properties2" is not enabled when "Enable API Validation"

### ISSUE THREAD

**Issue by llcxiongmao** [baldurk/renderdoc#3361]
crash if "VK_KHR_get_physical_device_properties2" is not enabled when "Enable API Validation",
I do not find any note from doc, it is a bug?

Reproduce:
- Just use VulkanSdk vkcube demo.
- Use this code create instance:
```
	// If not enable "VK_KHR_get_physical_device_properties2", 
	// it is will crash when "Enable API Validation" checked.
	const char* _tmp[] = {
		VK_KHR_SURFACE_EXTENSION_NAME,
		VK_KHR_WIN32_SURFACE_EXTENSION_NAME,
		// "VK_KHR_get_physical_device_properties2"
	};

	VkInstanceCreateInfo inst_info = {
		.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
		.pNext = NULL,
		.flags = (portabilityEnumerationActive ? VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR : 0),
		.pApplicationInfo = &app,
		.enabledLayerCount = demo->enabled_layer_count,
		.ppEnabledLayerNames = (const char* const*)instance_validation_layers,
		.enabledExtensionCount = 2,
		.ppEnabledExtensionNames = _tmp,
	};
```
- check "Enable API Validation".

My environment:
- System: Windows 10 64bit.
- VulkanSdk: 1.3.268.0.
- RenderDoc: 1.33.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
