### ISSUE TITLE
Couldn't start global hook

### ISSUE THREAD

**Issue by deapqeab** [baldurk/renderdoc#3374]
![OI87}%S_)~{I`AKB$9KXGFH](https://github.com/baldurk/renderdoc/assets/63036894/e1ed3371-5831-459c-8224-d4121867b2c7)

How do I make short paths enabled?

RenderDoc version: 1.33
Operating System: windows11

**Comment by Zorro666** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by Porco24** [comment]
use this cmd command can fix the problem

fsutil file setshortname "D:\Program Files\RenderDoc" RENDER~1

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
