### ISSUE TITLE
Identical expressions. Probably meant .width || .height

### ISSUE THREAD

**Issue by Sluggernot** [baldurk/renderdoc#3377]
https://github.com/baldurk/renderdoc/blob/aa5538b2e92a266b9126c75f085abdc508597c10/renderdoc/core/image_viewer.cpp#L758

Line is if(texDetails.width > 16384 || texDetails.width > 16384)

**Comment by Zorro666** [comment]
This does look a code mistake and would want to see this as a bug report with a reproduction to drive code change. In this case an image with width < 16384 and height > 16384 might create a bug

**Comment by Zorro666** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by Sluggernot** [comment]
Thanks. I am looking for real contributions to be made. I am trying to avoid being a contributor to the project through some cheap means like this.
