### ISSUE TITLE
Identical statements in if and else if. 

### ISSUE THREAD

**Issue by Sluggernot** [baldurk/renderdoc#3378]
https://github.com/baldurk/renderdoc/blob/aa5538b2e92a266b9126c75f085abdc508597c10/renderdoc/driver/d3d11/d3d11_device_wrap.cpp#L1740

Not completely sure what may have been meant but we have two identical statements in the if and else if. 
Possible D3D_PRIMITIVE_TOPOLOGY_POINTLIST was meant for the first if statement?
 D3D_PRIMITIVE_TOPOLOGY_POINTLIST	= 1,
 D3D_PRIMITIVE_TOPOLOGY_LINELIST	= 2,
 D3D_PRIMITIVE_TOPOLOGY_LINESTRIP	= 3,

**Comment by Sluggernot** [comment]
Line 1820 there is an identical issue. 
Let me know if you just want a pull request.

**Comment by Zorro666** [comment]
Thank you for the static analysis or compiler warning report.
In this case it does like a real code mistake however there hasn't been a user report of a bug associated with it and ideally project change is driven by user bug reports. In this case would need a geometry shader that generates points to expose the problem.

**Comment by Zorro666** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
