### ISSUE TITLE
Export to bytes does not export the full buffer

### ISSUE THREAD

**Issue by roamic** [baldurk/renderdoc#3385]
## Description

When exporting a constant buffer to bytes it only exports part of the buffer (in my example `array_size` bytes instead of `array_size * sizeof(element)`). CSV works fine.

![image](https://github.com/user-attachments/assets/aecda7b9-0c08-43ef-8140-def034bf4e46)
![image](https://github.com/user-attachments/assets/f5b9d0ca-fa7d-44a3-85df-c594a50fb91b)

## Steps to reproduce

* Capture Vulkan frame
* Open a shader with constant buffer containing an array of floats
* Open the buffer view of this binding
* Save this constant buffer as bytes

## Environment

* RenderDoc version: 1.33
* Operating System: Windows 11
* Graphics API: Vulkan 1.3

**Comment by Zorro666** [comment]
Hi

I am not able to reproduce this in my testing.  Are you able to share the reproduction case or provide further details in particular the shader declaration for the constant buffer, the uniform buffer binding details, the type of shader (vertex/fragment/compute) i.e.

![image](https://github.com/user-attachments/assets/b9d4a774-778c-4087-bc42-1886a37218e8)

Without a reproduction going to be hard to narrow down what the problem is.

**Comment by roamic** [comment]
I've tried to reproduce it and it does not reproduce!
There's probably more to the reproduction steps then. I will re-open the issue if this happens again.
