### ISSUE TITLE
Compute shader local_size ID's are not diplayed correctly

### ISSUE THREAD

**Issue by Trider12** [baldurk/renderdoc#3393]
## Description

I have a compute shader with the following group size declaration:
```c
layout(local_size_x_id = 0, local_size_y_id = 0) in;
```
I then pass this ID as a single uint32_t value:
```c
uint32_t value = 32;
VkSpecializationMapEntry specEntry { 0, 0, sizeof(uint32_t) };
VkSpecializationInfo specInfo { 1, &specEntry, sizeof(uint32_t), &value };
```
However, Renderdoc displays this:
![image](https://github.com/user-attachments/assets/384b31f8-ddcb-4dcc-bf9b-63f96cb8f362)

I don't know where the value 1 comes from, but it's definitely wrong.

## Environment

* RenderDoc version: 1.33
* Operating System: Windows
* Graphics API: Vulkan

**Comment by Zorro666** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In GitHub when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
