### ISSUE TITLE
Crash in Texture Viewer on Intel GPU

### ISSUE THREAD

**Issue by bonizz** [baldurk/renderdoc#340]
I get a crash on my Intel HD 530 when viewing the Texture Viewer tab and clicking on the EID (70-81) "execute_tristrip_godl" with this capture file:
[test.zip containing test.rdc](https://github.com/baldurk/renderdoc/files/439851/test.zip)

I'm running off the git repo, and see this in the output log, but I cannot find exactly where it's crashing:
```
First-chance exception at 0x12d38a0e in renderdocui.exe: 0xC0000005: Access violation reading location 0x00000058.
A first chance exception of type 'System.AccessViolationException' occurred in renderdocui.exe
An unhandled exception of type 'System.AccessViolationException' occurred in renderdocui.exe

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
````

I'm on driver version 20.19.15.4364 WHQL / Win10 64.

When I switch to my nvidia 960M, I don't get the crash.

Side issue, I also noticed it looked like it was using uninitialized values in RenderTexture(), specifically TextureDisplay::offx and TextureDisplay::offy.  (I added
`disp.offx = disp.offy = 0.0f;` in replay_output.cpp line 496.)

**Comment by baldurk** [comment]
I can repro it, thanks for including the capture. I think I've seen something like this before but didn't have a solid repro. I believe it's a driver bug when binding both depth and stencil as readable SRVs in a drawcall.

I'll dig into it more next week and see if I can produce a simple repro app to send to Intel for fixing, but I can't say when a fix would be available or what driver it would be in. I'd suggest if you have access to an nvidia (or AMD) card that's always a better option, only using Intel if there's not an alternative available.

**Comment by bonizz** [comment]
Cool, right, I actually didn't know RD was using my Intel card, and switched it to now use nvidia for RD.  Thanks.

**Comment by baldurk** [comment]
I've isolated it to a simple standalone program that produces the crash, I'll report to Intel shortly.

It's possible that I could work around it in renderdoc, but I think what I'd need to do to workaround it would then break stencil display on AMD. Since the current code is valid and shouldn't be crashing, and I suspect I have more users on AMD, unfortunately there's not much I can do directly about this.

All I can do is recommend that anyone running into this uses a discrete card (NV/AMD) if possible, and if not you can try locally backing out c35531c65fd5b07b688867b4d2499836436eef2a - this may or may not help. Otherwise just wait until a fixed driver is out :(.

**Comment by baldurk** [comment]
[Reported to Intel](https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/681813).
