### ISSUE TITLE
Unreal 4 crashes if start in D3D11 with 1.34

### ISSUE THREAD

**Issue by BleuBleu** [baldurk/renderdoc#3404]
## Description

With the latest version (1.34), I get a crash on D3D11CreateDevice when starting the UE4 editor with `-d3d11`. This did not happen with 1.31.

## Steps to reproduce

1. Start `UE4Editor.exe -d3d11`
2. Crash

## Environment

* RenderDoc version: 1.34
* Operating System: Win11 64-bit
* Graphics API: D3D11

I have a NVIDIA RTX3060 and I think I also have some AMD onboard graphics that isnt used (I dont think I have any drivers installed for it either). 

The callstack of the crash shows atixx.dll, so is it possible that somehow when RenderDoc is active, it tries to use the onboard graphics instead of my discrete GPU? Just a thought.

**Comment by baldurk** [comment]
I can't reproduce this, though I don't have an identical system with AMD integrated GPU and NV discrete GPU.

If you have an AMD GPU in your system then the drivers will quite likely be used one way or another, even just for enumeration. If you have a laptop then the display is likely driven by the built-in GPU whether or not you're using the discrete card. If you've never updated your AMD drivers they are quite possibly wildly out of date, I would recommend updating them to latest.

If the crash is in AMD's driver then this is more likely an AMD driver bug - is RenderDoc's crash handler kicking in, or is Unreal's? After updating your AMD drivers can you either submit the crash or share the minidump depending on which crash handler is catching it? Do you have the possibility of testing on a machine without an AMD integrated GPU or a desktop where the GPU is disabled in the BIOS?

I don't see any relevant changes between v1.31 and v1.34 on D3D11 capturing that could indirectly trigger this. Are you sure that it works on v1.31 and breaks on v1.34 or have you not run with RenderDoc for a while and the only time you've tested it recently is on the latest version where it crashed? If so then it may be caused by something else.

**Comment by BleuBleu** [comment]
Im not getting this anymore. Sorry for the confusion, not sure what fixed it. 🤷 
Keep up the good work.

-Mat
