### ISSUE TITLE
Incorrect handling of RTT Cubemaps in GL

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#341]
In D3D11, RenderDoc correctly displays render to texture cubemaps by face: +X, -X, +Y, -Y, +Z, -Z

However in GL, RenderDoc renders everything into face +X; thus incorrectly replaying what was shown in the original capture.

I'm attaching a small demo. Just capture with GL and see that the playback won't match what was seen in the original run (also the bug can be seen in the texture browser).

Repro demo can be downloaded from: http://www.mediafire.com/download/8mavd18nazbqj34/RenderDocBug.7z

Additionally, it would seem something similar happens with D3D11's pixel history (draw calls from the different faces get stacked). Though that's very minor since it doesn't break anything or bother much.

**Comment by baldurk** [comment]
OK I think this should fix both bugs. The GL side one is just because GL is ~~stupid~~ awkward with its handling of binding cubemap faces to framebuffers, but just needed a bit of extra handling and dropping use of DSA.

The D3D11 one I didn't find that all drawcalls were stacked - it just appeared that clear calls wouldn't pay attention to which mip/slice was selected. I think I've fixed that, but can you check the behaviour? If you're seeing a case where actual drawcalls are getting included in the wrong history can you give more details on that, because I think with these changes it should all be correct now.

Let me know how it looks for you on the next nightly build or if you make a build yourself. I'll close this with the next stable version unless there's something else that seems broken or the fix hasn't worked for you.

**Comment by baldurk** [comment]
I believe this should now be fixed in [v0.31](https://github.com/baldurk/renderdoc/releases/tag/v0.31). If there's something remaining to do, please comment and I'll re-open.

**Comment by AllianceDarkSylinc** [comment]
Oops! Sorry. Forgot to comment. Yes. This is fixed and can be closed.
