### ISSUE TITLE
OpenGL Program run through RenderDoc crashes when a frame capture is taken

### ISSUE THREAD

**Issue by qFelixDev** [baldurk/renderdoc#3410]
## Description

I'm currently trying to create a frame capture of my Program. This works fine on my PC, on my Laptop (of which the specs are listed below) however, the Program freezes for 5 seconds then crashes with this error without producing a capture. X is a very large number that is not consistent.

Fatal - Allocation for X bytes failed

## Steps to reproduce

1. Extract the zip file I have provided
2. Run ResontideServer
3. Run ResontideClient through RenderDoc
4. Attempt to create a capture
5. If the program doesn't crash here you probably don't have the same Hardware or Drivers as I do.

If I was able to show a capture, I wouldn't be creating this issue.

## Environment

* RenderDoc version: v1.32 (Possibly earlier) - v1.34
* Operating System: Arch Linux x86_64
* Graphics API: OpenGL 4.3
* Desktop Environment: Budgie 10.9.2
* Windowing System: X11
* CPU: Intel Core i7-1165G7
* GPU: Intel Iris Xe Graphics G7 96EU Mobile
* GPU Driver as described in Budgie Settings: Intel Iris Xe Graphics (TGL GT2)
* System Memory: 16 GB LPDDR4X 4267 MHz in Dual Channel

[Resontide.zip](https://github.com/user-attachments/files/16634884/Resontide.zip)

**Comment by qFelixDev** [comment]
I just tested it again and it printed this "Fatal   - Allocation for 159642125736800 bytes failed". Why is it trying to allocate 159 TB of RAM?

**Comment by baldurk** [comment]
The out of memory error is because a texture is being created that would require that many bytes for storage. The program looks to create a single 2D texture and its dimensions seem to vary unpredictably but width and height are usually both out of valid bounds with width being quite massive, e.g. `1626870080x29282` or `1102582080x29072`.

This is invalid use of the API as GL requires all dimensions to be less than `GL_MAX_TEXTURE_SIZE` (16384 on my system). You should run you program with validation enabled and maybe check for uninitialised memory given that the values are not consistent and look like they are random.

**Comment by qFelixDev** [comment]
That checks out, I added a texture to my game recently with a resolution of 3072 x 3072 recently. I'll try running with validation enabled and see what I get. Thanks for your help!

**Comment by qFelixDev** [comment]
How do I run my Program with validation enabled?

**Comment by baldurk** [comment]
You should look for GL documentation on how to enable validation. I do not recommend trying to enable or run validation with RenderDoc as this can cause false positives or false negatives.

Especially in this case because the error is most likely in your code itself and not your API use if there is uninitialised memory use, you would be best put at looking at regular CPU debugging or memory sanitisers.

**Comment by qFelixDev** [comment]
It turns out that my asset embedder had a bug where the file size and file name length got mixed up making OpenGL think that "blocks.png" was just 10 bytes large. Yikes!
