### ISSUE TITLE
Can't capture on Linux, SDL2, bgfx-OpenGL

### ISSUE THREAD

**Issue by zefir1990** [baldurk/renderdoc#3415]
When I am trying to capture OpenGL with qrenderdoc on Arch Linux, I can't get any output. Everything works correct with clean bgfx, SDL2, OpenGL sample, but for some reason does not capture anything for my SurrealEngine fork.

## Steps to reproduce

1. git clone git@github.com:demensdeum/SurrealEngine-Emscripten.git
2. cd SurrealEngine-Emscripten
3. git checkout BGFX-DrawComplexSurface
4. mkdir build
5. cd build
6. ../buildScripts/Native/build.sh
7. find and put "Unreal Tournament 99" game into "UnrealTournament" directory inside build
8. run qrenderdoc with SurrealEngine binary
9. try to capture any frame -> nothing

## Environment

* RenderDoc version: 1.34
* Operating System: Arch Linux
* Graphics API: Bgfx - OpenGL frontend

Laptop with Intel + Nvidia GPU, nvidia-open drivers, KDE, Wayland

![Screenshot_20240822_190447](https://github.com/user-attachments/assets/22c977cf-389a-4ebd-ac81-88ead677341f)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by zefir1990** [comment]
Found that there was window initialization for Vulkan + Vulkan Context, after that I use OpenGL context for rendering. 
After removing whole Vulkan part, and keeping only OpenGL - renderdoc starts to capture correctly. 
Looks like mixing Vulkan and OpenGL is a bad idea.
@baldurk
