### ISSUE TITLE
Vulkan: Naming broken for command buffers

### ISSUE THREAD

**Issue by vmilea** [baldurk/renderdoc#3421]
## Description

RenderDoc shows a generic tag like "Command Buffer 215" instead of the actual object name. The name is displayed correctly in other debuggers like NVIDIA Nsight Graphics.

## Steps to reproduce

1. Create a command buffer.
2. Name it using `vkSetDebugUtilsObjectNameEXT()` with `VK_OBJECT_TYPE_COMMAND_BUFFER`.
3. Capture a frame.

## Environment

* RenderDoc version: v1.34
* Operating System: Windows 11
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Yes since these names are not semantic and it's up to each tool to interpret them, this is a known/deliberate case where names are not applied to command buffers due to their complex lifecycle and because in the vast majority of cases an individual command buffer object doesn't have a meaningful name.

For command buffers, annotation is much better provided by `vkCmdBeginDebugUtilsLabelEXT`/`vkCmdEndDebugUtilsLabelEXT` and `vkCmdInsertDebugUtilsLabelEXT` within the commands themselves.

**Comment by vmilea** [comment]
Thanks for the quick reply (and this excellent tool)! I agree the utility is small for most apps. In case you ever revisit the decision, it shouldn't be too difficult: lifecycle states are irrelevant for naming, just make sure to track when the command buffer is destroyed by `vkFreeCommandBuffers()` or `vkDestroyCommandPool()`.
