### ISSUE TITLE
Error replay hardware incompatible encountered when trying to run a capture

### ISSUE THREAD

**Issue by derpyzza** [baldurk/renderdoc#3431]
## Description

Hello, when trying to replay a capture, renderdoc displays a popup that reads:
"failed to open capture.rdc for replay

current replaying hardware unsupported or incompatible with captured hardware: Couldn't create OpenGL ES 3.x replay context- required for replay".

This error is strange, since i'm attempting to run the replay on exactly the same hardware as the one that captured it i.e on the same machine. Not only that, but the application that i'm trying to debug doesn't even use OpenGL ES, it uses OpenGL Core 3.3, as set up by an SDL variable in the code as so:

```c
SDL_GL_SetAttribute( SDL_GL_CONTEXT_MAJOR_VERSION, 3 );
SDL_GL_SetAttribute( SDL_GL_CONTEXT_MINOR_VERSION, 3 );
SDL_GL_SetAttribute( SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
```

I'm not quite sure what could be causing this bug, and the error window is quite unhelpful too considering that i can't figure out how to get it to explain what's wrong in more detail. 

## Environment

* RenderDoc version: v1.33 (Built from unknown source)
* Operating System: Fedora linux 40
* Graphics API: OpenGL Core 3.3
* Windowing system: Wayland
* GPU: Intel® UHD Graphics 620 (KBL GT2)
* SDL Version: 2.30.3

Attached is a screenshot of the error i get

![image](https://github.com/user-attachments/assets/6c16afbc-2c12-4c95-8344-50cb523a8178)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
