### ISSUE TITLE
Dispatch call  query build-in CS invocation is zero in DX12.

### ISSUE THREAD

**Issue by POLO-huhu** [baldurk/renderdoc#3458]
## Description
![image](https://github.com/user-attachments/assets/ada78863-6983-4d32-8eda-44efb30362f4)
there are two dispatch  have zero cs invocation

![image](https://github.com/user-attachments/assets/e8bf71a5-d98d-4214-a65f-87f067642d33)
As we see, dispatch call have been performed and shader look likes right. Most cs invocations of dispatch call  is right but there are always errors like this in every file

## Steps to reproduce
1  UI open rdc file
2 windows--> perfCounterView->capture counters->build-in->cs invocations->sample counters
3 find some cs invocations is zero but dispatch have been performed

## Environment
* RenderDoc version: v1.32
* Operating System: win10
* Graphics API: DX12

**Comment by POLO-huhu** [comment]
![image](https://github.com/user-attachments/assets/58f4dbec-5885-41ff-ad28-001ea8fb16e5)
more example

**Comment by baldurk** [comment]
For steps to reproduce, as detailed in [the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) please share a specific and complete reproducible test case that I can use to investigate the problem, such as a capture or executable depending on what is most relevant to the bug. Without a repro case it is usually impossible for me to replicate the situation you are running into, and it can easily waste time trying to reproduce a problem that is not as expected or described.

Please ensure that you have run your program on its own (not from RenderDoc) with API validation and have checked that your program does not produce any validation errors or warnings, since RenderDoc does not handle invalid API use. Make sure that you have updated your graphics drivers and if you have a different GPU or hardware available try testing on that to eliminate your hardware as a potential problem.

If you can't share your test case publicly due to privacy or NDA concerns you can contact me [via email](mailto:baldurk@baldurk.org). Even if you can't share your test case privately email is typically the best avenue if you can discuss more details than you can privately.

**Comment by POLO-huhu** [comment]
Steps to reproduce
1 UI open rdc file. Google drive link: https://drive.google.com/file/d/17BQs9CGKBlXGhS8PydKeLj07K6fHr8IR/view?usp=drive_link
2 click window--> Performance Counter Viewer ->Capture Counters-->Generic --> D3D12 build-in->CS Invocations->Sample counters
3 You can find EID 20226 and 20232 that  CS Invocations are zero but dispatch has been performed.
4 Correctly, EID 20226 and 20232 CS Invocations are not zero after we sampled counters.

Environment:
RenderDoc version: v1.35

I have tested this case in v1.35 and same results.

**Comment by POLO-huhu** [comment]
link: https://drive.google.com/file/d/17BQs9CGKBlXGhS8PydKeLj07K6fHr8IR/view?usp=sharing

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own [is not endorsed or allowed for any reason](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING.md#acceptable-use-of-renderdoc), and I will provide absolutely no support for it.
