### ISSUE TITLE
Display arguments to IDXGISwapChain::Present()

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#346]
While RenderDoc generally reports ID3D11 function argument values, it does not report the values passed for IDXGISwapChain::Present()'s arguments. Can RenderDoc report the value passed as the SyncInterval argument to Present()? The Flag values would be nice as well, but not nearly as important. Thanks!

**Comment by baldurk** [comment]
I typo'd the issue number but I think this should be sorted as of 2f2afa820b7a957f1c0c28175efeb726378fba62 - they will appear in the API inspector under the detailed list of parameters. The values weren't serialised before because generally they're fixed for the application and don't have any bearing on the actual rendering.

Let me know if you have any notes on how it's implemented, it'll be in the next nightly build. Otherwise I'll close this issue down with the next stable release.

**Comment by baldurk** [comment]
I believe this should now be implemented in [v0.31](https://github.com/baldurk/renderdoc/releases/tag/v0.31). If there's something remaining to do, please comment and I'll re-open.
