### ISSUE TITLE
Is there a bug here for replay Vulkan when call vkUnmapMemory

### ISSUE THREAD

**Issue by fuhaijin** [baldurk/renderdoc#3460]
* RenderDoc version: 1.34
* Operating System: Windows
* Graphics API: Vulkan

file:renderdoc/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp
function:Serialise_vkFlushMappedMemoryRanges, Calculate size like below：
![Serialise_vkFlushMappedMemoryRanges](https://github.com/user-attachments/assets/49570ed9-7c1f-4e3c-8134-5f264c3c83ce)
function:Serialise_vkUnmapMemory, Calculate size like below：
![Serialise_vkUnmapMemory](https://github.com/user-attachments/assets/96ccd0d5-b183-47ea-adde-93bf6a58b218)

I think there's a problem with size calculation in function Serialise_vkUnmapMemory；if mapMemory use offset!=0,size is small，“size=finish - offs” could be a very large number。

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
