### ISSUE TITLE
Vulkan - vkCmdPushDescriptorSetKHR issue

### ISSUE THREAD

**Issue by RoboMage** [baldurk/renderdoc#3461]
## Description

When using vkCmdPushDescriptorSetKHR if you set .dstSet in your VkWriteDescriptorSet object(s), normally this should have no effect. No other tools or validation layers reported this as an issue,  but it causes a crash in RenderDoc.

From the spec:

> Each element of pDescriptorWrites is interpreted as in VkWriteDescriptorSet, except the dstSet member is ignored. [vkCmdPushDescriptorSetKHR(3) Manual Page](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPushDescriptorSetKHR.html)

So, I have pretty mixed feelings for this bug.
I had passed in the wrong value to that field, but the driver just ignores it. 
Yes this is bad, but RenderDoc shouldn't read it and then crash with no explanation either. (The logs had nothing useful in them)
I would say Renderdoc should just ignore this value as well, but I don't know if this would interfere with debugging.

Side note:
The pointers returned from vkGetDeviceProcAddr are different in renderdoc. Is this intentional?
00007FFD4CFC59F0 RenderDoc
00007FFD49B9ACE0 Normal

## Steps to reproduce
Program:
    Load device extension : VK_KHR_push_descriptor
    Load procedure address for vkCmdPushDescriptorSetKHR
    Fill out VkWriteDescriptorSet and set .dstSet to non zero value
    Call vkCmdPushDescriptorSetKHR
 
 Run this program in renderdoc, and it will crash.
 Set .dstSet to 0 and it wont crash.

## Environment

* RenderDoc version: 1.35
* Operating System: Windows 10
* Graphics API: Vulkan
* Device: AMD 7900 XTX
* Driver: 24.10.1

**Comment by baldurk** [comment]
You didn't say quite explicitly (only 'non-zero') but I could only reproduce a problem if a totally invalid handle was passed like 0x12345678. If I passed a valid descriptor set it worked fine - if this isn't the case for you let me know.

As you say though, annoyingly the vulkan spec often says these values are 'ignored' rather than requiring them to be NULL so RenderDoc should handle this as well as any drivers. That commit should fix it.
