### ISSUE TITLE
Size is very large when call memcpy in function vkUnmapMemory

### ISSUE THREAD

**Issue by fuhaijin** [baldurk/renderdoc#3465]
## Description

there's a problem with size calculation in function Serialise_vkUnmapMemory；if mapMemory use offset!=0,size is small，“size=finish - offs” could be a very large number, memcpy call could be out of bounds。

file:renderdoc/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp
function:Serialise_vkUnmapMemory, Calculate size like below：
![image](https://github.com/user-attachments/assets/c5911004-a2c6-4ff2-afac-5d2a012730c4)

function:Serialise_vkFlushMappedMemoryRanges, Calculate size like below：
![image](https://github.com/user-attachments/assets/cc14ad32-91ab-42f9-9325-9f8a12d48d76)

## Environment

* RenderDoc version:  v1.34
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
