### ISSUE TITLE
D3D11 Applications wont's open

### ISSUE THREAD

**Issue by softinitializing** [baldurk/renderdoc#3470]
HI,
I am working on a DirextX11 renderer with SharpDX, the SwapChain is hosted in a WPF HwndHost,
whenever i launch the exe from RenderDoc it wont open
i simply locate the exe and click launch.
so i tried to use some games i have, mainly Dark Souls 3 that uses DirectX 11 API and Elden Ring that uses DirectX 12 API
DS3 would open and immediately close while ER works fine and i can capture as intended .
i have tried some other D3D11 games and the [SharpDX DirectX11 Tutorials ](https://github.com/RobyDX/SharpDX_Demo) but i would experience the same behavior as DS3
I also tried a D3D12 SharpDX sample and it worked without a problem .

* RenderDoc version: 1.35
* Operating System: Win11 ,Dell Laptop with intel 620 UHD and RTX3050 
* Graphics API: DirextX11

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
