### ISSUE TITLE
Durations in event browser change every time I click the clock icon

### ISSUE THREAD

**Issue by Oppodelldog** [baldurk/renderdoc#3513]
## Description of Bug
Durations in event browser change every time I click the clock icon.

(Not sure if this is a bug, or if I don't get the feature)

## Steps to reproduce
* Capture a frame
* In the event browser I find a time icon (Time durations for the actions)
* When I click on it, durations are displayed
* When I click again other durations are displayed. (my expectation would be to see no change in durations)

## Environment

* RenderDoc version: v1.36
* Operating System: Win11
* Graphics API: Vulkan

**Comment by baldurk** [comment]
No this is not a bug. Any time/profile measurement in basically any circumstance (on CPU or GPU) will have some amount of noise and variation due to many factors. The only way to ensure the durations do not change at all would be to only measure once and cache the result, which is strictly less useful than allowing re-measurement.

RenderDoc's durations are measured by inserting timestamps immediately before and after each draw, at the top and bottom of the pipe, to give the best measure feasible of how long that draw took. You can end up with significant variation due to the effects of pipelining, other driver work being included, HW clocks changing, other work on the system etc.

**Comment by Oppodelldog** [comment]
Just to be sure, I am loading one profile, then click multiple times on the clock. 
From multiple captures it would be expected to vary in times, but I am clicking the icon for one capture, shouldn't it be the same data I am looking at?

https://github.com/user-attachments/assets/ecec9e43-7134-47ce-a3f2-c6ee3afa543c

**Comment by DumbTrollface** [comment]
> Just to be sure, I am loading one profile, then click multiple times on the clock. From multiple captures it would be expected to vary in times, but I am clicking the icon for one capture, shouldn't it be the same data I am looking at?

I am having the same behavior with v1.38 and it makes no sense to me.
I'd assume that the timestamps are part of the capture. Meaning that my ONE capture should always show the same durations.
Or is the frame replicated when clicking on the icon with the timings coming from the replicated frame?

@Oppodelldog Did you find out more?

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
