### ISSUE TITLE
QRenderDoc crash on Fedora 24

### ISSUE THREAD

**Issue by Corralx** [baldurk/renderdoc#366]
QRenderDoc crash during startup on Fedora 24.
Apparently the crash happens during the window creation, attemping to call glXGetVisualFromFBConfig(...).
At that point the debugger shows that the glhooks table is uninitialized and all the pointers are set to 0x0, and setting a breapoint on PopulateHooks reveals that the function is not called at all.
I attached the stack trace recovered from gdb.
[qrenderdoc_crash.txt](https://github.com/baldurk/renderdoc/files/479738/qrenderdoc_crash.txt)

Matteo

**Comment by baldurk** [comment]
This looks like maybe a clash between recent fixes to the GL hooking code and Qt, it's picking up some of the exported symbols that are only intended for hooking external applications not really used for internal symbols.

It should be fixable, but honestly at this point it's probably not worth reporting bugs against qrenderdoc - it's barely runnable and even if you get it working, it has no usable functionality. Given the current status it's just not mature enough to be worth tracking individual bugs.

**Comment by svenstaro** [comment]
Funny, I was _just_ about to report this issue and then @Corralx showed up and already did it. This is also crashing for me on Arch Linux compiled with gcc (gcc (GCC) 6.2.1 20160830) with the exact same stacktrace.

**Comment by Corralx** [comment]
Well that's no great news.
Since I've used it with success on Windows on my personal projects, I was just about the test it at work to see if it was feasible on Linux.
I understand that being alone, maintaining all the platform/API combinations is really hard and Linux is not a priority in the 3D graphics world :)
I'll see what I can do to contribute onto the Linux/OGL path.
May I contact you privately at this point to see the state of the work and what could be done for it?

Matteo

**Comment by svenstaro** [comment]
I would prefer if the roadmap were open so that contributors like us could just choose to tackle random issues here and there.

**Comment by baldurk** [comment]
Yeh you can always email me if you want to, but I don't think there's any reason to take this privately. Right now though there's not a specific roadmap - it's just "get everything ported to Qt, doing some clean up & refactor along the way".

Getting the UI up and running on linux is definitely a priority though. The [survey results](https://renderdoc.org/survey) indicated that the next two priorities are D3D12 support and Linux native UI, so those are what I'm working on right now.

It's hard to give exact timelines as I like to stay flexible enough to respond to things when they come up and changing priorities, but I'm hoping at least there will be some basic functionality there by the start of next year. As in - not necessarily feature complete and comparable to the winforms UI, but at least usable to debug a bit.

You're welcome to PR improvements, just be aware that since the Qt UI is still pretty raw, the code will be churning a lot so there's more chance of clashes, constant rebasing and duplicated work :smile:.

**Comment by baldurk** [comment]
Oops, well one of those commits (which github decided to double-report because I pushed to two branches) should have been for #365.

Either way, I think this is fixed now and qrenderdoc is back to being working but severely non-functional :). Let me know if it fixes it for you, or if you're still having some issues.

**Comment by Corralx** [comment]
Thanks, I can see QRenderDoc launching correctly now.
As soon as I find time (this week I'm a bit constrained at work) I'll look into what needs to be done to take the Qt UI on par with the .NET one.
