### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by tinou98** [baldurk/renderdoc#367]
I reported a crash with in app reporter, and i report here to.

RenderDoc crash if we forgot to generate the program pipeline (use glGenProgramPipelines) in OpenGL 4.5

I know it's a problem in my App, but RenderDoc should not crash

**Comment by baldurk** [comment]
I can definitely fix this particular spot, but it's really a tiny drop in the ocean compared to the other undefined behaviour that can cause crashes in RenderDoc.

In general I just assume that the API is used legally. It's a huge undertaking and a project in itself to validate that API use is legal and I usually leave that up to other API mechanisms - the D3D11/12 debug layer, GL's KHR_debug and Vulkan's validation layers. The problem with trying to make RenderDoc bullet-proof against bad use is that you end up duplicating a lot of this work and it can cascade out of control. E.g. if I add some code to bail out and not crash when `glUseProgramStages` is called with an invalid pipeline, this might stop the crash there - but then it might crash in some other function. Even if it doesn't crash in any function, then the replay might crash in unexpected ways because no shader is bound, or even if it doesn't crash on replay there's probably not going to show anything obviously wrong but maybe the rendering ends up different or going crazy.

One thing I can possibly do is add more informative messages to things like asserts that I leave around - in this case an assert fired but the message was just `record` which isn't informative, but `couldn't get record for program pipeline '12345' - wrong type or uninitialised value?` might be more helpful.

I think general case API validation is not within RenderDoc's scope though, so there might still be crashes if you call in invalid ways.

**Comment by tinou98** [comment]
A better label would be a great improvement. It can say that the problem come from a gl program instead of saying that RenderDoc crash.

**Comment by baldurk** [comment]
That's roughly what I've done here, the assertions have been expanded so they will print a log message (and if you're attached to a debugger, into the debug output). It should also at least try and avoid the immediate crash, but no guarantees about further crashes later.
