### ISSUE TITLE
does not build with GCC

### ISSUE THREAD

**Issue by Marqin** [baldurk/renderdoc#369]
GCC 6.2.1 on Arch Linux

```
[  5%] Building CXX object renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/SPIRV/GlslangToSpv.cpp.o
/build/renderdoc/src/renderdoc-0.31/renderdoc/3rdparty/glslang/SPIRV/GlslangToSpv.cpp:4695:9: error: 'spv::Id {anonymous}::TGlslangToSpvTraverser::getExtBuiltins(const char*)' defined but not used [-Werror=unused-function]
 spv::Id TGlslangToSpvTraverser::getExtBuiltins(const char* name)
         ^~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/build.make:159: renderdoc/driver/shaders/spirv/CMakeFiles/rdoc_spirv.dir/__/__/__/3rdparty/glslang/SPIRV/GlslangToSpv.cpp.o] Error 1
make[3]: Leaving directory '/build/renderdoc/src/renderdoc-0.31/build'
```

**Comment by baldurk** [comment]
This is an upstream bug for glslang really, as it's in glslang code. Although it's up to them whether or not they think this warning is worth fixing or not. I suspect not as it looks like the usage is protected by `#ifdef AMD_EXTENSIONS` which is why it's not used by default, so it's not a bug.

Since the last time we went through chasing warnings though, I changed the `Release` CMake target to disable `-Werror`. Distribution packages should be building with the `Release` target which makes this moot anyway. I don't want to be chasing and muting all possible warnings across all compiler versions, sorry.

**Comment by Marqin** [comment]
How can I build it with Release target? It's not documented in COMPILING.md
`make CMAKE_BUILD_TYPE=Release` doesn't help.

**Comment by baldurk** [comment]
You have to apply the flag at the cmake command line - `cmake -DCMAKE_BUILD_TYPE=Debug`. I don't think the generated `Makefile` takes any parameters like that.

**Comment by Marqin** [comment]
I'm not using gneerated Makefile. I'm using renderdoc Makefile and in
COMPILE.md it's documented to use it, not cmake on Linux.

I see that in git-head it takes some variable to set cmake-flags, but 0.31
doesn't have it.

Which means, that 0.31 Release could't be compiled via "make" as documented
in COMPILE.md - maybe you should mention that somewhere for 0.31?

**Comment by Marqin** [comment]
I think the best would be to release 0.31.1 with option to pass
cmake_flags to main Makefile

**Comment by baldurk** [comment]
The Makefile is just there for convenience so you can type 'make' as a quick start. There's no reason you can't run cmake directly if you need something specific and it definitely doesn't say _not_ to use it in COMPILE.md.

You can just run the commands that Makefile runs and add the extra parameters you need, that will work just fine in 0.31. There's no need to make a new release just to slightly change the default optional Makefile.
