### ISSUE TITLE
View Indirect Args buffers

### ISSUE THREAD

**Issue by EvilSteve** [baldurk/renderdoc#372]
Hi,

Apologies if I'm just overlooking something - Is there a a way to view the contents of the BufferForArgs passed to DrawIndexedInstancedIndirect (D3D11)? I can see the draw call in the "API Calls" window, and know the resource ID for it, but there's no link to the buffer in the "Pipeline State" tab or anywhere else I can find.
If there's no way currently, can this be added in a future release please?

Alternatively / additionally, is there a way to view any arbitrary buffer if I know its ID?

Cheers,
Steve

**Comment by baldurk** [comment]
You're not missing anything - at the moment it's not possible to get that buffer out. It's not really part of the pipeline state, and at the moment there's not a better place where it fits in.

Currently the "API Calls" is a pretty dumb string dump of the serialised form, I do plan on making it smarter in the future so that I can display buffer names instead of IDs, and make them clickable so they'd open the resource up.

You can possibly whip up a python script to get the buffer data. Something like this might work for example:

```python
import struct

buffer = renderdoc.ResourceId(1234) # your id here

def fetch(r):
    data = r.GetBufferData(buffer, 0, 0)
    # data is now a byte array. You can interpret it with struct.unpack for example:
    print struct.unpack('IIIiI', str(bytes(data)[0:20])) # this is UINT UINT UINT INT UINT, the parameters to DrawIndexedInstancedIndirect

pyrenderdoc.Renderer.Invoke(fetch)
```

There might be a way to create a buffer viewer from python, but I'm not sure exactly how. This code should create a new viewer, but it has to run on the UI thread, and trying to do a `BeginInvoke()` hung my UI, so maybe it's not possible.

```python
import renderdocui

viewer = renderdocui.Windows.BufferViewer(pyrenderdoc, False)
viewer.ViewRawBuffer(False, 0, 0xffffffffffffffff, buffer)
viewer.Show(pyrenderdoc.GetTextureViewer().DockPanel)
```

Is there some information missing btw that you're after? Indirect calls should have the buffer contents fetched and the parameters used will be displayed e.g. in the event browser.

**Comment by EvilSteve** [comment]
Thanks for the quick reply baldurk!

"Is there some information missing btw that you're after?"
I've got a compute shader which writes to an append buffer, and then I use CopyStructureCount() to write to the instance count of the indirect args buffer, and then a DrawIndexedInstancedIndirect() call to draw all the instances written by the compute shader. I can debug the compute shader and check how many instances are being written to the append buffer, but it'd be easier if I could crack open the buffer and look at the individual fields of the struct, as written by the CopyStructureCount() call (And the other parameters).

"Indirect calls should have the buffer contents fetched and the parameters used will be displayed e.g. in the event browser."
All I see in the event browser is e.g. DrawIndexedInstancedIndirect(<1317, 0>) - is that what you're referring to (I'm fairly new to RenderDoc)? Is this maybe just a bug with the parameters to DrawIndexedInstancedIndirect()?

Cheers,
Steve

**Comment by baldurk** [comment]
Yeh it's not exactly obvious in fairness :mile:. The `<>`s are intended to signify that these parameters come indirectly, rather than directly. The values are the same as those displayed for `DrawIndexedInstanced()` - `IndexCountPerInstance` and `InstanceCount` respectively.

I omit the Start/BaseLocation parameters just to avoid visual noise, especially as they're often less interesting. Usually those ones are listed in the "API Calls" view if needed, although now that I explain it I realise that for indirect calls those parameters won't show up - for the same reason I mentioned before, it's a raw dump of what's serialised which doesn't include the indirect buffer contents.

Again as a workaround you can fetch them via python (not ideal I know! but at least it's there somewhere). This time with a one-liner: `pyrenderdoc.GetDrawcall(X).indexOffset` or `pyrenderdoc.GetDrawcall(X).baseVertex` or `pyrenderdoc.GetDrawcall(X).instanceOffset` respectively for `StartIndexLocation`, `BaseVertexLocation`, `StartInstanceLocation` for EID `X`.

I'll need to think if there's a nicer way to expose those parameters if needed, similar to how they're available for non-indirect calls.

**Comment by EvilSteve** [comment]
Ahhhh, that makes sense - I didn't realise that's what those args were :smile:

That's all I needed, thanks again!
Steve
