### ISSUE TITLE
"File/Open log" clears currently open log preemptively

### ISSUE THREAD

**Issue by Velro** [baldurk/renderdoc#378]
If I'm in one log, then hit "File/Open Log" my current log is cleared away, so I have to go re-open my current log even if I decided to close the dialog or hit cancel. Minor problem just want to have it on the radar.

**Comment by baldurk** [comment]
The issue with this is that it either leads to confusing or inconsistent UI to change it. Currently it closes the log as soon as you hit File->Open so that it's always closing the log at the same time regardless of status/workflow.

If I delayed the closing until you choose a file and hit open, then if the log is unsaved I need to prompt to save it. You're then down a rabbit hole of dialogs - if the user selects 'cancel' on the save prompt rather than yes or no, you also have to cancel the file that they chose to open.

If I left logs open until the new one had been selected but still continued to prompt for unsaved logs as soon as you go File->Open, then does the log still stay open after that until you choose a file? If so and you choose not to save a log, and then cancel out of the open, the log will still be there - does that mean closing it will re-prompt to save? Or will closing it be unprompted this time, technically losing user data without any prompt.

This might sound like me making arbitrary what-ifs, but these cases aren't uncommon. For simplicity and consistency's sake I think it's better to keep the current behaviour of closing the log as soon as you hit file->open. You won't lose anything, it just means that if you decide to cancel the open operation and go back to the current log, you need to find it again. I don't think this is is so common that it's worth optimising for at the expense of other UX flows.

Does that seem reasonable?

**Comment by moradin** [comment]
The only reasonable conclusion: renderdoc needs to be able to open multiple logs at the same time :)

**Comment by Velro** [comment]
I hadn't thought of those other cases, thanks for pointing them out. I went and tested how Unity handles this with their scenes files. They have it work like your second option, it prompts for save when File->Open is hit. If you cancel that, then try to close the app without saving, you will be prompted again. This does seem naggy, but is more reasonable than the alternative rabbit-hole you described and the user wont accidently lose any data.

Anyways, this only raised a flag to me because I've been using the app in a weird way, testing lots of different saved logs. I don't think this is a typical user flow. If it were up to me I would change it to how I described above because I accidently close my desired log through this route a couple times a day, I hit File->Open but already had the log I wanted open. Its like my gut-reaction now when I focus the app to go to that dialog. I tend to launch Renderdoc, Open log, alt-tab to something else, then come back when its done loading the capture (loading takes at least 8 seconds or so on development builds). 

I wasn't sure if it was by-design or not, now that I know it's by-design I'll close the issue.
