### ISSUE TITLE
UNCONFIRMED Crash when binding a 0-element byte SRV.

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#383]
Sorry, no time for repro this time. Also I haven't double checked, but 80% sure this is what's going on.
If I don't post now, I may forget.

This bug affects both GL & D3D11.

Calling:

`glTexBufferRange( GL_TEXTURE_BUFFER, mInternalFormat, boName, endOfBufferBytes, 0 );`

or its D3D11 equivalent:
```
D3D11_SHADER_RESOURCE_VIEW_DESC srDesc;
srDesc.Format               = DXGI_FORMAT_R32G32B32A32_FLOAT;
srDesc.ViewDimension        = D3D11_SRV_DIMENSION_BUFFER;
srDesc.Buffer.FirstElement  = lastElement;
srDesc.Buffer.NumElements   = 0;
```

Seems to completely crash an application launched from RenderDoc (before even capturing with F12!) giving a callstack deep inside ntdll with a completely useless callstack.

**Comment by baldurk** [comment]
I can't reproduce the crash just with these calls, however I can believe that a crash might happen some time later if you tried to use the texture or SRV.

The problem is that both cases here are invalid API use, and we go off the deep end into undefined behaviour.

For GL it explicitly says that [size 0 texture buffers](http://docs.gl/gl4/glTexBufferRange) aren't valid:

> GL_INVALID_VALUE is generated if offset is negative, **if size is less than or equal to zero**, or if offset + size is greater than the value of GL_BUFFER_SIZE for buffer.

For D3D11 there isn't a nice spec and the MSDN docs as usual are horrible, but the debug layer warns with this message:

> D3D11 ERROR: ID3D11Device::CreateShaderResourceView: The Dimensions of the View are invalid due to at least one of the following conditions. Assuming this Format (0x2, R32G32B32A32_FLOAT), ElementOffset (value = 5) must be between 0 and the maximum offset of the Buffer, 9, inclusively. With the current ElementOffset, ElementWidth (value = 0) must be between 1 and 5, inclusively, in order that the View fit on the Buffer. [ STATE_CREATION ERROR #128: CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS]

In this case the buffer was 160 bytes == `float4[10]`. I got the same result when setting `ElementOffset` to 9, except that it says `ElementWidth` (misleading - it means `NumElements`) must be between 1 and 1.

As mentioned in #367 in general it's quite hard to get RenderDoc to cope with any possible invalid API use robustly as it can have a cascading effect, and detecting all such cases is a non-goal of the project (better suited to API validation layers).

If you're having a crash elsewhere on code that should be valid (or I've misunderstood your repro case) then let me know, otherwise I think this is probably not going to be fixed :frowning_face:.

**Comment by darksylinc** [comment]
Interesting! Didn't know. Thanks! (on D3D11 we had an assert that prevented the code from triggering in debug mode, and in Release mode the validation layer was being turned off)
Yeah, I now prevent this from happening at all and the crashes are gone.

Turns out this scenario would be sensitive to "what was rendered before" due to how we reuse texture buffers; thus it would happen if that's the first thing we do during a frame. That's why it was crashing on the first frame but not on other frames.

Thanks.
Let's close it. If I see the crash again after fixing this bug, I'll prepare a repro. Otherwise I guess it can be dismissed.
