### ISSUE TITLE
Crash when exporting buffer texture

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#387]
To reproduce:
1. Open log https://owncloud.hpi.de/index.php/s/TyUzlhe2vxT0wyE (same log as in #386)
2. select event section "ISM CS", then the "Point Buffer" texture
3. click the "save" icon to export it
4. renderdoc closes. (even worse, without showing the crash reporter)

the texture in question is a buffer texture, so basically a texture with a one-dimensional buffer as memory, and has 8 million rgba32f elements.

**Comment by baldurk** [comment]
This should be fixed - at least, I'm now able to export the texture to disk without a crash. However for that texture it ends up being really wide so the viewers I tried (including RenderDoc) can't then open and view the resulting file. You might have more luck since it is a buffer using the 'open texture as buffer' and saving it to a binary blob. Or to CSV if it makes sense to subdivide it.

(Side note - I wasn't able to repro the crash reporter not kicking in, but it was an unhandled exception in the C# code so I wouldn't be surprised if something was busted there.)

**Comment by karyon** [comment]
there is no new nightly again :(

**Comment by baldurk** [comment]
I'm not sure what's wrong this time, I kicked it manually and it built OK, and the scheduled task is still enabled. I'll keep an eye on it and see what happens tomorrow.

**Comment by karyon** [comment]
can confirms that the export does not crash, but the resulting file cannot be read anywhere :)

**Comment by baldurk** [comment]
Thanks!
