### ISSUE TITLE
Exporting miplevels produces garbage output

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#390]
When exporting a texture as png or jpg, selecting any other than miplevel 0 will result in garbage. the dimensions are correct.

example: 
![ism_single_pixel_pl3](https://cloud.githubusercontent.com/assets/1891915/19153851/67121ed0-8bd8-11e6-85e8-55e7fc8ab4db.png)

when i export as dds, i can open the result in renderdoc and it looks fine, but paint.net, wtv and DDSviewer fail to open the exported file.

**Comment by baldurk** [comment]
There turned out to be a couple of bugs here, I think I've got it straightened out but let me know if you still run into problems - there might still be broken cases.

As to dds files, there are a lot of dds viewers that don't support modern formats, with the new DX10 header to indicate an arbitrary DXGI_FORMAT. That might be it? I think RenderDoc produces and consumes valid DDS files, so in that case I would say it's more likely a viewer incapable of reading the file rather than a broken file.

**Comment by karyon** [comment]
png export of miplevels works. didn't check the dds thing again.

**Comment by baldurk** [comment]
Thanks!
