### ISSUE TITLE
Version 0.31: Crash in GetProcAddress with some .NET programs

### ISSUE THREAD

**Issue by ChaosCom** [baldurk/renderdoc#394]
I've submitted several minidumps but thought that it might be worthwhile opening an issue here on github as well. 

I believe there's a problem with the hooking code in Version 0.31. From the dumps I see a 

Unhandled exception at 0x000007FEE4513BCB (renderdoc.dll) in c736506a-7a24-4e5e-80a4-5ffa809a5ca5.dmp: 0xC0000005: Access violation reading location 0x0000000000000000. and the call stack shows that it occurs at

>   renderdoc.dll!Hooked_GetProcAddress(HINSTANCE__ \* mod=0x00000000002bdf41, const char \* func=0x00000000002bdf70) Line 496    C++

Since the minidumps don't contain heap info, i can't tell what the function name is that it tries to hook. All I know is that previous versions (Tested 0.30, 0.25 and 0.21) don't have the issue, so it has to be something that has been recently introduced. Both Versions (32bit and 64bit) exhibit the same behaviour (all of the above is from a dump of the x64 version)

**Comment by baldurk** [comment]
Hey, this happens with .NET programs that use P/Invoke's `DllImport` on the functions `GetProcAddress` or `LoadLibrary`. They end up calling `GetProcAddress("GetProcAddress")` or `GetProcAddress("LoadLibrary")` which indeed was broken on v0.31 master.

A fix has been [submitted since](https://github.com/baldurk/renderdoc/commit/cf5059706e701fc4ea87026e1f736bc1d777df60) so if you try any recent nightly build it should work for you.

**Comment by BleuBleu** [comment]
I can confirm the nightly build fixes an a crash we had in our .NET app that started in 0.31.

**Comment by mellinoe** [comment]
Just wanted to chime in here and say that the latest nightly build works with my .NET program as well. Cheers!

**Comment by baldurk** [comment]
This should be resolved in v0.32. If something's still not right in the latest build then let me know and I'll re-open and investigate.
