### ISSUE TITLE
No matching signal

### ISSUE THREAD

**Issue by Uroc327** [baldurk/renderdoc#410]
I've installed renderdoc v0.31 from aur.archlinux.org. Now when starting `qrenderdoc` I get the message

    Log     - QRenderDoc initialising.
    QMetaObject::connectSlotsByName: No matching signal for on_findHighlight_timeout()
    zsh: segmentation fault (core dumped)  qrenderdoc

**Comment by baldurk** [comment]
I think that message is harmless, it happens when there's a slot with the correct naming scheme to be automatically connected but no signal that would follow the scheme. The crash is something else.

I'd need at least a callstack or a repro or something to investigate. But qrenderdoc in v0.31 is basically non-functional and kind of unmaintained. There are improvements with the master branch, but it's still not anything really usable.

If you still want to get it running, can you try again with latest master branch code and give some more info on what's crashing - if it still does?

**Comment by Uroc327** [comment]
The problem seems to be fixed on the latest master branch, thanks.

I could only provide you with a backtrace without debugging symbols as v0.31 does not seem to build on my machine with buildmode set to `Debug`.

**Comment by baldurk** [comment]
If it's fixed on latest master branch then it's fine :smile:.
