### ISSUE TITLE
d3d debug runtime doesn't work with RenderDoc?

### ISSUE THREAD

**Issue by sebbbi** [baldurk/renderdoc#418]
When RenderDoc Unreal Engine plugin is active, there's no DirectX debug runtime output and no break on error.

RenderDoc outputs this at the beginning (related?):
d3d11_device.cpp( 766) - Warning - Returning a dummy ID3D11InfoQueue that does nothing. This ID3D11InfoQueue will not work!

Do you think this problem could be caused by RenderDoc or do you think there's a bug in the UE plugin? If I disable the RenderDoc plugin (+restart) d3d debug outputs / break works fine.

**Comment by baldurk** [comment]
Yes this is deliberate behaviour, RenderDoc takes control over the debug layer to make sure there's no interference between the application trying to control it and RenderDoc trying to control it.

If you want to enable the debug layer and include messages in frame captures, you can check the "Enable API Validation" [capture option](https://renderdoc.org/docs/window/capture_log_attach.html#capture-options), and any messages will be included in the capture. You can then look them up in the replay UI and jump to the particular drawcall where they happened.

If you need the output in the debugger, the in-application API has [an option to un-mute the output](https://renderdoc.org/docs/in_application_api.html#_CPPv2N23RENDERDOC_CaptureOption33eRENDERDOC_Option_DebugOutputMuteE) so you can see it, but this would just be the output, it wouldn't include any filters or break on error or anything like that.

**Comment by sebbbi** [comment]
I like to have RenderDoc plugin always loaded so that I can press a single button to fire a RenderDoc capture at any point. But I also want to have d3d debug breaks and debug output always active (every frame and especially during startup) to ensure that I haven't written any bugs that violate the API rules.

Un-mute is a partial solution. Unfortunately I need filters, as Unreal Engine is rendering 2d full screen passes without a vertex buffer using SV_VertexID to generate the quad geometry (d3d debug would complain about that several times every frame).

Could you take my ID3D11InfoQueue object or array of D3D11_INFO_QUEUE_FILTERs as a parameter?

**Comment by sebbbi** [comment]
This is the exact list of things I need to mute:
D3D11_MESSAGE_ID_OMSETRENDERTARGETS_INVALIDVIEW, 
D3D11_MESSAGE_ID_QUERY_BEGIN_ABANDONING_PREVIOUS_RESULTS,
D3D11_MESSAGE_ID_QUERY_END_ABANDONING_PREVIOUS_RESULTS,
D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_EMPTY_LAYOUT,
D3D11_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_TOO_SMALL,

**Comment by baldurk** [comment]
I'm not sure exactly what you mean - do you mean the in-application API should accept those? That's not really possible as it's API and platform agnostic, so it can't have D3D constants or interfaces.

I think a possible compromise would be to expose a separate UUID that you could QueryInterface from that would give you the real ID3D11InfoQueue object instead of the wrapped dummy one. That way applications would have to opt-in knowing that they're going past the RenderDoc wrapping, and would have to obey additional restrictions to make sure nothing breaks. But that way you could set up the filters and break-on-error stuff. You would still have to enable the API validation capture option before creating the D3D device, or the D3D11_CREATE_DEVICE_DEBUG flag would be removed.

Bear in mind though, RenderDoc is not intended to be loaded 100% of the time since it has a bunch of extra overhead. If there's a reasonable compromise then I'm fine, but it's not going to be a design goal to support it so you're kind of on your own to some extent :smile:.

**Comment by sebbbi** [comment]
I am aware that RenderDoc has some CPU overhead. However we are mostly compute shader based and aren't issuing huge amount of draw calls, so this doesn't affect us. Our development computers also are high end i7 models. Some extra CPU overhead is fine, as long as it improves iteration time. I also tend to have d3d debug runtime always active on my development computer. It eats even more CPU cycles. 

Exposing separate UUID for QueryInterface to get the real ID3D11InfoQueue object would be perfect. This would solve all our problems!

**Comment by baldurk** [comment]
Give it a try with that UUID query. Note that like I say, you'll still have to request RenderDoc's API validation option or enable it before creating the device, so that the debug layer is turned on at all. You'll also have to unmute the infoqueue yourself if you don't unmute it via RenderDoc's option.

**Comment by baldurk** [comment]
This should be resolved in v0.32. If something's still not right in the latest build then let me know and I'll re-open and investigate.
