### ISSUE TITLE
glMemoryBarrier()'s <barriers> argument is shown as an integer value

### ISSUE THREAD

**Issue by DominikWitczakAMD** [baldurk/renderdoc#420]
The argument is a bitfield, which can be an OR of various enums. Right now, RenderDoc shows the API call as below:

![image](https://cloud.githubusercontent.com/assets/17761066/20227173/7cb26ee0-a84b-11e6-9ce6-5d70549adb0c.png)

A potential improvement here would be to change the existing behavior to show a set of barriers the call toggles, instead of a raw int.

**Comment by baldurk** [comment]
This is partially because the API calls view is just a dump of the serialised form, and that value is serialised as a uint32. (See e.g. #271).

In this case though I can just co-erce it to an enum and get a nicer text display of the number at least so it's not too difficult to fix. Unfortunately GL doesn't have nice enums so I'll have to make one myself :/.

**Comment by baldurk** [comment]
Try with that commit, it should now display the list of barriers correctly I think.

**Comment by DominikWitczakAMD** [comment]
Works like a charm, thanks :)
