### ISSUE TITLE
Difficulty using Vulkan RenderDoc with Vulkan ANGLE

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#423]
The capture executes properly it seems but I get this message:

Failed to open file for replay: Your hardware or software configuration doesn't meet this API's minimum requirements.

Log file: https://gist.github.com/null77/43c8b29fbd822cafa3d207d1863718e7

The operative error seems to be: 

RDOC 004940: [16:45:41]  vk_device_funcs.cpp( 163) - Error   - Log requires layer 'VK_LAYER_GOOGLE_unique_objects' which is not supported

Using RenderDoc master, Release/x64. I have recently installed the Vulkan SDK - is there anything else I need to do? I have also clicked the Vulkan embedding button that shows in the RenderDoc UI. One note about ANGLE - I don't use the SDK layers, I build them from scratch on my own. Not sure if this affects capture and/or replay.

Any help figuring this out would be appreciated. RenderDoc is great and would be a huge help to development.

**Comment by baldurk** [comment]
It looks like I'm just missing a check for that layer, usually I disable validation layers on replay. If you don't have it registered system wide then it'd fail when I try to create the replay vulkan instance.

Since it looks like you're already building your own copy of RenderDoc, can you try adding that layer to [this check here in `StripUnwantedLayers`](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp#L69-L73) ?

```cpp
    // filter out validation layers
    if(*it == "VK_LAYER_LUNARG_standard_validation" || *it == "VK_LAYER_LUNARG_core_validation" ||
       *it == "VK_LAYER_LUNARG_device_limits" || *it == "VK_LAYER_LUNARG_image" ||
       *it == "VK_LAYER_LUNARG_object_tracker" || *it == "VK_LAYER_LUNARG_parameter_validation" ||
       *it == "VK_LAYER_LUNARG_swapchain" || *it == "VK_LAYER_GOOGLE_threading")
```

**Comment by null77** [comment]
Awesome, thanks for the quick response! That change worked for me.

**Comment by baldurk** [comment]
Cool, I will commit that fix then.

**Comment by null77** [comment]
Thanks again Baldur.
