### ISSUE TITLE
GL Vendor checks can cause GLX errors on linux

### ISSUE THREAD

**Issue by jonlm** [baldurk/renderdoc#424]
Hello,

Using renderdoc git commit a786668208 from today, 2016/11/14. Recorded using renderdoccmd on linux, Ubuntu 14.04, nvidia driver 349.16. Playing back in Windows 10, nvidia driver 368.39. The binary is a packaged build from UE4. I'm getting the crash shown in the attached image in Serialize_glDrawRangeElements(). It says it's crashing on line 1193 but I'm guessing it's really 1191.

Any ideas or suggestions to try? Happy to provide any additional data, although unfortunately I cannot provide the full log file. Thanks for your help!

![renderdoc_gl_draw_funcs](https://cloud.githubusercontent.com/assets/19480642/20292962/cd674a92-aaa6-11e6-97fc-a1b4573e65e6.png)
![renderdoc_gl_draw_funcs_stack](https://cloud.githubusercontent.com/assets/19480642/20292968/d59c5ff4-aaa6-11e6-89df-99ae9ddb66e8.png)
![renderdoc_gl_draw_funcs_vars](https://cloud.githubusercontent.com/assets/19480642/20292970/d82eddfa-aaa6-11e6-8baf-ce477ff11732.png)

**Comment by baldurk** [comment]
The callstack in the driver means this could be a lot of things and it's not easy to guess what. I guess you are not seeing these crashes when running without RenderDoc? I've heard of at least one person hitting a driver crash in glDrawRangeElements on linux with UE4, but they are getting that crash in the game too, not on replay.

Does the capture replay fine if you replay it on linux? ie. is it a cross-device/cross-driver/cross-OS bug, or is the capture just broken?

Without any specific reproduction steps it's hard to investigate any further, the only thing I can suggest is you get the render state at the time of the draw and inspect it to see if anything looks funky. In particular I've seen crashes before where the index  buffer isn't bound, and that causes crashes as the driver invalidly tries to read the indices directly from CPU memory, but I *should* have code in place to catch that and prevent any crashes.

You can fetch the state with something like:

```cpp
GLRenderState rs(&m_Real, NULL, READING);
rs.FetchState(GetCtx(), this);
```

in that function that's crashing.

**Comment by jon-ml** [comment]
Thanks for the help! Yeah, the exact same crash was happening when replaying on Linux too.

Ok, after some further testing, it appears that this crash is related to another problem I've been having that I was going to ask about as well.

In gl_common.cpp starting at line 328 there is some code to (quoting the comment) "Check to see if FBOs or VAOs are shared between contexts." This block of code doesn't work for me on my Linux distro / driver version. X windows throws an error and then the program quits:

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  169
  Current serial number in output stream:  169

Assuming you haven't heard any other reports of this, I suspect this may be due to being on older Ubuntu/nvidia versions but haven't had a chance to test newer versions. Unfortunately I need to use this exact distro version for other reasons. In any case I simply skipped that block and hardwired the values of "VendorCheck[VendorCheck_EXT_fbo_shared]" and "VendorCheck[VendorCheck_EXT_vao_shared]". When they are set to "true" I get the replay crash but when they are set to "false", no crash. There is some reason I'm forgetting why I thought it best to set them to true, but false seems to be the way to go.

Does that all seem plausible? Skipping that block is the only change I made to get renderdoc working for me, so makes sense I might have messed something up there.

Not sure if there's anyway reasonable way to test at runtime for skipping that whole block.

**Comment by baldurk** [comment]
Wrong values for those checks could definitely cause all sorts of broken capture or replay. I'll need to try and find a repro for the check failing in that case, I think I did hit something similar on some old 3.2 software mesa implementation I was testing.

The problem is that the original EXT_framebuffer_object extension (and ditto vertex_array_object) indicated that the objects were shared between contexts. So fbo '1' means the same in all contexts, and if you generate another in a different context it would be different. The ARB variants of both followed the convention of container objects being context-specific, so fbo '1' in the first context is distinct from fbo '1' in the second context. That's what those checks detect, because implementations vary whether they always follow the ARB rules, implement the EXT rules, or some crazy mix. The checks themselves should always work so if they cause an X error that's a bug on my side. My guess would be the context creation is failing somehow.

Unfortunately there's no conservative option. If you treat all handles as shared when they're not, then I start aliasing the use of distinct objects between contexts. If you treat all handles as *not* shared then when fbo 1 is used again on the another context from where it was created, I won't know what that refers to because I'll think it's unique. Just another thing where opengl is a nightmare :(.

I think nvidia's behaviour can be inconsistent on those handles - I've seen it go both ways. From looking at past logs, it seems like at least in some drivers VAOs aren't shared (ie. false for those checks). If false seems like a reasonable default for your case then I'd stick with that for now. I'd be curious to see which check makes the difference - ie. do they both need to be false? just one, and if so which? My guess would be VAO sharing since if I thought there was no VAO bound or the wrong VAO bound on replay (e.g. from binding what I thought was an invalid VAO because I was expecting sharing), then the data for the draw would be garbage and that might explode.

I'll leave this issue open until I can find and fix the problem with the vendor check - if the check ultimately returned true and caused a crash, that would definitely be a problem. If the check came out with a false value and it all works from there, then it's probably OK.

**Comment by jon-ml** [comment]
Ok, tried both separately. Crashes when VAO set to true, doesn't seem to be affected by the FBO setting. Happy to try any changes out in MakeContext/MakeContextCurrent, or otherwise.  I'll also see if I can try out a more updated Ubuntu.

Thanks again!

**Comment by jon-ml** [comment]
Update: I managed to find a machine with a more updated Ubuntu 14, including nvidia driver 367 and a newer X server. The VAO/FBO test worked fine on there, so my suspicions about my older distro appear to be valid. Feel free to close this out if making older driver/distro versions work isn't worth the effort.

**Comment by baldurk** [comment]
I think the chances are good that the failure is a legitimate bug, but it only happens in edge cases or older drivers/distros. I'll leave this open for a little while to see if I have any luck managing to reproduce it. If I can't, then I'll close it. It sounds like the only bug is this failing test though, which is good.

**Comment by jon-ml** [comment]
In case you ever come back to this, I did try something out. After looking at how SDL (which is what UE4 uses on Linux) deals with X11 GL contexts, I tried adding an X11 error handler routine based on theirs. Setting the error handler prevented the default X11 behavior of quitting, although you are still left with the problem of not knowing for sure what the shared FBO/VAO behavior is. Still, this is handy for not having to worry about unexpected quitting, or at least being about to control what gets printed if you want to quit.

See the SDL source file "SDL_x11opengl.c". There might be other clues in there as well, although it seems to match up pretty well to what you are doing.

**Comment by baldurk** [comment]
Right that's always possible, but in most cases an X error quickly means nothing sensible can happen after that in an application like RenderDoc. Just like segfaults and out-of-memory, it's only worth catching if I have a crash handler to catch and upload a coredump or something.

**Comment by baldurk** [comment]
I think this might be fixed together with the changes I made to support GL mesa and older contexts. Can you try with [v0.33](https://github.com/baldurk/renderdoc/releases/tag/v0.33) to see if it works better for you?

**Comment by jonlm** [comment]
Finally got a change to check this. Yep, it works! Thanks!
