### ISSUE TITLE
Problem with hooking CreateDeviceAndSwapChain for Directx11

### ISSUE THREAD

**Issue by wczmich** [baldurk/renderdoc#425]
Hi,
First of all I would like to thank for this great project you brought tp public - it is really very helpful especially for beginners in DirectX 11 to understand it.
Now coming to my problem : this actually something to consider to change in future versions as I have solved my problem. Originally Renderdoc could not hook to one of my D3D11 apps for CreateDeviceAndSwapChain function - I didn't get any error or warning but hooked function just never got called so Renderdoc did not initialize and I didn't get Renderdoc overlay in my app. What I did is : I used Minihook library (https://github.com/TsudaKageyu/minhook) just for hooking CreateDeviceAndSwapChain function and it worked like a charm - renderdoc initialized correctly. The rest of renderdoc hooking was unchanged. I was not able to identify why original hoking didn't work. Please consider changing or giving alternative for hooking method for CreateDeviceAndSwapChain function for future releases. My D3D11 app is in 64bit architecture.
Regards

**Comment by baldurk** [comment]
The hooking code is fairly well tuned and battle-tested at this point. There's a number of tradeoffs to different hooking methods and it's not something that I'd throw out the whole system for another untested one without a really good reason.

Besides, this sounds like just a bug somewhere that's possibly fixable, since that function is obviously often hooked and used without incident. Can you give more information about the repro case you were hitting? Is the executable you were running compressed with an executable compressor like upx or did it have any other unusual post-linking steps applied to it? Both of these can corrupt the IAT used for hooking.

**Comment by wczmich** [comment]
It is not compressed at my knowledge also I used minihook at the same time of process initialization so maybe the difference is in the way IAT and minihook are hooking - i'm not an expert in hooking. I can do some experiments but I would need some tips from you what to check if you want to go deeper into this problem.

**Comment by baldurk** [comment]
Are you able to share your repro case? that's the easiest way, because then I can investigate it and figure out where the hooking is breaking. If not then I can give you some guidance about where to dive in.

**Comment by moradin** [comment]
Generally the problem with IAT based hooking is that some application environments can decide to restore the IAT to make sure nobody is tempering with the application. Since this can happen at any point it's hard to work around it, it would require noticing that this happened and patching it again and even then it could miss an important call. Minhook is patching the function code by adding a call to a trampoline function. The problem here is that this doesn't work for functions that are only a few instructions. I use Minhook extensively and it's really reliable but it can be a major effort to move the hooking completely over. Any application that you are making should not be restoring the IAT while you are developing it so I don't think that RenderDoc is meant to support this (but maybe Baldur will say otherwise)

**Comment by baldurk** [comment]
I used to use a trampoline-based hooking mechanism but I did run into those cases where it would break. There are ways around it in theory but it becomes more and more complicated. I haven't tried minhook specifically, but that's why I'm wary of totally changing the hooking based on a function that otherwise works fine.

And yes indeed, obviously RenderDoc's hooking will not work if there's anti-tamper or copy-protection or any such thing running. As @moradin says I have no intention of trying to break any protections like that since RenderDoc is intended as a developer tool. If it works on a 3rd party program then that's great, but if it doesn't then you're on your own.

**Comment by wczmich** [comment]
Ok - i'm not going to force you to minihook in any way. I worked arround this problem just by implementing minihook just for this one function and it worked for me. I used Renderdoc on other projects and can confirm that it also worked with default IAT hooking method. What you can consider in your project is:
* not change anything and see if someone else gets same problem
* implement alternative way to hook only CreateDeviceAndSwapChain using Minihook

**Comment by baldurk** [comment]
I think you're maybe missing the point a little. The IAT hooking works fine on CreateDeviceAndSwapChain and indeed any function - to my understanding it is more portable than the trampoline method minihook uses, aside from the cases where there's deliberate attempts to foil hooking. As above those are not supported by RenderDoc since any genuine developer can easily turn them off. Whatever case you have run into that's solved by changing to minihook is much more likely to be specific to your repro case and CreateDeviceAndSwapChain just happens to be the only function that needs to be hooked there, rather than being specific to a function call.

If it's a case of exe modification/drm/anti-tamper etc then there's no point to changing the hooking method - or worse still implementing _two_ separate hooking methods with neither of them working all the time.

If it's a genuine bug then I'd like to fix it now rather than wait to see if someone else has a problem. There's no minimum bar for the number of times a bug is hit before I fix it, only whether or not I get a report I can act on. I want to fix every bug that I can even if it only affects one person.

But to fix the bug I will need some more information from you to determine what's going wrong, whether that be a repro case you can share, or extra debug logging, or deeper debugging of what's going on in the hooking, or something.

**Comment by wczmich** [comment]
I cant share my external application I'm using RenderDoc with but I can run some extra tests or collect extra info from logs myself and send you. Now I have the problem that renderdoc logs do not contain any valuable information related to this problem - it seams that IAT hook gets installed but never gets called - no errors or warnings in logs. Are there any extra logging levels to turn on to get some more info ? Debug mode is on as I'm working on debug version. Do you have any other idea what else could be checked ?

**Comment by baldurk** [comment]
I just pushed a commit with extra verbose debug logging. Change the `#define VERBOSE_DEBUG_HOOK OPTION_OFF` to be `OPTION_ON` inside `win32_hook.cpp`, and then run your program to see what the output is.

The resulting logfile will be many megabytes so you'll need to zip it before upload (it should compress very well).

**Comment by wczmich** [comment]
I managed to find out hat exe was upx packed. If you confirm that it is not supported by RenderDoc then we are clear about this issue.

**Comment by baldurk** [comment]
Yes as I mentioned [in the first comment](https://github.com/baldurk/renderdoc/issues/425#issuecomment-261059263), upx is explicitly not supported.

It removes information from the IAT that's needed to hook any imports properly. It might in theory be fixable but it's much easier to fix on the application side - just don't run upx on your executable if you want to capture with RenderDoc - so in practice it's not a problem.
