### ISSUE TITLE
Capture to launch and got payload size 0

### ISSUE THREAD

**Issue by LemonAniLabs** [baldurk/renderdoc#444]
Hi,

I try to run the old commit "eb3e74db38c29c2c7d74745ff7c85383d310f389"
and I got a error when I capture to GTAV.
![image](https://cloud.githubusercontent.com/assets/6212976/21049782/c3794684-be51-11e6-807c-7cee2f3e4fee.png)

And I found that because payload size is 0 in socket_helpers.h line 67
`*ser = new Serialiser(payload.size(), &payload[0], false);`

Any idea of payload size 0?

Thanks

**Comment by baldurk** [comment]
That commit is from almost a year ago, lots of things have changed since then and many bugs. On top of that there was a specific bug relating to network connections to GTA V that was just fixed recently and is in v0.32, so anything before then could easily break in unexpected ways.

I'm not sure why you're running such old code, but I'm not really going to go chasing down bugs unless they're happening something fairly recent.
