### ISSUE TITLE
Profiling support for research purposes

### ISSUE THREAD

**Issue by victor-moya** [baldurk/renderdoc#450]
I'm interested on modifying renderdoc to be used for research in 3D rendering adding support for profiling and generating traces that can be used on research models.

First stage will be to improve the existing capability for capturing the information from GPU counters (D3D11, D3D12, OGL and perhaps later IHV custom counters).

The second stage will be generating text trace files with pipeline state changes from the renderdoc replay driver (renderdoc.dll).  I'm currently using Python scripts on renderdocui but I think it would be more portable adding new commands to renderdocmd.

Third stage will be to use the Stream Output, Pixel History and Pixel Debug mechanisms (instrumentation shaders with UAVs and Render Targets basically) to create instrumented traces of the GPU execution.

**Comment by baldurk** [comment]
Profiling has definitely been something a lot of people have wanted. The reason I haven't touched it until now is just because it can be quite a complex task to make a good profiling UI and I didn't want to split my focus between improving the debugger and writing a profiler. Providing the information just to script access or text output is one way of side-stepping that so I'd be quite happy with contributions from that perspective.

I think actually it would be better to either continue using python scripts, or to expose some limited profiling capability in renderdocui. A couple of reasons - one is that renderdocui will be going away some time in the near future to be replaced by qrenderdoc, and with Qt and C++ it's much easier to integrate python more completely into the program. There will be the chance of UI automation through python, and general querying and dumping of data is an ideal fit for python scripting. It should be very portable as the python scripts will run anywhere that renderdoc's UI does.

The other thing is that renderdoccmd kind of fits a specific niche. It is mostly intended as a utility for capturing and more 'meta' operations. I don't want to add complexity to it to have it use the replay UI extensively. Also together with the above - once I have C++ python integration then something we _could_ add would be a 'run python script' command, as that's very light impact on renderdoccmd.

**Comment by victor-moya** [comment]
That's fine with me.  I will then submit the changes for D3D11, D3D12 and OpenGL API counters as I implement them and you can apply them as you see fit.  Later we can discuss about how to expose the pixel history/debug mechanism and how to create text traces of the API and rendering state in a more useful way for my purposes, and see how I can contribute here.

**Comment by Trass3r** [comment]
> I'm interested in modifying renderdoc to be used for research in 3D rendering adding support for profiling

Are you talking about macro or micro profiling? By macro I mean the usual "which draw call took longest and why" while micro is actual shader profiling, i.e. why is shader x slow and which part of the code is slowest.

**Comment by victor-moya** [comment]
That was long ago ...

I was mostly interested in exposing the existing performance counters in
GPUs.  Nothing as ambitious as instrumenting shader code at instruction or
function or whatever level.  That may not be impossible

I added the support for D3D11, D3D12 and Vulkan standard counters which was
easy and the merge request was accepted.

I had some python scripts and a couple private modifications, that later
become redundant, to get all the information per drawcall

Then the project I was involved evolved away from that.

Why are you asking?

Thanks.

Victor

**Comment by baldurk** [comment]
This issue is not well defined in scope and profiling is deliberately not supported by RenderDoc so I'm closing this.
