### ISSUE TITLE
OpenGL error "No index buffer bound at indexed draw!"

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#452]
The application just activates a VAO that has an index buffer in it, so there are no `glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ..)` in the capture. It looks like RenderDoc does not properly replay VAOs with regards to the index buffers.

App to test:
```
git clone https://github.com/kvark/webrender wr
cd wr/sample
cargo run
```
The executable is built into `wr/target/debug/wr-sample`.

**Comment by baldurk** [comment]
Hey there doesn't seem to be an executable or batch file called cargo anywhere. There's `Cargo.toml` but it looks like just a configuration file of some kind. I guess cargo is a separate build program, can you point me to how to set that up?

**Comment by zao** [comment]
cargo is the package and build system for Rust. Grab and run rustup to install a tool chain, add sir to PATH, and run away. 
https://www.rustup.rs

**Comment by baldurk** [comment]
Is there any way to choose where to install that? When I run the installer it allows me to configure a couple of things like to not modify the system PATH etc, but doesn't let me choose the installation directory.

**Comment by kvark** [comment]
@baldurk my apologies! I didn't realize that you may not have Rust installed.
rustup [doesn't seem to allow](https://github.com/rust-lang-nursery/rustup.rs/blob/master/README.md#installation) an alternative install path at the moment. If that's a problem, we can suggest a different way of installing Rust, or I can even provide you with the executable.

**Comment by baldurk** [comment]
No it's not a big deal. If I could install it anywhere I'd be able to put it somewhere that I could just leave it in case I needed it for a future repro, but I can just remove it once I'm done.

**Comment by baldurk** [comment]
I got it running, but I don't get the error reported anywhere. I tried capturing normally, or queueing a very early capture (frame 2) just in case it only happens early, but there's no complaints anywhere and so far as I can see there's an index buffer bound on all the indexed draws.

Does it happen somewhere specific?

**Comment by kvark** [comment]
@baldurk thanks for giving it a go!
Perhaps, I was using an old RenderDoc version on that machine. I'll try the nightly and report back, attaching the executable to test.

**Comment by kvark** [comment]
I tried the latest nightly, and here is what I got.

Starting RenderDoc, capturing wr-sample, hitting F12, capture is saved (in the temporary folder), exiting - RenderDoc disappears, I assume it's a crash. The capture is not saved into a permanent location. Attaching the temporary location captures here:

[wr-sample-captures.zip](https://github.com/baldurk/renderdoc/files/672035/wr-sample-captures.zip)

Starting RenderDoc again, loading one of those temporary captures, navigating to `Errors and Warnings`, getting 5 subject errors in there. Attaching the executable for your reference:

[wr-sample-exe.zip](https://github.com/baldurk/renderdoc/files/672036/wr-sample-exe.zip)

**Comment by baldurk** [comment]
Hmm, what hardware/driver are you running on? I'm on `NVIDIA Corporation / GeForce GTX 1080/PCIe/SSE2 / 4.3.0 NVIDIA 375.70` at the moment. Windows 7, if it matters. I don't know if your code does anything different based on the vendor, or if it's likely to bump up against any different limits. Usually GL captures are pretty portable.

When I open either of your captures, I get an internal crash inside the nvidia driver trying to create one of the shaders as a separable program, and the exe seems to behave just the same as the one I built locally - no matter where I capture it opens successfully with no crashes and doesn't complain about any errors.

I haven't unpacked my machines with AMD or Intel yet, I'll probably do that tomorrow. I'll try to repro there.

**Comment by kvark** [comment]
@baldurk I'm testing on
HW: Radeon RX480
ID: PCI\VEN_1002&DEV_67DF&SUBSYS_E347174B&REV_C7
Driver: 21.19.137.1
OS: Windows 7

**Comment by zao** [comment]
I cannot make the executable in the thread misbehave on GTX1080 and RX470 (Win10).

RenderDoc log says:

    Vendor checks for 45 (ATI Technologies Inc. / Radeon (TM) RX 470 Graphics / 4.5.13464 Compatibility Profile Context 21.19.384.0)

which seems a bit fishy as normally RenderDoc doesn't want to touch compatibility contexts with a ten foot pole.

Your application built from scratch reports:
OpenGL version 3.2.13464 Core Profile/Debug Context 21.19.384.0
OpenGL version 3.2.0 NVIDIA 376.19.
so it might just be a RenderDoc quirk.

Building from top of master (482b59be6e) myself, you've got cs_box_shadow failing to compile at all on the RX470 in a freestanding run, so not sure if your shaders are all that solid.

**Comment by baldurk** [comment]
The problem is OpenGL is just kind of a mess, particularly with the contexts. RenderDoc does allow compatibility contexts only if they're created via `CreateContextAttribs`, because it's so rare to find a program that uses modern GL _and_ creates a core profile explicitly.

Many programs use modern GL, but still just create a compatibility context anyway. If I blocked all programs from capturing except core contexts, that would eliminate a ton of programs that would otherwise work. Of course the downside is they might use functionality that isn't supported, but that's the tradeoff I decided to make.

**Comment by baldurk** [comment]
I think I found the root cause of this, testing on my AMD machine. It's some really weird behaviour, and I can't tell if it's actually invalid or if the expected GL behaviour is bizarre.

Either way, hopefully with that commit it should work correctly now. Can you test on the next nightly build (or compile yourself) to see how you get on now?

**Comment by kvark** [comment]
@baldurk that's awesome, thank you! I'll get back once I test the next nightly.

**Comment by nicebyte** [comment]
Hey Baldur,

I'm seeing the exact same issue on my side here.

RenderDoc version is 0.91
I'm running Windows 10
GPU is Nvidia GeForce GTX 970M
I'm creating a GL 4.3 core profile context

I'm clearly seeing a triangle being drawn in the texture viewer, yet this error message appears, and "mesh output" tab acts as if no index buffer is bound at all.

This doesn't happen consistently, and I'm not quite sure yet what exactly affects this.

Can you please look into it again?

**Comment by baldurk** [comment]
Someone else reported seeing this message on their project also using nvidia, and it turned out to be an nvidia driver bug. I narrowed it down to something 'impossible' where using `glGetVertexArrayInteger` I could verify that a given VAO has an index buffer, but after calling `glBindVertexArray` with that VAO then `glGet(GL_ELEMENT_ARRAY_BUFFER_BINDING)` (which is used to generate this message) would still return 0. It wouldn't happen all the time so it seemed like possibly some race condition inside the driver updating state.

I can't say for sure if this is the problem you're running into without repro details like a capture or the program, but my guess is you're running into the same bug.

**Comment by nicebyte** [comment]
Ah, I see. My drivers might not be quite up to date. Let me download a fresh version and see if the issue persists.

**Comment by nicebyte** [comment]
After updating the drivers, the issue still persists.
I tried switching both the test app and RenderDoc to use the integrated Intel GPU. It made the error go away. So, I'm pretty sure it's the driver bug you mentioned, and it hasn't been fixed yet.

In case yoou need it, here's the log: https://we.tl/KzU6Zl3vtT hope it helps

**Comment by ssylvan** [comment]
FWIW I also hit a variant of this. @baldurk  pointed me to setting eGL_DEBUG_OUTPUT_SYNCHRONOUS to true in gl_driver.cpp which made my particular issue go away. Seems like a race condition in the NV driver. So if anyone else sees this issue, this could be a workaround until the NV driver is fixed.

**Comment by kvark** [comment]
@baldurk I'm getting this again with 382639fb3f789bb489691c8b497d112d7e1e7415 on Linux/Intel, when capturing Firefox with WebRender enabled (`gfx.webrender.all = true` in Nightly preferences). Can we enable the previously submitted hack/workaround on Intel (and possibly NV)?

**Comment by kvark** [comment]
Updated to f46aa2944d9467fd6c29686382b2304169a524a8 and no longer seeing the issue.

**Comment by FredGithub** [comment]
Seeing the same issue with RenderDoc v1.4 (214d8522), and NVIDIA drivers up-to-date. I'm running:
NVIDIA Corporation / GeForce GTX 1060 6GB/PCIe/SSE2 / 4.6.0 NVIDIA 430.86

However, the issue only happens when debugging from Visual Studio. If I use Launch Application from RenderDoc, it works fine. Not sure that makes any sense, but at least I have a workaround now!

**Comment by baldurk** [comment]
Please don't comment on old and fixed issues. This was a driver bug, and a workaround is in place on recent builds of RenderDoc. If you're seeing the error it may be a different driver bug or you may have a bug in your application - running from Visual Studio will run with the debug heap which may e.g. initialise memory to 0xCCCCCCCC instead of 0.

If you think there is a RenderDoc bug please open a new issue with as much information as you can and importantly repro steps for me to investigate with.
