### ISSUE TITLE
FetchCounters failure in D3D12

### ISSUE THREAD

**Issue by victor-moya** [baldurk/renderdoc#457]
When clicking on 'Time durations' in the Event Browser renderdoccui crashes.

I was able to solve the first crash on D3D12Replay::FetchCounters but I'm stuck with the second crash.

The first crash happens because SetStablePowerState() is only supported on developer mode drivers (which I didn't have enabled) and forces subsequent DXGI_ERROR_DEVICE_REMOVED errors.  Code could be added when creating the D3D12 device to determine if developer mode is enabled, for example just check if SetStablePowerState() works or not, and then only use SetStablePowerState() if developer mode is available.  Got through it by commenting the calls in D3D12Replay::FetchCounters() for now.

The second crash is related with drawcall callbacks being enabled in the replay.  That implies that on  WrappedID3D12GraphicsCommandList::Serialise_Reset() CreateCommandList() is called on RESET_LIST chunks.  In the linked log there are two RESET_LIST commands without a CLOSE_LIST command in between (bakeID 57753 and CommandList 172 followed by bakeID  57754 and CommandList 157).  The second fails on CreateCommandList() because the same allocator instance is used for both.  I couldn't decipher yet how the whole mechanism works so a little help would be useful to solve this :).

[UE4 Infiltrator D3D12 capture](https://drive.google.com/open?id=0By78D8seJF_SUW5laU01bXdTMTg)

**Comment by baldurk** [comment]
Right, I ran into that SetStablePowerState() thing too on another computer. It's incredibly stupid and I've no idea how you're supposed to test for it - I think once you've hit the device removed error then it's too late and you have to recreate the device from scratch which isn't feasible. It's probably better to just assume that developer mode will be enabled and signal a fatal error to the user if that error is returned. Perhaps suggesting they should use a less terrible API :wink:.

As to the second crash, I'll need to check into this. From what I remember, when re-timing the lists should use the original allocator from the capture (usually when partially recording a single command list, we use our own internal allocator to keep things simpler). Since we use the original allocators, the original capture should not have had any overlap so the replay shouldn't either.

**Comment by victor-moya** [comment]
My idea on SetStablePowerState() was to create a dummy device when starting up the application, call SetStablePowerState() and let it crash before creating the real device, and then set a variable somewhere to tell the application and real device if the call can be used or not.  Perhaps setting a configuration file/registry entry after a crash could also work ...

I tested the D3D12 counters with a capture from a simple 'HelloWorld' application and they seem to work, however when trying with a capture from Intel's Asteroids demo it crashed in a similar way.

**Comment by baldurk** [comment]
That could work, if you create the dummy device in `D3D12_CreateReplayDevice` in [d3d12_replay.cpp](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/d3d12/d3d12_replay.cpp) then you could return `eReplayCreate_APIHardwareUnsupported` if the SetStablePowerState() fails and that would gracefully propagate up to the UI to display. If you then printed a log message people would be able to see what's wrong.

I'm not sure I'm that keen on having a variable silently flip somewhere in the background. That would be hard to convey to the user when everything otherwise seems to work - except that maybe the results would be off/unreliable. That's often the case already but at least this is something concrete that can be done.

**Comment by victor-moya** [comment]
Another option I thought would be to expose a 'SetDeviceMode' interface on the replay driver, on by default, then it could be used from Python to disable the call to SetStablePowerState before calling FetchCounters.

**Comment by victor-moya** [comment]
On the D3D12 error on WrappedID3D12GraphicsCommandList::Serialise_Reset() I have this other, shorter, log from Intel's [Asteroids Demo](https://drive.google.com/open?id=0By78D8seJF_SWmhkdGVJNUNCMlE) that seems to show the same signature.  I didn't dig too much into it though.

**Comment by baldurk** [comment]
Right, I had it backwards - how I thought it should work was right, I just didn't actually have it set up that way :).

**Comment by baldurk** [comment]
The fix for this was included in v0.33. If it's still happening then comment here or let me know directly.
