### ISSUE TITLE
Vulkan Capture Error

### ISSUE THREAD

**Issue by greenmachine757** [baldurk/renderdoc#461]
When I capture a frame the picture appears in the RenderDoc UI like this: http://imgur.com/HPS2Pfh

But when I close down the application so I can look at the information in RenderDoc, I get the following error and the frame data disappears: http://imgur.com/7vEQqMF

The error log reads the following:
RDOC 005516: [10:58:09]             core.cpp( 308) - Log     - RenderDoc v0.32 x64 (6a5ba7e6359e7b928fc460070a3bd5abff4d2c8e-official) loaded in replay application
RDOC 001132: [10:58:09]             core.cpp( 308) - Log     - RenderDoc v0.32 x64 (6a5ba7e6359e7b928fc460070a3bd5abff4d2c8e-official) loaded in replay application
RDOC 005516: [10:58:20]    win32_process.cpp( 457) - Log     - Running process C:\Users\Austin\Desktop\creators.exe
RDOC 005516: [10:58:20]    win32_process.cpp( 521) - Log     - Injecting renderdoc into process 2996
RDOC 005516: [10:58:22]   target_control.cpp( 406) - Log     - Got remote handshake: creators () [2996]
RDOC 005516: [10:58:23]   target_control.cpp( 619) - Log     - Used API: Vulkan
RDOC 005516: [10:58:24]   target_control.cpp( 606) - Log     - Got a new capture: 0 (time 1482335904) 25062 byte thumbnail
RDOC 005516: [10:58:26]    win32_network.cpp( 178) - Warning - recv: 10054
RDOC 005516: [10:58:26]  replay_renderer.cpp(1526) - Log     - Creating replay device for C:\Users\Austin\AppData\Local\Temp\RenderDoc\creators_2016.12.21_10.58.20_frame27.rdc
RDOC 005516: [10:58:26]        vk_replay.cpp(5592) - Error   - Failed to load vulkan library
RDOC 005516: [10:58:26]  replay_renderer.cpp(1549) - Error   - Couldn't create a replay device :(.

**Comment by baldurk** [comment]
Hi, that last error `Failed to load vulkan library` indicates that RenderDoc is failing a call to load the `vulkan-1.dll` library.

Normally if you have vulkan drivers, then vulkan-1.dll is in the system path, as part of the vulkan runtime that drivers install. Same idea as d3d11.dll or opengl32.dll which ship with the D3D runtime or the system.

Do you have vulkan-1.dll in your C:\windows\system32 directory? What dll is being used when you run the program?

**Comment by greenmachine757** [comment]
http://imgur.com/a/kGkaX It appears to be in my system32.  Do I need to be adding the path somewhere in RenderDoc explicity?  Are you asking me what vulkan-1.dll is being used when I run my program by itself?  I compile with the static vulkan-1.lib and not any vulkan-1.dll as far as I'm aware of.  I am very new to vulkan and renderdoc though and I'm sure I've made a silly mistake somewhere.

**Comment by baldurk** [comment]
Well I don't want to be contrarian but that screenshot shows that you *don't* have it in system32. You have a couple of versioned dlls - vulkan-1-1-0-30-0.dll and vulkan-1-1-0-11-1.dll, but you don't have the actual canonical name vulkan-1.dll.

The vulkan runtime installer is supposed to install a new versioned dll, and then update vulkan-1.dll to be a copy of the latest version. Something has gone wrong for you I guess and vulkan-1.dll has gone missing. I'm not sure where to file a bug for the vulkan runtime, you could try on [the loader repository](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers) as that's what the dll is.

The vulkan-1.lib you are linking against probably isn't a static library, it's an import library to link against the dll. I don't think the SDK ships a static version of the loader as it's generally not a good idea. So you might still have a vulkan-1.dll somewere that you're using at runtime. You can check the modules list in visual studio when you're running to see.

Either way though vulkan programs will expect a vulkan-1.dll in your system path so whatever has gone wrong to remove it is the real problem here. I'd check with LunarG to see what they say.

**Comment by greenmachine757** [comment]
That was the issue! I moved the 64 bit version of vulkan-1.dll into system32 and everything seems to be working, no errors!
