### ISSUE TITLE
RenderDoc does not work

### ISSUE THREAD

**Issue by SALTAIR** [baldurk/renderdoc#464]
I am trying to run DOOM through RenderDoc, through Vulcan and using Steam RIP. But it is not working.

**Comment by baldurk** [comment]
Well, a couple of things - this _can_ work because I and others have gotten it to work, so you must be doing something wrong during setup. My guess is that you're running the doom exe directly, but it's closing itself and instead launched through steam indirectly as most steam games do. The global process hook might help with this.

But as a general policy, I don't support capturing 3rd party programs as it is a bit of a grey area. Since renderdoc is intended as a developer tool for debugging I don't want to get any game developer pissed by explicitly supporting a tool for reverse engineering. So while it can work sometimes, I don't go out of my way to bypass any copy/cheat protections and I don't provide support for capturing unless it's a legitimate bug that might affect other programs - so you're on your own with that one.
