### ISSUE TITLE
F12 doesn't work for capturing frames in GIGABYTE gaming laptop

### ISSUE THREAD

**Issue by monajalal** [baldurk/renderdoc#465]
I am following this tutorial which say press F12 for capturing frames.  I pressed it both when playing GTA5 as well as when on the renderdocui.exe GUI. Nothing happens. Are there alternative for starting the capture process?
https://bitbucket.org/visinf/projects-2016-playing-for-data

**Comment by baldurk** [comment]
F12 should work fine and it definitely doesn't depend on the brand of hardware you're using.

You should use F12 or print screen (the default keys) with the program you are capturing in focus. It will only work though if RenderDoc is successfully injected - do you have the in-application overlay visible when you're doing this? What exactly do you mean by 'nothing happens' - does the overlay show 0 captures still? does a capture get made but it doesn't become visible in the connection in the UI? Do you get any noticeable pause when triggering a capture? You can also try triggering a capture from the connection window in the UI rather than pressing F12.

Also since you're linking that same repository - again please make sure you are testing with the latest code from **this** repository. If that doesn't work, then we can investigate, but if you're running from that fork then you will have to report bugs to them as the code is very out of date and any number of bugs could have already been fixed. It also looks like they've also made changes to how capturing works, so it could be a bug they've added.

**Comment by monajalal** [comment]
I also get these errors:
```
RENDERDOC:  [13:07:59]             core.cpp( 242) - Log     - RenderDoc v0.27 x86 (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application
RENDERDOC:  [13:10:13]    win32_process.cpp( 307) - Log     - Injecting renderdoc into process 11916
RENDERDOC:  [13:10:13]    win32_process.cpp( 339) - Error   - Can't capture x64 process with x86 renderdoc
RENDERDOC:  [13:18:16]    win32_process.cpp( 307) - Log     - Injecting renderdoc into process 8328
RENDERDOC:  [13:18:16]    win32_process.cpp( 339) - Error   - Can't capture x64 process with x86 renderdoc
RENDERDOC:  [13:20:49]    win32_process.cpp( 307) - Log     - Injecting renderdoc into process 2060
RENDERDOC:  [13:20:49]    win32_process.cpp( 339) - Error   - Can't capture x64 process with x86 renderdoc
RENDERDOC:  [13:23:29]    win32_process.cpp( 307) - Log     - Injecting renderdoc into process 3584
RENDERDOC:  [13:23:29]    win32_process.cpp( 339) - Error   - Can't capture x64 process with x86 renderdoc
```

**Comment by baldurk** [comment]
That's definitely the real problem. You're trying to capture a 64-bit program but you've built the 32-bit binaries. If you build the x64 version of RenderDoc then it will capture normally.

If you need to capture _both_ types of executable, then build both targets and put `renderdoc.dll` and `renderdoccmd.exe` in an `x86/` subfolder under the 64-bit build.
