### ISSUE TITLE
Crash when running Vulkan app with render doc attached

### ISSUE THREAD

**Issue by BearishSun** [baldurk/renderdoc#471]
Hi! Love RenderDoc, but I'm having an issue with my Vulkan application crashing when I run it under RenderDoc. 

Normally the application runs fine, but when I run it from RenderDoc it seems to render one frame, freeze for a second and then just silently shut down.

I ran RenderDoc in debug mode and tracked the issue down to a GetRecord() call for a VkBuffer, which appears to return an invalid value, which causes an access violation. Exact error text:
> Exception thrown: read access violation. this was 0xFFFFFFFFFFFFFFFF.

I have also included a screenshot of my debugging session, showing the callstack and exact line of the problem. I can provide more information if needed.

![renderdoccrash](https://cloud.githubusercontent.com/assets/6533403/21541452/c9a3f936-cdb6-11e6-93d3-e66961fe43e6.png)

I've experienced the crash happen in a couple of different places so far, and every time it was caused by a call to vkUpdateDescriptorSets. 

It smells like memory corruption, but I don't think my application can corrupt another process' memory, so I don't think its on my end (nor have I experienced any similar crashes without RenderDoc).

You can test this yourself by compiling Banshee 3D (which is what I'm debugging):
https://github.com/BearishSun/BansheeEngine/tree/5a1370c0107ad6afadce8665f80c0528946a21a0

If you try to run *ExampleProject* the error should happen.

EDIT: I should also note that sometimes I have solved the error just by moving some code around (e.g. creating a buffer much sooner before it was referenced in a write to the descriptor set).

I can also disable certain code calling vkUpdateDescriptorSets and my app can run fine under render doc. Note that other code still calls vkUpdateDescriptorSets and it works - so it's not every call to vkUpdateDescriptorSets that fails.

**Comment by BearishSun** [comment]
This revision might be more appropriate to reproduce the issue: https://github.com/BearishSun/BansheeEngine/tree/aa3da03dd4ab91efa23c3774312d953ad96b4e07

Previous one had a small issue with the build process.

**Comment by baldurk** [comment]
Hey, I've tried to reproduce this but so far I haven't had any crashes. I've been running from that commit aa3da03, and just using the latest code on the main branch.

I've run on my nvidia/win7 machine, as well as on amd/win10 (I had to make a few fixes/tweaks to get it to run on amd - you unconditionally create a D24S8 depth buffer which isn't supported, I'd suggest just changing that to D32S8 since it's basically free. There's also an issue with some queries that I think might be because they're invalidly started outside a renderpass and ended inside it).

I've not had any crashes though, near vkUpdateDescriptorSets or otherwise. Are there any workarounds I need to undo, or specific things I need to do while running the program? I just let it run, move the camera a bit, so I don't know if I need to trigger it somehow.

The callstack in your pasted screenshot doesn't seem to match up with the code I have. It goes from `VulkanRenderAPI::setGpuParams` to `VulkanCmdBuffer::setGpuParams` to `VulkanGpuParams::prepareForBind`, but the latter call doesn't exist in the code I have:

```cpp
	void VulkanCmdBuffer::setGpuParams(const SPtr<GpuParamsCore>& gpuParams)
	{
		// Note: We keep an internal reference to GPU params even though we shouldn't keep a reference to a core thread
		// object. But it should be fine since we expect the resource to be externally synchronized so it should never
		// be allowed to go out of scope on a non-core thread anyway.

		mBoundParams = std::static_pointer_cast<VulkanGpuParams>(gpuParams);
		
		if (mBoundParams != nullptr)
			mBoundParamsDirty = true;
		else
		{
			mNumBoundDescriptorSets = 0;
			mBoundParamsDirty = false;
		}

		mDescriptorSetsBindState = DescriptorSetBindFlag::Graphics | DescriptorSetBindFlag::Compute;
	}
```

That seemed to have changed recently, but I tried going back a few revisions with no change.

Also FYI - your current glslang compilation step is producing invalid SPIR-V. You pass `EShMsgDefault` to the `shader->parse`, but to get vulkan-compliant SPIR-V you need to pass `EShMsgSpvRules|EShMsgVulkanRules`. Otherwise you're missing some required decorations and things.

**Comment by BearishSun** [comment]
I just re-tested both the revisions I posted, and I cannot reproduce it on either anymore. The only major change I can think of doing since the last time I tested, is installing the 1.37 Vulkan SDK and updating my GPU drivers.

But the error is not gone, it's just hidden and can't be reproduced in ExampleProject anymore. It can however be reproduced by running the (more complex) BansheeEditorExec project. I have done it using the most-recent available revision: https://github.com/BearishSun/BansheeEngine/tree/f03dcda9f79a3b3147c3924b921e227a2f1fc9f5

Here's the callstack of the error using that specific revision:
![renderdoccrash2](https://cloud.githubusercontent.com/assets/6533403/21595496/c452344a-d12e-11e6-880b-a9bc671300e2.png)

To reproduce, checkout the commit above, compile BansheeEditorExec project under Debug & x64 configuration. Then run the editor under RenderDoc. When it opens it won't crash immediately, and you'll need to load a project first. I've provided the exact one I'm using:

http://bearishsun.thalassa.feralhosting.com/BansheeProject.zip

Once the editor starts, hit Browse on the central window and then select "BansheeProject" folder you extracted from the archive above. As soon as the project opens it should crash. The problem is reproducible in 100% of the cases on my end. You do not need to do anything like moving the camera or waiting, it happens as soon as the project loads.

If I have some free time soon I'll explore it a bit more to find out what's the difference between ExampleProject and BansheeEditorExec that's causing it to crash.

And thanks for the tips regarding SPIR-V and D24S8 - I find it really surprising the depth format isn't supported, thought it was pretty standard.

**Comment by baldurk** [comment]
OK I think I've fixed this now - the editor loads fine for me and I can play around so it doesn't seem like there are other problems lurking. The issue was that since I don't have back-links to be able to clear out descriptor sets when objects are deleted, I rely on objects being 'valid enough' with empty IDs after deletion that I can safely try and dereference them. I wasn't handling that properly and it lead to the crash.

Yes D24S8 is a fairy tale that graphics programmers have passed down through the years but hasn't been real for a long time. Almost everyone now just allocates a D32S8 texture and tries to emulate 24-bit accuracy, so you are basically just shooting yourself in the foot. Nvidia may or may not still have special-casing for it, but as usual they aren't telling.

It's better just to stick with either 16-bit or 32-bit depth, depending on what you actually need. And of course - if you don't need stencil, then just use D32.

**Comment by BearishSun** [comment]
Confirmed resolved!
