### ISSUE TITLE
VK_LAYER_LUNARG_monitor causes RenderDoc to hang with high CPU usage when using the texture viewer

### ISSUE THREAD

**Issue by Ashalah** [baldurk/renderdoc#490]
Running on Windows 10 x64 with an AMD HD7770.
Disabling this layer solves the problem on both v0.32 and the nightly RenderDoc_2017_01_14_6e2fc42c_64.
Symptoms are that RenderDoc becomes unresponsive, and one CPU core becomes maxed out.

**Comment by baldurk** [comment]
Thanks for the report. I've added that layer to the list of layers to strip out when replaying which should fix the problem.

The hang is because the layer is buggy - it calls `SetWindowText` inside `vkQueuePresentKHR`, but there's no guarantee that present is being called from the UI thread. On windows, this causes the call to block until the UI thread has processed a message - and in my case the UI thread was spinning waiting for the thread that made the present call to finish presenting.

You might want to report this as a bug to LunarG, although I'm not sure why they're changing the window title instead of rendering an FPS overlay. As it is the framerate won't even show up in e.g. any fullscreen or borderless window without a title bar.

**Comment by Ashalah** [comment]
Thanks for the heads-up! I am actually presenting from another thread, and this would have eventually led to some headache for me.

In my opinion this is the correct solution, and you could close this issue.

**Comment by baldurk** [comment]
OK I'll close it down, as it works in my tests and I agree that this should be the simple obvious solution. But just in case it's still broken for some reason just comment here and I can re-open & re-investigate.

**Comment by Ashalah** [comment]
Works with the nightly build RenderDoc_2017_01_18_92c69761_64
