### ISSUE TITLE
%TEMP% as a network folder breaks path processing

### ISSUE THREAD

**Issue by CodedByATool** [baldurk/renderdoc#506]
RenderDoc v0.32 - I'm hitting an issue when I use Attach to Running Instance to capture.
It seems to generate a temporary path made by concatenating the path to the executable of the process and my (Windows 10, x64) home drive path (which is a UNC network location). The result is it cannot process the capture.

`F:\xxx\xx_xx\xxx\xxxxx\xxx\xxxxxx\Win64-Dll\release\UNC\xxx-xxxx.xx.xx.xx.com\home\xxxxxxl\My Documents\xxxxxxxxxxxxx.xx_xx.Win32\Screenshots\_frame1357.rdc`

Using Capture Executable I do not have this issue.

Cheers.

Log...

`RDOC 017144: [13:57:54]             core.cpp( 308) - Log     - RenderDoc v0.32 x64 (6a5ba7e6359e7b928fc460070a3bd5abff4d2c8e-official) loaded in replay application
RDOC 020452: [13:57:54]             core.cpp( 308) - Log     - RenderDoc v0.32 x64 (6a5ba7e6359e7b928fc460070a3bd5abff4d2c8e-official) loaded in replay application
RDOC 017144: [13:58:06]   target_control.cpp( 406) - Log     - Got remote handshake: xxxxxx.Main_Win64_release_Dll (D3D11) [13812]
RDOC 017144: [13:58:10]   target_control.cpp( 406) - Log     - Got remote handshake: xxxxxx.Main_Win64_release_Dll (D3D11) [13812]
RDOC 017144: [13:58:26]   target_control.cpp( 406) - Log     - Got remote handshake: xxxxxx.Main_Win64_release_Dll (D3D11) [13812]
RDOC 017144: [13:58:26]   target_control.cpp( 606) - Log     - Got a new capture: 0 (time 1486158823) 0 byte thumbnail
RDOC 017144: [13:58:26]   target_control.cpp( 606) - Log     - Got a new capture: 1 (time 1486158843) 0 byte thumbnail
RDOC 017144: [13:58:26]   target_control.cpp( 606) - Log     - Got a new capture: 2 (time 1486158987) 0 byte thumbnail
RDOC 017144: [13:58:41]    win32_network.cpp( 178) - Warning - recv: 10054
RDOC 017144: [13:59:48]   target_control.cpp( 406) - Log     - Got remote handshake: xxxxxx.Main_Win64_release_Dll (D3D11) [18460]
RDOC 017144: [13:59:50]   target_control.cpp( 406) - Log     - Got remote handshake: xxxxxx.Main_Win64_release_Dll (D3D11) [18460]
RDOC 017144: [13:59:54]   target_control.cpp( 606) - Log     - Got a new capture: 0 (time 1486159194) 0 byte thumbnail
RDOC 017144: [13:59:57]       serialiser.cpp( 659) - Error   - Can't open capture file 'F:\xxx\xx_xx\xxx\xxxxx\xxx\xxxxxx\Win64-Dll\release\UNC\xxx-xxxx.xx.xx.xx.com\home\xxxxxxl\My Documents\xxxxxxxxxxxxx.xx_xx.Win32\Screenshots\_frame1357.rdc' for read - errno 2
RDOC 017144: [13:59:57]             core.cpp( 780) - Error   - Couldn't open 'F:\xxx\xx_xx\xxx\xxxxx\xxx\xxxxxx\Win64-Dll\release\UNC\xxx-xxxx.xx.xx.xx.com\home\xxxxxxl\My Documents\xxxxxxxxxxxxx.xx_xx.Win32\Screenshots\_frame1357.rdc'
RDOC 017144: [13:59:57]  replay_renderer.cpp(1526) - Log     - Creating replay device for F:\xxx\xx_xx\xxx\xxxxx\xxx\xxxxxx\Win64-Dll\release\UNC\xxx-xxxx.xx.xx.xx.com\home\xxxxxxl\My Documents\xxxxxxxxxxxxx.xx_xx.Win32\Screenshots\_frame1357.rdc
RDOC 017144: [13:59:57]       serialiser.cpp( 659) - Error   - Can't open capture file 'F:\xxx\xx_xx\xxx\xxxxx\xxx\xxxxxx\Win64-Dll\release\UNC\xxx-xxxx.xx.xx.xx.com\home\xxxxxxl\My Documents\xxxxxxxxxxxxx.xx_xx.Win32\Screenshots\_frame1357.rdc' for read - errno 2
RDOC 017144: [13:59:57]             core.cpp( 780) - Error   - Couldn't open 'F:\xxx\xx_xx\xxx\xxxxx\xxx\xxxxxx\Win64-Dll\release\UNC\xxx-xxxx.xx.xx.xx.com\home\xxxxxxl\My Documents\xxxxxxxxxxxxx.xx_xx.Win32\Screenshots\_frame1357.rdc'
RDOC 017144: [13:59:57]  replay_renderer.cpp(1536) - Error   - Couldn't get device type from log
`

**Comment by baldurk** [comment]
Right, it looks like the network path for `%TEMP%` is being interpreted as relative, rather than absolute. I think what you're running into is when the UI doesn't set the capture path itself (which it seems to get right), but instead when the capture dll decides its own path, which comes from `GetTempPathW` I think.

I might need to figure out how to create an account with a network path as its home directory. Or maybe if I override `%TEMP%` then it'll do the trick.

**Comment by baldurk** [comment]
I tried to reproduce this by setting `TEMP` and `TMP` to point to a UNC path just to a share on my local machine. I tried both variants, `\\max\t\tmp\` and `\\?\UNC\max\t\tmp` but both of them worked fine, whether it was from the UI, or launched from renderdoccmd, or even launching the exe along to then self-inject by loading renderdoc.dll.

Looking at the capture again I find something a bit suspicious - looking at the path it's trying to read from:

`F:\xxx\xx_xx\xxx\xxxxx\xxx\xxxxxx\Win64-Dll\release\UNC\xxx-xxxx.xx.xx.xx.com\home\xxxxxxl\My Documents\xxxxxxxxxxxxx.xx_xx.Win32\Screenshots\_frame1357.rdc`

Aside from the rest of the path, I see that the end is `Screenshots\_frame1357.rdc`, which should never normally happen. The captures will always be saved using the exe name (which you can see it found successfully earlier in the log), like `xxxxxx.Main_Win64_release_Dll__frame1357.rdc`.

So now I wonder - are you using the in-application API to call [`SetLogFilePathTemplate`](https://renderdoc.org/docs/in_application_api.html#_CPPv222SetLogFilePathTemplatePKc)? If you called this with only a path ending in `Screenshots\` instead of `Screenshots\myfile` this would explain the missing filename.

I tried passing both types of UNC path to the API and it worked OK in my tests, so I wonder if perhaps you're passing the wrong path to that function - if you passed a path starting `UNC\xxx-xxxx.xx.xx.xx.com\home` then you'd get this behaviour, as it would be interpreted as a relative path and it would not create the directories needed to write to that location - so it'd fail to write in on capture, and the replay UI would fail to load as we see.

Hopefully that makes sense, I think there's something missing as I can't repro as-is. If you could share (censored as well) the output log from the program being captured that might also help.

**Comment by CodedByATool** [comment]
You are absolutely correct, the problem is in our call to SetLogFilePathTemplate. Thanks for the suggestion and sorry I didn't report back sooner.
