### ISSUE TITLE
OpenGL debug labels not getting displayed.

### ISSUE THREAD

**Issue by cgrant78** [baldurk/renderdoc#509]
When running my application and setting object labels using  glObjectLabel, the object labels do not displayed in the respective pipeline state view. Is there something I"m missing to get this to work?

**Comment by baldurk** [comment]
Which object types are you naming? The objects that should get names picked up for them are renderbuffers, textures, buffers, program pipelines, programs, and shaders.

Testing just now on a sample, it seems like nvidia's driver is barfing when trying to name buffer objects, even though everything looks valid to me. I'll need to check on AMD but I think it's just wrong. It worked fine for me on a texture and programs/shaders/etc.

On replay I can store object names in my own data structures rather than storing them in the driver, which also means you don't need KHR_debug on replay.

**Comment by cgrant78** [comment]
I'm naming: vertex, index, render buffers, frame buffer objects and textures.
Was the Nvidia driver complaining when you try to label an object prior to binding? If so, the AMD driver will do the same thing on Core Contex.

**Comment by baldurk** [comment]
Looks like that's the case - I was using a sample program that added labels, and it was indeed calling glObjectLabel right after glGenBuffers.

It would still be nice to make it work even in spite of that, since I can just apply the names myself. But if that isn't the problem you're running into then it seems like everything works for me. Apart from FBOs that aren't displayed directly in the UI, so there'd be no place to name them anyway.

Can you provide any repro details? Either the program or a frame capture?

**Comment by cgrant78** [comment]
The program has too many dependencies to package up right now...so I'll just submit the capture. 
[labeltest.zip](https://github.com/baldurk/renderdoc/files/772241/labeltest.zip)

**Comment by baldurk** [comment]
Right, it's definitely some issue with storing the names in the driver, other than an unrelated shader issue the capture opens fine for me an buffers & textures are named:

![image](https://cloud.githubusercontent.com/assets/661798/22924914/dc3b83c2-f29e-11e6-8cdc-fab8220ac1b5.png)
![image](https://cloud.githubusercontent.com/assets/661798/22924917/de7916b8-f29e-11e6-9df9-15f7c9c702ee.png)

(the weird misalignment on the CLODTerrainSMTexture_3_00 is because there's a `\n` in the name - I suspect that's not deliberate).

I think it's clear the solution is to store the names myself and not rely on the driver implementation at all, that should fix all of this. I'll do that today.

**Comment by cgrant78** [comment]
I forgot to mention that I was running the latest stable version 0.32, and I'm not seeing what you are seeing and the other way around too. Are you running the test with the nightly build or the latest stable? Thanks for looking into the issue.

Also I'll remove the extra newline char from the name .

**Comment by baldurk** [comment]
I tried on v0.32 as well as recent code, it seemed to behave the same. I've got a fix I'll push up later today that you can check out in the next nightly.

**Comment by cgrant78** [comment]
...thanks.

**Comment by baldurk** [comment]
That commit changes it to store the object names internally instead of also using KHR_debug for naming on replay. It worked for me (e.g. it let me use names that were applied before binding), but let me know how you get on with the next nightly build.

**Comment by cgrant78** [comment]
Just got a chance to test with RenderDoc_2017_02_15_a70bcb8a_64 nightly release and the object labels are now showing up correctly. Thanks!!!!
