### ISSUE TITLE
ID3D12Resource obtained via IDXGISwapChain3::GetBuffer has wrong ref count

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#527]
When RenderDoc v0.33 is loaded in D3D12 I get wrong refcount for swap chain ID3D12Resource.

Issue can be reproduced with latest bgfx (this check doesn't trigger without RenderDoc):
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_d3d12.cpp#L1749

**Comment by baldurk** [comment]
The refcount values aren't wrong, they're just different to the D3D12 runtime as it ships today - which could even be different from the D3D12 runtime in a year's time. The return values from AddRef and Release are for debugging only, they're not part of the interface contract and you shouldn't rely on their values being something specific.

I can change the behaviour to be similar to D3D11, where the internal reference on the swapchain image is hidden from the user so it will hit 0 when you release your last reference. That still fails your assert though because it seems to expect the refcount to be somehow shared between all the images. That behaviour won't ever happen because renderdoc tracks the images separately internally.

**Comment by bkaradzic** [comment]
It's useful for debugging resource leaks. I have mechanism to disable this functionality if RenderDoc is present, but I thought since only swap chain is wrong that might be easy fix.

**Comment by baldurk** [comment]
With that change it should hit 0 instead of 1 when you've released all your references. That's about as good as I can make it, there's no way it's worthwhile to link up the separate refcounts to track each other.

I realise it's useful to have the return values for debugging, but I wouldn't suggest making it a fatal error that's always on. Like I say the refcount values could easily change in a future D3D runtime to be tracked individually, and then the code doesn't know which refcount to expect.

**Comment by baldurk** [comment]
Closing this issue as the new behaviour is available in v0.34.
