### ISSUE TITLE
Vulkan: Renderdoc crashes in write serializer VKCreateImage.pQueueFamilyIndices  

### ISSUE THREAD

**Issue by scyganINTEL** [baldurk/renderdoc#529]
The write serialization of `VkCreateImage` crashes for me, because serialization of  `pQueueFamilyIndices`  is NOT skipped, when  `sharingMode` does not equal to `VK_SHARING_MODE_CONCURRENT`.

Spec says:
```
pQueueFamilyIndices is a list of queue families that will access this buffer (ignored if sharingMode is not VK_SHARING_MODE_CONCURRENT).
```

... so there is no guarantee that pQueueFamilyIndices  is a valid pointer in case of non-concurrent sharing mode.

The test app I am using seems to pass `queueFamilyIndexCount = -1` and `pQueueFamilyIndices = NULL`, what causes a crash.

**Comment by baldurk** [comment]
Right, this would work if `queueFamilyIndexCount` was 0 like most code seems to do, since then the array would be skipped.

It should be an easy fix but I'm away next week at GDC so I probably won't be able to make the fix until into March. As a workaround if you are able to modify the test app then set `queueFamilyIndexCount` to 0.

**Comment by baldurk** [comment]
Sorry for the delay. I believe it should be fixed with that commit, let me know what you find with the next nightly build.

**Comment by baldurk** [comment]
Closing this - the issue should be sorted in v0.34 which includes the above fix.
