### ISSUE TITLE
Clicking "Debug" on Pixel Context window for a Dispatch event opens pixel history view

### ISSUE THREAD

**Issue by ChrisBunner** [baldurk/renderdoc#533]
Perhaps this should just have the button grayed out or it should debug the default 0,0,0 thread?  Curious if this is intended (as the history button is still there and functional) or just a case of a code branch falling through unintentionally.

Clean installed v0.33, D3D11 trace, can supply a repro capture if it helps! :)

**Comment by baldurk** [comment]
Right so the rough behaviour of the debug button is

1. See if the current draw wrote to that pixel, if so debug the first write (if there were multiple).
2. If there weren't any writes, open the pixel history

So in this case even if a dispatch modified the pixel you have selected it's not easily detectable so I fall back to opening the pixel history view. It's the same if you selected a draw which hadn't written to it.

The separate debug button is a bit of a leftover from before I had the history feature, but it can be nice to launch the debug directly without having to go through the history, and then launch the debug from the current event.

I wouldn't want to grey out the button because it's still useful to have that fallback to pixel history - the user might not be thinking particularly about the current draw/dispatch, but just see that there's a pixel out of place and want to debug the last write.

Perhaps I could use the pixel history to detect if the current dispatch did write to the pixel (which I can't do perfectly - I can only detect a modification, not if there was a write but to the same value), but I'd still have to prompt the user for which group and thread to debug at some point in the process, debugging the 0,0,0 thread probably won't be what you want.

**Comment by ChrisBunner** [comment]
I see, makes sense :+1: Was more just seeing if the fallback was intentional as whilst it's probably always been that way, hadn't noticed it before.
