### ISSUE TITLE
empty compute shader resources from UE4 in GL

### ISSUE THREAD

**Issue by jonlm** [baldurk/renderdoc#535]
Hi, I'm running renderdoc on UE4 and running into a case where one particular compute shader can't be inspected in renderdoc. The calls to glDispatchCompute are in the Event Browser but when I inspect the compute state the shader id is the id from the previous dispatch and all of the resources are highlighted in red and labelled "Empty". There are several dozen dispatch calls to about five different shaders and only the calls to this specific shader don't work. Any thoughts on how I could go about diagnosing this? Happy to modify the engine if necessary. Thanks!

p.s. - Running in GL from Windows 10. For what it's worth, if I run in DX11 the dispatch calls to this shader are inspectable.

**Comment by baldurk** [comment]
Just to get it out of the way - I guess you can't send me a capture repro'ing the problem? That'd be the easy way to investigate it :smile:.

Failing that, it sounds like something's going wrong identifying the bound program. You'd need to see what's going on with the bind and why it's not updating the current state. If you look at the dispatch draw that's broken and look in the API inspector, can you see a glUseProgram or glBindProgramPipeline? That's the one to investigate. You can identify the event ID of it and then breakpoint in Serialise_glBindProgramPipeline or Serialise_glUseProgram to see if you can spot anything wrong (conditionally breakpointing on m_CurEventID to find the right call). Also worth checking to see if there are any errors in the diagnostic log.

Then also look in GLReplay::SavePipelineState where it fetches curProg from either the current program (or if that's 0) the current pipeline binding, and see if anything's going wrong there.

If you get more detail I can tell you where to dive in more, if you don't find anything wrong I can make a branch with some diagnostic logging added to see if we can track where the problem is from there.

**Comment by jonlm** [comment]
Can't send it, but might be able to create a simple test case.

Ah, yep, I do see glUseProgram in the API inspector, and it's got a unique ID, so I'll try what you suggested first. Thanks!

**Comment by jonlm** [comment]
Ok, figured it out. Was due to a bug in HLSL->GLSL translation from Unreal. It was emitting a swizzle on a constant like this: "0.xxxx" which is invalid GLSL. renderdoc prints compile errors to the output log but I didn't notice them until running in VS. Thanks for the help!
