### ISSUE TITLE
Text box doesn't allow ctrl+left/rightarrow

### ISSUE THREAD

**Issue by RCalocaO** [baldurk/renderdoc#542]
On the Capture Executable tab, Command-line Arguments text box, scrolling through a lot of arguments is easier if you press ctrl+left/right arrow to skip between words; I'm pretty sure this used to work a while ago but has been broken for some time.

**Comment by baldurk** [comment]
This hasn't ever been a feature in renderdoc, so you're maybe remembering something else. They're just regular textboxes so ctrl-left/right isn't a standard shortcut (although it's a common addition).

**Comment by RCalocaO** [comment]
I just tried the 0.21 standalone exe and it works there :)

**Comment by baldurk** [comment]
Oh shows what I know, it looks like it worked up to 0.31. I guess it _is_ a standard shortcut. I haven't checked, but I bet the reason why it fails is that I added a global shortcut for ctrl-left/ctrl-right which goes to the previous/next drawcall (see #389 for discussion).

I could probably make it so that shortcut only kicks in if there's a capture open - since there's nothing for it to do with no capture open and that's probably the time that you're editing command line arguments. Then at least the shortcut isn't stolen all the time. It's a bit of a hack, but would that work for you?

**Comment by RCalocaO** [comment]
That would be great! I personally don't use the shortcut (yet) :) I'd assume you want the shortcut on all tabs/window panes except the capture exec one... Whatever works out good for you!

**Comment by baldurk** [comment]
Sorry, I completely forgot about this until someone else mentioned it! It should be fixed with that commit, I filtered it so it only applies when a capture is open and also doesn't run when you have a textbox type control highlighted.

**Comment by RCalocaO** [comment]
Looks good, thanks!
