### ISSUE TITLE
[opengl] Frame not being captured completely / properly

### ISSUE THREAD

**Issue by sergeyreznik** [baldurk/renderdoc#548]
We have a world editor inside a Qt application. Capturing frame currently results only Qt draw calls to be captured (i.e one full screen quad with all controls and our scene). 
Here is some details:
- we are using OpenGL context from Qt (not creating separate context);
- we are rendering on QQuickWindow::beforeRendering signal (not sure if this will help);
- not using multi-threaded rendering;

I would be glad to provide sample application and all required information.

**Comment by baldurk** [comment]
Hi, yes a sample application or other repro details would be very useful here. I don't know exactly how Qt renders, it could be that it presents the swapchain more often and so the default behaviour of capturing a "frame" from one present to another then skips your rendering. The solution to this would probably be to use the [RenderDoc API](https://renderdoc.org/docs/in_application_api.html) to start and stop captures around your rendering.

If you send me a program that repros it, I can check what's happening for sure.

**Comment by sergeyreznik** [comment]
Here is a link to our editor:
https://www.dropbox.com/s/qxrsh4tj8xkqufk/ResourceEditor.zip?dl=0

Something more interesting happening here, behavior is pretty unstable:
- capturing an empty scene (only coordinate grid) seems to be working, but **sometimes** our render fails after capture (does not rendering anything);
- sometimes capturing opened scene does not work, but again **sometimes** it works fine.

I will provide test scene later if needed (so far I have not figured out which scenes exactly fails to capture). 

Could this issue be related to backward-compatible context we are using?

**Comment by baldurk** [comment]
Hi there, thanks for the link.

When I run it, I think I always get the frame rendering included in the capture, although it's hard to tell since the rendering is just to a grey screen:

![image](https://cloud.githubusercontent.com/assets/661798/24106692/9615a3ee-0d80-11e7-9522-19ef41574931.png)

It looks like that even running alone, not with renderdoc. I'm not sure if that's how it should look? if there should be some grid?

However it does sound like there's some kind of timing issue if sometimes it works and sometimes it doesn't. If you're not in control of when presentation happens with Qt, possibly your rendering doesn't happen at the same frequency as the presentation so there will be some frames rendered that only update Qt's stuff. If you happen to hit capture at that time, it will capture one of the frames without your work.

The only way around this is to manually start and stop the capture yourself when you know your work is happening. This could be triggered from a button in the UI when you detect that renderdoc is loaded, that's how I implemented the Unity integration.

The backwards-compatible context should be fine as long as you're not using legacy/deprecated functionality, since that's what I support with renderdoc.

**Comment by sergeyreznik** [comment]
Thank you for the responses, I will investigate issue more. 

Actually editor does not render anything, because you need to open project, and create new scene, but this is a bit complicated for unfamiliar user :)

**Comment by baldurk** [comment]
I'm going to close this as there hasn't been any update in a while, but if you find something is wrong on renderdoc's side please feel free to comment here with more information and I can open it up again to continue investigating.
