### ISSUE TITLE
Renderdoc crashes when trying to view drawcall

### ISSUE THREAD

**Issue by edrickhong** [baldurk/renderdoc#554]
This is for vulkan on amd's driver. I'm able to reproduce this on windows and the amdgpu pro driver on linux. It crashes when I'm trying to view my gui buffer. I do a cmd to copy the vertices and indices to the vertex and index buffer, then draw said vertex and index buffers. It might be my fault because I'm not doing any synchronization and just assuming the fixed function pipeline will copy before doing the draw call. On a side note, is there a way to view mips of the input textures? Thanks.

**Comment by baldurk** [comment]
That's not really enough information to investigate the problem. Can you send some repro details - ideally if possible the original program, but otherwise at least a capture that shows the problem? It will be difficult for me to investigate on linux, as it's not really possible to switch drivers easily and I'm currently using mesa for another bug. However I can investigate on windows if you can send a repro.

You definitely need synchronisation between a copy and a draw, since the copy is probably executed as a compute shader - the fixed function copy hardware (DMA engine) is exposed as a transfer-only queue on AMD hardware. That wouldn't explain a crash though (it might give corrupted geometry or something).

To view mips on any texture you can use the drop-down in the texture viewer:

![image](https://cloud.githubusercontent.com/assets/661798/24351587/32a2f97a-12de-11e7-9e5f-d6c5b8446d77.png)

**Comment by edrickhong** [comment]
I'll try to get the debugging symbols and get back to you on this. And thanks for the clarification, added in a barrier for the transfer

**Comment by edrickhong** [comment]
Btw, is there a way to point cmake to the correct qt library? I downloaded it manually and am not sure how to get cmake to use it

**Comment by baldurk** [comment]
I don't know exactly, I think there is a way but like most things with cmake it's a pain in the ass.

When I'm compiling on linux it's usually in ubuntu [with this ppa](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt562-trusty) which can be activated just by running `. /opt/qt56/bin/qt56-env.sh`. Or on other distros I've been able to get it in system-wide folders needing no configuration.

**Comment by zao** [comment]
Qt5 itself ships with a large set of CMake modules that one can use from CMake by adding the directory to `CMAKE_PREFIX_PATH` which is a list of places where CMake functionality like `find_package` and `find_program` searches.

Taking a quick look at the `qrenderdoc` build files, it seems that you mostly just invoke `qmake`, so a `find_program` might be enough to find the dir via the slightly more standard `CMAKE_PREFIX_PATH` over relying on the environment of the builder.

(documentation on "proper" use of Qt's CMake functionality is at http://doc.qt.io/qt-5/cmake-manual.html )

**Comment by baldurk** [comment]
I'm closing this issue since there hasn't been an update in a while. If you do find repro information that you can give me to investigate further please feel free to comment and I can re-open to continue investigating.
