### ISSUE TITLE
Crash when trying to open capture log (.rdc)

### ISSUE THREAD

**Issue by stelar7** [baldurk/renderdoc#561]
When i try to view a capture log, renderdoc crashes.

Link to data [here](https://www.dropbox.com/sh/cghlx21rvwme0r4/AAAEJLA5PlDt2N0c7uUbwwR2a?dl=0)
Link to code [here](https://github.com/stelar7/vulkanEngine/commit/ea91fde116eeb96be3fc2b1edcdfaae00467ef7c)

**Comment by baldurk** [comment]
It think this is caused by an invalid call from your code. From looking at the parameters in renderdoc's code (I don't know how to debug java) you have a call to `vkCreatePipelineLayout` where both the output pointer `VkPipelineLayout *pPipelineLayout` and the input pointer `const VkDescriptorSetLayout *pCreateInfo->pSetLayouts` are pointing at the same memory. This causes problems because as soon as the output pointer is written to then the input pointer becomes incorrect, and that breaks the renderdoc recording.

It's invalid because Vulkan is a C API and C aliasing rules apply, meaning you can't allow two pointers with different types (aside from `void *` and `char *`) to point to the same memory.

I did have quite some trouble getting the code running and I had to hack some stuff as it wouldn't compile, but I don't think that it would affect this. If this doesn't make sense though then let me know and I can try to investigate further.

**Comment by stelar7** [comment]
That seems to fix it! 

I find it odd that Vulkan doesn't report an error on this, but that might just be me not being used to C memory rules.

Thanks anyways. I don't think I would ever spot that.

**Comment by baldurk** [comment]
Glad to help :smile:. And yeh it's not really a vulkan issue but more a basic C/memory safety issue, so I don't think it'd be something the validation layers would be expected to catch either.
