### ISSUE TITLE
Application crash when calling vkGetPhysicalDeviceMemoryProperties2KHR

### ISSUE THREAD

**Issue by ArtVandelae** [baldurk/renderdoc#569]
I'm experiencing a crash in my application when running it in RenderDoc 0.33 and using the VK_KHR_get_physical_device_properties2 extension.

Calling vkGetPhysicalDeviceMemoryProperties2KHR while running in RenderDoc results in a crash somewhere in VkLayer_parameter_validation.dll according the the debugger.  Outside of RenderDoc it runs as expected and validates cleanly against the 1.0.46 SDK.  If I comment out the call or use the old vkGetPhysicalDeviceMemoryProperties function then the crash goes away and RenderDoc works correctly.  

All of the other calls related to the extension work correctly as well.

**Comment by baldurk** [comment]
Looks like this was an oversight on my part - I'd intercepted the function but I didn't hook it up to the extension so that `vkInstanceGetProcAddr` would return the pointer to it properly. That meant the dispatch chain skipped renderdoc's layer, and everything will blow up after that as objects don't get unwrapped.

I think it should be fixed with that change, let me know how you get on.

**Comment by ArtVandelae** [comment]
That fixed it. Thanks!
