### ISSUE TITLE
"-official" status and git commit hash for distro packaging

### ISSUE THREAD

**Issue by akien-mga** [baldurk/renderdoc#571]
I've just packaged RenderDoc for my Linux distro Mageia, and with a plain CMake call using the v0.33 release tarball from GitHub, I get this version string in `qrenderdoc`:
```
RenderDoc Unofficial release (v0.33 - NO_GIT_COMMIT_HASH_DEFINED)
```

[Looking at the source](https://github.com/baldurk/renderdoc/blob/master/qrenderdoc/Windows/MainWindow.cpp#L61), it seems easy to "fix" by calling `cmake -DGIT_HASH="anything-official"` ("anything" since in the case of `-official`, the first part of the string doesn't seem to used), but I wanted to ask what the upstream policy would be in this regard.

Can distro packages call themselves "official" when packaging stable releases (thus using the string `RenderDoc v0.33`), or should they mark the provenance in a clearer way? If the latter, maybe some additional logic would be necessary so that it appears as e.g.:
```
RenderDoc release on Mageia 6 (v0.33 - stable)
```

**Comment by baldurk** [comment]
Right I added a public variable `BUILD_VERSION_HASH` to control both the git hash (if you're not building within a git checkout), and suffixes like this.

The format I'd prefer would be `hash-official-distroname` or whatever additional suffix you want. So the -official would be picked up and the 'unofficial' title would disappear, but it would still be clear from any log output that it's been built downstream. 

At some point I will need to investigate porting breakpad crashdump reporting over to linux, but that's not as easy as it is on windows. That would be the main difference between my official builds and a distro's official builds - only my builds would have my own crash reporting enabled, since those are the only ones I'd have symbols for.

Hopefully that clarifies things. To be honest, a large part of the reason why this whole 'tagged suffixes' thing exists is because I was limited in how I could define things in the C# UI. Since it's on the way to being deprecated I should probably rethink how builds will be tagged with version info and displayed in the UI.

**Comment by akien-mga** [comment]
`BUILD_VERSION_HASH` looks good, I had overlooked it as I was grepping my way through the v0.33 source tarball. I'll cherry-pick 248dbfa4a2c8aaed4093b8bf02595972a9f289aa and use `BUILD_VERSION_HASH="v0.33-official-mageia"` then (or maybe `v0.33-official-%{release}`, where `%{release}` would be the package release suffix (`3.mga6` for my current package, would be `4.mga6` at the next build)).

**Comment by baldurk** [comment]
I'd like to have the git commit hash in there instead of `v0.33`. The version number is already stored separately, so I'd rather use `efc592bfe6dc0dfcfe7dc53135f5a6e0f1cdae5c` (the hash for v0.33). Ideally if you had a fork where you committed the cherry-pick and any other patches a unique hash of that would be used, so the hash listed there will tell you unambiguously exactly what version of the code was used to build, but if you don't have that then using the upstream base git hash is fine.

Also it's up to you if you use `-mageia` or `-%{release}`, but bear in mind in the latter case that you need to disambiguate from packages on other distros.

This variable is definitely getting overloaded with meaning though. On windows it needed to be packed together and there wasn't any other distribution but myself. It's needed both to identify the source code that was used to build it, and any custom changes. Both for user information and for diagnostics when looking at bugs.

Off the top of my head seems like we want to know:

* The upstream baseline git hash that the build was made from.
* If it was a local development build, local release build, or a stable release-for-packaging build.
* What distro it came from.
* Any distro-specific version number.
* An URL to the distro package.
* Possibly some way of identifying what patches were applied, e.g. the git hash of a fork where the build was made

The last one maybe not being useful, if distros just apply cherry-picks or custom patches in their packaging process and there's no good unique hash to list. Maybe it's enough for the distro's package URL to the specific versioned build page which will have information of what patches were applied?

Ping @jansol and @Marqin who are the other people I know who've packaged renderdoc - what information and/or metadata would you want tagged with builds?

**Comment by Marqin** [comment]
In Arch AUR the "our package number"(build number) is appended after -, like eg. "0.33.1-1", "0.33.1-2", which gives info about current build (so, our patches[applied as diff patches] + compiler flags)

**Comment by Marqin** [comment]
Also the package is not official, but it's in AUR - Arch User Repository - from which ppl download source packages and build them with `makepkg`, and then install via pacman

**Comment by jansol** [comment]
I'd prefer to keep it as simple as possible. Currently in nix I have hash-distro-nix, but I wouldn't mind changing to hash-offficial-nix. I'd hesitate going for anything longer though.

**Comment by baldurk** [comment]
Just to clarify I'm not suggesting overloading even more information into the variable that we have just now, I'm suggesting that there'd be separate variables storing version information that we want. Simple works for windows where I can just distribute one package that works for everybody, but on linux I think it's preferable to know where and how something was built.

**Comment by baldurk** [comment]
OK I've revamped the version stamping variables. I've removed the hacky "append onto the git hash" thing, and instead split it up into a couple of different variables.

These are all defined in `renderdoc/api/replay/version.h` and on linux you can set them directly via cmake variables. There's now an option to define stable vs nightly/interim/local builds and the hash is purely the commit hash. On top of that I've added three values for downstream distributions - the name of the distribution, an URL to the package info, and a version number that can be defined any way you like (e.g. Mageia could be `0.34-4.mga6`, Arch could be `0.34.0-1`, and Nix could be `0.34-nix` or something like that).

I built an example build like this:

```bash
cmake -DCMAKE_BUILD_TYPE=Release \
 -DBUILD_VERSION_HASH=e3306f4d3f00871f2dd2623f3ad9bb328f9273cf \
 -DBUILD_VERSION_DIST_NAME=DisttributionName \
 -DBUILD_VERSION_DIST_VER=0.34-foo.4b \
 -DBUILD_VERSION_DIST_CONTACT=https://distribution.example/packages/renderdoc \
 -DBUILD_VERSION_STABLE=ON
```

And here's the output on qrenderdoc's about dialog and `renderdoccmd version`:

![image](https://cloud.githubusercontent.com/assets/661798/25485466/f176bc08-2b55-11e7-9b0c-8187bb468831.png)

Before I commit this I'd like to hear feedback - does this seem a reasonable fit? It seems to check all the necessary boxes for me and makes it clear what the version is and where it was built.

**Comment by akien-mga** [comment]
It looks pretty good to me!

**Comment by Marqin** [comment]
I'm not sure about that "distributed by" part. Maybe it would be better as
"packaged for"? With "distributed by" it could be not clear when
distributed via some 3rd party repo. It could be "Distrubuted by Marqin"
but "packaged for Debian" in such case.

**Comment by Marqin** [comment]
I just mean to ask, if it's not better to replace words "distributed by"
with words "packaged for"

**Comment by baldurk** [comment]
Sure - I'm flexible on the phrasing. I just went went with "distributed by" since I figured each build would come from its own distro.

The intention would be to list the source - whether that's a packaging system or distro or family of distros, not the package maintainer (which could change from version to version).

**Comment by jansol** [comment]
Looks good! And yeah, "packaged for" is more accurate - debian repos are quite often used by ubuntu users for example.

**Comment by baldurk** [comment]
I've pushed my changes, using "Packaged for" phrasing. I'll close this down for now but comment here or open a new issue if you run into any issues packaging in future.
