### ISSUE TITLE
Shader debug search paths doesn't seem to be initialized from options

### ISSUE THREAD

**Issue by calvindhsu** [baldurk/renderdoc#572]
After entering some values into the shader debug search paths, i.e. D:\root_dir_to_my_shaders\, 

m_DebugInfoSearchPaths in WrappedShader::ShaderEntry (d3d11_resources.cpp) is null, so no search is performed.

So far I see that the relative path is returned correctly in "originalPath" using D3DSetBlob using RENDERDOC_ShaderDebugMagicValue_struct.

**Comment by baldurk** [comment]
Looks like the search paths are only set when the shader debug info path is configured with SetPrivateData and serialised that way, it's not set if the path is stored in the private data blob.

Should be an easy fix, I just need to set that search path vector to `WrappedID3D11Device::m_ShaderSearchPaths` for all shaders regardless.

**Comment by baldurk** [comment]
That commit should fix it - passing the search paths in at init time instead of only when processing a SetPrivateData call.

FYI I also found a bug that caused the search paths not to be saved into the config file at all (whoops!) so you'll want to grab the next nightly build or the latest code to make sure you have that fix too.

**Comment by calvindhsu** [comment]
Thanks again Baldur!  :)

**Comment by calvindhsu** [comment]
Fix verified on my end.
