### ISSUE TITLE
renderdoc crashing on null ptr

### ISSUE THREAD

**Issue by amhagan** [baldurk/renderdoc#579]
In vk_initstate.cpp I seem to be ending up with a null value for arrayIm (~ line 2115 ) for a few of my applications, resulting in renderdoc crashing. The following seems to fix it:

`  if (arrayIm)
	  {
		  GetDebugManager()->CopyArrayToTex2DMS(ToHandle<VkImage>(live), arrayIm->real.As<VkImage>(),
			  c.extent, (uint32_t)c.arrayLayers, (uint32_t)c.samples,
			  fmt);
	  }`

Can this change get rolled in or would you like me to make a PR ?

**Comment by baldurk** [comment]
If `arrayIm` is `NULL` at that point then that indicates a deeper problem, adding this if check is only patching over the broken symptom, you'd still have incorrect replay due to the missing image.

Do you have a repro case you can share or any other information about what's happening?

**Comment by amhagan** [comment]
As my application loads it fills m_InitialContents with calls made in WrappedVulkan::Create_InitialState.

It creates three initial images by calling: 
 GetResourceManager()->SetInitialContents(id, VulkanResourceManager::InitialContentData(
                                                       NULL, eInitialContents_ClearColorImage, NULL));

After that, calls get made to Apply_InitialState and WrappedVkImage *arrayIm = (WrappedVkImage *)initial.resource is null.

Should the items in m_InitialContents get set to something else before they get used in Apply_InitialState ?

**Comment by baldurk** [comment]
Hey, I think I know what might be wrong then. That path through Create_InitialState is unusual on vulkan, since I think it should only happen if an image isn't written to before being captured. But if that path is taken for an MSAA texture I was assuming it had real contents to restore, instead of just applying the clear. Switching around the order (to check for a clear before handling MSAA images) should fix it.

I've pushed a potential fix in that commit, it will be in the next nightly build. Let me know if it fixed the problem for you.

**Comment by amhagan** [comment]
that seemed to work. thanks !
