### ISSUE TITLE
vkCreateImage fails when using RenderDoc, but runs fine without

### ISSUE THREAD

**Issue by fredrikzetterman** [baldurk/renderdoc#582]
I have an odd issue when using RenderDoc(0.33).

When starting my exe (with or without validation layers), everything runs fine. When starting with RenderDoc however, it fails when calling vkCreateImage when creating MSAA targets. However, if I disable the MSAA path in my code, RenderDoc/my exe runs fine (and further vkCreateImage calls succeeds). Here's the code that causes trouble:
```
...other code...
    VkImageCreateInfo ici;
    ici.format = g_vkformat_lut[ri._color_fmt];

    if ( _dev->_phys._format_props[ici.format].optimalTilingFeatures & VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT ) {
      ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    } else if ( _dev->_phys._format_props[ici.format].linearTilingFeatures & VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT ) {
      ici.tiling = VK_IMAGE_TILING_LINEAR;
    }

    ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ici.pNext = nullptr;
    ici.flags = 0;
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.extent.width = ri._width;
    ici.extent.height = ri._height;
    ici.extent.depth = 1;
    ici.mipLevels = 1;
    ici.arrayLayers = 1;
    ici.samples = _sample_count;
    ici.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
    ici.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    ici.queueFamilyIndexCount = 0;
    ici.pQueueFamilyIndices = nullptr;
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;

    VkImageFormatProperties ifp;
    VK_VERIFY( vkGetPhysicalDeviceImageFormatProperties( _dev->_phys._device, 
          ici.format, ici.imageType, ici.tiling, ici.usage, ici.flags, &ifp ) );

    VK_VERIFY( vkCreateImage( _dev->_device, &ici, nullptr, &_color_msaa._img ) );
    ^^^^ fails ^^^^
```

And the error when debugging my exe (relevant parameters can be seen in this output):
```
RDOC 023308: [09:08:27]          vk_core.cpp(2604) - Warning - [Image:686/0] CreateImage extents exceed allowable limits for format: Width = 784 Height = 561 Depth = 1:  Limits for Width = 0 Height = 0 Depth = 0 for format VK_FORMAT_B8G8R8A8_SRGB.
RDOC 023308: [09:08:27]          vk_core.cpp(2604) - Warning - [Image:702/0] CreateImage resource size exceeds allowable maximum Image resource size = 0x6b6100, maximum resource size = 0x0 
RDOC 023308: [09:08:27]          vk_core.cpp(2604) - Warning - [Image:711/0] CreateImage mipLevels=1 exceeds allowable maximum supported by format of 0
RDOC 023308: [09:08:27]          vk_core.cpp(2604) - Warning - [Image:719/2133] CreateImage arrayLayers=1 exceeds allowable maximum supported by format of 0. For more information refer to Vulkan Spec Section '11.3. Images' which states 'arrayLayers must be less than or equal to VkImageFormatProperties::maxArrayLayers (as returned by vkGetPhysicalDeviceImageFormatProperties with format, type, tiling, usage, and flags equal to those in this structure)' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkImageCreateInfo)
RDOC 023308: [09:08:27]          vk_core.cpp(2604) - Warning - [Image:725/2138] CreateImage samples VK_SAMPLE_COUNT_4_BIT is not supported by format 0x00000000. For more information refer to Vulkan Spec Section '11.3. Images' which states 'samples must be a bit value that is set in VkImageFormatProperties::sampleCounts returned by vkGetPhysicalDeviceImageFormatProperties with format, type, tiling, usage, and flags equal to those in this structure' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkImageCreateInfo)
RDOC 023308: [09:08:27]          vk_core.cpp(2604) - Warning - [ParameterValidation:848/9] vkCreateImage: returned VK_ERROR_INITIALIZATION_FAILED, indicating that initialization of an object has failed
```

But as you can see, I do a call to vkGetPhysicalDeviceImageFormatProperties prior, to see what it returns. The values I get are the following:

```
ifp =
    maxExtent: {width=16384 height=16384 depth=1 }
    maxMipLevels: 15
    maxArrayLayers: 2048
    sampleCounts: 15
    maxResourceSize: 11728124018688
```

Full VkImageCreateInfo for reference:

```
ici =
    pNext: 0x0000000000000000
    flags: 0
    imageType: VK_IMAGE_TYPE_2D (1)
    format: VK_FORMAT_B8G8R8A8_SRGB (50)
    extent: {width=784 height=561 depth=1 }
    mipLevels: 1
    arrayLayers: 1
    samples: VK_SAMPLE_COUNT_4_BIT (4)
    tiling: VK_IMAGE_TILING_OPTIMAL (0)
    usage: 16 // VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT == 16
    sharingMode: VK_SHARING_MODE_EXCLUSIVE (0)
    queueFamilyIndexCount: 0
    pQueueFamilyIndices: 0x0000000000000000
    initialLayout: VK_IMAGE_LAYOUT_UNDEFINED (0)
```

I am fully aware that this issue is a bit diffuse, so if there's anything you need me to do or if you need extra information, please ask. My graphics card is a Radeon RX 480, attached a vulkan report from Vulkan Caps Viewer:
[vulkanreport.json.txt](https://github.com/baldurk/renderdoc/files/932385/vulkanreport.json.txt)

**Comment by baldurk** [comment]
I think the problem here is that I add additional usage flag bits to be able to operate internally. In this case the important one is that for MSAA images it adds `VK_IMAGE_USAGE_STORAGE_BIT`. On the 480, `VK_FORMAT_B8G8R8A8_SRGB` doesn't support `VK_IMAGE_USAGE_STORAGE_BIT` which leads to the confusingly-worded validation errors.

As a potential workaround, I don't know your use case but you could try creating the image as `VK_FORMAT_B8G8R8A8_UNORM` with the `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` flag, and then cast it to `VK_FORMAT_B8G8R8A8_SRGB` in the image view for color attachment. I think that should work, but I haven't tried it.

Unfortunately at the moment there isn't really a good proper fix for this that doesn't require changes to your code :disappointed:. The only thing I can do I think is detect whether or not a format supports storage and avoid adding the bit, then just remove the functionality that requires it - which may or may not break the capture/replay.

**Comment by fredrikzetterman** [comment]
Thank you for the very informative answer!

From my point of view, changing the code a bit to make sure RenderDoc works is no big deal, I'm just happy that my code didn't have any serious, hidden problem :)

I will try your solution, if it works I can use it iff I detect that RenderDoc is loaded.

If possible, I'd like a feature from RenderDoc (keep in mind that I don't know how complicated it would be to implement):

If a call fails, fall back to evaluate the original call (without added bits and tweaks). If the original call then succeeds, then report that RenderDoc changed something somewhere (optimally refer to which alterations where made), then log that to some debug function and/or printf. To me this is preferred to disabling features in RenderDoc, because that way I:
1) know it isn't my fault
2) can hopefully do some hacks so it still works

Do you think such a thing would be feasible?

**Comment by baldurk** [comment]
In general I try to only make minimal changes during capture, and in most cases they're completely invisible to the user. Adding those usage flags is probably the most invasive thing I do. On a case-by-case basis I can add some kind of fallback. It depends on how likely the changes will be to cause a problem and how hard it is to work around needing them.

Like I say in this case I should try and check the usage flags are valid, and warn and back-off if they can't be added. Though some of the usage flags would break things pretty heavily if they're not supported. It's also possible I could work around the need for STORAGE_BIT and implement a slow path that only needs COLOR_ATTACHMENT_BIT, which might alleviate the problem.

Remember that in general in vulkan you can't assume that any call will be checked - if the validation layers aren't present this could easily lead to a crash, so it has to be a pre-emptive measure rather than reacting to failure. Plus in general if something is validation-clean and breaks only when renderdoc is enabled, it's a safe bet that it's somehow a renderdoc bug.

**Comment by fredrikzetterman** [comment]
> Remember that in general in vulkan you can't assume that any call will be checked - if the validation layers aren't present this could easily lead to a crash, so it has to be a pre-emptive measure rather than reacting to failure. Plus in general if something is validation-clean and breaks only when renderdoc is enabled, it's a safe bet that it's somehow a renderdoc bug.

You are of course correct.

I've tried to implement your suggested changes to fix my problem, and they did indeed work. Thank you for the awesome tool, your fast response and your help! 👍 🥇
