### ISSUE TITLE
Instanced Mesh Preview doesn't work sometimes

### ISSUE THREAD

**Issue by SakibSaikia** [baldurk/renderdoc#585]
The instanced Mesh Preview (VS Output) shows severe mesh corruption. As far as I can tell, this seems to be a combination of high InstanceCount and high IndexCountPerInstance. In my case InstanceCount was 788 and IndexCountPerInstance was 1461. Attached image shows courrption in mesh viewer, and the actual rendered result in Texture Viewer. 

IThe first instance in the draw renders correctly. Everything afterwards is broke.

![image](https://cloud.githubusercontent.com/assets/8186559/25250676/9c4c222a-25e4-11e7-8314-66cd14227278.png)

![image](https://cloud.githubusercontent.com/assets/8186559/25250690/aa110cea-25e4-11e7-922a-3aaa63a5ca55.png)

**Comment by baldurk** [comment]
What API are you using? Is it only the preview that's broken, or is the data output also busted?

Are you able to share a capture that exhibits the problem? Without being able to repro it I'm not sure I'll have much chance to fix the bug. I did fix a bug since v0.33 that involved corrupted vertex outputs with instancing but it only applied to the GS/DS output where each instance might output a different amount of data.

Anything you can give me to try and help me repro the problem will be helpful.

**Comment by SakibSaikia** [comment]
I apologize. I should have provided more info. This is a DX11 issue, and I am on v0.33. I'm using VS-PS stages only.

I can send you a capture but the file size is rather large. Let me know how I can send it to you.

**Comment by baldurk** [comment]
No problem. Do you have any upload service you can use like google drive or dropbox? that's how I've received files in the past. You can post the link here, or email the link to me at baldurk@baldurk.org if you want to keep it private.

If you aren't signed up for anything like that, then possibly [mega.nz](https://mega.nz) will work? I'm not sure how much it allows without an account, but maybe you can sign up for a free account there with a throw-away email.

**Comment by SakibSaikia** [comment]
I've sent the capture via dropbox. Thanks.

**Comment by baldurk** [comment]
Cheers, I've found the problem - it's not dissimilar to the instancing problem I had before, where the stride from instance to instance calculated by `totalBytes / numInstances`  was wrong. For GS/DS that didn't account for instances being different sizes, and here it doesn't account for there being more than 32MB of output data (the fixed size of output buffer I have).

I do have a check for the output buffer being overrun, but it looks like it's not properly constructed and it fails in this case - I'm not entirely sure how it should be functioning since I know it does fail that check in some cases. My guess is it works if a single draw writes more than 32MB of data, but not if an instanced draw goes over that limit in total. The `totalBytes` figure is then truncated, and then the instance stride is shorter than it should be.

The fix is probably to get rid of the fixed size buffer and resize up when necessary, but that'll need to wait until Monday before I fix that. If you need a partial workaround before then you could search for `m_SOBufferSize` in d3d11_debug.h and bump it up. Doubling it to 64MB should be sufficient, which probably isn't even that big a deal to just do by default.

**Comment by SakibSaikia** [comment]
That's great, Baldur. Appreciate the prompt response. Keep making awesome stuff :)

**Comment by baldurk** [comment]
I'm going to keep this open until I _actually_ fix it, as opposed to just identifying the problem :wink:.

**Comment by SakibSaikia** [comment]
Right, my bad.

**Comment by baldurk** [comment]
That commit should fix the issue by letting the stream-out buffer resize up when it needs to, for both VS out and GS/DS out.

**Comment by SakibSaikia** [comment]
Verified fix. Thanks again 👍
