### ISSUE TITLE
When are the automatic 'Colour Pass' / 'Depth-only Pass' markers present?

### ISSUE THREAD

**Issue by muaz-git** [baldurk/renderdoc#595]
Hi, 
I am new to renderdoc as well as graphics. I am just aiming to collect some pixelwise annotated data by approach followed by [Stephan et al. ](https://bitbucket.org/visinf/projects-2016-playing-for-data).
The [code](https://bitbucket.org/visinf/projects-2016-playing-for-data/src/8b11a42db50184a773951af15e6b28e5c0602d9f/scripts/extract_from_game.py?at=master&fileviewer=file-view-default) they have provided, they are looking for some pattern like "Targets + Depth" as shown in screenshots provided on [this web](https://cloud.githubusercontent.com/assets/661798/8890997/634bf0f8-3316-11e5-9eb7-75d74e3a9356.png). But when I am trying to capture logs I don't get any event which would contain such pattern as shown in [this image](https://ibb.co/dHYhvk).

I am not sure why there is this difference. Only differences in my knowledge are:

- I installed renderdoc from official website and just installed using exe file but didn't build by my own as they provided the code on their repo. So does it make a difference?
- In screenshots provided I am using executable (graphics rendering) file which is different from what they are using. 
- When I open log, I receive an error with description "RenderDoc requires FEATURE_LEVEL_11_0 availability". 

I am trying to figure out this problem for last couple of days but unfortunately I am not able to succeed. I would really appreciate if this could be addressed. Thanks.

**Comment by baldurk** [comment]
When RenderDoc encounters a capture that doesn't have any debug markers at all defining regions of the frame, then it will automatically insert some 'fake' markers based on which targets are bound. E.g.:

![image](https://cloud.githubusercontent.com/assets/661798/25539114/7b1295f8-2c3d-11e7-977d-213f978cc824.png)

These are named "Colour Pass #X (N Targets + Depth)" or "Compute Pass #Y" or "Depth-only Pass #Z" and are generated with a [heuristic in the code](https://github.com/baldurk/renderdoc/blob/master/renderdocui/Code/Core.cs#L308).

In your example though, there is a marker region "HUD / Stats", so RenderDoc won't try to create its own conflicting markers. Unfortunately in your case there aren't any other useful markers, and this one is I believe the marker generated by DXUT's built-in UI.

If you have control over the source then you're better off adding your own markers and using that to define which regions of the frame to examine since you know exactly what should be grouped together.

**Comment by baldurk** [comment]
I'm going to close this now since there's nothing to fix here - but if you need any more clarification or information feel free to leave a comment or contact me [directly by email](mailto:baldurk@baldurk.org).
