### ISSUE TITLE
Launching an app via RenderDoc renders differently than running standalone

### ISSUE THREAD

**Issue by matyasf** [baldurk/renderdoc#605]
I have an app made with Xamarin in C# using OpenGL. Currently it has a bug (maybe there is some wrong OpenGL code in it) that causes some things not to render. But when launching it via Renderdoc to debug this issue, renderDoc renders it correctly... Heres a minimal sample, I can send sources too if you need it. https://www.dropbox.com/s/9i7wciijcoivhfu/SparrowGame.zip?dl=0

Expected behavior:
There is no red rectangle in the top left corner. (just run the app)

Observed behavior: 
There is a red rectangle in the top left corner when launching it in renderdoc with the launch button.

Note: The app needs OpenGL 4.2+ to run.
Renderdoc 0.33 exhibits this bug.
Renderdoc nightly 2017-05-05 crashes the app.

Thanks!

**Comment by baldurk** [comment]
Hey, I've had a look at this. I can see why the red rectangle shows up - that seems to be what the program is intending to do. I'm actually more confused about why it doesn't show up when RenderDoc isn't attached.

There are two drawcalls - the second draws the star, the first draws the rectangle:

![image](https://cloud.githubusercontent.com/assets/661798/25774197/eb6c4164-3282-11e7-8f1a-89183c41fc44.png)

It's using this vertex shader:

```glsl
#version 110
#define highp  
#define mediump  
#define lowp  
attribute vec4 aPosition;
attribute vec4 aColor;
uniform mat4 uMvpMatrix;
uniform vec4 uAlpha;
varying lowp vec4 vColor;
void main() {
  gl_Position = uMvpMatrix * aPosition;
  vColor = aColor * uAlpha;
}
```

and this fragment shader:

```glsl
#version 110
#define highp  
#define mediump  
#define lowp  
varying lowp vec4 vColor;
void main() {
  gl_FragColor = vColor;
}
```

And the vertex data comes in as red:

![image](https://cloud.githubusercontent.com/assets/661798/25774216/359fc58a-3283-11e7-8d78-35f455224060.png)

![image](https://cloud.githubusercontent.com/assets/661798/25774260/26b3b3f0-3284-11e7-9f2d-444a675d69db.png)

![image](https://cloud.githubusercontent.com/assets/661798/25774211/115091aa-3283-11e7-8c7c-6253af9c8c63.png)

In the past when this has happened it's because something in the program is using the fixed function pipeline or some other legacy code, and when RenderDoc renders its overlay or something then the driver goes down a modern path and changes, but from what I can see the program with the above shaders is always bound.

It's hard to debug from my side since RenderDoc makes it behave normally, but I'll keep investigating. Maybe this gives you some hints what might be wrong though.

**Comment by matyasf** [comment]
Thanks for the help!
Okay, this is really weird. The rectangle shows up if I run this code at the start of my app:    

Gl.Enable((EnableCap)Gl.DEBUG_OUTPUT_SYNCHRONOUS);

I guess RenderDoc enables this flag, thus it works. 
Maybe this is a driver bug? Im using an Nvidia 540M with driver version 376.54. But its weird that you are seeing the same behaviour.

**Comment by baldurk** [comment]
That's interesting. I found a driver bug just the other day that would go away if I enabled that flag - it was the cause of this workaround 023cb57c6650b46015fd326e45bf85d8f303d254 where if that flag wasn't enabled then the DSA functions would actually bind their parameters and change state.

**Comment by matyasf** [comment]
Thanks for the help! I guess this is not a RenderDoc issue then.
