### ISSUE TITLE
RenderDoc requires Visual C++ runtime

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#607]
I just ran into issue where renderdoc.dll silently fails to load because msvcr100.dll (VS2010 runtime) is not present. Not sure if it's mentioned anywhere but VS2010 redistributable is required to use RenderDoc properly. Just opening ticket in case there is fix for this, and in someone else runs into this issue.

**Comment by baldurk** [comment]
Yes, although note that since v0.33 I upgraded the compiler so it's now the VS2015 runtime that's required for new builds.

I'm not sure how I can fix this though - the installer will already install the runtime as necessary, and if you compile locally then you'll by definition have the runtime you need. The only case I can't cover is the portable zip builds where you'll need to have the runtime yourself.

I guess when the UI switches to Qt this will become more obvious, since then the UI will also require the same runtime and give a more obvious error when it fails to load.

**Comment by bkaradzic** [comment]
v0.33 I have was downloaded from here (x64 portable).

**Comment by baldurk** [comment]
Yeh like I say, for the portable zip I can't auto-install the redistributable. Hopefully in future there will at least be a more obvious error and the audience of renderdoc should be technically minded enough to figure out the problem.

In the past it's very rarely been a problem since the VS2010 redist was commonly used and so installed by other applications, that might be less true today but moving to VS2015 should give much the same result now.
