### ISSUE TITLE
Pure offscreen rendering

### ISSUE THREAD

**Issue by dkrikun** [baldurk/renderdoc#608]
I'm using Vulkan to perform pure offscreen rendering (i.e. without a swapchain and surface) to a framebuffer.

How to use RenderDoc to capture such kind of rendering?

**Comment by baldurk** [comment]
Without the swapchain presents to form a frame boundary you'll need to use the [in-application API](https://renderdoc.org/docs/in_application_api.html) that RenderDoc exposes to signal when to start and stop the frame capture.

For vulkan identifying the device is a little awkward because the device can be wrapped and you don't get a direct pointer, so you need to instead pass the pointer to the dispatch table. As a shortcut as long as you don't have more than one vulkan device (or some other graphics API active) you can pass `NULL` for both the device and the window and the active vulkan device will be captured.

**Comment by baldurk** [comment]
I'm going to close this down as hopefully you got it working with the API as mentioned above. If you're still having trouble you can comment again or contact me directly.

**Comment by dkrikun** [comment]
Sure, thank you!
