### ISSUE TITLE
Vulkan app crashes on capture load

### ISSUE THREAD

**Issue by Dolphiniac** [baldurk/renderdoc#613]
Hi, all.

Trying to build a Vulkan interface here, and I just got to multipass rendering with some FBX data.

Anyway, my depth is screwing up, so I thought I'd check RenderDoc to start debugging, and it crashes when loading the capture.  To note, it does NOT crash if I don't render the FBX mesh, but that doesn't really help me much.

Log file: http://puu.sh/vQ3VR/213e95bce3.log

Capture file: http://puu.sh/vQ4bw/ba62ee1763.rdc

**Comment by baldurk** [comment]
Hey, I can repro the crash but unfortunately it doesn't tell the whole story. For some reason the capture is missing a secondary command buffer which is being executed which is why it crashes, but I can't tell why that secondary command buffer was omitted.

Are you able to share the problem that you're running, that I could then test the capture-side of? If not I understand, if you're willing to try running some renderdoc builds with additional logging that could also help track it down.

**Comment by Dolphiniac** [comment]
I don't feel comfortable sharing the problem, but I don't mind running the
extra logging.  Hao?

**Comment by baldurk** [comment]
I will make up a branch tomorrow with extra logging and point you in that direction, if you can build and run it.

**Comment by Dolphiniac** [comment]
Sure.  Just let me know.

**Comment by Dolphiniac** [comment]
Any news on the logging build?

**Comment by baldurk** [comment]
Sorry I got caught up doing some other work. I'll sort this out shortly.

**Comment by baldurk** [comment]
Try the [logging-613](https://github.com/baldurk/renderdoc/tree/logging-613) branch, if you build a development build and zip the output log that might at least point to something that needs further investigation.

**Comment by Dolphiniac** [comment]
Okay, I ran it as short as I could to make the log smaller.

http://puu.sh/vSRtR/850ef4b4ee.log

**Comment by baldurk** [comment]
I think there's an error in your code, but it's a little long-winded to explain.

First we see the primary command buffer being started:

```
vkResetCommandBuffer() 145
vkBeginCommandBuffer() 145 -> baked 409
```

`145` being the ID assigned to the command buffer handle directly, and `409` being an internal ID for basically 'this version' of the command buffer, so it would have a different version when it's reset & recorded again.

Then we see some secondary command buffers being recorded:

```
vkResetCommandBuffer() 196
vkBeginCommandBuffer() 196 -> baked 410
vkEndCommandBuffer() 196 -> baked 410
vkResetCommandBuffer() 224
vkBeginCommandBuffer() 224 -> baked 411
vkEndCommandBuffer() 224 -> baked 411
... more like this ...
vkResetCommandBuffer() 371
vkBeginCommandBuffer() 371 -> baked 423
vkEndCommandBuffer() 371 -> baked 423
```

So e.g. `196` is recorded to the versioned ID `410`. Let's follow this one along, because `410` is one that ends up missing from the capture causing the crash.

These secondary command buffers are then executed on `145`:

```
vkCmdExecuteCommands() on 145 -> exec 196 baked 410
vkCmdExecuteCommands() on 145 -> exec 224 baked 411
... more again ...
vkCmdExecuteCommands() on 145 -> exec 371 baked 423
```

All good so far, now `145` is holding a reference to these command buffers, but they haven't been run yet since `145` hasn't been submitted.

Then the problem happens. `196` and friends are reset, re-recorded, and re-executed:

```
vkResetCommandBuffer() 196
vkBeginCommandBuffer() 196 -> baked 425
vkEndCommandBuffer() 196 -> baked 425
vkResetCommandBuffer() 224
vkBeginCommandBuffer() 224 -> baked 426
vkEndCommandBuffer() 224 -> baked 426
...
vkResetCommandBuffer() 371
vkBeginCommandBuffer() 371 -> baked 438
vkEndCommandBuffer() 371 -> baked 438
...
vkCmdExecuteCommands() on 145 -> exec 196 baked 425
vkCmdExecuteCommands() on 145 -> exec 224 baked 426
...
vkCmdExecuteCommands() on 145 -> exec 371 baked 438
```

So this time `196` is recorded as `425` and executed again. The end result is that you get duplicates in the referenced command buffers in the queue submission:

```
vkQueueSubmit() cmd buf 145 baked 409
   sub 0 id marking 196 ref'd 425 baked <-- should be 410 baked
   sub 1 id marking 224 ref'd 426 baked <-- should be 411 baked
   ...
   sub 15 id marking 196 ref'd 425 baked
   sub 16 id marking 224 ref'd 426 baked
```

In general command buffers have to be kept alive and unmodified until they're done executing on the GPU. With secondary command buffers this is a bit more complex, but in section [5.1 Command Buffer Lifecycle](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#commandbuffers-lifecycle) the spec says:

> Secondary command buffers can be recorded to a primary command buffer via vkCmdExecuteCommands. This partially ties the lifecycle of the two command buffers together - if the primary is submitted to a queue, both the primary and any secondaries recorded to it move to the pending state. Once execution of the primary completes, so does any secondary recorded within it, and once all executions of each command buffer complete, they move to the executable state. **If a secondary moves to any other state whilst it is recorded to another command buffer, the primary moves to the invalid state.** A primary moving to any other state does not affect the state of the secondary. Resetting or freeing a primary command buffer removes the linkage to any secondary command buffers that were recorded to it.

Emphasis mine - when the secondary command buffer is recorded, it moves from the `Executable` state to `Recording` state, and that violates the bolded line. Even though the secondary command buffer isn't yet in the `Pending` state it still needs to be left alone until the primary is submitted and executes. As it stands, the primary command buffer is invalidated when you re-record the secondary, and so it cannot be legally submitted later.

This is something that the validation layers should catch, so it'd be worth filing a bug there.

**Comment by Dolphiniac** [comment]
Oh, thank you so much!  You're right, I would have expected validation to
catch that.  I only remembered that vkCmdExecuteCommands steals the
contents, so I didn't realize that they still needed to be kept in their
finalized state until submission.  I'll restructure and test to make sure
that fixes the issue.

**Comment by Dolphiniac** [comment]
Yup, that was it.  I just allocated extra command buffers for each subpass for each material, and it fixed the issue.
