### ISSUE TITLE
GetPostVSData returning 'NoneType' object

### ISSUE THREAD

**Issue by avijit9** [baldurk/renderdoc#623]
I am trying to access the VS_Output data for a particular instance by the following code.
```
def callback(r):
    r.GetPostVSDataWrapper(3692)

pyrenderdoc.Renderer.Invoke(callback)
```

Note: I have modified the `GetPostVSData ` method with hardcoded value of `stage` and made another function `GetPostVSDataWrapper`. The definition is given below-

```
        public MeshFormat GetPostVSDataWrapper(UInt32 instID)
        {
            //IntPtr mem = CustomMarshal.Alloc(typeof(MeshFormat));
            MeshDataStage stage = MeshDataStage.VSOut;

            IntPtr mem = CustomMarshal.Alloc(typeof(MeshFormat));

            ReplayRenderer_GetPostVSData(m_Real, instID, stage, mem);

            MeshFormat ret = (MeshFormat)CustomMarshal.PtrToStructure(mem, typeof(MeshFormat), true);

            CustomMarshal.Free(mem);

            return ret;
        }
```

 But it is always returning` 'NoneType'` object everytime. I have doubt on two things - 
(a) I am not sure how to pass the `instID`? Right now I am getting the value from the `eventbrowser` (3692 I have put ). 

(b) The invoke method has `void `return type.

Can you please tell me what is wrong here? 
![instid](https://cloud.githubusercontent.com/assets/22516722/26313038/3ad3d536-3f27-11e7-8562-fff0ed0d733c.PNG)

**Comment by baldurk** [comment]
You asked one of these questions verbatim to me before in an email:

> How to get the values of 'instID' and 'stage'? I have attached the screenshot if event browser. I was putting InstanceCount from API calls as instID. But it is returning None. Please let me know what to do? Thanks in advance,
> ![image](https://cloud.githubusercontent.com/assets/661798/26313421/bb14f5a6-3f02-11e7-9927-e51ddc1b0cef.png)

And I gave you the answer at the time:

> The instID is the index of the instance. So 627 is too high - there are 627 instances so the maximum instance is 626. The stage is whichever stage you want to retrieve the data for, either VSOut or GSOut (it's not valid to call it with VSIn - you must get the vertex inputs manually if you want them).

Which hasn't changed - that problem still remains, you are passing an instance ID of 3693 which is too high.

The code internally clamps the parameter to the highest valid value (3692) anyway, so it would still return the data for the last instance.

As you can see in the code you have posted the return type from GetPostVSData is always a MeshFormat - even if it doesn't contain any data (it may point to a NULL buffer). If you are getting `None` back then it is an error in your python script. That's not something I can help with directly unless there's a problem with the python access itself or there's something else going wrong you haven't mentioned.

Also I do not understand why you're hardcoding the stage parameter to the function when you could just as easily pass it in from python without making local changes to complicate matters.

**Comment by avijit9** [comment]
I have tried passing instance ID values less than 3693 also (like 3692, 3690 etc, etc.). The result is same. I am getting the 'NoneType' object.

I have hardcoded the `stage ` parameter because if I pass it from python script it will result in `TypeError: expected MeshDataStage, got str`.

**Comment by Anteru** [comment]
That error indicates that you're not passing a `MeshDataStage`,  but a `str` -- did you try passing in the right type?

**Comment by avijit9** [comment]
How to pass `MeshDataStage` from python? Do I have access to this class?

**Comment by baldurk** [comment]
It's in the `renderdoc` namespace, just the same as it is in C# - `renderdoc.MeshDataStage.VSOut` for example.

**Comment by avijit9** [comment]
I will try this and let you know. But what do you mean by "error in the python script"? I have the python script that I am using which is basically you suggested me earlier. I tried a lot of things. But it is not working :(

**Comment by baldurk** [comment]
I don't know what your full python script looks like so I can't say what the error is. The snippet you posted in the original bug does nothing with the return value of GetPostVSData:

```
def callback(r):
    r.GetPostVSDataWrapper(3692) # return value unused

pyrenderdoc.Renderer.Invoke(callback)
```

So I presume whatever code you have in your real script that is actually using the return value has an error. If you have an example repro for when GetPostVSData returns `None` instead of a `MeshFormat` then I can investigate that as a bug, but otherwise I believe you have an error in your python script.

**Comment by avijit9** [comment]
I tried to check the type - `type(renderdoc.Renderer.Invoke(callback))` which is returning me `<type 'NoneType'>`.

**Comment by baldurk** [comment]
Yes that is expected because `Invoke` doesn't return anything - it calls your callback function with the appropriate environment to access the `ReplayRenderer`.

Inside your callback you are calling `GetPostVSData` and that function returns the data. This is a different function call, and it's not the same as `Invoke`, so you the return value of `GetPostVSData` will not also be returned from `Invoke`.

You could call many different `ReplayRenderer` functions in your callback - each with a different return value - and process them separately.

Help with understanding the python language itself is not on topic in this repository and I'm definitely not the right person to explain it since I only know a little python. I would suggest that you read python documentation or tutorials to understand better how the language works.

**Comment by avijit9** [comment]
Even if I want to print some attribute of the` MeshFormat` class it is giving `0` in all the cases. The code is given below -
```

def callback(r):
    print r.GetPostVSDataWrapper(2).compCount

```
I tried changing the attributes and also `instIDs`. So, I am worried whether I am passing the `instIDs` correctly or not. 

I will look into your suggestions and let you know. Thanks for your reply.

**Comment by Deepayan137** [comment]
Hi, 

I am also working on same kind of thing. I have successfully called the `GetPostVSData ` from python shell without any trouble. May be @avijit9 should consider upgrading to the latest version.
However, I am facing some difficulties in order to get the VSOutput data. I do not know if this is the good place to ask or not. 

1) I have the `MeshFormat `object now which has been returned from `GetPostVSData `. Can you please tell me which attribute stores the `VS_Output data`? I have tried with `buf' and 'idxbuf' and passing it to `GetBufferData `function from `ReplayRenderer.cs`. The output I am getting is the some array of `byte` object. Am I going in the right direction? 

2) Is there anyway where I can fill the frame of interest with different `colors `corresponding to different `Meshes`? Suppose pixels which belong to car gets green color. I want to extract mesh information from renderdoc and mark the pixels as green corresponds to the car. Stencil can help? If yes, which function would do the job?

Thanks in advance.

**Comment by baldurk** [comment]
Yes calling `GetBufferData` with the `buf` object gives the generated vertex data, as raw bytes. You'll need to interpret it using the output signature of the shader, although note that any SV_Position output will always be first, even if the shader signature declares it later.

No there's no way to render an image with colours for each draw. You would have to implement this functionality yourself.

**Comment by Deepayan137** [comment]
From generated.hlsl I have obtained the following - 

```
// No HLSL available - function stub generated

cbuffer cbuffer0 : register(b0) {
	float4 cb0_v0 : packoffset(c0.x);
	float4 cb0_v1 : packoffset(c1.x);
	float4 cb0_v2 : packoffset(c2.x);
	float4 cb0_v3 : packoffset(c3.x);
	float4 cb0_v4 : packoffset(c4.x);
	float4 cb0_v5 : packoffset(c5.x);
	float4 cb0_v6 : packoffset(c6.x);
	float4 cb0_v7 : packoffset(c7.x);
	float4 cb0_v8 : packoffset(c8.x);
};

cbuffer cbuffer1 : register(b1) {
	float4 cb1_v0 : packoffset(c0.x);
	float4 cb1_v1 : packoffset(c1.x);
	float4 cb1_v2 : packoffset(c2.x);
	float4 cb1_v3 : packoffset(c3.x);
	float4 cb1_v4 : packoffset(c4.x);
	float4 cb1_v5 : packoffset(c5.x);
	float4 cb1_v6 : packoffset(c6.x);
	float4 cb1_v7 : packoffset(c7.x);
};

cbuffer cbuffer2 : register(b2) {
	float4 cb2_v0 : packoffset(c0.x);
	float4 cb2_v1 : packoffset(c1.x);
	float4 cb2_v2 : packoffset(c2.x);
	float4 cb2_v3 : packoffset(c3.x);
	float4 cb2_v4 : packoffset(c4.x);
};



struct VSInput
{
	float3 param0 : POSITION;
	float4 param1 : NORMAL;
	float4 param2 : TANGENT;
	float2 param3 : TEXCOORD;
};

struct VSOutput
{
	float3 param0 : TEXCOORD0;
	float3 param1 : TEXCOORD1;
	float4 param2 : TEXCOORD2;
	float2 param3 : TEXCOORD3;
	float3 param4 : TEXCOORD4;
	float3 param5 : TEXCOORD5;
	float4 param6 : TEXCOORD6;
	float4 param7 : SV_Position;
};

VSOutput EditedShaderVS(in VSInput IN)
{
	VSOutput OUT = (VSOutput)0;

	// ...

	return OUT;
}

```

Is this is file I should investigate to generate vertex data?

**Comment by baldurk** [comment]
Well that's a generated stub based on the shader blob (from the looks of it, with no reflection data - just generated purely from the bytecode). You can access the same information programmatically through the python interface.

But once again the python interface is provided 'as-is' and I can't really give support on using it. If you're able to make use of it that's great and please let me know of any actual bugs you find, but I can't reasonably help with any possible use of the python scripting.

If you run into an actual bug then please let me know, otherwise you are more or less on your own to explore what you can do with the interface.

**Comment by Deepayan137** [comment]
Can you please tell me one thing? How to check the output signature of the Shader? Is this something like - 
```
struct vertexOutput{
    float4 position : SV_POSITION;
    float2 uv : TEXCOORD0;
};
```

**Comment by baldurk** [comment]
It's available through the shader reflection - `pyrenderdoc.CurPipelineState.GetShaderReflection()`. Look at the `OutputSig` member.
