### ISSUE TITLE
VkImage named using debug marker does not show up in texture viewer

### ISSUE THREAD

**Issue by warp-10** [baldurk/renderdoc#628]
Process (code was 2k+ lines, so it is abbreviated here)

1. Allocate arena for image data with buffer aliasing the entire space for defragmentation
2. Load scanline view of image into a staging buffer (same alignment reqs. as arena) - filled with 0xFF0000FF for now (opaque red).
3. Create image bound to device memory, which aliases the defragmentation buffer
4. Name the image (just "IMAGE" in this case - the call does go through to allocating a string, so I can guess it worked).
5. Record image barrier transitioning layout from undefined -> transfer_dst_optimal
6. Record vkCopyBufferToImage
7. Push into batch buffer for push thread, signal condition
--push thread--
8. Swap batch buffer out for workspace, reset fences
9. vkQueueSubmit with transfer fence, signal pop condition
--pop thread--
10. grab fences and vkWaitForFences (dorky select loop)

Not sure where the image is supposed to appear in the texture list during this process...

**Comment by baldurk** [comment]
Hey, sorry especially for an API like Vulkan it's not feasible for me to try to recreate a sample that replicates the behaviour you describe from pseudocode.

From what you describe, any capture that contains the vkCmdCopyBufferToImage should include both the buffer and image in its referenced resources and so it should show up in the texture list as well as in the event browser as a visible command which would show the source/destination resources.

Are you able to share your program for me to repro? or the frame capture you made? If you can't that's fine, but then I think the way to go would be for me to add some logging on a branch to see what's happening and why the image isn't showing up.

**Comment by warp-10** [comment]
Actually, I'm not seeing anything show up in captures.
I have "auto start" checked, but the window is empty.

To check, I've run the "texture" project in vulkanExamples. Still nothing.

Note: Mine is just a resource test, so there is no vkQueuePresentKHR or swapchain (I see "frame" on a few buttons, and am wondering if that is what is assumed...)

**Comment by baldurk** [comment]
OK I see sorry, I thought you were getting captures but the texture wasn't showing up.

The 'auto start' checkbox is [to do with saving a configuration](https://renderdoc.org/docs/getting_started/tips_tricks.html?highlight=auto-start), it doesn't connect to capturing.

I think the vulkanExamples projects from what I remember only render a single frame, so it's a little difficult to capture them. It should work I think if you do a queued frame capture of frame 1:

![image](https://cloud.githubusercontent.com/assets/661798/26556338/e6e31c8c-4491-11e7-8433-b791e435187c.png)

But yes RenderDoc captures frames based on the calls to `vkQueuePresentKHR` since there's no other way to determine when a frame starts and stops. If you're doing headless rendering where you aren't presenting to a window then you'll need to use the [in-application API](https://renderdoc.org/docs/in_application_api.html) RenderDoc provides, to start and stop the frame capture at whichever points makes sense for your application. You can normally just pass `NULL` for the device or window, since you don't have any windows and there's only one device (the vulkan device) so it will pick that one by default.

**Comment by warp-10** [comment]
Thanks.
Sorry to bring this up as an issue, and not know entirely how the tool is supposed to be used.

Unfortunately, linking against another library isn't an option right now.

What would really help is being able to record submissions to individual/all queues (the tricky bits are all going to happen in the transfer queues).

Sadly, the concept of "frame" is not very meaningful for CAD software, especially since we generally don't maintain internal frame counters or worry about precisely when a presentation will occur.

**Comment by baldurk** [comment]
It's no problem, I just didn't understand the trouble you were having at first.

You don't have to link to another library - the renderdoc dll is already injected into your program to capture (or on vulkan, it's loaded by the vulkan loader when the layer is enabled). When renderdoc is capturing your program then the API will be available.

You can access it just by using `GetModuleHandle("renderdoc.dll")` and then `GetProcAddress("RENDERDOC_GetAPI")`. You can also use this to conditionally execute the code depending on whether RenderDoc is present. Here's some example code:

```cpp
if(HMODULE mod = GetModuleHandleA("renderdoc.dll"))
{
	pRENDERDOC_GetAPI RENDERDOC_GetAPI = (pRENDERDOC_GetAPI)GetProcAddress(mod, "RENDERDOC_GetAPI");

	RENDERDOC_API_1_0_0 *rdoc_api = NULL;

	int ret = RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_0_0, (void **)&rdoc_api);

	assert(ret == 1);
	assert(rdoc_api->StartFrameCapture != NULL && rdoc_api->EndFrameCapture != NULL);
}
```

Then you simply call `rdoc_api->StartFrameCapture(NULL, NULL)` and `rdoc_api->EndFrameCapture(NULL, NULL)`.

It's quite fine to not have a direct concept of a frame, the presentation boundary is the automatic frame boundary since there's no other API function that can be used to delineate frames. But I've used the renderdoc API before to capture offline non-presentation work e.g. when baking LODs or performing compute processes that aren't directly presented. That's why the renderdoc API exists so that you can define your own entirely arbitrary start and stop times.

Hopefully that clears things up. If there are improvements I can make that will help suit your use case, please let me know what I can do - depending on priorities I might not be able to address it immediately but at the very least I need to know about it :).

**Comment by warp-10** [comment]
That worked.
So, I see my image, but - not surprisingly - it is all black and not red. At least it is the correct size and color format :P

A small improvement would be __cdecl StartCapture(void) & EndCapture(void) functions that could be linked to the latest API version without needing to include a header. Not sure how well this will survive/cope with other improvements, though (the API struct idea has its ups/downs)...

A big improvement (and I mean very big) would be a visual timeline of {threadId, timestamp, entrypoint} tuples from some start time to end time determined from the UI. The visual would be each thread has its own horizontal timeline, and API calls show up as little boxes - this could help identify poor synchronization, etc...

I notice that there are requests for multiple queues as an enhancement, so I won't repeat that here - that would be a very basic part of the above.

Even though drivers currently look like they're just routing every submission into one physical queue, we _might_ see true queue parallelism in the future (resources in one thread, rendering in another, compute in yet another, etc...).

**Comment by warp-10** [comment]
I would also like to note that some applications might have multiple swapchains. You may want to detect whenever a particular swapchain is being presented, rather than relying on a single concept of frame. For example: We could have a tool that renders texture previews into a separate floating window that shares its device with a bunch of other free-floating viewport windows. Frame swaps for each will necessarily occur at different times (though, on windows, all happen in the same thread).

**Comment by baldurk** [comment]
Yes I already handle the case of multiple swapchains as it's quite common in editors (I encountered it even before renderdoc was publicly released in the cryengine editor :smile:). The 'frame' is defined as one present on a window to the next present *on that same window*, so presents from other windows don't interfere. The overlay lets you cycle through which window is considered active.

I don't want to export any static functions for the API since then it opens several questions - maybe there's another function or two that are very commonly wanted, so maybe they should be exported too? Also what if StartCapture() or EndCapture() are changed in a backwards incompatible way, with the version-specific API struct I can easily return different function pointers based on which version was requested, but with a single exported function then either I break old programs or I have to export StartCapture2() and EndCapture2(). In the end I think the header is fairly easy to drop into a project since it's standalone, so it's worth the tradeoff.

The threadid/timestamp/duration thing is something I have had in mind for a while now. I have been working in the background on a revamped serialisation scheme and it will let me save a thread ID and CPU-side timestamp/duration for every API call. This won't immediately be visible in the UI but the data will be present in the captures so it would be at least possible to write a visualisation.

And yes queue parallelism is definitely a thing already, at least on AMD cards. Being able to visualise the CPU and GPU queues is probably something RenderDoc will need to support in future although it starts to run into questions about what the scope of RenderDoc is in that respect :smile:.
