### ISSUE TITLE
some screenshots work, some don't.

### ISSUE THREAD

**Issue by bogdann96** [baldurk/renderdoc#629]
https://www.youtube.com/watch?v=qI5kcJAWRIA

I don't know what details I should give, so tell me if you need any. Thanks for watching the video.

**Comment by baldurk** [comment]
Hi, yes this is a bug [that's been fixed](https://github.com/baldurk/renderdoc/commit/16bc831c167503bab94ba72e482172d5d4c3f2d6) since v0.34. It only affects OpenGL and I didn't catch it unfortunately since it also only affects windows 10. You can download the latest nightly build, or alternatively capture multiple frames at a time and one of them will be working:

![image](https://cloud.githubusercontent.com/assets/661798/26587319/e305cd90-4549-11e7-9f31-78228f92de91.png)

**Comment by bogdann96** [comment]
Perfect. It works now. Thanks.
