### ISSUE TITLE
Visual Studio 2017 

### ISSUE THREAD

**Issue by el3ment** [baldurk/renderdoc#631]
At some point the upgrade to VS 2017 should be considered. This issue is so that you can track that upgrade when it happens!

**Comment by baldurk** [comment]
I think it's very unlikely I'll ever change renderdoc to VS 2017. I only just very recently switched from VS 2010 to VS 2015, and that was because there was realistically no choice - really I would have much preferred to stay on 2010.

Staying on the lowest version as long as possible likely means it'll be one or two versions after 2017 before I'm forced to change.
