### ISSUE TITLE
Knowledge share - made a python script to dump information from rdc log

### ISSUE THREAD

**Issue by vinjn** [baldurk/renderdoc#632]
https://gist.github.com/vinjn/fecd33ff8c407d7c31e8392142318f1c

You can get information about draw calls, textures and buffers.

**Comment by baldurk** [comment]
Thanks!

FWIW, you can export the drawcall information from the event browser directly in a similar fashion.

I'm going to close this issue since an open issue implies there's something unresolved for me to do, but this is useful for people to see an example of how to use the python API.

**Comment by vinjn** [comment]
I do have a question, the ID from `outputs[]` and `depthOut` looks like `1000000000000000433`.
It's different from other IDs like `ResID_12344`.
How to connect them?

**Comment by baldurk** [comment]
Those are the internal IDs, created on replay to identify the replay-time resources and there's a mapping inside the API back-end which translates to and from the original IDs given during capture like `12344`. You can tell them apart because replay-time resources are all >= `1000000000000000000`.

There's no way to convert from the UI side, but really I should remap those IDs before storing them in `draw.outputs` and `draw.depthOut`. I just left them alone because they're only ever used to compare two draws to see if they have the same bindings, to generate the "colour pass #12345" markers etc - the actual values aren't used for anything as long as they're the same for the same textures, etc.

**Comment by vinjn** [comment]
All right, it makes sense to me now. Any chance remapping them soon? With the correct mapping, I can connect the resources and visualize the data flow in the frame.

**Comment by baldurk** [comment]
Can you give it a try with that commit? I think that should do the trick, at least it worked on a few captures I tried.

Also the data flow visualisation you're talking about sounds interesting - when you have it working can you share a peek? :smile:.

**Comment by vinjn** [comment]
I will try that next week, and will keep you updated.

**Comment by vinjn** [comment]
Happen to have some time in the weekend.
And your fix works!
You can check the current result -> https://github.com/vinjn/renderdoc-frame-reporter#sample-outputs
