### ISSUE TITLE
glXWaitX is not implemented in the tracer.

### ISSUE THREAD

**Issue by jrmuizel** [baldurk/renderdoc#638]
Firefox crashes when it sees this missing.

**Comment by baldurk** [comment]
Sorted with that commit I think. Let me know how you get on.

For background, a while ago this function was used as a dummy to force libGL to be linked even in qrenderdoc/renderdoccmd even though renderdoc provided all the GL symbols required. So I couldn't export it for hooking.

Since @galpeter fixed the linking setup to not need that hack it looks like I forgot to add back in the hooking for it.

**Comment by baldurk** [comment]
Closing this down now as the function is now exported in the v0.90 release.
