### ISSUE TITLE
Having to right-click to change Texture Viewer focus point is not obvious.

### ISSUE THREAD

**Issue by michaelrgb** [baldurk/renderdoc#655]
We were examining a depth buffer and were wondering why the "1.00" was never changing in the status bar as we moved across viewer. Because it had a very narrow range of depth values, we assumed that it was a precision issue and that we needed to show more decimal places.

It was only much later that we realised that you need to right-click to change the focal point. I know it says "Right Click" in the status bar, but can we just have the same behaviour as the NVidia's Linux Graphics Debugger by just changing focus without any buttons?

Having used NVidia's LGD first was why this was so unintuitive.

**Comment by baldurk** [comment]
I'm not going to change the pixel picking to be button-less. The reason for right clicking is so that you can move the mouse freely without worrying about losing the pixel you've picked - if you don't have to press any buttons then highlighting a particular pixel becomes a chore and it's very easy to then accidentally nudge the mouse and select a different one. Likewise it has consistency with the mesh viewer - in both cases right clicking picks vertices/pixels, and left click pans/moves the camera.

As you mention there's "right click" on the picked pixel, and the colour swatch on the status bar whose only purpose is to draw the eye there to see the text. The text then has the moving/changing 'hover' text which shows the hovered texture co-ordinate, and then the unmoving/unchanging 'right click' text showing the current pixel - as soon as you see it the you can see that as the mouse moves the right click values aren't changing - even on a flat texture you can still see the co-ordinates remain fixed to whichever point is picked.

I'm not sure I can make it any more obvious without being annoying really. I think it's fairly intuitive as I've not had anyone mention before that they've not understood how to pick values, and being different to another debugger isn't necessarily the same as being unintuitive.
