### ISSUE TITLE
OpenGL capture crashes on "BufferData with NULL pointer + MapBuffer" sequence

### ISSUE THREAD

**Issue by EBatut-ALG** [baldurk/renderdoc#684]
Hi

Investigating why RenderDoc was crashing with our OGL2 test harness, I found that the following code sequence causes RenderDoc to crash:
```
	GLuint buffer;
	glGenBuffers(1, &buffer);

	glBindBuffer(GL_ARRAY_BUFFER, buffer);
	glBufferData(GL_ARRAY_BUFFER, 0x10000, NULL, GL_STATIC_DRAW);
	glBindBuffer(GL_ARRAY_BUFFER, 0);

	glBindBuffer(GL_ARRAY_BUFFER, buffer);
	void* ptr = glMapBuffer(GL_ARRAY_BUFFER, GL_WRITE_ONLY);
	glUnmapBuffer(GL_ARRAY_BUFFER);
	glBindBuffer(GL_ARRAY_BUFFER, 0);

	glDeleteBuffers(1, &buffer);
```

The crash happens during the MapBuffer call, rerouted to glMapNamedBufferRangeEXT, in gl_buffer_funcs.cpp at line 1939 : `memcpy(shadow, record->GetDataPtr(), buflength);`. RenderDoc crashes because the way the `ResourceRecord` is setup for the buffer, `DataPtr` is 0, and `DataOffset` is non-zero, so the memcpy tries to source data from 0x0 + a small value, causing an access violation.

Why are things setup that way? At the end of the `glBufferData` wrapper, specifically at line 736 in the same file, the capture state is tested, as well as `record->GetDataPtr()`. However, `GetDataPtr()` is non-null here, because the `ResourceRecord`'s `DataOffset` is modified by the `Serialise_glNamedBufferDataEXT` call on line 728 and is non-zero. So in our case, the `else` block at line 742 which correctly fills the data chunk/length/usage for the `ResourceRecord` is not executed. and the buffer location is never tracked (hence the access violation later in the `MapBuffer` wrapper).

Suggested fix: on line 736, replace `record->GetDataPtr()` by `record->HasDataPtr()`, which will test if the `ResourceRecord`'s base `DataPtr` is NULL, regardless of the value of its `DataOffset`. This fixes the crash that I am encountering, but I cannot tell with exact certainty if that would be the right behaviour for RenderDoc. I suspect that the `ResourceRecord`'s `DataOffset` needs to be adjusted accordingly, as for now all our renders are black when replaying the capture, so I suspect this fix is not enough on its own...

Best Regards,
Eric

**Comment by EBatut-ALG** [comment]
Looking at the file history, it looks related to 6694c7302fc03541e16fede262a263fb8235cbe3

**Comment by baldurk** [comment]
Hey, sorry for the delayed reply!

Your analysis is exactly correct, the call to `record->GetDataPtr()` is incorrect and should be to `record->HasDataPtr()` as with the others. Looks like I just forgot to update this instance in https://github.com/baldurk/renderdoc/commit/6694c7302fc03541e16fede262a263fb8235cbe3 and since it's a relatively specific situation it didn't show up as a bug since then. The reasoning for the data pointer/data offset stuff is tediously historical so I won't embarrass myself any more by detailing it :smile:.

As to the replay not working, I don't think it's due to `DataOffset` being wrong - that offset refers specifically to how far into the serialised chunk containing the serialised data buffer, the actual data pointer is. It's aligned up to 64 so that map pointers are aligned, so DataOffset will almost always be 64. It should only need to change if the actual serialisation format changed to contain more data before the buffer.

I'm happy to help debug the failing replay though if you're able to give me any more info. The only thing that sets off alarm bells is you mentioning an OGL _2_ test harness - so if you're using functionality that renderdoc doesn't support in GL 2.0 that was deprecated in GL 3.2, that could account for the problem.

**Comment by EBatut-ALG** [comment]
Hey, no problem, we're all busy and a 17-hour reply time for an one-man open-source product isn't exactly what I would call a "delayed answer" :-D

Regarding OGL2 features, we experience the same black renders with our OGL3 test harness, and since we're not doing any super weird old-school OGL trick, I'm not sure this is caused by out-of-fashion OGL features, or at least I hope not.

I attach a zipfile with two captures, one working OK, captured with our D3D11 backend, and one not working (black render), captured with our OGL2 backend. Source data is identical, gfx api-wise, and the end result should be the rotated square texture you can see replaying the D3D11 capture. In both cases, we do an instanced rendering of 1 instance of 1 full-screen triangle, which is transformed by the VS. Looking at the geometry, the D3D11 capture correctly shows that the post-VS SV_Position values define a triangle which will cover some area of the screen. On the other hand, the OGL2 capture shows that the post-VS gl_Position values are all identical and will cover nothing. What might be relevant is that we do not source input vertex positions at all, only instance attributes, and the vertex positions are generated in the VS from gl_VertexID.

If the captures themselves are borked and you need to be able to perform some captures locally, I can probably send you a package with the test harnesses themselves and some input data, but I'd rather post this to a private address than to GitHub.

Thanks a lot for your help in investigating this!
Eric

[vertexID-instanced.zip](https://github.com/baldurk/renderdoc/files/1122134/vertexID-instanced.zip)

**Comment by baldurk** [comment]
I've tracked the bug as far as I can from the capture.

1. The bad mesh transform is because the uniforms are all 0s instead of proper values.
2. The glUniform calls are failing because the location translation table (that remaps location values which can change between implementations) is empty, and so the location gets translated to -1.
3. The location translation table is empty because ... I'm not sure. The initial state of the program claims that it has 0 free uniforms (ie. values not in UBOs). I don't know why this is.

If you can send me a repro feel free - my email is baldurk@baldurk.org. If you'd feel more comfortable, I can also point you at a branch with increased verbose logging around this region to see if we can narrow it down that way.

**Comment by EBatut-ALG** [comment]
I sent you an email with a link to a repro package with more details on the way we do things internally and some hypotheses as to why it could cause some of RenderDoc's paths to fail.

If there's anything I can do to help you solve this, please ping me, I'll be glad to help!

Best Regards,
Eric

**Comment by EBatut-ALG** [comment]
Thanks for the simple and elegant fix, the capture now works even if OGL programs are created *after* StartFrameCapture is called \o/

Cheers!
