### ISSUE TITLE
VERIFIER STOP: Freeing heap block containing an active critical section.

### ISSUE THREAD

**Issue by mrshutterbug** [baldurk/renderdoc#685]
Description:
Microsoft's Application Verifies detects a problem when attempting shutdown RenderDoc

Repro:
- Build with vs2015 for windows x64
- Run Microsoft's "Application Verifier" and pick the exe you built.  
- In the "Tests" window, make sure "Basics" is checked.  Save if necessary.
- Run the exe you built (which uses RenderDoc).
- Exit the exe, so that it calls RENDERDOC_API_1_1_0::Shutdown().
- Observe that Application Verifier stops with output like this:

  RDOC 007600: [14:59:35]       win32_hook.cpp( 796) - Error   - Failed to make IAT entry writeable 
  0x00007FFC448C0E48
  RDOC 007600: [14:59:35]       win32_hook.cpp( 796) - Error   - Failed to make IAT entry writeable 
  0x00007FFC448C0E58

  =======================================
  VERIFIER STOP 0000000000000202: pid 0x1DB0: Freeing heap block containing an active critical section. 

    00000221B983F108 : Critical section address. Run !cs -s <address> to get more information.
    000002219D45F8A0 : Critical section initialization stack trace. Run dps <address> to dump the stack trace.
    00000221B983E900 : Heap block address.
    0000000000003700 : Heap block size.

**Comment by baldurk** [comment]
Hi, thanks for the detailed report. I think there are some more details needed - for example does this happen with any program at all? Or only your application that you're testing with?

Also this step worries me a lot:

> Exit the exe, so that it calls RENDERDOC_API_1_1_0::Shutdown().

Are you really calling the shutdown function from your exe? Why are you calling it exactly, and where in your flow are you calling it?

This function is provided as "best effort" as there isn't a guaranteed way to be able to unload renderdoc and many parts of the hooking are irreversible, So if it causes some corruption only when calling this function I'm not surprised and it's not going to be worth fixing.

If you're really calling it at exit time as well then this is far more likely to break - the errors that you printed I assume are part of this. If you're going to call Shutdown at all, then this function should be called as early as possible (ideally the first thing in `main()` if you decide it's needed).

**Comment by mrshutterbug** [comment]
Thanks for the quick reply.  I'm working on a project that uses bgfx (https://github.com/bkaradzic/bgfx).  I believe you can repro this issue with any of the samples.  When bgfx shuts down, it also shuts down RenderDoc.  This happens on exit, or when switching renderers (e.g. when switching from d3d11 to opengl).  

We would like to be able to run all of our code with Application Verifier enabled, from time to time.  Errors like this make it harder to test the integrity of our own code.  A fix would be greatly appreciated.

Thank you for your time.

**Comment by baldurk** [comment]
Thanks for clarifying. It looks like bgfx is indeed calling shutdown and also unloading the renderdoc dll when it exits the program, which is bad. I'll file an issue over there to get that changed - in the meantime you can try going to the 'unloadRenderDoc' function in `debug_renderdoc.cpp` and commenting out all of the code in there so that it does nothing.

**Comment by mrshutterbug** [comment]
If I don't shutdown RenderDoc, it leaks memory, which ApplicationVerifier also complains about.  If you could fix RenderDoc to shutdown cleanly (no leaks & no undefined behavior), that would be great.

From the log:

BGFX Shutdown...
BGFX Shutdown complete.

=======================================
VERIFIER STOP 0000000000000900: pid 0x2958: A heap allocation was leaked. 

	000001BB8701CE00 : Address of the leaked allocation. Run !heap -p -a <address> to get additional information about the allocation.
	000001BBD50F5980 : Address to the allocation stack trace. Run dps <address> to view the allocation stack.
	000001BBE41B4FE8 : Address of the owner dll name. Run du <address> to read the dll name.
	00007FFC41C20000 : Base of the owner dll. Run .reload <dll_name> = <address> to reload the owner dll. Use 'lm' to get more information about the loaded and unloaded modules.

**Comment by baldurk** [comment]
Doing an entirely clean shutdown with no leaks isn't a goal right now, or possibly ever. It doesn't really fit with a dll which is injected without application knowledge and doesn't receive any callbacks before process shutdown. As long as there's nothing drastic that can cause crashes, and of course no leaks that add up over time, that's all I aim for.

If you need a completely warning/error free run then I'd recommend not launching from RenderDoc while application verifier is enabled, and only use one tool at a time, otherwise you're likely to keep chasing false positives like this.

**Comment by mrshutterbug** [comment]
Our code (using BGFX) is no longer attempting to shutdown RenderDoc.  Now (in addition to the leaks), we have a new problem.  Other code, unrelated to RenderDoc is getting an error calling WSACleanup(), indicating that WSAStartup() was never called.  Now, these are Windows APIs, which are internally ref-counted.  It appears that using render doc (and not shutting it down) results in a mismatch between the number of times WSAStartup() and WSACleanup() is called.  In particular, it appears that RenderDoc is calling WSACleanup() too many time (thus cleaning up the 'startup' that was preformed by unrelated code)!

Note that RenderDoc also appears to notice this issue for itself.  The end of the log includes this:

RDOC 018168: [11:19:14]  sys_win32_hooks.cpp( 142) - Log     - WSACleanup called with (to the application) no WSAStartup! Ignoring.

Again.  Our graphics programmers like using RenderDoc.  Please fix it so that it can be used without destroying everything else's ability to shutdown properly!

**Comment by baldurk** [comment]
I only call WSAStartup [once](https://github.com/baldurk/renderdoc/blob/master/renderdoc/os/win32/win32_network.cpp#L39) [at startup](https://github.com/baldurk/renderdoc/blob/master/renderdoc/core/core.cpp#L256) and then WSACleanup [once](https://github.com/baldurk/renderdoc/blob/master/renderdoc/os/win32/win32_network.cpp#L44) [at shutdown](https://github.com/baldurk/renderdoc/blob/master/renderdoc/core/core.cpp#L389), so I'm not sure how the code could be calling WSACleanup multiple times without the application doing that itself.

The only thing RenderDoc does in regards to these functions is it maintains [its own refcount](https://github.com/baldurk/renderdoc/blob/master/renderdoc/os/win32/sys_win32_hooks.cpp#L126-L150) for them, to prevent the application from closing my sockets. This happened on one program where it called WSACleanup() first before its own WSAStartup(), which cancelled out mine. So now I track the refcount, starting from 1 at program startup, and if it would ever drop below 1 then I ignore the call to WSACLeanup(). This means that I'm changing the behaviour, but only to call it _fewer_ times (which means it might leak, but shouldn't ever be closed early), and it only happens if the application itself is calling these functions mismatched. Note that renderdoc explicitly sets the `WSANOTINITIALISED` error that it sounds like you're getting reported, when it hits this case.

If you're seeing that error being printed it suggests something is already going wrong on the application side to have mismatched WSAStartup() & WSACleanup() calls, since RenderDoc should be loaded before any other code executes so it can be able to track the refcount accurately.

Do you have a repro for this behaviour? It sounds like an application bug, but without being able to investigate more myself I can't really tell. If you can build renderdoc locally you could also put an extra debug log message in the functions in sys_win32_hooks.cpp I linked above to see how often they are being called by the application, and if you want you can add a log when renderdoc calls it to verify that the renderdoc code isn't being executed more than once.

**Comment by baldurk** [comment]
I'm closing this now as it's not clear there's anything remaining to solve on renderdoc's side. If you have more information or a repro about something going wrong in the normal flow then feel free to add another comment or open a new issue about that issue.
