### ISSUE TITLE
Global hook in steam games, Cap doens't appear?

### ISSUE THREAD

**Issue by HathawayJA** [baldurk/renderdoc#694]
Hello,
So my issue is that I am trying to capture Skyrim Special Edition. The only way I could get the renderdoc overlay to appear is to do a global hook. It appears in the overlay to believe that it is indeed capturing frames correctly, however whenever I close the game to view the cap, nothing ever comes up in the window. I'm not sure if it's not actually getting the capture, or if it is failing to hand off the cap at some point. Has anyone experienced a similar thing? Am I just using it wrong?

**Comment by baldurk** [comment]
When you use the global hook renderdoc doesn't automatically connect to the program (since it doesn't know what the target process is). You have to go File -> Attach to Running Instance and find it listed there. Then it will create a connection and show any captures that are made. If you never connected, the captures should be stored in the capture location - by default %TEMP%\RenderDoc.

Note that I do not provide any support for capturing 3rd party games that you don't own. Unless this problem shows up regardless of application and you can give me a repro on another program, I can't help any further.
