### ISSUE TITLE
Instance selector not deterministic?

### ISSUE THREAD

**Issue by SakibSaikia** [baldurk/renderdoc#712]
I am investigating a draw batch issued via DrawIndexedInstancedIndirect (DX11) across two different passes (depth & geometry) in the same frame. I am using the Instance selector box in the MeshOutput pane to investigate the individual instances in the batch. 

![image](https://user-images.githubusercontent.com/8186559/28940488-e3166456-7862-11e7-8efb-57acda2b457b.png)

However, the individual instances between the two batches do not match up when viewed through the VS Output pane. -- what is Instance 5 in the depth pass is Instance 1 in geometry pass.

Since, I am using SV_InstanceID to index into a structured buffer for the instance transforms, etc. and the structured buffer itself seems identical, I believe the execution itself is correct. So, perhaps the instance selector in Renderdoc is not tied to SV_InstanceID and is therefore unreliable for investigating the index of the instance in the batch?

However, I am investigating a rendering bug and this could be related to that. I found this behavior weird and wanted to make sure if it was an issue with Renderdoc or otherwise. It will definitely help me understand my bug better.

Additional Info:
Renderdoc v0.34 / DX11 / Windows 10 / Nvidia GTX 960 / Driver 382.53

Let me know and I can share the capture with you.

**Comment by baldurk** [comment]
The instance you select in the mesh output should definitely correspond to SV_InstanceID. There are some subtleties around GS/tessellation output where each instance can have a different amount of data, where there might be bugs, but if it's just VS output then it should be identical.

You say you're fetching the information from a structured buffer - how is that buffer filled? If you're filling the buffer with GPU work that uses atomic counters, or append/consume buffers, then the order is not deterministic and will vary. Each time the frame is replayed, the buffer may be filled in a different order - which might not matter to you and might be fine for your algorithm if it's order-agnostic, but will mean the debugged intermediate will be different. The mesh output is fetched when the event is first selected and remains fixed after that, so this means that although you won't see the variation anymore the frame will be replayed at least once if you select one event, then another so the variation will happen between two events.

If you can share the capture with my then I can look into this, as it does sounds weird.

**Comment by SakibSaikia** [comment]
I've emailed you the link to the capture. The events in question are EID 2637 and 6986.

Yes, the structured buffer is filled with GPU work using atomic counters. This happens in the beginning of the frame (before any rendering work).

**Comment by baldurk** [comment]
OK yes, I see how it works. Then like I say this is expected behaviour - if you jump to the event filling out the buffer at EID 583 and open the buffer, then if you quickly jump back/forth to a different draw (like 587 below will do), you'll occasionally see that the first few results re-arrange.

This is because the atomic counter work is non-deterministic and can insert in different orders. Each time renderdoc replays the frame internally it has a chance to get a different result, and if it gets a different result for each of the mesh-output fetch processes, then they won't agree.

If the mesh output wasn't cached, you could see the instances jump around even, but because it's cached then you might find that the results are the same, or you might get unlucky and find they're different.

This isn't really fixable in RenderDoc I don't think, so the best you can do as a workaround is to reload the capture if you find the results were different. E.g. for me when I tested it, the buffer ended up being the same so the instances were the same.

You could add a debug mode to your code that runs deterministically (like 64 dispatches of 1 thread, instead of 1 dispatch with 64 threads), but that's probably not worth the effort.

**Comment by SakibSaikia** [comment]
Ok, I think I understand. Renderdoc replays the entire frame upto the point of the selected event, right? So, although I am going back and forth between two events which occur *after* the atomic operations, but in effect, I am executing *everything before* it including the atomic operations and hence different results?

How will reloading the capture help in this case? Is it because of the caching you mentioned?

Thanks.

**Comment by baldurk** [comment]
Yes you've got it exactly right, every time you change to a different event, RenderDoc restores the state at the start of the frame and replays again from the start, even if you're going between events all the way at the end. This ensure there's a clean slate and that no effects from later in the frame affect the visualisation earlier in the frame.

At some long-distant point in the future, I'd like to try setting 'checkpoints' part way through the frame, so that replaying forward and backwards doesn't have to do a lot of redundant work - but just needs to keep track of what could have changed between the events, and reset that to a known-good place. However right now it always replays everything.

Reloading might work since there's a chance that the atomic operations will work out the same for both drawcalls, depending on luck and GPU scheduling and everything. Reloading the capture clears the caches that I mentioned so it will re-fetch the mesh output for the draws when you select them, so each time you can try again to have the buffer work out the same for both drawcalls.

**Comment by SakibSaikia** [comment]
Got it. Thanks again for your stellar response!
