### ISSUE TITLE
Feature (VK): Show more information directly in API Calls list

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#719]
Currently, when looking at the details of a single vkCmdDraw in the Event Browser, in the API Calls pane you get a list of all the state calls right before it, but unlike the entries in the Event Browser these do not show any details about their parameters:

![renderdoc_idea_1](https://user-images.githubusercontent.com/130929/29271125-457087ea-80fa-11e7-9984-15741654e806.PNG)

Details of the parameters are only available if you expand:

![renderdoc_idea_2](https://user-images.githubusercontent.com/130929/29271132-4ed894f8-80fa-11e7-8e8c-dd2ab7339b98.PNG)

It would be nice if they would display directly like: 

    vkCmdSetStencilCompareMask(VK_STENCIL_FRONT_AND_BACK, 255)

in the API Calls pane so you didn't need to expand them for most common uses.

**Comment by hrydgard** [comment]
This would also slightly reduce the need for https://github.com/baldurk/renderdoc/issues/678 .

**Comment by baldurk** [comment]
There are a couple of issues to tackle with this.

One is that the API events are just auto-generated entirely from the debug text the serialiser spits out, there's no concept of which parameter means which or what data is contained. Coming Soon&trade; there's going to be a new serialisation system which will give more rich information, but right now it's not worth doing a bunch of string parsing to figure it out.

The second is just one of pragmatism, the drawcalls have in-lined information because there's only a small(ish) number of draw functions and each one can have the important parameters manually in-lined in the text. Doing that for every function call though is a large amount of work especially since not all functions have nice easy concise parameter representations - e.g. the vkCmdBindDescriptorSet call just below. Right now I don't think this is going to land on my priority list.

I'd rather go back a step first and figure out what workflow you need where you want parameters visible in-line. For example are you trying to locate where a particular state was changed? This would be better and more easily address by being able to search across the frame for a given pattern, or find the EID where any given state element was last changed.

**Comment by hrydgard** [comment]
Fair enough, I had no idea if it was a lot of work to do or not. I was simply trying to check if and where the stencil state parameters changed in a list of draws or not, in order to debug some lazy state tracking, and that involved a lot of expanding those little tree nodes. Being able to search for where a particular state changed would address this particular use case fairly well.

**Comment by turol** [comment]
One related small improvement would be to auto-expand the first level of things in the API Inspector when selecting an event where there's just one sub-event. For example when I select vkCmdBeginRenderPass call I almost always want to expand it in the inspector so I can actually see what RenderPass object it is.

**Comment by baldurk** [comment]
That's possible to do, although if the original issue were addressed and the un-expanded view looked like this:

![image](https://user-images.githubusercontent.com/661798/37462243-29da4a9c-2849-11e8-8087-114aa778016c.png)

would that still be as much of an issue?

**Comment by turol** [comment]
I think that might be sufficient but I'd have to test it in action to be sure.

**Comment by baldurk** [comment]
As part of a larger event browser and API inspector refactor this has been implemented. API calls now show in-line the most significant parameters (the same as drawcalls have shown index/instance counts without offsets), and the event browser can now be filtered to include more than just draws:

![image](https://user-images.githubusercontent.com/661798/124173600-2c23cc00-daa3-11eb-92ad-495164743b14.png)

The same parameter information is still available by expanding out the calls, this only affects the summary line when unexpanded.
