### ISSUE TITLE
Mesh Output view doesn't work when using min16* types in HLSL

### ISSUE THREAD

**Issue by shessel** [baldurk/renderdoc#720]
When using min16 precision types in HLSL several Mesh Output panes don't work. The only thing that shows up is the index buffer in the VS Input pane.

[min16.zip](https://github.com/baldurk/renderdoc/files/1222932/min16.zip) contains a minimal .fx file for repro (adapted from Direct3D11Tutorial\Tutorial07) and a log.

Tested using v0.90.

**Comment by baldurk** [comment]
Thanks for the nice repro case. I've added support for min precision (min16/min10 etc), although it's only really in name, since AFAIK D3D's min precision only affects variables within the shader, anything externally facing just gets promoted to 32-bit. At the least, constant buffer values are still expected to be 32-bit, I guess inter-stage stuff could be optimised to 16-bit if the implementation allows, but the mesh output uses stream-out which promotes things to full float.

It's fixed on v0.x so the next v0.x nightly build should work, let me know if you have any more problems.

**Comment by shessel** [comment]
Thanks for the fast response! I Just tested by building from source and it works fine.

If if I put in 16-bit values using an input layout like this:
D3D11_INPUT_ELEMENT_DESC layout[] =
{
    { "POSITION", 0, DXGI_FORMAT_R16G16B16A16_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
    { "TEXCOORD", 0, DXGI_FORMAT_R16G16_FLOAT, 0, 8, D3D11_INPUT_PER_VERTEX_DATA, 0 },
};
at least the shader disassembly shows up as using min16f types instead of def32/min16f as def32 and renderdoc also shows the format correctly in the Input Assembler view.

I gathered my modifications into [Tutorial07Modifications.zip](https://github.com/baldurk/renderdoc/files/1227673/Tutorial07Modifications.zip). You can apply it on top of the Direct3D11Tutorials/Tutorial07 folder from https://github.com/walbourn/directx-sdk-samples.

I also have a follow up on this:
When using the pixel shader debugger, values from 16-bit interpolators get set to all zero. In the example I attached it's v1 (TEXCOORD) and v2 (COLOR).

**Comment by baldurk** [comment]
I tried on the latest build but I can't repro that pixel shader debugging issue - for me the pixel debug values come out fine. I tried on both the min16float.rdc you attached originally, and on a newly compiled version from that tutorial + your modifications. Can you send the .rdc you're debugging and a pixel that isn't working for you? Also just to be sure, can you try with the latest v0.x nightly build so we're both using the same source revision.

About the vertex input stuff - I think this would still be only used internally by the driver, it doesn't change what datatypes are valid for the input layout. It's totally valid to pass `DXGI_FORMAT_R16G16B16A16_FLOAT` input data to a shader that declared a `float4` input, and this is quite common for most vertex inputs since it's rare to need full 32-bit precision. The shader will just read the half data and convert it to full floats after reading in the shader - with the min16float hint the compiler can optionally skip that conversion and pipe it into further half computations. Since the shader is compiled independently of the input layout description I think the `min16f` annotations are just indicating that it's declared to _possibly_ accept 16F data without change.

The `{min16f}` vs any other type of disassembly annotationse I don't really understand (and it's not documented AFAIK). In the same commit I switched renderdoc's disassembly to just use `{min16f}` everywhere since the `as def32` was just a lot of noise, and it's not clear where it's applied and where it's not.

**Comment by shessel** [comment]
Sure thing, here's [log](https://github.com/baldurk/renderdoc/files/1227846/pixelShaderDebug.zip) I captured with the 32bit 2017-08-15 nightly.

Any pixel will do, here's a screenshot of the debugger for pixel 425, 420
<img width="960" alt="pixelshaderdebug" src="https://user-images.githubusercontent.com/13854012/29359181-e2db4d1a-827d-11e7-8293-60714d440761.png">

Ah, I see, thanks for the clarification. In our experience AMD cards tend to actually take the 16 bit hints seriously (:

**Comment by baldurk** [comment]
Hmm, unfortunately I still get normal shader debugging. I tried on a windows 10 pc (since on my normal win7 pc the min precision stuff won't be active) and with nvidia/amd, but no luck. I tried the 32-bit nightly but it behaved the same.

What hardware/driver version are you on? try updating drivers if there's a newer one available.

My best guess aside from driver wonkiness is that when I run a special fragment shader to gather the interpolator inputs for the shader debugging, there's a signature mismatch because I declare the inputs as float4 instead of min16float4. However I don't get any warnings from the D3D debug layer, and it seems to work fine in every case I can test.

Would you be up for diving into the code if I told you where to look, and breakpoint/add some hacks to test the theory?

**Comment by shessel** [comment]
A colleague of mine checked on his machine with an Nvidia Titan X and it worked. For me on an R9 Fury it doesn't. I'm leaving for a vacation now, but I'll follow up when I'm back end of August. If it's not the driver, then I can help with checking the code, as you suggest.

**Comment by Ingrater** [comment]
Colleague here. We updated the garphics driver for the R9 Fury and the shader debugging is now working correctly. You can close this issue as fixed. Thank you very much for the quick fix! RenderDoc is really an awesome peace of software.

**Comment by baldurk** [comment]
Interesting! I'm glad it's fixed.

Thanks again for the clear & easy repro, and if you run into any other issues then my door is always open :smile:

**Comment by shessel** [comment]
Great, thanks again for the quick fix!
We'll be sure to do that.
