### ISSUE TITLE
glBindVertexBuffers(0, 1, NULL, NULL, NULL); crashes

### ISSUE THREAD

**Issue by asylum2010** [baldurk/renderdoc#754]
According to the OpenGL wiki the array buffer can be decoupled from the VAO if I call glBindVertexBuffers(0, 1, NULL, NULL, NULL) when creating it.

RenderDoc tries to read these NULL pointers and crashes.

**Comment by baldurk** [comment]
The spec does indeed allow for that, but I'm not entirely clear where the crash lies. A fix for this was submitted in PR #351 and as far as I can tell it's still protected. There are checks [here](https://github.com/baldurk/renderdoc/blob/v0.x/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp#L4302) and [here](https://github.com/baldurk/renderdoc/blob/v0.x/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp#L4180-L4185) where the pointers would otherwise be dereferenced, so on the face of it I can't see where the read of NULL would be.

If you have a repro of this crash can you give more information about where exactly the NULL read happens, and if possible share a program that exhibits the crash?

**Comment by asylum2010** [comment]
Here's the crash in renderdoc. You can easily repro it if you create a VAO with this call.

![rdoc](https://user-images.githubusercontent.com/937925/30809782-4a2630ee-a203-11e7-887f-de3f4f54e8de.png)

**Comment by baldurk** [comment]
Oh! I'm blind - the check for offsets/strides is backwards. It should be `buffers ? (uint64_t)offsets[i] : 0` and similarly for `strides`. I'll fix this, thanks for the report.

**Comment by baldurk** [comment]
I believe that should fix the crash on v0.x and v1.x branches. Can you let me know if you still have trouble with the next nightly build? Or if you're able to build locally and test all the better :).

**Comment by asylum2010** [comment]
The fix you suggested actually solved the problem, so I'm pretty sure it will be fine.
