### ISSUE TITLE
Crash when using separate shaders/program pipelines

### ISSUE THREAD

**Issue by asylum2010** [baldurk/renderdoc#761]
Interesting that this issue surfaced after I actually fixed my buggy code:
Link to the relevant part of my code (if you want to actually compile it I can prepare a package):

https://www.dropbox.com/s/67a9rljdnif46qp/main.cpp?dl=0

And RenderDoc call stack with variables. As you can see it tries to query a vertex input as fragment output:

![somethingwrong](https://user-images.githubusercontent.com/937925/31020784-3a460544-a534-11e7-9d2f-a39273120eaf.png)

**Comment by baldurk** [comment]
Hi, if you could make a compilable package that would be useful.

This code is intended to save and restore the variable bindings of a program - vertex input locations, and fragment output locations, both of which can be changed at runtime so might need to have state saved.

As you point out it won't always be valid, since any program that doesn't have a vertex or fragment stage its inputs or outputs won't have a location to fetch or set. However the GL spec says that querying for a variable name that doesn't exist returns `-1`. It also says that if the program doesn't contain a vertex or fragment shader (as appropriate for the function call), it will generate no error and return `-1`. That's why the code checks that the location is `>= 0`, so that if it does happen to return `-1` then it just skips that variable. It avoids painful queries to try and figure out what subset of shaders a program might have.

So although it's not intuitive, I'm not sure I see a problem with RenderDoc's code here. If it's crashing inside the driver that sounds like it might be a driver bug. If you give me a program I can run and check myself I'm happy to investigate, but I don't think this sounds like a renderdoc issue.

**Comment by asylum2010** [comment]
Package is here: https://www.dropbox.com/s/quhcumapwlfvadf/FOR_RENDERDOC.zip?dl=0
Card is AMD Radeon R7 360

It might be a driver bug, but still it's an invalid usage of the API. Perhaps there is a way to query whether a program has fragment shader. If not, then you can still keep track of what kind of shaders were attached to a program.

**Comment by baldurk** [comment]
I also get a crash on the same call with a RX 480 and latest drivers. I've made a simple repro program that exhibits it, so I'll report this to AMD to investigate.

I'm not sure what invalid usage you mean though. Like I mentioned before, the GL spec explicitly states that calling `glGetFragDataLocation` for a program with no fragment shader returns -1 and generates no error.

**Comment by asylum2010** [comment]
I only read the reference, but it didn't mention this scenario. It says that if there is no output with that name, then it returns -1 (so it assumes the existence of a fragment shader). It is possible that the spec. is more precise on this, idk.

**Comment by baldurk** [comment]
This has been reported to AMD to be fixed, for now I'm not planning to workaround this in renderdoc.
