### ISSUE TITLE
Invalid API usage for vkCmdCopyQueryPoolResults() while replaying

### ISSUE THREAD

**Issue by jozefkucia** [baldurk/renderdoc#765]
RenderDoc doesn't handle `vkCmdCopyQueryPoolResults()` correctly when the command is used to copy query results from the previous frame. While replaying, RenderDoc tries to copy query results from a query which wasn't issued. This produces the following validation error:

`DS(ERROR): object: 0xb68cf0 type: 6 location: 7123 msgCode: 15: Requesting a copy from query to buffer with invalid query: queryPool 0x161, index 0`

This breaks replays completely with Nvidia drivers when `VK_QUERY_RESULT_WAIT_BIT` is used.

The issue can be reproduced with slightly modified `cube` demo: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/c0c8b810094f8269652f3ca19da17253c9473aa2

As a workaround RenderDoc could simply issue a query before the `vkCmdCopyQueryPoolResults()` call (if it wasn't issued).

**Comment by baldurk** [comment]
This is a tricky one. The solution you propose is right, but the implementation is the hard part.

For the first part, issuing a query isn't trivial when it comes to occlusion and pipeline stats since it requires a draw (with all the dependencies for that), but that's solvable. The harder part is figuring out which queries were issued.

I already do a fair amount of active tracking to see which descriptors are used in which descriptor sets, I'm hesitant to add even more tracking to determine which queries in a query pool have been modified and when.

I'm considering just filling out the query pool with dummy results when it's created on replay, and then allowing that to be overwritten by the 'real' results if they are produced within the frame. The one problem with that is the query results could affect rendering - consider using `vkCmdCopyQueryPoolResults` on an occlusion query as the input for an indirect draw, perhaps modified through a compute shader. For now I might just hope that doesn't happen - saving and restoring query pool values would be error prone at best :disappointed: .

**Comment by jozefkucia** [comment]
FWIW, I need this for timestamp queries.

**Comment by baldurk** [comment]
This should be fixed on v1.x branch now with that commit - I tested with your repro case and it fixed it for me on nvidia. Please let me know if it works for you or not.

**Comment by jozefkucia** [comment]
It works for me. Thanks for the fix.
