### ISSUE TITLE
qrenderdoc causes GPU hang while replaying captured frame on ANV

### ISSUE THREAD

**Issue by jlegg0** [baldurk/renderdoc#772]
When switching which events I'm viewing in qrenderdoc on a Vulkan frame capture, I often see the Intel HD Graphics 530 GPU hang.

This might not be a bug in renderdoc. If this appears to be driver bug I can report it to the DRM/Intel project on bugzilla.freedesktop.org instead.

# Steps to reproduce:
1. Launch qrenderdoc using an ANV (the Intel Linux Vulkan driver) ICD: `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json qrenderdoc`
2. On the Capture Executable tab, set the Executable Path to the path of vulkan-smoketest, for example `/usr/bin/vulkan-smoketest`.
3. Press Launch
4. Press F12 to capture a frame
5. Press the escape key to exit vulkan-smoketest
6. Select the captured frame
7. Switch to to the Texture Viewer tab
8. Expand the Colour Pass and vkCmdExecuteCommands rows in the Event Browser
9. Press the end key to select the last event (vkQueuePresentKHR())
10. Press the up and down arrow keys to repeatedly scroll through the last 6 events of the trace
11. After a few iterations, the device is lost.  (There doesn't seem to be a specific call that causes the GPU hang in a trace every time it is viewed, but flipping through them like this for less than minute is enough to hit the bug

Alternatively, you can load a previously captured frame such as this one: 
[vulkan-smoketest_2017.10.10_17.55_frame68.zip](https://github.com/baldurk/renderdoc/files/1375824/vulkan-smoketest_2017.10.10_17.55_frame68.zip),  instead of steps 2 to 6.

# Results
This appears on the terminal that launched qrenderdoc:
> Log     - QRenderDoc - renderer created for "/tmp/RenderDoc/vulkan-smoketest_2017.10.11_12.46.17_frame70.rdc"
> vulkan/anv_queue.c:46: execbuf2 failed: No such file or directory (VK_ERROR_DEVICE_LOST)
> vulkan/anv_queue.c:216: vkQueueSubmit() failed (VK_ERROR_DEVICE_LOST)
> Error   - Assertion failed: 'vkr == VK_SUCCESS' (vkr=VK_ERROR_DEVICE_LOST, VK_SUCCESS=VK_SUCCESS)

The last line is repeated several times. It is printed more times if you interact with the UI.
The textures shown in the texture viewer stop updating, but the status bar still contains the text "No problems detected.".

Sometimes a GPU crash dump is saved to /sys/class/drm/card1/error. Here is one:
[error.txt](https://github.com/baldurk/renderdoc/files/1375661/error.txt).

# Expected results
The texture Viewer should represent the state of the Vulkan images at the selected event whenever possible, and be clear if there was an error. A GPU hang might be acceptable if the capture executable was risking a GPU hang, but ideally qrenderdoc should be resilient in the case of capture executable bugs as it is used as a debugger. I'm not convinced vulkan-smoketest or other applications that cause this have such bugs however, in which case renderdoc shouldn't hang the GPU.

# System
I can reproduce this on this system:

Parameter | Value
---|---
Renderdoc version | commit 2f728480566e4cfdd81de5435ba5c57c0e5d4525 (v1.x branch), with a `#pragma GCC diagnostic ignored "-Wformat-truncation"` added before an intentionally dodgy snprintf call at renderdoc/serialise/utf8printf.cpp:1441 (GCC 7.2 warns the buffer is too small for the format string, and it is compiled with warnings as errors enabled.)
Processor | Intel® Core™ i7-6700K CPU @ 4.00GHz × 8
Graphics | Both an Intel® HD Graphics 530 (Skylake GT2) and an AMD RX 480 (I'm not using the AMD GPU for Vulkan when reproducing the bug, by setting a VK_ICD_FILENAMES that doesn't include the radeon ICD)
Graphics Driver | Mesa 17.2.2
OS | Fedora 26

I don't see any similar problems when using the AMD GPU.

**Comment by baldurk** [comment]
Thanks for the detailed report! that's a lot of good info. My intel machine has a Broadwell chip but I'll test to see if I can get it there anyway. I do have that exact chip but no easy way to test mesa. Though maybe I can just boot off a portable install...

Can you try one thing - are you able to reproduce this hang on a capture that doesn't use secondary command buffers? There's a lot of things that this could be due to, but I'd like to know if I can eliminate that as it reduces the scope a fair amount. E.g. testing with any of [Sascha's demos](https://github.com/SaschaWillems/Vulkan).

**Comment by jlegg0** [comment]
> are you able to reproduce this hang on a capture that doesn't use secondary command buffers?

No - I tried a few of Sascha's demos, but saw no GPU hangs.

**Comment by baldurk** [comment]
Just to let you know I've repro'd this on mesa 17.2.3 with my HD 6000, so I'll continue to investigate.

**Comment by baldurk** [comment]
There's something funny going on here - it looks like the precise repro was to select an event part-way through a `vkCmdExecuteCommands` so that a special partial-recorded primary command buffer would execute the secondaries in the capture, then select an event after it (like `vkQueuePresentKHR`) so that they are replayed on the original command buffer. Doing this seems to break.

However I'm not entirely sure that's illegal, I'm a little unclear on the spec implications of omitting `USAGE_SIMULTANEOUS_USE_BIT` and when you're allowed to re-execute the same buffer. For now, I've added that bit since it's a conservative and at worst a bit less efficient. Let me know if that fixes the problem for you, in the meantime I'll see if I can determine for sure if it's a driver bug or not.

**Comment by jlegg0** [comment]
That change works for me.

**Comment by baldurk** [comment]
Thanks for verifying!
