### ISSUE TITLE
Mesh Viewer: glBeginTransformFeedback Error because TF is already used by the game.

### ISSUE THREAD

**Issue by michaelrgb** [baldurk/renderdoc#773]
A draw call used in the game is preceded by a glBeginTF call, and its corresponding glEndTF call is in the next API Inspector group of commands, just before the next draw call. Therefore the Mesh Viewer is unable to use TF to get the mesh, because the game was already using it.

We could just check if TF is active in InitPostVSBuffers() and end it, but that might cause further errors when glEndTF is called in the following event group.

Do you have a high-level plan to solve this and I can try to submit a PR?

**Comment by baldurk** [comment]
So the GL back-end _should_ already be tracking active transform feedback, because e.g. you could get in the position of calls like:

```
EID X: glBeginTransformFeedback
EID X+1: glDrawElements
EID X+2: glDrawElements
EID X+3: glEndTransformFeedback
```

Where then selecting X+2 and X+3 would begin TF twice, but never end it. So there should be tracking - see `m_ActiveFeedback` - which detects this case and then manually calls `glEndTransformFeedback` if it's leftover as active. The same thing applies for queries and conditional renders.

So I think we should just be able to extend this to check and stop the TF inside InitPostVSBuffers() so that we can use it ourselves. I don't think there're any problems with stopping it for subsequent events - the only thing that can be replayed after that point is whichever draw is selected, and it doesn't matter if TF is incorrectly disabled for that - AFAIK TF only has side-effects for subsequent work that might use the data, not in itself for the draw. By the time we select a later event then we're replaying from the start of the frame so it just gets restarted again.

Maybe there's something I'm missing, but I think it might just be as simple as adding this somewhere:

```
    if(m_ActiveFeedback)
    {
      m_Real.glEndTransformFeedback();
      m_ActiveFeedback = false;
    }
```

Give that a try and see if you run into problems.

**Comment by michaelrgb** [comment]
> By the time we select a later event then we're replaying from the start of the frame so it just gets restarted again.

Makes sense! Fixed this with a 2-liner using WrappedOpenGL::glEndTransformFeedback().
