### ISSUE TITLE
How to create a depth map using renderdoc?

### ISSUE THREAD

**Issue by tyzaizl** [baldurk/renderdoc#777]
Is there any idea or references about using renderdoc capture log to create a depth map?

thanks

**Comment by baldurk** [comment]
Sorry I don't understand what you are asking. A RenderDoc capture only contains the resources used in the frame from the captured application, it doesn't create any other resources or add/change any graphics work (except stuff internally used to analyse the capture).

**Comment by tyzaizl** [comment]
sorry about that. What I mean is that does RenderDoc capture the depth-buffer (like GTA5 depth-stencil buffer) ?

**Comment by baldurk** [comment]
Render targets like that aren't directly captured. They are reconstructed during replay in the UI by replaying the same commands as the original program used to render.

Also I can't help you if you are working with a program you don't own like GTA5. I only help with people debugging their own code.

**Comment by NagabhushanSN95** [comment]
@baldurk Computer Vision researchers are using data generated by Games since they're very rich compared to opensource games or scenarios we can build ourself. It looks like GTA V allows researchers to do this as long as they don't use it for commercial purpose. GTA V has been used by [this](https://link.springer.com/chapter/10.1007/978-3-319-46475-6_7) and [this](https://arxiv.org/abs/1806.07381) papers. 

@tyzaizl might have asked in that context. You may also consider helping such researchers :)
