### ISSUE TITLE
Linux: Inconsistent GUI Information about attaching to running processes

### ISSUE THREAD

**Issue by MeFisto94** [baldurk/renderdoc#788]
Hello Guys!
The following applies to both v0.9 and the nightly build as of 25.10.2017:
On Linux, injecting into already running processes is not supported, however the UI does not clearly communicate that.

I'd like to propose that the File->Inject into Process is removed/disabled or triggers a message box, so you don't have to look into the logs just to notice that this feature is not yet supported.
Furthermore the Inject into Process Window is missing the Name and Window Titles.

What do you think?

Edit: By looking at the code I can see that I am missing xdotool, however tools like OBS still get the Window Name, so that could be investigatable. I have no clue why extracting the cmdline fails, though

**Comment by baldurk** [comment]
Yeh this is something I don't do very well, making it visible at the UI level which features are or aren't available.

I should be able to do something to show that process injection is only available on windows. I think it's theoretically possible to implement on linux, but given that injecting is almost always the wrong thing to do it's very low priority to actually implement.

**Comment by MeFisto94** [comment]
Sorry for the late reply. 
For another project i stumbled over: https://github.com/gaffe23/linux-inject however it seems that it's not as reliable as you'd wish it to be.

Do you have any clue why showing the processname fails? (It doesnt matter though if one wont support injection, it's just a side note)

**Comment by baldurk** [comment]
That seems like an interesting project, but the license is GPL so I would not consider using it and cannot look at it any closer at risk of being infected.

The process name failure is a typo on my part creating the `/proc/<pid>` path, I've fixed it now. The requirement for xdotool is just for my sanity - xdotool is built on top of xlib so I could do all the same queries myself, but for now it's simpler to rely on the external tool for the queries. If someone wants to, they can PR a pure xlib solution [to the repository](https://github.com/baldurk/qprocessinfo) - since that should probably be a safe library to depend on.

**Comment by baldurk** [comment]
I've hidden the menu item, as it didn't seem sensible to keep it permanently disabled as even a tooltip won't always be noticed.

I also fixed up a couple of other things like shader debugging or pixel history that weren't platform-gated but were API-gated, and it wasn't clear why they didn't work.
