### ISSUE TITLE
Are MinGW apps supported?

### ISSUE THREAD

**Issue by oskidan** [baldurk/renderdoc#792]
Hi, 
Is it possible to use Renderdoc with those apps, which have been built with MinGW 64 from MSYS2 distribution?
I get this error when I try debugging a MinGW 64 app:
```
RDOC 011148: [14:53:06]    win32_process.cpp( 458) - Log     - Running process D:\Fun\GLFun\shadows_2d\build\shadows_2d.exe
RDOC 011148: [14:53:06]    win32_process.cpp( 518) - Log     - Injecting renderdoc into process 22600
RDOC 011148: [14:53:06]    win32_process.cpp( 330) - Error   - Error injecting into remote process with PID 22600 which is no longer available.
Possibly the process has crashed during early startup, or is missing DLLs to run?
RDOC 011148: [14:53:06]    win32_process.cpp( 852) - Error   - Can't locate renderdoc.dll in remote PID 22600
```
Thanks, -- Oleksii

**Comment by baldurk** [comment]
There shouldn't be any problems regardless of the toolchain, renderdoc hooks calls directly to the target APIs so any valid win32 executable should work.

The error message suggests that the application is exiting immediately on launch. Have you checked that it has everything in the environment there that it needs to run? If you double click on the exe in the folder, does it launch normally?

**Comment by oskidan** [comment]
I'm sorry, it was false positive. The issue was that MinGW-specific DLLs were not added to `PATH`. Although I find it surprising that the application stopped showing the error dialog abut missing DLLs, when launched by RenderDock.

**Comment by baldurk** [comment]
The missing DLL popup error dialog is provided by windows directly if you're running the exe through explorer. Since RenderDoc launches the exe through `CreateProcess` there's no built-in dialog, and I don't think there's a way to distinguish between a program that crashed for other reasons, and a program that failed to initialise properly. That's why RenderDoc's error message that you pasted originally suggests that it _might_ be due to missing DLLs but might be something else.
