### ISSUE TITLE
User experience when capture crashes application (Windows)

### ISSUE THREAD

**Issue by avoroshilov** [baldurk/renderdoc#801]
Hello!
When I am trying to capture my Vulkan application using RenderDoc, and it crashes. The crash is separate issue though.

When the crash happens, I am getting strange behavior from RenderDoc: it loses focus and brings some other (completely unrelated) app on top, and when I alt-tab into RenderDoc again, it is locked due to modal dialog telling that capture failed. **However that dialog is not visible, and RenderDoc is simply unresponsive**, in a manner when you press outside of the modal dialog. The only way to bring the dialog back to the visible stat, press Ok and resume RenderDoc functionality - is by exactly **minimizing** the app that was brought on the top.

After this is done, and RenderDoc resumes functionality, if I try to view the diagnostic log, I am having two issues:
1. Default viewer that is associated with the log files cannot handle the line endings in the log (seemingly they are not correct Windows line endings).
2. It was hard to locate the log file to "Open with..", because there is no option to open log file location. Probably a button somewhere in the "About" screen that leads to the log file location would be helpful.

Thank you!

**Comment by baldurk** [comment]
I think this is a combination of "I can't fix it" and "it's already fixed".

The focus behaviour is weird - I can reproduce that situation where you can switch to the application without seeing the message box, but I think it must be some .NET implementation detail.

On the Qt UI the message box that appears is implicitly linked to the application. You can't alt-tab back to the application without getting the message box on top of it. Since the .NET UI is gone now, this should go away in the next major version.

Also on the v1.x branch I've switched to native line endings for this reason, because by default notepad still doesn't handle anything but CRLF line endings.

**Comment by avoroshilov** [comment]
I can confirm that in 1.x:
1) The line endings are digested correctly by the notepad.exe
2) I do not get the locked RenderDoc with the new UI
3) Still cannot find any explicit mentions of the directory where the diagnostic log file is stored - but that's very minor given that it now could be opened correctly without the need to "Open with.."
