### ISSUE TITLE
Arrays of nested structs not supported in buffer viewer

### ISSUE THREAD

**Issue by MasayoshiMiyamoto** [baldurk/renderdoc#805]
I found incorrect view of a structured buffer bound to a DX11 compute shader, when the struct has a nested struct and its array.
struct A {
 ...
 struct B {...};
 B data[8];
};
StructuredBuffer<A> a;
data[1], data[2], ... were not in the view, and a[1], a[2],... in the buffer were not correctly displayed.
My version is 0.91. 
Thanks!

**Comment by baldurk** [comment]
Thanks for reporting this. I've repro'd it and there's a small bug to fix internally that stops the array count of `data` being passed up to the UI.

There's a deeper problem though - at the moment the way the buffer format is specified, it doesn't have a way to specify arrays-of-structs like this. The elements have to be flattened, which means the only workaround would be to 'unroll' the nested struct.

I think I can probably add support for nested structs in the format parsing but it will require some more invasive changes on the UI so it might take a bit longer.

**Comment by NPatch** [comment]
Any update on this? I've stumbled upon the same thing.
Mine is a simple case. The struct is a sequence of 16 floats but even if I say float[16] in the format, I get 6-7 rows even though there should be 26.

**Comment by baldurk** [comment]
Fixing this will require a bit of a refactor to support nesting of structs and an actual parser rather than just line-by-line declaration parsing, which is why I haven't worked on it yet.

Can you give more details about your problem? Translating a simple non-nested struct to an array should work fine.

**Comment by NPatch** [comment]
I ended up using a temp flat float array to set the Buffer, but on the shader I still use the struct to read them. At least in RD, I can now see the flat array using "float" as format. It's just not as comfortable to read since you're looking at a flat array with a stride. Btw is there a way to set the row stride?

I'm using a ComputeShader to do some effects and one of them has a loop inside which uses offsets on textures. The loop is dependent on a repetition variable and each rep uses 16 offsets for sampling. So I precalculate the array of offsets which is also dependent on the reps var and feed it to the CS as a structured buffer of struct of 16 floats with distinct names. I could use a float[16] instead but it's not easy to read/debug the function if you end up using indices to query offsets instead of distinct names.

At the moment I'm trying to debug the algo of the effect and I'm checking if the recalculation of those values in the engine editor after changing some properties, feeds the correct values back to the ComputeShader when the CommandBuffer is resubmitted.

**Comment by baldurk** [comment]
I'm afraid I don't follow. Does your structured buffer have a base struct that's 16 named float? If that's the case, can't you just use the struct itself as the base definition? Or do you mean that you have a parent struct, and then an inner struct, where the inner struct contains 16 floats.

Can you paste the specific definition of your structured buffer? I'm trying to understand what your situation is. The case that doesn't work which this bug is about, is having an array of an inner struct within an outer struct, that can only be properly represented with proper struct nesting. There's no way to set the row stride at the moment, although that could be a useful thing to be able to specify.

**Comment by NPatch** [comment]
Using Unity. I have a struct in a C# script where I calculate the values and another struct in the Compute shader with the same layout.
```
struct Spread {
	float Left_0_25;
	float Left_0_5;
	float Left_0_75;
	float Left_1;
	float Right_0_25;
	float Right_0_5;
	float Right_0_75;
	float Right_1;
	float Top_0_25;
	float Top_0_5;
	float Top_0_75;
	float Top_1;
	float Bottom_0_25;
	float Bottom_0_5;
	float Bottom_0_75;
	float Bottom_1;
};
```
They were shown as hex,first time I tried to view it in RD. Didn't see any apparent way to switch from hex other than changing the format. When I tried to change the format to show floats, I tried a "float[16]" first but the rows and values were not correct, also incorrect rows when I tried a "float" format. I also tried this struct from brace to brace as the format and it worked but showed less rows than it should.

**Comment by baldurk** [comment]
Thanks, but I'm still not clear on whether that is your _base_ struct e.g. `StructuredBuffer<Spread> mybuf;` or if you have that inside another struct, and whether that itself is an array or not. Can you please post the **full** definition of your structured buffer with all component structs.

If that's the root struct and there isn't anything else, then it should be enough on its own and if you got the wrong data out or not as many rows as you should then it's a separate unrelated bug, nothing to do with this issue.

**Comment by NPatch** [comment]
Ok I should probably move this to a separate thread then. It's as you said StructuredBuffer<Spread> and it's the base struct. But I can't get a proper viz of the data either due to values or due to row count being incorrect. Also I expected float[16] to work as they're sequential bytes but it still gave wrong row count and even values if I remember correctly.
I'll try to redo them tomorrow and post a new thread instead with proper examples. Right now I'm going off of my recollection of what happened.

**Comment by baldurk** [comment]
OK thanks, indeed that's a different bug, please open a new issue with some repro case I can use to check with.

**Comment by baldurk** [comment]
This took a while but I've done the necessary refactoring to support this, you should now be able to declare arrays-of-structs using familiar syntax:

```
struct A
{
  float x;
  float2 y;
}

struct B
{
  A as[4];
}
```

And it will be unrolled and displayed as 8 columns - `as[0].x, as[0].y, as[1].x, as[1].y, as[2].x, ...`
