### ISSUE TITLE
Hook without WGL_ARB_create_context way of initialization

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#809]
Currently, Firefox uses `wglCreateContextAttribs` only when `ARB_robustness` is present. This is not the case on many machines, and Firefox falls back to `wglCreateContext`. Unfortunately, RenderDoc refuses to connect to such a context. Would it be difficult to add support for this?

**Comment by baldurk** [comment]
This is a deliberate decision that I'm not going to change. RenderDoc only supports core profile GL, but the only way to be *sure* that the application is actually using core profile is if it calls `wglCreateContextAttribs` and self-declares by passing the appropriate profile bit.

As a concession to pragmatism, I also allow capturing if the profile bit isn't passed as long as `wglCreateContextAttribs` is called - since many applications don't opt-in to core profile but still use modern GL. This can break though since they might then use legacy features, but in my experience it's a very common case so it'd be painful to require the core profile bit.

But I can't allow capturing from `wglCreateContext` because for all I know it's a really old program using fixed function pipeline and other legacy GL features. It would be much too likely to break inexplicably for people who didn't read any docs and expect the whole of GL to work.

If you're already searching for `ARB_robustness`, consider searching for [`EXT_debug_tool`](https://renderdoc.org/debug_tool.txt) which renderdoc reports and (to my knowledge) no other tool does, then switch to the attribs create.

**Comment by kvark** [comment]
Thanks @baldurk for the prompt and detailed response! Your reasoning is sound, and the workaround (checking for `EXT_debug_tool`) is quite interesting.

**Comment by kdashg** [comment]
createContextAttribs(nullptr) and createContext() should be semantically equivalent, so it's disappointing that you'd make this distinction.

**Comment by baldurk** [comment]
They are indeed equivalent, so if I was being strict I would have to disallow capture in **both** cases - since neither of those are actually core profile contexts. It would be entirely legal to `glBegin` / `glEnd` in either context which would at best produce a broken capture, at worst actively crash during the program's execution due to missing functionality...

Like I say though, I ran into a lot of modern GL programs (that used the core profile subset) that were using `CreateContextAttribs` without specifying core profile, so I relaxed the requirements a little to allow them to work and instead drew the line in the sand as "If you're using `CreateContextAttribs` then hopefully you're using modern enough code.". It's not perfect, and some people will use the attribs create and then use legacy GL and get confused as to why it doesn't work. It seemed like the best balance between not blocking applications that would work, while not allowing too many that won't.

In the end I'm giving some leeway, but I can't relax it all the way and allow any application to capture unless I commit to supporting legacy GL.

**Comment by kdashg** [comment]
I really wish you would offer an explicit opt-in instead.
It feels pretty absurd to have to add a CreateContextAttrib(null) call in order to appease your heuristic. We have this branch merged with CreateContext() right now, since we should be able to expect them to be equivalent.

**Comment by baldurk** [comment]
I'm not sure what to say. If you're asking that only contexts with an explicit CORE_PROFILE_BIT should be allowed to capture, I've explained why I don't want to do that. Plus it doesn't seem like it would help you since that would replace a requirement for CreateContextAttribs(null) with a call to CreateContextAttribs({core attribs}). If you mean that there should be another opt-in to say "hey, this CreateContext call is going to be core profile, trust me" then that would require a side-band API that's renderdoc specific, which adds complexity and maintenance burden and will require you to detect renderdoc in order to call that API, which doesn't seem easier than just detecting renderdoc and calling CreateContextAttribs().

If I were to be strict to-the-letter compliant and require a core profile, it would put even more of a burden on you and there'd be no heuristic. The heuristic (such as it is) is just about making it easier on everyone by allowing a bunch more cases to work without any extra renderdoc knowledge.

**Comment by kvark** [comment]
I believe the question is answered in full. Thank you!
