### ISSUE TITLE
Unable to capture Google Chrome on Windows 10

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#810]
Tried the following ways to capture it:
  1. by starting Chrome from RenderDoc UI
    - selecting "Hook into children" checkbox
    - Chrome starts, but none of the children detected by RenderDoc are the GPU process
  2. by starting Chrome separately
    - passing `--gpu-startup-dialog` flag, as recommended in https://github.com/baldurk/renderdoc/issues/228#issuecomment-205340672 (cc @null77)
    - injecting into the GPU process before clicking OK to Chrome's dialog (thus, before D3D11 context is created)
    - injection passes, but after clicking OK Chrome seems to fail to create D3D1 context and tries to re-spawn the GPU process again. Same story is repeated.

Any ideas on what we could do to get a stream? Is this an intentional block by Chrome team?

**Comment by null77** [comment]
Maybe try using the --disable-gpu-sandbox option? I haven't tried to do this in quite some time.

**Comment by baldurk** [comment]
Using `--disable-gpu-sandbox` works for me. It seems like chrome uses `CreateProcessAsUserW` to init the gpu process with low rights - I added support for those functions on v1.x recently (amusingly, since firefox was using them) but that just runs into other problems where the DLL injection fails into that process for unknown reasons. It must be something subtle since attaching VS right after process create without injecting renderdoc also causes the process to die.

**Comment by kvark** [comment]
Works like a charm, thank you!

**Comment by kvark** [comment]
Hmm, I'm no longer able to repeat this trick. Chromium 0.70 reports:
> You are using an unsupported command-line flag: --disable-gpu-sandbox. Stability and security will suffer.

I understand that this is not an issue with RenderDoc specifically, so apologies for bothering you with this. However, many people find this issue in search of an answer, so it would be great to have an updated solution here, if any.

**Comment by baldurk** [comment]
I used chrome for testing EGL capture on windows, and using version 70.0.3522.0 this still works fine for me. It displays that message - which is a fair warning - but it still captures and replays just fine.

Also as you say this is **not** a RenderDoc issue, so shouldn't be open here since there's nothing I can do to fix it. It's not feasible to expect to have instructions for capturing external program in this repository.

**Comment by darksylinc** [comment]
Starting RenderDoc 1.10; it is now possible to capture Chrome on Linux!

Use the following extra cmds:

``
Executable Path: /opt/google/chrome/chrome
Working Dir: /opt/google/chrome/
Cmd Line Args: --user-data-dir=/tmp/mytmpprofile --disable-gpu-sandbox --no-sandbox --disable-gpu-watchdog --use-gl=desktop
```

Unfortunately the ANGLE backend doesn't seem to work (yet? I haven't tried everything) which is what I'm interested in to fix a bug in Chrome
