### ISSUE TITLE
RenderDoc issue with Intel's Instant Access D3D11 extension

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#816]
There is crash issue when using RenderDoc with Intel's Instant Access D3D11 extension.

In order to repro it you can use Intel's example:
https://github.com/GameTechDev/InstantAccess_Tiling

Or run with latest bgfx on Intel GPU. Tthis is commit where it was added:
https://github.com/bkaradzic/bgfx/commit/0e5f3457c3c507ba8836aaa67563be66635f248e

More info:
https://software.intel.com/en-us/articles/tiling-format-for-intel-iris-graphics-extension-for-instant-access
https://software.intel.com/en-us/blogs/2013/03/27/cpu-texture-compositing-with-direct-resource-access

**Comment by baldurk** [comment]
There's no way this will ever be captureable, but I should probably be able to do the same as I do elsewhere and just block the initialisation of the extensions while renderdoc is injected. Due to the clumsy setup though it will mean snooping all CreateBuffer calls to intercept one with the right signature, which I'm not very happy about.

Can I make a pointless complaint here shouted to the void: this is a horrible way to initialise extensions and Intel should have wrapped this in their own proper extension system like the other IHVs do.

**Comment by baldurk** [comment]
I believe that should fix the issue, I've cherry-picked it onto v0.x as well.

The only crash I got was one on shutdown that looked like there'd been some memory corruption - can you please double check that it's sorted with the next nightly build.

**Comment by bkaradzic** [comment]
It doesn't crash anymore. :+1:
