### ISSUE TITLE
No API detected

### ISSUE THREAD

**Issue by Const-me** [baldurk/renderdoc#817]
I’m trying to capture my app.

It launches it OK, attaches OK, but doesn’t do anything, the UI says “Connection established (No API detected)”.

Meanwhile, the app uses both Direct3D 9 (it has a .NET frontend, and D3D9 is used by WPF I’m using for 2D GUI parts), and Direct3D 11 (the app renders complex 3D content into a texture that’s shared with WPF through DXGI surface sharing).

I know my app doesn’t look like a game, it’s actually a CAD app, I’m not creating any swap chains, never call Present, and I only render my stuff on demand when something’s changed as the result of user input.

But still, is there a way to use it with RenderDoc?

Maybe there’s a way to do manual integration, e.g. link with renderdoc.dll, and after I call Direct3DCreate9Ex and D3D11CreateDevice pass these interfaces to renderdoc.dll to have them wrapped in these capturing wrappers?

Thanks in advance.

**Comment by baldurk** [comment]
You should be able to use manual integration, although not of the form 'link to renderdoc.dll'. I think the only missing piece is that without any swapchains, renderdoc doesn't know where the frames start or stop (or call it a 'section of work' if it's not really frames) so it can't generate any frame captures.

You need to use the [in-application API](https://renderdoc.org/docs/in_application_api.html) from your code, to manually start and stop the frame capture from your code rather than relying on renderdoc's handling based on keypress. See the `StartFrameCapture` and `EndFrameCapture` functions. If you have D3D9 and D3D11 active then you'll need to at least pass the D3D11 device into those functions to disambiguate where you want the capture to happen, but you can leave `NULL` as the window.

The "no API detected" is indeed misleading, it's originally from when I found applications might initialise different APIs but then choose on and start using it - I didn't want to mis-report, so I waited until the first presented frame. Obviously this falls down and gives a weird message when you never present any frames. I'm thinking about adding some heuristic like if I see a certain amount of created resources or drawcalls or something. It would still require manual intervention to trigger the capture but at least it could pop up a warning "there's rendering but no presenting. Are you offscreen rendering? see X documentation."

**Comment by Const-me** [comment]
Thanks a lot!

I will try to implement that method tomorrow.

I do render frames, I just don’t present them. Instead, each time I’m done rendering, I call ResolveSubresource to copy my render target texture to the non-MSAA texture shared with WPF. Then in C# code I call D3DImage::AddDirtyRect, and that one does present somehow, with D3D9 API. Apparently, the way WPF presents stuff does not cause RenderDoc to trigger frame captures. And even it would, I’m interested in debugging my own D3D11 rendering, not Microsoft’s D3D9 GUI rendering.

**Comment by baldurk** [comment]
FYI, Latest builds on the v1.x branch now display explicitly that the API is detected but not presenting:

![image](https://user-images.githubusercontent.com/661798/35050309-6c02e68a-fb9a-11e7-8a79-6be0a4571e3d.png)

And link to [the in-application API docs](https://renderdoc.org/docs/in_application_api.html).

This should make it much clearer than before what's happening and why it can't be captured. The capture buttons are also disabled until a capture can actually be remotely triggered.

**Comment by baldurk** [comment]
With the above improvements in v1.0 I think this should be a lot clearer, so I'm going to close this issue. If you have other questions or clarification you want please ask.
