### ISSUE TITLE
VK_KHR_maintenance2 is not supported

### ISSUE THREAD

**Issue by DrGr4f1x** [baldurk/renderdoc#818]
My application initializes this extension: VK_KHR_MAINTENANCE2_EXTENSION_NAME, but then Renderdoc crashes my app.

**Comment by baldurk** [comment]
VK_KHR_maintenance2 isn't supported by RenderDoc yet, so I'm not sure what exactly is crashing but this isn't too surprising.

Since it's a device extension you should find that when RenderDoc is attached, VK_KHR_maintenance2 is not enumerated as a supported extension - your code should check that the extension is available before enabling it.

**Comment by DrGr4f1x** [comment]
Cool, I'll fix my code to detect availability before initializing this extension.  Thanks!

**Comment by BearishSun** [comment]
Just want to add my +1 on adding support for the extension. Without the extension you cannot bind depth buffer as read-only, yet have stencil writable, without using the GENERAL image layout. This is useful for operations like determining MSAA coverage for deferred rendering. If you do use the GENERAL layout the validation layer keeps popping warnings about it being inefficient.

Obviously I can just not load the extension and use the GENERAL layout when debugging with RenderDoc, but it's not an ideal solution.

Thanks for the great work so far! :)

**Comment by baldurk** [comment]
Yeh, VK_KHR_maintenance2 is definitely a high-priority extension to support since it's going to be very commonly used.

Currently my focus is 100% on getting v1.0 stabilised and shipped. Hopefully that will be Real Soon Now&trade;. Once that's out, my plan is to shore up support for missing extensions and other general API support things that have been unaddressed for a while.

**Comment by baldurk** [comment]
I've implemented support now, although I didn't really have any test cases so there might be problems.

Let me know if you run into any issues.
