### ISSUE TITLE
Qt v1.x branch window size issue on 2nd run

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#820]
On second run of qrenderdoc.exe, window size is messed up (width seems to go way out of display area). Only way to fix it is to delete directory: `%USERPROFILE%\AppData\Roaming\qrenderdoc`.

Not sure if is relevant to mention that I only tested it on multi-monitor setup.

**Comment by baldurk** [comment]
Are you on windows 10? I've seen this problem before but only on win10. I'm not sure if it's a Qt bug, a windows 10 bug, or my bug.

Also I've noticed that when I do hit this, it's intermittent, so if I run 10 times then maybe 1 or 2 will work.

**Comment by bkaradzic** [comment]
Yes, Windows 10. At first I thought it was related to changing theme, since in that case is 100% repro on 2nd run, but running default theme is also causing this issue.

**Comment by vk2gpu** [comment]
I see this issue too, typically every 2nd or 3rd run. Windows 10 too, I believe the most recent update as well.

**Comment by baldurk** [comment]
I think I found the issue, just some uninitialised data which eventually found its way to the size calculations. That's why I had 0% repro rate on my PC, the value always ended up being 0 just by luck.

If anyone still sees any crashes on startup after this commit (or the next nightly build) please let me know, since a few people ran into a similar looking crash on startup but had different symptoms.

**Comment by bkaradzic** [comment]
This fix makes sense. I've didn't see crash, rather width was stretched (it looked exactly like 0xcccccccc width :)

I'll give it a try after nightly is available. Thanks! 👍

**Comment by baldurk** [comment]
v1.0 has now released, including this fix which I haven't seen myself or seen reported since.
