### ISSUE TITLE
64-bit renderdoc tries to load 32-bit renderdoccmd when using global hook

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#836]
I've built latest renderdoc v1.x locally, when I run it and try to enable global hook it says it failed. If I look at the log the output message is:

RDOC 017292: [13:34:55]             core.cpp( 298) - Log     - RenderDoc v1.0 x64 Release (027a7e951b4e03e2b05fdfa272688595786898b5) loaded in replay application
QTRD 017292: [13:34:55]       qrenderdoc.cpp( 101) - Log     - QRenderDoc initialising.
RDOC 017292: [13:34:56]          android.cpp( 313) - Log     - COMMAND: adb 'devices'
RDOC 017292: [13:34:56]    win32_process.cpp( 475) - Log     - Running process adb
RDOC 017292: [13:34:56]    win32_process.cpp( 492) - Warning - Process adb could not be loaded.
RDOC 017292: [13:34:56]    win32_process.cpp( 933) - Warning - Couldn't launch process 'adb'
RDOC 017292: [13:34:59]    win32_process.cpp(1528) - Error   - Can't launch 32-bit renderdoccmd from 'C:\Users\redorav\Desktop\renderdoc\Win32\Release\renderdoccmd.exe'

If I build the 32-bit version of renderdoc it all works fine.

**Comment by baldurk** [comment]
To clarify, are you saying the global hook only works if you run the 32-bit version? Or that you need to build both 32-bit and 64-bit versions before you can run the 64-bit global hook?

The latter is by design, that's what the error message is saying. Distributed builds include the 32-bit renderdoc.dll and renderdoccmd.exe to allow this, on local builds I just enforce that the project is built with both versions.

**Comment by redorav** [comment]
Yeah sorry, what I meant to say is that by compiling the Win32 version, the 64-bit version works. If this is by design then there's not much to look at here. Thanks!
