### ISSUE TITLE
Open capture automatically when using API?

### ISSUE THREAD

**Issue by PfhorSlayer** [baldurk/renderdoc#843]
When using the RenderDoc API to open a capture with LaunchReplayUI (as is done in the Unreal engine RenderDoc plugin), it would be nice if the log for the frame you just captured was actually opened automatically once the RenderDoc UI has come up and loaded the capture log. Right now, you're required to actually double-click on the frame log to open it, which is mildly annoying. :)

If there's more than one frame in the capture (if you capture multiple frames, etc.), perhaps only the first one should be opened automatically?

**Comment by baldurk** [comment]
The API lets you query the available captures with [GetNumCaptures()](https://renderdoc.org/docs/in_application_api.html#_CPPv214GetNumCapturesv) and [GetCapture()](https://renderdoc.org/docs/in_application_api.html#_CPPv210GetCapture8uint32_tPcP8uint32_tP8uint64_t) - they are listed in order from first to latest, but you can also get a timestamp per capture and sort that way.

Then `LaunchReplayUI` lets you pass an optional extra command line, and you can just pass a filename as a parameter to have the UI open up that file when it launches.

Also if you're doing this you can also pass `0` for the `connectTargetControl` parameter, so that when the UI launches it doesn't bring up the connection for no reason.

**Comment by PfhorSlayer** [comment]
It's already doing that - it DOES launch the UI and open up the capture log file, but after doing so it doesn't ALSO open the log for the frame that was just captured - you have to manually double-click on it to have RenderDoc open it up and run the replay. It's a very minor annoyance, but given that I'm typically having to restart Unreal every time I change renderer code, it adds up! :)

**Comment by baldurk** [comment]
I don't quite understand what you mean.

The first parameter `connectTargetControl` determines whether the UI makes a connection to the current program. That brings up this window:

![image](https://user-images.githubusercontent.com/661798/34847961-006fb9a4-f715-11e7-8c0c-67492b7e9cb2.png)

But that doesn't actually load any frame capture for you to browse or analyse. You would then have to manually double click on one of the thumbnails to open and replay that frame capture.

However the second parameter `cmdline` lets you specify whatever command line you want, so e.g. you could run some python scripts or pass the path to an `.rdc` file. The simplest case is just to pass it the full path to the `.rdc` file for the capture you want - which you can obtain with `GetNumCaptures`/`GetCapture`.

From what you're describing, you're only doing the first part. So you'd need to change your code to pass the `.rdc` path on the command line, and then the frame would be loaded immediately after the renderdoc UI launches.

EDIT: to clarify; the capture connection is not a file on disk that's loaded, it's just a socket connection to the application which then provides information about the active API and any existing captures to the UI program.

**Comment by PfhorSlayer** [comment]
I am passing in the .rdc path on the command line there, but it's still not opening the frame log. Here's some debug output from the VS output window:
`Launched process 'C:\Program Files\RenderDoc/renderdocui.exe' with 'C:/Depot/r4/game/SW/Saved/RenderDocCaptures/2018.01.11-14.28.01_frame670.rdc --targetcontrol localhost:38920'`
RenderDoc opens up, but it looks just like the screenshot you posted, and the actual capture log for this frame is not being opened. Also, for some reason the code in the Unreal engine RenderDoc plugin was appending ".log" to the path being passed in on the command line (so it was "C:/Depot/r4/game/SW/Saved/RenderDocCaptures/2018.01.11-14.28.01_frame670.rdc.log" in this case), and I figured that was why it wasn't working, but removing that still doesn't do what I expect.

**Comment by baldurk** [comment]
Oh I think I see the problem, my apologies. The UI only looks at the very last parameter in the command line for a filename to open, and in `LaunchReplayUI` I've appended the `--targetcontrol` part instead of prepending it. If you pass 0 for `connectTargetControl` and it omits that extra part of the command line, does it work as expected then?

**Comment by PfhorSlayer** [comment]
Setting the first parameter to 0 does open the log as expected, but then obviously doesn't connect properly to the target. :)

**Comment by baldurk** [comment]
Yeh that's my bug. I'll either improve the command line processing to see the .rdc anywhere, or reverse the order of where it puts the `--targetcontrol` or both :smile:. In the meantime you can workaround it by adding that part in manually - bit of a hack, sorry :disappointed:.

**Comment by PfhorSlayer** [comment]
No worries! I'll keep an eye out for when the next update rolls out. Thanks so much for an awesome tool!

**Comment by baldurk** [comment]
I've improved the command line parsing on v1.x, so this should be resolved once v1.0 arrives (which shouldn't be long), or in the meantime you can try the nightly builds - just be aware of the gotchas on the v1.x branch.

**Comment by baldurk** [comment]
This should now be fixed in the v1.0 build.
