### ISSUE TITLE
Debian / RPM packages for Linux?

### ISSUE THREAD

**Issue by fschutt** [baldurk/renderdoc#844]
It would be nice to have a .deb, .rpm / AUR packages and some way of updating (launchpad or similar), so that you could `apt install renderdoc` and automatically upgrade when a new version is released. This could be automated by a release script.

I realize that the target audience is mostly using Windows, but it would be nice to have.

**Comment by baldurk** [comment]
Some people have already created packages for renderdoc. That I know of: @gicmo packaged for [Fedora](https://src.fedoraproject.org/rpms/renderdoc), several people made [AUR](https://aur.archlinux.org/packages/?O=0&K=renderdoc) packages, and @akien-mga packaged for [Mageia](https://madb.mageia.org/package/show/name/renderdoc). @jljusten mentioned plans to create a debian package but I'm not sure that they had time.

Unfortunately I don't have the time or background knowledge to create packaging scripts for various distributions. More critically, I can't commit to maintaining those packages going into the future. I provide the binary builds so that people don't necessarily have to built from scratch to run the tool (although given the nature of the tool, most people will certainly already at least have a compiler toolchain).

So this would be up to users to meet me half-way. I don't usually respond with "patches welcome", but this is something that's not in the scope of the project right now.

FWIW if someone does create a script I can run to make packages, I'm happy to set up automated tasks to build the packages and host them on renderdoc.org - similar to how llvm hosts its own apt repository, with stable version builds and maybe a nightly-tracking build. For distributions that don't have their own package hosting. If any changes need to be upstreamed I'm open to that as well, see e.g. #570, #571, #639, #644, #750.

**Comment by fschutt** [comment]
Hm. Debian is rather easy to package, you just create the folders how you want them to be installed on your target machine, a debian control file (for versioning and dependencies) and dpkg does the rest. 

I could create a script for this, but I am not sure how you create the linux folders (manually?). Is there an existing script I could use as a reference - how do you bundle your tar.gz, is there a script?

All I'd need to do is to copy the binary and the necessary libraries and put them into their respective folders, shouldn't be too hard.

**Comment by baldurk** [comment]
The build scripts currently aren't public because I haven't vetted them to ensure they're ready to publish. It's on my list of TODO items that I plan to bring the build/packaging scripts into this repo at some point.

I don't know if the folder structure there actually follows any strict standards or matches debian guidelines. It's there to mostly-sort-of put the right files in the right place, but it's not really intended to be extracted in `/`.

Also more significantly at the moment the linux binaries are built against a very old glibc and statically linking as much as possible - including e.g. Qt - for maximum portability. I don't think they're suitable to push into a debian package as-is. As I understand it you'd need to build the binaries in roughly the same environment as the deb intends to target.

**Comment by akien-mga** [comment]
> All I'd need to do is to copy the binary and the necessary libraries and put them into their respective folders, shouldn't be too hard.

Please don't. Either provide packages that are built using the proper toolchain on the *target* environment (so if you want to provide DEB packages for Debian 8, build them on Debian 8), or don't provide any package.

If you're shipping self-compiled binaries from a different build environment that might have library or glibc version incompatibilities, then a tarball with the binaries (and if need be some shared libraries with a RPATH) is enough. An alternative could be to provide AppImages.

But please no custom DEBs or RPMs, those are installed as *root* and as a user, I don't want to let such thirdparty packages mess with my system. If you do want to make proper packages built from source on the target platform, you could use OpenSUSE Build System (which supports many distros, see e.g. for [Lutris](https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris)).

**Comment by gicmo** [comment]
> An alternative could be to provide AppImages.

My first approach was to do a flatpak, which I think would be awesome to have, and avoid having different packages for different distros. I spent a few hours at GUADEC trying to get it done but the obvious problem is that flatpaks are sandboxed and but you want to run the `renderdoc` plus the target outside the sandbox. There is the HostCommand facility of flatpak which together with a statically linked `renderdoccmd` or something might work and I started on this but then I ran out of time ... I'd be happy to share my efforts and continue with them at some point in time.

**Comment by cheako** [comment]
Ubuntu/Debian packages [available here](https://launchpad.net/~cheako/+archive/ubuntu/renderdoc).  Usable, far from perfect.  Debian users will need to install a number of things from sid(as of this writing obviously), Qt and Python/libc6 among the most visible.
