### ISSUE TITLE
Inspecting specialization constants

### ISSUE THREAD

**Issue by edrickhong** [baldurk/renderdoc#851]
Is there a way to view specialization constants in renderdoc? if there isn't, that would be nice

**Comment by baldurk** [comment]
Yes, they are visible in the same place as push constants under the uniform buffers in the pipeline state. It's not a *perfect* analogy, since they are applied at compile time instead of bind/record time, but they act fairly similarly to global shader constants and it was the most intuitive place I found to put them:

![image](https://user-images.githubusercontent.com/661798/35388665-988ffd7c-01cc-11e8-97a3-b26a35aecc0b.png)

**Comment by edrickhong** [comment]
They are visible on the Linux build too right? Do they not show up if no spec constants are passed? I'm getting an error because I believe the shader is using the default spec constant values.

**Comment by baldurk** [comment]
It will work the same on linux, yes. If the shader declares some spec constants, they will always be shown there even if no spec data is passed - the values will just be the defaults.

If you have a pipeline with spec constants and they aren't showing up, that's a bug. I'd need a repro case or more information to investigate.

**Comment by edrickhong** [comment]
I'll take a look again over the weekend

**Comment by edrickhong** [comment]
It works. I didn't notice because it was named 'Push constants' for some reason
