### ISSUE TITLE
MipMapped Texture3D display

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#854]
Hi, I think I've spotted a bug concerning the display of mipmapped 3D texture.
I join a renderdoc log file and I'll describe using this example.

During the draw call (EID 59), I use a 128x128x128 volume texture (Texture3D RTV 205) I've mipmapped previously using generateMips from the directX API. 
When I'm looking at it in render doc, the first level of mipmap show the 128 slices correctly. But for the higher levels of mipmap, the last slices are shown black (slices [32,63] for mip 1, slices [8,31] for mip 2, etc. ).

I've used the VS debugger and a custom method in order to check if my texture is correctly mipmapped and it does. So the problem seems to come from renderdoc (0.91).

I hope it can be reproduced with the log file but I'm still there for more information.

ps : The file is to big so I post put a link [there](https://drive.google.com/file/d/1fHzuF_hCB29Z2aJ2BV9Oi9ezindkjxPP/view?usp=sharing).

**Comment by baldurk** [comment]
Hi there, could you try with the latest [v0.x nightly build](https://renderdoc.org/builds#nightly) from [yesterday](https://renderdoc.org/autobuilds/v0.x/2018/RenderDoc_2018_01_31_c87dfebd_64.zip)?

I was able to repro this on v0.91 but it worked on that build for me, so I think this is a bug that [has been fixed](https://github.com/baldurk/renderdoc/commit/8617a7fad3125f8dfcbc8fa1542d02a1afc6a0ea) on the branch since v0.91 and hasn't been in a stable release yet.

**Comment by ghost** [comment]
Yep you're right, it works. Thank you.
