### ISSUE TITLE
[Renderdoc 1.0] - Go to next draw call doesn't jump to the next draw call

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#868]
Instead it jumps to the next bundle of API Calls it finds, so essentially it just moves forward without skipping them.

**Comment by baldurk** [comment]
Can you clarify exactly what you mean here? The behaviour of the previous/next drawcall button has always included the "API Calls" elements included when a marker region has some extra API calls that wouldn't otherwise be included, like these:

![image](https://user-images.githubusercontent.com/661798/36023801-973c0f50-0d85-11e8-94ff-844cb8aebd5c.png)

Is that what you mean, or is it something else? I wouldn't necessarily be opposed to filtering them out (I'd need to think about it), but I'm not clear on whether you want to change that behaviour or if there's some 1.0-specific regression you're referring to.

**Comment by redorav** [comment]
Sorry, you're absolutely right, I just retried 0.91 and that's the behavior it used to have. It caught me totally by surprise to be honest, I just happened to use the feature to try to count actual number of drawcalls (I wanted to skip the events) and was a bit perplexed. But I suppose it's not a regression if it's always worked that way. 

I'm not quite sure what the purpose of go to next draw call is if it selects everything in between, but that's a different question to stabilizing 1.0 :)

**Comment by baldurk** [comment]
The main purpose of those buttons is to give an easy way to jump back and forth even when the draws might be in nested markers and not where you can easily just use the up/down arrow keys. It's still intended to jump to every entry in the event browser.

The "API Calls" entries are a bit of a weird edge case. They're added since otherwise calls that happen inside markers with no draw might get lost since I only display API calls associated with a draw, but I can see the argument that sometimes you don't want to select them as a draw. It might make sense to change and it's easy enough, I'll think about it.

**Comment by baldurk** [comment]
Decided after some experimentation that it was probably better to skip "API Calls", so changed that behaviour while working in this area.
