### ISSUE TITLE
Handle out of memory -situations more gracefully

### ISSUE THREAD

**Issue by jansol** [baldurk/renderdoc#870]
In some cases, such as viewing the mesh on indirect draw calls, renderdoc creates *huge* buffers to hold all rendered instances of the mesh, which can cause OOM situations and crash renderdoc.

It would be nice if renderdoc could either
* avoid this kind of problem
* recover from it or
* notify the user of the problem and its cause, allow saving the capture and exit gracefully (maybe disable all tools to not give the user any ideas)

**Comment by baldurk** [comment]
To clarify - this isn't related to indirect draws, it's most likely on instanced draws where you have `NumIndices * NumInstances * NumVertexOutputs` bytes of data to store, and the multiplicative effect means you end up with a lot of data.

Out of memory is a rarer case, but the more likely crash situation is with a driver/GPU error that gets returned via the API's error messages (rather than actually crashing for real in driver code) as a device lost/device removed error. Handling that enough to pop up a fatal error message would be nice, although it will quite possibly still require restarting the UI. This means plumbing an error message safely back to the UI (the easy bit) and handling errors at basically arbitrary times both in the core backend code and on the UI, without trying to do any subsequent work (the hard bit).

**Comment by baldurk** [comment]
I believe this is now handled as well as it can be, any other crashes as a result of GPU OOM should be considered bugs. Note that a CPU memory allocation failure is still going to result in a crash, but that should be rarer.

I added in specific handling for the mesh output on different APIs running out of memory a long while ago as that was the most common case with some draws generating unreasonable amounts of data with high instance/tessellation/vertex output sizes. The code now should handle fatal error codes like device lost & out of memory as soon as possible and stop running API commands almost immediately after, which should mean no crashes as a result of these and instead a message box popup indicating the error.
