### ISSUE TITLE
[Renderdoc 1.0] Multiple queued captures not working properly

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#871]
Hi, the new capture queue code I think is a bit buggy. I'll list my observations here:

a) Seems like I can no longer capture more than 4 consecutive frames. "Capture 4 sequential frames" is as high as the option goes.

b) It seems like it captures every 2 frames. So I get frames 1, 3, 5 and 7 if I set it to capture 4.

c) If delay is 0, then it ignores the consecutive frames option.

**Comment by baldurk** [comment]
a) Yes this is deliberate, there's a large overhead in capturing frames since they go to separate files and have individual setup/teardown for the captures. Trying to capture 100 frames or something is not desirable, it's really only intended for cases where you have something cyclical over a couple of frames that you want to grab and be sure you get a capture of it.

b) I can't repro this, I tested on a program and it captured frames 135, 136, 137, 138. Can you share or point to a program where this happens? RenderDoc's frame counting is 'global' so if you had e.g. two windows both presenting, capturing four frames would capture the active window four times - which would lead to frames 1, 3, 5, 7 (since the other inactive window would be 2, 4, 6, 8).

c) I've repro'd this, it's just a silly missing case - easy enough to fix.

**Comment by redorav** [comment]
a) Is there no chance to get this back or an alternative? We do have processes (especially long-running editor tasks) that create and concatenate results over multiple frames and it'd be nice to be able to get them in a single run for debugging. Just out of curiosity, what is the extra overhead for capturing N frames, other than the memory required to store them?

b) We do have two windows so this doesn't seem to be a bug

c) Great :)

**Comment by baldurk** [comment]
The main reason I'm hesitant to set a high or no limit is that there's a large shoot-yourself-in-the-foot factor. Someone who uses the option naively or with different expectations could end up stuck with their program churning away making a lot of expensive captures.

The overhead is because renderdoc doesn't try and concatenate or share any data between the frames, they get captured just as if they were entirely independent, they just happen to be next to each other. So say you have 3GB of resources hanging around that need to be fetched for renderdoc's data, and 1GB of that is saved to disk, it happens for every frame instead of being processed once and then shared. The memory use actually isn't any worse than one frame because of this, the high water mark just gets reached N times then all the memory gets freed again, and back and forth like that.

In your case if you have a specific region of work you want to bracket, I'd highly recommend using the [in-application API](https://renderdoc.org/docs/in_application_api.html) to start the capture and stop the capture manually around the work you want to include. Then you'd also have access to the whole set of work in a single RDC file, instead of having separate files for each 'frame' where a frame doesn't necessarily even make sense for your case. Of course if the capture then has too many events it can get unwieldy that way, but there's not an ideal solution either way.

You could also [trigger multiple separate frames](https://renderdoc.org/docs/in_application_api.html#_CPPv224TriggerMultiFrameCapture8uint32_t) to capture this way with no limit (the limit is purely in the UI widget) if that's what you prefer.

**Comment by redorav** [comment]
> Someone who uses the option naively or with different expectations could end up stuck with their program churning away making a lot of expensive captures

I see what you mean and I agree that if it's such a memory problem the program should try to avoid mysteriously hanging a user's machine. However maybe a big tooltip with a few explanations as to how it's supposed to work and the implications of it would help people out in using this feature. Have people complained about it? 

I just find '4' to be a bit limiting in this regard, and integrating the renderdoc API to get the previous functionality would be a bit painful... I have actually used up to 10 frames in the past to capture these long running processes. Perhaps just upping the limit and not making it unbound is enough?

**Comment by baldurk** [comment]
> I see what you mean and I agree that if it's such a memory problem the program should try to avoid mysteriously hanging a user's machine. However maybe a big tooltip with a few explanations as to how it's supposed to work and the implications of it would help people out in using this feature. Have people complained about it?

In an ideal world then yes this would be enough, but even with the giant red text on the inject screen there are sometimes people who don't see/read that and don't understand why the injecting fails. Unfortunately for better or worse the reality is that a lot of people don't read documentation or tooltips.

That said RenderDoc ***is*** a tool for devs so there's some degree of being willing to give people enough rope, but there's still a balance between the value of exposing/making available some option and how often it will be useful vs. the chance and impact that it will screw someone up.

> I just find '4' to be a bit limiting in this regard, and integrating the renderdoc API to get the previous functionality would be a bit painful... I have actually used up to 10 frames in the past to capture these long running processes. Perhaps just upping the limit and not making it unbound is enough?

I've raised the limit to 10 for now, although that's still higher than I'd like. I don't promise to keep it there forever if it does turn out to be a problem. It's fine when each frame capture only takes a couple of seconds, but if each frame capture takes 20 seconds then you've just signed your machine up for over 3 minutes of heavy work...

I still think the best solution for you is to do a custom capture because it doesn't sound like you're capturing 10 frames, you're capturing one piece of work that happens to run across 10 frames. If I understand your use-case correctly, it could be that something in your codebase changes - unrelated to what you want to capture - and then the work ends up spread across 20 frames. I've captured baking processes and offline processes before and the best way to do it is to define the region yourself in code rather than trying to match it up to N frame boundaries.

**Comment by redorav** [comment]
> Unfortunately for better or worse the reality is that a lot of people don't read documentation or tooltips.

:(

> I've raised the limit to 10 for now, although that's still higher than I'd like. I don't promise to keep it there forever if it does turn out to be a problem.

:)

> I still think the best solution for you is to do a custom capture because it doesn't sound like you're capturing 10 frames, you're capturing one piece of work that happens to run across 10 frames.

That's fair enough, thanks for understanding. To be fair we do have in scope integrating the renderdoc api into the engine and you're right that it is the best solution, probably a lot more flexible than what I currently do, but it's just not been done yet and until it is it's helpful for us to keep a relatively high capture count.

**Comment by baldurk** [comment]
> That's fair enough, thanks for understanding. To be fair we do have in scope integrating the renderdoc api into the engine and you're right that it is the best solution, probably a lot more flexible than what I currently do, but it's just not been done yet and until it is it's helpful for us to keep a relatively high capture count.

Remember of course there's always the option of compiling your own version with the limit raised. That's one of the advantages of open source :smile:.

Actually it's even possible to do without recompiling, since it's just a UI-enforced limit. On windows builds where PySide2 is available you can run this while a capture connection is open:

```python
from PySide2.QtGui import *
from PySide2.QtWidgets import *
mainwindow = pyrenderdoc.GetMainWindow().Widget()
for spinner in mainwindow.findChildren(QDoubleSpinBox, "numFrames"):
    spinner.setMaximum(999.0)
```

**Comment by redorav** [comment]
> Remember of course there's always the option of compiling your own version with the limit raised

Yeah that's definitely an option, thanks for the tip and the code. One doesn't always know the implications though, for all I know renderdoc hasn't allocated enough memory for all those captures! I'd be like "Hmm let's raise this little number here see what it [...]"

**Comment by baldurk** [comment]
Made those changes mentioned above now.

**Comment by redorav** [comment]
Works great, thanks a lot!
