### ISSUE TITLE
Channel selection buttons in Texture Viewer highlight, but do not activate when clicking if window is not foreground.

### ISSUE THREAD

**Issue by PfhorSlayer** [baldurk/renderdoc#875]
This is in version 0.91, so it may already be fixed with the change to Qt, but we're not using 1.xx yet so I thought I'd mention it regardless:

When the Texture Viewer is not the foreground window, you can mouse over the RGBA channel selection buttons and they appear as though they're responding to mouse input correctly, but clicking on one does nothing but bring the window to the foreground. You then have to click AGAIN to actually toggle the button's state. This behavior is the same for all of the single-click toggle buttons on the toolbar there, but the drop-down selection boxes do respond on the first click, even when the window is not the foreground.

**Comment by baldurk** [comment]
Being honest since we're only a couple of weeks away from v0.x being retired and the UI replaced I don't think I'm likely to fix any bugs like this in 0.91. Any bugs are unlikely to be fixed if they're not something I can cherry-pick back from a v1.x branch fix.

I do seem to be able to get that behaviour on 0.91, though I can't explain it - it might be something winforms does by default for buttons because they're an "action" but a drop-down can be cancelled.

On the Qt v1.x UI it seems to work as expected, processing the click and raising the window. If you see the same then I don't think this bug will be fixed, sorry.

**Comment by baldurk** [comment]
As mentioned above, this behaviour seems to be gone in the  Qt UI in the v1.0 release.
