### ISSUE TITLE
Qt UI scaling issues

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#883]
UI elements are extra big on my 2560x1440 LCD matrix with GTK scaling factor of 2:
![renderdoc-scaling](https://user-images.githubusercontent.com/107301/36558654-b052f888-17d9-11e8-8f60-4ba064c94c0e.png)

The UI elements leave very little working space to actually look at the capture data, and many are restricted from resizing (presumably, to have an unreasonably large minimum size?).

This is somewhat relevant to #2, but it's been 4 years since then (!), and now we are talking about Qt.

**Comment by kvark** [comment]
Installing [Minwaita](https://www.gnome-look.org/p/1174686/) theme somewhat helps, but I still don't always even able to maximize the window, if it happens to start with more height than my screen is.

**Comment by baldurk** [comment]
As discussed on IRC this doesn't seem to be an actual bug - the icons are correctly selected as 2x and the text appears to be sized correctly (roughly the same line-height as the icons). The issue is a combination of a theme with a lot of padding, and a resolution that's barely larger than 1920x1080 but at 2x scaling means half the usable space.

I'm not sure there's anything renderdoc is doing wrong though - it's displaying at 2x as it should.
