### ISSUE TITLE
[Linux] Attempting Vulkan capture breaks Nvidia Vulkan driver outright

### ISSUE THREAD

**Issue by roothorick** [baldurk/renderdoc#886]
Even something as basic as vulkaninfo fails to so much as create an instance. 0.91 and the v1.x nightly produce different console output, but the net effect appears to be the same. 

0.91:
```
roothorick@modestmonster:~/Downloads/renderdoc_0.91/bin$ ./renderdoccmd capture -w vulkaninfo
Launching 'vulkaninfo'
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.65

ERROR: [loader] Code 0 : loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD libGL.so.1 failed.
ERROR: [RDOC] Code 1 : RenderDoc does not support a requested instance extension.
/build/vulkan-quzn99/vulkan-1.0.65.2+dfsg1/demos/vulkaninfo.c:705: failed with VK_ERROR_EXTENSION_NOT_PRESENT
'vulkaninfo' finished executing.
```

1.x 2/23 nightly:
```
roothorick@modestmonster:~/Downloads/renderdoc_2018_02_23_08738f27/bin$ ./renderdoccmd capture -w vulkaninfo
Launching 'vulkaninfo'
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.65

WARNING: [loader] Code 0 : loader_add_layer_properties: /home/roothorick/.local/share/vulkan/implicit_layer.d/renderdoc_capture.json invalid layer manifest file version 1.1.2.  May cause errors.
WARNING: [loader] Code 0 : Indicating layer-specific vkGetInstanceProcAddr function is deprecated starting with JSON file version 1.1.0.  Instead, use the new vkNegotiateLayerInterfaceVersion function to return the GetInstanceProcAddr function for thislayer
WARNING: [loader] Code 0 : Indicating layer-specific vkGetDeviceProcAddr function is deprecated starting with JSON file version 1.1.0.  Instead, use the new vkNegotiateLayerInterfaceVersion function to return the GetDeviceProcAddr function for thislayer
ERROR: [RDOC] Code 1 : RenderDoc does not support a requested instance extension.
/build/vulkan-quzn99/vulkan-1.0.65.2+dfsg1/demos/vulkaninfo.c:705: failed with VK_ERROR_EXTENSION_NOT_PRESENT
'vulkaninfo' finished executing.
```

Vulkan functionality is perfectly fine outside of RenderDoc.

**Comment by baldurk** [comment]
What windowing system are you using? I wonder if this is caused by running under Wayland which is not currently supported. I think that would cause `vulkaninfo` and any other vulkan program to enable the wayland surface extension and trigger this error.

**Comment by baldurk** [comment]
Actually it seems like it might be something simpler, by default `vulkaninfo` requests `VK_KHR_get_surface_capabilities2` which is also unsupported. With a newer version of the loader (1.0.68.0 and above) RenderDoc will be able to filter out unsupported instance extensions and that works because `vulkaninfo` doesn't require it. Until then `vulkaninfo` will try and fail to initialise that extension.

Do you have any problems with other programs that don't use unsupported instance extensions?

**Comment by roothorick** [comment]
I see. I am also having problems with dxvk, but my troubleshooting pretty much stopped when I discovered that vulkaninfo is broken.

I think RenderDoc isn't really usable for my purposes then. I'm working on a library that interfaces with SteamVR, which requires some rather obscure extensions; on the instance side, the ones likely to be most problematic are `VK_KHR_external_memory_capabilities` and `VK_KHR_external_semaphore_capabilities`; naturally, it also wants the corresponding device extensions.

**Comment by baldurk** [comment]
RenderDoc does support the external memory and external semaphore extensions at instance and device level, I worked with the SteamVR folks at Valve a while ago to get that all set up. I can't speak to dxvk but I believe the author of that project has been using RenderDoc before, so it just depends on what extensions are in use.

It does depend on a case-by-case basis. After v1.0 ships I plan to go back and add support for some of the missing extensions, but recently my focus has been on getting v1.0 ready. vulkaninfo is actually a much worse case than most programs because it initialises some uncommon extensions just for the purposes of querying their capabilities.

**Comment by roothorick** [comment]
I see. I'll give it closer inspection then, try to figure out what my dxvk fork is doing that mixes up RenderDoc.

**Comment by roothorick** [comment]
0.91 doesn't work with dxvk, but v1.x seems to. I'm having a hard time seeing how to correlate textures shown in RenderDoc with the texture handles pushed around in the code, but that's not exactly something for an issue report.
