### ISSUE TITLE
VK_NV_glsl_shader device extension causes unhandled exception

### ISSUE THREAD

**Issue by RC-1290** [baldurk/renderdoc#887]
**Version:** RenderDoc v0.91

**Repro steps:**
1) Include "VK_NV_glsl_shader" in the array sent to VkDeviceCreateInfo::ppEnabledExtensionNames
2) RenderDoc > Capture Log
3) Select the executable
4) Launch

**Result:**
Within a second RenderDoc opens an error reporter about an unhandled exception or other similar unrecoverable error.

**Debug notes:**
Nothing in the logs seems to point to this specific extension. 

Manually enabling the "VK_LAYER_RENDERDOC_Capture" layer in the program (adding it to VkInstanceCreateInfo::ppEnabledLayerNames before calling vkCreateInstance) causes the ERROR_EXTENSION_NOT_PRESENT ("A requested extension is not supported.") result to be returned from vkCreateDevice.

**Expected Result:**
If supporting this extension in RenderDoc ends up not being viable, it would be nice to show a more specific error message.

**Workaround:**
Use SpirV shaders, and disable the "VK_NV_glsl_shader" extension.

**Comment by baldurk** [comment]
Yes, `VK_NV_glsl_shader` will never be supported.

The extension is removed from the list of device extensions reported through `vkEnumerateDeviceLayerProperties` when RenderDoc is active, and a valid vulkan application must enumerate the supported extensions before trying to enable them.

~Note that `VK_NV_glsl_shader` is a device extension, not an instance extension, so it's also invalid to add it to the `VkInstanceCreateInfo::ppEnabledLayerNames` array~. I misread, my mistake. Although it's not recommended to manually add RenderDoc's layer as it can cause crashes.

**Comment by RC-1290** [comment]
Good point! _(it makes me wonder why I didn't have that support check for device extensions, when I did for instance extensions. Maybe because it's not a reasonable extension for non-debug versions. But still, time for me to add that check.)_

And thanks for the comment about RenderDoc's layer. I didn't want to leave it there for other reasons, but it's good to know that it's not recommended anyway.

You can't be expected to handle every incorrect usage of Vulkan, so hopefully this issue post is at least useful in letting you know you can ignore the crash report.


~~That said, I'm opening RenderDoc because I expect to have made a mistake in at least one other place. So unless I'm the only one who is ever going to make a mistake like this, perhaps it would be nice to show the VkResult that presumably precedes this error reporter opening, given that it will only show up when starting a RenderDoc capture, or manually enabling the renderdoc layer. I did not see it in the log.~~ Adding proper error logging to file to my own application, rather than relying entirely on DebugBreaks should solve this.

**Comment by baldurk** [comment]
Yeh I appreciate you looking into it and figuring out the problem!

This kind of lands in a bit of a weird middle-ground, where although it's unique behaviour to using RenderDoc it's the kind of thing that the validation layers should be checking. I deliberately avoid adding error-checking and API use validation into RenderDoc because otherwise I end up duplicating all the work that the validation layers do.

I think there should be a check in validation to make sure you enumerate device extensions before enabling any extensions. I'll file an issue on the layers, since they already check something similar making sure you query buffer/image memory requirements before binding memory.

That said I do already have a check on `vkCreateInstance` to see if an unsupported extension is added and then I return `VK_ERROR_EXTENSION_NOT_PRESENT`. That's because up until recently I was unable to filter out unsupported instance extensions from the enumerated list, but it wouldn't be hard to do the same for `vkCreateDevice` to make it easier to catch bugs like this.
