### ISSUE TITLE
How to launch the app with specific name?

### ISSUE THREAD

**Issue by Qjames** [baldurk/renderdoc#889]
There is a game named "com.tencent.tmgp.sgame", when launch it from renderdoc, it will always fail due to wrong activity name.
Checked the renderdoc Log, it will launch with "com.tencent.tmgp.sgame/com.tencent.tmgp.sgame.SGameActivity".
While manually launch it, from the adb log it was "com.tencent.tmgp.sgame/.SGameActivity".
How can I set in the RenderDoc? Thanks.

**Comment by michaelrgb** [comment]
The GUI uses the following adb command to get the activity name to launch:
`adb shell cmd package resolve-activity -c android.intent.category.LAUNCHER %s`

Can you run that for your package and tell us what activity name it is reporting? (Might as well just paste the whole output) It looks for the "name=" string so its possible we may need to cut off the package name from the activity.

Also can you give any more details about the exact error when it fails due to the wrong activity name?

**Comment by baldurk** [comment]
I'm trying to be a bit more reactive in closing issues, and as part of that if an issue is sitting indefinitely needing more info from the original reporter I will close it after a while.

A closed issue of course can easily be re-opened if more info is provided, so please if you can provide the information requested above then please comment and we can investigate. But having old issues cluttering the list doesn't help anyone if there's no solution to the original problem.
