### ISSUE TITLE
Vulkan Macos support?

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#895]
Note don’t know if makes much sense but now that Vulkan MacOS SDK has been released and the core Metal wrapper (MoltenVK) too (even open sourced), just asking if much work to support it? Or course right now we must use (I assume) Xcode Metal debug capabilities.. and of course after 1.0 release..
With new Vulkan version hopingly coming GDC, seems renderdoc still have a road ahead after 1.0..

**Comment by baldurk** [comment]
In theory MoltenVK should just kind of slot in and it uses the normal loader so layers can be loaded. This is something I plan to look into, but it's not a high priority for after v1.0. Are you working on a OS X project that you would want RenderDoc for?

I'm not sure what you mean about there still being a road ahead, 1.0 is far from being the last planned release - it's just a milestone release.

**Comment by oscarbg** [comment]
must say not anything serious..
perhaps better would have been to test by myself and report any concrete issues I encounter if any..
yeah I know 1.0 is not the end of renderdoc.. I just meant that it seemed "feature complete" enough to not consider updating (I as a user) for a long time.. then remembered a new Vulkan version is probably coming soon so must keep perhaps updating Renderdoc..

**Comment by gplusplus314** [comment]
Chiming in here to express my interest in this feature. I am, in fact, working on a project for macOS.

I'm still in the beginning/learning stage of both Vulkan and graphics programming as a whole, so something like RenderDoc would not only be useful for general troubleshooting, but also as an educational tool. Let's also remember that moving forward, Apple has deprecated OpenGL support in all of their platforms, making Vulkan development (via MoltenVK) even more relevant in the Apple ecosystem.

I briefly glanced over how RenderDoc integrates with Vulkan on Windows (sets up an implicit layer via Windows Registry). This may be a stupid question, but as an experimental setup, could we explicitly load the RenderDoc layer(s) and capture a frame? I've gotten all of the LunarG validation/debug layers to work without any deviation from the standard procedure you'd do for any other platform. Programmatic, platform-specific layer and extension loading (or conditional compilation) is par for the course, so this wouldn't be anything out of the ordinary, my naive little mind would think. Sure, not as sexy, but it would at least work for a proof-of-concept in the short term.

Furthermore, if someone could point me in the general direction of how this new feature might be able to be patched in to RenderDoc, I could try to afford some time into making a proof-of-concept.

Thanks!

**Comment by baldurk** [comment]
Thanks, it's always good to have a concrete non-theoretical use case.

I don't recommend manually loading the vulkan layer on any platform, really, as renderdoc isn't a normal layer. I'm not sure that would save you much though, as if you can compile the layer at all you might as well make it load implicitly like normal.

I think the main things to do (in order) are: 

1. Get the layer compiling on mac with no WSI support. This might already 'just work' with the mac compilation support that's there, I'm not sure.
2. Add WSI support for MoltenVK's surfaces, which shouldn't be too far off the existing xlib/xcb/android/win32 WSI support.
3. Fix up any other issues that arise.

That should get you far enough to compile and capture with sufficient manual steps.

Then you need to get the replay program to use MoltenVK to replay vulkan captures. I _think_ this is mostly a packaging consideration? Since MoltenVK is packaged into the app rather than available as a system library as it is on other platforms.

After that then hopefully it captures and replays perhaps with some manual intervention. At that point it's a matter of tidying it up, adding automatic layer registration and making it compile and run with as few configuration steps as possible.

If there's someone who'll actually use it I can look into this myself if you don't get a chance sooner, the few devs I'd spoken to using it before said they were getting by using the Metal tools and having RenderDoc was a 'nice-but-not-urgent' thing.

**Comment by gplusplus314** [comment]
Wow, thanks for the detailed reply! I'm absolutely slammed for the next month, so I won't be able to spend much time on this, if at all, during that time. Keep in mind that in the world of graphics coding, especially in the Vulkan world, I'm still very much a beginner, so I move at a snail's pace. But I will definitely _try_ to help.

But here's what I do know, in the short term... I'm not sure about point number 1, but I enumerated extensions and poked around and I can say, for certain, MoltenVK's surface extension `VK_MVK_macos_surface` works with WSI and I'm up and running. I could have saved time and actually read the GLFW documentation, which says exactly the same thing. But hey - I learned something! ;)

About packaging, only iOS requires a static-linked build. On macOS, I'm using MoltenVK as an external `dylib` just fine. It may be optionally installed as a framework so that XCode can do its magic, but I'm just doing everything through CMake and CLion. Point is, there isn't one canonical setup, so the general convention is to just set environment variable `VULKAN_SDK` for the root directory of the SDK and the whole LunarG toolchain "just works" for the development environment.

I'll try to spend some time on this and I'll keep an eye on this issue thread. Again **thank you very much**.

P.S.:
Since you're interested in concrete projects, I'll tell you a bit about what I'm working on. It's an interactive content creation tool that requires GPU acceleration for both visualization and GPGPU. End users would work on MacOS, create their project, and deploy to a Linux target that will "perform" the content with specialized hardware. I'm maintaining cross platform compatibility from the get-go (Mac and Linux; Windows as a best-effort, but not required). So in my very specific use case, I'm very much targeting _Vulkan_, not Metal. Semantics, I know, but I'm just trying to share perspective for where I'm coming from and why I'm placing emphasis on learning/inspecting/debugging Vulkan directly, not the output of the MoltenVK abstraction. If you'd like to know more, please contact me directly; I'd prefer to keep it out of plain sight for now.

**Comment by baldurk** [comment]
I'm closing this now - vulkan mac support isn't super-top quality shippable yet (I'm not sure when that point will come) but it's at least implemented to a basic degree, and any further bugs should be filed as specific issues rather than this catch-all.

Notes about the current support:

* Currently KhronosGroup/MoltenVK#234 is a blocker. I've worked around it with the patch I mentioned in that issue, and the current code assumes I can pass a `CALayer`. I'll update my code if a different resolution comes out of that bug.
* To capture an application it must be linked against the actual vulkan loader on mac which loads layers properly. Applications linking direct to MVK won't work because MVK doesn't load layers as far as I know.
* For replay, RenderDoc first tries to find the loader as `libvulkan.1.dylib` globally - either installed to the system or at least in `~/lib`. In this case, you're expected to have an ICD registered e.g. in `~/.local/share/vulkan`. If you don't, then it falls back to trying to load MVK from the qrenderdoc bundle. That should be `libvulkan.1.dylib`, `libMoltenVK.dylib` and `MoltenVK_icd.json` all in a `MoltenVK` folder inside `qrenderdoc.app/Contents`. The default build doesn't do this for you, you have to place it there yourself.

Aside from those gotchas I can capture and replay simple applications like Sascha Willems' demos.

**Comment by oscarbg** [comment]
Thanks @baldurk for the update!
Will give a try soon..
