### ISSUE TITLE
[Vulkan] Support for VK_EXT_conservative_rasterization

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#898]
It looks like RenderDoc does not report the ```VK_EXT_conservative_rasterization``` extension, even if the device supports it, so if an application requires this, device creation will fail.

Adding support for this extension would be great, and even better if the state of conservative rasterization would also be visible

**Comment by baldurk** [comment]
Yes I remove any unsupported extensions from the enumerated lists, so that applications have a chance to fail gracefully.

This won't happen for 1.0 as the branch is locked down for anything but bugfixes, but for 1.1 I'm planning to look at this kind of thing. Since I've been focussed on the 1.0 features and there are a number of obvious extensions and API features across other APIs that I should add support for.

**Comment by baldurk** [comment]
I implemented this and tested it against your conservative rasterization demo, and it seems to all work for me.

The state is displayed in the rasterization section in the pipeline state viewer.
