### ISSUE TITLE
Missing check for Qt5Network build dependency

### ISSUE THREAD

**Issue by akien-mga** [baldurk/renderdoc#907]
Building qrenderdoc on Mageia 6 x86_64 (Linux), I got the following build error right at the end of the build:
```
make[3]: Entering directory '/home/iurt/rpmbuild/BUILD/renderdoc-1.0/build/qrenderdoc'
compiling ../../qrenderdoc/Code/Interface/Analytics.cpp
../../qrenderdoc/Code/Interface/Analytics.cpp:28:33: fatal error: QNetworkAccessManager: No such file or directory
compilation terminated.
Makefile:12183: recipe for target '.obj/Analytics.o' failed
```

CMake should check for Qt5Network as a required dependency to prevent this.

**Comment by baldurk** [comment]
The current cmake doesn't check for Qt at all, because of the way it forwards to `qmake` directly - if I remember rightly there were some problems on linux systems before with checking for Qt existing one way in cmake, and then invoking it another way.

The Qt project file `qrenderdoc.pro` specifies that network is required so qmake could (and I think should) check that all of the components are available including network, it checks the minimum version number manually at least.

In general anyway not all dependencies are checked for directly in cmake, they're documented in the build instructions and people can refer to that if they run into build errors.
