### ISSUE TITLE
Android debug.vulkan.layers prop issue

### ISSUE THREAD

**Issue by ruggiex** [baldurk/renderdoc#910]
RenderDoc seems to set debug.vulkan.layers to VK_LAYER_RENDERDOC_Capture and not resetting it. After running RenderDoc and go back to Android Studio to debug causes vkCreateInstance call to fail with return code VK_ERROR_LAYER_NOT_PRESENT.

**Comment by baldurk** [comment]
This is an unfortunate limitation of the android system of handling layers. The debug.vulkan.layers property is both global and not 'latched' at program startup time like an environment variable, instead it's read at the time the app calls vkCreateInstance. That means we have to set it before starting the app, and there is no guaranteed safe time to unset it again because we don't know when the app will create an instance. It gets unset when opening a capture (so the replay app doesn't pick it up), or when you close/disconnect from renderdoc on the device, but not in between.

So I don't think this is fixable. Having android studio open in the background while using renderdoc will break it anyway because the tool interferes with renderdoc's debug process, so I'd recommend using one program or another but not both at the same time. In an ideal world this would be supported but android is not a developer friendly platform and a lot of hard limitations like this kick in.

**Comment by ruggiex** [comment]
Maybe mention it in the troubleshoot section of the document? I'm not using both android studio and renderdoc at the same time but somehow the variable was left in the state that it took me a while to figure out why the app is suddenly broken.

**Comment by baldurk** [comment]
Sure I can find somewhere in the docs to mention it in case someone else runs into it.

When I say using them both at the same time I don't necessarily mean debugging a program launched with renderdoc, I mean if you left renderdoc open and then switched over to launch through android studio.

If you completely closed down the renderdoc program before launching your program in android studio, then it should have unset the layers property upon close - if it didn't then that's a bug and I'd certainly like to fix it.

**Comment by ruggiex** [comment]
Ok I did have both open at the same time initially so it might be in some odd state causing it not getting reset. Good to know that it's supposed to reset it. Thanks.
