### ISSUE TITLE
Output in RenderDoc varies significantly from actual geometry captured  on Intel hardware

### ISSUE THREAD

**Issue by BunnCode** [baldurk/renderdoc#912]
Currently, it appears that for some reason, glMultiDrawIndirect results in significantly altered results in the actual application, vs what RenderDoc displays.  Here's the difference visualized: https://i.imgur.com/VCxFUtC.png
As you can see, the render is mangled, but RenderDoc displays it with no issues; this makes the issue particularly difficult to debug.
Here is the capture: https://my.mixtape.moe/fiiagc.rdc
and here is the code used to generate the inconsistent draw command: https://pastebin.com/6sDCjSFf
Graphics Processor: Intel HD Graphics 620 (Lenovo)
OpenGL version: 4.5 core
RenderDoc version: 1.0 (API v 1.2.1)
OS: Windows 10
Thank you very much for your time.

**Comment by baldurk** [comment]
Unfortunately diagnosing why something _works_ from within renderdoc's replay is a lot harder than diagnosing why something is broken. From the screenshot it looks to me a lot like the index buffer is broken, since all of the vertices rendered seem to be in the right place - just in the wrong order.

I don't see anything in particular in the state or setup of those draws which I'd expect to break, or the code that you pasted, but it's hard to tell without being able to compare against the application itself.

Since you're using GL and Intel, both of those make it more plausible that this is a driver bug, but it's impossible to say without more information. Are you able to share a build of your program with me (either here or privately)?

**Comment by BunnCode** [comment]
Dang, that was a fast response!
Sure thing. I've added the debug and release version, as well as debugging symbols, in case that helps at all.
https://my.mixtape.moe/htaeiz.zip (initially forgot to add a required resource, should be fixed)
Also, there was a small typo in the paste in AddMesh; it wasn't in the actual code, but ended up in the paste while cleaning out some comment gore so that my code wasn't horrifying to those looking at it.
Here's the actual version;
https://pastebin.com/QMfhY5gd
I'd be more than willing to supply anything else that might help.

**Comment by baldurk** [comment]
There's definitely something funky going on here. My guess is some invalid behaviour which RenderDoc is normalising or avoiding somehow on replay.

For what it's worth:

* On my nvidia machine, the demo plays fine without RenderDoc. Not too surprising since nvidia tends to be extremely lax/forgiving:
  ![image](https://user-images.githubusercontent.com/661798/37340048-a7224252-26b4-11e8-9ce2-ad42d40dd262.png)
* On my intel machine I unfortunately can't run the demo, as it requires GL 4.5 and my chip is an HD Graphics 6000 which only supports GL 4.4 at best.
* On my AMD machine the draw is completely missing, both running the program on its own, and while capturing and replaying. On AMD it _does_ say that the draw call generates GL_INVALID_OPERATION but unfortunately nothing more than that, I'll see if I can find out any more info here about why it doesn't like the draw as it might lend you a hand.

I still can't see anything that's definitely wrong, but there are a couple of weird points - there's a call to `glShadeModel` which is deprecated and no longer part of core profile OpenGL which you look to be using. I don't think that's related though. It also seems very weird to bind the same buffer to both `GL_DRAW_INDIRECT_BUFFER` and `GL_ARRAY_BUFFER` but I'm not sure if it's technically illegal from reading the spec.

**Comment by baldurk** [comment]
I heard back from AMD. It seems like their driver isn't correctly stripping dead code from your shader, so there's a `return;` in `main()`, and the dead code after that refers to a couple of samplers which are unbound (no surprise - since they're only used in dead code). Unfortunately the samplers are of different types, and without anything bound they end up referring to the same binding slot and things blow up from there.

So you could try removing that dead code, but otherwise I'm not sure if AMD's failure is related at all to the Intel problems.

I'm not sure there's much more I can do from my side, this feels like it might just be an Intel driver bug which I can't investigate myself. Closing this issue for now, but if there's more in renderdoc you'd like me to look at or a different repro case, feel free to comment and I can open it up again.

**Comment by BunnCode** [comment]
Apologies for dropping off on this end! My laptop actually flat-out _died_, which was probably the cause of the graphical issue in the first place. Thanks for trying to help out!
