### ISSUE TITLE
Option to change "cycle windows" key

### ISSUE THREAD

**Issue by Zeblote** [baldurk/renderdoc#917]
## Description

The default key (f11) to cycles windows is kind of dodgy in unreal engine, since it maximizes/minimizes windows aswell. Is there an option to change it? I looked through all settings pages but didn't find anything.

## Environment

* RenderDoc build: v1.0
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
There isn't a way in the UI to change the keybinds, but you can use the [RenderDoc API](https://renderdoc.org/docs/in_application_api.html) to change it. UE4 now ships a RenderDoc plugin using this API so you could ask if they could provide an option in the plugin settings.

**Comment by Zeblote** [comment]
The plugin is very nice, but it means renderdoc is always loaded which creates a major performance hog.
It seems to about double the frametime, so instead I launch the editor through renderdoc only when I want to use it.

If the key can't be changed, maybe you could just pick a different default one? F11 is bound to maximize windows in more programs than unreal, so it might help more people that way.

**Comment by baldurk** [comment]
Right I don't typically recommend leaving renderdoc active at all times, but my understanding was that the plugin doesn't always have to be configured to load renderdoc, it could just passively detect whether the editor has been launched through renderdoc and activate its integration. That way you still get the benefits of hiding all the overlays and a nice button to generate captures, but only when you've opted in. At least that's how I wrote the Unity integration, I'm not really familiar with the UE4 plugin.

Having said that, doubling your frame time sounds bad, can you give any more information on that? There's been discussion before (see #660) about the overhead that RenderDoc has, and unfortunately with refcounting and hazard tracking behaviour in D3D11 there's some active overhead that's quite to eliminate completely, but it generally shouldn't be that bad unless your frametime is already quite low and doubling it isn't adding too much.

The thing is I don't know if whichever other default key I pick will interfere with some other program, so I don't want to change it without a stronger reason than that, especially when alternatives are available and this hasn't come up (from memory) in the 4 years that the shortcut has been there.

**Comment by redorav** [comment]
In our company at one point F12 was bound to "close program" (yeah I don't know why either) so I had to be really careful to use print screen and thankfully for me there were two options. I don't know how difficult it is to add to the UI, but I definitely would have changed it if I could. I agree I wouldn't just go and change the default blindly.

**Comment by Zeblote** [comment]
The unreal plugin doesn't work that way, it automatically loads renderdoc when the editor starts. Then it adds a button to editor viewports to trigger a capture, or you can press alt+f12.

Having it only activate when renderdoc is already loaded doesn't seem to be an option, but would be really nice...

**Comment by Zeblote** [comment]
After some investigation the performance drop doesn't seem to be renderdocs fault, instead unreal is detecting that renderdoc is loaded and automatically adjusts some settings.

It enables draw events that are normally disabled, and also turns off multithreaded rendering. Is the latter actually necessary to use renderdoc?

**Comment by baldurk** [comment]
That could be a useful thing to feature request then maybe - all the plugin should need to do is avoid `LoadLibrary` explicitly and just call `GetModuleHandle` to see if the library is already loaded, and gracefully fail away if it's not.

I'm not aware of any reason to disable multithreaded rendering. Perhaps there was a bug at some point and this was a workaround? Or maybe it's just nicer to debug without deferred command lists in D3D11.

**Comment by baldurk** [comment]
One question - would you find it sufficient to have control over the active window from the UI's capture connection window? I'll need to think about whether adding full shortcut configuration is worthwhile, but I wouldn't mind adding control to that UI panel since it makes sense with the other capture triggering controls.

It might also be worth trying to just disable that code that you found which changes based on renderdoc's presence, and see if it works for you - talking to a friend at Epic it seems like it might have been added to benefit other cases and just happens to have impacted you as well. It'd be useful to know more precise details e.g. what the frame time is before and after - 30ms to 60ms is a big problem, but 5ms to 10ms is less so :smile:.

**Comment by Zeblote** [comment]
I'm not really sure what you mean, what's the capture connection window?
Yeah it's more like a 8ms to 10ms change if I turn the parallel rendering back on. :D

It doesn't seem like anyone is maintaining the unreal plugin, so I made a pull request that adds an option for it. https://github.com/EpicGames/UnrealEngine/pull/4560

**Comment by baldurk** [comment]
The [capture connection window](https://renderdoc.org/docs/window/capture_connection.html) is the one that shows up once you've launched an application, that shows the captures you've made and gives some controls for triggering a capture:

![image](https://user-images.githubusercontent.com/661798/37421977-4d3bb80a-27b2-11e8-859b-6169d1ebf299.png)

I could add an option under the 'tools' panel to switch the active window.

The PR looks good, although perhaps it should default to enabled since that's the current default behaviour? Otherwise anyone using the plugin may get confused as to why it suddenly stops working and they'd need to go find the cvar to change.

**Comment by Zeblote** [comment]
Could be useful, though now that the plugin is usable without performance hog it's not necessary for unreal anymore. The alt+f12 to capture the active viewport kinda solves the problem.

You're right, I changed it so the default behavior is like before. Though that is arguably the "worse" option..

**Comment by baldurk** [comment]
I'm going to close this now as I think your use case is covered. I've made a note internally to consider adding active window control onto the tools (maybe with a preview of the window to make it more useful).
