### ISSUE TITLE
Inspecting UWP applications.

### ISSUE THREAD

**Issue by nical** [baldurk/renderdoc#920]
## Description

Running UWP apps is a bit more involved than running a regular executable, and it looks like renderdoc doesn't have a way to hook into such applications.

I don't know how feasible this is, but It would be useful.

## Environment

* RenderDoc build: v1.0
* Operating System:  Windows 10
* API: All.

**Comment by baldurk** [comment]
Realistically I think this will always be completely impossible. UWP is deliberately a very locked-down and limited format that only Microsoft blessed tools can work with at the system level, and AFAIK Microsoft isn't much of a fan of RenderDoc even if it were feasible to open up some access.

I'd hope any project that's making UWP builds would also have a proper build available as well that they use during development, as it seems kind of self-limiting to use UWP for anything but the final release product. As far as graphics APIs go the code is roughly the same so debugging on one should be equivalent to debugging on the other. The only case where this wouldn't be true is debugging someone else's program for which you don't have a non-UWP build, but this is deliberately not a supported use-case with RenderDoc. Can you explain why you'd want UWP support in RenderDoc rather than using it normally on a regular build of your program?

**Comment by nical** [comment]
Thanks for your answer. I kind of expected as much but it's good to know. I'll close the issue and hopefully other people asking themselves the same question will find the answer here.

**Comment by nmr8acme** [comment]
FWIW I would like to use RenderDoc to debug a UWP app that doesn't have a regular win32 build. (We ship an app via the app stores and I don't work on the UWP app itself but I do work on the cross platform system which uses DX.)

I was surprised that the UWP exe can't be launched normally, but I guess thats par for the course.

**Comment by baldurk** [comment]
Please do not comment on years-old closed issues. If you have a bug to report or a feature request, please open a new issue.
