### ISSUE TITLE
CMake does not correctly check presence of Qt5 modules svg and x11extras

### ISSUE THREAD

**Issue by turol** [baldurk/renderdoc#921]
## Description

CMake doesn't check if necessary Qt5 modules svg and x11extras are installed. If they are missing cmake configures the project correctly but build fails with
```
Project ERROR: Unknown module(s) in QT: svg x11extras
qrenderdoc/CMakeFiles/build-qrenderdoc.dir/build.make:61: recipe for target 'qrenderdoc/QRenderDoc' failed
make[2]: *** [qrenderdoc/QRenderDoc] Error 3
```

Installing `libqt5svg5-dev` and `libqt5x11extras5-dev` packages fixed it but it would be nice to know at cmake time.

## Environment

* RenderDoc 1.0
* Operating System: Debian Linux Stable

**Comment by baldurk** [comment]
This is the same kind of issue as #907. The CMake project doesn't check Qt dependencies because of the way the build forwards to qmake for the Qt build. There were issues in the past with checking independently in cmake and qmake because the detection might not match up in both cases, especially if someone is using a custom qmake.
