### ISSUE TITLE
Insane memory usage after opening D3D11 capture in v1.0

### ISSUE THREAD

**Issue by Gaktan** [baldurk/renderdoc#924]
## Description

Renderdoc is using an insane amount of memory when opening a capture made in v1.0

## Repro steps

1. Build your D3D11 app with Renderdoc's API
2. Press Print Screen to trigger a capture
3. Click "Attach to Instance" and open capture
4. Notice memory increase while Renderdoc is opening the capture
5. Sometimes Renderdoc completely freezes

I should also mention that this bug is not a 100% repro, but probably around 25% in my case

## Environment

* RenderDoc build: v1.0
* Operating System: Windows 10
* API: D3D11

This bug happened on two different computers with two completely different captures of the same app.
Note that I also have a huge amount of virtual memory on both machines (between 32GB and 45GB)

**Comment by baldurk** [comment]
Can you give more details about your repro case? Generally renderdoc's memory consumption is proportional to the size of the capture, which is proportional to general GPU memory use.

I've not noticed any case in my testing where memory use is higher than I'd expect, so it sounds like you're hitting a bug which is specific to certain circumstances. Can you share a capture or application that reproduces this behaviour, even only some of the time?

**Comment by Gaktan** [comment]
Sadly I won't be able to share the app or a capture with you. 

I can however share the statistics generated by Renderdoc:
https://pastebin.com/2aJjDSHS

Indeed it looks like the Grand total GPU buffer + texture load is 7451.34 MB

Which is quite a lot, but doesn't explain why Renderdoc was using up to 10GB of memory.

This issue didn't exist at all before v1.0

Let me know if there is anything I could share with you other than the capture itself or the app

**Comment by baldurk** [comment]
If it just needed that amount of memory then I'd expect to repro 100% of the time on the same capture, that it's inconsistent suggests something is going out of wack somewhere. In particular I see that even though the total GPU load was 7.5GB the actual capture was only 400MB suggesting most of those RTs are just being cleared and no data was actually stored for them. Unfortunately a lot of things changed between v0.x and v1.0 so that alone doesn't narrow it down enough.

If you can paste/upload the diagnostic log, that might shed some light. Are you able to build RenderDoc locally and identify the callstacks where most of the allocations are coming from? I could make you a build that adds debug logs but without any more knowledge I'd have to cast a wide net. I'm flying out to GDC soon so I won't have time to do any work on this until later in the month, but I can interpret any findings you post.

**Comment by Gaktan** [comment]
Sorry, maybe I didn't make myself clear. I can repro 100% with the same capture, although it doesn't happen for all the captures I make (about 25% of the captures I made had the issue)
Does Renderdoc "create" a new RT in for every drawcall? Because I am pretty sure my app doesn't have 1031 RTs since the capture only had about 1351 drawcalls

The info I gave you actually come from a capture that didn't have the issue, since I am totally unable to open the faulty capture since it takes so much memory, and time loading.
I never built Renderdoc locally but yes I believe that a special build with debug logs is the best way to identify the issue. I saved the faulty capture on my side so I could easily test this in the future

**Comment by baldurk** [comment]
OK I follow what you mean now. RenderDoc only creates RTs that existed at capture time, and those stats correspond to objects that the application created only, so this seems like maybe figuring out why your captures have so many RT textures would shed light on why other captures are failing. Assuming the other captures just have a more extreme example of this.

When you open that capture that does work, can you look and see in the texture list what the render targets are, and identify which ones shouldn't be there according to what your program is doing? I can't be any more specific than that without seeing the capture or knowing what should be there and what shouldn't be.

Also when you capture, do you have the "Ref All Resources" option enabled? By default RenderDoc only includes objects that are needed for the captured frame, but with that option enabled it includes all objects that are alive. I wonder if there's a refcounting issue that's keeping render targets alive longer than they should, and then they're being pulled in pointlessly.

**Comment by Gaktan** [comment]
Hi, sorry about the delay.

I am using the API and I believe that "Ref All Resources" is disabled by default, so it wasn't enabled during my capture.

I did have a look at the texture list and it seems like there hundreds more 2D Depth targets than needed, as well as Depth Stencil Views. According to RenderDoc, these are never used. But the type and dimensions are all the same (Format DXGI_FORMAT_R32G8X24_TYPELESS, 1213x532). They are the same size as the screen.
(This happens on a a sane capture and the memory consumption was about 262MB, so about the same size as the capture file)

Is there a way to see the resource list from a capture without opening it in RenderDoc?

edit: I actually have a machine with a lot of ram so maybe I can try opening the capture on this one

**Comment by Gaktan** [comment]
I managed to open the capture with a PC with a lot of RAM and what I found the a sane capture is also true in this one but to the extreme:

https://pastebin.com/mRaG4nhr

`2773 RTs - 19335.62 MB.`

I can also see in the Resource inspector that there are way more 2D Depth targets and Depth Stencil Views. than I mentioned previously.
Also important to note that there are way more RTs than there are drawcalls

**Comment by Gaktan** [comment]
I noticed something odd when looking at the ouput of my program. Renderdoc is spitting out a bunch of errors, I don't know if it's related or useful in any way. But here it is:

https://pastebin.com/CL2VB1qX

**Comment by baldurk** [comment]
The E_INVALIDARG messages can probably be ignored - that likely just means you're not running on FL11 hardware and can't create those shaders that require SM5.

The rest of the messages though suggest something very strange is going on with refcounting. Are you expecting to recreate the D3D11 device many many times over? Some of those messages are from the D3D11 device destructor, and that snippet is only covering a few seconds. Normally the D3D11 device can only be destroyed when all resources have been released, so having some resources left behind suggests there's more going on there.

I will get a debug logging branch to you soon (with more logging given this recent data), but probably tomorrow at this rate since I've only just started working again after GDC & GDC plague recovery, and I spent most of today catching up on other bug reports and emails I had to deal with.

**Comment by Gaktan** [comment]
Yes I am pretty sure that D3D11CreateDevice is only called once, right after initializing Renderdoc. So yes, this is very strange indeed

**Comment by baldurk** [comment]
Hey I've created a branch [issue924logging](https://github.com/baldurk/renderdoc/tree/issue924logging) with an initial set of log prints, we might need to run these and get information and then diagnose further. Can you build and run this against your program and then paste the output log? It might run quite slow since it has logging of the refcounting for the above device behaviour.

It doesn't necessarily need to be a full case, anything that will show off the bloat of unnecessary textures will do, since even in a 'manageable' case it may be still showing the same problem.

**Comment by Gaktan** [comment]
Hi, 

I did a capture with the issue924logging branch and it generated a very big log file (16000 lines even after cropping).
I also noticed that renderdoc was logging even when not triggering a capture. I tried to crop the file so that you only have logging right before and after the capture.

[rdoc_log.txt](https://github.com/baldurk/renderdoc/files/1880677/rdoc_log.txt)

**Comment by baldurk** [comment]
Yes the idea of adding the logging is to get information from beyond just the captured frame. The log may be large but if you zip it then it should compress heavily since it's very repetitive. Apart from editing out any sensitive information though please post the whole log, since the information required might not just be around the capture.

None of the spam you pasted before seems to be in here, although without seeing the whole log it's unclear where it would appear. From the log it appears you are indeed creating a lot of depth-stencil textures (at least in the 6 second period that the log spans, you create 5 such textures).

I've updated the branch to remove the refcounting logging (which should help reduce the spam) and add more logging about why the textures are being included. Could you run again and post the whole log, and then also look at the resulting capture and tell me the ID numbers of which textures shouldn't have been there?

**Comment by Gaktan** [comment]
Here is the log file from the start of the application, up until the end:

[rdoc_log.txt](https://github.com/baldurk/renderdoc/files/1883216/rdoc_log.txt)

Looking through the capture, I see a lot of depth buffers in the Resource inspector and it looks like most of them are never used. It is difficult to look through each buffer but I can tell for sure that the only one used for sure is **2D Depth Target 29182**, which is related to **Depth stencil view 29184**

Any other Depth Target _probably_ should not have been there

**Comment by baldurk** [comment]
OK I think I found the problem from that log. Basically a combination of factors meant that RTVs/DSVs bound on deferred contexts would 'stack up' so that a capture would include *all* of them that were ever bound on that deferred context previously. Combined with the application creating a huge number meant that every previous target was being included in unnecessarily.

With that commit it should now behave correctly, only pulling in the views that were bound  for the actual commands recorded. Please check this out either with a local build or the next nightly, and let me know if it's working for you now.

**Comment by Gaktan** [comment]
Hey, I tested a few captures and I don't see a ton of Depth Targets. Your fix seems to be working correctly, I wasn't able to reproduce the original issue with it.

I will let you know if we ever see the issue again, but everything looks clear for now, so I will close this bug.
Thanks for the quick response!
