### ISSUE TITLE
Pipeline state does not show the UAV in CS in the D3D12ExecuteIndirect sample

### ISSUE THREAD

**Issue by Ashalah** [baldurk/renderdoc#926]
## Description

In the D3DExecuteIndirect sample, there is one compute shader that outputs to a UAV, but this resource does not show up in a capture in the CS pipeline state.

## Repro steps

Download the D3D12ExecuteIndirect sample, build with VS2017, run and capture a frame. There is only one dispatch to look at. I've attached a capture file.

## Environment

* RenderDoc build: 1.0
* Operating System: Windows 10
* API: D3D12
* GPU: RX 560, 18.2.2 driver

[missing_uav.zip](https://github.com/baldurk/renderdoc/files/1827289/missing_uav.zip)

**Comment by vk2gpu** [comment]
I've seen the same issue with the PS stage. Hadn't gotten round to reporting it (hadn't confirmed if it was just a bug in my code), but will try get a capture up for it.

**Comment by baldurk** [comment]
Thanks for the report! Fixed these issues I believe, it should now work correctly on both CS and PS stages (all stages were affected the same way).

**Comment by Ashalah** [comment]
Thanks! Btw you marked it as unresolved for some reason.

**Comment by baldurk** [comment]
Yeh I mark issues as unresolved if they're waiting for me to look at (as opposed to where I'm waiting for more info to act on). I now close issues when I upload a fix rather than changing the status and waiting for the reporter, since that tended to leave a lot of issues in limbo. But I've not bothered changing the tags to 'resolved' or something when I close the issue, as it's kind of useless to generate noise and add extra process for me to remember.

Hopefully at some point github will have a simple open/need more info/closed status so I don't have to abuse tags this way.

**Comment by Ashalah** [comment]
Oh! Thanks for explaining :)
