### ISSUE TITLE
No overlay / capture key does nothing

### ISSUE THREAD

**Issue by caveman250** [baldurk/renderdoc#940]
I have tried launching multiple programs on both my home and work computers through renderdoc including both my own vulkan renderer and a bunch of 3rd party games in steam. I have also tried attaching renderdoc to running instances of each program aswell. 

As far as i can tell just nothing is happening, no overlay, no functionality when pressing the capture keys, renderdoc says it is connected in the gui but that's it. The only time i see the in game overlay is when trying to launch old OpenGL applications where it tells me that the application isn't supported.

Are there prerequisites to using this program that i am missing? the documentation makes it look like i should just be able to launch a game through renderdoc and start capturing.

## Environment

* RenderDoc build: v1.0 x64
* Operating System: Windows 10 x64
* API: Vulkan, D3D11, OpenGL

**Comment by baldurk** [comment]
Sorry this got missed, somehow I didn't get an email notification.

Yes, RenderDoc should work as long as you launch the program directly through the UI. Injecting into a running program is generally more difficult and comes with gotchas so it's not recommended unless you're sure that's what you need.

Note that in cases such as running games on steam there could be issues of DRM, launcher processes and other complications. This is explicitly **not** supported, so if you have any problems I cannot help with that, however it should work fine with your own programs.

The only thing you'd need to be aware of with Vulkan is that the layer must be registered. If you ran the windows installer this would happen automatically, otherwise you'll see a message like this on the capture dialog:

![image](https://user-images.githubusercontent.com/661798/38735509-db52cc84-3f20-11e8-9807-b585fa6bf016.png)

And clicking on that will prompt you to fix the registration. For all other APIs it should work out of the box.

To investigate I'd need more information - can you upload or paste into a gist the diagnostic log (you can get this through help -> view diagnostic log) after launching one of your programs through RenderDoc.

**Comment by caveman250** [comment]
I wasn't adding the vulkan layer oops! works fine now, thank you so much.
