### ISSUE TITLE
Renderdoc crashes when trying to replay/open the captured scene on ubuntu

### ISSUE THREAD

**Issue by kenchen3000** [baldurk/renderdoc#942]
## Description
I recently added a 2d display feature and found out it breaks renderdoc. I can capture it, but it crashes when open the captured scene.
The log in the terminal window shows:
Warning - Required VK Extension 'VK_AMD_gpa_interface' is not enabled.
Warning - Unable to initialize Vulkan entrypoints.
Warning - Required VK Extension 'VK_AMD_gpa_interface' is not enabled.
Warning - Unable to initialize Vulkan entrypoints.
Warning - Cannot identify graphics hardware.
Warning - Open context for counters failed. Driver Not Supported
Warning - Capture may be missing reference to VkRenderPass resource.
Warning - Capture may be missing reference to VkFramebuffer resource.
Segmentation fault

PS: I got the first 6 lines of warning all the time, even when the replay works.
The last 2 lines of warning and segmentation fault is new and only happens when there is a crash.

Any help will be appreciated.

## Repro steps
press f12, click the captured image, double click mouse button, crashes

## Environment

* RenderDoc build:  v1.0.
* Ubuntu Linux.
* API: Vulkan.

**Comment by baldurk** [comment]
Thanks for the report. Unfortunately without being able to run your application I can't reproduce your bug, this isn't a general problem that will happen on any program, it is something specific to your application.

If you can't share a copy of your program to run, since you mention that you've made changes that trigger it could you give me more details about what those changes are? Those messages about missing references to resources can certainly be fatal a lot of the time, and they are most commonly caused by the application deleting vulkan objects too early before they're finished being used. If you run the latest vulkan validation layers, do they find any problems with your program?

**Comment by kenchen3000** [comment]
thanks that's helpful. found out that i was creating fbo every frame and fixing it makes renderdoc works again.

**Comment by baldurk** [comment]
Glad you got it sorted out, indeed if you run into any problems with RenderDoc while using Vulkan (or any API) it's best to make sure you don't have any errors caught in the validation first.
