### ISSUE TITLE
App crashes on QueryInterface for ID3D11InfoQueue

### ISSUE THREAD

**Issue by Valdiralita** [baldurk/renderdoc#946]
## Description

Application started through RenderDoc crashes with "0x80004002 E_NOINTERFACE/No such interface supported" when requesting a ID3D11InfoQueue.
Removing the calls to query the InfoQueue will allow the application under test to continue working as expected.
Note: This will create a 4GB RenderDoc logfile filled with \0.

## Repro steps

Start application through RenderDoc.
Create D3D11Device of type D3D_DRIVER_TYPE_HARDWARE with D3D11_CREATE_DEVICE_DEBUG flag.
Query for ID3D11Debug.
Query for ID3D11InfoQueue -> E_NOINTERFACE

```
var device = new Device(DriverType.Hardware, DeviceCreationFlags.Debug);
var d3DDebug = device.QueryInterface<SharpDX.Direct3D11.DeviceDebug>();
var d3DInfoQueue = d3DDebug.QueryInterface<SharpDX.Direct3D11.InfoQueue>();
```

## Environment

* RenderDoc v1.0 x64
* Operating System: Windows 10 1709
* API: D3D11 (SharpDX)

**Comment by baldurk** [comment]
The problem with `QueryInterface` is that nowhere is it documented which interfaces can be queried from which other interfaces, and it's not necessarily always true that you can always query any interface from any other interface.

In this case it would work if you queried the `ID3D11InfoQueue` directly from the `ID3D11Device`, which is what I've always seen in the past, I didn't realise you could also query it from `ID3D11Debug`. It's easy enough to add but I have to do this reactively.

For what it's worth, `E_NOINTERFACE` is not a fatal error. In this case it's caused by RenderDoc removing the DEBUG flag and so the D3D runtime doesn't return an info queue. Normally renderdoc steps in and returns a dummy interface that does nothing to make it invisible to the application.

> Note: This will create a 4GB RenderDoc logfile filled with \0.

I've fixed this problem partially - it was caused by an error code being interpreted as a file length. However I haven't been able to reproduce the problem myself so I don't know why the error code is happening. If you have a reliable case where this happens with your crash, can you share the application with me so I can test it and try to fix the underlying problem?

**Comment by Valdiralita** [comment]
Querying the ID3D11InfoQueue directly from the ID3D11Device seems to work as expected.
I can't reproduce the problem with RenderDoc crashing and creating a 4GB logfile when I compile 1.0 or 1.x myself (Development and Release). Also I can't reproduce it with a testapplication.

EDIT: using the API it even tells me what the problem is:
RDOC 017384: [14:28:50]     d3d11_device.cpp( 610) - Warning - Returning a dummy ID3D11Debug that does nothing. This ID3D11Debug will not work!

**Comment by baldurk** [comment]
As discussed I fixed it so the query will work from either interface now.
