### ISSUE TITLE
Vulkan: Storage buffer visualization redundantly repeats the first fields with garbage data

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#948]
This is with Vulkan. 

I have a storage buffer that looks like this:

```
struct Object {
	int type; int material; float radius; int pad2;
	vec4 pos;
};
layout (binding = 3) buffer Scene {
	int objectCount;
	int materialCount;
	int pixelWidth;
	int pixelHeight;
	vec4 skyColor1;
	vec4 skyColor2;
	int frameCount;
	int a;
	int b;
	int c;
	Object objects[];
};
```

GLSL storage buffers have a set of base data (everything up to and including "c") and then a variable-sized array, in this case objects. RenderDoc visualizes this as if every item in the variable-sized array also has all the base fields, but initialized with garbage (like pixelWidth):

![buffer_storage_bad](https://user-images.githubusercontent.com/130929/38418227-d73b63de-399b-11e8-9670-aa0a7388fb2b.PNG)

Would be nice to split the table up into two parts, where one is the base structure, and the rest contains only the Object struct.

**Comment by baldurk** [comment]
This is a bug, I'll try and set up a local repro to see what's going on.

What's supposed to happen is that while generating the format string, it lists the non-repeating variables (the base data you're talking about) as commented out, saying `// members skipped as they are fixed size:` and then lists the structure of the repeated variable.

I'm not sure it's feasible to have this view set up to display *both* types of data. Instead it's the kind of thing where you could manually uncomment those variables if you wanted, to see the first row. Not ideal really but the view is set up for viewing repeated data - the constant buffer viewer is more the style for viewing non-repeated data but it's hard to untangle from a buffer containing both and have it not end up as a complete mess to look at for both.

**Comment by hrydgard** [comment]
If you want to, I can get you access to my code, it's not particularly secret. But should be trivial to repro.

Regarding presentation, I was thinking to keep the table for the repeated data, and maybe just dump the base struct as something like this to a multiline text box beside it:
```
objectCount: 2
materialCount: 5
pixelWidth: 800
(etc...)
```

**Comment by baldurk** [comment]
If you're able to share a repro privately or not that would definitely help, but like you say hopefully it's not too specific to your case and I can repro it with an artificial sample.

I don't think it's reasonable to add an extra text-box into the view, since for one thing it would then be inconsistent if you couldn't edit the format and you start to have two related but independent views of the data. The existing viewer for constant buffers is pretty much what you want for viewing that part of the data.

Fundamentally the final runtime array is a different layout of data to the initial fixed data, so the existing buffer viewer is a tuned well for being a viewer of AoS data but not of a fixed set, likewise the constant buffer view is tuned well for being a viewer of fixed data but not large arrays. There maybe needs to be some way of opening one or the other depending on how you want to view the data, although that's not really ideal either.

**Comment by hrydgard** [comment]
E-mailed you a repro. (in it, there's a bug causing the buffers to be too large and filled with zeroes after the data, but that shouldn't matter).

Alright, I didn't realize how the Buffer Format textbox was intended to be used. It indeed outputs the line ```// members skipped as they are fixed size:``` but none of the fields after that are actually commented out.

Being able to switch to the constant buffer viewer for that first data would be nice, yeah.

**Comment by baldurk** [comment]
Yes the buffer format is pre-populated with data from the pipeline where possible, but generally it's completely customisable which can be useful if configuration is wrong or missing, or you suspect the data was packed incorrectly and want to view it in another way.

On looking again at the code I'm blind apparently, it looks like indeed it's as simple as the members that are supposed to be skipped aren't generated commented out. That commit should actually comment them out now.
