### ISSUE TITLE
Open letter: Thank you for your responsible analytics!

### ISSUE THREAD

**Issue by jpouellet** [baldurk/renderdoc#949]
Dear Baldur Karlsson and contributors,

I just wanted to write you to let you know how much I appreciate how transparent and responsible you are with your collection of analytics in [RenderDoc](https://renderdoc.org/). I am often frustrated by today's pervasive culture of "silently collect all the things, because one day some of it might be valuable", and you are a shining example of the exact opposite!

Specifically, I really appreciate the following:
- you make it obvious that analytics are being collected (instead of silently collecting by default and not clearly notifying the user)
- you allow users to trivially opt out (instead of hiding an opt-out deep in some obscure menu, or not being able to at all)
- you only collect things which have clear utility to you as the developer (instead of collecting as much as possible because "why not? it's easy!")
- you explain exactly what is being collected, with reader-friendly types and descriptions (instead of "data to help us serve you better" or equivalently vague nonsense)
- you report the minimum necessary to still gain the insights desired without the inadvertent introduction of oracles into user behavior. Specifically, I appreciate your reporting of "did the user do X" rather than "how many times did the user do X" or "timestamp of the user's first/last use of X" or such.
- you integrate functionality to allow users to easily review the report before it's submitted
- and of course, it's all open source (and I did briefly skim your reporting code<sup>[1]</sup>)

...and as if that weren't enough, you publish the [aggregated results for all to see](https://renderdoc.org/analytics)!

I feel that you respect my privacy as a fellow human and user of your software, and for the first time in my life I am happy to opt-in. I hope the data is useful to you :)

Whenever I complain about over-collection of data, I can now point to you as a shining example of how to collect useful information while still respecting users' privacy.

Hopefully the GDPR will encourage more to be like you, but I won't hold my breath. Here in the US you are unfortunately an outlier.

Sincerely,
Jean-Philippe

For posterity and context for others, here is what you are currently greeted with on 1st launch of RenderDoc:
![responsible-analytics](https://user-images.githubusercontent.com/1231207/38452783-0ae2713c-3a19-11e8-8ca2-763222601e00.png)
and an archive.org link to your [published aggregate data](https://web.archive.org/web/20180407080647/https://renderdoc.org/analytics) as of the time of this writing.

@baldurk: Feel free to close upon reading. I'm only opening an issue because this seems like an appropriately related and visible place to put such an open letter. My intention is not to clutter your open issues :)

**Comment by jpouellet** [comment]
<sup>[1]</sup>: I'm well aware that I am necessarily implicitly trusting many things by running your software regardless. I have no interest in performing a proper audit, and you could of course be collecting whatever you like behind my back. I do not wish to detract from this letter with a tangent on security.

**Comment by baldurk** [comment]
Thanks for writing this letter, it was really pleasing to read!

Not to overly give myself complimentes, but I did make a deliberate effort to try and minimise the possible impact or concern of the analytics and I'm glad that those design decisions weren't completely lost :smile:.

I do respect people's privacy and I know what I would personally be comfortable with in an application, and it's also in my own self-interest since after all the more careful and transparent I am with data gathering and transmission, the more likely someone is to opt-in to the system (with/without manual vetting) and so I get more data to work with.

I'll close this down since as you say there's not really anything to _do_ here, but again I greatly appreciate you taking the time to write this and I hope there are others with the same sentiment!
