### ISSUE TITLE
Wrong  shader file in editor

### ISSUE THREAD

**Issue by kuon** [baldurk/renderdoc#950]
## Description

After capturing a frame in Unity3d, I am trying to edit the shader in RenderDoc. But the shader entry file is not the right one.

The Unity shader is composed of one main entry file, called `temp.hlsl` in RenderDoc, and this file includes a bunch of other files.

Now, when I try to edit the shader in RenderDoc, instead of compiling the `temp.hlsl` file, it compiles `hlslsupport.cginc` which fails as this is just an include file.

As I am not sure if this is a RenderDoc or Unity bug, I opened a question on the Unity forum too:  https://answers.unity.com/questions/1491039/cannot-edit-shader-in-renderdoc.html

## Repro steps

- Capture a frame in Unity
- Select the camera draw calls in the event box
- Go into pipeline state -> pixel shader
- Click edit
- Press F5 to compile
- The wrong file is compiled

As it is a bit unclear, I made a serie of screeshot describing the problem:

![a](https://user-images.githubusercontent.com/160200/38468933-49d46c8a-3b4d-11e8-9747-4a7d9ee78a06.png)
![b](https://user-images.githubusercontent.com/160200/38468934-49f1724e-3b4d-11e8-9ff2-c4e1ec6d5ad9.png)
![c](https://user-images.githubusercontent.com/160200/38468935-4a0bf39e-3b4d-11e8-9feb-8fae400fb690.png)

## Environment

* RenderDoc build: e.g. v1.0
* Operating System: Windows 10
* API: D3D11 (Unity 3D 2017.3.1f1)

**Comment by baldurk** [comment]
This is a renderdoc bug, or rather it's a limitation of the D3D shader format which renderdoc isn't handling well. Part of the problem here is that as far as I'm aware the D3D shader debug info gives you a list of files in alphabetically sorted order, and doesn't tell you which file was actually the "main" file, and which are just included from it.

RenderDoc tries to search through the files to see which one declared the entry point, but without being a full HLSL parser this is generally quite hard or even impossible to do correctly.

I'll take another look to see if the actual file is somehow specified, or else I might be able to fix the search to work better in this case.

**Comment by baldurk** [comment]
I believe that should sort out the problem, at least from my experimentation. I found a way to identify the main file from the D3D debug info - but it's very dubiously documented so it might not work in all cases.

The fix will be in the next nightly build.

**Comment by kuon** [comment]
This is great.

I was about to suggest supporting comment, like vim modeline:

`// renderdoc:entry`

inside the main shader file.
