### ISSUE TITLE
Q: Vulkan & renderdoc.dll

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#955]
When I load renderdoc.dll, Vulkan integration is running:
https://github.com/bkaradzic/bgfx/blob/d057700d53f50948deffd79c0bbca302d6345554/src/debug_renderdoc.cpp#L75

But none of options I set are respected:
https://github.com/bkaradzic/bgfx/blob/d057700d53f50948deffd79c0bbca302d6345554/src/debug_renderdoc.cpp#L83

Is there something different I have to do with VK to set these options?

**Comment by baldurk** [comment]
I tried to repro this but it works correctly locally for me. My steps:

1. Build bgfx, modify one of the samples to add `init.type = bgfx::RendererType::Vulkan;` to force vulkan mode.
2. Launch the example through RenderDoc.
3. As expected the overlay is hidden, F11 captures, and the captures are saved in `bgfx/examples/runtime/temp`.

Can you give more details on exactly how you're setting it up?

**Comment by bkaradzic** [comment]
I'm not launching through RenderDoc, just running example with renderdoc.dll present inside examples/runtime directory (this works for D3D11/2).

**Comment by baldurk** [comment]
I think that explains the problem then. When the vulkan loader initialises the renderdoc layer, it will load it from the installed/registered location - usually in Program Files etc.

Most likely you end up with two copies of renderdoc.dll in your process - one which you're calling into the renderdoc API, but it doesn't do anything, the other one is initialised into the vulkan stack and sets up to capture, which hasn't been configured at all. In the D3D11/12/GL case, renderdoc does all the API injection itself so it happens to work.

You should load the renderdoc.dll from the installed location where possible, I don't recommend just copying the dll around randomly.

**Comment by bkaradzic** [comment]
> You should load the renderdoc.dll from the installed location where possible, 
> I don't recommend just copying the dll around randomly.

I don't have it installed (it's located somewhere in P4). Loading from working directory makes easy to control do you load or not renderdoc.dll.

**Comment by baldurk** [comment]
Installed is used loosely here, it doesn't actually have to be the msi installer, wherever the RenderDoc build zip is extracted to works too. If it's an extracted build you will have to run the UI and on the capture screen it will prompt you to manually register the vulkan layer - the msi installer just handles this all for you.

The vulkan layer must be registered for vulkan capture to work at all, and the dll you call into through the RenderDoc API must be the same DLL. Whether you somehow make sure the path matches or you only passively look for a renderdoc.dll that's already loaded by the process instead of loading your own, that's up to you.

In the end the same thing applies, I do not recommend you copy renderdoc.dll on its own somewhere else outside the RenderDoc build. Off the top of my head I know of some minor things that will break, and I don't guarantee that it won't break more seriously in the future if I add a new dependency. It's not supported so if you want to make it work you're on your own.
