### ISSUE TITLE
Crash when launching a Qt based application through renderdoc

### ISSUE THREAD

**Issue by jonathansty** [baldurk/renderdoc#956]
## Description
When launching a Qt based application through renderdoc a warning gets logged:

` WARNING: QApplication was not created in the main() thread.`
After this warning the window shows up and as soon as any event happens ( eg focus/unfocus/mouse move) an assert is hit.

`ASSERT: "receiver->d_func()->threadData->thread == mainThread()" in file kernel\qcoreapplication.cpp, line 1146`

I'm not sure if this is due to how renderdoc launches something or I'm doing something very very wrong in my program. I've tested this with a very simple app that implements a application derived from QApplication and it till happens.

## Repro steps

1.  Create a simple Qt application
2.  Launch it through renderdoc
3. Observe the warning
4. click on the window
5. observe an assert and crash

## Environment

* RenderDoc build: v1.0
* Operating System: Windows 10
* API: Vulkan

**Comment by baldurk** [comment]
What version of Qt is this? My guess is that Qt is latching onto the first thread in the process and assuming it's the main() thread by statically initialising some values. RenderDoc injects a thread before main() which initialises itself, but obviously doesn't call into Qt.

This seems like it was changed a long time ago: https://bugreports.qt.io/browse/QTBUG-36426 / https://codereview.qt-project.org/#/c/76859/ so I wouldn't expect it to happen on newer Qts. I can look into it, but due to how renderdoc works I don't think it would be possible to avoid the need for this early thread.

**Comment by jonathansty** [comment]
I'm using Qt 5.10.1 at the moment, I'll try out a different version to see if there's a difference.

**Comment by baldurk** [comment]
Maybe Qt regressed in a recent version. My guess is this is a false positive and you should be able to ignore the assert as Qt has basically misidentified the main thread, but I don't know for sure if anything will break later...

**Comment by jonathansty** [comment]
I've tried to ignore it but the application freezes and I get this windows message box "the application stopped working".

**Comment by jonathansty** [comment]
Just to give you a small update. Turns out it wasn't the fault of either Qt or renderdoc. I had a static object getting used before the application was created. I suppose the nature of this object caused it to misidentify the main thread. Removing this fixed the renderdoc issue.
