### ISSUE TITLE
GCC 8 has many warnings

### ISSUE THREAD

**Issue by Themaister** [baldurk/renderdoc#984]
GCC 8 starts to warn about any memcpy/memset/etc usage on non-POD classes.
RenderDoc appears to use this all over the place, causing a huge number of warnings.

**Comment by baldurk** [comment]
Yeh I started looking at GCC 8 warnings when it was mentioned in #968, this one is definitely getting turned off globally since it's kind of dubious in value and very high in noise. There were some others that weren't as easy to fix or would require some non-local changes, so I put it on the backburner.

**Comment by Themaister** [comment]
Yup, I think it's mostly to warn about use with vtables and inheritance and that kind of stuff.
