### ISSUE TITLE
Launch Application not reliably updating environment variables

### ISSUE THREAD

**Issue by cmartel** [baldurk/renderdoc#989]
## Description

I'm trying to use RenderDoc to debug a Qt application targeting a few different kits. In order to avoid copying DLLs around, I just add the required Qt path to PATH when running the executable.

But setting environment variables in RenderDoc's Launch Application window doesn't always seem to take hold, and the application fails to start because it doesn't find the DLLs. I tried adding different environment variables and then querying them, to no avail.

If I do copy Qt DLLs alongside the test application, it starts up properly and the environment variables appear to be getting set. So it's a bit of a chicken and egg problem as the app won't start if the environment variable isn't getting set, and the environment variable doesn't seem to get set unless the program started correctly.

What's weird is that sometimes the environment variable does seem to "stick" without Qt DLLs alongside the application, but I can't narrow down a reliable repro for this.

[QuickTest.zip](https://github.com/baldurk/renderdoc/files/2014807/QuickTest.zip)

This might be specific to Qt Quick, but it happens with a fresh empty Quick project.

## Repro steps

1. Add a TEST_ENV variable to RenderDoc's launch application settings
2. Launch application
3. (Optional) Copy Qt DLLs alongside application
4. From application, query environment variable

## Environment

* RenderDoc build: v1.0 and 2018-05-16 nightly
* Operating System: Windows 10
* Qt: 5.10.1

**Comment by baldurk** [comment]
I can explain the behaviour - because of other reasons (e.g. injecting into processes and the global hooking) RenderDoc applies environment variable changes immediately after it's injected, before the process starts running.

Normally that's fine as they're changed before any code runs, but it does mean that it fails in this particular case because PATH needs to be set as the process is loading so it can find DLLs.

I can probably add two ways to set the environment - one if starting the process, and one if injecting, then it should be set for startup. In the meantime a workaround is just to set the PATH manually before launching renderdoc and then it will be inherited by any processes renderdoc launches.

**Comment by cmartel** [comment]
Ah, that makes sense. I was hoping to avoid explicitly setting the path to swap between kits more easily, but that shouldn't be as necessary while using RenderDoc than when debugging Qt proper, so it's a good enough workaround in the meantime.

**Comment by baldurk** [comment]
When launching a program directly now it should modify the environment variables before launch rather than after - which should allow `PATH` modifications to work fine.
