### ISSUE TITLE
[Android] Invalid texture format gets converted to valid texture format by RenderDoc?

### ISSUE THREAD

**Issue by FelixK15** [baldurk/renderdoc#990]
## Description

We had some graphical issues (texture samples were black) in a mobile app on Android using OpenGL ES 3.0 - we could narrow the issue down to an invalid texture format when calling glTexImage2D.

When we started the app wihout attaching RenderDoc, the texture samples were all black. However, when we started the app with RenderDoc attached, the texture samples had the correct values.

This was somewhat irritating at first and I'm not exactly sure if this is a feature or a 'bug' on RenderDoc's part ;)

If this is part of the featureset of RenderDoc, maybe it would be beneficial for the user to indicate that the format of the texture was changed internally so that the user knows that something with the provided texture format was invalid?

## Repro steps

Create a OpenGL texture with an invalid texture format.
(I'll provide the same format that we used when we were experiencing the texture sampling issues)

1. create a new texture
2. upload texture data using glTexImage2D with the following parameter: internalFormat=**GL_SRGB8_ALPHA8**
sourceFormat=**GL_RGBA**
sourceType=**GL_UNSIGNED_SHORT_5_5_5_1**
3. issue a drawcall which uses this texture

When RenderDoc was not attached, this resulted in vec4(0, 0, 0, 0) values when sampling the texture. When RenderDoch was attached however, the internalFormat parameter was changed to GL_RGB5_A1 (presumably by RenderDoc) thus resulting in a correctly rendered image (as this was actually the format of the texture provided).

## Environment

* RenderDoc build: v1.1 (built from d90d1d81)
* Operating System: Windows 7
* API: OpenGL ES 3.0
* Device: Samsung Galaxy S8
* Android Version: 8.0.0

I'll happily provide more informations, in case you need them.

**Comment by baldurk** [comment]
I think this is an unintentional side-effect. The spec is a bit convoluted in this area but I *believe* you are allowed to specify whatever format/type combination you want, and it will get converted to the specified internalformat through up or downcasting. There might be some restriction like you need to have the same number of components, I'm not sure.

RenderDoc is accidentally replacing it with GL_RGB5_A1 when trying to convert unsized internal formats into sized internal formats, when it shouldn't change an already sized format.

Note though that in general RenderDoc isn't intended to support programs that have OpenGL errors in them, since that would be an unbounded amount of work to detect and report errors.

**Comment by tabikati** [comment]
We have reproduced this problem with a Linux desktop application. 

When the _internalFormat_ is converted to sized _internalFormat_, it checks the _type_ parameter first and it returns immediatelly with **eGL_RGB5_A1** if the _type_ is **eGL_UNSIGNED_SHORT_5_5_5_1**.
Would it be a good fix if we checked the _internalFormat_ first or we could provide a Warning to the user that not the correct format-type pair is used in this case?

**Comment by baldurk** [comment]
No like I say I don't believe it's an error to specify a different internalformat than the type/format parameters. At least I don't see anything in the spec that prevents it.

The check inside `GetSizedFormat` is just too aggressive, it should only do that short-circuit if the internalformat is unsized. I've moved it down below the next switch, so it will only apply in the unsized case.
