### ISSUE TITLE
How to capture more than one frame?

### ISSUE THREAD

**Issue by guwangfeng** [baldurk/renderdoc#995]
Hi,

I tried "Capture 2 Sequential Frames" option, but seems RenderDoc just captured two adjacent frames into two capture files.

I wondering is it possible to capture more than one frames into a RenderDoc capture file? Because if more than one frames (for example: two frames) are captured into one capture file, then I can do:
1. Use the first frame to create all resources (buffers/images/...) and do warm-up rendering.
2. As almost all resources are created and initialized in the first frame, I assume that there are only rendering operations in the second frame. Then if I insert performance counter queries in the second frame, the got performance result may be stable, compared with just inserting counter in the first frame.

**Comment by baldurk** [comment]
Yes this is a deliberate choice, captures are intended to only contain one frame. The option to capture sequential frames is there to be able to capture bugs that happen every-other-frame or similar. It's worth noting though that the definition of a 'frame' is flexible - if you use the in-application API to control capture from your program, the start and end points are are arbitrary.

I'm not sure I understand your motivating example though. In your example why can't you just capture the second frame, since that's all you're interested in? Combining more frames into a single capture only makes your job harder rather than easier, because you need to deliberately exclude some counter results that come from the first frame.

Also remember that RenderDoc is not a profiler and isn't intended to support profiling use-cases. Any limitation there is in this regard is likely not going to be addressed in the near future.

**Comment by guwangfeng** [comment]
if you use the in-application API to control capture from your program, the start and end points are are arbitrary.
=>
Yes, seems currently in RenderDoc, the frame boundary is vkQueuePresent. If possible, in order to capture more than one frames,  the most easiest way is to tell RenderDoc to end capture after N vkQueuePresent calls instead of one vkQueuePresent call, right? If it's true and easy to implement, seems there is no reason to disable the multiple-frame capture feature. Just an option needs to be provided in the "Launch Application" panel and check if N vkQueuePresent is called after capture is triggered.

The motivation I need to capture several frames is that if just one frame is captured, then a lot of resource creation/initialization is done in the frame (I studied the exported xml file format, most chunks are for creation/initialization purpose). I expect to get the performance counters from a frame which just consists of render APIs. And as I wrote in my first text, I expect the first frame to warm up the graphics pipeline (for example: cache).

I didn't plan to do it inside RenderDoc itself, rather, I expect to convert the xml file to source file, then I can insert performance counter APIs for each draw.

**Comment by baldurk** [comment]
There are more UI complexities than you describe, but leaving that aside the main reason I don't plan to add this is because it opens a can of worms that currently I'm not interested in supporting. The intended use-case of RenderDoc is single frame capture and if you allow many frames to be captured at once then that's a promise that people can expect it to work reliably in all cases. There are various limitations and scaling problems that would be come apparent with huge multi-frame captures and the bugtesting and bugfixing load increases in proportion.

I'm trying to understand what you describe and what you want, but it still doesn't make sense to me. If you capture one frame, yes there are initialisation and creation chunks recorded for all of the resources used in that frame. If you capture two frames, you will have _at least as many_ chunks like that and maybe more. Since you'll still have all of the creation chunks that you did before for the first frame, but now with any extras for resources needed in the second frame.

You  say you want "a frame which just consists of render APIs" but it's not possible to have a capture with no creation chunks at all, the rendering API calls refer back to pipelines, images, command buffers, etc that need to be created in order to replay the frame. If you want to export just the rendering commands then that's easily doable, but you'll be stuck with the same problem that you can't actually run those commands without doing all of the creation you just excluded.

Can you explain precisely how being able to capture multiple frames helps you?

Also as I mentioned I do allow someone using the in-application API to capture as much work as they want in one 'frame', and then they are opting-in to extreme behaviour so it's more understandable if things break. I'm not clear why this isn't a solution for you if you do want to have multiple frames captured together.

btw, I'd recommend not using the xml directly but exporting from the structured data in the same way that the XML does. The xml representation isn't contractual and might change in future.

**Comment by guwangfeng** [comment]
What you said makes sense to me. Just one frame capture should work for me.

btw, I'd recommend not using the xml directly but exporting from the structured data in the same way that the XML does. The xml representation isn't contractual and might change in future.
=> could you tell me what the "structured data" mean here? If I want to study the captured file content, seems the exported xml file is the only way currently? Any other structured data? (Or do you mean I should parse the binary .rdc file directly?)

**Comment by baldurk** [comment]
OK cool. There are certainly cases where multiple frame capture would be useful, but it's a small niche of cases and currently is not in scope to explicitly support.

The XML is a representation of the structured data, which is just what I call the programmatic view of the .rdc file. It contains all of the chunks in a capture file in a tree in memory, that you can iterate over without needing to know how to parse an .rdc.

By default when loading a capture, RenderDoc creates an in-memory representation of the full file but with large binary buffers discarded. This is used in the UI to populate the API inspector and resource inspector views, but can also be exported to XML. Optionally you can load a capture and include the buffers - and this is what is exported to XML+ZIP.

You can access the data directly from C++ (see `xml_codec.cpp` for the XML export example) or from Python - see [`ReplayController.GetStructuredFile`](https://renderdoc.org/docs/python_api/base/main_ifaces.html#renderdoc.ReplayController.GetStructuredFile) or [`CaptureFile.GetStructuredData`](https://renderdoc.org/docs/python_api/base/main_ifaces.html#renderdoc.CaptureFile.GetStructuredData). That way you don't have to export to XML (in a format that might change) then parse.
